Repository dlang/dmd, pull requests merged in 2018-04, with the labels that each got.

#8107 refactor: split specialFunctions() out of FuncDeclaration_toObjFile()
  src/dmd/glue.d
Labels: Easy Review, Refactoring

#8108 refactor: make fieldinit an array
  src/dmd/declaration.d
  src/dmd/dscope.d
  src/dmd/expressionsem.d
  src/dmd/semantic3.d
  src/dmd/statementsem.d
Labels: Refactoring, auto-merge

#8091 Use --retry for AUTO_BOOTSTRAP=1
  src/posix.mak
Labels: 72h no objection -> merge, Continuous Integration, makefiles

#8110 add ctorflow.d - begin encapsulation of flow analysis of constructors
  src/dmd/ctorflow.d
  src/dmd/declaration.d
  src/dmd/dscope.d
  src/dmd/expressionsem.d
  src/dmd/scope.h
  src/dmd/semantic3.d
  src/dmd/statementsem.d
  src/dmd/traits.d
  src/posix.mak
  src/win32.mak
Labels: Refactoring, auto-merge

#8089 Allow passing additional DFLAGS to the DMD build
  src/posix.mak
Labels: Continuous Integration, makefiles

#8027 Fix issue 18504 - Generate unwind tables for halting functions
  src/dmd/semantic3.d
  test/runnable/b18504.d
Labels: Bug Fix, auto-merge

#8114 refactor: add Scope.detach()
  src/dmd/dscope.d
  src/dmd/traits.d
Labels: Easy Review, Refactoring, auto-merge

#8111 Fix GDC build on SemaphoreCI
  src/posix.mak
Labels: Continuous Integration

#8115 [Trivial]Fix Issue 14997 - __ctor present in error message
  src/dmd/func.d
  test/fail_compilation/fail14997.d
Labels: Bug Fix, Trivial, auto-merge

#8098 Fix Issue 18474 - Postblit not working in shared structs
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  test/compilable/test18474.d
Labels: Bug Fix, auto-merge

#8113 refactor: more use of ctorflow
  src/dmd/ctorflow.d
  src/dmd/dscope.d
  src/dmd/expressionsem.d
  src/dmd/statementsem.d
Labels: Refactoring, auto-merge

#8116 expression.d: Use foreach
  src/dmd/expression.d
  src/dmd/root/array.d
Labels: Refactoring

#8131 Remove OBJ from exported_vars.sh
  test/tools/exported_vars.sh
Labels: Trivial, auto-merge

#8118 fix Issue 18708 - Flow analysis in constructors not done correctly fo…
  src/dmd/ctorflow.d
  src/dmd/dscope.d
  src/dmd/expressionsem.d
  src/dmd/statementsem.d
  test/fail_compilation/test18708.d
Labels: Bug Fix

#8122 refactor: merge redundant super() and this() code
  src/dmd/expressionsem.d
Labels: Easy Review, Refactoring

#8130 More test documentation
  test/README.md
Labels: documentation

#8127 Fix Issue 18130 - ICE on zero-length `out` array parameter
  src/dmd/semantic3.d
  test/fail_compilation/test18130.d
Labels: Bug Fix, Easy Review, auto-merge

#8009 Issue 18594 - Replace lvalue in error messages with 'cannot modify'
  src/dmd/expression.d
  test/fail_compilation/checkimports1b.d
  test/fail_compilation/checkimports1c.d
  test/fail_compilation/diag10862.d
  test/fail_compilation/diag10926.d
  test/fail_compilation/diag12598.d
  test/fail_compilation/diag14102.d
  test/fail_compilation/diag4596.d
  test/fail_compilation/fail10299.d
  test/fail_compilation/fail13116.d
  test/fail_compilation/fail13336a.d
  test/fail_compilation/fail13336b.d
  test/fail_compilation/fail13574.d
  test/fail_compilation/fail17491.d
  test/fail_compilation/fail351.d
  test/fail_compilation/fail6795.d
  test/fail_compilation/fail9537.d
  test/fail_compilation/fail9773.d
  test/fail_compilation/fail9891.d
  test/fail_compilation/fail_arrayop2.d
  test/fail_compilation/ice10419.d
  test/fail_compilation/ice12841.d
  test/fail_compilation/ice14929.d
  test/fail_compilation/test16381.d
Labels: Diagnostic Messages, auto-merge

#8136 Port the individual test script runner to D
  .circleci/run.sh
  test/README.md
  test/run_individual_tests
  test/run_individual_tests.d
Labels: auto-merge, makefiles

#8139 add Win_32_64 mapping
  test/Makefile
Labels: auto-merge

#8145 refactor: rename noctor to inLoop
  src/dmd/aggregate.d
  src/dmd/declaration.d
  src/dmd/dscope.d
  src/dmd/expressionsem.d
  src/dmd/scope.h
  src/dmd/semantic3.d
  src/dmd/statementsem.d
Labels: auto-merge

#8149 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  semaphoreci.sh
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  src/dmd/semantic2.d
  test/compilable/test17906.d
  test/compilable/test17942.d
  test/compilable/test18645.d
  test/compilable/test18670.d
Labels: Enhancement, auto-merge

#8129 Route all tests through d_do_test
  test/Makefile
  test/tools/d_do_test.d
Labels: 72h no objection -> merge, auto-merge, makefiles

#8132 Automatically print the segtrace for segfaulting tests
  test/tools/d_do_test.d
Labels: 72h no objection -> merge, auto-merge, makefiles

#8013 fix Issue 12486 - Function returning struct isn't called if `enum` of its result is accessed
  src/dmd/typesem.d
  test/runnable/test12486.d
Labels: auto-merge

#8134 d_do_test: Move 'msc' to envData
  test/tools/d_do_test.d
Labels: Easy Review, auto-merge, makefiles

#8140 [trivial] d_do_test.d: show a warning when auto-updating the TEST_OUTPUT failed.
  test/tools/d_do_test.d
Labels: Easy Review, Trivial, auto-merge, makefiles

#8051 fix Issue 18199 - Error with lambda in struct initializer
  src/dmd/parse.d
  test/compilable/test18199.d
Labels: 72h no objection -> merge, Bug Fix, auto-merge

#8126 Fix Issue 17991 - ICE with imports without module
  src/dmd/dsymbol.d
  test/compilable/imports/test17991a/a.d
  test/compilable/imports/test17991a/package.d
  test/compilable/test17991.d
Labels: Bug Fix, Easy Review, auto-merge

#8152 use special enums for __c_long, etc. instead of special structs
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/denum.d
  src/dmd/glue.d
  src/dmd/mtype.d
  src/dmd/toctype.d
  src/dmd/typesem.d
  test/runnable/cppa.d
Labels: auto-merge

#8166 [D1] Fix misspelled comments from PR #8163
  src/mars.c
Labels: auto-merge

#8170 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
Labels: auto-merge

#7994 Fix issue 18034 - Bad codegen for OPvecfill
  src/dmd/backend/glocal.c
  test/runnable/b18034.d
Labels: Bug Fix, auto-merge

#8161 Fix Issue 18753 - chunkBy compile error causes ICE
  src/dmd/expressionsem.d
  test/fail_compilation/ice18753.d
Labels: Bug Fix, auto-merge

#8174 Fix Issue 18762 - DMD should use a unique path/filename for __stdin.o
  src/dmd/dmodule.d
Labels: Bug Fix, auto-merge

#8167 Fix Issue 18719 - Doubly-called constructor against member when using forwarding constructors
  changelog/deprecate_double_initialization.dd
  src/dmd/ctorflow.d
  src/dmd/declaration.d
  src/dmd/expressionsem.d
  test/fail_compilation/fail18719.d
Labels: Bug Fix, auto-merge

#8178 refactor: remove more shadowing declarations
  src/dmd/backend/cgxmm.c
  src/dmd/backend/cv8.c
  src/dmd/backend/gloop.c
  src/dmd/backend/gother.c
  src/dmd/backend/symbol.c
Labels: auto-merge

#8175 Fix Issue 18767 - __xtoHash memberwise hashing shouldn't just sum the member hashes
  src/dmd/clone.d
Labels: Enhancement, auto-merge

#8071 fix Issue 5227 - X ^^ FP at compile-time
  changelog/fix5227.dd
  src/dmd/builtin.d
  src/dmd/root/ctfloat.d
  src/dmd/root/ctfloat.h
  test/compilable/test5227.d
Labels: Bug Fix, auto-merge

#8153 Fix Issue 18746 - function returning empty struct isn't called if used in equality expression
  src/dmd/e2ir.d
  test/runnable/test18746.d
Labels: Bug Fix, auto-merge

#8164 Fix Issue 7443 - Better diagnostic on wrongly written static constructor
  changelog/deprecate_ctor_in_static_block.dd
  src/dmd/dsymbolsem.d
  test/fail_compilation/fail7443.d
  test/runnable/test15.d
Labels: Bug Fix, auto-merge

#8181 refactor cgelem.c cgobj.c cgsched.c remove shadow declarations
  src/dmd/backend/cgelem.c
  src/dmd/backend/cgobj.c
  src/dmd/backend/cgsched.c
Labels: auto-merge

#8180 refactor blockopt.c cgcod.c cgcv.c remove shadow declarations
  src/dmd/backend/blockopt.c
  src/dmd/backend/cgcod.c
  src/dmd/backend/cgcv.c
Labels: auto-merge

#8172 Fix issue 15574 - wrong order of link arguments
  src/dmd/link.d
  test/compilable/issue15574.sh
Labels: Bug Fix, auto-merge

#8185 Use toAlias2 instead of toAlias - follow-up on Issue 18584
  src/dmd/dsymbolsem.d
Labels: auto-merge

#8187 gflow.c: fix shadowing declarations
  src/dmd/backend/gflow.c
  src/dmd/backend/mscoffobj.c
Labels: Refactoring, auto-merge

#8190 cod3.c: fix shadowing declarations
  src/dmd/backend/cod3.c
Labels: Refactoring, auto-merge

#8188 cod2.c: fix shadowing declarations
  src/dmd/backend/cod2.c
Labels: Refactoring, auto-merge

#8186 cod1.c: fix shadowing declarations
  src/dmd/backend/cod1.c
Labels: Refactoring, auto-merge

#8168 Preserve the `__debug_line` section on macOS in the final executable
  src/dmd/backend/dwarf.c
  test/runnable/debug_info.d
Labels: auto-merge

#8148 refactor: redo CSX merge logic layout and names
  src/dmd/ctorflow.d
  src/dmd/dscope.d
Labels: auto-merge

#8192 cod4.c: fix shadowing declarations
  src/dmd/backend/cod4.c
Labels: Refactoring, auto-merge

#8191 Fix Issue 13435 - Strange error if struct is a class member and opAssign applied
  src/dmd/expressionsem.d
  test/fail_compilation/fail13435.d
  test/fail_compilation/fail302.d
Labels: Bug Fix, auto-merge

#8141 Fix Issue 18228 - this(this a){} doesn't generate postblit ctor; this(this){} does
  changelog/deprecate_this_as_param_type.dd
  src/dmd/parse.d
  test/fail_compilation/fail18228.d
Labels: Bug Fix, auto-merge

#8087 Rename potentially conflicting output files + small bash cleanup
  test/compilable/test9680.sh
  test/runnable/test13742.sh
  test/runnable/test17619.sh
  test/runnable/test18076.sh
  test/tools/sh_do_test.sh
Labels: Continuous Integration, auto-merge, makefiles

#8173 Partial fix for Issue 18472 - permit using typeid at compile-time in betterC
  src/dmd/typinf.d
  test/runnable/betterc.d
Labels: Bug Fix, Vision, auto-merge

#8196 better error message for else without if
  src/dmd/parse.d
  test/fail_compilation/test10.d
Labels: Easy Review, auto-merge

#8197 use End of File instead of EOF in messages
  src/dmd/tokens.d
  test/fail_compilation/diag10792.d
  test/fail_compilation/diag10805.d
  test/fail_compilation/diag13609b.d
  test/fail_compilation/fail207.d
  test/fail_compilation/fail246.d
  test/fail_compilation/fail247.d
  test/fail_compilation/fail265.d
  test/fail_compilation/fail315.d
  test/fail_compilation/ice8795.d
  test/fail_compilation/lexer2.d
  test/fail_compilation/lexer3.d
Labels: Easy Review, Trivial, auto-merge

#8198 Fix Issue 11742 - cannot inizialize void initialized static variable in static constructor
  src/dmd/dsymbolsem.d
  test/runnable/test42.d
Labels: Bug Fix, auto-merge

#8194 Fix Issue 18775, 12807: gently resolve alias this
  src/dmd/typesem.d
  test/compilable/test12807.d
  test/compilable/test18775.d
Labels: Bug Fix

#8202 fix spurious test failures for test18322.d
  test/tools/d_do_test.d
Labels: auto-merge

#7959 Fix Issue 17373 - traits getOverloads + multiple interface inheritan…
  src/dmd/traits.d
  test/runnable/test17373.d
Labels: Bug Fix, auto-merge

#8183 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
Labels: auto-merge

#8142 fix issue 18730 - dmd miscompiles core.bitop.bt with -O
  src/dmd/backend/cgelem.c
  src/dmd/backend/cod4.c
  test/runnable/mars1.d
Labels: Bug Fix, Enhancement, auto-merge

#8207 Improve documentation for -gx switch
  src/dmd/cli.d
Labels: Easy Review, auto-merge, documentation

#8204 Add ability to use interfaces and classes without the runtime if they only contain static members
  changelog/min_runtime_classes.dd
  src/dmd/dsymbolsem.d
  src/dmd/toobj.d
  test/compilable/minimal2.d
  test/runnable/minimal2.d
Labels: auto-merge

#8184 Optimization: Don't generate try-catch for nothrow postblits
  src/dmd/dsymbolsem.d
  test/runnable/betterc.d
  test/runnable/xpostblit.d
Labels: 72h no objection -> merge

#8211 Fix issue 18803: when failing to parse a module without errors, don't call semantic3
  src/dmd/dsymbolsem.d
  test/fail_compilation/ice18803a.d
  test/fail_compilation/ice18803b.d
Labels: Bug Fix, auto-merge
