Repository dlang/dmd, pull requests merged in 2018-11, with the labels that each got.

#8895 [dmd-cxx] Don't care about D/C++ compatibility in C++ port
  src/globals.h
Labels: C++ Port, GDC

#8900 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/cppVersions.dd
  changelog/deprecated_switch_gc.dd
  changelog/isZeroInit.dd
  changelog/mangle_cpp.dd
  changelog/pragmaLinkerDirective.dd
  changelog/reboot14246.dd
  changelog/targetinfo.dd
  src/dmd/compiler.d
  src/dmd/compiler.h
  src/dmd/errors.h
  src/dmd/func.d
  src/dmd/root/dcompat.h
  src/dmd/root/filename.h
  src/dmd/root/port.h
  test/runnable/betterc.d
Labels: Bug Fix

#8899 Fix Issue 19336 - [ICE] segfault on invalid code
  src/dmd/typesem.d
  test/fail_compilation/fail19336.d
Labels: Bug Fix, auto-merge

#8887 convert elfobj.c to free functions
  src/dmd/backend/elfobj.c
  src/dmd/backend/obj.d
Labels: D Conversion, Easy Review

#8880 prep machobj.c for conversion to D
  src/dmd/backend/machobj.c
Labels: D Conversion, auto-merge

#8876 convert mscoffobj.c to D
  src/dmd/backend/cgobj.d
  src/dmd/backend/code.d
  src/dmd/backend/mscoffobj.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8892 remove global variable refstop
  src/dmd/backend/gloop.d
Labels: Refactoring, auto-merge

#8902 Refactor aliasthis checks into functions
  src/dmd/opover.d
Labels: Easy Review, Refactoring, auto-merge

#8898 refactor cpwalk() to eliminate 2 globals
  src/dmd/backend/gother.d
Labels: Refactoring, auto-merge

#8901 remove global use in numcpelems()
  src/dmd/backend/gflow.d
Labels: Refactoring, auto-merge

#8869 Add compiler support for core.volatile.volatileLoad/Store
  src/dmd/toir.d
Labels: Bug Fix, auto-merge

#8822 Fix Issue 5973 - alias this is not considered with superclass lookup
  src/dmd/aliasthis.d
  src/dmd/expressionsem.d
  src/dmd/typesem.d
  test/compilable/test5973.d
Labels: Bug Fix, auto-merge

#8908 Fix build of the D frontend on the Hurd and KFreeBSD
  src/dmd/root/object.h
Labels: GDC, Trivial, auto-merge

#8909 Backport [C++] Allow compiling front-end with strict warnings
  src/aggregate.h
  src/aliasthis.h
  src/attrib.h
  src/declaration.h
  src/doc.h
  src/dsymbol.h
  src/enum.h
  src/import.h
  src/module.h
  src/nspace.h
  src/parse.h
  src/root/aav.h
  src/root/async.h
  src/root/object.h
  src/staticassert.h
  src/template.h
  src/version.h
Labels: C++ Port, GDC, Trivial

#8907 dmd.expression: Use align(8) for alignment of UnionExp
  src/dmd/expression.d
  src/dmd/expression.h
Labels: GDC, Trivial, auto-merge

#8904 Fix Issue 13953 - AA .remove pseudo-method doesn't work via alias this
  src/dmd/expressionsem.d
  test/compilable/test13953.d
Labels: Bug Fix, auto-merge

#8905 convert elfobj.c to D
  src/build.d
  src/dmd/backend/elfobj.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8906 fix Issue 19318 - Variables captured from outer functions not visible in debugger
  src/dmd/backend/cgcv.d
  src/dmd/backend/dcgcv.d
  src/dmd/glue.d
  src/dmd/tocvdebug.d
  src/dmd/toir.d
  test/runnable/testpdb.d
Labels: Bug Fix

#8912 [dmd-cxx] Include checkedint.h from correct relative path
  src/argtypes.c
  src/declaration.c
  src/init.c
  src/initsem.c
  src/mtype.c
  src/optimize.c
  src/root/checkedint.c
  src/root/checkedint.h
  src/statementsem.c
  src/traits.c
Labels: C++ Port, GDC, Trivial

#8914 [dmd-cxx] Backport use align(8) for alignment of UnionExp
  src/expression.h
Labels: C++ Port, GDC, Trivial

#8913 [dmd-cxx] Use rmem instead of libc for malloc/strdup
  src/dmodule.c
  src/dsymbol.c
  src/mtype.c
  src/utils.c
Labels: C++ Port, GDC, Trivial

#8916 [dmd-cxx] Backport: Don't pass null pointer as format parameter to errorSupplemental
  src/dmodule.c
Labels: C++ Port, Easy Review, GDC

#8918 [dmd-cxx] Fix C++ build for DMC/Windows
  src/cppmangle.c
  src/cppmanglewin.c
  src/e2ir.c
  src/errors.c
  src/globals.c
  src/glue.c
  src/hdrgen.c
  src/inline.c
  src/libmscoff.c
  src/libomf.c
  src/link.c
  src/mars.c
  src/mtype.c
  src/root/checkedint.c
  src/root/ctfloat.c
  src/root/dsystem.h
  src/s2ir.c
  src/scanmscoff.c
  src/scanomf.c
  src/target.c
  src/tocsym.c
  src/tocvdebug.c
  src/toobj.c
  src/unittests.c
  src/win32.mak
Labels: C++ Port, Easy Review

#8846 Fix Issue 16633 - Case where an alias this is tried before the object itself
  src/dmd/expressionsem.d
  src/dmd/opover.d
  test/runnable/aliasthis.d
Labels: Bug Fix, auto-merge

#8917 [dmd-cxx] Fix C++ build for OSX
  src/objc_glue.c
Labels: C++ Port, Easy Review

#8885 Fix Issues 16082 and 16086
  src/dmd/cli.d
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/expressionsem.d
  src/dmd/globals.d
  test/compilable/testAliasLookup.d
  test/runnable/imports/a12037.d
Labels: Bug Fix, Needs Approval

#8787 Fix issue 19278 - extern(C++, "name") doesn't accept expressions
  src/dmd/astbase.d
  src/dmd/dsymbolsem.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/nspace.d
  src/dmd/nspace.h
  src/dmd/parse.d
  test/compilable/cppmangle.d
  test/fail_compilation/cppmangle.d
  test/fail_compilation/cppmangle2.d
  test/fail_compilation/ice17074.d
Labels: Enhancement, auto-merge

#8919 C++,POSIX: Correct mangling of pointers with const
  src/dmd/cppmangle.d
  test/runnable/cpp_abi_tests.d
  test/runnable/extra-files/cpp_abi_tests.cpp
Labels: Bug Fix, auto-merge

#8738 Fix Issue 19246 - Binary literal `0b_` allowed
  changelog/deprecated_binary_literals.dd
  src/dmd/lexer.d
  test/fail_compilation/fix19246.d
Labels: Enhancement, auto-merge

#8839 Fix Issue 9274 and 11499 - is + alias this = wrong code
  src/dmd/dtemplate.d
  src/dmd/expressionsem.d
  test/compilable/test9274.d
Labels: Bug Fix, auto-merge

#8923 Tweak Lexer.decodeUTF & utf.utf_decodeWchar
  src/dmd/lexer.d
  src/dmd/utf.d
Labels: auto-merge

#8677 Fix issues 1870 and 12790: Write out string mixin code to a file for debugging purpose
  .circleci/run.sh
  changelog/debugmixins.dd
  src/dmd/cli.d
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/mars.d
  src/dmd/parse.d
  test/fail_compilation/extra-files/mixin-postscript.sh
  test/fail_compilation/mixin.d
  test/runnable/extra-files/mixin.d
  test/runnable/extra-files/mixin.mixin
  test/runnable/mixin.sh
Labels: Enhancement, auto-merge

#8924 cod1.d: whitespace formatting
  src/dmd/backend/cod1.d
Labels: auto-merge

#8722 [refactor] scopeForTemplateParameters
  src/dmd/dtemplate.d
Labels: Refactoring, auto-merge

#8920 [ddoc] Display mismatched parameter counts
  src/dmd/doc.d
  test/compilable/ddoc10236.d
  test/compilable/ddoc10236b.d
  test/fail_compilation/ddoc_18083.d
Labels: auto-merge

#8925 [Trival] Encapsulate string copy using xarraydup
  src/dmd/dsymbolsem.d
Labels: Easy Review, auto-merge

#8926 Remove duplicate builtins from std.math
  src/dmd/builtin.d
Labels: auto-merge

#8927 convert dt.c to D
  src/dmd/backend/cgen.c
  src/dmd/backend/dt.c
  src/dmd/backend/dt.d
  src/dmd/backend/dt.h
  src/dmd/backend/nteh.d
  src/dmd/backend/out.d
  src/dmd/backend/pdata.d
  src/dmd/backend/symbol.d
  src/dmd/eh.d
  src/dmd/glue.d
  src/dmd/objc_glue.d
  src/dmd/tocsym.d
  src/dmd/todt.d
  src/dmd/toobj.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8928 fix Issue 19376 - Do not generate object file from .di file passed on…
  src/dmd/dmodule.d
  src/dmd/mars.d
  src/dmd/module.h
  test/compilable/extra-files/test19376.di
  test/compilable/test19376.sh
Labels: Bug Fix

#8931 Add accidentally removed `__DragonFly__` in #8908
  src/dmd/root/object.h
Labels: auto-merge

#8883 cod3.d: fix whitespace
  src/dmd/backend/cod3.d
Labels: Easy Review, auto-merge

#8932 convert cgen.c to D
  src/dmd/backend/cgen.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8933 fix issue 19381 - capture pointer in nested function should not be called "this"
  src/dmd/func.d
  src/dmd/id.d
  test/runnable/testpdb.d
Labels: Bug Fix, auto-merge

#8934 windows 64-bit dmd: restore default target as 32-bit OMF
  src/dmd/mars.d
Labels: auto-merge

#8870 Support markdown-style backslash escapes
  res/default_ddoc_theme.ddoc
  src/dmd/cli.d
  src/dmd/doc.d
  src/dmd/globals.d
  test/compilable/ddoc_markdown_escapes.d
  test/compilable/extra-files/ddoc_markdown_escapes.html
Labels: auto-merge

#8935 merge outbuf.c into outbuf.d
  src/dmd/backend/outbuf.c
  src/dmd/backend/outbuf.d
  src/dmd/backend/outbuf.h
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8936 remove sizecheck.c
  src/dmd/backend/cc.d
  src/dmd/backend/cdef.d
  src/dmd/backend/sizecheck.c
  src/dmd/backend/type.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8937 fix Issue 19086 - Bad stack trace for exceptions
  src/dmd/backend/cod1.d
  test/runnable/test19086.d
Labels: Bug Fix, auto-merge

#8938 fix issue 7804 - Allow __traits(getMember) as a BasicType
  changelog/alias_from_trait.dd
  src/dmd/astbase.d
  src/dmd/dmangle.d
  src/dmd/dsymbolsem.d
  src/dmd/hdrgen.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/parse.d
  src/dmd/parsetimevisitor.d
  src/dmd/strictvisitor.d
  src/dmd/transitivevisitor.d
  src/dmd/typesem.d
  src/dmd/visitor.h
  test/fail_compilation/e7804_1.d
  test/runnable/e7804.d
Labels: Enhancement

#8943 remove cdef.h
  src/dmd/backend/cdef.h
  src/dmd/backend/fp.c
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion

#8947 make C's `wchar_t` a special enum
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/denum.d
  src/dmd/id.d
  test/runnable/cppa.d
  test/runnable/extra-files/cppb.cpp
Labels: auto-merge

#8949 convert os.c to D
  src/dmd/backend/os.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: auto-merge

#8834 pull common code into expressionsToString()
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  src/dmd/statement.d
Labels: Easy Review, Refactoring, auto-merge

#7867 fix Issue 18010 - Undefined reference to _d_arraycopy when copying ar…
  src/dmd/e2ir.d
  test/runnable/betterc.d
Labels: Bug Fix

#8951 Fix Issue 19393 - Structure dtor isn't called after passed to T[] argument. Memory leaks issue
  src/dmd/expressionsem.d
  test/runnable/test19393.d
Labels: Bug Fix

#8953 [dcast.d] reduce indenting
  src/dmd/dcast.d
Labels: Easy Review, Refactoring, auto-merge

#8950 Allow implicit string literal -> const(wchar_t)[]
  changelog/wchar_t.dd
  src/dmd/dcast.d
  test/compilable/implicitconv.d
Labels: auto-merge

#8956 outline `sym.getMemtype(Loc.initial)`
  src/dmd/mtype.d
Labels: Easy Review, Refactoring, Trivial, auto-merge

#8957 OutBuffer: add ability to write slices
  src/dmd/backend/cgobj.d
  src/dmd/backend/dcgcv.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/machobj.d
  src/dmd/backend/mscoffobj.d
  src/dmd/backend/outbuf.d
Labels: Easy Review, Refactoring, auto-merge

#8488 Fix Issue 18979 - Template constructor bypasses private
  src/dmd/expressionsem.d
  test/fail_compilation/fail18979.d
  test/fail_compilation/imports/imp18979.d
Labels: Bug Fix, auto-merge

#8962 [trivial] remove useless cast to RootObject
  src/dmd/dtemplate.d
Labels: Trivial, auto-merge

#8960 add backend.barray.d - encapsulate array allocations
  src/dmd/backend/barray.d
  src/dmd/backend/gflow.d
  src/dmd/backend/goh.d
  src/posix.mak
  src/win32.mak
Labels: Easy Review, Refactoring

#8965 gother.d: use Barray for assnod[]
  src/dmd/backend/barray.d
  src/dmd/backend/gother.d
Labels: Refactoring, auto-merge

#8966 remove dead variable labelarr
  src/dmd/backend/global.d
Labels: Easy Review, Refactoring, auto-merge

#8968 convert defnod[] to Barray
  src/dmd/backend/debugprint.d
  src/dmd/backend/gflow.d
  src/dmd/backend/gloop.d
  src/dmd/backend/go.d
  src/dmd/backend/goh.d
  src/dmd/backend/gother.d
Labels: Easy Review, Refactoring, auto-merge

#8970 convert expnod[] to Barray
  src/dmd/backend/gdag.d
  src/dmd/backend/gflow.d
  src/dmd/backend/go.d
  src/dmd/backend/goh.d
Labels: Easy Review, Refactoring, auto-merge

#8954 -color=on should overwrite the default detection
  changelog/color.dd
  src/dmd/cli.d
  src/dmd/console.d
  src/dmd/globals.d
  src/dmd/mars.d
  test/compilable/testcolor.sh
Labels: auto-merge

#8974 convert blkexp[] to Barray
  src/dmd/backend/gflow.d
  src/dmd/backend/go.d
  src/dmd/backend/goh.d
  src/dmd/backend/gother.d
Labels: Refactoring, auto-merge

#8978 change weights[] to Barray
  src/dmd/backend/cgreg.d
Labels: Easy Review, Refactoring, auto-merge

#8969 improve performance of Barray.setLength()
  src/dmd/backend/barray.d
Labels: Easy Review, Refactoring, auto-merge

#8977 Deprecate extern(Pascal)
  changelog/deprecated_extern_pascal.dd
  src/dmd/parse.d
Labels: Trivial, auto-merge

#8979 convert csextab[] to Barray
  src/dmd/backend/cgcod.d
  src/dmd/backend/code.d
Labels: auto-merge

#8980 change hcstab[] to Barray
  src/dmd/backend/cgcs.d
Labels: Refactoring, auto-merge

#8981 convert debtyp[] to Barray
  src/dmd/backend/dcgcv.d
Labels: Refactoring, auto-merge

#8984 convert dfo[] to Barray
  src/dmd/backend/blockopt.d
  src/dmd/backend/global.d
  src/dmd/backend/out.d
Labels: Refactoring, auto-merge

#8945 fixup for enhancement 7804 - allow __traits(getMember) as basic type
  changelog/alias_from_trait.dd
  src/dmd/astbase.d
  src/dmd/dsymbolsem.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/parse.d
  src/dmd/typesem.d
  test/fail_compilation/e7804_1.d
  test/fail_compilation/e7804_2.d
  test/runnable/e7804.d
Labels: auto-merge

#8985 refactor compdfo() to remove dependence on dfotop
  src/dmd/backend/blockopt.d
Labels: Refactoring, auto-merge

#8986 cgcs.d: whitespace reformat
  src/dmd/backend/cgcs.d
Labels: Refactoring, Trivial, auto-merge

#8034 Fix issue 15206 - SROA doesn't play well with double slices
  src/dmd/backend/gsroa.d
  test/compilable/b15206.d
Labels: Bug Fix, auto-merge

#8987 Clean up a `CallExp` constructor
  src/dmd/expression.d
Labels: Trivial, auto-merge

#8983 Fix Issue 19415 - return non-copyable struct fails if member function has return attribute
  src/dmd/mtype.d
  test/compilable/test19145.d
Labels: Bug Fix, auto-merge

#8991 convert resolve() to symbolToExp()
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/semantic3.d
  src/dmd/traits.d
  src/dmd/typesem.d
Labels: Easy Review, Refactoring, auto-merge

#8973 [Refactor] Remove unneceserray if(1) in dmd.expressionsem.functionParameters
  src/dmd/expressionsem.d
Labels: Easy Review, Refactoring, auto-merge

#8993 Fix Issue 19409 - static if (__traits(compiles, __traits(identifier, ...) )) evaluates to false even though the expression alone evaluates to true
  src/dmd/cond.d
  test/compilable/test19409.d
Labels: auto-merge

#8994 Fix Issue 19419 - [REG2.080.1] @disabled this() will print wrong error if calling non-default constructor with wrong parameters
  src/dmd/func.d
  test/fail_compilation/fail19419.d
Labels: Bug Fix, auto-merge

#8995 convert resolve() from Visitor to switch
  src/dmd/typesem.d
Labels: Easy Review, Refactoring, auto-merge

#8996 convert getProperty() from Visitor to switch
  src/dmd/typesem.d
Labels: Easy Review, Refactoring, auto-merge

#8999 [Refactoring] move `Type.resolveExp()` to typesem.d because it was actually static
  src/dmd/mtype.d
  src/dmd/typesem.d
Labels: auto-merge

#9001 simplify resolve()
  src/dmd/typesem.d
Labels: Refactoring, auto-merge

#8997 Fix issue 19163: don't count declarations in coverage analysis
  src/dmd/s2ir.d
  test/runnable/extra-files/runnable-test19163.lst
  test/runnable/test19163.d
Labels: Bug Fix, Enhancement

#9003 convert dotExp() from Visitor to switch
  src/dmd/typesem.d
Labels: Refactoring, auto-merge

#9004 [Trivial] `resolveTupleIndex()` does not need a TypeQualified parameter anymore
  src/dmd/typesem.d
Labels: Trivial, auto-merge

#9008 cover more parser errors
  test/fail_compilation/misc_parser_err_cov1.d
Labels: auto-merge

#9007 fix issue 15876 - various cases of SEGFAULT when formatting parser errors
  src/dmd/hdrgen.d
  src/dmd/parse.d
  test/fail_compilation/e15876_1.d
  test/fail_compilation/e15876_2.d
  test/fail_compilation/e15876_3.d
  test/fail_compilation/e15876_4.d
  test/fail_compilation/e15876_5.d
  test/fail_compilation/e15876_6.d
Labels: Bug Fix, auto-merge

#9011 convert usages of list_next() to ListRange
  src/dmd/backend/cgcod.d
  src/dmd/backend/cgreg.d
  src/dmd/backend/cod5.d
  src/dmd/backend/gflow.d
  src/dmd/backend/gloop.d
  src/dmd/backend/gother.d
Labels: Easy Review, Refactoring, auto-merge

#8992 fix master - TypeTrait semantic fails for non static aggregate members
  changelog/alias_from_trait.dd
  src/dmd/dsymbolsem.d
  src/dmd/mtype.d
  src/dmd/traits.d
  src/dmd/typesem.d
  test/runnable/e7804.d
Labels: auto-merge

#8712 Fix Issue 6777 - alias this disables casting for classes
  src/dmd/dcast.d
  src/dmd/mtype.d
  test/compilable/test6777.d
  test/fail_compilation/fail_casting.d
Labels: Bug Fix, auto-merge

#9019 improve loops for stagelist
  src/dmd/backend/cgsched.d
Labels: Easy Review, Refactoring, auto-merge

#9021 add isXxxxExp() functions to Expression
  src/dmd/expression.d
Labels: Refactoring, auto-merge

#9022 refactor cgreg_spillreg_prolog() and _epilog()
  src/dmd/backend/cgreg.d
Labels: Refactoring, auto-merge
