Repository dlang/dmd, pull requests merged in 2018-09, with the labels that each got.

#8627 Fix Issue 19199 - Use core.bitops intrinsics during CTFE
  src/dmd/builtin.d
Labels: Enhancement, auto-merge

#8648 expression: Remove bodies of functions that forward to free functions
  src/dmd/dcast.d
  src/dmd/dinterpret.d
  src/dmd/expression.h
  src/dmd/opover.d
  src/dmd/optimize.d
  src/tests/cxxfrontend.c
Labels: GDC, Trivial

#8661 Temporarily revert SemaphoreCI to v2.081.2
  semaphoreci.sh
Labels: auto-merge

#8662 convert global.params to params
  src/dmd/frontend.d
  src/dmd/mars.d
Labels: Easy Review, Refactoring, auto-merge

#8658 [C++] Include globals.h instead of mars.h
  src/dmd/aliasthis.h
  src/dmd/declaration.h
  src/dmd/dsymbol.h
  src/dmd/errors.h
  src/dmd/expression.h
  src/dmd/init.h
  src/dmd/scope.h
  src/dmd/tokens.h
Labels: GDC, Trivial, auto-merge

#8657 Link with clang runtime when doing coverage
  src/posix.mak
Labels: auto-merge

#8594 Fix debug build and remove debug messages
  src/dmd/backend/go.d
  src/dmd/backend/nteh.d
Labels: auto-merge

#8609 Refactor FunDecl semantic
  src/dmd/semantic3.d
Labels: auto-merge

#8593 simplify loadconst() for LDC build
  src/dmd/backend/cg87.d
  test/runnable/fldconst.d
Labels: auto-merge

#8652 Fixes Issue 19212 - Add versions for C++ runtimes.
  src/dmd/cond.d
  src/dmd/mars.d
  test/fail_compilation/reserved_version.d
  test/fail_compilation/reserved_version_switch.d
Labels: Enhancement, auto-merge

#8654 Fixes Issue 19195 - Support pragma to specify linker directives
  src/dmd/backend/cgobj.c
  src/dmd/backend/elfobj.c
  src/dmd/backend/machobj.c
  src/dmd/backend/mscoffobj.c
  src/dmd/backend/obj.d
  src/dmd/backend/obj.h
  src/dmd/dsymbolsem.d
  src/dmd/glue.d
  src/dmd/id.d
  src/dmd/statementsem.d
  src/dmd/toobj.d
  test/compilable/extra-files/header1.d
  test/compilable/extra-files/header1.di
  test/compilable/extra-files/header1i.di
  test/compilable/testheader1.d
  test/compilable/testheader1i.d
Labels: Enhancement, auto-merge

#8623 Improve diagnostic with forward references and tupleof
  src/dmd/aggregate.d
  src/dmd/typesem.d
  test/fail_compilation/diag19196.d
Labels: auto-merge

#8674 [STABLE] Temporarily revert SemaphoreCI to v2.081.2
  semaphoreci.sh
Labels: auto-merge

#8664 refactor setTargetCPU()
  src/dmd/mars.d
Labels: Easy Review, Refactoring, auto-merge

#8597 Fix Issue 19185 - [ICE] Nested struct segfaults when using variable from outer scope
  src/dmd/expressionsem.d
  test/runnable/test19185.d
Labels: Bug Fix, auto-merge

#8506 Fix Issue 19098 - Improve error for non-assignable struct
  src/dmd/expression.d
  test/fail_compilation/fail19098.d
Labels: Bug Fix, Trivial, auto-merge

#8671 refactor getenv_setargv, parse_arch_arg, parse_conf_arg
  src/dmd/mars.d
Labels: Easy Review, Refactoring, auto-merge

#8598 Fix Issue 19182 - missing semicolon crashes compiler
  src/dmd/statementsem.d
  test/fail_compilation/fail19182.d
Labels: Bug Fix, auto-merge

#8575 Turn globals.argv0 into a DArray
  src/dmd/dinifile.d
  src/dmd/frontend.d
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/identifier.d
  src/dmd/json.d
  src/dmd/link.d
  src/dmd/mars.d
  src/dmd/root/file.d
  src/dmd/root/filename.d
  src/dmd/root/filename.h
  src/dmd/utils.d
  src/posix.mak
Labels: auto-merge

#8665 Fix Issue 19209 - [ICE] Overriding a field in a baseclass issues an ICE
  src/dmd/dsymbolsem.d
  test/fail_compilation/fail19209.d
Labels: Bug Fix, auto-merge

#8660 [stable] Fix Issue 19219 - Could not CTFE with std.math.exp
  src/dmd/builtin.d
  src/dmd/root/ctfloat.d
  test/compilable/test5227.d
Labels: Bug Fix, auto-merge

#8666 Fix issue 19225 - Confusing error message on `static else`
  src/dmd/parse.d
  test/fail_compilation/diag19225.d
Labels: Bug Fix

#8583 Fix Issue 19180 - Expose dmd.mtype.Type.isZeroInit as __traits(isZeroInit, T)
  changelog/isZeroInit.dd
  src/dmd/dstruct.d
  src/dmd/id.d
  src/dmd/traits.d
  test/compilable/isZeroInit.d
  test/fail_compilation/fail_isZeroInit.d
Labels: 72h no objection -> merge, Enhancement, auto-merge

#8678 [STABLE] Switch AppVeyor to use downloads.dlang.org and v2.078.3
  appveyor.sh
  appveyor.yml
Labels: Bug Fix, auto-merge

#8680 Merge stable into master
  VERSION
  appveyor.sh
  appveyor.yml
  changelog/betterc_cmp_types.dd
  changelog/betterc_versions.dd
  changelog/cond_assign.dd
  changelog/debug-unsafe.dd
  changelog/deprecate-opDot.dd
  changelog/enum_attributes.dd
  changelog/error_for_c-style_arrays.dd
  changelog/fix19043.dd
  changelog/objc_offsetof_tupleof.dd
  changelog/osx64_long_cppmangling.dd
  changelog/uda-function-parameters.dd
  src/dmd/builtin.d
  src/dmd/root/ctfloat.d
  test/compilable/test5227.d
Labels: Bug Fix

#8683 Add changelog entries for my 2 recent PR's.
  changelog/cppVersions.dd
  changelog/pragmaLinkerDirective.dd
Labels: auto-merge

#8670 Make Identifier hold a slice internally
  src/dmd/identifier.d
  src/dmd/identifier.h
Labels: Easy Review, Trivial, auto-merge

#8681 [Trivial] Fix dragonflybsd compilation
  src/dmd/backend/cdef.d
Labels: Trivial, auto-merge

#8686 cod4.d: fix whitespace
  src/dmd/backend/cod4.d
Labels: Refactoring, Trivial

#8684 Make PR #8583 work with GDC longdouble_soft
  src/dmd/dstruct.d
Labels: auto-merge

#8675 Fix Issue 18771 - Identical overload sets in different modules have different identities
  src/dmd/traits.d
  test/compilable/imports/test18771a.d
  test/compilable/imports/test18771b.d
  test/compilable/imports/test18771c.d
  test/compilable/imports/test18771d.d
  test/compilable/test18771.d
Labels: Bug Fix, auto-merge

#8685 [REG master] Partially revert #8623
  src/dmd/aggregate.d
Labels: GDC

#8653 convert cod1.c to D
  src/dmd/backend/cod1.d
  src/dmd/backend/code.d
  src/dmd/backend/code.h
  src/dmd/backend/out.c
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, Refactoring

#8691 Mars: Split a loop into its own function
  src/dmd/mars.d
Labels: Refactoring

#8694 Remove deprecated or errored command line switches
  changelog/deprecated_switch_gc.dd
  src/dmd/mars.d
Labels: Trivial

#8695 Replace custom extension stripping with FileName.removeExt
  src/dmd/mars.d
Labels: Trivial, auto-merge

#8679 convert cod3.c to D
  src/dmd/backend/cc.d
  src/dmd/backend/cdef.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code.d
  src/dmd/backend/code.h
  src/dmd/backend/code_x86.d
  src/dmd/backend/dwarf.c
  src/dmd/backend/global.d
  src/dmd/backend/global.h
  src/dmd/backend/melf.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, Refactoring

#8689 convert cgcod.c to D
  src/build.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code.d
  src/dmd/backend/code.h
  src/dmd/backend/global.d
  src/dmd/backend/optabgen.c
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, Refactoring

#8698 fix typo in cod3.d
  src/dmd/backend/cod3.d
Labels: Trivial, auto-merge

#8656 This .editorconfig is incompatible with git on windows.
  .editorconfig
Labels: 72h no objection -> merge, auto-merge

#8700 [~regression fix] fix Issue 19248 and reopened 18957
  src/dmd/cppmangle.d
  test/compilable/cppmangle.d
  test/runnable/cpp_abi_tests.d
  test/runnable/extra-files/cpp_abi_tests.cpp
Labels: Bug Fix, auto-merge

#8706 Make mangleOverride a D slice
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dmangle.d
  src/dmd/dsymbolsem.d
Labels: auto-merge

#8702 Have issue15574.sh use $(CC) instead of hard coded 'cc'.
  test/compilable/issue15574.sh
Labels: auto-merge

#8631 Fix Issue 18955 - extern(C++) default struct mangling is overridden when interacting with a cppmangle = class template
  src/dmd/typesem.d
  test/compilable/test18955.d
Labels: Bug Fix, auto-merge

#8704 Link: Remove custom removeExt, use FileName instead
  src/dmd/link.d
Labels: Trivial, auto-merge

#8709 refactor _isZeroInit()
  src/dmd/dstruct.d
Labels: Refactoring, auto-merge

#8667 Implement better C++ name mangling feature.
  changelog/mangle_cpp.dd
  src/dmd/astbase.d
  src/dmd/identifier.d
  src/dmd/nspace.d
  src/dmd/parse.d
  test/compilable/cppmangle3.d
  test/fail_compilation/cppmangle.d
Labels: Enhancement

#8713 prep cv8.c for conversion to D
  src/dmd/backend/cv8.c
Labels: D Conversion, Easy Review

#8701 Add __CXXLIB__ special token
  changelog/mscrt_ver.dd
  src/dmd/doc.d
  src/dmd/id.d
  src/dmd/lexer.d
  test/compilable/cpp.d
Labels: Enhancement, auto-merge

#8705 Iasmdmd: Reduce usage of string, use some immutable
  src/dmd/expressionsem.d
  src/dmd/iasmdmd.d
Labels: Trivial, auto-merge

#8715 prep cgcv.c for conversion to D
  src/dmd/backend/cgcv.c
Labels: D Conversion, Easy Review, auto-merge

#8717 Fix styling of if/whilte statements.
  src/dmd/parse.d
Labels: auto-merge

#8716 Fix grammar of changelog a bit for cpp mangle update
  changelog/mangle_cpp.dd
Labels: auto-merge

#8725 Minor refactor to FileName
  src/dmd/mars.d
  src/dmd/root/filename.d
Labels: Easy Review, Refactoring

#8720 root/file.h: Align C++ headers with D sources
  src/dmd/root/file.h
Labels: GDC, Trivial, auto-merge

#8726 test/runnable: Remove references to Project Gutenberg
  test/runnable/extra-files/alice30.txt
Labels: Trivial, auto-merge

#8727 prep out.c for conversion to D
  src/dmd/backend/out.c
Labels: D Conversion, Easy Review, auto-merge

#8731 prep dwarfeh.c for D conversion
  src/dmd/backend/dwarfeh.c
Labels: D Conversion, Easy Review, auto-merge

#8732 prep dwarf.c for D conversion
  src/dmd/backend/dwarf.c
Labels: D Conversion, Easy Review, auto-merge

#8733 [C++] Remove unused #includes and forward declarations
  src/dmd/aggregate.h
  src/dmd/attrib.h
  src/dmd/cond.h
  src/dmd/declaration.h
  src/dmd/dsymbol.h
  src/dmd/enum.h
  src/dmd/errors.h
  src/dmd/expression.h
  src/dmd/hdrgen.h
  src/dmd/identifier.h
  src/dmd/import.h
  src/dmd/init.h
  src/dmd/module.h
  src/dmd/mtype.h
  src/dmd/objc.h
  src/dmd/root/filename.h
  src/dmd/root/outbuffer.h
  src/dmd/root/stringtable.h
  src/dmd/scope.h
  src/dmd/statement.h
  src/dmd/target.h
  src/dmd/template.h
Labels: GDC, Refactoring, Trivial

#8734 dmd/hdrgen: Remove HdrGenState from headers, remove C++ linkage from helper functions
  src/dmd/hdrgen.d
  src/dmd/hdrgen.h
  src/dmd/mars.d
Labels: Refactoring, Trivial, auto-merge

#8737 dmd/clone.d: Remove C++ linkage from all functions
  src/dmd/aggregate.h
  src/dmd/clone.d
  src/dmd/dsymbolsem.d
Labels: Refactoring, Trivial

#8736 dmd/arraytypes.h: #include array header instead of root
  src/dmd/arraytypes.h
Labels: Refactoring, Trivial, auto-merge

#8730 prep newman.c for conversion to D
  src/dmd/backend/newman.c
Labels: D Conversion, Easy Review, auto-merge

#8723 convert cv8.c to D, add varstats.d
  src/dmd/backend/cv8.d
  src/dmd/backend/varstats.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8741 fix issue 19266 - Some source files names are no longer accepted
  src/dmd/root/filename.d
  test/compilable/extra-files/test19266.d
  test/compilable/test19266.sh
Labels: Bug Fix, auto-merge

#8729 [stable] Fix tests for proper core.stdc.stdint aliases
  test/compilable/teststdint.d
  test/runnable/extra-files/stdint.cpp
  test/runnable/stdint.d
Labels: auto-merge

#8697 fix Issue 14246 - RAII - proper destruction of partially constructed …
  changelog/reboot14246.dd
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/cli.d
  src/dmd/clone.d
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/semantic3.d
  src/dmd/statement.d
  test/runnable/sdtor.d
Labels: Bug Fix

#8708 add test for issue 18955
  test/runnable/cppa.d
  test/runnable/extra-files/cppb.cpp
Labels: auto-merge

#8753 dmd/declaration.h: Remove FUNCFLAG macros from headers
  src/dmd/declaration.h
Labels: Trivial, auto-merge

#8752 dmd/declaration.h: Remove functionResolve and resolveFuncCall
  src/dmd/declaration.h
  src/dmd/func.d
Labels: Trivial, auto-merge

#8762 dmd.dsymbol: Remove ScopeDsymbol.dim and getNth
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
Labels: Refactoring, auto-merge

#8724 Add __traits(getTargetInfo) in favour of ___CXXLIB__
  changelog/mscrt_ver.dd
  changelog/targetinfo.dd
  src/dmd/id.d
  src/dmd/lexer.d
  src/dmd/target.d
  src/dmd/target.h
  src/dmd/traits.d
  test/compilable/cpp.d
  test/compilable/traits.d
  test/fail_compilation/traits.d
Labels: auto-merge

#8747 dmd/expression.d: Declare UnaExp as an abstract class
  src/dmd/expression.d
Labels: Trivial, auto-merge

#8754 dmd.expressionsem: Make rewriteOpAssign private to this module
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
Labels: Refactoring, auto-merge

#8766 dmd.init: Remove Initializer.arraySyntaxCopy
  src/dmd/init.d
  src/dmd/init.h
Labels: Refactoring, Trivial, auto-merge

#8751 dmd.func: Remove C++ overloadApply from source and headers
  src/dmd/declaration.h
  src/dmd/func.d
Labels: Refactoring, Trivial, auto-merge

#8755 dmd/expression.h: Remove functions and macros only used in semantic
  src/dmd/access.d
  src/dmd/aliasthis.d
  src/dmd/arrayop.d
  src/dmd/dcast.d
  src/dmd/dinterpret.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/initsem.d
  src/dmd/nogc.d
  src/dmd/opover.d
  src/dmd/sideeffect.d
  src/dmd/traits.d
Labels: Refactoring

#8775 Fix C++ headers following merge of #8724
  src/dmd/target.h
Labels: GDC, Regression, Trivial, auto-merge

#8757 dmd.imphint: Remove C++ linkage from importHint
  src/dmd/expressionsem.d
  src/dmd/imphint.d
  src/dmd/mars.h
  src/dmd/typesem.d
Labels: Refactoring, auto-merge

#8779 dmd.dmodule: Remove workaround for compilers older than 2.069
  src/dmd/dmodule.d
Labels: Trivial, auto-merge

#8772 dmd.mtype: Remove Type.error and Type.warning
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/declaration.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/typesem.d
  src/dmd/typinf.d
Labels: Refactoring, auto-merge

#8749 dmd/hdrgen.h: Move declarations of functions defined in hdrgen here
  src/dmd/dsymbol.h
  src/dmd/hdrgen.h
  src/dmd/mtype.h
Labels: Refactoring

#8748 dmd.expression: Add asserts that TOK is never an invalid value
  src/dmd/expression.d
Labels: Trivial, auto-merge
