Repository dlang/dmd, pull requests merged in 2018-06, with the labels that each got.

#8316 Forward AddrExp constructor to this instead of super
  src/dmd/expression.d
Labels: Trivial, auto-merge

#8222 Fix issue 17968 - Use typeid(Object) instead of typeid(T) to avoid pulling in unused symbols
  src/dmd/clone.d
  test/runnable/extra-files/test17968.d
  test/runnable/extra-files/test17968a.d
  test/runnable/test17968.sh
Labels: Bug Fix, auto-merge

#8286 Fix issue 18902 - -lib crashes on static libraries in the command line
  src/dmd/mars.d
  test/runnable/test18902.sh
Labels: Bug Fix, auto-merge

#8323 Remove 'deprecate this as parameter type' changelog entry
  changelog/deprecate_this_as_param_type.dd
  test/fail_compilation/fail18228.d
Labels: auto-merge

#8327 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  src/dmd/attrib.d
  src/dmd/attrib.h
  src/dmd/clone.d
  src/dmd/cond.d
  src/dmd/dinterpret.d
  src/dmd/func.d
  src/dmd/mars.d
  src/dmd/mtype.d
  test/compilable/extra-files/json.out
  test/compilable/json.d
  test/compilable/test11169.d
  test/compilable/test17819.d
  test/compilable/test18115.d
  test/compilable/test18871.d
  test/compilable/test7815.d
  test/compilable/test7886.d
  test/fail_compilation/fail11169.d
  test/fail_compilation/fail7886.d
  test/runnable/extra-files/test17968.d
  test/runnable/extra-files/test17968a.d
  test/runnable/test17968.sh
  test/runnable/test18902.sh
Labels: Bug Fix, auto-merge

#8322 convert evalu8.c to evalu8.d
  src/dmd/backend/bcomplex.d
  src/dmd/backend/evalu8.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, auto-merge

#8329 relax assert about return value from GetFullPathNameW
  src/dmd/root/filename.d
Labels: auto-merge

#8333 posix.mak: parameterize ../res
  src/posix.mak
Labels: Refactoring, Trivial, auto-merge

#8326 fix Issue 18936 - Internal error: dmd/backend/cgxmm.c 684
  src/dmd/backend/gsroa.c
  test/compilable/test18936.d
Labels: Bug Fix, auto-merge

#8335 Simplify parseAssignExp
  src/dmd/parse.d
Labels: Refactoring, Trivial, auto-merge

#8332 Fix issue 18922: No substitutions for C++ namespaces in different module/file
  src/dmd/cppmangle.d
  src/dmd/dsymbol.d
  test/compilable/cppmangle.d
  test/compilable/cppmangle2.d
Labels: Bug Fix, Vision, auto-merge

#8337 bcomplex.d: a little more functional
  src/dmd/backend/bcomplex.d
Labels: Refactoring, auto-merge

#8340 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
Labels: Bug Fix, auto-merge

#8334 Posix extern(C++) operator mangling
  changelog/mangle_operators.dd
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  test/compilable/cppmangle.d
Labels: Vision, auto-merge

#8339 Remove unused enum values from dmd.ctorflow.CSX
  src/dmd/ctorflow.d
  src/dmd/expressionsem.d
Labels: Easy Review, auto-merge

#8341 Fix issue 14178 - extern(C++) doesn't mangle 'std' correctly on posix systems
  src/dmd/cppmangle.d
  test/compilable/cppmangle.d
Labels: Bug Fix, Vision, auto-merge

#8338 Fix Issue 18951 - package static method masked by public static method in class
  src/dmd/access.d
  src/dmd/typesem.d
  test/compilable/test18951a.d
  test/compilable/test18951b.d
Labels: Bug Fix, auto-merge

#8330 fix issue 18928 - extern(C++) bad codegen on win64, wrong calling convention
  src/dmd/e2ir.d
  src/dmd/glue.d
  src/dmd/s2ir.d
  src/dmd/semantic3.d
  src/dmd/target.d
  src/dmd/toir.d
  src/dmd/traits.d
  test/runnable/cppa.d
  test/runnable/extra-files/cppb.cpp
Labels: Bug Fix, Vision, auto-merge

#8343 Export CC to the test shell environment
  test/compilable/issue15574.sh
  test/tools/exported_vars.sh
Labels: 72h no objection -> merge

#8348 Change deprecation to error for redundant storage classes
  changelog/redundant_stc_error.dd
  src/dmd/parse.d
  test/fail_compilation/parseStc3.d
  test/fail_compilation/parseStc4.d
Labels: 72h no objection -> merge, Deprecation -> Error, Easy Review

#8352 Fix Issue 15691 - Improve error message for struct member initializer
  src/dmd/initsem.d
  test/fail_compilation/fail15691.d
Labels: Easy Review, Enhancement, auto-merge

#8351 Fix Issue 15068 - wrong error message on attempting to use type as template
  src/dmd/dtemplate.d
  test/fail_compilation/fail15068.d
Labels: Bug Fix

#8349 fix issue 15589 - cleanup/improve PR #8277 - C++ dtors in vtbl
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/arraytypes.d
  src/dmd/arraytypes.h
  src/dmd/clone.d
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/dsymbolsem.d
  src/dmd/id.d
  src/dmd/target.d
  src/dmd/target.h
  src/dmd/todt.d
  src/dmd/toobj.d
  test/compilable/cppmangle.d
  test/runnable/cppa.d
  test/runnable/extra-files/cppb.cpp
  test/runnable/extra-files/cppb.h
Labels: Enhancement, auto-merge

#8356 Fix Issue 16088 - Parse error for import expression in statement
  src/dmd/parse.d
  test/compilable/imports/imp16088.d
  test/compilable/test16088.d
Labels: Bug Fix

#8346 fix Issue 18963 - Relax restrictions on 'return' parameters when para…
  src/dmd/typesem.d
  test/fail_compilation/test16228.d
Labels: Blocking Other Work, Enhancement, Needs spec PR, Vision, auto-merge

#8354 Fix Issue 18970 - DMD segfault due to opDispatch
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  src/dmd/typesem.d
  test/fail_compilation/fail18970.d
Labels: Bug Fix, WIP

#8355 Fix Issue 18976 - Inconsistency in overload merging with aliases
  src/dmd/func.d
  test/compilable/test18976.d
Labels: Bug Fix, Easy Review, auto-merge

#8353 Fix Issue 15755 - DMD segfault upon alias on alias on __trait(getAttributes, ...)
  src/dmd/dtemplate.d
  test/fail_compilation/fail15755.d
Labels: Bug Fix

#8364 add BlockRange - use foreach for block lists
  src/dmd/backend/cc.d
  src/dmd/eh.d
  src/dmd/glue.d
  src/dmd/s2ir.d
Labels: Refactoring, Trivial

#8317 convert list.c to dlist.d
  src/dmd/backend/cc.d
  src/dmd/backend/cdef.d
  src/dmd/backend/cgcv.d
  src/dmd/backend/dlist.d
  src/dmd/backend/el.d
  src/dmd/backend/global.d
  src/dmd/backend/tk.c
  src/dmd/backend/type.d
  src/dmd/s2ir.d
  src/dmd/tk/dlist.d
  src/dmd/tk/list.c
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, auto-merge

#8361 Some foreach related fixes
  src/dmd/statementsem.d
  test/fail_compilation/fail18994.d
Labels: Enhancement, auto-merge

#8362 fix Issue 18966 - extern(C++) constructor should match C++ semantics …
  src/dmd/aggregate.h
  src/dmd/dclass.d
  src/dmd/expressionsem.d
  src/dmd/tocsym.d
  src/dmd/toobj.d
  test/runnable/cppa.d
  test/runnable/extra-files/cppb.cpp
  test/runnable/extra-files/cppb.h
Labels: Bug Fix, Vision, auto-merge

#8366 Aggregate extern(C++) changes into a single, more-detailed changelog.
  changelog/extern_cpp_overhaul.dd
  changelog/mangle_ctor.dd
  changelog/mangle_nullptr_t.dd
  changelog/mangle_operators.dd
Labels: Vision, auto-merge

#8359 fix issue 18953 - 32-bit: extern(C++) struct destructor not called cor…
  src/dmd/clone.d
  test/runnable/cppa.d
Labels: Bug Fix, Vision

#8373 reduce reliance on global.errors
  src/dmd/dimport.d
  src/dmd/dsymbolsem.d
Labels: Refactoring, auto-merge

#8363 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/typesem.d
  test/compilable/test18976.d
  test/fail_compilation/fail15755.d
  test/fail_compilation/fail18970.d
Labels: Bug Fix, auto-merge

#8377 Add Objective-C example to the `getLinkage` changelog
  changelog/getlinkage_for_classes.dd
Labels: Easy Review, Trivial, auto-merge

#8375 toctype.d: minor refactor
  src/dmd/toctype.d
Labels: Easy Review, Refactoring, auto-merge

#8376 Fix Issue 17602 - improve message for deprecated enum comparison
  src/dmd/hdrgen.d
  test/fail_compilation/fail17602.d
  test/fail_compilation/imports/imp17602.d
Labels: Easy Review, Enhancement

#8379 Create visitor for Type.defaultInit methods
  src/dmd/aggregate.d
  src/dmd/initsem.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/typesem.d
Labels: Easy Review, Refactoring

#8381 Remove unused dmd.mars imports.
  src/dmd/semantic2.d
  src/dmd/semantic3.d
Labels: Trivial, auto-merge

#8382 Sync C++ headers with D sources
  src/dmd/aggregate.h
  src/dmd/cond.h
  src/dmd/template.h
Labels: GDC, Trivial, auto-merge

#8368 fix issue 18984 - stack struct's which are returned causes incorrect debuginfo.
  src/dmd/glue.d
  src/dmd/tocsym.d
  test/runnable/testpdb.d
Labels: Bug Fix, auto-merge

#8383 [C++] Put ClassKind enum inside a struct.
  src/dmd/aggregate.h
Labels: GDC, Trivial, auto-merge

#8386 Move TypeQualified semantic methods to typesem.d and make them private
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/typesem.d
Labels: Easy Review, Refactoring, auto-merge

#8385 [C++] Refactor type declarations of ClassFlags and StructFlags.
  src/dmd/aggregate.h
  src/dmd/dclass.d
  src/dmd/dstruct.d
  src/dmd/todt.d
  src/dmd/toobj.d
Labels: Trivial, auto-merge

#8387 [C++] Add declaration for ClassDeclaration::vtblSymbol.
  src/dmd/aggregate.h
Labels: GDC, Trivial, auto-merge

#8388 [C++] Fix signature of Loc::equals to match D declaration.
  src/dmd/globals.h
Labels: GDC, Trivial, auto-merge

#8384 provide location of called function in message
  src/dmd/expression.d
  test/fail_compilation/diag10319.d
  test/fail_compilation/diag7050a.d
  test/fail_compilation/diag7050c.d
  test/fail_compilation/fail10254.d
  test/fail_compilation/fail10968.d
  test/fail_compilation/fail12622.d
  test/fail_compilation/fail13120.d
  test/fail_compilation/fail14407.d
  test/fail_compilation/fail14486.d
  test/fail_compilation/fail328.d
  test/fail_compilation/fail7848.d
Labels: auto-merge

#8360 Fix Issue 18985 - bad error message for += operation on shared Object
  src/dmd/expressionsem.d
  test/fail_compilation/diag13320.d
  test/fail_compilation/fail18985.d
  test/fail_compilation/fail3672.d
Labels: Bug Fix

#8390 add some const to mtype.d
  src/dmd/mtype.d
Labels: Easy Review, Refactoring

#8393 Update Objective-C glue layer for GDC.
  src/dmd/gluelayer.d
Labels: GDC, Trivial, auto-merge

#8392 [C++] Fix order of virtual functions in Dsymbol
  src/dmd/dsymbol.h
Labels: GDC, Trivial, auto-merge

#8112 needed compiler features to convert backend to D
  src/dmd/backend/divcoeff.d
Labels: Continuous Integration, D Conversion

#8394 Improve compile_output regex
  test/tools/d_do_test.d
Labels: auto-merge

#8389 Use supplemental error message for called function
  src/dmd/expression.d
  test/fail_compilation/diag10319.d
  test/fail_compilation/diag7050a.d
  test/fail_compilation/diag7050c.d
  test/fail_compilation/fail10254.d
  test/fail_compilation/fail10968.d
  test/fail_compilation/fail12622.d
  test/fail_compilation/fail13120.d
  test/fail_compilation/fail14407.d
  test/fail_compilation/fail14486.d
  test/fail_compilation/fail328.d
  test/fail_compilation/fail7848.d
  test/fail_compilation/ice15441.d
Labels: auto-merge

#8397 Remove -property compiler switch
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/mars.d
  test/runnable/opover2.d
  test/runnable/property2.d
Labels: Deprecation -> Error, auto-merge

#8396 Fix Issue 19018 - lexer do not allow invalid integer literal
  src/dmd/lexer.d
  test/fail_compilation/fix19018.d
Labels: Bug Fix, auto-merge

#8370 Fix Issue 18266 - ICE: should allow reusing identifier in declaration…
  src/dmd/expressionsem.d
  test/fail_compilation/fail11720.d
  test/fail_compilation/fail18266.d
Labels: Bug Fix

#8401 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/extern_cpp_overhaul.dd
  changelog/getlinkage_for_classes.dd
  changelog/mangle_ctor.dd
  changelog/mangle_nullptr_t.dd
  changelog/mangle_operators.dd
  src/dmd/aggregate.h
  src/dmd/clone.d
  src/dmd/dclass.d
  src/dmd/expressionsem.d
  src/dmd/glue.d
  src/dmd/tocsym.d
  src/dmd/toobj.d
  test/fail_compilation/fail11720.d
  test/fail_compilation/fail18266.d
  test/runnable/cppa.d
  test/runnable/extra-files/cppb.cpp
  test/runnable/extra-files/cppb.h
  test/runnable/test18916.d
  test/runnable/testpdb.d
Labels: Bug Fix, auto-merge

#8395 Require test rerun if DMD has been rebuilt
  test/run.d
Labels: Easy Review, auto-merge

#8403 Fix buffer overflow in test/runnable/cppa.d
  test/runnable/cppa.d
Labels: auto-merge

#8402 Print output on segfault in the testsuite
  test/tools/d_do_test.d
Labels: Easy Review, auto-merge

#8404 Fix Issue 9701 - allow UDAs to be attached to enum values
  changelog/enum_attributes.dd
  src/dmd/astbase.d
  src/dmd/declaration.d
  src/dmd/denum.d
  src/dmd/dsymbolsem.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/parse.d
  src/dmd/traits.d
  test/compilable/test9701.d
  test/fail_compilation/disable.d
  test/fail_compilation/disable_new.d
  test/fail_compilation/fail15044.d
  test/fail_compilation/fail341.d
  test/fail_compilation/test17908a.d
  test/fail_compilation/test17908b.d
  test/fail_compilation/test9701.d
  test/fail_compilation/test9701b.d
Labels: Bug Fix, auto-merge

#8400 Sanitize Json import path to a relative path
  test/tools/sanitize_json.d
Labels: Easy Review, auto-merge

#8409 [D1] Update vendor name in deb package
  pkg/dmd1.pkg
Labels: D1

#8399 Fix Issue 19022 - CTorFlow: Show the line of the duplicated initialization for const/immutable fields
  src/dmd/ctorflow.d
  src/dmd/declaration.d
  src/dmd/dscope.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/globals.d
  src/dmd/root/rmem.d
  src/dmd/semantic3.d
  src/dmd/statementsem.d
  test/fail_compilation/diag12678.d
  test/fail_compilation/diag19022.d
  test/fail_compilation/fail18719.d
  test/fail_compilation/fail9665a.d
Labels: Enhancement, auto-merge

#8414 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  test/runnable/cppa.d
Labels: auto-merge

#8406 Deprecate opDot
  changelog/deprecate-opDot.dd
  src/dmd/typesem.d
  test/fail_compilation/deprecateopdot.d
Labels: Easy Review, Needs Approval, auto-merge

#8415 convert gsroa.c to gsroa.d
  src/dmd/backend/gsroa.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, auto-merge

#8416 convert glocal.c to glocal.d
  src/dmd/backend/glocal.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, auto-merge

#8417 build.d: ignore optabgen in backgend globbing
  src/build.d
Labels: Continuous Integration, Easy Review

#8419 convert go.h to goh.d
  src/dmd/backend/glocal.d
  src/dmd/backend/goh.d
  src/posix.mak
  src/win32.mak
Labels: Blocking Other Work, D Conversion

#8420 convert gdag.c to D
  src/dmd/backend/gdag.d
  src/dmd/backend/goh.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, auto-merge

#7576 UDAs for function arguments
  changelog/uda-function-arguments.dd
  src/dmd/astbase.d
  src/dmd/attrib.d
  src/dmd/clone.d
  src/dmd/cond.d
  src/dmd/declaration.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/hdrgen.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/parse.d
  src/dmd/semantic2.d
  src/dmd/semantic3.d
  src/dmd/statementsem.d
  src/dmd/traits.d
  src/dmd/typesem.d
  test/compilable/extra-files/header1.d
  test/compilable/extra-files/header1.di
  test/compilable/extra-files/header1i.di
  test/compilable/extra-files/headerudamodule.di
  test/compilable/testheaderudamodule.d
  test/fail_compilation/fail10207.d
  test/fail_compilation/udaparams.d
  test/runnable/uda.d
Labels: Enhancement, auto-merge

#8421 convert gother.c to D
  src/dmd/backend/global.d
  src/dmd/backend/gloop.c
  src/dmd/backend/go.h
  src/dmd/backend/goh.d
  src/dmd/backend/gother.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, auto-merge
