Repository dlang/dmd, pull requests merged in 2018-10, with the labels that each got.

#8776 Add aliases to ASTCodegen for dmd#8591
  src/dmd/astcodegen.d
Labels: auto-merge

#8696 Fix 19243 - [REG 2.081] Can no longer override pragma(lib) with -L switch
  src/dmd/link.d
  test/README.md
  test/compilable/issue19243.sh
  test/tools/exported_vars.sh
Labels: Bug Fix

#8780 dmd.globals: Move vendor string back to Global struct
  src/dmd/compiler.d
  src/dmd/compiler.h
  src/dmd/globals.d
  src/dmd/json.d
  src/dmd/lexer.d
Labels: Blocking Other Work, GDC, Trivial, auto-merge

#8778 Move ArrayLiteralExp.copyElements to dmd.constfold
  src/dmd/constfold.d
  src/dmd/expression.d
  src/dmd/expression.h
Labels: Refactoring, auto-merge

#8711 Fix Issue 19251 - Alias this does not get called on struct qualified type
  src/dmd/expressionsem.d
  test/runnable/test19251.d
Labels: 72h no objection -> merge, Bug Fix

#8773 Remove C++ linkage from static members
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/astbase.d
  src/dmd/attrib.d
  src/dmd/attrib.h
  src/dmd/ctfe.h
  src/dmd/ctfeexpr.d
  src/dmd/dmodule.d
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/identifier.d
  src/dmd/identifier.h
  src/dmd/module.h
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/objc.d
  src/dmd/objc.h
  src/dmd/scope.h
  src/dmd/template.h
  src/dmd/tokens.d
  src/dmd/tokens.h
Labels: Refactoring, Trivial, auto-merge

#8784 dmd.expression: Squash multiple uses of combine into one helper function call
  src/dmd/expressionsem.d
  src/dmd/inline.d
  src/dmd/opover.d
Labels: Refactoring, auto-merge

#8777 convert cgcv.c to dcgcv.d
  src/dmd/backend/dcgcv.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8745 convert pdata.c to D
  src/dmd/backend/pdata.c
  src/dmd/backend/pdata.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8746 [Refactoring] Move the printing of overload candidates to a separate function
  src/dmd/func.d
Labels: Refactoring, auto-merge

#8771 convert util2.c to D
  src/dmd/backend/util2.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8786 cod4.d: fix warning about integral pr
  src/dmd/backend/cod4.d
Labels: Easy Review

#8735 convert var.c to D
  src/build.d
  src/dmd/backend/cc.d
  src/dmd/backend/optabgen.c
  src/dmd/backend/var.c
  src/dmd/backend/var.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8742 convert out.c to D
  src/dmd/backend/cc.d
  src/dmd/backend/machobj.c
  src/dmd/backend/obj.d
  src/dmd/backend/obj.h
  src/dmd/backend/out.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, Refactoring

#8447 convert md5.c to D
  src/dmd/backend/md5.c
  src/dmd/backend/md5.d
  src/dmd/e2ir.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8790 remove broken dmd_backend.vcxproj.filters
  src/vcbuild/dmd_backend.vcxproj.filters
Labels: auto-merge

#8793 transfer code from outbuf.c to outbuf.d
  src/dmd/backend/outbuf.c
  src/dmd/backend/outbuf.d
  src/dmd/backend/outbuf.h
Labels: D Conversion, Refactoring, WIP

#8791 fix different qualifiers on declarations
  src/dmd/backend/cgcv.d
  src/dmd/backend/ty.d
Labels: auto-merge

#8794 split off sizecheck.c from backconfig.c
  src/dmd/backend/backconfig.c
  src/dmd/backend/sizecheck.c
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Easy Review, Refactoring, auto-merge

#8795 dmd/root/stringtable.h: Remove header and all references
  src/dmd/dinifile.d
  src/dmd/root/stringtable.d
  src/dmd/root/stringtable.h
  src/posix.mak
  src/tests/cxxfrontend.c
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: Refactoring, auto-merge

#8785 dmd.expression: Use 'out' parameter for extractLast
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/inline.d
  src/dmd/statementsem.d
Labels: Refactoring, auto-merge

#8799 Remove extern(C++) linkage from non-virtual template member functions
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/template.h
Labels: Refactoring, auto-merge

#7559 Move loadModule and paintAsType from Target to Compiler
  src/dmd/compiler.d
  src/dmd/compiler.h
  src/dmd/ctfeexpr.d
  src/dmd/dmodule.d
  src/dmd/target.d
  src/dmd/target.h
Labels: auto-merge

#8797 Remove extern(C++) linkage from non-virtual check member functions
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/func.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/statement.d
  src/dmd/statement.h
Labels: Refactoring, auto-merge

#8634 Fix issue 19203 - alias this to a bool behaves both inconsistently and incorrectly with static assert
  src/dmd/staticcond.d
  test/compilable/test19203.d
Labels: 72h no objection -> merge, Enhancement, auto-merge

#8801 convert backconfig.c to D
  src/dmd/backend/backconfig.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Easy Review, Refactoring, auto-merge

#8800 dmodule: Refactor/improve IO code
  src/dmd/dmodule.d
  src/dmd/root/file.d
Labels: Easy Review, auto-merge

#8788 convert optabgen.c to D
  appveyor.yml
  src/build.d
  src/dmd/backend/optabgen.c
  src/dmd/backend/optabgen.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring

#8807 [C++] Allow compiling front-end with strict warnings
  src/dmd/aggregate.h
  src/dmd/declaration.h
  src/dmd/dsymbol.h
  src/dmd/enum.h
  src/dmd/expression.h
  src/dmd/globals.h
  src/dmd/import.h
  src/dmd/module.h
  src/dmd/mtype.h
  src/dmd/nspace.h
  src/dmd/root/object.h
  src/dmd/statement.h
  src/dmd/template.h
  src/dmd/tokens.h
Labels: GDC, Trivial

#8806 Apply const attributes on base member functions
  src/dmd/aggregate.d
  src/dmd/declaration.d
  src/dmd/dsymbol.d
Labels: Trivial, auto-merge

#8699 optimization: recognize empty trailing statements
  src/dmd/statementsem.d
Labels: auto-merge

#8803 [refactor] Move onImport callback to Compiler.onImport
  src/dmd/compiler.d
  src/dmd/compiler.h
  src/dmd/dmodule.d
  src/dmd/mars.d
  src/dmd/module.h
Labels: Refactoring, auto-merge

#8808 fix Issue 19292 - Mixin expressions should take an argument list the …
  src/dmd/astbase.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/hdrgen.d
  src/dmd/iasmgcc.d
  src/dmd/parse.d
  src/dmd/parsetimevisitor.d
  src/dmd/transitivevisitor.d
  test/compilable/test19292.d
Labels: Enhancement

#8805 convert ph2.c to D
  src/dmd/backend/ph2.c
  src/dmd/backend/ph2.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring

#8809 fix Issue 19292 part 2 - Mixin statements should take an argument list the …
  src/dmd/astbase.d
  src/dmd/hdrgen.d
  src/dmd/parse.d
  src/dmd/statement.d
  src/dmd/statement.h
  src/dmd/transitivevisitor.d
  test/compilable/test19292.d
  test/fail_compilation/ice12497.d
Labels: Enhancement

#8812 Fix regression introduced by #8808
  src/dmd/visitor.h
  src/tests/cxxfrontend.c
Labels: GDC, Regression, auto-merge

#8818 dmd.iasmgcc: Remove special handling of mixins
  src/dmd/iasmgcc.d
Labels: GDC, auto-merge

#8814 Fix Issue 19284 - alias this not used in nested functions of a method
  src/dmd/expressionsem.d
  test/runnable/aliasthis.d
Labels: Bug Fix

#8819 convert newman.c to D
  src/dmd/backend/newman.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring

#8820 remove dependency on rtlsym.h
  src/dmd/backend/dwarf.c
  src/dmd/backend/rtlsym.d
Labels: D Conversion, Refactoring, Trivial, auto-merge

#8826 fix Issue 11538: stack overflow with recursive NullableRef
  test/runnable/aliasthis.d
Labels: Bug Fix, Trivial, auto-merge

#8827 convert rtlsym.h and rtlsym.c to drtlsym.d
  src/dmd/backend/cc.h
  src/dmd/backend/drtlsym.d
  src/dmd/backend/dwarf.c
  src/dmd/backend/rtlsym.c
  src/dmd/backend/rtlsym.d
  src/dmd/backend/rtlsym.h
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8728 More target info
  src/dmd/target.d
  test/compilable/traits.d
Labels: auto-merge

#8829 fix dependencies of optabgen build step in VS project
  src/vcbuild/dmd_backend.vcxproj
Labels: auto-merge

#8830 convert dwarfeh.c to D
  src/dmd/backend/dwarf.d
  src/dmd/backend/dwarfeh.d
  src/posix.mak
  src/win32.mak
Labels: D Conversion, Refactoring

#8835 Temporarily revert SemaphoreCI to ldc v1.11.0
  semaphoreci.sh
Labels: Blocking Other Work, Easy Review

#8836 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
Labels: auto-merge, stable -> master

#8838 Initializer: add InitKind discriminant
  src/dmd/astbase.d
  src/dmd/init.d
  src/dmd/init.h
Labels: Refactoring, auto-merge

#8816 convert ptrntab.c to D
  src/dmd/backend/iasm.d
  src/dmd/backend/ptrntab.c
  src/dmd/backend/ptrntab.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring

#8832 Frontend lib: remove assertion for parsing errors
  src/dmd/frontend.d
  test/dub_package/frontend.d
  test/dub_package/frontend_file.d
Labels: auto-merge

#8833 Convert warnings and useDeprecated byte values into an enum
  src/dmd/dsymbol.d
  src/dmd/errors.d
  src/dmd/expressionsem.d
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/lexer.d
  src/dmd/mars.d
  src/dmd/semantic3.d
  src/dmd/sideeffect.d
Labels: GDC, Trivial, auto-merge

#8843 remove iasm.h (replaced by iasm.d)
  src/dmd/backend/iasm.h
  src/posix.mak
  src/win32.mak
Labels: D Conversion, Easy Review, Refactoring, auto-merge

#8844 remove xmm.h (replaced by xmm.d)
  src/dmd/backend/xmm.h
  src/posix.mak
  src/win32.mak
Labels: D Conversion, Easy Review, Refactoring, auto-merge

#8841 de-virtualize cgobj.c and mscoffobj.c
  src/dmd/backend/cgobj.c
  src/dmd/backend/cv8.d
  src/dmd/backend/mscoffobj.c
  src/dmd/backend/obj.d
  src/dmd/backend/obj.h
  src/dmd/backend/pdata.d
  src/dmd/glue.d
Labels: D Conversion, Refactoring, auto-merge

#8718 add -checkaction switch
  changelog/checkaction.dd
  src/dmd/cli.d
  src/dmd/e2ir.d
  src/dmd/globals.d
  src/dmd/mars.d
  src/dmd/statementsem.d
Labels: auto-merge

#8850 Remove compatibility support for D 2.06x
  src/dmd/backend/global.d
  src/dmd/backend/oper.d
  src/dmd/backend/ty.d
  src/dmd/backend/type.d
  src/dmd/constfold.d
  src/dmd/link.d
  src/dmd/optimize.d
Labels: Refactoring, auto-merge

#8848 minor changes to cgobj.c to work with dmc
  src/dmd/backend/cgobj.c
Labels: auto-merge

#8854 whitespace formatting of cod2.d
  src/dmd/backend/cod2.d
Labels: Easy Review, Refactoring, auto-merge

#8821 Correct type name for associative arrays in CodeView
  src/dmd/backend/cv8.d
  src/dmd/backend/type.d
  src/dmd/backend/type.h
  src/dmd/toctype.d
Labels: auto-merge

#8856 prep cgobj.c for conversion to D
  src/dmd/backend/cgobj.c
Labels: D Conversion, Easy Review, Refactoring, auto-merge

#8859 Fix real_t == sinteger_t comparison from #8850
  src/dmd/optimize.d
Labels: GDC, Trivial, auto-merge

#8707 Enable putting structs with void field initializers into BSS segment
  src/dmd/dstruct.d
Labels: Easy Review, auto-merge

#8862 Reword -dw to not refer to deprecations as warnings
  src/dmd/cli.d
Labels: Easy Review, Trivial, documentation

#8853 replace Visitor with switch in Initializer_toDt()
  src/dmd/todt.d
Labels: Easy Review, Refactoring, auto-merge

#8860 convert cgobj.c to D
  src/dmd/backend/cgobj.d
  src/dmd/backend/mscoffobj.c
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8861 Tweak utf_isValidDchar: put check for most common condition first
  src/dmd/utf.d
Labels: auto-merge

#8783 convert varstats.c to dvarstats.d
  src/dmd/backend/cgobj.d
  src/dmd/backend/cv8.d
  src/dmd/backend/dcgcv.d
  src/dmd/backend/dvarstats.d
  src/dmd/backend/var.d
  src/dmd/backend/varstats.di
  src/dmd/backend/varstats.h
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8865 remove varstats.h
  src/dmd/backend/varstats.h
  src/posix.mak
  src/win32.mak
Labels: Trivial, auto-merge

#8855 de-virtualize elfobj.c and machobj.c
  src/dmd/backend/cod3.d
  src/dmd/backend/dwarf.c
  src/dmd/backend/elfobj.c
  src/dmd/backend/machobj.c
  src/dmd/backend/obj.d
  src/dmd/backend/obj.h
  src/dmd/objc_glue.d
Labels: D Conversion, Refactoring

#8443 Turn deprecation into error for issue 313
  changelog/fqn_imports_bypass_private_imports_error.dd
  src/dmd/access.d
  test/compilable/testDIP37.d
  test/fail_compilation/fail313.d
  test/runnable/testdstress.d
  test/runnable/testmodule.d
Labels: Deprecation -> Error, Easy Review, auto-merge

#8845 replace use of Visitor in initializerSemantic()
  src/dmd/initsem.d
Labels: Refactoring, auto-merge

#8847 fix issue 19307 - Variables moved to a closure show nonsense in debugger
  src/dmd/backend/cv8.d
  src/dmd/backend/dcgcv.d
  src/dmd/glue.d
  src/dmd/tocvdebug.d
  src/dmd/toir.d
  test/runnable/testpdb.d
Labels: Bug Fix, auto-merge

#8873 replace use of Visitor in inferType() with switch
  src/dmd/initsem.d
Labels: Refactoring, auto-merge

#8871 finish translating melf.h to melf.d
  src/dmd/backend/melf.d
Labels: D Conversion, auto-merge

#8874 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  src/dmd/link.d
Labels: Bug Fix

#8875 [trivial] fix typo in changelog for 14246
  changelog/reboot14246.dd
Labels: Trivial

#8879 prepare elfobj.c for conversion to D
  src/dmd/backend/elfobj.c
Labels: D Conversion, auto-merge

#8884 Fix locating the DMD config in the Dub package for Windows
  src/dmd/frontend.d
Labels: auto-merge

#8872 fix Issue 18457 - betterC - struct destructor is always called at fun…
  src/dmd/func.d
  test/runnable/betterc.d
Labels: Bug Fix, auto-merge

#8878 Expose DMD's command line parsing
  src/dmd/mars.d
Labels: Trivial, auto-merge

#8886 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/reboot14246.dd
Labels: auto-merge

#8851 [stable] Minor C++ fixups/extensions + paintAsType() simplification
  src/dmd/compiler.d
  src/dmd/compiler.h
  src/dmd/errors.h
  src/dmd/root/dcompat.h
  src/dmd/root/filename.h
  src/dmd/root/port.h
Labels: auto-merge

#8896 cgcod.d: whitespace formatting
  src/dmd/backend/cgcod.d
Labels: Easy Review, Refactoring, auto-merge

#8867 convert dwarf.c to dwarfdbginf.d
  src/dmd/backend/aarray.d
  src/dmd/backend/dwarfdbginf.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: D Conversion, Refactoring, auto-merge

#8877 replace use of Visitor in intializerToExpression() with switch
  src/dmd/initsem.d
Labels: Refactoring, auto-merge

#8897 gdag.d: minor refactor of aewalk()
  src/dmd/backend/gdag.d
Labels: Refactoring, auto-merge

#8891 fix compilation broken when using GCC 8.2.1
  src/dmd/backend/elfobj.c
Labels: auto-merge

#8893 Fix build of the D frontend on the Hurd and KFreeBSD
  src/root/object.h
  test/Makefile
Labels: C++ Port, GDC
