Repository dlang/dmd, pull requests merged in 2018-03, with the labels that each got.

#7972 Improve d_do_test DISABLED to allow true submatches
  test/d_do_test.d
Labels: auto-merge

#7938 [Refactor] Create Visitor for getProperty method of type AST nodes
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/typesem.d
Labels: Refactoring, auto-merge

#7937 Add [Environment{arch}] DFLAGS to -v output
  src/dmd/mars.d
  test/compilable/testclidflags.sh
Labels: Bug Fix, auto-merge

#7975 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/comma-deprecation-error.dd
  changelog/default_after_variadic.dd
  changelog/deprecate_delete.dd
  changelog/deprecation-dylib.dd
  changelog/dip1008.dd
  changelog/disabled-trait.dd
  changelog/fix17630.dd
  changelog/fix17899.dd
  changelog/fix18053.dd
  changelog/fix18219.dd
  changelog/fix18361.dd
  changelog/fix8207.dd
  changelog/hexstrings.dd
  changelog/includeimports.dd
  changelog/json_includes.dd
  changelog/lambdacomp.dd
  changelog/lld_mingw.dd
  changelog/minimal_runtime.dd
  changelog/osx-10_9.dd
  changelog/private.dd
  changelog/ptr-safe-end-of-deprecation.dd
  src/dmd/semantic2.d
  test/fail_compilation/fail17492.d
  test/fail_compilation/fail2789.d
Labels: auto-merge

#7890 Fix issue 16555 - Generate correct code for pushing scalar parameters.
  src/dmd/backend/cod1.c
  test/runnable/test16555.d
Labels: Bug Fix, Easy Review, auto-merge

#7978 [dmd-cxx] Logic error when backpatching fix for issue 15149
  src/dstruct.c
Labels: C++ Port, Trivial

#7979 [dmd-cxx] Remove va_argsave and move magic initialization of _argptr to the glue layer
  src/backend/cgelem.c
  src/backend/gflow.c
  src/glue.c
Labels: C++ Port

#7963 fix Issue 16243 - wrong C++ argument passing with empty struct when i…
  src/dmd/aggregate.h
  src/dmd/backend/cgcod.c
  src/dmd/backend/cgelem.c
  src/dmd/backend/cod1.c
  src/dmd/backend/cod2.c
  src/dmd/backend/code.h
  src/dmd/backend/nteh.c
  src/dmd/backend/type.c
  src/dmd/backend/type.d
  src/dmd/backend/type.h
  src/dmd/dstruct.d
  src/dmd/dsymbolsem.d
  src/dmd/e2ir.d
  src/dmd/expressionsem.d
  src/dmd/glue.d
  src/dmd/mtype.d
  src/dmd/target.d
  src/dmd/target.h
  src/dmd/tocsym.d
  src/dmd/toctype.d
  src/dmd/toir.d
  test/runnable/cppa.d
Labels: Bug Fix, auto-merge

#7891 Fix Issue 16578 - bogus deprecation - switch skips declaration of variable
  src/dmd/statement.d
  test/compilable/test16578a.d
  test/compilable/test16578b.d
Labels: Blocking Other Work, Bug Fix, Easy Review, auto-merge

#7976 fix Issue 5212 - no escape analysis for typesafe variadic function ar…
  src/dmd/dtemplate.d
  src/dmd/expressionsem.d
  src/dmd/semantic3.d
  test/fail_compilation/fail13902.d
  test/fail_compilation/fix5212.d
  test/fail_compilation/retscope.d
Labels: Bug Fix

#7762 Add support for Objective-C class/static methods
  changelog/objc_class_methods.dd
  src/dmd/aggregate.h
  src/dmd/dclass.d
  src/dmd/dsymbolsem.d
  src/dmd/e2ir.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/func.d
  src/dmd/id.d
  src/dmd/mtype.d
  src/dmd/objc.d
  src/dmd/objc.h
  src/dmd/objc_glue.d
  src/dmd/root/stringtable.d
  src/dmd/tokens.d
  src/dmd/tokens.h
  src/dmd/visitor.d
  src/dmd/visitor.h
  test/fail_compilation/objc_non_objc_base.d
  test/runnable/objc_call_static.d
Labels: 72h no objection -> merge, auto-merge

#7953 [dmd-cxx]: Fix the auto-tester and copy dmd to $(GENERATED)/$(OS)/$(BUILD)/$(MODEL)
  .gitignore
  src/posix.mak
Labels: C++ Port, WIP

#7932 [Refactor] Create visitor for resolve method of type AST nodes
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/typesem.d
Labels: 72h no objection -> merge, Refactoring

#7923 Start documenting the Objective-C ABI
  docs/objective-c_abi.md
Labels: 72h no objection -> merge, auto-merge

#7983 Refactor: code to generate struct copies
  src/dmd/e2ir.d
  src/dmd/s2ir.d
  test/runnable/inline.d
Labels: Refactoring

#7985 [Refactor] Move buildPostBlit from dmd/clone.d to dmd/dsymbolsem.d
  src/dmd/clone.d
  src/dmd/dsymbolsem.d
Labels: Refactoring

#7984 Fix Issue 18551 - Improve hint for does not override any function
  src/dmd/dsymbolsem.d
  test/fail_compilation/diag9191.d
  test/fail_compilation/fail18093.d
  test/fail_compilation/fail8631.d
  test/fail_compilation/retref2.d
  test/fail_compilation/test13867.d
Labels: Enhancement, auto-merge

#7967 fix Issue 18530 - src/rt/tracegc.d(43): Deprecation: The delete keywo…
  src/dmd/expressionsem.d
  src/dmd/parse.d
  test/compilable/vgc1.d
  test/fail_compilation/fail14486.d
  test/fail_compilation/fail2361.d
  test/fail_compilation/fail_arrayop2.d
  test/fail_compilation/faildeleteaa.d
  test/fail_compilation/nogc1.d
  test/fail_compilation/test16195.d
Labels: Bug Fix

#7981 fix Issue 16037 - assigning delegate to a scope variable shouldn't al…
  src/dmd/escape.d
  test/compilable/test16037.d
  test/runnable/test42.d
Labels: Enhancement

#7968 appveyor: build test suite for coff32
  appveyor.yml
Labels: Continuous Integration, auto-merge

#7989 fix Issue 18575 - making delegate from member function can lead to un…
  src/dmd/expressionsem.d
  test/fail_compilation/fix18575.d
Labels: Bug Fix

#7987 Fix issue 18574: Unclear error message when trying to inherit from mu…
  src/dmd/dsymbolsem.d
  test/fail_compilation/diag18574.d
Labels: Bug Fix, Enhancement, auto-merge

#7990 fix Issue 18576 - Compiler not doing RVO with auto returns
  src/dmd/s2ir.d
  test/runnable/test28.d
Labels: Bug Fix, auto-merge

#7992 Make Lexer.escapeSequence more reusable and add unittests
  src/dmd/lexer.d
  test/fail_compilation/lexer1.d
Labels: auto-merge

#7993 fix Issue 17892 - Scope analysis with -dip1000 fails for templated st…
  src/dmd/expressionsem.d
  test/fail_compilation/test17892.d
Labels: Bug Fix, auto-merge

#7997 add issue/bugzilla link as badge
  README.md
Labels: auto-merge

#8004 Update test4.d to use long.alignof
  test/runnable/test4.d
Labels: auto-merge

#7977 Fix issue 15653 - IFTI fails for immutable parameter
  src/dmd/dtemplate.d
  test/runnable/template9.d
Labels: Bug Fix, auto-merge

#7973 Allow getting type from template declarations.
  src/dmd/mtype.d
  test/compilable/mixintempl.d
Labels: Enhancement, auto-merge

#8000 supplemental fix for PR 7993
  src/dmd/expression.d
  test/fail_compilation/test17892.d
Labels: auto-merge

#8001 fix Issue 17512 - [REG 2.073] [DIP1000] Error on bad interplay of 'au…
  src/dmd/statementsem.d
  test/compilable/test17512.d
Labels: Bug Fix, auto-merge

#7982 fix Issue 17284 - Template function attribute inference wrongly infer…
  src/dmd/safe.d
  test/fail_compilation/test17284.d
Labels: Bug Fix, auto-merge

#8008 fix Issue 17959 - [DIP1000] Can store scope delegate in non-scope member
  src/dmd/escape.d
  test/fail_compilation/fix5212.d
  test/fail_compilation/retscope2.d
  test/fail_compilation/test17959.d
Labels: Bug Fix, auto-merge

#8011 fix Issue 18000 - [scope] auto-generated opAssign not scope aware
  src/dmd/clone.d
  src/dmd/escape.d
  src/dmd/semantic3.d
  test/compilable/test18000.d
Labels: Bug Fix, auto-merge

#7934 [Refactor] Create visitor for dotExp method of type AST nodes
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/typesem.d
Labels: Refactoring, auto-merge

#7935 __traits(isSame) for lambda functions which contain function calls
  src/dmd/declaration.h
  src/dmd/func.d
  src/dmd/lambdacomp.d
  src/dmd/traits.d
  test/compilable/imports/testlambda1.d
  test/compilable/imports/testlambda2.d
  test/compilable/testlambdacomp.d
Labels: auto-merge

#8026 sh_do_test: Export LIBEXT
  test/compilable/test6461.sh
  test/runnable/gdb15729.sh
  test/runnable/link14198a.sh
  test/runnable/link14198b.sh
  test/runnable/link14834.sh
  test/runnable/link846.sh
  test/runnable/linkdebug.sh
  test/runnable/test10386.sh
  test/runnable/test13666.sh
  test/runnable/test13742.sh
  test/runnable/test13774.sh
  test/runnable/test39.sh
  test/runnable/test9377.sh
  test/sh_do_test.sh
Labels: Trivial, auto-merge

#8029 test42.d: Add cases for 128 bit reals in testreal_to_ulong()
  test/runnable/test42.d
Labels: auto-merge

#8035 fix Issue 18554 - tupleof ignoring private shouldn't be accepted in @…
  src/dmd/access.d
  src/dmd/dscope.d
  src/dmd/typesem.d
  test/fail_compilation/imports/imp18554.d
  test/fail_compilation/test18554.d
Labels: Bug Fix, auto-merge

#8033 Handle string escape errors more cleanly
  src/dmd/lexer.d
Labels: Diagnostic Messages, auto-merge

#8023 Emit a newline at the end of the JSON output file
  src/dmd/json.d
  test/compilable/extra-files/json-postscript.sh
  test/compilable/extra-files/json.out
  test/compilable/extra-files/json2.out
  test/compilable/extra-files/jsonCompilerInfo.out
  test/compilable/extra-files/jsonNoOutFile.out
  test/compilable/extra-files/json_nosource.out
  test/sanitize_json.d
Labels: auto-merge

#8036 fix Issue 18484 - [dip1000] Subtype allows reference to escape with i…
  src/dmd/escape.d
  test/fail_compilation/test18484.d
Labels: Bug Fix, auto-merge

#8024 Fix the check for untracked files + fix violation
  .circleci/run.sh
  posix.mak
  test/compilable/ddoc9764.sh
Labels: Continuous Integration, Trivial, auto-merge

#8030 fix Issue 18282 - [Scope][DIP1000]Assignment of local variable to va…
  src/dmd/dcast.d
  src/dmd/escape.d
  src/dmd/expressionsem.d
  test/fail_compilation/retscope3.d
  test/fail_compilation/test18282.d
Labels: Bug Fix, auto-merge

#8016 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/dmd/expressionsem.d
  src/dmd/parse.d
  src/dmd/statementsem.d
  test/compilable/test17512.d
  test/compilable/vgc1.d
  test/fail_compilation/fail14486.d
  test/fail_compilation/fail_arrayop2.d
  test/fail_compilation/nogc1.d
Labels: Bug Fix, auto-merge

#8039 refactor inferForeachAggregate
  src/dmd/opover.d
  src/dmd/statement.d
  src/dmd/statementsem.d
Labels: Refactoring, auto-merge

#7817 End deprecation phase for `switch` cases which skip the declaration of a variable
  changelog/switch-skip-declaration.dd
  src/dmd/statement.d
  test/fail_compilation/skip.d
  test/fail_compilation/switches.d
Labels: Blocked, Deprecation -> Error, auto-merge

#8044 refactor inferApplyArgTypes
  src/dmd/opover.d
Labels: auto-merge

#7999 fix Issue 17423 - pointer assignment to in member function is not ac…
  src/dmd/escape.d
  src/dmd/expressionsem.d
  src/dmd/mtype.d
  test/fail_compilation/test17423.d
Labels: Bug Fix, auto-merge

#8022 Use supportedFeatures object for feature detection
  src/dmd/json.d
  test/compilable/extra-files/json2.out
  test/compilable/extra-files/jsonCompilerInfo.out
  test/compilable/extra-files/jsonNoOutFile.out
  test/compilable/extra-files/json_nosource.out
Labels: auto-merge

#8047 fix Issue 15624 - opApply with @safe and @system variants can't be us…
  src/dmd/opover.d
  test/runnable/test15624.d
Labels: Enhancement, auto-merge

#8045 fix Issue 18282 part 2
  src/dmd/escape.d
  src/dmd/expressionsem.d
  test/fail_compilation/fail17842.d
  test/fail_compilation/retscope6.d
  test/fail_compilation/test18282.d
Labels: Bug Fix, auto-merge

#8032 Fix Issue 18417 - Make const and immutable postblit constructors illegal
  changelog/postblitQualifiers.dd
  src/dmd/parse.d
  test/compilable/ddoc10.d
  test/fail_compilation/fail18417.d
  test/fail_compilation/parseStc4.d
  test/fail_compilation/parseStc5.d
Labels: Enhancement, Needs Approval, Needs Changelog

#8052 fix Issue 18534 - Wrong code for ?: operator when compiling with -O
  src/dmd/backend/cod2.c
  test/runnable/test18534.d
Labels: Bug Fix, auto-merge

#8054 fix Issue 17784 - [scope][DIP1000] Confusing error message for escapi…
  src/dmd/escape.d
  test/fail_compilation/fail17842.d
  test/fail_compilation/retscope2.d
  test/fail_compilation/retscope3.d
  test/fail_compilation/retscope6.d
  test/fail_compilation/test18282.d
Labels: Enhancement

#8048 fix Issue 15660 - break immutable with pure function and mutable refe…
  src/dmd/dcast.d
  src/dmd/id.d
  test/compilable/fix17635.d
  test/fail_compilation/fix17635.d
  test/fail_compilation/test15660.d
  test/runnable/arrayop.d
  test/runnable/implicit.d
  test/runnable/testconst.d
Labels: Bug Fix, auto-merge

#8062 fix Issue 18644 - [dip1000] escape of outer local not detected
  src/dmd/escape.d
  test/fail_compilation/test18644.d
Labels: Bug Fix

#8040 Add a convenience script for running individual tests
  .circleci/run.sh
  test/run_individual_tests
Labels: 72h no objection -> merge, auto-merge

#8064 Fix postblitQualifiers's changelog
  changelog/postblitQualifiers.dd
Labels: Trivial, auto-merge

#8053 Remove NCEG operators from the language
  src/dmd/expressionsem.d
  src/dmd/lexer.d
  src/dmd/parse.d
  src/dmd/target.d
  src/dmd/tokens.d
  test/fail_compilation/ice11755.d
  test/runnable/testxmm.d
Labels: auto-merge

#8060 Document and update string literal lexer functions
  src/dmd/lexer.d
Labels: auto-merge

#8017 Fix issue 18553 - Allow mov reg64,crn and mov crn,reg64
  src/dmd/backend/ptrntab.c
  src/dmd/iasm.d
  test/runnable/iasm64.d
Labels: Bug Fix, auto-merge

#8037 Improve error message 'for {mutable,non-shared} method is not callable using X'
  src/dmd/func.d
  test/fail_compilation/diag1730.d
  test/fail_compilation/diag6707.d
  test/fail_compilation/diag8101b.d
  test/fail_compilation/fail241.d
  test/fail_compilation/ice9759.d
Labels: Diagnostic Messages, auto-merge

#8061 fix Issue 18607 - using labelled continue in tuple foreach can break …
  src/dmd/blockexit.d
  test/fail_compilation/test18607.d
Labels: Bug Fix, auto-merge

#8025 sh_do_test: verbose trace + start to remove inferred output_file
  test/compilable/crlf.sh
  test/compilable/ddoc9764.sh
  test/compilable/extra-files/ddocAny-postscript.sh
  test/compilable/issue17167.sh
  test/compilable/jsonNoOutFile.sh
  test/compilable/test14894.sh
  test/compilable/test18367.sh
  test/compilable/test6461.sh
  test/compilable/test9680.sh
  test/compilable/testclidflags.sh
  test/runnable/depsprot.sh
  test/runnable/gdb15729.sh
  test/runnable/link14198a.sh
  test/runnable/link14198b.sh
  test/runnable/link14834.sh
  test/runnable/link846.sh
  test/runnable/linkdebug.sh
  test/runnable/test10386.sh
  test/runnable/test10567.sh
  test/runnable/test13666.sh
  test/runnable/test13742.sh
  test/runnable/test13774.sh
  test/runnable/test16096.sh
  test/runnable/test17619.sh
  test/runnable/test18141.sh
  test/runnable/test18335.sh
  test/runnable/test2.sh
  test/runnable/test35.sh
  test/runnable/test39.sh
  test/runnable/test44.sh
  test/runnable/test9287.sh
  test/runnable/test9377.sh
  test/runnable/test_shared.sh
  test/sh_do_test.sh
Labels: 72h no objection -> merge, auto-merge

#8019 fix Issue 18597 - more unsafe unaligned pointer errors
  src/dmd/dstruct.d
  src/dmd/initsem.d
  test/fail_compilation/test18597.d
Labels: Bug Fix, Vision, auto-merge

#8050 Fix issue 18242 - Warn if object.Exception is missing
  src/dmd/statementsem.d
  test/compilable/b18242.d
Labels: Bug Fix, auto-merge

#8068 Remove redundant -c from test/compilable
  test/compilable/b6395.d
  test/compilable/ddoc9789.d
  test/compilable/ddocunittest.d
  test/compilable/header18364.d
  test/compilable/minimal.d
  test/compilable/sw_transition_complex.d
  test/compilable/sw_transition_field.d
  test/compilable/sw_transition_tls.d
  test/compilable/test17541.d
  test/compilable/test17752.d
  test/compilable/test6395.d
  test/compilable/test7190.d
  test/compilable/test9057.d
  test/compilable/test9399.d
  test/compilable/test9436.d
  test/compilable/testDIP37.d
  test/compilable/testDIP37_10302.d
  test/compilable/testDIP37_10421.d
  test/compilable/testDIP37a.d
Labels: Trivial, auto-merge

#8069 Set -euo pipefail by default for all bash scripts
  test/compilable/crlf.sh
  test/compilable/issue17167.sh
  test/compilable/jsonNoOutFile.sh
  test/compilable/test14894.sh
  test/compilable/test18367.sh
  test/compilable/test6461.sh
  test/compilable/testclidflags.sh
  test/runnable/depsprot.sh
  test/runnable/gdb15729.sh
  test/runnable/link14198a.sh
  test/runnable/link14834.sh
  test/runnable/link846.sh
  test/runnable/linkdebug.sh
  test/runnable/test10386.sh
  test/runnable/test10567.sh
  test/runnable/test13666.sh
  test/runnable/test13742.sh
  test/runnable/test16096.sh
  test/runnable/test18141.sh
  test/runnable/test18335.sh
  test/runnable/test2.sh
  test/runnable/test35.sh
  test/runnable/test39.sh
  test/runnable/test44.sh
  test/runnable/test_shared.sh
  test/sh_do_test.sh
Labels: auto-merge

#8073 refactor: dmangle.d
  src/dmd/dmangle.d
Labels: Easy Review, auto-merge

#8066 Fix Issue 18647 - Use of delete should be allowed without a deprecation in a deprecated scope
  src/dmd/expressionsem.d
  test/compilable/test17906.d
Labels: Enhancement

#8065 fix Issue 18461 - codegen bug - OPbt expressions and assignments to a…
  src/dmd/backend/gflow.c
  src/dmd/backend/gother.c
  test/runnable/mars1.d
Labels: Bug Fix, auto-merge

#8077 fix Issue 17942 - Enums are evaluated differently in global scope
  src/dmd/semantic2.d
  test/compilable/test17942.d
Labels: Bug Fix, auto-merge

#8072 Fix Issue 18645 - DMD segmentation fault (Enum Initialization)
  src/dmd/dsymbolsem.d
  test/compilable/test18645.d
Labels: Bug Fix, Regression

#8074 fix Issue 16189 - Optimizer bug, with simple test case
  src/dmd/backend/gloop.c
  test/runnable/mars1.d
Labels: Bug Fix, auto-merge

#8057 Fix issue 18489 - SROA w/ vector arguments
  src/dmd/backend/gsroa.c
  test/compilable/b18489.d
Labels: Bug Fix

#8079 Consolidate information on running the testsuite in a README
  test/Makefile
  test/README.md
  test/d_do_test.d
Labels: auto-merge, documentation

#8084 test18367: use proper library extension for Windows
  test/compilable/test18367.sh
Labels: auto-merge

#8085 windows: fix sh failures not triggering test suite failure
  test/sh_do_test.sh
Labels: auto-merge

#8088 Remove myself as code owner
  CODEOWNERS
Labels: Trivial, auto-merge

#8086 fix Issue 18661 - auto ref and return attribute inference
  src/dmd/statementsem.d
  test/compilable/test17512.d
Labels: Bug Fix, auto-merge

#8090 Fix Issue 18578 - First enum value assigned 0 instead of EnumBaseType.init
  src/dmd/dsymbolsem.d
  test/compilable/test18578.d
  test/fail_compilation/diag7477.d
Labels: Enhancement, auto-merge

#8093 src/posix.mak: use rm -f to fix the nightlies
  src/posix.mak
Labels: Blocking Other Work, Trivial, auto-merge

#8092 Fix issue 17874 - Static arrays & memset
  src/dmd/e2ir.d
  test/runnable/mars1.d
Labels: Bug Fix, auto-merge

#8082 Fix Issue 18197 - Correct optimization for OPpair in x87 mode
  src/dmd/backend/cgelem.c
  test/compilable/b18197.d
Labels: Bug Fix, auto-merge

#8097 SemaphoreCi: fix BRANCH detection
  semaphoreci.sh
Labels: Blocking Other Work

#8099 revert #7890 for x87 code gen
  src/dmd/backend/cod1.c
Labels: auto-merge

#7820 recognize erroneous uses of C types
  src/dmd/dscope.d
  src/dmd/id.d
  src/dmd/lexer.d
  src/dmd/parse.d
  test/fail_compilation/cerrors.d
  test/fail_compilation/ctypes.d
  test/fail_compilation/widechars.d
Labels: Easy Review, auto-merge

#8095 Fix Issue 18670 - compiler segfault if new on a union type with dip1000
  src/dmd/expressionsem.d
  test/compilable/test18670.d
Labels: Bug Fix, Vision

#8101 Fix Issue 18694 - pure functions using static/global structs with no fields should pass compilation
  src/dmd/expression.d
  test/compilable/test18694.d
Labels: Enhancement, auto-merge

#8083 Add postscript.sh run environment
  test/Makefile
  test/compilable/extra-files/ddocAny-postscript.sh
  test/compilable/extra-files/ddocYear-postscript.sh
  test/compilable/extra-files/depsOutput.sh
  test/compilable/extra-files/header-postscript.sh
  test/compilable/extra-files/json-postscript.sh
  test/compilable/extra-files/rdepsOutput.sh
  test/compilable/extra-files/test7754-postscript.sh
  test/runnable/extra-files/a20-postscript.sh
  test/runnable/extra-files/bug9010-postscript.sh
  test/runnable/extra-files/cov2-postscript.sh
  test/runnable/extra-files/hello-profile-postscript.sh
  test/runnable/extra-files/sieve-postscript.sh
  test/runnable/extra-files/statictor-postscript.sh
  test/runnable/extra-files/test17868-postscript.sh
  test/tools/d_do_test.d
  test/tools/postscript.sh
  test/tools/sanitize_json.d
  test/tools/sh_do_test.sh
Labels: 72h no objection -> merge, Continuous Integration, auto-merge

#7816 End deprecation phase of read-modify-write on shared variables.
  changelog/rwm-shared-error.dd
  src/dmd/expression.d
  test/fail_compilation/diag3672.d
  test/fail_compilation/diag3672a.d
  test/fail_compilation/fail3672.d
Labels: Deprecation -> Error, Vision, auto-merge

#8105 isReturnOnStack: fix link to the changelog entry
  changelog/isReturnOnStack.dd
Labels: Trivial, auto-merge, documentation

#8042 Deprecate class allocators and deallocators
  changelog/deprecate_class_allocators.dd
  src/dmd/dsymbolsem.d
  src/dmd/func.d
  test/compilable/disable_new.d
  test/compilable/vgc1.d
  test/fail_compilation/disable_new.d
  test/fail_compilation/fail14249.d
  test/fail_compilation/fail14407.d
  test/fail_compilation/fail14486.d
  test/fail_compilation/fail7848.d
  test/fail_compilation/failmemalloc.d
  test/fail_compilation/nogc1.d
Labels: Vision, auto-merge

#8100 Fix Issue 18688 - Constructors shouldn't have implicit super call if it throws
  src/dmd/expressionsem.d
  test/compilable/test18688.d
Labels: Enhancement, auto-merge

#7912 fix Issue 18459 - The static array ABI doesn't match the struct ABI
  src/dmd/argtypes.d
  test/runnable/test_cdstrpar.d
  test/runnable/testargtypes.d
Labels: Bug Fix, auto-merge

#8102 Put DMD's binary in 'generated' instead of TMP when using AUTO_BOOTSTRAP=1
  src/posix.mak
Labels: 72h no objection -> merge, Continuous Integration, makefiles

#8106 glue.d: refactor to use foreach
  src/dmd/glue.d
Labels: Easy Review, auto-merge
