Repository dlang/dmd, pull requests merged in 2018-07, with the labels that each got.

#8391 Adapt dmd.root.longdouble to LDC
  src/dmd/root/longdouble.d
  src/dmd/root/longdouble.h
Labels: auto-merge

#8424 convert gflow.c to D
  src/dmd/backend/gflow.d
  src/dmd/backend/gloop.c
  src/dmd/backend/go.h
  src/dmd/backend/goh.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion

#8408 fix Issue 19035 - Escape in scope inference, improve scope inference
  src/dmd/declaration.d
  src/dmd/escape.d
  src/dmd/semantic3.d
  test/fail_compilation/retscope6.d
Labels: Bug Fix, Vision

#8428 Fix Issue 19024 - [ICE] AssertError@dmd/dsymbolsem.d(4317): Assertion failure
  src/dmd/dsymbolsem.d
  test/compilable/ice14739.d
  test/fail_compilation/fail17492.d
Labels: Bug Fix, Regression

#8422 Refactor cppmanglewin
  src/dmd/cppmanglewin.d
Labels: auto-merge

#8433 refactor glocal.d
  src/dmd/backend/glocal.d
Labels: Easy Review, auto-merge

#8427 Use `const ref Loc loc` in all constructors
  src/dmd/aggregate.d
  src/dmd/aliasthis.d
  src/dmd/astbase.d
  src/dmd/dclass.d
  src/dmd/declaration.d
  src/dmd/dimport.d
  src/dmd/dmodule.d
  src/dmd/expression.d
  src/dmd/parse.d
Labels: Easy Review, auto-merge

#8435 gother.d: whitespace formatting
  src/dmd/backend/gother.d
Labels: Easy Review, Refactoring, auto-merge

#8434 gdag.d: whitespace formatting
  src/dmd/backend/gdag.d
Labels: Refactoring, auto-merge

#8430 convert gloop.c to D
  src/dmd/backend/evalu8.d
  src/dmd/backend/gloop.d
  src/dmd/tk/mem.c
  src/dmd/tk/mem.h
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, auto-merge

#8436 gflow.d: whitespace formatting
  src/dmd/backend/gflow.d
Labels: Easy Review, Refactoring, auto-merge

#8441 gloop.d: whitespace formatting
  src/dmd/backend/gloop.d
Labels: Easy Review, Refactoring, auto-merge

#8438 Change deprecation to error for C-style array syntax
  changelog/error_for_c-style_arrays.dd
  src/dmd/parse.d
  test/compilable/callconv.d
  test/compilable/imports/test63a.d
  test/compilable/interpret3.d
  test/compilable/test66.d
  test/fail_compilation/diag_cstyle.d
  test/runnable/bitops.d
  test/runnable/delegate.d
  test/runnable/dhry.d
  test/runnable/foreach3.d
  test/runnable/foreach4.d
  test/runnable/imports/inline2a.d
  test/runnable/imports/test11931d.d
  test/runnable/interpret.d
  test/runnable/printargs.d
  test/runnable/template1.d
  test/runnable/template2.d
  test/runnable/template9.d
  test/runnable/test11.d
  test/runnable/test15.d
  test/runnable/test17.d
  test/runnable/test19.d
  test/runnable/test22.d
  test/runnable/test34.d
  test/runnable/test4.d
  test/runnable/test42.d
  test/runnable/test48.d
  test/runnable/test8.d
  test/runnable/testaa.d
  test/runnable/testaa2.d
  test/runnable/testdt.d
  test/runnable/testthread.d
  test/runnable/traits_getPointerBitmap.d
  test/runnable/untag.d
Labels: Deprecation -> Error, Diagnostic Messages, auto-merge

#8418 Add different ENABLE + unittest modes to build.d
  .circleci/run.sh
  src/build.d
  src/dmd/asttypename.d
  src/posix.mak
Labels: 72h no objection -> merge, Continuous Integration, auto-merge

#8431 Upgrade gdc to gdc-8
  ci.sh
  src/posix.mak
Labels: Blocking Other Work, auto-merge

#8412 Changed 'body' to 'do' x2
  src/dmd/cond.d
Labels: auto-merge

#7421 make outbuffer printf nothrow
  src/dmd/root/outbuffer.d
Labels: auto-merge

#8444 Bump the version for AUTO_BOOTSTRAPPING to 2.079.1
  src/posix.mak
Labels: auto-merge

#8442 rename md5.d to md5.di
  src/dmd/backend/md5.di
  src/posix.mak
  src/win32.mak
Labels: D Conversion, Easy Review, auto-merge

#8357 Go.c to d
  src/dmd/backend/cgcod.c
  src/dmd/backend/code.h
  src/dmd/backend/go.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion

#8446 Build __vtbl type as a static array of pointer type
  src/dmd/dclass.d
  src/dmd/expressionsem.d
Labels: GDC, auto-merge

#8448 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/deprecate_ctor_in_static_block.dd
  changelog/deprecate_this_super_as_types.dd
  changelog/expression-based_contract_syntax.dd
  changelog/extern_cpp_overhaul.dd
  changelog/fix16206.dd
  changelog/getlinkage_for_classes.dd
  changelog/implicit_catch_error.dd
  changelog/implicit_enum_comparison_error.dd
  changelog/implicit_string_concatenation_error.dd
  changelog/iretq.dd
  changelog/min_runtime_classes.dd
  changelog/redundant_stc_error.dd
  src/dmd/dsymbolsem.d
  src/dmd/root/longdouble.d
  src/dmd/root/longdouble.h
  test/compilable/ice14739.d
  test/fail_compilation/fail17492.d
Labels: Bug Fix, auto-merge

#8439 convert compress.c to compress.d
  src/dmd/backend/compress.d
  src/dmd/backend/global.d
  src/dmd/backend/global.h
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion

#8450 Fix Issue 19053 - debug should escape @safe
  changelog/debug-unsafe.dd
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/typesem.d
  test/compilable/test16492.d
Labels: Bug Fix, auto-merge

#8285 Revert mangling of D `long` back to C++ `long` on 64-bit OS X
  changelog/osx64_long_cppmangling.dd
  src/dmd/cppmangle.d
  src/dmd/target.d
  src/dmd/target.h
  test/runnable/cppa.d
  test/runnable/externmangle.d
Labels: 72h no objection -> merge, auto-merge

#8237 Fix Issue 18743 - ConditionalExpression with AssignExpression should require parens
  changelog/cond_assign.dd
  src/dmd/parse.d
  test/fail_compilation/bug18743.d
Labels: 72h no objection -> merge, Enhancement, auto-merge

#8453 Remove usage of initializerToExpression from parse.d
  src/dmd/astbase.d
  src/dmd/parse.d
Labels: Easy Review, auto-merge

#8456 Fix Issue 19064 - [REG2.081] Vibe.d's InterfaceProxy no longer works
  src/dmd/traits.d
  test/compilable/test17373.d
Labels: Bug Fix, auto-merge

#8457 [Trivial] Fix missing newline regression in -v predefs output
  src/dmd/mars.d
Labels: Trivial, auto-merge

#8458 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/dmd/traits.d
  test/compilable/test17373.d
Labels: Bug Fix, auto-merge, stable -> master

#8463 Fix issue 19066 - Allow using symobls Object inside a struct without a toHash override
  src/dmd/clone.d
  test/compilable/test19066.d
Labels: Bug Fix, auto-merge

#8465 Avoid weird `!<ClassKind> == <ClassKind.cpp>`
  src/dmd/dsymbolsem.d
Labels: auto-merge

#8470 gflow.d: use foreach
  src/dmd/backend/gflow.d
Labels: Easy Review, Refactoring, auto-merge

#8471 add ListRange
  src/dmd/backend/dlist.d
Labels: Easy Review, Refactoring, auto-merge

#8469 add import hints for stdlib
  src/dmd/imphint.d
Labels: Easy Review, auto-merge

#8466 convert tk/mem.h to memh.d
  src/dmd/backend/gloop.d
  src/dmd/backend/memh.d
  src/posix.mak
  src/win32.mak
Labels: D Conversion

#8461 Don't fail test9287 with 'Device or resource busy'
  test/runnable/test9287.sh
Labels: auto-merge

#8468 convert cgcs.c to D
  src/dmd/backend/cgcs.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion

#7531 Fix invalid characters in mangling
  src/dmd/dmangle.d
  src/dmd/dsymbolsem.d
Labels: 72h no objection -> merge, Blocking Other Work, Bug Fix, Regression, auto-merge

#8474 convert ee.c to ee.d
  src/dmd/backend/ee.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, auto-merge

#8477 convert cod5.c to cod5.d
  src/dmd/backend/cod5.d
  src/dmd/eh.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, auto-merge

#8479 Move semantic methods out of expression.d
  src/dmd/attrib.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/objc.d
  src/dmd/typesem.d
Labels: auto-merge

#8486 [REG] Fix Issue 19076 - dmd 2.081 crashed by getVirtualFunctions for a interface extended interface
  src/dmd/traits.d
  test/fail_compilation/fail19076.d
Labels: Easy Review, Enhancement, Regression, auto-merge

#8485 eliminate global use from compdom()
  src/dmd/backend/gloop.d
Labels: Refactoring, auto-merge

#8451 Fix Issue 19059 - Disallow `08` and `09` in integer literal
  src/dmd/lexer.d
  test/fail_compilation/fix19059.d
Labels: Bug Fix, WIP, auto-merge

#8491 Add missing field to SwitchErrorStatement
  src/dmd/statement.h
Labels: GDC, Trivial, auto-merge

#8493 purify mangleSpecialName()
  src/dmd/cppmanglewin.d
Labels: Refactoring, auto-merge

#8494 don't reimplement deduceWild()
  src/dmd/expressionsem.d
Labels: Refactoring, auto-merge

#8497 array constructor sets length
  src/dmd/constfold.d
  src/dmd/ctfeexpr.d
  src/dmd/declaration.d
  src/dmd/dinterpret.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/init.d
  src/dmd/initsem.d
  src/dmd/inline.d
  src/dmd/mars.d
  src/dmd/mtype.d
  src/dmd/opover.d
  src/dmd/root/array.d
  src/dmd/semantic3.d
  src/dmd/statement.d
  src/dmd/typesem.d
Labels: Easy Review, Refactoring, auto-merge

#8495 deduceWild() returns MOD
  src/dmd/mtype.d
Labels: Refactoring, auto-merge

#8499 add type parameter to ArrayLiteralExp constructors
  src/dmd/constfold.d
  src/dmd/ctfeexpr.d
  src/dmd/dinterpret.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/initsem.d
  src/dmd/mtype.d
  src/dmd/parse.d
  src/dmd/traits.d
Labels: Easy Review, Refactoring, auto-merge

#8500 small refactor of functionParameters()
  src/dmd/expressionsem.d
Labels: Easy Review, Refactoring, auto-merge

#8049 Fix Issue 18620 - error cannot be interpreted at compile time is missing context where error occurs
  src/dmd/ctfeexpr.d
  src/dmd/dinterpret.d
  src/dmd/dsymbolsem.d
  src/dmd/expression.d
  src/dmd/initsem.d
  src/dmd/tokens.d
  test/fail_compilation/fail18620.d
Labels: Bug Fix

#8481 convert nteh.c to D
  src/dmd/backend/cdef.h
  src/dmd/backend/code.d
  src/dmd/backend/code_x86.d
  src/dmd/backend/nteh.d
  src/dmd/backend/rtlsym.c
  src/dmd/backend/rtlsym.h
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion

#8501 refactor semanticY()
  src/dmd/expressionsem.d
Labels: Easy Review, Refactoring, auto-merge

#8492 Fix issue 19081 - defining enum with UDA at statements level
  src/dmd/parse.d
  test/compilable/test19081.d
Labels: Enhancement

#8502 sideeffect.d: small refactor
  src/dmd/sideeffect.d
Labels: Easy Review, Refactoring, auto-merge

#8426 convert blockopt.c to blockopt.d
  src/dmd/backend/blockopt.d
  src/dmd/backend/cc.d
  src/dmd/backend/el.d
  src/dmd/backend/el.h
  src/dmd/mars.d
  src/dmd/root/ctfloat.d
  src/dmd/root/longdouble.d
  src/dmd/tk/mem.h
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion

#8510 convert backend/cg.c to D
  src/build.d
  src/dmd/backend/cg.d
  src/dmd/backend/code.h
  src/dmd/backend/code_x86.d
  src/dmd/backend/optabgen.c
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion

#8513 modernize loops in gloop.d
  src/dmd/backend/gloop.d
Labels: Easy Review, Refactoring, auto-merge

#8511 convert cgreg.c to D
  src/dmd/backend/cc.d
  src/dmd/backend/cgreg.d
  src/dmd/backend/code.d
  src/dmd/backend/code_x86.h
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion

#8505 Improve build_opAssign documentation + minor refactoring
  src/dmd/clone.d
Labels: Easy Review, Refactoring, documentation

#8518 convert type.c to dtype.d
  src/dmd/backend/cc.d
  src/dmd/backend/cdef.d
  src/dmd/backend/dtype.d
  src/dmd/backend/type.c
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion

#8515 convert debug.c to debugprint.d
  src/build.d
  src/dmd/backend/debug.c
  src/dmd/backend/debugprint.d
  src/dmd/backend/global.h
  src/dmd/backend/optabgen.c
  src/dmd/backend/ty.h
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, auto-merge

#8516 fix issue 19112 - Associative array opIn with static array key fails …
  src/dmd/expressionsem.d
  test/fail_compilation/test19112.d
  test/runnable/testaa.d
Labels: Bug Fix, auto-merge

#8521 -betterC: Add support for types when comparing arrays
  test/runnable/betterc.d
Labels: auto-merge

#8520 convert symbol.c to D
  src/dmd/backend/cc.d
  src/dmd/backend/cc.h
  src/dmd/backend/cgcod.c
  src/dmd/backend/cgxmm.c
  src/dmd/backend/cod3.c
  src/dmd/backend/global.d
  src/dmd/backend/global.h
  src/dmd/backend/symbol.c
  src/dmd/backend/symbol.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion, auto-merge

#8522 Add missing deprecation comment for invalid integer
  src/dmd/lexer.d
Labels: auto-merge

#8524 convert el.c to elem.d
  src/dmd/backend/code.d
  src/dmd/backend/elem.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/vcbuild/dmd_backend.vcxproj.filters
  src/win32.mak
Labels: D Conversion

#8526 Fix Issue 15373 - Segfault when using typeid on extern(C++) class with virtual functions
  src/dmd/expressionsem.d
  test/fail_compilation/test15373.d
  test/runnable/test15373.d
Labels: Bug Fix, auto-merge

#8525 Add D_ModuleInfo D_Exceptions and D_TypeInfo version identifiers
  src/dmd/mars.d
  test/compilable/betterCarray.d
  test/compilable/betterc.d
  test/compilable/version.d
Labels: auto-merge

#8527 Add changelog for D_ModuleInfo, D_Exceptions, and D_TypeInfo version identifiers
  changelog/betterc_versions.dd
Labels: auto-merge

#8519 Fix Issue 19107 - -de produces compilation error, -dw does not
  src/dmd/errors.d
  src/dmd/globals.d
  src/dmd/mtype.d
  test/compilable/imports/test19107a.d
  test/compilable/imports/test19107b.d
  test/compilable/test19107.d
Labels: Blocking Other Work, Bug Fix
