Repository dlang/dmd, pull requests merged in 2019-02, with the labels that each got.

#9309 start using reg_t for registers
  src/dmd/backend/cgcod.d
  src/dmd/backend/code.d
  src/dmd/backend/code_x86.d
Labels: Easy Review, Refactoring, auto-merge

#9312 use NOREG for not-a-register
  src/dmd/backend/cgcod.d
Labels: Refactoring, auto-merge

#9313 more uint => reg_t conversion
  src/dmd/backend/cg87.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/cgen.d
  src/dmd/backend/cgxmm.d
  src/dmd/backend/cod1.d
  src/dmd/backend/cod2.d
  src/dmd/backend/cod3.d
  src/dmd/backend/cod4.d
  src/dmd/backend/code.d
Labels: Easy Review, Refactoring

#9314 bring reg_t to cgreg.d
  src/dmd/backend/cgreg.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code.d
Labels: Easy Review, Refactoring, auto-merge

#9315 bring reg_t to cgxmm.d
  src/dmd/backend/cgxmm.d
Labels: Easy Review, Refactoring, auto-merge

#9272 fix Issue 19618 - Incorrect conversion of function returning `typeof(null)` to function returning an associative array
  src/dmd/mtype.d
  test/runnable/nulltype.d
Labels: Blocking Other Work, Bug Fix, GDC, auto-merge

#9318 cod3.d: convert to reg_t
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod1.d
  src/dmd/backend/cod2.d
  src/dmd/backend/cod3.d
  src/dmd/backend/cod4.d
  src/dmd/backend/code.d
  src/dmd/backend/nteh.d
Labels: Easy Review, Refactoring, auto-merge

#9316 bring reg_t to cod2.d
  src/dmd/backend/cg87.d
Labels: Easy Review, Refactoring, auto-merge

#9319 fix size calculation on pairs
  src/dmd/backend/evalu8.d
Labels: auto-merge

#9240 testsuite: Add TEST_OUTPUT to most verbose compilable tests
  test/compilable/b16382.d
  test/compilable/b17111.d
  test/compilable/callconv.d
  test/compilable/extra-files/json.out
  test/compilable/extra-files/json2.out
  test/compilable/interpret3.d
  test/compilable/json.d
  test/compilable/json2.d
  test/compilable/test11471.d
  test/compilable/test15177.d
  test/compilable/test17419.d
  test/compilable/test17791.d
  test/compilable/test9701.d
Labels: 72h no objection -> merge, Continuous Integration, auto-merge

#9322 use opcode_t to represent CPU opcodes instead of uint
  src/dmd/backend/code_x86.d
  src/dmd/backend/iasm.d
  src/dmd/backend/ptrntab.d
Labels: Easy Review, Refactoring, auto-merge

#9321 Fix 'reinterpret' casts of StringExp to static array with implicit extension
  src/dmd/dcast.d
  test/runnable/test19639.d
Labels: Bug Fix, auto-merge

#9324 cgxmm.d: add opcode_t
  src/dmd/backend/cgxmm.d
  src/dmd/backend/cod4.d
  src/dmd/backend/code.d
  src/dmd/backend/code_x86.d
Labels: Easy Review, Refactoring

#9264 Add support for the in operator in dassert
  src/dmd/expressionsem.d
Labels: auto-merge

#9327 remove unnecessary REX prefix byte from 32 bit MOV
  src/dmd/backend/cod1.d
  test/runnable/test_cdcmp.d
  test/runnable/test_cdstrpar.d
Labels: auto-merge

#9330 hoist commas out of memcmp expressions
  src/dmd/backend/cgelem.d
Labels: auto-merge

#9332 remove dead code for struct equality test
  src/dmd/e2ir.d
Labels: auto-merge

#9335 Make a couple small code quality changes in thematic breaks
  src/dmd/doc.d
Labels: auto-merge

#9342 [dmd-cxx] testsuite: Add another test for issue 18057
  src/dstruct.c
  test/fail_compilation/fail18057b.d
Labels: C++ Port, auto-merge

#9343 Fix Issue 19574 Fix crashing with template declaration used with mangle only namespaces.
  src/dmd/nspace.d
  test/compilable/test19574.d
Labels: Bug Fix, auto-merge

#9340 Slice struct types as well
  src/dmd/backend/cod1.d
  src/dmd/backend/evalu8.d
  src/dmd/backend/gsroa.d
Labels: auto-merge

#9347 oper.d: use OPER alias
  src/dmd/backend/oper.d
  src/dmd/backend/optabgen.d
Labels: Easy Review, Refactoring, auto-merge

#9345 Improve compile-time performance of capitalisation
  src/dmd/cli.d
Labels: auto-merge

#9333 Add unit test runner
  .circleci/run.sh
  dub.sdl
  test/Makefile
  test/README.md
  test/run.d
  test/tools/paths.d
  test/tools/unit_test_runner.d
  test/unit/self_test.d
  test/unit/support.d
Labels: Blocking Other Work, auto-merge

#9329 Fix issue 19654: cannot have final methods in objc interfaces
  src/dmd/func.d
  test/compilable/objc_interface_final_19654.d
Labels: Bug Fix, Regression, auto-merge

#9349 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
Labels: auto-merge

#8528 Add `deinitializeDMD` function to deinitialize the front end
  src/dmd/builtin.d
  src/dmd/dmodule.d
  src/dmd/expression.d
  src/dmd/frontend.d
  src/dmd/globals.d
  src/dmd/id.d
  src/dmd/mtype.d
  src/dmd/objc.d
  src/dmd/target.d
  test/unit/deinitialization.d
  test/unit/self_test.d
Labels: Blocking Other Work, auto-merge

#9298 fix Issue 19607 - [ICE] dmd/e2ir.d(117): Invalid type mTYconst|TYstruct
  src/dmd/ctfeexpr.d
  src/dmd/dinterpret.d
  src/dmd/e2ir.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/hdrgen.d
  src/dmd/parse.d
  src/dmd/tokens.d
  src/dmd/tokens.h
  src/dmd/typesem.d
  src/dmd/visitor.d
  src/dmd/visitor.h
  test/compilable/ctfesimd.d
  test/compilable/test19224.d
  test/runnable/test19223.d
Labels: Bug Fix, auto-merge

#9337 [trivial] Remove an unused local variable
  src/dmd/utils.d
Labels: Trivial, auto-merge

#9352 cod4.d: add OPER
  src/dmd/backend/cod4.d
Labels: Easy Review, Refactoring, auto-merge

#9346 Get rid of concatination in a loop
  src/dmd/cli.d
Labels: auto-merge

#9336 Add a changelog entry for the -preview/-revert flags
  changelog/preview-flags.dd
Labels: auto-merge, documentation

#9351 special case OPpair to push on parameter stack
  src/dmd/backend/cod1.d
Labels: auto-merge

#9353 use LEA instead of 0x8D
  src/dmd/backend/cgobj.d
  src/dmd/backend/cgsched.d
  src/dmd/backend/cgxmm.d
  src/dmd/backend/cod1.d
  src/dmd/backend/cod4.d
  src/dmd/backend/elfobj.d
Labels: Easy Review, Refactoring, auto-merge

#9354 cgen.d etc.: add opcode_t
  src/dmd/backend/cg87.d
  src/dmd/backend/cgen.d
  src/dmd/backend/code.d
  src/dmd/backend/codebuilder.d
  src/dmd/backend/nteh.d
Labels: Easy Review, Refactoring, auto-merge

#9355 Do not generate debug info for the unit test runner when Optlink is used
  test/tools/unit_test_runner.d
Labels: auto-merge

#9356 fix issue 12001 - __traits(isSame) does not work with the basic types
  src/dmd/traits.d
  test/compilable/b12001.d
Labels: Bug Fix, auto-merge

#9344 Remove global token freelist
  src/dmd/iasmgcc.d
  src/dmd/lexer.d
  src/dmd/parse.d
  src/dmd/tokens.d
Labels: auto-merge

#9350 Add customizable diagnostic reporter for the lexer and parser
  src/dmd/compiler.d
  src/dmd/dmodule.d
  src/dmd/doc.d
  src/dmd/dsymbolsem.d
  src/dmd/errors.d
  src/dmd/expressionsem.d
  src/dmd/frontend.d
  src/dmd/iasmgcc.d
  src/dmd/lexer.d
  src/dmd/parse.d
  src/dmd/statement.d
  src/examples/avg.d
  src/examples/impvisitor.d
  test/dub_package/lexer.d
  test/dub_package/parser.d
  test/unit/lexer/diagnostic_reporter.d
  test/unit/parser/diagnostic_reporter.d
  test/unit/support.d
Labels: Blocking Other Work, auto-merge

#9357 fix Issue 19672 - Function uses the stack to read a static array para…
  src/dmd/backend/cod1.d
  test/runnable/test19672.d
Labels: Bug Fix

#9360 fix issue 19523 - "undefined identifier" causes DMD crash
  src/dmd/expression.d
  test/fail_compilation/b19523.d
Labels: Bug Fix, auto-merge

#9363 fix Issue 19676 - Destructor not called for returned temporary that w…
  src/dmd/expression.d
  test/runnable/sdtor.d
Labels: Bug Fix

#9364 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/dmd/backend/cod1.d
  src/dmd/expression.d
  test/fail_compilation/b19523.d
  test/runnable/test19672.d
Labels: Bug Fix

#9365 fix issue 15875 - case of undetected circular reference in function parameter
  src/dmd/expressionsem.d
  test/fail_compilation/b15875.d
Labels: Bug Fix, auto-merge

#9368 add OutBuffer.extractSlice()
  src/dmd/root/outbuffer.d
Labels: Easy Review, Refactoring, auto-merge

#9370 Fixup changelog entries
  changelog/assert.dd
  changelog/stdcpp.dd
Labels: auto-merge, documentation

#9369 Fix Issue 17684 - [REG 2.062] static alias this (Part 5)
  src/dmd/expressionsem.d
  test/runnable/test17684.d
Labels: Bug Fix, auto-merge

#9338 == lowering needs to access private fields
  src/dmd/opover.d
  test/compilable/fieldwise.d
  test/compilable/imports/impfieldwise.d
Labels: Blocking Other Work, auto-merge

#9362 fix Issue 18573 - cast(void) leads to floating point return value not…
  src/dmd/e2ir.d
  test/runnable/test22.d
Labels: Bug Fix, auto-merge

#9269 Define static xxxExp::emplace member function
  src/dmd/expression.d
  src/dmd/expression.h
  src/tests/cxxfrontend.c
Labels: GDC, auto-merge

#9371 [dmd-cxx] Backport extern(C++, "namespace") and CppRuntime
  src/cond.c
  src/cppmangle.c
  src/cppmanglewin.c
  src/dsymbol.c
  src/dsymbol.h
  src/mars.c
  src/nspace.c
  src/nspace.h
  src/parse.c
  src/parse.h
  test/compilable/cppmangle3.d
  test/compilable/test19574.d
  test/fail_compilation/cppmangle.d
  test/fail_compilation/reserved_version.d
  test/fail_compilation/reserved_version_switch.d
Labels: C++ Port, auto-merge

#9334 #19652 Fix chained alias this.
  src/dmd/dcast.d
  test/compilable/test19652.d
  test/runnable/bug19652.d
Labels: Bug Fix, auto-merge

#9367 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
Labels: auto-merge

#9373 fix issue 19685 - Revert "aggregate, reduce the complexity of the loo…
  src/dmd/aggregate.d
  src/dmd/attrib.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  test/fail_compilation/b19685.d
  test/fail_compilation/test_overlap.d
Labels: Bug Fix, auto-merge

#9372 Fix issue 19679, add test
  src/dmd/func.d
  test/runnable/test19679.d
Labels: Bug Fix, auto-merge

#9376 backend: Document that RTLSYM_ARRAYEQ is unused
  src/dmd/backend/rtlsym.d
Labels: Trivial, auto-merge

#9374 for non-ptr params, return-scope goes away
  src/dmd/typesem.d
  test/compilable/pr9374.d
  test/fail_compilation/retscope2.d
Labels: Blocking Other Work, Vision, auto-merge

#9377 Fix Issue 19688 - [ICE] Default function argument concatenation crashes DMD
  src/dmd/expression.d
  test/runnable/test19688.d
Labels: Bug Fix

#9378 Fix Issue 19687 - Wrong error for overloaded opDispatch + UFCS with non-existing function
  src/dmd/expressionsem.d
  test/fail_compilation/fail19687.d
Labels: Bug Fix, auto-merge

#9380 treat the null type as a pointer type
  src/dmd/mtype.d
Labels: auto-merge

#9381 Make leadingBlank into a boolean
  src/dmd/doc.d
Labels: auto-merge

#9382 dmd.root.filename: Define PATH_MAX if missing in druntime
  src/dmd/root/filename.d
Labels: Regression, auto-merge

#9383 parameters have function scope too
  src/dmd/escape.d
  test/compilable/pr9383.d
Labels: Blocking Other Work, Vision, auto-merge

#9384 use OPER instead of uint in g*.d
  src/dmd/backend/gdag.d
  src/dmd/backend/gflow.d
  src/dmd/backend/glocal.d
  src/dmd/backend/gloop.d
  src/dmd/backend/gother.d
Labels: Easy Review, Refactoring, auto-merge

#9386 cod2.d: use opcode_t instead of uint
  src/dmd/backend/cod2.d
Labels: Easy Review, Refactoring, auto-merge

#9385 cod3.d: use opcode_t instead of uint
  src/dmd/backend/cod3.d
Labels: Easy Review, Refactoring, auto-merge

#9387 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/assert.dd
  changelog/stdcpp.dd
  src/dmd/aggregate.d
  src/dmd/attrib.d
  src/dmd/dcast.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/expressionsem.d
  src/dmd/root/filename.d
  test/compilable/test19652.d
  test/fail_compilation/b19685.d
  test/fail_compilation/fail19687.d
  test/fail_compilation/test_overlap.d
  test/runnable/bug19652.d
Labels: Bug Fix, auto-merge

#9389 cg87.d: use opcode_t instead of uint
  src/dmd/backend/cg87.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod1.d
Labels: Easy Review, Refactoring, auto-merge

#9390 Fix issue 19699: Obj-C segfault - in objc_glue.getClassName
  docs/objective-c_abi.md
  src/dmd/objc_glue.d
  test/compilable/objc_class.d
Labels: Bug Fix, auto-merge

#9323 Fix Issue 19441 - alias this causes partial assignment
  src/dmd/opover.d
  test/fail_compilation/fail19441.d
  test/runnable/test19441.d
  test/runnable/testaa.d
Labels: Enhancement

#9391 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  docs/objective-c_abi.md
  src/dmd/objc_glue.d
  test/compilable/objc_class.d
Labels: Bug Fix, auto-merge

#9392 Start to disable OSX-32 on the auto-tester
  posix.mak
Labels: auto-merge

#9220 infer 'return' for first arg
  src/dmd/escape.d
  test/compilable/scope.d
  test/compilable/test19097.d
  test/fail_compilation/retscope6.d
Labels: Vision, auto-merge

#9395 split getLevel() into two functions
  src/dmd/declaration.d
  src/dmd/escape.d
  src/dmd/func.d
Labels: Easy Review, Refactoring

#9396 Update D-Scanner version
  src/posix.mak
Labels: auto-merge

#9263 SemaphoreCI: Remove compiler versions locking
  semaphoreci.sh
Labels: Continuous Integration, auto-merge

#9400 [stable] Fix typo in -extern-std description
  src/dmd/cli.d
  src/dmd/globals.h
Labels: auto-merge
