Repository dlang/dmd, pull requests merged in 2019-04, with the labels that each got.

#9531 hdrgen.d: consolidate status into HdrGenState
  src/dmd/hdrgen.d
Labels: Easy Review, Refactoring, auto-merge

#9527 use constructor to build Loc
  src/dmd/doc.d
  src/dmd/lib.d
  src/dmd/parse.d
Labels: Easy Review, Refactoring

#9532 hdrgen.d: extract parameterToBuffer() from Visitor
  src/dmd/hdrgen.d
Labels: Refactoring

#9529 dmd.dmodule: fix memory leak in lookForSourceFile
  src/dmd/dmodule.d
Labels: auto-merge-squash

#9534 hdrgen.d: extract parametersToBuffer() from Visitor
  src/dmd/hdrgen.d
Labels: Refactoring, auto-merge

#9535 hdrgen.d: extract expToBuffer() from Visitor
  src/dmd/hdrgen.d
Labels: Refactoring, auto-merge

#9536 hdrgen.d: extract typeToBuffer() from Visitor
  src/dmd/hdrgen.d
Labels: Refactoring, auto-merge

#9537 hdrgen.d: extract objectToBuffer() from Visitor
  src/dmd/hdrgen.d
Labels: Refactoring, auto-merge

#9538 hdrgen.d: extract visitFuncIdentWithxxxxx() from Visitor
  src/dmd/hdrgen.d
Labels: Refactoring, auto-merge

#9539 hdrgen.d: extract initializerToBuffer() from Visitor
  src/dmd/hdrgen.d
Labels: Refactoring, auto-merge

#9540 hdergen.d: extract typeToBufferx() from Visitor
  src/dmd/hdrgen.d
  src/dmd/typesem.d
  test/fail_compilation/e7804_2.d
Labels: Refactoring, auto-merge

#9541 hdrgen.d: extract moduleToBuffer2() from Visitor
  src/dmd/frontend.d
  src/dmd/hdrgen.d
Labels: Refactoring, auto-merge

#9542 hdrgen.d: extract statementToBuffer() from Visitor
  src/dmd/hdrgen.d
Labels: Refactoring, auto-merge

#9543 hdrgen.d: fix unmatched brace
  src/dmd/hdrgen.d
Labels: auto-merge

#9544 hdrgen.d: extract conditionToBuffer() from Visitor
  src/dmd/hdrgen.d
Labels: Refactoring, auto-merge

#9545 hdrgen.d: extract templateParameterToBuffer() from Visitor
  src/dmd/hdrgen.d
Labels: Refactoring, auto-merge

#9546 hdrgen.d: replace accept() with expression/dsymbol ToBuffer()
  src/dmd/hdrgen.d
Labels: Refactoring, auto-merge

#9547 Fix Issue 19778 - ICE when accessing empty array at compile time
  src/dmd/dinterpret.d
  test/compilable/test19778.d
Labels: Bug Fix, auto-merge

#9548 hdrgen.d: extract expressionToBuffer() from Visitor
  src/dmd/hdrgen.d
Labels: Refactoring

#9550 Fix Issue 19782 - alias this appends null instead of inner/aliased element to array
  src/dmd/expressionsem.d
  test/runnable/test19782.d
Labels: Bug Fix, Regression, auto-merge

#9553 Advance 32 byte vector deprecation to error
  src/dmd/typesem.d
  test/compilable/vector_types.d
  test/fail_compilation/vector_types.d
Labels: auto-merge

#9552 hdrgen.d: split Visitor
  src/dmd/hdrgen.d
Labels: Refactoring, auto-merge

#9554 Clean up some messy/buggy markdown code
  src/dmd/doc.d
  test/compilable/ddoc_markdown_links.d
  test/compilable/extra-files/ddoc_markdown_links.html
Labels: auto-merge

#9555 hdrgen.d: prefix PrettyPrintVisitor with Dsymbol
  src/dmd/hdrgen.d
Labels: Refactoring, auto-merge

#9557 Fix `test/run.d` on macOS
  test/run.d
Labels: auto-merge

#9559 simplify attributesApply()
  src/dmd/hdrgen.d
  src/dmd/mtype.d
  src/dmd/traits.d
Labels: Refactoring

#9563 [dmd-cxx] Fix Issue 19778 - ICE when accessing empty array at compile time
  src/dinterpret.c
  test/compilable/test19778.d
Labels: Bug Fix, C++ Port, GDC

#9560 replace stcToChars with stcToString
  src/dmd/hdrgen.d
Labels: Easy Review, Refactoring

#9564 hdrgen: prefer strings to chars
  src/dmd/hdrgen.d
Labels: Easy Review, Refactoring, auto-merge

#9561 dmd.cond: Add VersionCondition.isVersionCondition
  src/dmd/cond.d
  src/dmd/cond.h
Labels: GDC, auto-merge

#9549 Advance deprecation of hex string literals (Error)
  changelog/dephexstrings.dd
  src/dmd/lexer.d
  test/fail_compilation/dephexstrings.d
  test/fail_compilation/fail136.d
  test/fail_compilation/lexer1.d
  test/fail_compilation/lexer2.d
  test/runnable/foreach4.d
  test/runnable/test15.d
  test/runnable/test20.d
  test/runnable/testdstress.d
  test/runnable/xtest46.d
  test/unit/lexer/diagnostic_reporter.d
Labels: auto-merge

#9464 fix Issue 19719 - Debugging string mixins using -mixin doesn't work
  src/dmd/backend/cv8.d
  src/dmd/parse.d
  test/runnable/extra-files/mixin.mixin
  test/runnable/testpdb.d
Labels: Bug Fix, auto-merge

#9565 build.d - Fix invalid file name '' error on Windows
  src/build.d
Labels: auto-merge-squash

#9521 Fix Issue 19775 - multiple argument string mixin doesn't expand tuples
  src/dmd/expressionsem.d
  test/compilable/b19775.d
Labels: Bug Fix, auto-merge

#9568 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  src/dmd/backend/cod2.d
  src/dmd/expressionsem.d
  src/dmd/toctype.d
  test/fail_compilation/fail19757_m32.d
  test/fail_compilation/fail19757_m64.d
  test/fail_compilation/ice19762.d
  test/fail_compilation/imports/b19762.d
  test/fail_compilation/imports/c19762.d
  test/runnable/test42.d
Labels: Bug Fix, auto-merge

#9567 Remove unused backend/platform_stub.c
  src/dmd/backend/platform_stub.c
Labels: D Conversion, auto-merge

#9570 bring const to RootObject.equals()
  src/dmd/access.d
  src/dmd/declaration.d
  src/dmd/dsymbol.d
  src/dmd/func.d
  src/dmd/identifier.d
Labels: Refactoring, WIP

#9572 Full qualify lowering to object.__ArrayCast
  src/dmd/expressionsem.d
Labels: auto-merge

#9558 Fixes issues 16271, 18825, 8065, 5050 - Allow function literals return by reference
  src/dmd/parse.d
  test/fail_compilation/diag16271.d
  test/runnable/funclit.d
Labels: Enhancement, auto-merge-squash

#9573 translate strtold.c to strtold.d
  src/build.d
  src/dmd/backend/strtold.c
  src/dmd/root/ctfloat.d
  src/dmd/root/strtold.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
  test/tools/unit_test_runner.d
Labels: Bug Fix, auto-merge

#9575 Remove C++ new/delete implementations from mem.c
  src/dmd/tk/mem.c
Labels: auto-merge

#9569 Convert fp.c to fp.d
  src/build.d
  src/dmd/backend/fp.c
  src/dmd/backend/fp.d
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: 72h no objection -> merge, auto-merge

#9576 Add more symbols to the import hinter
  src/dmd/imphint.d
  test/fail_compilation/imphint.d
Labels: auto-merge

#9289 Fix Issue 16657 and 11161 - alias this interacts with generated opCmp and opEquals
  changelog/alias_this_opEquals.dd
  src/dmd/opover.d
  test/compilable/test15292.d
  test/compilable/test16657.d
  test/runnable/aliasthis.d
  test/runnable/opover2.d
Labels: Enhancement, auto-merge

#9577 canthrow.d: eliminate nearly all casts
  src/dmd/canthrow.d
Labels: Easy Review, Refactoring, auto-merge

#9578 statement.d: add const, inout, pure, nothrow
  src/dmd/statement.d
Labels: Easy Review, Refactoring, auto-merge

#8507 Fix Issue 19099 - Struct with field that has postblit or destructor makes struct assignable
  src/dmd/mtype.d
  test/fail_compilation/fail19099.d
Labels: Bug Fix, auto-merge

#8344 Fix Issue 15361 - Incomprehensible error message: function declaration without return type
  src/dmd/parse.d
  test/fail_compilation/fail15361.d
Labels: Easy Review, Enhancement, auto-merge

#9580 dmangle.d: remove some casts
  src/dmd/dmangle.d
Labels: Easy Review, Refactoring, auto-merge

#9581 rewrite realToMangleBuffer()
  src/dmd/dmangle.d
Labels: Easy Review, Refactoring, auto-merge

#9574 Remove unused .h files from tk directory
  src/dmd/tk/filespec.h
  src/dmd/tk/list.h
  src/dmd/tk/vec.h
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: 72h no objection -> merge, auto-merge

#9584 Rename backend/memh.d to backend/mem.d
  src/dmd/backend/blockopt.d
  src/dmd/backend/cg87.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/cgen.d
  src/dmd/backend/cgobj.d
  src/dmd/backend/cgsched.d
  src/dmd/backend/cgxmm.d
  src/dmd/backend/cod1.d
  src/dmd/backend/cod2.d
  src/dmd/backend/cod3.d
  src/dmd/backend/cod4.d
  src/dmd/backend/codebuilder.d
  src/dmd/backend/cv8.d
  src/dmd/backend/dcgcv.d
  src/dmd/backend/dcode.d
  src/dmd/backend/dt.d
  src/dmd/backend/dtype.d
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/elem.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/filespec.d
  src/dmd/backend/global.d
  src/dmd/backend/gloop.d
  src/dmd/backend/machobj.d
  src/dmd/backend/mem.d
  src/dmd/backend/mscoffobj.d
  src/dmd/backend/newman.d
  src/dmd/backend/out.d
  src/dmd/backend/symbol.d
  src/dmd/backend/util2.d
  src/posix.mak
  src/win32.mak
Labels: auto-merge

#9583 expression.d: refactor small things
  src/dmd/expression.d
Labels: Easy Review, Refactoring, auto-merge

#9582 For issue 19724, group library files explicitly listed with `-L=` in with other library-related `-L=` flags.
  src/dmd/link.d
  test/compilable/issue19724.sh
Labels: auto-merge

#8837 Add proper toArgTypes() for System V x86_64 ABI
  src/dmd/argtypes.d
  src/dmd/argtypes_sysv_x64.d
  src/dmd/dstruct.d
  src/dmd/target.d
  src/posix.mak
  src/win32.mak
  test/runnable/testargtypes.d
Labels: auto-merge

#9589 resolvehelper(): remove goto's
  src/dmd/typesem.d
Labels: Easy Review, Refactoring, auto-merge

#9588 Merge tk/mem.c with backend/tk.c
  src/dmd/backend/tk.c
  src/dmd/tk/mem.c
  src/posix.mak
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: auto-merge

#9591 dmd.cond: Add VersionCondition.isVersionCondition
  circle.yml
  src/cond.h
Labels: C++ Port, GDC

#9593 Remove support for SUN SUN386 in tk.c
  src/dmd/backend/tk.c
Labels: auto-merge

#9595 Remove PRINT macro from tk.c
  src/dmd/backend/tk.c
Labels: auto-merge

#9596 Remove call to write() for Microsoft platforms in tk.c
  src/dmd/backend/tk.c
Labels: auto-merge

#9594 getProperty.visitBasic(): eliminate gotos
  src/dmd/typesem.d
Labels: Easy Review, Refactoring, auto-merge

#9597 Remove some code in tk.c that is specific to older compilers
  src/dmd/backend/tk.c
Labels: auto-merge

#9585 Fix Issue 15371 - __traits(getMember) should bypass the protection
  changelog/traits.dd
  src/dmd/traits.d
  test/compilable/imports/test15371.d
  test/compilable/test15371.d
Labels: Enhancement, auto-merge

#9416 [Azure-Pipelines]: Build DMD with VisualD
  .azure-pipelines/lib.sh
  .azure-pipelines/windows-visual-studio.sh
  .azure-pipelines/windows-visual-studio.yml
  .azure-pipelines/windows.sh
  .azure-pipelines/windows.yml
  appveyor.sh
  appveyor.yml
  azure-pipelines.yml
  src/vcbuild/dmd_backend.vcxproj
  test/runnable/extra-files/statictor-postscript.sh
  test/runnable/extra-files/test17868-postscript.sh
  test/runnable/test18076.sh
  test/tools/paths.d
Labels: auto-merge

#9592 Replace mem.c and tk.c with C stdlib wrappers in tk.d
  azure-pipelines.yml
  src/build.d
  src/dmd/backend/code_stub.h
  src/dmd/backend/tk.c
  src/dmd/backend/tk.d
  src/posix.mak
  src/vcbuild/dmd.sln
  src/vcbuild/dmd.vcxproj
  src/vcbuild/dmd_backend.vcxproj
  src/win32.mak
Labels: auto-merge

#9590 make TypeTraits semantic more clear and prevent invalid type swaps
  src/dmd/traits.d
  src/dmd/typesem.d
Labels: auto-merge

#9606 Remove C Compiler from Windows makefiles
  src/vcbuild/msvc-dmc.d
  src/win32.mak
  src/win64.mak
Labels: auto-merge

#9604 Merge backend/tk.d with backend/mem.d
  src/dmd/backend/mem.d
  src/dmd/backend/tk.d
  src/posix.mak
  src/win32.mak
Labels: auto-merge

#9605 Fix Issue 19658 - MSVC++ enum mangling
  src/dmd/cppmanglewin.d
  test/runnable/cpp11.d
  test/runnable/cpp_stdlib.d
  test/runnable/extra-files/cpp11.cpp
  test/tools/d_do_test.d
Labels: Bug Fix

#9610 Remove CXX from build.d
  src/build.d
Labels: auto-merge

#9607 build.d now builds on Windows x64
  src/build.d
Labels: auto-merge

#9613 build.d: Replace Visual Studio's lib.exe and ar with dmd -lib
  src/build.d
Labels: auto-merge

#9614 refactor namedargs
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code.d
Labels: Easy Review, Refactoring, auto-merge

#9587 expression.d: refactor small things pt 2
  src/dmd/expression.d
Labels: Easy Review, Refactoring

#9612 Clean up C++ headers and expose a few more functions
  src/dmd/dsymbol.h
  src/dmd/globals.h
  src/dmd/identifier.h
  src/dmd/json.d
  src/dmd/json.h
  src/dmd/mars.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/opover.d
  src/dmd/scope.h
  src/dmd/target.h
  src/dmd/tokens.d
  src/dmd/tokens.h
Labels: auto-merge

#9616 build.d fix model flag in buildBackend()
  src/build.d
Labels: auto-merge

#9617 build.d: remove some left-over C++ stuff
  src/build.d
Labels: auto-merge

#9619 Add some attributes to Prot and DSymbol.prot()
  src/dmd/aggregate.d
  src/dmd/denum.d
  src/dmd/dimport.d
  src/dmd/dsymbol.d
  src/dmd/dtemplate.d
Labels: auto-merge

#9618 let dinifile.readFromEnv()'s environment parameter be const
  src/dmd/dinifile.d
Labels: auto-merge

#8633 Rework #8542 wrt. deterministic IDs via generateIdWithLoc()
  src/dmd/ctorflow.d
  src/dmd/dscope.d
  src/dmd/globals.d
  src/dmd/identifier.d
  src/dmd/root/filename.d
  src/dmd/root/hash.d
Labels: auto-merge

#9623 Fix Issue 19804 - fails to compile with fixes size array T[1]...
  src/dmd/backend/cgxmm.d
  src/dmd/backend/cod3.d
  test/compilable/test19804.d
Labels: Bug Fix, auto-merge

#9625 Fix Issue 19809 - override block affects passing lambda as argument
  src/dmd/dsymbolsem.d
  test/compilable/test19809.d
Labels: Enhancement, auto-merge

#9624 build.d: Remove PGO environment variable
  src/build.d
Labels: auto-merge

#9626 mark environment parameters in dmd.dinifile as ref instead of raw pointers
  src/dmd/dinifile.d
  src/dmd/mars.d
Labels: auto-merge

#9627 have dinifile.parseConfFile take a ubyte[] instead of a ubyte*+length pair
  src/dmd/dinifile.d
  src/dmd/mars.d
Labels: auto-merge

#9631 Refactor loop check for inout modification into a recursive function
  src/dmd/expressionsem.d
Labels: auto-merge

#9630 Refactor function skip loop in `getRightThis()` to a separate function
  src/dmd/expressionsem.d
  src/dmd/typesem.d
Labels: auto-merge

#9628 change path parameter of dinifile.parseConfFile to array
  src/dmd/dinifile.d
  src/dmd/mars.d
Labels: auto-merge

#9620 don't allocate space for frame pointer if not using frame pointer
  src/dmd/backend/cgcod.d
Labels: auto-merge

#9634 Fix Issue 19519 - cannot determine length of static array at compile …
  src/dmd/dinterpret.d
  test/compilable/test19519.d
Labels: Bug Fix, auto-merge

#9635 xtest46.d: remove Phobos dependency
  test/runnable/xtest46.d
Labels: auto-merge

#9633 test42.d: remove Phobos dependency
  test/runnable/test42.d
Labels: auto-merge

#9230 testsuite: Prepare for stricter TEST_OUTPUT tests
  test/README.md
  test/tools/d_do_test.d
Labels: Continuous Integration

#9638 s2ir.d: remove Phobos dependency
  test/runnable/s2ir.d
  test/runnable/test37.d
  test/runnable/testfile.d
Labels: Easy Review, Refactoring, auto-merge

#9642 fail_compilation: remove Phobos dependencies
  test/fail_compilation/diag10768.d
  test/fail_compilation/fail18719.d
  test/fail_compilation/fail3895.d
  test/fail_compilation/fail80_m32.d
  test/fail_compilation/fail80_m64.d
  test/fail_compilation/fail97.d
Labels: Easy Review, Refactoring, auto-merge

#9639 test/README.md: add Test Coding Practices
  test/README.md
Labels: documentation

#9637 testabi.d: remove Phobos dependency
  test/runnable/testabi.d
Labels: Easy Review, Refactoring, auto-merge

#9640 Introduce a `toParent()` variant that strictly follows the declaration context
  src/dmd/declaration.d
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/e2ir.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/semantic3.d
  src/dmd/statementsem.d
  src/dmd/tocvdebug.d
  src/dmd/typesem.d
Labels: auto-merge

#9641 test25.d test13512.d: remove Phobos dependency
  test/compilable/test13512.d
  test/compilable/test25.d
Labels: Easy Review, Refactoring, auto-merge

#9645 Add changelog entry for Markdown features in Ddoc
  changelog/ddoc_markdown.dd
Labels: auto-merge

#9646 Rename `toParent4`/`isMember4` to `toParentDecl`/`isMemberDecl`
  src/dmd/declaration.d
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/e2ir.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/semantic3.d
  src/dmd/statementsem.d
  src/dmd/tocvdebug.d
  src/dmd/typesem.d
Labels: auto-merge

#9651 Update imports for the codegen update scripts
  test/runnable/test_cdcmp.d
  test/runnable/test_cdstrpar.d
  test/runnable/test_cdvecfill.d
Labels: Trivial, auto-merge

#9650 VC build: make 32-bit build /LARGEADDRESSAWARE
  src/vcbuild/dmd.vcxproj
Labels: auto-merge

#9654 pass response_expand's args by ref instead of by pointer
  src/dmd/mars.d
  src/dmd/root/response.d
Labels: auto-merge

#9656 fix Issue 19813 - Generated bt instruction seg faults, high 32 bits of register is garbage
  src/dmd/backend/cgelem.d
  test/runnable/testbtst.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#9655 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  src/dmd/backend/cgxmm.d
  src/dmd/backend/cod3.d
  src/dmd/dinterpret.d
  test/compilable/test19519.d
  test/compilable/test19804.d
Labels: Bug Fix, auto-merge

#9658 fix issue 18794 - Compiling with -O causes runtime segfault
  test/runnable/mars1.d
Labels: Bug Fix, auto-merge

#9659 Fix issue 19814 - Nested code blocks in Ddoc break formatting
  src/dmd/doc.d
  test/compilable/ddoc19814.d
  test/compilable/extra-files/ddoc19814.html
Labels: auto-merge

#9660 Fix bugs and testsuite failures relating to BigEndian.
  src/dmd/constfold.d
  test/runnable/mars1.d
  test/runnable/test12.d
  test/runnable/test23.d
  test/runnable/testxmm.d
Labels: Blocking Other Work, GDC, auto-merge

#9661 let DSymbol.oneMembers take members by ref rather than by pointer
  src/dmd/astbase.d
Labels: auto-merge

#9657 [trivial] remove unnecessary main function from compailable test
  test/compilable/test19519.d
  test/compilable/test19804.d
Labels: Trivial, auto-merge

#9664 change instances of memcpy to slice copies in dmd.root.speller
  src/dmd/root/speller.d
Labels: auto-merge

#9665 [dmd-cxx] Fix bugs and testsuite failures relating to BigEndian.
  src/constfold.c
  test/runnable/mars1.d
  test/runnable/test12.d
  test/runnable/test23.d
  test/runnable/testxmm.d
Labels: C++ Port, GDC

#9669 have the delegates used by dmd.root.speller take arrays instead of pointers
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/root/speller.d
  src/dmd/traits.d
Labels: auto-merge

#9670 remove unnecessary charset parameter in dmd.root.speller functions
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/root/speller.d
  src/dmd/traits.d
Labels: auto-merge

#9673 INT_MAX -> int.max in dmd.root.speller
  src/dmd/root/speller.d
Labels: auto-merge

#9647 Move `toParentDecl` to `toParentLocal` and make a new `toParentDecl()` which follows the declaration scope even for static templates
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/dsymbolsem.d
  src/dmd/e2ir.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/semantic3.d
  src/dmd/statementsem.d
  src/dmd/tocvdebug.d
  src/dmd/typesem.d
  test/compilable/test6541.d
  test/compilable/testtempl2.d
Labels: Bug Fix, auto-merge

#9675 remove Visitor from Expression_toDt()
  src/dmd/todt.d
Labels: Easy Review, Refactoring

#9676 add isClassReferenceExp()
  src/dmd/expression.d
Labels: Easy Review, auto-merge

#9677 add hasMonitor()
  src/dmd/dclass.d
  src/dmd/todt.d
  src/dmd/toobj.d
  src/dmd/typesem.d
Labels: Refactoring, auto-merge

#9678 [dmd-cxx] Backport betterC patches
  src/clone.c
  src/dcast.c
  src/declaration.c
  src/dinterpret.c
  src/dmodule.c
  src/dstruct.c
  src/e2ir.c
  src/expressionsem.c
  src/func.c
  src/globals.h
  src/glue.c
  src/idgen.c
  src/mars.c
  src/opover.c
  src/parse.c
  src/statementsem.c
  src/todt.c
  src/toobj.c
  src/typinf.c
  test/fail_compilation/test18312.d
Labels: C++ Port, GDC

#9680 convert LRet to a nested function
  src/dmd/e2ir.d
Labels: Refactoring, auto-merge

#9674 make speller's search delegate parameter into an alias parameter
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/root/speller.d
  src/dmd/traits.d
Labels: auto-merge

#9684 runnable/test42.d: Fix bswap test for BigEndian
  test/runnable/test42.d
Labels: Blocking Other Work, C++ Port, GDC

#9652 Fix Issue 19661 - DMD 2.084.0 SIGSEGV in std.traits.isFunction
  src/dmd/expressionsem.d
  src/dmd/initsem.d
  test/fail_compilation/imports/imp19661.d
  test/fail_compilation/test19661.d
Labels: Bug Fix, Regression, auto-merge

#9683 runnable/test42.d: Fix bswap test for BigEndian
  test/runnable/test42.d
Labels: Blocking Other Work, GDC, auto-merge

#9282 Fix for the non-global template issue 5710
  src/dmd/aggregate.d
  src/dmd/ctfeexpr.d
  src/dmd/dcast.d
  src/dmd/declaration.d
  src/dmd/delegatize.d
  src/dmd/dinterpret.d
  src/dmd/dstruct.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/e2ir.d
  src/dmd/escape.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/glue.d
  src/dmd/hdrgen.d
  src/dmd/id.d
  src/dmd/initsem.d
  src/dmd/inline.d
  src/dmd/mtype.d
  src/dmd/semantic3.d
  src/dmd/statementsem.d
  src/dmd/todt.d
  src/dmd/toir.d
  src/dmd/traits.d
  src/dmd/typesem.d
  src/dmd/visitor.d
  test/compilable/nestedtempl0.d
  test/compilable/nestedtempl1.d
  test/compilable/test324.d
  test/fail_compilation/fail324.d
  test/fail_compilation/nestedtempl0.d
  test/fail_compilation/nestedtempl1.d
  test/fail_compilation/nestedtempl2.d
  test/fail_compilation/nestedtempl3.d
  test/runnable/template10.d
Labels: Bug Fix, auto-merge

#9686 Add recent regression test case to CTFE test suite
  test/compilable/interpret3.d
Labels: auto-merge

#9682 todt.d: remove casts and other improvements
  src/dmd/todt.d
Labels: Easy Review, Refactoring, auto-merge

#9689 use constructor rather than in-place setting of .op
  src/dmd/expressionsem.d
  src/dmd/semantic3.d
Labels: Easy Review, Refactoring, auto-merge

#9690 add CatElemAssignExp and CatDcharAssignExp
  src/dmd/expression.d
  src/dmd/expressionsem.d
Labels: Easy Review, Refactoring, auto-merge

#9688 Make a unittest static data non-TLS
  src/dmd/root/speller.d
Labels: Easy Review, Trivial

#9687 Cleanup gotos from visit cast exp
  src/dmd/e2ir.d
Labels: auto-merge-squash

#9685 prep for making Expression.op const
  src/dmd/dinterpret.d
  src/dmd/expression.d
  src/dmd/opover.d
Labels: Refactoring, auto-merge

#9693 change dmd.root.speller.spellerX's flag param to a bool
  src/dmd/root/speller.d
Labels: auto-merge

#9691 finish making Expression.op const
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/opover.d
Labels: Refactoring, auto-merge

#9695 Fix Issue 19540 - ICE when using `typeof(new class {})` as default value
  src/dmd/expressionsem.d
  test/compilable/test19540.d
Labels: Bug Fix, auto-merge

#9692 Fix copy-pasta in comment in opover.d
  src/dmd/opover.d
Labels: auto-merge

#9701 scanomf.scanOmfObjModule: free array with exit scope guard
  src/dmd/scanomf.d
Labels: auto-merge

#9696 Fix Issue 19774 - wrong code caused by opIndex
  src/dmd/statementsem.d
  test/runnable/test19774.d
Labels: Bug Fix

#9713 cod2.d: reduce technical debt a bit
  src/dmd/backend/cod2.d
  src/dmd/backend/code.d
Labels: Easy Review, Refactoring

#9711 Advance deprecation of using this and super as types: Error
  changelog/dep_type_error.dd
  src/dmd/typesem.d
  test/fail_compilation/fail18228.d
  test/fail_compilation/test12228.d
  test/runnable/testconst.d
  test/runnable/xtest46.d
Labels: auto-merge

#9694 let dmd.root.speller.spellerY use a seed array
  src/dmd/root/speller.d
Labels: auto-merge

#9636 Remove visiblity and lookup deprecation (Take 2)
  changelog/remove_visibility.dd
  src/dmd/access.d
  src/dmd/cli.d
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/expressionsem.d
  src/dmd/globals.d
  src/dmd/mars.d
  src/dmd/traits.d
  src/dmd/typesem.d
  test/compilable/diag12598.d
  test/compilable/dip22d.d
  test/compilable/imports/diag12598a.d
  test/compilable/imports/dip22d.d
  test/compilable/imports/dip22e.d
  test/compilable/test15925.d
  test/compilable/test19107.d
  test/compilable/testcheckimports.d
  test/fail_compilation/checkimports1a.d
  test/fail_compilation/checkimports1b.d
  test/fail_compilation/checkimports1c.d
  test/fail_compilation/checkimports2.d
  test/fail_compilation/checkimports2a.d
  test/fail_compilation/checkimports2b.d
  test/fail_compilation/checkimports2c.d
  test/fail_compilation/diag10169.d
  test/fail_compilation/diag5385.d
  test/fail_compilation/dip22a.d
  test/fail_compilation/dip22b.d
  test/fail_compilation/dip22d.d
  test/fail_compilation/dip22e.d
  test/fail_compilation/fail10528.d
  test/fail_compilation/fail17625.d
  test/fail_compilation/fail18938.d
  test/fail_compilation/fail18979.d
  test/fail_compilation/fail262.d
  test/fail_compilation/fail313.d
  test/fail_compilation/imports/imp15925.d
  test/fail_compilation/imports/test15117a.d
  test/fail_compilation/imports/test19107a.d
  test/fail_compilation/imports/test19107b.d
  test/fail_compilation/lookup.d
  test/fail_compilation/test143.d
  test/fail_compilation/test15177.d
  test/fail_compilation/test15785.d
  test/fail_compilation/test15785b.d
  test/fail_compilation/test15897.d
  test/fail_compilation/test15925.d
  test/fail_compilation/test19107.d
  test/fail_compilation/test314.d
Labels: 72h no objection -> merge

#9709 Dub: initialize contract checks
  src/dmd/frontend.d
  test/unit/frontend.d
Labels: auto-merge

#9714 Dub: add ability to pass version identifiers when initializing frontend
  src/dmd/frontend.d
  test/unit/frontend.d
Labels: auto-merge

#9722 cod2.c: improve details a bit pt 2
  src/dmd/backend/cod2.d
Labels: Easy Review, Refactoring

#9721 access.d: remove obsolete access checks in favor of visibility checks
  src/dmd/access.d
  test/runnable/imports/pubprivtmpla.d
  test/runnable/pubprivtmpl.d
Labels: auto-merge

#9719 change highlight in doc.highlightCode2 to a string
  src/dmd/doc.d
Labels: auto-merge
