Repository dlang/dmd, pull requests merged in 2019-08, with the labels that each got.

#10252 Fix segfault in trait getLocation with some symbols
  src/dmd/traits.d
  test/fail_compilation/trait_loc_err.d
Labels: auto-merge-squash

#10256 Fix 20094: Wrong C++ template substitution for arguments in the same namespace
  src/dmd/cppmangle.d
  test/compilable/cppmangle.d
Labels: Regression, auto-merge, stable-priority

#10232 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/dmd/access.d
  src/dmd/aggregate.d
  src/dmd/astbase.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/cgobj.d
  src/dmd/backend/cod3.d
  src/dmd/backend/dcgcv.d
  src/dmd/ctfeexpr.d
  src/dmd/delegatize.d
  src/dmd/dinterpret.d
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/e2ir.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/hdrgen.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/semantic3.d
  src/dmd/statementsem.d
  src/dmd/typesem.d
  test/compilable/b20011.d
  test/compilable/b20045.d
  test/compilable/b20067.d
  test/compilable/cppmangle.d
  test/compilable/ice20044.d
  test/compilable/staticforeach.d
  test/compilable/test19754.d
  test/compilable/test20039.d
  test/compilable/test20051.d
  test/compilable/test20063.d
  test/compilable/test20065.d
  test/compilable/test930.d
  test/compilable/vcg-ast.d
  test/fail_compilation/b20011.d
  test/fail_compilation/diag4596.d
  test/fail_compilation/fail106.d
  test/fail_compilation/fail17491.d
  test/fail_compilation/fail351.d
  test/fail_compilation/fail4206.d
  test/fail_compilation/fail8262.d
  test/fail_compilation/fail9891.d
  test/fail_compilation/ice11856_0.d
  test/fail_compilation/ice11856_1.d
  test/fail_compilation/ice11919.d
  test/fail_compilation/ice12362.d
  test/fail_compilation/ice14929.d
  test/fail_compilation/ice19295.d
  test/fail_compilation/ice19950.d
  test/fail_compilation/ice20042.d
  test/fail_compilation/ice20056.d
  test/fail_compilation/test12385.d
  test/runnable/e7804.d
  test/runnable/test17885.d
  test/runnable/test20025.d
  test/runnable/testxmm.d
Labels: Bug Fix, Enhancement, auto-merge

#10257 [stable] Fixup PR 10256: Properly nest substituted C++ names in N..E
  src/dmd/cppmangle.d
  test/compilable/cppmangle.d
Labels: Regression, auto-merge, stable-priority

#10259 Report code coverage for the backend
  src/posix.mak
Labels: auto-merge

#10261 todt.d: convert for to foreach
  src/dmd/todt.d
Labels: Easy Review, Refactoring

#10258 switch typesTable to Barray
  src/dmd/backend/cc.d
  src/dmd/backend/dwarfeh.d
  src/dmd/backend/symbol.d
  src/dmd/s2ir.d
Labels: Easy Review, Refactoring

#10260 add checkEnclosedInTry()
  src/dmd/s2ir.d
Labels: Easy Review, Refactoring, auto-merge

#10262 add Mem.check()
  src/dmd/root/rmem.d
Labels: Easy Review, Refactoring, auto-merge

#10263 Merge remote-tracking branch 'upstream/stable'
  VERSION
  src/dmd/cppmangle.d
  test/compilable/cppmangle.d
Labels: auto-merge

#10228 VS project: generate VERSION to generated folder rather than importing it directly
  src/vcbuild/dmd.vcxproj
Labels: auto-merge

#10272 Remove BACK_FLAGS from build.d
  src/build.d
Labels: Trivial

#10274 VS: generate VERSION file into the output folder, not the intermediat…
  .azure-pipelines/windows-visual-studio.yml
  src/vcbuild/dmd.vcxproj
Labels: auto-merge

#10275 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
Labels: auto-merge

#10269 outbuffer.d: add unittests
  src/dmd/root/outbuffer.d
Labels: auto-merge

#10267 Fix issue 20033 - Deprecation do not trigger on `alias this`
  changelog/deprecated_alias_this.dd
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/aliasthis.d
  src/dmd/aliasthis.h
  src/dmd/dscope.d
  src/dmd/dsymbolsem.d
  src/dmd/expression.d
  src/dmd/mtype.d
  src/dmd/opover.d
  test/fail_compilation/fail20033.d
Labels: Bug Fix, auto-merge

#8121 fix Issue 18729 - dmd -run executes in different environment
  src/dmd/dinifile.d
  src/dmd/env.d
  src/dmd/link.d
  src/posix.mak
  src/win32.mak
  test/dshell/extra-files/printenv.d
  test/dshell/sameenv.d
Labels: Bug Fix, Enhancement

#10276 utf_decodeChar(): use const and saner table initialization
  src/dmd/utf.d
Labels: Easy Review, Refactoring, auto-merge

#10277 OutBuffer.writeUTF8: 5 and 6 byte encodings are illegal
  src/dmd/root/outbuffer.d
Labels: Easy Review, auto-merge

#10279 canThrow(): replace dead code with assert(0)
  src/dmd/canthrow.d
Labels: auto-merge

#10278 fix azure builds for master/stable
  .azure-pipelines/lib.sh
Labels: auto-merge

#10282 refactor code into checkFuncThrows()
  src/dmd/canthrow.d
Labels: Easy Review, Refactoring

#10283 fix azure builds for master/stable (for real)
  .azure-pipelines/lib.sh
Labels: auto-merge

#10266 fix Issue 20096 - error message 'cannot goto into try block' is follo…
  src/dmd/glue.d
  test/fail_compilation/test20096.d
Labels: Bug Fix, Enhancement, auto-merge

#10217 Fix Issue 20074 - header file generation doesn't include attributes with CallExp
  src/dmd/hdrgen.d
  test/compilable/extra-files/header2.d
  test/compilable/extra-files/header2.di
  test/compilable/extra-files/header2i.di
  test/fail_compilation/diag13028.d
  test/fail_compilation/fail11125.d
  test/fail_compilation/ice10259.d
  test/fail_compilation/ice12673.d
  test/fail_compilation/ice13225.d
Labels: Bug Fix, auto-merge

#10285 Fix Issue 20108 - -dip1000 defeated by auto
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/escape.d
  test/fail_compilation/fail20108.d
Labels: Bug Fix, auto-merge

#10270 Fix Issue 20100 - Segfault with checkaction=context on struct comparison
  src/dmd/expressionsem.d
  test/compilable/test20100.d
Labels: Bug Fix, auto-merge

#10284 fix Issue 20113 - Cannot find source code for runtime library file 'object.d' when the path contains '~'
  src/dmd/root/filename.d
Labels: Bug Fix, auto-merge

#10288 [stable] Fix some issues wrt. wide Windows API usage in frontend
  src/dmd/root/file.d
  src/dmd/root/filename.d
Labels: auto-merge

#10289 add more isXxxxStatement() functions
  src/dmd/statement.d
  src/dmd/statement.h
Labels: Easy Review, Refactoring, auto-merge

#10290 add STC.safeGroup
  src/dmd/aggregate.d
  src/dmd/astbase.d
  src/dmd/declaration.d
  src/dmd/dsymbolsem.d
  src/dmd/parse.d
Labels: Easy Review, Refactoring, auto-merge

#10281 Suppress the "read-modify-write" error if type is a struct or a class
  changelog/no-readmodify-error-if-struct-class.dd
  src/dmd/expression.d
  test/compilable/readmodify_structclass.d
Labels: auto-merge

#10245 resolveOpDollar(): replace awkward and buggy loop
  src/dmd/expressionsem.d
Labels: Easy Review, Refactoring, auto-merge

#9933 Test cases for finding a common type with typeMerge()
  test/compilable/commontype.d
Labels: auto-merge

#10291 parse.d: redo AST.STC as STC
  src/dmd/parse.d
Labels: Easy Review, Refactoring, auto-merge

#10292 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/escape.d
  src/dmd/glue.d
  src/dmd/root/file.d
  src/dmd/root/filename.d
  test/fail_compilation/fail20108.d
  test/fail_compilation/test20096.d
Labels: Bug Fix

#10295 add missing test cases for s2ir.d
  test/fail_compilation/goto1.d
  test/fail_compilation/goto2.d
Labels: Easy Review, auto-merge

#10300 Fix broken test case in master
  test/fail_compilation/goto2.d
Labels: Blocking Other Work, auto-merge

#10297 convert Mem.error() to Mem.check()
  src/dmd/dinifile.d
  src/dmd/dmodule.d
  src/dmd/dsymbol.d
  src/dmd/e2ir.d
  src/dmd/eh.d
  src/dmd/glue.d
  src/dmd/libelf.d
  src/dmd/libmscoff.d
  src/dmd/libomf.d
  src/dmd/link.d
  src/dmd/mars.d
  src/dmd/mtype.d
  src/dmd/s2ir.d
  src/dmd/scanmscoff.d
  src/dmd/scanomf.d
  src/dmd/tocsym.d
  src/dmd/toctype.d
  src/dmd/toir.d
Labels: Easy Review, Refactoring, auto-merge

#10298 Give root/string.d complete coverage
  src/dmd/root/string.d
Labels: auto-merge

#10301 Issue 20024 - "No property x for type Y" error not as helpful as it should be
  src/dmd/typesem.d
  test/fail_compilation/diag12063.d
  test/fail_compilation/fail19103.d
  test/fail_compilation/fail20040.d
  test/fail_compilation/fail7234.d
  test/fail_compilation/fail9562.d
Labels: Diagnostic Messages, Enhancement

#10294 labelToBlock(): replace unreachable error message with assert
  src/dmd/iasmdmd.d
  src/dmd/root/aav.d
  src/dmd/s2ir.d
  src/dmd/semantic3.d
  src/dmd/statement.d
  src/dmd/statement.h
  src/dmd/statementsem.d
  test/fail_compilation/fail11552.d
  test/fail_compilation/goto4.d
  test/fail_compilation/goto5.d
  test/fail_compilation/ice11552.d
Labels: Easy Review, Refactoring, auto-merge

#10303 Improve root/hash.d
  src/dmd/dtemplate.d
  src/dmd/root/ctfloat.d
  src/dmd/root/hash.d
  src/dmd/root/stringtable.d
Labels: auto-merge-squash

#10306 [dmd-cxx] Don't crash when compiling for 16-bit platforms
  src/expression.c
  src/hdrgen.c
Labels: C++ Port, GDC, auto-merge

#10308 Tokens.tochars: Remove never used TOK.manifest
  src/dmd/parse.d
  src/dmd/tokens.d
Labels: Easy Review, Refactoring

#10310 OutBuffer: Add ability for extractSlice to null-terminate its data
  src/dmd/root/outbuffer.d
Labels: Easy Review, Trivial, auto-merge

#10311 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
Labels: auto-merge

#10312 fix Issue 20131 - Bad codegen from inline asm LOCK CMPXCHG; possible …
  src/dmd/iasmdmd.d
  test/runnable/iasm64.d
Labels: Bug Fix, auto-merge

#10307 Refactor Lexer.combineComment to be simpler and accept D slices
  src/dmd/astbase.d
  src/dmd/doc.d
  src/dmd/dsymbol.d
  src/dmd/lexer.d
  src/dmd/parse.d
  src/dmd/root/dcompat.h
  src/dmd/tokens.d
  src/dmd/tokens.h
Labels: Easy Review, Refactoring, auto-merge

#10309 [dmd-cxx] fix Issue 20113 - Cannot find source code for runtime library file 'object.d' when the path contains '~'
  src/iasmdmd.c
  src/posix.mak
  src/root/ctfloat.c
  src/root/filename.c
Labels: Bug Fix, C++ Port, GDC

#10314 do not print version in debug builds, it just complicates the testsuite
  src/dmd/mars.d
Labels: auto-merge

#10304 Refactor and test response.d
  src/dmd/mars.d
  src/dmd/root/file.d
  src/dmd/root/response.d
Labels: auto-merge

#10313 Fixup #10308: Remove TOKmanifest from token.h
  src/dmd/tokens.d
  src/dmd/tokens.h
  src/tests/cxxfrontend.c
Labels: auto-merge

#10316 fix Issue 20126 - codegen reloads parameter from register when iasm c…
  src/dmd/backend/cod1.d
  test/runnable/iasm64.d
Labels: Bug Fix, auto-merge

#10318 Label.fwdrefs is now dead code
  src/dmd/irstate.d
  src/dmd/s2ir.d
Labels: Easy Review, Refactoring, auto-merge

#10320 Fix Issue 20136 - opEquals not recognized for AA key
  src/dmd/expressionsem.d
  test/compilable/test20136.d
Labels: Bug Fix, Regression

#10317 fix issue 20138 - is expression not evaluating correctly?
  changelog/isexpression-const-inout-shared.dd
  src/dmd/dtemplate.d
  test/compilable/test20138.d
Labels: Bug Fix, auto-merge

#10324 fix issue 20021 - static if doesn't evaluate opCast(bool)
  src/dmd/staticcond.d
  test/compilable/test20021.d
  test/fail_compilation/ice11553.d
Labels: Bug Fix, auto-merge-squash

#10231 fix building tests with debug compiler
  .azure-pipelines/lib.sh
  .azure-pipelines/windows-visual-studio.sh
  .azure-pipelines/windows-visual-studio.yml
  .azure-pipelines/windows.sh
  azure-pipelines.yml
  src/dmd/dmangle.d
  src/dmd/dsymbolsem.d
  src/vcbuild/dmd.vcxproj
  test/dshell/sameenv.d
  test/fail_compilation/fail7524a.sh
  test/runnable/extra-files/statictor-postscript.sh
  test/runnable/extra-files/test17868-postscript.sh
  test/runnable/test18772.d
  test/tools/d_do_test.d
  test/tools/dshell_prebuilt/dshell_prebuilt.d
Labels: Blocking Other Work, auto-merge

#10247 Fix issue 20089: Handle extra case in fixresult_complex87
  src/dmd/backend/cg87.d
  src/dmd/backend/cod2.d
  test/runnable/test18772.d
Labels: Blocking Other Work, Bug Fix

#10321 Declare frontend structs as extern cpp
  src/dmd/compiler.d
  src/dmd/complex.d
  src/dmd/dclass.d
  src/dmd/dinterpret.d
  src/dmd/dmodule.d
  src/dmd/expression.d
  src/dmd/globals.d
  src/dmd/id.d
  src/dmd/target.d
Labels: auto-merge

#10327 fix issue 1104 - CodeView: dchar shown as uint in the debugger
  src/dmd/backend/var.d
Labels: Bug Fix, auto-merge

#10094 Remove some more extern(C++) linkage from compiler functions
  src/dmd/astbase.d
  src/dmd/builtin.d
  src/dmd/cond.d
  src/dmd/cond.h
  src/dmd/declaration.h
  src/dmd/delegatize.d
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/hdrgen.d
  src/dmd/hdrgen.h
  src/dmd/init.h
  src/dmd/mtype.h
  src/dmd/statement.h
  src/dmd/template.h
Labels: auto-merge

#10337 Fix-up C++ headers for dmd frontend interface
  src/dmd/declaration.h
  src/dmd/statement.h
Labels: GDC, auto-merge

#10331 ctfeInterpret: remove apparently dead code
  src/dmd/dinterpret.d
Labels: auto-merge

#10328 fix Issue 4372, 982 - CodeView: type of enumerator values reduced to …
  src/dmd/backend/dcgcv.d
  test/runnable/testpdb.d
Labels: Bug Fix

#10338 Move toParentP and followInstantiationContext to public API
  src/dmd/declaration.d
  src/dmd/delegatize.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/inline.d
  src/dmd/toir.d
  src/dmd/typesem.d
Labels: auto-merge

#10341 Refactor link.d in preparation for fix to issue 6952
  src/dmd/link.d
Labels: auto-merge

#10342 Refactor link.d in preparation for fix to issue 6952 (Part 2)
  src/dmd/link.d
Labels: auto-merge

#10336 Fix issue 13582: Don't print deprecation when importing a deprecated module from another deprecated module.
  src/dmd/dimport.d
  src/dmd/dscope.d
  test/compilable/imports/test13582.d
  test/compilable/test13582a.d
  test/compilable/test13582b.d
Labels: Bug Fix

#10335 replace CtfeCompiler with foreachExpAndVar()
  src/dmd/dinterpret.d
Labels: Refactoring, auto-merge

#10347 ctfeexpr.d: get rid of a number of casts
  src/dmd/ctfeexpr.d
Labels: Easy Review, Refactoring, auto-merge

#10348 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  src/dmd/expressionsem.d
  src/dmd/staticcond.d
  test/compilable/test20021.d
  test/compilable/test20136.d
  test/fail_compilation/ice11553.d
Labels: Bug Fix, auto-merge

#10343 Start allocating CTFE memory in a separate Region
  src/build.d
  src/dmd/dinterpret.d
  src/dmd/root/region.d
  src/posix.mak
  src/win32.mak
Labels: Refactoring, auto-merge

#10349 ctfeInterpret(): add more shortcuts
  src/dmd/dinterpret.d
Labels: Refactoring, auto-merge

#10344 Refactor resolveFuncCall: Reduce nesting, return early, improve 'quiet' resolution
  src/dmd/expressionsem.d
  src/dmd/func.d
Labels: Refactoring

#10264 Fix Issue 809 - Should be possible to convert lazy argument to delegate
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  test/fail_compilation/fail809.d
  test/runnable/test809.d
Labels: 72h no objection -> merge, Enhancement, auto-merge

#10351 Move hard-coded logic to generate C main out of the compiler and into druntime
  src/dmd/compiler.d
  src/dmd/compiler.h
  src/dmd/dsymbolsem.d
  src/dmd/glue.d
  src/dmd/id.d
  src/dmd/mars.d
  test/runnable/extra-files/minimal/object.d
Labels: auto-merge

#10352 more use of ctfeEmplaceExp
  src/dmd/dinterpret.d
Labels: Easy Review, Refactoring, auto-merge

#10346 Fix issue 20164: print deprecation if a deprecated module is imported from a local function or a mixin.
  src/dmd/dimport.d
  src/dmd/dmodule.d
  src/dmd/dsymbolsem.d
  test/fail_compilation/fail20163.d
  test/fail_compilation/fail20164.d
  test/fail_compilation/imports/fail20164.d
Labels: Bug Fix, auto-merge

#10355 Move isPOSIX from global to target
  src/dmd/e2ir.d
  src/dmd/globals.d
  src/dmd/target.d
Labels: auto-merge

#10354 Add root/dsystem.h header for wrapping system includes
  src/dmd/errors.h
  src/dmd/objc.h
  src/dmd/root/array.h
  src/dmd/root/dcompat.h
  src/dmd/root/dsystem.h
  src/dmd/root/object.h
  src/dmd/root/outbuffer.h
  src/dmd/root/port.h
  src/dmd/root/rmem.h
  src/dmd/visitor.h
Labels: auto-merge

#10357 convert onExpression() to foreachVar() with delegate
  src/dmd/dinterpret.d
Labels: Refactoring, auto-merge

#10329 Fix Issue 1547 - Default parameter values should use implicit static opCall
  src/dmd/initsem.d
  test/compilable/test1547.d
  test/runnable/opover.d
Labels: Enhancement, auto-merge

#10350 change ctfeStack to ctfeGlobals.stack
  src/dmd/dinterpret.d
Labels: Easy Review, Refactoring, auto-merge

#10358 CtfeStatus: more consolidation to CtfeGlobals
  src/dmd/ctfeexpr.d
  src/dmd/dinterpret.d
Labels: Easy Review, Refactoring, auto-merge

#10212 Second round of makefile/build.d consolidation
  src/build.d
  src/posix.mak
  src/win32.mak
Labels: auto-merge

#10359 dmd.glue: Remove _STD hack from code generator
  src/dmd/glue.d
Labels: auto-merge

#10362 dmd/glue: Use target.isPOSIX instead of global.params where POSIX is implied
  src/dmd/glue.d
Labels: auto-merge

#10360 more use of ctfeEmplaceExp()
  src/dmd/dinterpret.d
Labels: Easy Review, Refactoring, auto-merge

#10361 dmd.dmsc: Remove global.params guards in setting exe
  src/dmd/dmsc.d
Labels: auto-merge

#10365 Don't emit documentation for public import if no DDoc comment
  src/dmd/doc.d
  test/compilable/ddocunittest.d
Labels: auto-merge

#10323 statement_toIR(): simplify conversion of label statements to goto
  src/dmd/s2ir.d
  src/dmd/semantic3.d
  src/dmd/statement.d
  src/dmd/statement.h
Labels: Refactoring, auto-merge

#10366 more use of region in dinterpret.d
  src/dmd/dinterpret.d
Labels: Refactoring

#10364 foreachVar(): move some logic into dgVar()
  src/dmd/dinterpret.d
Labels: Refactoring, auto-merge

#10367 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
Labels: auto-merge

#10370 Fix Issue 13826 - Move volatileLoad/Store to core.volatile when the volatile keyword is removed
  src/dmd/toir.d
Labels: Enhancement, auto-merge

#10368 dinterpret.d: try to get that .origin hack to work
  src/dmd/dinterpret.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/tocsym.d
  test/runnable/xtest46.d
Labels: auto-merge

#10371 ctfeexpr.d: replace new with ctfeEmplaceExp()
  src/dmd/ctfeexpr.d
Labels: Refactoring, auto-merge

#10373 Eliminate goto and casting from resolvePropertiesOnly
  src/dmd/expressionsem.d
Labels: Easy Review, Refactoring, auto-merge

#10374 remove CompiledCtfeFunction
  src/dmd/declaration.h
  src/dmd/dinterpret.d
  src/dmd/func.d
Labels: Easy Review, Refactoring, auto-merge

#10375 ctfeAdrOnStack from int to uint
  src/dmd/astbase.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dinterpret.d
Labels: Easy Review, Refactoring, auto-merge

#10377 Replace `hash_t` with `size_t`
  src/dmd/dtemplate.d
  src/dmd/root/stringtable.d
Labels: auto-merge

#10379 Replace `sizediff_t` with `ptrdiff_t`
  test/compilable/interpret3.d
Labels: auto-merge

#10380 fix Issue 18272 - missing changelog entry and no doc for -gf
  src/dmd/cli.d
Labels: Enhancement, auto-merge

#10339 Fix Issue 6952 - Static Linking on Linux (Add -preview=noXlinker)
  changelog/noxlinker.dd
  src/dmd/cli.d
  src/dmd/globals.d
  src/dmd/link.d
  test/dshell/extra-files/test6952/main.d
  test/dshell/extra-files/test6952/object.d
  test/dshell/test6952.d
Labels: auto-merge
