Repository dlang/dmd, pull requests merged in 2019-06, with the labels that each got.

#9931 fix broken link in a changelog entry
  changelog/aliasdecly_func.dd
Labels: auto-merge

#9930 Turn deprecation into error for invalid integer literals
  changelog/error_invalid_integer_literal.dd
  src/dmd/lexer.d
  test/fail_compilation/fix19018.d
  test/fail_compilation/fix19246.d
  test/unit/lexer/diagnostic_reporter.d
Labels: auto-merge

#9935 Have glue.d choose same defaultlib as link.d
  src/dmd/globals.d
  src/dmd/glue.d
  src/dmd/link.d
Labels: auto-merge

#9938 fix Issue 19914/19915 - ICE: Segmentation fault using align in a templated class
  src/dmd/attrib.d
  test/compilable/aggr_alignment.d
  test/fail_compilation/fail19914.d
  test/fail_compilation/fail19915.d
Labels: Bug Fix, auto-merge

#9939 fix Issue 19911 - ICE: Segmentation fault with struct object and variadic function
  src/dmd/semantic3.d
  test/compilable/minimal.d
  test/compilable/minimal2.d
  test/fail_compilation/extra-files/no_Throwable/object.d
  test/fail_compilation/extra-files/no_TypeInfo/object.d
  test/fail_compilation/fail19911a.d
  test/fail_compilation/fail19911b.d
  test/fail_compilation/fail19911c.d
  test/fail_compilation/no_Throwable.d
  test/fail_compilation/no_TypeInfo.d
Labels: auto-merge

#9940 Stop run.d if any tools fail to build
  test/run.d
Labels: auto-merge

#9942 Fix Issue 19234 - betterC TypeInfo error when using slice copy on Structs
  src/dmd/expression.d
  test/compilable/betterCarray.d
Labels: Bug Fix, auto-merge

#9068 Fix Issue 10665 - The documentation produced by ddoc should clearly list all public imports of a module
  src/dmd/doc.d
  test/compilable/ddocunittest.d
  test/compilable/extra-files/ddocunittest.html
Labels: Enhancement, auto-merge

#9941 fix Issue 19922/19923 - ICE: using typeid() or .classinfo without TypeInfo_Class
  src/dmd/expressionsem.d
  src/dmd/typesem.d
  test/fail_compilation/fail19922.d
  test/fail_compilation/fail19923.d
Labels: Bug Fix, auto-merge

#9928 Fix PIC_FLAG in run.d
  test/run.d
Labels: auto-merge

#9937 Turn deprecation on struct ctor with all defaults to error
  changelog/static_this_immutable_initialization.dd
  changelog/struct_ctor_default_params.dd
  src/dmd/dsymbolsem.d
  test/fail_compilation/b19691.d
  test/fail_compilation/b19691e.d
  test/fail_compilation/diag3438.d
  test/runnable/structlit.d
Labels: auto-merge

#9919 Fix compilation using LDC as the host compiler
  src/dmd/backend/global.d
Labels: auto-merge

#9929 evalu8.d: use foreach
  src/dmd/backend/evalu8.d
Labels: 72h no objection -> merge, auto-merge

#9927 Use core.bitop in evalu8
  src/dmd/backend/evalu8.d
Labels: auto-merge

#9948 remove useless cast
  src/dmd/mars.d
Labels: Easy Review, Trivial, auto-merge

#9950 remove unused addObjectToLibrary
  src/dmd/lib.d
Labels: Easy Review, Trivial, auto-merge

#9954 json writer, refact switch `case`s with `return` to gain a few sloc
  src/dmd/json.d
Labels: Refactoring, Trivial, auto-merge

#9945 dmd.conf not needed to compile dmd, changing it shouldn't trigger a rebuild
  src/build.d
  src/posix.mak
Labels: auto-merge

#9958 evalu8.d: remove legacy redunancy "isnan(f) || f != 0"
  src/dmd/backend/evalu8.d
Labels: auto-merge

#9932 Parser.parseDeclarations reduce scope for variables, add const in a couple places
  src/dmd/parse.d
Labels: auto-merge

#9959 Delete thread.h
  src/dmd/root/thread.h
  src/tests/cxxfrontend.c
Labels: Easy Review, Refactoring, Trivial, auto-merge

#9960 remove Tsize_t & Tptrdiff_t
  src/dmd/astbase.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/statementsem.d
Labels: Easy Review, Refactoring, Trivial, auto-merge

#9953 [REG 2.084.1] Fix issue 19936: `alias deprecated get this` falsely triggers deprecation on `array ~=`
  src/dmd/opover.d
  test/compilable/test19936.d
Labels: Bug Fix, auto-merge

#9905 enable CSEs for XMM operands
  src/dmd/backend/cg87.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/cgcs.d
  src/dmd/backend/cgxmm.d
  src/dmd/backend/cod1.d
  src/dmd/backend/cod3.d
  src/dmd/backend/cod4.d
  src/dmd/backend/code.d
  src/dmd/backend/gdag.d
  test/runnable/testfloat.d
Labels: auto-merge

#9961 [CI] CircleCi sometimes builds DMD stable against Phobos master
  .circleci/run.sh
Labels: auto-merge

#9964 Add attributes to the lexer
  src/dmd/lexer.d
Labels: Easy Review, auto-merge

#9966 Fix test case - escaping reference to stack struct
  test/runnable/template10.d
Labels: auto-merge

#9962 Add a sponsorship button
  .github/FUNDING.yml
Labels: Trivial, auto-merge

#9968 genObjFile: use the multi obj flag passed
  src/dmd/glue.d
Labels: Easy Review, Refactoring, Trivial, auto-merge

#9969 remove some commented out #includes(!)
  src/dmd/dmsc.d
Labels: Trivial, auto-merge

#9970 bring HtmlNamedEntity above the fold.
  src/dmd/entity.d
Labels: Trivial, auto-merge

#9967 add some private to glue
  src/dmd/glue.d
Labels: Easy Review, Trivial, auto-merge

#9972 Update to CSEs for XMMs
  src/dmd/backend/cg87.d
  src/dmd/backend/cgcod.d
  test/runnable/testfloat.d
Labels: Easy Review, auto-merge

#9949 Lazy Make-Like dependencies in build.d
  src/build.d
Labels: auto-merge

#9977 cgcs.d: publics above the fold, private below
  src/dmd/backend/cgcs.d
Labels: Easy Review, Refactoring, auto-merge

#9983 cgcs.d: minor refactor
  src/dmd/backend/cgcs.d
Labels: Easy Review, Refactoring, auto-merge

#9951 Remove unused stuff from mars.h
  src/dmd/mars.h
  src/posix.mak
  src/tests/cxxfrontend.c
  src/win32.mak
Labels: auto-merge

#9973 Make BArray use an actual destructor
  src/dmd/backend/barray.d
  src/dmd/backend/cgsched.d
  src/dmd/backend/go.d
Labels: auto-merge

#9984 Revert "Fix Issue 18439 Fix issue with `static foreach` not working with scoped @nogc."
  src/dmd/cond.d
  test/compilable/b18439.d
Labels: Bug Fix, auto-merge

#9976 add cse.d: manage CSE memory in stack frame
  src/dmd/backend/cgcod.d
  src/dmd/backend/cgcse.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code.d
  src/posix.mak
  src/win32.mak
Labels: Easy Review, Refactoring, auto-merge

#9894 Fix issue 19891 - Confusing error messages for auto ref parameters with default values
  src/dmd/dtemplate.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/typesem.d
  test/runnable/test19891.d
Labels: Bug Fix, auto-merge

#9985 Change name field to msg, frees up the name field to be used as the string to build each dependency
  src/build.d
Labels: auto-merge

#9988 backend/README.md: correct info and add missing info
  src/dmd/backend/README.md
Labels: auto-merge

#9989 Fix race condition in bash test rm
  test/tools/common_funcs.sh
Labels: auto-merge

#9991 fix Issue 19941 - [ICE] Segmentation fault in ImplicitConvTo::visit(AddrExp*) at dmd/dcast.d(980)
  src/dmd/expressionsem.d
  test/compilable/test19941.d
  test/fail_compilation/fail19941.d
Labels: Bug Fix, auto-merge

#9980 fix Issue 19942 - [ICE] Segmentation fault in resolvePropertiesX at dmd/expressionsem.d:1112
  src/dmd/statementsem.d
  test/compilable/traits.d
Labels: Bug Fix, auto-merge

#9990 fix issue 19584 - Illegal optimization: Shift-or -> imul
  src/dmd/backend/cgelem.d
  test/runnable/b19584.d
Labels: Bug Fix

#9946 fix issue 18784 - cpp constructor returns void on Posix
  src/dmd/e2ir.d
  src/dmd/globals.d
  test/runnable/cpp_abi_tests.d
  test/runnable/extra-files/cpp_abi_tests.cpp
Labels: Bug Fix

#10000 [dmd-cxx] fix Issue 19913 - ICE: Segmentation fault with mixin and enum
  src/mtype.c
  test/fail_compilation/fail19913.d
Labels: Bug Fix, C++ Port

#9999 [dmd-cxx] fix Issue 19912: No implicit import of object module when an object declaration exists.
  src/dmodule.c
  test/compilable/test19912.d
  test/fail_compilation/fail19912a.d
  test/fail_compilation/fail19912b.d
  test/fail_compilation/fail19912c.d
  test/fail_compilation/fail19912d.d
  test/fail_compilation/fail19912e.d
Labels: Bug Fix, C++ Port

#10001 [dmd-cxx] fix Issue 19914 - ICE: Segmentation fault with mixin and templated class
  src/attrib.c
  test/compilable/aggr_alignment.d
  test/fail_compilation/fail19914.d
  test/fail_compilation/fail19915.d
Labels: Bug Fix, C++ Port

#9997 [dmd-cxx] fix Issue 19897 - dinterpret.d:6439: Internal Compiler Error: null field
  src/dinterpret.c
  test/fail_compilation/fail19897.d
Labels: Bug Fix, C++ Port

#9998 [dmd-cxx] fix Issue 19898 - ICE: in sizemask at dmd/mtype.d(2563): Assertion failure
  src/intrange.c
  test/fail_compilation/fail19898a.d
  test/fail_compilation/fail19898b.d
Labels: Bug Fix, C++ Port

#9996 [dmd-cxx] Issue 15407 - Assert hit in toElem e2ir.c:1962
  src/expressionsem.c
  src/mtype.c
  src/statementsem.c
Labels: C++ Port

#9992 Add druntime's rt directory to the list of directories to omit in the test/tools/sanitize_json.d
  test/tools/sanitize_json.d
Labels: auto-merge

#10003 [dmd-cxx] fix Issue 19911 - ICE: Segmentation fault with struct object and variadic function
  src/func.c
  test/fail_compilation/extra-files/minimal/object.d
  test/fail_compilation/fail19911a.d
  test/fail_compilation/fail19911b.d
  test/fail_compilation/fail19911c.d
Labels: Bug Fix, C++ Port

#10004 [dmd-cxx] fix Issue 19922/19923 - 19922 - ICE: Segmentation fault with typeid()
  src/expressionsem.c
  src/mtype.c
  test/fail_compilation/fail19922.d
  test/fail_compilation/fail19923.d
Labels: Bug Fix, C++ Port

#10005 [dmd-cxx] fix Issue 19941 - [ICE] Segmentation fault in ImplicitConvTo::visit(AddrExp*) at dmd/dcast.d(980)
  src/expressionsem.c
  test/compilable/test19941.d
  test/fail_compilation/fail19941.d
Labels: Bug Fix, C++ Port

#10006 [dmd-cxx] fix Issue 19942 - [ICE] Segmentation fault in resolvePropertiesX at dmd/expressionsem.d:1112
  src/statementsem.c
  test/compilable/traits.d
Labels: Bug Fix, C++ Port

#10007 [dmd-cxx] fix Issue 19890 - ICE: Segmentation fault with negative array size
  src/mtype.c
  test/fail_compilation/fail19890a.d
  test/fail_compilation/fail19890b.d
Labels: Bug Fix, C++ Port, Enhancement

#10008 [dmd-cxx] dmd/declaration.c: Add VarDeclaration.create to C++ API
  src/declaration.c
  src/declaration.h
Labels: C++ Port, auto-merge

#10009 [dmd-cxx] Fix Issue 19856 - [aApplycd2]: foreach (int) doesn't work on BigEndian targets
  src/statementsem.c
  test/compilable/b16976.d
  test/compilable/interpret3.d
  test/fail_compilation/diag16976.d
  test/fail_compilation/fail110.d
Labels: C++ Port, Enhancement

#10012 iasmdmd.d: move public above fold
  src/dmd/iasmdmd.d
Labels: Refactoring, Trivial, auto-merge

#10014 escape.d: improve Ddoc
  src/dmd/escape.d
Labels: Trivial, auto-merge, documentation

#10015 add TupleExp::create
  src/dmd/expression.d
  src/dmd/expression.h
Labels: auto-merge

#9987 Define dmd variations in build.d
  src/build.d
Labels: auto-merge

#10016 Test case for 18698
  test/compilable/staticforeach.d
Labels: auto-merge

#10024 Add tests for PR dmd/8271
  test/fail_compilation/staticarrayoverflow.d
Labels: auto-merge

#10023 fix Issue 19955 - [ICE] Segmentation fault in StatementSemanticVisitor::visit(SwitchStatement*)
  src/dmd/statementsem.d
  test/fail_compilation/fail19955.d
Labels: Bug Fix, auto-merge

#10027 denum.d: improve comments
  src/dmd/denum.d
Labels: Refactoring, Trivial, auto-merge

#10025 [dmd-cxx] add numberOfElems() to mtype.c
  src/clone.c
  src/expressionsem.c
  src/mtype.c
  src/mtype.h
  src/todt.c
  src/toobj.c
  test/fail_compilation/staticarrayoverflow.d
Labels: C++ Port

#10030 Reduce indentation in importAll
  src/dmd/dimport.d
Labels: Easy Review, Refactoring, auto-merge

#10032 Minor C++ refactoring / bug fix
  src/dmd/cppmangle.d
  src/dmd/expression.d
  test/compilable/cppmangle.d
Labels: auto-merge

#10033 [dmd-cxx] fix Issue 19955 - [ICE] Segmentation fault in StatementSemanticVisitor::visit(SwitchStatement*)
  src/statementsem.c
  test/fail_compilation/fail19955.d
Labels: Bug Fix, C++ Port, auto-merge

#9965 Fix Issue 13848 - overlapping initialization for r
  src/dmd/dstruct.d
  test/fail_compilation/fail155.d
  test/fail_compilation/fail156.d
Labels: Bug Fix, auto-merge

#10019 fix issue 12950 - Lexer interprets UFCS on hex integer as hex float literal
  src/dmd/lexer.d
  test/runnable/literal.d
Labels: Bug Fix, auto-merge

#9817 add rvalues matching to ref parameters
  src/dmd/cli.d
  src/dmd/expressionsem.d
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/mtype.d
  test/compilable/rvalueref.d
  test/fail_compilation/ice8255.d
  test/runnable/overload.d
  test/runnable/structlit.d
  test/runnable/template9.d
  test/runnable/testassign.d
  test/runnable/xtest46.d
  test/runnable/xtest46_gc.d
Labels: 72h no objection -> merge, auto-merge

#10021 Refactor mangle-only `extern(C++, namespace)` into an AttribDeclaration
  src/dmd/aggregate.d
  src/dmd/astbase.d
  src/dmd/attrib.d
  src/dmd/attrib.h
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/dsymbolsem.d
  src/dmd/func.d
  src/dmd/nspace.d
  src/dmd/nspace.h
  src/dmd/parse.d
  src/dmd/parsetimevisitor.d
  src/dmd/scope.h
  src/dmd/visitor.h
  test/compilable/cppmangle.d
  test/compilable/cppmangle3.d
  test/fail_compilation/cppmangle.d
  test/runnable/cpp_abi_tests.d
  test/runnable/extra-files/cpp_abi_tests.cpp
Labels: auto-merge

#10036 Fix Issue 19954 - ICE: Casting AliasSeq to array and passing to a function
  src/dmd/expressionsem.d
  test/compilable/test19954.d
Labels: Bug Fix, Enhancement, auto-merge

#10038 [dmd-cxx] Backport early return of blockExit
  src/blockexit.c
Labels: C++ Port

#10040 fix issue 19971 - wrong string literals in "cannot pass argument" errors
  src/dmd/expressionsem.d
  test/fail_compilation/test19971.d
Labels: Bug Fix, auto-merge

#10034 Add myself as CODEOWNER of a couple files
  CODEOWNERS
Labels: Easy Review, Trivial, auto-merge

#10026 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  src/dmd/backend/cgelem.d
  src/dmd/cond.d
  src/dmd/e2ir.d
  src/dmd/expressionsem.d
  src/dmd/globals.d
  src/dmd/lexer.d
  src/dmd/statementsem.d
  test/compilable/b18439.d
  test/compilable/test19941.d
  test/compilable/test19954.d
  test/compilable/traits.d
  test/fail_compilation/fail19941.d
  test/fail_compilation/fail19955.d
  test/runnable/b19584.d
  test/runnable/cpp_abi_tests.d
  test/runnable/extra-files/cpp_abi_tests.cpp
  test/runnable/literal.d
Labels: Bug Fix

#10043 Add another test that used to SEGV before #9412
  test/fail_compilation/b19717a.d
Labels: auto-merge

#10045 workaround Issue 19974 - changed naked asm parameter offsets
  src/dmd/backend/cgobj.d
Labels: auto-merge

#10044 cppmangle: Follow up on #10021
  src/dmd/attrib.d
  src/dmd/cppmangle.d
  test/compilable/cppmangle.d
Labels: auto-merge

#10046 [dmd-cxx] Backport semanticRun refactoring and recursive semantic SEGV bug fixes
  src/dclass.c
  src/declaration.c
  src/denum.c
  src/dimport.c
  src/dinterpret.c
  src/dstruct.c
  src/dtemplate.c
  src/expression.c
  src/expressionsem.c
  src/func.c
  src/mtype.c
  src/optimize.c
  src/statement.c
  src/statementsem.c
  src/toobj.c
  src/traits.c
  test/compilable/imports/test16214b.d
  test/compilable/test16214a.d
  test/fail_compilation/b15875.d
  test/fail_compilation/b17285.d
  test/fail_compilation/b19691.d
  test/fail_compilation/b19691e.d
  test/fail_compilation/b19717.d
  test/fail_compilation/b19717a.d
  test/fail_compilation/fail19336.d
Labels: Bug Fix, C++ Port

#10039 fix issue 19969 - Unhelpful error when attempting (incorrectly) to append to a string
  src/dmd/arrayop.d
  test/fail_compilation/fail_arrayop1.d
Labels: Enhancement, auto-merge

#9993 encapsulate CSE
  src/dmd/backend/cgcod.d
  src/dmd/backend/cgcse.d
  src/dmd/backend/cod3.d
Labels: Refactoring

#9994 add -fPIE support to front end
  src/dmd/backend/backconfig.d
  src/dmd/backend/cdef.d
  src/dmd/backend/cgelem.d
  src/dmd/backend/cod1.d
  src/dmd/backend/cod2.d
  src/dmd/backend/elem.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/ty.d
  src/dmd/dmsc.d
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/iasmdmd.d
  src/dmd/mars.d
  test/fail_compilation/fail13939.d
  test/fail_compilation/reserved_version.d
  test/runnable/iasm.d
  test/runnable/iasm64.d
  test/runnable/s2ir.d
  test/runnable/testpic.d
  test/runnable/testxmm.d
  test/runnable/xtest46.d
Labels: auto-merge

#10051 Don't crash when compiling for 16-bit platforms
  src/dmd/astbase.d
  src/dmd/expression.d
  src/dmd/hdrgen.d
Labels: auto-merge

#10053 cppmangle: Add more tests, fix double 'N'
  src/dmd/cppmangle.d
  test/compilable/cppmangle.d
  test/compilable/cppmangle2.d
Labels: auto-merge

#10054 Version out assert in cppmangle
  src/dmd/cppmangle.d
Labels: Easy Review, Trivial, auto-merge

#10052 elfobj.d: refactor with const and reltype_t
  src/dmd/backend/elfobj.d
Labels: Easy Review, Refactoring, auto-merge

#10056 fix Issue 19646 - Initialization of globals not checked for @safe
  src/dmd/expressionsem.d
  test/fail_compilation/test19646.d
Labels: Bug Fix

#10058 [stable] Fix `extern(C++, "namespace")` following refactor
  src/dmd/attrib.d
  src/dmd/cppmangle.d
  test/compilable/cppmangle.d
  test/compilable/cppmangle2.d
Labels: auto-merge

#9909 Fix Issue 19122 - Postblits and destructors called on members of anonymous unions
  changelog/union_members.dd
  src/dmd/aggregate.d
  src/dmd/dscope.d
  src/dmd/dsymbolsem.d
  src/dmd/scope.h
  test/runnable/test19122.d
Labels: Bug Fix, Enhancement, auto-merge-squash

#10059 elpicpie.d: carve out from elem.d
  src/dmd/backend/el.d
  src/dmd/backend/elem.d
  src/dmd/backend/elpicpie.d
  src/posix.mak
  src/win32.mak
Labels: Easy Review, Refactoring, auto-merge

#10047 fix Issue 19758 - (0x01 & 0xFF) == 0 by dmd 2.085.0(-m64) on Window
  src/dmd/backend/cod3.d
  test/runnable/test15.d
Labels: Bug Fix

#10061 dmd/utils.d: Remove extern(C++) linkage from internal helpers
  src/dmd/utils.d
Labels: auto-merge

#10060 dmd/statement.h: Fix virtual hidden by overload errors
  src/dmd/statement.h
Labels: Regression, auto-merge

#10062 dmd/root: Fix C++ headers to match new signatures
  src/dmd/root/outbuffer.h
  src/dmd/root/port.h
Labels: Regression, auto-merge

#10063 dmd/module.h: Fix undefined reference to Module::read
  src/dmd/module.h
Labels: Regression, auto-merge

#10065 Update C++ headers - Follow up to #9282
  src/dmd/aggregate.h
  src/dmd/declaration.h
  src/dmd/expression.h
Labels: auto-merge

#10067 fix issue 9884 - Refused initialization of const array in the module static this()
  src/dmd/expressionsem.d
  test/compilable/issue9884.d
Labels: Bug Fix, auto-merge

#10068 fix issue 19925 - static opDispatch not considered in WithStatement
  src/dmd/expressionsem.d
  test/compilable/issue19925.d
Labels: Bug Fix, auto-merge

#10066 elpicpie.d: publics above the fold, privates below
  src/dmd/backend/elpicpie.d
Labels: Refactoring, Trivial, auto-merge

#10074 fix issue 19995 - parameter attributes are accepted in parameter-less functions
  src/dmd/parse.d
  test/fail_compilation/misc_parser_err_cov1.d
Labels: Bug Fix

#10075 Fix Issue 19534 - Wrong error message "only one index allowed to index int"
  src/dmd/expressionsem.d
  src/dmd/mtype.d
  src/dmd/opover.d
  test/fail_compilation/fail15.d
  test/fail_compilation/fail_arrayexp.d
Labels: Bug Fix, auto-merge

#9979 Allow dependencies to specify name/description
  src/build.d
Labels: Enhancement, auto-merge

#10082 Remove Dsymbol.toParent3()
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
Labels: Refactoring, auto-merge

#10081 Merge remote-tracking branch 'upstream/stable' into merge_stable
  .azure-pipelines/windows-visual-studio.yml
  VERSION
  src/dmd/backend/cod3.d
  src/dmd/parse.d
  test/fail_compilation/misc_parser_err_cov1.d
  test/runnable/test15.d
Labels: Bug Fix, auto-merge, stable -> master

#10085 Fix Issue 20001 - Error: a struct is not a valid initializer for a _error_
  src/dmd/initsem.d
  test/fail_compilation/fail346.d
Labels: Bug Fix, Trivial, auto-merge

#10057 Fix Issue 19931 - Missing error message when defining postblit, rvalue constructor and copy constructor
  src/dmd/dsymbolsem.d
  test/fail_compilation/fail19931.d
Labels: Bug Fix, auto-merge

#10084 convert addMod() to modToTym()
  src/dmd/glue.d
  src/dmd/toctype.d
Labels: Easy Review, Refactoring, auto-merge

#10080 Issue 20000 - Casting to interfaces disallowed in @safe code
  src/dmd/safe.d
  test/compilable/test20000.d
  test/fail_compilation/fail20000.d
Labels: Bug Fix, auto-merge

#10088 fix issue 15478 - cases of missed CTFE evaluation when defining arrays dimensions
  src/dmd/typesem.d
  test/compilable/issue15478.d
Labels: Bug Fix, auto-merge

#10089 Set correct type on IR element - Followup to #9946
  src/dmd/e2ir.d
Labels: auto-merge

#10086 Fix issue 19315 - #line inside token string affect outside code
  src/dmd/lexer.d
  test/compilable/test19315.d
Labels: Bug Fix, auto-merge

#10090 Revert "Fix issue 19315 - #line inside token string affect outside code"
  src/dmd/lexer.d
  test/compilable/test19315.d
Labels: Bug Fix, auto-merge

#10013 Add `__traits(getLocation)`
  changelog/getloc.dd
  src/dmd/id.d
  src/dmd/traits.d
  test/compilable/traits.d
  test/fail_compilation/trait_loc_ov_err.d
Labels: auto-merge-squash

#10091 Fix issue 19315 (follow-up) - #line inside token string affect outside code
  src/dmd/lexer.d
  test/compilable/test19315.d
Labels: Bug Fix, auto-merge

#10071 C++ headers Integrity check - follows #10065
  src/dmd/dsymbol.h
  src/tests/cxxfrontend.c
Labels: auto-merge

#10087 Fix undefined reference to 'ParameterList::opIndex(unsigned long)'
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/globals.h
  src/dmd/mtype.h
  src/dmd/root/rmem.h
  src/posix.mak
  src/tests/cxxfrontend.c
Labels: auto-merge-squash

#10101 Fix typo, makes it annoying to auto-port frontend to Java
  src/dmd/astbase.d
Labels: Trivial, auto-merge-squash

#10077 fix issue 15818 - Multiple function declarations without definition cause ambiguity overloading error
  src/dmd/dtemplate.d
  test/compilable/issue15818.d
Labels: Bug Fix, auto-merge

#10100 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
Labels: auto-merge

#10104 [stable] test/runnable/testargtypes.d: Remove (debugging aid) output
  test/runnable/testargtypes.d
Labels: auto-merge

#10109 Mark many semantic-only final functions as extern(D)
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/ctfe.h
  src/dmd/ctfeexpr.d
  src/dmd/dclass.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dimport.d
  src/dmd/dmodule.d
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/func.d
  src/dmd/identifier.h
  src/dmd/import.h
  src/dmd/init.d
  src/dmd/init.h
  src/dmd/module.h
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/root/array.h
  src/dmd/root/object.h
  src/dmd/root/rootobject.d
  src/dmd/scope.h
  src/dmd/statement.h
  src/dmd/statementsem.d
  src/dmd/target.d
  src/dmd/template.h
Labels: auto-merge

#10107 Fix undefined reference to Loc:Loc()
  src/dmd/globals.h
  src/tests/cxxfrontend.c
Labels: auto-merge

#10110 fix: regular text in code block in dep_type_error.dd
  changelog/dep_type_error.dd
Labels: auto-merge

#10113 root/dcompat.h: Add a DString type and constructor helper
  src/dmd/declaration.h
  src/dmd/globals.h
  src/dmd/identifier.h
  src/dmd/module.h
  src/dmd/root/dcompat.h
  src/dmd/root/filename.h
  src/dmd/root/object.h
  src/tests/cxxfrontend.c
Labels: auto-merge

#10114 Add hasMonitor to C++ headers, introduced in #9677
  src/dmd/aggregate.h
  src/tests/cxxfrontend.c
Labels: auto-merge
