Repository dlang/dmd, pull requests merged in 2019-10, with the labels that each got.

#10443 Fix Issue 3004 - Better handling of ignored pragmas
  src/dmd/dsymbolsem.d
  test/compilable/test3004.d
Labels: Easy Review, Enhancement, auto-merge

#10440 Move dmd_frontend to build.d
  src/build.d
  src/posix.mak
  src/win32.mak
Labels: auto-merge

#10421 azure: extract batch commands from yml to file for better reusage
  .azure-pipelines/windows-msbuild.bat
  .azure-pipelines/windows-visual-studio.yml
Labels: auto-merge

#10446 Compile dmd exe in build.d
  src/build.d
  src/posix.mak
  src/win32.mak
Labels: auto-merge

#10449 ctfeexpr.d: use switch statements
  src/dmd/ctfeexpr.d
Labels: Easy Review, Refactoring, auto-merge

#10447 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  src/dmd/cppmangle.d
  src/dmd/escape.d
  test/compilable/cppmangle.d
  test/fail_compilation/test20149.d
Labels: Bug Fix, auto-merge, stable -> master

#10451 [stable] DIP1008: Fix leaking exceptions for `catch(T)` without identifier
  src/dmd/statementsem.d
  test/runnable/test19317.d
Labels: auto-merge

#10457 saveGlobalConstant: fix region memory leak
  src/dmd/dinterpret.d
Labels: Bug Fix, auto-merge

#10456 add bug flushing option to region.d
  src/dmd/hdrgen.d
  src/dmd/root/region.d
Labels: auto-merge

#10450 Fix issue 20267 - Error: `string` is used as a type - and similar “smart” error messages
  src/dmd/typesem.d
  test/fail_compilation/imports/test20267.d
  test/fail_compilation/test20267.d
  test/fail_compilation/typeerrors.d
Labels: Bug Fix, auto-merge

#10455 Remove backend globals from header modules
  src/dmd/backend/cg87.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod1.d
  src/dmd/backend/cod2.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code.d
  src/dmd/backend/code_x86.d
Labels: auto-merge

#10464 make OutBuffer.data an array
  src/dmd/objc.d
  src/dmd/root/outbuffer.d
Labels: Refactoring, auto-merge

#10466 remove OutBuffer.peekSlice(), replace with []
  src/dmd/dinifile.d
  src/dmd/dmangle.d
  src/dmd/dmodule.d
  src/dmd/doc.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/errors.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/hdrgen.d
  src/dmd/identifier.d
  src/dmd/lambdacomp.d
  src/dmd/lexer.d
  src/dmd/lib.d
  src/dmd/mars.d
  src/dmd/mtype.d
  src/dmd/root/outbuffer.d
  src/dmd/statementsem.d
  src/dmd/typesem.d
Labels: Easy Review, Refactoring, auto-merge

#10473 use extractSlice() instead of extractData()
  src/dmd/dcast.d
  src/dmd/declaration.d
  src/dmd/dmodule.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/filecache.d
  src/dmd/glue.d
  src/dmd/libelf.d
  src/dmd/libmach.d
  src/dmd/libmscoff.d
  src/dmd/libomf.d
  src/dmd/mars.d
  src/dmd/root/file.d
  src/dmd/tokens.d
  src/dmd/utils.d
Labels: Easy Review, Refactoring

#10441 [RFC] Add -Xcc= compiler switch
  changelog/noxlinker.dd
  changelog/xcc.dd
  src/dmd/cli.d
  src/dmd/globals.d
  src/dmd/link.d
  src/dmd/mars.d
  test/dshell/test6952.d
Labels: auto-merge

#10471 Remove debug logging from verbose output
  src/dmd/dinterpret.d
  src/dmd/expressionsem.d
Labels: auto-merge

#10470 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  src/dmd/statementsem.d
  test/runnable/test19317.d
Labels: auto-merge

#10475 reduce use of extractChars()
  src/dmd/dsymbolsem.d
  src/dmd/lambdacomp.d
  src/dmd/statement.d
  src/dmd/tokens.d
  src/dmd/traits.d
  src/dmd/typesem.d
Labels: Easy Review, Refactoring

#10483 StringExp.peekSlice(): rename to peekString()
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/traits.d
Labels: Easy Review, Refactoring, auto-merge

#10485 replace direct use StringExp with functions
  src/dmd/constfold.d
  src/dmd/ctfeexpr.d
  src/dmd/dcast.d
  src/dmd/dinterpret.d
  src/dmd/dmangle.d
  src/dmd/dmodule.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
Labels: Easy Review, Refactoring

#10488 add StringExp.setData()
  src/dmd/dcast.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
Labels: Easy Review, Refactoring, auto-merge

#10459 [stable] Fix linker flags with blanks on Windows
  src/dmd/link.d
  test/dshell/extra-files/linker_flag_with_spaces_a.d
  test/dshell/extra-files/linker_flag_with_spaces_b.d
  test/dshell/linker_flag_with_spaces.d
Labels: Enhancement, auto-merge-squash

#10480 build.d: Fix host compiler detection for LDC
  src/build.d
Labels: auto-merge

#10486 dmd/root/array.h: Align field names and access modifiers to match D sources
  src/dmd/root/array.h
Labels: GDC

#10493 [stable] Fix 2.089 C++ header regressions
  src/dmd/globals.h
  src/dmd/root/outbuffer.h
  src/dmd/tokens.h
Labels: auto-merge

#10461 hdrgen.d: fix printf format
  src/dmd/hdrgen.d
Labels: auto-merge

#10495 pass [] instead of * to StringExp constructors
  src/dmd/arrayop.d
  src/dmd/astbase.d
  src/dmd/clone.d
  src/dmd/constfold.d
  src/dmd/ctfeexpr.d
  src/dmd/e2ir.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/opover.d
  src/dmd/parse.d
  src/dmd/semantic3.d
  src/dmd/statementsem.d
  src/dmd/target.d
  src/dmd/traits.d
  src/dmd/typesem.d
Labels: Refactoring, auto-merge

#10478 root/array.d: convert data from pointer to array
  src/dmd/root/array.d
  src/dmd/root/array.h
Labels: Easy Review, Refactoring, auto-merge

#10497 dmd/root/array.h: Convert internal data from pointer to DArray.
  src/dmd/root/array.h
  src/tests/cxxfrontend.c
Labels: GDC, Refactoring, auto-merge

#10487 more conversion to using peekString()
  src/dmd/objc.d
  src/dmd/semantic2.d
  src/dmd/statementsem.d
Labels: Easy Review, Refactoring

#10500 add root/bitarray.d
  src/build.d
  src/dmd/arraytypes.h
  src/dmd/compiler.h
  src/dmd/dsymbol.d
  src/dmd/root/array.d
  src/dmd/root/array.h
  src/dmd/root/bitarray.d
  src/dmd/root/bitarray.h
  src/posix.mak
  src/win32.mak
Labels: Easy Review, Refactoring, auto-merge

#10501 remove StringExp.toPtr()
  src/dmd/e2ir.d
  src/dmd/expression.d
  src/dmd/iasmdmd.d
  src/dmd/todt.d
  src/dmd/traits.d
Labels: Refactoring, auto-merge

#10468 fix issue 15118 - Win32: default to using optlink.exe with the Digital Mars toolchain
  changelog/optlink.dd
  ini/windows/bin/sc.ini
  src/dmd/link.d
Labels: Enhancement, auto-merge

#10489 Update handling of HOST_DMD when performing builds.
  .circleci/run.sh
  src/build.d
  src/posix.mak
Labels: auto-merge

#10496 make StringExp's union private
  src/dmd/dcast.d
  src/dmd/expression.d
Labels: Easy Review, Refactoring, auto-merge

#10448 Move checkwhitespace to build.d
  src/build.d
  src/posix.mak
  src/win32.mak
Labels: auto-merge

#10445 Remove building dmd_frontend executable
  src/build.d
  src/posix.mak
  src/win32.mak
Labels: Build System, auto-merge

#10477 Fix broken C++ headers and broken bootstrap builds
  src/dmd/cppmangle.d
  src/dmd/expression.h
  src/dmd/globals.h
  src/dmd/mtype.h
  src/dmd/root/dcompat.h
  src/dmd/root/outbuffer.d
  src/dmd/root/outbuffer.h
  src/dmd/root/rmem.h
  src/tests/cxxfrontend.c
  test/compilable/cppmangle.d
Labels: 72h no objection -> merge, GDC, Regression, auto-merge

#10507 src/expression.h: Remove StringExp::toPtr from headers
  src/dmd/expression.h
Labels: GDC

#10508 carve foreachvar.d out of dinterpret.d
  src/build.d
  src/dmd/dinterpret.d
  src/dmd/foreachvar.d
  src/posix.mak
  src/win32.mak
Labels: Easy Review, Refactoring, auto-merge

#10511 Fix Issue 20326 - stringof on opaque type results in forward referenc…
  src/dmd/dclass.d
  src/dmd/dstruct.d
  test/compilable/test20326.d
Labels: Bug Fix, auto-merge

#10515 BitArray: add opEquals(), and change allocation size to size_t
  src/dmd/root/bitarray.d
Labels: auto-merge

#10514 Move zip to build.d
  src/build.d
  src/posix.mak
  src/win32.mak
Labels: auto-merge

#10520 Try fixing code coverage with relative paths
  src/build.d
Labels: Build System, Continuous Integration, auto-merge

#10516 Move html gen to build.d
  src/build.d
  src/posix.mak
Labels: Build System, auto-merge, documentation

#10521 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/optlink.dd
  ini/windows/bin/sc.ini
  src/dmd/link.d
  src/dmd/tokens.h
  test/dshell/extra-files/linker_flag_with_spaces_a.d
  test/dshell/extra-files/linker_flag_with_spaces_b.d
  test/dshell/linker_flag_with_spaces.d
Labels: Enhancement, auto-merge, stable -> master

#10523 Improve code coverage a bit more by enabling it in the lexer library
  src/build.d
Labels: Build System, Continuous Integration, auto-merge

#10517 Fix Issue 20318 - Illegal instruction (core dumped)
  src/dmd/e2ir.d
  test/compilable/test20318.d
Labels: Bug Fix, auto-merge
