Repository dlang/dmd, pull requests merged in 2019-12, with the labels that each got.

#10631 build.d: Add toolchain-info as dependency of auto-tester-build
  posix.mak
  src/build.d
Labels: auto-merge

#10633 add links to documentation for rvalue ref implementation
  src/dmd/globals.d
Labels: auto-merge, documentation

#10639 build.d: Propagate whether a dependency was built/skipped
  src/build.d
Labels: auto-merge

#10640 fix Issue 20416 - [Regression 2.073.2] compiler complains about escap…
  src/dmd/escape.d
  test/compilable/fix20416.d
Labels: Bug Fix, Regression

#10645 Fix C++ signature of isDstyleVariadic
  src/dmd/mtype.h
  src/tests/cxxfrontend.c
Labels: GDC, auto-merge

#10647 small refactor of arrayOp()
  src/dmd/arrayop.d
Labels: Easy Review, Refactoring

#10650 test: Use EXTRA_SOURCES instead of REQUIRED_ARGS for sources
  test/compilable/minimal.d
  test/compilable/minimal2.d
  test/compilable/test17541.d
  test/fail_compilation/fail18938.d
  test/fail_compilation/fail19911b.d
  test/fail_compilation/no_Throwable.d
  test/fail_compilation/no_TypeInfo.d
  test/fail_compilation/verifyhookexist.d
  test/runnable/minimal.d
  test/runnable/minimal2.d
  test/runnable/pubprivtmpl.d
Labels: auto-merge

#10649 test: Document extra source files used by test cases
  test/compilable/filefullpath_18911.d
  test/compilable/test13582a.d
  test/compilable/test13582b.d
  test/compilable/test16088.d
  test/compilable/test16214a.d
  test/compilable/test19187.d
  test/fail_compilation/fail20163.d
  test/fail_compilation/fail20164.d
  test/fail_compilation/test20267.d
  test/runnable/cppa.d
Labels: auto-merge

#10651 dmd/tocsym.d: Remove dead code calling generateId
  src/dmd/tocsym.d
Labels: GDC, auto-merge

#10610 build.d: put dmd sources into its own struct
  src/build.d
Labels: auto-merge

#10609 move install-copy from win32.mak to build.d
  src/build.d
  src/win32.mak
Labels: auto-merge

#10629 Fix issue 20431 - Allow a Mixin Type to resolve to an expression
  src/dmd/astbase.d
  src/dmd/mtype.d
  src/dmd/parse.d
  src/dmd/traits.d
  src/dmd/typesem.d
  test/compilable/mixintype2.d
Labels: Bug Fix, auto-merge

#10648 Remove constant folding of powers in the compiler.
  src/dmd/expressionsem.d
  src/dmd/optimize.d
  test/runnable/ctorpowtests.d
  test/runnable/xtest46.d
Labels: auto-merge

#10636 build.d: rename Dependency to BuildRule
  src/build.d
Labels: auto-merge

#10653 refactor: replace peek(&token).value with peekNext in parser
  src/dmd/parse.d
Labels: auto-merge

#10656 refactor intrinsic op
  src/dmd/id.d
  src/dmd/toir.d
Labels: auto-merge

#10322 statement_toIR(): simplify conversion of case statements to goto
  src/dmd/s2ir.d
  src/dmd/statement.d
  src/dmd/statement.h
Labels: Easy Review, Refactoring, auto-merge

#10652 fix Issue 20349 - [REG2.087] ICE with sqrt
  src/dmd/backend/cg87.d
  src/dmd/backend/cod2.d
  test/runnable/testfloat.d
Labels: Bug Fix, Regression, auto-merge

#10658 clean up intrinsic
  src/dmd/toir.d
Labels: auto-merge

#10643 build.d: Save whether dependency was updated
  src/build.d
Labels: auto-merge

#10635 Issue6592 - di header file created even if errors occur
  src/dmd/dmodule.d
  src/dmd/mars.d
  test/fail_compilation/extra-files/fail6592.d
  test/fail_compilation/fail6592.sh
Labels: Bug Fix, auto-merge-squash

#10662 Fix circle CI issue "MODEL: unbound variable"
  .circleci/run.sh
Labels: auto-merge

#10661 fix Issue 20441 - Wrong code with -O -fPIC and pointer subtraction
  src/dmd/backend/cod2.d
  test/runnable/testpic.d
Labels: Bug Fix, auto-merge

#10634 Issue17125 - Header Generation Incorrectly Formats Floating Point Number
  src/dmd/hdrgen.d
  test/compilable/extra-files/header17125.d
  test/compilable/extra-files/header17125.di
  test/compilable/testheader17125.d
Labels: Bug Fix

#10665 intrinsic_op: restrict math operations to actually implemented overloads
  src/dmd/toir.d
Labels: auto-merge

#10671 posix.mak: Don't invoke build.d twice to build dmd
  src/posix.mak
Labels: auto-merge

#10669 support VERBOSE=1 from makefiles
  src/build.d
  src/win32.mak
  src/win64.mak
Labels: auto-merge

#10659 build.d: make toolchain-info's output thread-safe
  src/build.d
Labels: auto-merge

#10667 dmd built with longdouble_soft: fix printing float.inf at compile time
  src/dmd/root/longdouble.d
Labels: auto-merge

#10666 azure: do not display the OMF build as x64, but win32
  azure-pipelines.yml
Labels: Easy Review, Trivial, auto-merge

#10676 Fix Issue 20448 - Error: unknown when mutating an escaped member reference from a template function
  src/dmd/expressionsem.d
  test/fail_compilation/fail20448.d
Labels: Enhancement

#10642 fix Issue 20383 - [REG 2.084.z] illegal conversion from int[] to ubyt…
  src/dmd/arrayop.d
  src/dmd/dcast.d
  test/fail_compilation/test20383.d
Labels: Bug Fix, Regression, auto-merge

#10675 Fix Issue 20151 - particular directory layout causes DMD to crash
  src/dmd/dsymbol.d
  src/dmd/dsymbolsem.d
  test/compilable/imports/test20151a/b/c/c.d
  test/compilable/test20151a.d
Labels: Bug Fix, auto-merge-squash

#10654 Add core.math.toPrec intrinsics
  src/dmd/backend/cgcod.d
  src/dmd/backend/cgelem.d
  src/dmd/backend/oper.d
  src/dmd/builtin.d
  src/dmd/e2ir.d
  src/dmd/id.d
  src/dmd/toir.d
  test/runnable/interpret.d
Labels: auto-merge

#10403 remove getLabel() and labelToBlock() as dead code
  src/dmd/s2ir.d
Labels: Easy Review, Refactoring, auto-merge

#10484 Merge remote-tracking branch 'upstream/stable' into merge_stable
  .circleci/run.sh
  VERSION
  changelog/deprecate_foreach_shadowing.dd
  changelog/isexpression-const-inout-shared.dd
  changelog/mixin_template_mangling.dd
  changelog/optlink.dd
  changelog/xcc.dd
  src/dmd/astbase.d
  src/dmd/backend/cg87.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod2.d
  src/dmd/backend/cv8.d
  src/dmd/backend/dcgcv.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dinterpret.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/escape.d
  src/dmd/expressionsem.d
  src/dmd/globals.d
  src/dmd/hdrgen.d
  src/dmd/hdrgen.h
  src/dmd/id.d
  src/dmd/inline.d
  src/dmd/mtype.d
  src/dmd/optimize.d
  src/dmd/parse.d
  src/dmd/root/outbuffer.d
  src/dmd/root/outbuffer.h
  src/dmd/semantic2.d
  src/dmd/semantic3.d
  src/dmd/traits.d
  src/dmd/typesem.d
  test/compilable/extra-files/test20280a.d
  test/compilable/fix20416.d
  test/compilable/ice20092.d
  test/compilable/mixintype2.d
  test/compilable/test20280.d
  test/compilable/test20388.d
  test/compilable/test20420.d
  test/compilable/test9029.d
  test/fail_compilation/b15069.d
  test/fail_compilation/fail104.d
  test/fail_compilation/fail20376.d
  test/fail_compilation/fail280.d
  test/fail_compilation/fail281.d
  test/fail_compilation/fail282.d
  test/fail_compilation/ice20264.d
  test/runnable/interpret.d
  test/runnable/testfloat.d
  test/runnable/testpdb.d
  test/runnable/testpic.d
Labels: Enhancement

#10683 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/dmd/arrayop.d
  src/dmd/dcast.d
  src/dmd/dsymbol.d
  src/dmd/dsymbolsem.d
  test/compilable/imports/test20151a/b/c/c.d
  test/compilable/test20151a.d
  test/fail_compilation/test20383.d
Labels: Bug Fix

#10684 test/runnable: Version out DMD or x86-specific tests
  test/runnable/arrayop.d
  test/runnable/bitops.d
  test/runnable/constfold.d
Labels: Easy Review, auto-merge

#10686 Fix Issue 9937: CTFE floats don't overflow correctly
  test/compilable/interpret3.d
Labels: Bug Fix

#10688 test: Add EXTRA_FILES to compilable/test20280.d
  test/compilable/test20280.d
Labels: Easy Review

#10689 test: Update test42.d to use intrinsic va_args
  test/runnable/test42.d
Labels: Easy Review

#10691 dmd/builtin: Add std.math.trig.tan intrinsic
  src/dmd/builtin.d
  src/dmd/id.d
  src/dmd/toir.d
Labels: auto-merge

#10687 azure: run druntime tests for x64 and OMF builds, too
  .azure-pipelines/windows.sh
Labels: auto-merge

#10693 Fix issue 19325 - Deprecate body keyword
  changelog/body-as-keyword.dd
  src/dmd/astbase.d
  src/dmd/compiler.d
  src/dmd/frontend.d
  src/dmd/lexer.d
  src/dmd/objc.d
  src/dmd/objc_glue.d
  src/dmd/parse.d
  src/dmd/root/man.d
  test/compilable/b16967.d
  test/compilable/interpret3.d
  test/fail_compilation/fail17502.d
  test/fail_compilation/fail2350.d
  test/fail_compilation/fail329.d
  test/fail_compilation/fail330.d
  test/fail_compilation/fail6242.d
  test/fail_compilation/fail94.d
  test/fail_compilation/fail9413.d
  test/fail_compilation/fail9414a.d
  test/fail_compilation/fail9414b.d
  test/fail_compilation/fail9414c.d
  test/fail_compilation/fail9414d.d
  test/fail_compilation/fail_scope.d
  test/fail_compilation/issue19325.d
  test/runnable/interface2.d
  test/runnable/nested.d
  test/runnable/test23.d
  test/runnable/test42.d
  test/runnable/test8.d
  test/runnable/testassign.d
  test/runnable/testdstress.d
  test/runnable/xtest46.d
Labels: Bug Fix

#10696 fix Issue 20466 - Optimizer clobbering msw register when testing it f…
  src/dmd/backend/cod1.d
  test/runnable/fix20466.d
Labels: Bug Fix, auto-merge

#10697 fix Issue 10100 - Identifiers with double underscores and allMembers
  src/dmd/traits.d
  test/runnable/traits.d
Labels: Bug Fix, auto-merge

#10695 Fix C++ mangling of argument packs
  src/dmd/cppmangle.d
  test/runnable/cpp_abi_tests.d
  test/runnable/extra-files/cpp_abi_tests.cpp
Labels: Bug Fix, auto-merge

#10698 Fix Issue 20465 - Dynamic + static array declaration fail
  src/dmd/expressionsem.d
  test/runnable/b10562.d
Labels: Bug Fix, auto-merge

#10701 dmd.cli: Separate help options from general options and ASCII collate a couple usage options
  src/dmd/cli.d
Labels: Refactoring, auto-merge

#10663 build.d: fix numbered bool variables like ENABLE_RELEASE
  src/build.d
Labels: auto-merge

#10703 build.d: Fixup install-copy
  src/build.d
Labels: auto-merge

#10670 build.d: Move install from posix.mak
  src/build.d
  src/posix.mak
Labels: auto-merge

#10705 Disable `make install` for the Darwin_64_32 target on the auto-tester
  posix.mak
Labels: auto-merge
