Repository dlang/dmd, pull requests merged in 2020-07, with the labels that each got.

#11347 fix Issue 20981 - Segfault for inlined __simd_sto
  src/dmd/backend/glocal.d
  test/runnable/testxmm.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#11358 test: Add or fix EXTRA_FILES directives to runnable tests
  test/runnable/foreach5.d
  test/runnable/ice15030.d
  test/runnable/link10920.d
  test/runnable/link11069a.d
  test/runnable/link11127.d
  test/runnable/link12037.d
  test/runnable/link13043.d
  test/runnable/link14074a.d
  test/runnable/link14074b.d
  test/runnable/link14541.d
  test/runnable/link14992.d
  test/runnable/link15021.d
  test/runnable/link6574.d
  test/runnable/mangle.d
  test/runnable/overload.d
  test/runnable/template13478.d
  test/runnable/template9.d
  test/runnable/test10378.d
  test/runnable/test10736.d
  test/runnable/test11863.d
  test/runnable/test15079.d
  test/runnable/test17181b.d
  test/runnable/test9271.d
  test/runnable/testptrref_gc.d
  test/runnable/traits.d
  test/runnable/uda.d
Labels: Trivial, auto-merge

#11359 fix issue 12504 - Wrong 'cannot cover index range' error message
  src/dmd/statementsem.d
  test/compilable/b12504.d
  test/fail_compilation/b12504.d
Labels: Bug Fix, auto-merge

#11356 Fix issue 21001: alias protection is ignored if used before declaration.
  src/dmd/dsymbolsem.d
  test/fail_compilation/fail21001.d
  test/fail_compilation/imports/fail21001b.d
Labels: auto-merge

#11355 convert bl_enlist() to Barray
  src/dmd/backend/blockopt.d
Labels: Refactoring, auto-merge

#11361 Fix AA iteration order dependency in testaa2.d
  test/runnable/testaa2.d
Labels: auto-merge

#11305 fix Issue 18748 - bt instruction with immediate offset uses 64-bit va…
  src/dmd/backend/cgelem.d
  src/dmd/backend/cod4.d
  test/runnable/testbtst.d
Labels: Bug Fix, auto-merge

#11348 Make -{preview|revert|transition}=all work again
  src/dmd/cli.d
  src/dmd/mars.d
  test/compilable/previewall.d
  test/compilable/previewhelp.d
  test/compilable/reverthelp.d
  test/compilable/transitionhelp.d
Labels: Bug Fix, Easy Review, auto-merge

#11253 Fix Issue 20909 - .offsetof fails on forward reference of field
  src/dmd/typesem.d
  test/compilable/test20909.d
Labels: Bug Fix, auto-merge

#11360 replace an `AliasDeclaration` field by an `STC` flag
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dtemplate.d
Labels: Refactoring, auto-merge

#11257 fix Issue 20363 - painting XMM registers as integers leads to codegen…
  src/dmd/backend/gflow.d
  src/dmd/backend/gother.d
  test/runnable/mars1.d
Labels: Bug Fix, auto-merge

#11364 Enable nothrow in debug inference test
  test/compilable/debugInference.d
Labels: Easy Review, Trivial, auto-merge

#11366 merge stable
  VERSION
  src/dmd/statementsem.d
  test/compilable/b12504.d
  test/fail_compilation/b12504.d
Labels: Bug Fix, auto-merge

#11367 remove unused NullExp.committed field
  src/dmd/dcast.d
  src/dmd/expression.d
  src/dmd/expression.h
Labels: auto-merge

#10018 Fix Issue 19277 - storage class used in alias statement has no effect
  src/dmd/parse.d
  test/fail_compilation/parse19277.d
Labels: Enhancement, auto-merge

#11337 Fix Issue 20989 - Checking array.ptr causes safety error ...
  src/dmd/expressionsem.d
  test/compilable/test20100.d
Labels: Bug Fix

#11350 add <= support to loop unroller
  src/dmd/backend/gloop.d
  test/runnable/mars1.d
Labels: auto-merge

#11372 fix issue 11624 - __trait(compiles) does not detect unimplemented int…
  test/compilable/compile1.d
Labels: Bug Fix, auto-merge

#11371 Improve documentation in aggregate.d, attrib.d
  src/dmd/aggregate.d
  src/dmd/attrib.d
Labels: auto-merge

#11370 optimize memory layout of aggregates
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/dstruct.d
Labels: auto-merge

#11376 replace struct UnrollWalker with unrollWalker()
  src/dmd/backend/gloop.d
Labels: Easy Review, Refactoring

#11363 Type: add mcache
  .gitignore
  src/dmd/astbase.d
  src/dmd/mtype.d
  src/dmd/mtype.h
Labels: Refactoring, auto-merge

#11375 remove unused Scope* sc from TypeAArray, avoiding stale pointers
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/typesem.d
Labels: auto-merge

#11380 Fix 21019 - Replace rm with rm_retry in shell scripts
  test/compilable/ddoc9764.sh
  test/compilable/extra-files/ddocAny-postscript.sh
  test/compilable/extra-files/ddocYear-postscript.sh
  test/compilable/extra-files/header-postscript.sh
  test/compilable/extra-files/json-postscript.sh
  test/compilable/extra-files/objdump-postscript.sh
  test/compilable/extra-files/vcg-ast-postscript.sh
  test/compilable/issue17167.sh
  test/compilable/jsonNoOutFile.sh
  test/compilable/test14894.sh
  test/compilable/test19463.sh
  test/compilable/test6461.sh
  test/compilable/test9680.sh
  test/runnable/cdvecfill.sh
  test/runnable/extra-files/coverage-postscript.sh
  test/runnable/extra-files/hello-profile-postscript.sh
  test/runnable/test18076.sh
  test/runnable/test_switches.sh
Labels: Bug Fix, Continuous Integration, Easy Review, auto-merge

#11374 fix Issue 20990 - Optimizer should move cold branches to the end of t…
  src/dmd/backend/blockopt.d
  test/compilable/test20990.d
Labels: Enhancement

#10999 Fix: DIP 1021: when len is smaller than escapeByStorage, only use first len fields
  src/dmd/escape.d
  test/compilable/issue20995.d
Labels: Bug Fix, auto-merge

#11378 generalize loop unroller from once to N times
  src/dmd/backend/gloop.d
  test/runnable/test20.d
Labels: auto-merge

#11382 Refactor: Provide an STC alias for the in / out / ref group
  src/dmd/declaration.d
  src/dmd/dmangle.d
  src/dmd/dtemplate.d
  src/dmd/inline.d
  src/dmd/mtype.d
  src/dmd/parse.d
  src/dmd/semantic3.d
  src/dmd/statementsem.d
Labels: Refactoring, Trivial, auto-merge

#11368 Refactor `TemplateInstance` to reduce its size
  src/dmd/dtemplate.d
  src/dmd/hdrgen.d
  src/dmd/template.h
Labels: Bug Fix, auto-merge-squash

#11373 fix issue 20761 - __traits(isSame) for alias tuples is broken and und…
  src/dmd/traits.d
Labels: Bug Fix, auto-merge

#11389 Formating (indentation) backend/dwarfdbginfo.d
  src/dmd/backend/dwarfdbginf.d
Labels: Refactoring, auto-merge

#11383 ArrayScopeSymbol use dyncast() to recognize the array content
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
Labels: auto-merge

#11392 Add tests for issue 20761 - __traits(isSame) for alias tuples...
  test/compilable/traits.d
Labels: auto-merge

#11390 Refactoring backend/dwarfdbginfo.d
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge

#11394 [C++] aggregate.h: Fix regression caused by #11370
  src/dmd/aggregate.h
  src/tests/cxxfrontend.c
Labels: auto-merge

#11395 test: Use asserts instead of printf in test8 va_arg checks
  test/runnable/test8.d
Labels: Easy Review, auto-merge

#11397 build.d: Add rootHeaders as dependencies of cxx-unittest
  src/build.d
Labels: Blocking Other Work, Easy Review, auto-merge

#11398 build.d: Move gluelayer from glue to frontend.
  src/build.d
Labels: Blocking Other Work, Easy Review, auto-merge

#11399 build.d: Move stmtstate from glue to frontend.
  src/build.d
Labels: Blocking Other Work, Easy Review, auto-merge

#11400 merge stable
  VERSION
  changelog/add_traits_isCopyable.dd
  changelog/check_interface_implementations.dd
  changelog/shared-init.dd
  changelog/vtemplates.dd
  src/dmd/cli.d
  src/dmd/expressionsem.d
  src/dmd/mars.d
  src/dmd/typesem.d
  test/compilable/previewall.d
  test/compilable/previewhelp.d
  test/compilable/reverthelp.d
  test/compilable/test20100.d
  test/compilable/test20909.d
  test/compilable/transitionhelp.d
Labels: Bug Fix, auto-merge

#11351 expression.d: Convert AssignExp.memset from int mask to enum (and use enum class)
  src/dmd/dinterpret.d
  src/dmd/e2ir.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
Labels: auto-merge, extern (C/C++)

#11401 build.d: Only link in the frontend sources to the cxx-unittest program
  src/build.d
Labels: Blocking Other Work, Easy Review, auto-merge

#11396 test/runnable: Add missed EXTRA_FILES to xtest46_gc.d
  test/runnable/xtest46_gc.d
Labels: Trivial, auto-merge

#11402 test: Fix function conflicts in test16492.d
  test/compilable/test16492.d
Labels: Easy Review, auto-merge

#11403 test: Add explicit module declaration to imports for issue16995.d
  test/runnable/imports/another_module_with_tests.d
  test/runnable/imports/module_with_tests.d
Labels: Easy Review, auto-merge

#11331 Convert enum BUILTIN to enum class, add gcc and llvm members.
  src/dmd/builtin.d
  src/dmd/declaration.h
  src/dmd/func.d
Labels: GDC, auto-merge

#11405 Remove dead FuncDeclaration.isArrayOp field and all supporting code
  src/dmd/declaration.h
  src/dmd/e2ir.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/glue.d
  src/dmd/inline.d
Labels: Easy Review, auto-merge

#11406 fix Issue 21037 - AVX code sometimes fails to set VEX prefix
  src/dmd/backend/cgxmm.d
Labels: Bug Fix, auto-merge

#11388 recognize byteswap and generate XCHG
  src/dmd/backend/cgelem.d
  src/dmd/backend/cod2.d
  src/dmd/backend/evalu8.d
  test/runnable/mars1.d
Labels: auto-merge

#11407 fix Issue 21040 - SIMD: illegal instruction using 32-byte operations on AVX
  src/dmd/target.d
  test/runnable/test21040.d
Labels: Bug Fix, auto-merge

#11409 optimize 2 word compare with zero
  src/dmd/backend/cgelem.d
Labels: auto-merge

#8804 Rename Compiler.loadModule to onParseModule, move call to Module.parseModule
  src/dmd/compiler.d
  src/dmd/compiler.h
  src/dmd/dmodule.d
Labels: GDC, Refactoring, auto-merge

#11408 add 64 bit bswap() intrinsic
  src/dmd/backend/cod2.d
  src/dmd/toir.d
Labels: auto-merge

#11377 fix issue 12490 - No "Error: , has no effect" Error for comma expression LHS
  src/dmd/expressionsem.d
  src/dmd/sideeffect.d
  test/fail_compilation/misc1.d
Labels: Bug Fix, auto-merge

#11404 test: Synchronize simd tests with gdc testsuite
  test/compilable/b16697.d
  test/compilable/commontype.d
  test/compilable/isZeroInit.d
  test/compilable/test10312.d
  test/compilable/test11371.d
  test/compilable/test11656.d
  test/compilable/test17793.d
  test/compilable/test19224.d
  test/compilable/test8543.d
  test/fail_compilation/vector_types.d
  test/runnable/b18034.d
  test/runnable/bug11155.d
  test/runnable/test17337.d
  test/runnable/test19223.d
  test/runnable/test42.d
  test/runnable/testxmm.d
Labels: Easy Review, auto-merge

#11415 Fix Typo
  src/dmd/backend/outbuf.d
Labels: auto-merge

#11279 Fix #20931 Take CTFE into account for coverage reports
  src/dmd/cli.d
  src/dmd/dinterpret.d
  src/dmd/dmodule.d
  src/dmd/globals.d
  src/dmd/glue.d
  src/dmd/mars.d
  src/dmd/module.h
  test/runnable/ctfe_cov.d
Labels: Enhancement, auto-merge

#11417 Add changelog entry for #11407
  changelog/vector-operation-support.dd
Labels: documentation

#11419 Introduce Parameter.isReference to check ref/out variables
  src/dmd/cppmanglewin.d
  src/dmd/dcast.d
  src/dmd/dinterpret.d
  src/dmd/e2ir.d
  src/dmd/escape.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/mtype.d
  src/dmd/optimize.d
  src/dmd/target.d
  src/dmd/toctype.d
  src/dmd/typesem.d
Labels: Refactoring, auto-merge

#11421 Use errorSupplemental for long read-modify-write error message
  src/dmd/expression.d
  test/fail_compilation/diag3672.d
  test/fail_compilation/diag3672a.d
  test/fail_compilation/fail3672.d
Labels: Easy Review, auto-merge

#11416 recognize 64 bit ROL and ROR
  src/dmd/backend/cgelem.d
  test/runnable/mars1.d
Labels: auto-merge

#11418 toir.setClosureVarOffset: Use early return
  src/dmd/toir.d
Labels: Refactoring, auto-merge

#11420 Refactor a loop with disjoint branches into an 'if' in foreach over array semantic
  src/dmd/statementsem.d
Labels: Refactoring, auto-merge

#11422 Move the implementation of `-preview=in` from parser to semantic
  src/dmd/parse.d
  src/dmd/typesem.d
Labels: Bug Fix, auto-merge

#11424 Backend: Remove unused 'mask/maskl' global from var
  src/dmd/backend/var.d
Labels: Blocking Other Work, Refactoring

#11428 Fixed issue 20422 - confusing error "new can only create structs, dynamic arrays or class objects, not int[]'s"
  src/dmd/expressionsem.d
  test/fail_compilation/issue20422.d
Labels: Bug Fix

#11436 [dmd-cxx] fix Issue 14739, 19024, 21060: ICE in semantic, at d/dmd/dstruct.c:1224
  src/dstruct.c
  test/compilable/ice14739.d
  test/fail_compilation/fail17492.d
  test/fail_compilation/ice21060.d
  test/fail_compilation/imports/ice21060a/package.d
  test/fail_compilation/imports/ice21060b/package.d
  test/fail_compilation/imports/ice21060c/package.d
  test/fail_compilation/imports/ice21060d/package.d
Labels: C++ Port, Easy Review, Enhancement, GDC, auto-merge

#11435 fix Issue 21060 - Another test for ICE in semantic
  test/fail_compilation/ice21060.d
  test/fail_compilation/imports/ice21060a/package.d
  test/fail_compilation/imports/ice21060b/package.d
  test/fail_compilation/imports/ice21060c/package.d
  test/fail_compilation/imports/ice21060d/package.d
Labels: Easy Review, Enhancement

#11439 [dmd-cxx] fix issue 9490 - 'this' is not found when expression is in parentheses
  src/expressionsem.c
  src/parse.c
  test/compilable/b9490.d
Labels: Bug Fix, C++ Port, Easy Review, GDC, auto-merge

#11437 fix Issue 14458 - very slow ubyte[] assignment (dmd doesn't use memset)
  src/dmd/backend/cod2.d
Labels: Bug Fix, auto-merge

#11438 Fix 21063 - getLinkage fails with forward references
  src/dmd/traits.d
  test/compilable/fwdref21063.d
Labels: Bug Fix, auto-merge

#11384 Missing/Incorrect deprecation for templates
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/template.h
  test/compilable/depmsg.d
  test/fail_compilation/depmsg.d
  test/fail_compilation/depmsg15815.d
  test/fail_compilation/deprecatedTemplates.d
  test/fail_compilation/diag14875.d
Labels: auto-merge

#11445 fix Issue 14936 - Dividing by a power of 2 slow on 32bit
  src/dmd/backend/cod2.d
  test/runnable/mars1.d
Labels: Enhancement, auto-merge

#11443 End the deprecation period for implicit base class override
  changelog/implicit-override-deprecation-end-17349.dd
  src/dmd/declaration.h
  src/dmd/dsymbolsem.d
  src/dmd/func.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  test/fail_compilation/fail17354.d
  test/fail_compilation/fix17349.d
Labels: auto-merge

#11444 Improve error message for implicit string concatenation
  src/dmd/parse.d
  test/fail_compilation/diag10805.d
  test/fail_compilation/fail196.d
  test/fail_compilation/issue3827.d
Labels: Diagnostic Messages, auto-merge

#11447 Fix qsort delegate prototype for compilation with ldc 1.8.0
  src/dmd/glue.d
Labels: auto-merge

#11446 Modulus by a power of 2 slow on 32 bit
  src/dmd/backend/cod2.d
  test/runnable/mars1.d
Labels: auto-merge

#11449 fix Issue 19663 - On x86_64 the fabs intrinsic should use SSE
  src/dmd/backend/cgxmm.d
  src/dmd/backend/cod2.d
  src/dmd/backend/code.d
Labels: Enhancement

#11448 split off cddiv() from cdmul()
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod2.d
  src/dmd/backend/code.d
Labels: Easy Review, Refactoring, auto-merge

#11452 std.math.fabs(float) and fabs(double) are now intrinsics
  src/dmd/toir.d
Labels: Blocking Other Work, Easy Review, auto-merge

#11451 remove divide from cdmul() and multiply from cddiv()
  src/dmd/backend/cod2.d
Labels: Refactoring

#11453 prevent repeated virtual call in TypeQualifier.syntaxCopyHelper
  src/dmd/mtype.d
Labels: auto-merge

#11454 test: Make sdtor/S17457 a non-POD type, @disable copying.
  test/runnable/sdtor.d
Labels: Easy Review, auto-merge

#11455 make cddivass a copy of cdmulass
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod4.d
  src/dmd/backend/code.d
Labels: Easy Review, Refactoring

#11457 remove multiplies from cddivass()
  src/dmd/backend/cod4.d
Labels: Easy Review, Refactoring, auto-merge

#11425 DScanner: Enable number_style_check compiler-wide
  src/.dscanner.ini
  src/dmd/astbase.d
  src/dmd/backend/aarray.d
  src/dmd/backend/cc.d
  src/dmd/backend/cgcs.d
  src/dmd/backend/cgobj.d
  src/dmd/backend/dcgcv.d
  src/dmd/backend/divcoeff.d
  src/dmd/backend/dwarfeh.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/gloop.d
  src/dmd/backend/mscoffobj.d
  src/dmd/backend/out.d
  src/dmd/globals.d
  src/dmd/libelf.d
  src/dmd/libmach.d
  src/dmd/libomf.d
  src/dmd/mars.d
  src/dmd/mtype.d
  src/dmd/root/longdouble.d
Labels: auto-merge

#11458 Fix Issue 21074 - const lost in mixin
  src/dmd/typesem.d
  test/compilable/mixintype2.d
Labels: Bug Fix, auto-merge

#11460 cdmul(): more flexibility with register usage
  src/dmd/backend/cod2.d
Labels: auto-merge

#11456 remove divides from cdmulass()
  src/dmd/backend/cod4.d
Labels: Easy Review, Refactoring

#11462 Fix Issue 21074 - const lost in mixin (extra case)
  src/dmd/typesem.d
  test/compilable/mixintype2.d
Labels: Bug Fix, auto-merge

#11432 Fix Issue 21058 - __traits(getOverloads) forgets "this" with third ar…
  src/dmd/traits.d
  test/compilable/test21058.d
Labels: Bug Fix, auto-merge-squash

#11464 addInvariant: Remove unused loc and sc parameters
  src/dmd/func.d
  src/dmd/semantic3.d
Labels: Easy Review, Refactoring, auto-merge

#11466 cdmulass(): add LEA for multiply by constant
  src/dmd/backend/cod4.d
  test/runnable/mars1.d
Labels: auto-merge

#11467 Use statically allocated ErrorExp instance
  src/dmd/arrayop.d
  src/dmd/attrib.d
  src/dmd/cond.d
  src/dmd/dcast.d
  src/dmd/declaration.d
  src/dmd/delegatize.d
  src/dmd/denum.d
  src/dmd/dinterpret.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/iasmgcc.d
  src/dmd/initsem.d
  src/dmd/inline.d
  src/dmd/mtype.d
  src/dmd/nogc.d
  src/dmd/opover.d
  src/dmd/optimize.d
  src/dmd/statementsem.d
  src/dmd/traits.d
  src/dmd/typesem.d
Labels: Refactoring, auto-merge

#11468 refactor cdmul() for clarity
  src/dmd/backend/cod2.d
Labels: Easy Review, Refactoring, auto-merge

#11470 cddiv(): refactor for clarity
  src/dmd/backend/cod2.d
Labels: Easy Review, Refactoring, auto-merge

#11469 [critical bugfix] Increase size for temporary HID identifier
  src/dmd/glue.d
Labels: Bug Fix, auto-merge

#11471 cddivass(): refactor for clarity
  src/dmd/backend/cod4.d
Labels: Easy Review, Refactoring, auto-merge

#11473 test: Add ICE testcase for issue 16657
  test/fail_compilation/ice16657.d
Labels: Easy Review, auto-merge

#11472 TypeFunction semantic: Remove STC.scope_ after processing Ttuple
  src/dmd/typesem.d
Labels: Refactoring, auto-merge

#11431 Fix Issue 21050 - __traits(getOverloads) for templates returns incorr…
  src/dmd/traits.d
  test/compilable/test21050.d
Labels: Bug Fix, auto-merge

#11461 pack `TypeFunction` flags in a bit set to reduce memory use
  src/dmd/astbase.d
  src/dmd/clone.d
  src/dmd/dmangle.d
  src/dmd/dsymbolsem.d
  src/dmd/escape.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/semantic3.d
  src/dmd/typesem.d
  src/tests/cxxfrontend.c
Labels: Refactoring, auto-merge

#11478 cddivass(): signed divide by constant
  src/dmd/backend/cod4.d
  test/runnable/mars1.d
Labels: auto-merge

#7065 fix Issue 17720 - Wrong code using vector extensions with different types
  changelog/implicit-vector-conversions.dd
  src/dmd/dcast.d
  src/dmd/mtype.d
  test/runnable/testxmm.d
Labels: 72h no objection -> merge, Bug Fix, GDC, auto-merge

#11480 Fix 19210: Poor error message for `return` function parameter that is not `ref`
  src/dmd/escape.d
  test/fail_compilation/dip25.d
  test/fail_compilation/fail13902.d
  test/fail_compilation/fail20084.d
  test/fail_compilation/fail20448.d
  test/fail_compilation/fix18575.d
  test/fail_compilation/test16589.d
  test/fail_compilation/test17450.d
Labels: Bug Fix, Diagnostic Messages, auto-merge

#11475 cdmul(): require one less register for LEA generated code
  src/dmd/backend/cod2.d
Labels: auto-merge

#11482 Reduce code duplication in Objective-C symbol cache
  src/dmd/objc_glue.d
Labels: Refactoring

#11477 Fix Issue 15103 - Improve declaration / initialization syntax error message
  src/dmd/parse.d
  test/fail_compilation/issue15103.d
Labels: Bug Fix, auto-merge
