Repository dlang/dmd, pull requests merged in 2020-08, with the labels that each got.

#11481 fix Issue 21095 - [ICE] AssertError@dmd/expressionsem.d(5015): Assertion failure
  src/dmd/expressionsem.d
  test/fail_compilation/ice21095.d
Labels: Bug Fix, auto-merge

#11442 Fix Issue 12223 - __traits(getMember,...) needed for aliases
  changelog/add_traits_child.dd
  src/dmd/id.d
  src/dmd/traits.d
  src/dmd/typesem.d
  test/fail_compilation/traits_child.d
  test/runnable/traits_child.d
Labels: auto-merge-squash

#11479 cddivass(): unsigned divide by constant
  src/dmd/backend/cod4.d
  test/runnable/mars1.d
Labels: 72h no objection -> merge

#11483 special code for signed divide by 2
  src/dmd/backend/cod4.d
Labels: auto-merge

#11484 add allocScratchReg()
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod4.d
  src/dmd/backend/code.d
Labels: Easy Review, Refactoring, auto-merge

#11486 cod2.d: make use of allocScratchReg()
  src/dmd/backend/cod2.d
Labels: Easy Review, Refactoring, auto-merge

#11485 cddivass(): register pair signed divide by power of 2
  src/dmd/backend/cod4.d
Labels: auto-merge

#11488 improve documentation and types for asm_make_modrm_byte()
  src/dmd/iasmdmd.d
Labels: Easy Review, Refactoring, auto-merge, documentation

#11489 fix Issue 6459 - Inline asm bugs with 64 bit registers R8..R15
  src/dmd/iasmdmd.d
  test/runnable/iasm64.d
Labels: Bug Fix, auto-merge

#11487 cddivass(): register pair signed modulo by power of 2
  src/dmd/backend/cod4.d
Labels: auto-merge

#11491 cod4.d: pull common code into opAssStorePair()
  src/dmd/backend/cod4.d
Labels: Easy Review, Refactoring, auto-merge

#11492 cod4.d: pull common code into opAssStoreReg()
  src/dmd/backend/cod4.d
Labels: Easy Review, Refactoring, auto-merge

#11494 Minor enhancements and reactor of Identifier
  src/dmd/identifier.d
Labels: Refactoring, auto-merge

#11493 cod4.d: make more use of opAssStoreReg()
  src/dmd/backend/cod4.d
Labels: Refactoring, auto-merge

#11497 Fix issue 21089: spawn linker with vfork to avoid need to overcommit memory
  src/dmd/link.d
Labels: Bug Fix, auto-merge

#11496 cod4.d: use opAssLoadPair() more
  src/dmd/backend/cod4.d
Labels: Refactoring, auto-merge

#11495 pull out opAssLoadPair() into separate function
  src/dmd/backend/cod4.d
Labels: Refactoring, auto-merge

#11498 cod4.d: use opAssLoadPair() even more
  src/dmd/backend/cod4.d
Labels: Refactoring, auto-merge

#11499 cod4.d: add opAssLoadReg()
  src/dmd/backend/cod4.d
Labels: Refactoring, auto-merge

#11501 Add missing STC.IOR / Type.isTypeXXX declarations to ASTBase
  src/dmd/astbase.d
Labels: Continuous Integration, auto-merge

#11503 Fix Issue 21091 - [ICE] Segmentation fault: Module::importAll(Scope*)…
  src/dmd/dmodule.d
  src/dmd/mars.d
  test/fail_compilation/fail21091a.d
  test/fail_compilation/fail21091b.d
Labels: Bug Fix, auto-merge

#11500 Fix Issue 21092 -[ICE] Segmentation fault in ExpressionPrettyPrintVis…
  src/dmd/hdrgen.d
  test/fail_compilation/fail21092.d
Labels: Bug Fix, auto-merge

#11505 Fix the mangling of 'in' to not include 'const'
  src/dmd/dmangle.d
  test/fail_compilation/diagin.d
Labels: auto-merge

#11502 Fix Issue 21096 - [ICE] Segmentation fault in dmd.hdrgen.sizeToBuffer at dmd/hdrgen.d:3153
  src/dmd/parse.d
  test/fail_compilation/test21096.d
Labels: Bug Fix, auto-merge

#11513 Fix Issue 20911 - Documentation for test/unit is non-existant
  test/unit/compilable/crlf.d
  test/unit/deinitialization.d
  test/unit/frontend.d
  test/unit/interfaces/check_implementations_20861.d
  test/unit/lexer/diagnostic_reporter.d
  test/unit/parser/diagnostic_reporter.d
  test/unit/self_test.d
  test/unit/support.d
Labels: Bug Fix, auto-merge

#11514 Fix Issue 21117 - When compiler segfaults running autotester, cannot …
  test/run.d
Labels: Bug Fix, auto-merge

#11512 Improve output for failed `unit` tests.
  test/tools/unit_test_runner.d
Labels: auto-merge

#11521 Fix 1995: Provide more informative error message for import(exp)
  src/dmd/expressionsem.d
  test/fail_compilation/fail1995.d
Labels: Easy Review, Enhancement, auto-merge

#11520 fix issue 21082: Testsuite fails on macOS with assertions enabled
  src/dmd/glue.d
  src/dmd/objc_glue.d
Labels: Bug Fix, auto-merge

#11526 testcgelem.d: add coverage tests for cgelem.d
  src/dmd/backend/cgelem.d
  test/runnable/testcgelem.d
Labels: auto-merge

#11527 Fix Issue 21122 - __traits(getAttributes) wrong scope on enums
  src/dmd/attrib.d
  src/dmd/dsymbolsem.d
  src/dmd/parse.d
  src/dmd/traits.d
  test/compilable/test20835.d
Labels: Bug Fix, auto-merge

#11535 small changes to prolog_frame() to improve clarity
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code.d
  src/dmd/backend/code_x86.d
Labels: Easy Review, Refactoring, auto-merge, documentation

#11536 add out parameters to prolog_frame()
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code.d
Labels: Easy Review, Refactoring, auto-merge

#11529 fix Issue 20162 - Sign Extension for ?: optimization done wrong
  src/dmd/backend/cod2.d
  src/dmd/backend/cod4.d
  test/runnable/mars1.d
Labels: Bug Fix, auto-merge

#11537 Github Actions: Drop testing for LLVM < v6.0.0
  .github/workflows/runnable_cxx.yml
Labels: auto-merge

#11534 build.d: Change working directory to the project root
  .circleci/run.sh
  src/build.d
  src/dmd/mars.d
Labels: auto-merge

#11525 mars1.d: consolidate divide tests together
  test/runnable/mars1.d
Labels: Easy Review, Refactoring, auto-merge

#11541 fix Issue 10966 - Optimizer generates wrong code with try-catch
  src/dmd/backend/gflow.d
  test/runnable/eh.d
Labels: Bug Fix, auto-merge

#11544 Small refactoring and fixes to `dinterpret.d`
  src/dmd/dinterpret.d
  test/compilable/interpret3.d
Labels: Refactoring, auto-merge

#11542 merge stable
  VERSION
  src/dmd/attrib.d
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  src/dmd/glue.d
  src/dmd/parse.d
  src/dmd/traits.d
  src/dmd/typesem.d
  test/compilable/fwdref21063.d
  test/compilable/mixintype2.d
  test/compilable/test20835.d
  test/fail_compilation/ice21095.d
  test/fail_compilation/test21096.d
Labels: Bug Fix, auto-merge

#11543 fix Issue 12730 - lea instruction accepts subtraction of scaling regi…
  src/dmd/iasmdmd.d
  test/fail_compilation/fail12730a.d
  test/fail_compilation/fail12730b.d
Labels: Bug Fix, auto-merge

#11549 fix Issue 14120 - iasm is missing pause instruction
  src/dmd/backend/cod3.d
  src/dmd/backend/code_x86.d
  src/dmd/backend/ptrntab.d
  src/dmd/iasmdmd.d
  test/runnable/iasm.d
Labels: Enhancement, auto-merge

#11546 Revert reinterpret cast introduced in #432, add ICE test case for 32-bit targets
  src/dmd/dinterpret.d
  test/compilable/interpret3.d
  test/fail_compilation/reg6769.d
Labels: Bug Fix, auto-merge

#11548 [stable] Cherry-pick #11500
  src/dmd/hdrgen.d
  test/fail_compilation/fail21092.d
Labels: Bug Fix, auto-merge

#11554 Optimize backend 'OmfObj_bytes' function
  src/dmd/backend/cgobj.d
Labels: auto-merge

#11550 fix Issue 16400 - naked variadic C function emits broken prologue
  src/dmd/backend/cgelem.d
  test/runnable/iasm.d
Labels: Bug Fix, auto-merge

#11556 iasm: make OpndSize its own type
  src/dmd/backend/iasm.d
  src/dmd/iasmdmd.d
Labels: Easy Review, Refactoring

#11552 set d1-style opover deprecation time to 10 rlz, as per dip 1013
  src/dmd/opover.d
Labels: Easy Review, auto-merge

#11559 Improve static function frame access error message and coverage
  src/dmd/declaration.d
  src/dmd/func.d
  test/fail_compilation/diag10984.d
  test/fail_compilation/diag15411.d
  test/fail_compilation/diag9148.d
  test/fail_compilation/diag9831.d
  test/fail_compilation/fail39.d
Labels: Diagnostic Messages, Easy Review, auto-merge

#11558 Minor cleanup to TypeFunction semantic and related
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/typesem.d
Labels: Refactoring, Trivial

#11545 Fix 17351 - Manifest constants can't sometimes be passed by `ref` in CTFE
  src/dmd/dinterpret.d
  test/compilable/test17351.d
Labels: Bug Fix

#11561 Fix STC of parameters to some druntime hooks
  src/dmd/statementsem.d
  src/dmd/typesem.d
Labels: Easy Review, auto-merge

#11562 Trivial: Correct some version-out logging statements
  src/dmd/dcast.d
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/toctype.d
  src/dmd/typesem.d
Labels: Easy Review, Trivial, auto-merge

#11566 [refactor] Remove explicit casts in new IntegerExp
  src/dmd/parse.d
  src/dmd/target.d
Labels: Easy Review, Refactoring, auto-merge

#11567 Fix duplicate function declarations in dmd/tests
  src/dmd/backend/go.d
  test/runnable/extra-files/cdvecfill.d
  test/runnable/extra-files/cdvecfillavx.out
  test/runnable/extra-files/cdvecfillavx2.out
Labels: Trivial, auto-merge

#11565 [refactor] constfold: Use >>> for evaluating Ushr expressions
  src/dmd/constfold.d
Labels: Easy Review, Refactoring, auto-merge

#11557 finish encapsulating bit masking of OpndSize
  src/dmd/backend/iasm.d
  src/dmd/backend/ptrntab.d
  src/dmd/iasmdmd.d
Labels: Easy Review, Refactoring, auto-merge

#11528 fix Issue 21038 - wchar and dchar string alignment should be 2 and 4,…
  src/dmd/backend/cc.d
  src/dmd/backend/dt.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/out.d
  src/dmd/todt.d
  test/runnable/mars1.d
Labels: Bug Fix, auto-merge

#11564 TypeFunction: Process default parameter only after all parameter semantic has been done
  src/dmd/dmangle.d
  src/dmd/mtype.d
  src/dmd/typesem.d
Labels: Refactoring, auto-merge

#11504 cod4.d: make more use of opAssLoadReg()
  src/dmd/backend/cod4.d
Labels: Refactoring, auto-merge

#11569 Improve diagnostic messages for redundant storage classes
  src/dmd/parse.d
  test/fail_compilation/fail183.d
Labels: Diagnostic Messages

#11506 cod4.d: make even more use of opAssLoadReg()
  src/dmd/backend/cod4.d
Labels: Refactoring, auto-merge

#11576 Merge stable into master
  VERSION
  src/dmd/backend/cgelem.d
  src/dmd/dinterpret.d
  test/compilable/test17351.d
  test/runnable/iasm.d
Labels: Bug Fix, auto-merge

#11519 Make -lowmem optional and prefer building d_do_test with the host compiler
  test/Makefile
  test/run.d
  test/tools/d_do_test.d
  test/tools/sanitize_json.d
Labels: Bug Fix, auto-merge

#11580 Add bootstrapping wrapper: src/bootstrap.sh
  src/bootstrap.sh
  src/posix.mak
Labels: Build System, auto-merge

#11583 Mangle C++ function parameter pack (POSIX)
  src/dmd/cppmangle.d
  test/runnable_cxx/externmangle.d
  test/runnable_cxx/extra-files/externmangle.cpp
Labels: Blocking Other Work, auto-merge, stable-priority

#11584 fix Issue 14697 add PCLMULQDQ instruction to inline assembler
  src/dmd/backend/ptrntab.d
  test/runnable/iasm64.d
Labels: Enhancement, auto-merge

#11578 fix issue 21163 - scope lambda argument in struct init does not parse
  src/dmd/parse.d
  test/compilable/compile1.d
Labels: Bug Fix, Regression, auto-merge, stable-priority

#11507 Enhance the implementation of anonymous identifiers
  src/dmd/aggregate.h
  src/dmd/dclass.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/identifier.d
  src/dmd/identifier.h
  src/dmd/objc.d
  src/dmd/statementsem.d
Labels: auto-merge

#11588 Separate objc data from the rest of `FuncDeclaration`
  src/dmd/declaration.h
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/glue.d
  src/dmd/objc.d
  src/dmd/objc.h
  src/dmd/objc_glue.d
  src/dmd/typesem.d
Labels: Refactoring, auto-merge

#11582 Fix Issue 20296 - Segfault when using variadic D functions with exter…
  src/dmd/cppmangle.d
  test/compilable/test20296.d
  test/runnable_cxx/externmangle.d
  test/runnable_cxx/extra-files/externmangle.cpp
Labels: Blocked, Bug Fix, stable-priority

#11590 fix Issue 16963 - Forward reference label name resolution in asm stat…
  src/dmd/statementsem.d
  test/runnable/iasm.d
Labels: Bug Fix

#11589 Fix Issue 16857 - inline assembler reverses operands of VPEXTRW instruction
  src/dmd/iasmdmd.d
  test/runnable/iasm64.d
Labels: Bug Fix

#11573 optimize instance size of SymbolExp and VarExp
  src/dmd/expression.d
  src/dmd/expression.h
Labels: Easy Review

#11515 Use .NOTPARALLEL in posix.mak instead of lockfiles in build.d
  posix.mak
  src/posix.mak
Labels: auto-merge

#11594 fix crash on semaphoreCI caused by unaligned bitops in TypeFunction
  src/dmd/astbase.d
  src/dmd/mtype.d
  src/dmd/mtype.h
Labels: Blocking Other Work, Bug Fix, Continuous Integration, Easy Review, Regression, auto-merge

#11570 fix Issue 12832 - asm movdqu accepts wrong operand size
  src/dmd/backend/iasm.d
  src/dmd/backend/ptrntab.d
  src/dmd/iasmdmd.d
  test/runnable/iasm.d
  test/runnable/iasm64.d
Labels: Bug Fix, auto-merge

#11540 Fix issue 21153 - DWARF: DMD emits the mangled name for DW_AT_name
  src/dmd/backend/dwarfdbginf.d
  test/dshell/dwarf.d
  test/dshell/extra-files/dwarf/excepted_results/fix21153.txt
  test/dshell/extra-files/dwarf/fix21153.d
Labels: Bug Fix, auto-merge

#11532 Use a more specialized type for the Objective-C method list
  src/dmd/dsymbol.d
  src/dmd/objc.d
  src/dmd/objc_glue.d
  src/dmd/root/array.d
Labels: auto-merge

#11597 fix Issue 15257 - __traits(compiles, .) with malformed inline asm sil…
  src/dmd/iasmdmd.d
  test/fail_compilation/fail152.d
  test/fail_compilation/fail3354.d
Labels: Bug Fix

#11601 fix Issue 21181 - Inline Assembler compiles long ptr as a byte operati…
  src/dmd/iasmdmd.d
  test/fail_compilation/failasm.d
Labels: Bug Fix, auto-merge

#11611 Fix Issue 19476 - explicit mixin template function call results in re…
  src/dmd/expressionsem.d
  test/runnable/test19476.d
Labels: Bug Fix

#11612 iasm.d: refactor tryExpressionToOperand() to clarify its behavior
  src/dmd/iasmdmd.d
Labels: Easy Review, Refactoring, auto-merge

#11608 fix Issue 15745 - Inline Assembly stomped on by Profiling
  src/dmd/glue.d
  test/runnable/testprofile.d
Labels: Bug Fix, auto-merge

#11000 Make `-preview=in` means `[ref] const scope` and accept rvalues
  changelog/preview-in.dd
  src/dmd/cli.d
  src/dmd/expressionsem.d
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/hdrgen.d
  src/dmd/mtype.d
  src/dmd/parse.d
  src/dmd/target.d
  src/dmd/target.h
  src/dmd/typesem.d
  test/compilable/previewhelp.d
  test/compilable/previewin.d
  test/fail_compilation/diagin.d
  test/fail_compilation/diaginref.d
  test/fail_compilation/previewin.d
  test/runnable/previewin.d
Labels: Enhancement, auto-merge

#11603 fix Issue 2617 - asm silently accepts ambiguous-sized operations
  src/dmd/iasmdmd.d
  test/fail_compilation/failasm.d
  test/fail_compilation/failasm2.d
  test/runnable/iasm.d
  test/runnable/iasm64.d
Labels: Bug Fix, auto-merge

#11614 iasm1.d: consolidate some test files
  test/fail_compilation/fail15999.d
  test/fail_compilation/fail15999b.d
  test/fail_compilation/fail274.d
  test/fail_compilation/goto4.d
  test/fail_compilation/goto5.d
  test/fail_compilation/iasm1.d
  test/fail_compilation/ice15239.d
  test/fail_compilation/test12979.d
Labels: Easy Review, Refactoring, auto-merge

#11617 Use module source name if searchPath returns null
  src/dmd/dsymbolsem.d
Labels: Bug Fix, Easy Review, GDC, auto-merge

#11619 fix issue 16044 - __traits(allMembers) returns empty tuple for subpackages
  src/dmd/traits.d
  test/compilable/imports/pkg16044/package.d
  test/compilable/imports/pkg16044/sub/package.d
  test/compilable/issue16044.d
Labels: Bug Fix, auto-merge

#11620 [dmd-cxx] Use module source name if searchPath returns null
  src/func.c
Labels: C++ Port, GDC, auto-merge

#11621 [dmd-cxx] Fix Issue 20092 and Issue 20356 - recursive expansion/optimization fixes
  src/dmacro.c
  src/dtemplate.c
  src/expressionsem.c
  src/globals.h
  src/mtype.c
  src/optimize.c
  test/compilable/ice20092.d
Labels: C++ Port, GDC, auto-merge

#11622 [dmd-cxx] Move check for NRVO from ReturnStatement semantic into FuncDeclaration
  src/declaration.h
  src/func.c
  src/statementsem.c
Labels: C++ Port, GDC, auto-merge

#11607 fix Issue 16092 - AVX registers YMM0-YMM7 are inaccessible to 32-bit asm
  src/dmd/iasmdmd.d
  test/runnable/iasm.d
Labels: Bug Fix, auto-merge

#11623 [dmd-cxx] Remove redundant contract checking
  src/func.c
  src/statementsem.c
Labels: C++ Port, GDC, auto-merge

#11625 [dmd-cxx] Backport some miscellaneous test fixes.
  test/runnable/sdtor.d
  test/runnable/test8.d
Labels: C++ Port, GDC, auto-merge

#11615 Generalize `isUdaSelector` to handle any attribute
  src/dmd/objc.d
Labels: Easy Review, Refactoring, auto-merge

#11626 semantic3: Remove nrvo_can test done before body semantic
  src/dmd/semantic3.d
Labels: auto-merge

#11628 [dmd-cxx] semantic3: Remove nrvo_can test done before body semantic
  src/func.c
Labels: C++ Port, Easy Review, GDC, auto-merge

#11616 Fix Issue 21159 - DWARF: DW_AT_pure should be emitted for pure functions
  src/dmd/backend/dwarfdbginf.d
  test/dshell/dwarf.d
  test/dshell/extra-files/dwarf/excepted_results/fix21159.txt
  test/dshell/extra-files/dwarf/fix21159.d
Labels: Enhancement, auto-merge

#11629 Fix 21196 - Deprecation for DIP25 triggered in deprecated block
  src/dmd/escape.d
  test/compilable/bug21196.d
Labels: Bug Fix

#11618 Improve documentation for the test suite
  test/README.md
  test/compilable/README.md
  test/dshell/README.md
  test/fail_compilation/README.md
  test/runnable/README.md
  test/runnable_cxx/README.md
  test/tools/README.md
  test/unit/README.md
Labels: auto-merge

#11631 fix Issue 14872 - [2.068.2] Label address in asm [x86-64]
  src/dmd/backend/elfobj.d
  src/dmd/iasmdmd.d
  test/runnable/iasm64.d
Labels: Bug Fix, auto-merge

#11624 fix Issue 7387 - call instruction does not understand $
  src/dmd/iasmdmd.d
  test/runnable/iasm.d
  test/runnable/iasm64.d
Labels: Bug Fix, auto-merge

#11636 fix Issue 6166 - Named return value optimization not dealt with in in…
  src/dmd/iasmdmd.d
  test/runnable/iasm64.d
Labels: Bug Fix, auto-merge

#11523 Add build option ENABLE_ASSERTS and use it for CI
  .azure-pipelines/windows-msbuild.bat
  .azure-pipelines/windows.sh
  posix.mak
  src/build.d
  src/posix.mak
  src/vcbuild/dmd.sln
  src/vcbuild/dmd.vcxproj
  src/win32.mak
  src/win64.mak
Labels: Build System, Continuous Integration, auto-merge

#11568 Fix issue 21154 - DWARF: shared types are not represented
  src/dmd/backend/dwarfdbginf.d
  test/dshell/extra-files/dwarf/excepted_results/fix21154.txt
  test/dshell/extra-files/dwarf/fix21154.d
Labels: Bug Fix, auto-merge

#11637 fix Issue 18373 - The inline assembler parser allows strange constructs
  src/dmd/iasmdmd.d
  test/fail_compilation/iasm1.d
Labels: Bug Fix, auto-merge

#11596 Properly fix TypeFunction.funcFlags alignment issue
  src/dmd/astbase.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/tests/cxxfrontend.c
Labels: auto-merge

#11606 fix Issue 17617 - No RIP relative addressing available in x64 inline …
  src/dmd/iasmdmd.d
  test/fail_compilation/iasm1.d
  test/runnable/iasm64.d
Labels: Bug Fix, auto-merge

#11644 don't use opsize prefix for MOV immediate instructions
  src/dmd/backend/cod3.d
Labels: auto-merge

#11645 Fix Issue 21120 - Inconsistent mangling of __init symbol
  src/dmd/dmangle.d
  test/runnable/test21120.d
Labels: Bug Fix, auto-merge

#11634 Fix issue 21198 - Inout copy constructor on union field does not prev…
  src/dmd/dsymbolsem.d
  test/fail_compilation/test21198.d
Labels: Bug Fix, auto-merge

#11649 add MOVSXb, MOVSXw, MOVZXb, MOVZXw
  src/dmd/backend/cod1.d
  src/dmd/backend/cod2.d
  src/dmd/backend/cod3.d
  src/dmd/backend/cod4.d
  src/dmd/backend/code_x86.d
  src/dmd/backend/ptrntab.d
Labels: Easy Review, Refactoring, auto-merge

#11648 avoid using byte constant loads
  src/dmd/backend/cod3.d
Labels: auto-merge

#11642 Fix Issue 21208 - C/C++ header generation for {string,enum} enums
  src/dmd/astcodegen.d
  src/dmd/dtoh.d
  test/compilable/dtoh_enum.d
Labels: Bug Fix, auto-merge

#11655 Print overview of failed targets
  test/run.d
Labels: Continuous Integration, Easy Review, auto-merge

#11647 d_do_test: Add missing DDOC comments
  test/tools/d_do_test.d
Labels: auto-merge, documentation

#10200 Posix x64 ABI fixes 2
  src/dmd/argtypes_sysv_x64.d
  src/dmd/backend/cg87.d
  src/dmd/backend/cgelem.d
  src/dmd/backend/cod1.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code.d
  src/dmd/backend/ty.d
  src/dmd/e2ir.d
  src/dmd/target.d
  test/runnable/testabi.d
  test/runnable/testargtypes.d
Labels: Bug Fix

#11627 fix issue 19590 - `__traits allMembers` should put fully qualified names for imports
  changelog/allMembers_import.dd
  src/dmd/traits.d
  test/compilable/issue19590.d
Labels: 72h no objection -> merge, Bug Fix, auto-merge

#11661 Correct name of param baseType in TypeVector.this(Type) to elide self…
  src/dmd/astbase.d
Labels: Trivial, auto-merge
