Repository dlang/dmd, pull requests merged in 2020-01, with the labels that each got.

#10690 test: Update generic tests that use x86 asm to work across all compilers
  test/runnable/imports/template13478a.d
  test/runnable/minimal2.d
Labels: Easy Review, auto-merge

#10707 update $(YEAR) test to 2020
  test/compilable/extra-files/ddocYear.html
Labels: auto-merge

#10706 fix Issue 20475 - Struct of static array of strings is bitwise-compar…
  src/dmd/clone.d
  test/runnable/opover.d
Labels: Bug Fix, auto-merge

#10708 update $(YEAR) test to 2020 - in master too
  test/compilable/extra-files/ddocYear.html
Labels: auto-merge

#10704 Fix Issue 20474 - Deprecation warnings inside deprecated function template
  src/dmd/dtemplate.d
  test/fail_compilation/deprecations.d
Labels: Bug Fix

#10712 build.d: Improve dscanner target & bump version to 0.7.2
  src/build.d
Labels: Build System, auto-merge

#10718 Fix issue 20488: opDispatch: copy call expression before checking for semantically valid parameters
  src/dmd/expressionsem.d
  test/compilable/test20488.d
Labels: Bug Fix

#10721 fix Issue 20391 - [REG 2.089] DMD compile times increased by 40% beca…
  src/win32.mak
Labels: Bug Fix

#10717 revert #9799 Deprecate scope as a type constraint on class declarations
  src/dmd/dsymbolsem.d
  test/compilable/test7172.d
  test/fail_compilation/scope_class.d
  test/fail_compilation/scope_type.d
  test/fail_compilation/typeerrors.d
Labels: Blocking Other Work, Regression

#10716 Revert "Fix Issue 18665 - Deprecate Undocumented Operator Overloads"
  src/dmd/opover.d
  test/fail_compilation/dep_d1_ops.d
  test/runnable/hospital.d
  test/runnable/interpret.d
  test/runnable/template4.d
  test/runnable/test15.d
  test/runnable/test20.d
  test/runnable/test4.d
  test/runnable/testdstress.d
  test/runnable/xtest46.d
Labels: Blocking Other Work, Regression, auto-merge

#10725 Give D2-style operator overload priority over D1-style, reinstate the latter's deprecation
  changelog/d1-operator-deprecation.dd
  src/dmd/opover.d
  test/fail_compilation/dep_d1_ops.d
  test/runnable/hospital.d
  test/runnable/interpret.d
  test/runnable/template4.d
  test/runnable/test15.d
  test/runnable/test20.d
  test/runnable/test4.d
  test/runnable/testdstress.d
  test/runnable/xtest46.d
Labels: Enhancement, auto-merge

#10720 Move toDString, iequals, toCStringThen from dmd.utils to dmd.root.string
  src/dmd/astbase.d
  src/dmd/cond.d
  src/dmd/dinifile.d
  src/dmd/dmangle.d
  src/dmd/dmodule.d
  src/dmd/doc.d
  src/dmd/dsymbol.d
  src/dmd/env.d
  src/dmd/errors.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/globals.d
  src/dmd/glue.d
  src/dmd/hdrgen.d
  src/dmd/identifier.d
  src/dmd/imphint.d
  src/dmd/json.d
  src/dmd/lexer.d
  src/dmd/lib.d
  src/dmd/libelf.d
  src/dmd/libmach.d
  src/dmd/libmscoff.d
  src/dmd/libomf.d
  src/dmd/link.d
  src/dmd/mars.d
  src/dmd/parse.d
  src/dmd/root/file.d
  src/dmd/root/filename.d
  src/dmd/root/outbuffer.d
  src/dmd/root/response.d
  src/dmd/root/string.d
  src/dmd/scanmscoff.d
  src/dmd/scanomf.d
  src/dmd/semantic2.d
  src/dmd/semantic3.d
  src/dmd/statementsem.d
  src/dmd/staticcond.d
  src/dmd/target.d
  src/dmd/traits.d
  src/dmd/typesem.d
  src/dmd/utils.d
Labels: auto-merge

#10726 Fix Issue 20507 - Debug statements affect inference...
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/typesem.d
  test/compilable/debugInference.d
Labels: Bug Fix, auto-merge

#10728 add STCFlowThru constants
  src/dmd/aggregate.d
  src/dmd/declaration.d
  src/dmd/semantic3.d
Labels: Easy Review, Refactoring, auto-merge

#10729 Fix issue 19542: Forward reference segfault with string namespace C++ syntax
  src/dmd/dsymbolsem.d
  test/compilable/cppmangle.d
Labels: Bug Fix, auto-merge

#10731 Build build.d with symbols
  src/posix.mak
  src/win32.mak
Labels: auto-merge

#10730 errors.d: move "(spec:%d) " printing (-verrors=spec) to verrorPrint()
  src/dmd/errors.d
Labels: auto-merge

#10586 add ob.d and @live prototype implementation of Ownership/Borrowing
  changelog/ob.md
  src/build.d
  src/dmd/astbase.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/escape.d
  src/dmd/foreachvar.d
  src/dmd/id.d
  src/dmd/mtype.d
  src/dmd/ob.d
  src/dmd/parse.d
  src/dmd/semantic3.d
  test/compilable/ob1.d
  test/fail_compilation/fob1.d
  test/fail_compilation/fob2.d
Labels: Enhancement

#10727 Remove class deallocator following deprecation
  changelog/deallocator.dd
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/astbase.d
  src/dmd/canthrow.d
  src/dmd/declaration.h
  src/dmd/dinterpret.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/hdrgen.d
  src/dmd/nogc.d
  src/dmd/parse.d
  src/dmd/parsetimevisitor.d
  src/dmd/strictvisitor.d
  src/dmd/toobj.d
  src/dmd/transitivevisitor.d
  src/dmd/visitor.h
  test/fail_compilation/diag_class_alloc.d
Labels: auto-merge

#10724 Fix Issue 17441 - Template instantiation reused when arguments are mo…
  src/dmd/dmodule.d
  src/dmd/module.h
  test/compilable/imports/test17441foo/bar.d
  test/compilable/imports/test17441foo/package.d
  test/compilable/test17441.d
Labels: Bug Fix, auto-merge-squash

#10736 Fix Issue 20518 - simple import ICE regression
  src/dmd/dimport.d
  test/fail_compilation/diag20518.d
  test/fail_compilation/imports/diag20518a.d
  test/fail_compilation/imports/diag20518a/b.d
Labels: Bug Fix, auto-merge

#10735 Owner pointers needn't be pointer to mutable
  changelog/ob.md
Labels: auto-merge, documentation

#10738 build.d: ENABLE_SANITIZERS is not a boolean variable
  src/build.d
Labels: auto-merge

#10682 add bzeroBytes symbol to share struct inits
  src/dmd/glue.d
  src/dmd/tocsym.d
  src/dmd/toobj.d
Labels: auto-merge

#10733 fix Issue 18147 - Debug information limited in size
  src/dmd/tocvdebug.d
  test/runnable/testpdb.d
Labels: Bug Fix, auto-merge

#10734 Bypass GC for compiler (without -lowmem) if built with GDC too
  src/dmd/root/rmem.d
Labels: GDC, auto-merge

#10739 Fix Issue 20530 - is(<...> == module/package) does not work with stri…
  src/dmd/dtemplate.d
  src/dmd/mtype.d
  test/compilable/imports/test20530a.d
  test/compilable/test20530.d
Labels: Bug Fix, auto-merge

#10740 build.d: Adapt dscanner target for windows
  src/build.d
Labels: auto-merge

#10742 Set OVERRIDE_MEMALLOC as false if building IN_GCC
  src/dmd/root/rmem.d
Labels: auto-merge

#10743 Add tests for reserved version identifiers: iOS, TVOS and WatchOS
  test/fail_compilation/reserved_version.d
Labels: auto-merge

#10744 mtype.h: Add islive field to C++ definition of TypeFunction
  src/dmd/mtype.h
  src/tests/cxxfrontend.c
Labels: Easy Review, Regression

#10737 root/array.d: Implement toString for Strings Array types
  src/dmd/root/array.d
Labels: auto-merge

#10741 Slightly increase flexibility of d_do_test test runner, mainly wrt. DISABLED directives
  test/run.d
  test/tools/d_do_test.d
Labels: auto-merge

#10748 runnable/test19086.d: Do not check CRLF in
  test/runnable/test19086.d
Labels: Easy Review

#10749 Fix issue 20545 - Segfault/Assertion failure when parsing invalid AA literal
  src/dmd/parse.d
  test/fail_compilation/ice20545.d
Labels: Bug Fix, auto-merge

#10750 Fix Issue 20549 - Initialization with a tuple of a module symbol refe…
  src/dmd/dsymbolsem.d
  test/fail_compilation/test20549.d
Labels: Bug Fix, auto-merge-squash
