Repository dlang/dmd, pull requests merged in 2020-03, with the labels that each got.

#10849 Merge remote-tracking branch 'upstream/stable' into merge_stable
  .azure-pipelines/windows-msbuild.bat
  .azure-pipelines/windows-visual-studio.sh
  VERSION
  azure-pipelines.yml
  changelog/d1-operator-deprecation.dd
  changelog/deallocator.dd
  src/dmd/link.d
  test/compilable/traits.d
  test/run.d
  test/tools/d_do_test.d
Labels: Bug Fix, auto-merge

#10838 Fix issue 20609 - Disabled and deprecated functions show up as candidate
  src/dmd/dscope.d
  src/dmd/func.d
  test/fail_compilation/fail19419.d
  test/fail_compilation/fail20609.d
Labels: Enhancement, auto-merge

#10853 test: Ensure template10.test1c is ran during execution test.
  test/runnable/template10.d
Labels: Easy Review, auto-merge

#10854 Fix printf example in changelog.
  changelog/chkprintf.md
Labels: auto-merge

#10855 Fix issue 20625: Improve diagnostics and test immediately called function literals
  src/dmd/expressionsem.d
  test/fail_compilation/diag_funclit.d
Labels: Diagnostic Messages, Enhancement, auto-merge

#10857 Restore old unittest behaviour for runnable tests
  test/tools/d_do_test.d
Labels: auto-merge

#10805 Enable DIP25 by default
  src/dmd/escape.d
  test/fail_compilation/dip25.d
  test/fail_compilation/fail11503c.d
  test/fail_compilation/fail11503d.d
Labels: auto-merge

#10859 Add a changelog for DIP25-by-default (PR10805)
  changelog/dip25.dd
Labels: Easy Review, Trivial, auto-merge

#10860 [refactor] extract VSOptions to a separate file for simpler reuse in LDC
  src/build.d
  src/dmd/link.d
  src/dmd/mars.d
  src/dmd/vsoptions.d
Labels: auto-merge

#10861 d_do_tests: Actually run the tools' unittests
  test/Makefile
Labels: auto-merge

#10862 Size t dtoh
  src/dmd/astcodegen.d
  src/dmd/dtoh.d
  test/compilable/dtoh_AliasDeclaration.d
  test/compilable/dtoh_VarDeclaration.d
  test/compilable/dtoh_functions.d
Labels: auto-merge-squash

#10865 Fix Issue 20636 - Support the RDSEED instruction in asm blocks
  src/dmd/backend/ptrntab.d
  test/runnable/iasm64.d
Labels: Enhancement, auto-merge

#10858 Fix issue 20627: Module ctors / dtors should always have D linkage
  changelog/dep-non-externd-modulectordtors.dd
  src/dmd/dsymbolsem.d
  src/dmd/tokens.d
  test/fail_compilation/issue20627.d
Labels: Enhancement, auto-merge

#10866 Minor code improvements, add documentation for nspace and target modules
  src/dmd/dsymbol.d
  src/dmd/expressionsem.d
  src/dmd/nspace.d
  src/dmd/target.d
Labels: Easy Review, Refactoring, auto-merge

#10868 Fix issue 20638: only offer correction for module property if symbol is visible.
  src/dmd/expressionsem.d
  test/fail_compilation/dip22a.d
  test/fail_compilation/fail10528.d
  test/fail_compilation/fail20638.d
  test/fail_compilation/imports/fail20638b.d
Labels: Bug Fix, auto-merge

#10845 [easy review] Reenable development utility astTypeName
  src/build.d
  src/dmd/asttypename.d
Labels: auto-merge-squash

#10719 Filter BUILD_SOURCEVERSIONAUTHOR in sameenv dshell test
  test/dshell/extra-files/printenv.d
Labels: auto-merge

#10870 Enforce TEST_OUTPUT for fail_compilation tests
  test/tools/d_do_test.d
Labels: auto-merge

#10873 [stable] Two small C++ header fix-ups
  src/dmd/expression.h
  src/dmd/root/ctfloat.h
Labels: auto-merge

#10611 build.d: Enable parallel builds
  src/build.d
Labels: auto-merge

#10879 run.d: Replace exit() with a dedicated exception.
  test/run.d
Labels: auto-merge

#10874 [refactor] deindent tuple parameter expansion
  src/dmd/semantic3.d
Labels: Refactoring, Trivial, auto-merge-squash

#10877 Enforce TEST_OUTPUT for runnable tests & add missing sections.
  test/runnable/arrayop.d
  test/runnable/complex.d
  test/runnable/cppa.d
  test/runnable/dhry.d
  test/runnable/ifti.d
  test/runnable/imports/link15194std.d
  test/runnable/integrate.d
  test/runnable/link10920.d
  test/runnable/opover.d
  test/runnable/template2.d
  test/runnable/template9.d
  test/runnable/test12.d
  test/runnable/test22.d
  test/runnable/test28.d
  test/runnable/test3449.d
  test/runnable/test42.d
  test/runnable/testassign.d
  test/runnable/testswitch.d
  test/runnable/testthread2.d
  test/runnable/traits.d
  test/runnable/xtest46_gc.d
  test/tools/d_do_test.d
Labels: auto-merge

#10875 Refactor escape
  src/dmd/escape.d
Labels: Refactoring

#10864 [stable] Follow-up on #9221
  src/dmd/dsymbolsem.d
  test/runnable/imports/test17181c.d
  test/runnable/test17181b.d
Labels: auto-merge

#10881 Fix Issue 20649 - Trait isZeroInit gives false in certain scenarios
  src/dmd/mtype.d
  src/dmd/mtype.h
  test/runnable/test20649.d
Labels: Bug Fix, auto-merge

#10871 Enforce TEST_OUTPUT for compilable tests & add missing sections
  test/compilable/objc_interface_final_19654.d
  test/compilable/test3004.d
  test/tools/d_do_test.d
Labels: auto-merge

#10885 fix issue 20658 - can modify overlapped storage classes in @safe enum…
  src/dmd/safe.d
  test/fail_compilation/fail20658.d
Labels: Bug Fix, auto-merge

#10820 fix Issue 20593 - Parser syntax for asm operands differs from GCC
  src/dmd/iasmgcc.d
Labels: Bug Fix, GDC, auto-merge

#10887 add mscoffobj to SCPP build
  src/dmd/backend/code.d
  src/dmd/backend/cv8.d
  src/dmd/backend/mscoffobj.d
  src/dmd/backend/obj.d
Labels: Refactoring, auto-merge

#10888 StringExp: Document compare semantic
  src/dmd/backend/cgreg.d
  src/dmd/expression.d
Labels: Trivial, auto-merge

#10702 Fix issue 20470 - Keep `this` when accessing tuple members
  src/dmd/expressionsem.d
  test/runnable/b20470.d
Labels: Enhancement, auto-merge

#10890 Remove obsolete test for issue 4543
  test/runnable/circular.d
Labels: auto-merge

#10889 (Fix #20662) Set the DMD binary as executable
  src/build.d
Labels: auto-merge

#10892 Make runnable/mixin1 test more deterministic
  test/runnable/mixin1.d
Labels: auto-merge

#10891 Backend: Remove some code duplication
  src/dmd/backend/cgobj.d
  src/dmd/backend/cv8.d
  src/dmd/backend/dcgcv.d
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/machobj.d
  src/dmd/backend/mscoffobj.d
  src/dmd/backend/outbuf.d
Labels: auto-merge

#10893 updateTempDecl: Simplify, refactor, de-indent
  src/dmd/dtemplate.d
Labels: auto-merge

#10042 remove `HiddenParameters`, refactor `declareThis`
  src/dmd/declaration.h
  src/dmd/dtemplate.d
  src/dmd/func.d
  src/dmd/semantic3.d
Labels: auto-merge

#10894 Refactor: Make backend's outbuffer a little bit safer
  src/dmd/backend/aarray.d
  src/dmd/backend/cgobj.d
  src/dmd/backend/cod3.d
  src/dmd/backend/cv8.d
  src/dmd/backend/dcgcv.d
  src/dmd/backend/dwarf.d
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/dwarfeh.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/machobj.d
  src/dmd/backend/mscoffobj.d
  src/dmd/backend/outbuf.d
  src/dmd/glue.d
Labels: auto-merge

#10876 Fix issue 20645 - printf deprecation for width + precision
  src/dmd/chkformat.d
  test/fail_compilation/chkformat.d
  test/runnable/dhry.d
Labels: Bug Fix

#10897 make varstats work with DMC
  src/dmd/backend/cc.d
  src/dmd/backend/cv8.d
  src/dmd/backend/dvarstats.d
Labels: auto-merge

#10896 dmd.root.array: Add `sort` method, wrapping `qsort`
  src/dmd/libmscoff.d
  src/dmd/libomf.d
  src/dmd/root/array.d
  src/dmd/root/string.d
  src/dmd/statementsem.d
Labels: auto-merge

#10886 Refactor: Group environment processing in d_do_test
  test/tools/d_do_test.d
Labels: auto-merge

#10900 Remove obsolete statictor-postscript.sh (replaced by RUN_OUTPUT)
  test/runnable/extra-files/statictor-postscript.sh
  test/runnable/extra-files/statictor.d.out
  test/runnable/statictor.d
Labels: auto-merge

#10901 Replace some runnable bash tests
  test/runnable/extra-files/test18868_b.d
  test/runnable/imports/test17968a.d
  test/runnable/imports/test18868_a.d
  test/runnable/test17968.d
  test/runnable/test17968.sh
  test/runnable/test18868.d
  test/runnable/test18868.sh
Labels: auto-merge

#10899 backend.outbuf: Make member 'p' private
  src/dmd/backend/cgobj.d
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/dwarfeh.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/machobj.d
  src/dmd/backend/mscoffobj.d
  src/dmd/backend/outbuf.d
Labels: Refactoring, auto-merge

#10906 Refactor some more string handling in lib
  src/dmd/glue.d
  src/dmd/lib.d
  src/dmd/libelf.d
  src/dmd/libmach.d
  src/dmd/libmscoff.d
  src/dmd/libomf.d
  src/dmd/mars.d
  src/dmd/root/file.d
  src/dmd/utils.d
Labels: auto-merge

#10869 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/deallocator.dd
  changelog/gnu-error-style.dd
  changelog/headers.dd
  src/dmd/expression.h
  src/dmd/root/ctfloat.h
Labels: auto-merge

#10907 Refactor: Rework dwarfdbginf's LEB128 handling to use slice
  src/dmd/backend/dwarfeh.d
Labels: auto-merge

#10914 [dmd-cxx] test: Remove compilable __traits tests
  test/fail_compilation/fail11169.d
  test/fail_compilation/fail7815.d
  test/fail_compilation/fail7886.d
Labels: C++ Port, Easy Review, GDC

#10913 [dmd-cxx] Fix issues 19655, 19656, 19657, 19746 & 19750 (#9471)
  src/dclass.c
  test/compilable/imports/pr9471a.d
  test/compilable/imports/pr9471b.d
  test/compilable/imports/pr9471c.d
  test/compilable/imports/pr9471d.d
  test/compilable/pr9471.d
  test/compilable/test19656.sh
  test/compilable/test19657.sh
  test/compilable/test19746.sh
  test/compilable/test19750.sh
  test/runnable/test19655.sh
Labels: Bug Fix, C++ Port, GDC

#10909 Add table of contents for src/dmd/root
  src/dmd/root/README.md
Labels: auto-merge

#10911 Add Ddoc headers for modules in dmd/root
  src/dmd/root/aav.d
  src/dmd/root/array.d
  src/dmd/root/bitarray.d
  src/dmd/root/ctfloat.d
  src/dmd/root/file.d
  src/dmd/root/filename.d
  src/dmd/root/hash.d
  src/dmd/root/longdouble.d
  src/dmd/root/man.d
  src/dmd/root/outbuffer.d
  src/dmd/root/port.d
  src/dmd/root/region.d
  src/dmd/root/response.d
  src/dmd/root/rmem.d
  src/dmd/root/rootobject.d
  src/dmd/root/speller.d
  src/dmd/root/string.d
  src/dmd/root/stringtable.d
  src/dmd/root/strtold.d
Labels: auto-merge

#10915 fix Issue 20084 - return by auto ref unsafe - and different code for …
  src/dmd/escape.d
  test/fail_compilation/fail20084.d
Labels: Bug Fix, auto-merge

#10832 [RFC] Let tests include generated files in TEST_OUTPUT check
  test/README.md
  test/compilable/extra-files/json2.out
  test/compilable/json2.d
  test/tools/d_do_test.d
Labels: auto-merge

#10916 [dmd-cxx] Check in iasmgcc.c implementation
  src/iasmgcc.c
Labels: Bug Fix, C++ Port, GDC, auto-merge

#10918 run.d: Use target model instead of DMD model in linker paths
  test/run.d
Labels: auto-merge

#10917 Replace OUTPUT_FILES marker which collides with section delimiters
  test/README.md
  test/compilable/extra-files/json2.out
  test/tools/d_do_test.d
Labels: auto-merge

#10923 Fix Issue 20610 - const in a .tupleof loop is ignored
  src/dmd/statementsem.d
  test/fail_compilation/test20610.d
Labels: Bug Fix, auto-merge

#10908 Rework compilable/test19656.sh as non-shell test
  test/compilable/imports/test19656a.d
  test/compilable/imports/test19656b.d
  test/compilable/imports/test19656c.d
  test/compilable/test19656.d
  test/compilable/test19656.sh
Labels: auto-merge

#10912 test: Add another compilable test for PR 9471
  test/compilable/imports/pr9471a.d
  test/compilable/imports/pr9471b.d
  test/compilable/imports/pr9471c.d
  test/compilable/imports/pr9471d.d
  test/compilable/pr9471.d
Labels: Easy Review, auto-merge

#10926 Backend: Cleanup dlist
  src/dmd/backend/dlist.d
Labels: auto-merge

#10925 d_do_test: Fix bash test on windows
  test/tools/d_do_test.d
Labels: auto-merge

#10928 Add missing test parameters to test/README.md
  test/README.md
Labels: auto-merge

#10919 Make printenv.d print all variables except BUILD_SOURCEVERSIONAUTHOR
  test/dshell/extra-files/printenv.d
Labels: auto-merge

#10933 [dmd-cxx] Backport contentImportedFiles field
  src/expressionsem.c
  src/module.h
Labels: C++ Port, Easy Review, GDC

#10936 [dmd-cxx] test: Don't use new-style contract syntax in runnable/traits.d
  test/runnable/traits.d
Labels: C++ Port, Easy Review, GDC

#10929 fix issue 20675 - dip1000 improper error about copying scope paramete…
  src/dmd/escape.d
  test/compilable/scope.d
Labels: Bug Fix, auto-merge

#10932 Backend's Outbuffer: Use Reset
  src/dmd/backend/cgobj.d
  src/dmd/backend/cv8.d
  src/dmd/backend/dcgcv.d
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/machobj.d
  src/dmd/backend/mscoffobj.d
Labels: Refactoring, auto-merge

#10904 Add table of contents for src/dmd
  src/dmd/README.md
  src/dmd/readme.txt
Labels: 72h no objection -> merge, auto-merge

#10942 Continue #10878: Remove unused code & fix parallelization in test/Makefile
  .azure-pipelines/windows-msbuild.bat
  .azure-pipelines/windows.sh
  .circleci/run.sh
  ci.sh
  test/Makefile
Labels: auto-merge

#10939 fix issue 20653 . Short circuit manifest constant evaluation
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/expressionsem.d
  src/dmd/initsem.d
  test/compilable/test20653.d
Labels: Bug Fix, auto-merge

#10941 Fix Issue 20130 - ICE when casting from string to other array type du…
  src/dmd/expressionsem.d
  test/runnable/test20130.d
Labels: Bug Fix, auto-merge

#10883 Fix Issue 20656 - cannot compile live function without -preview=dip1021
  src/dmd/semantic3.d
  test/compilable/test20656.d
  test/fail_compilation/fob1.d
  test/fail_compilation/fob2.d
Labels: Bug Fix, auto-merge

#10935 fix issue 20682 - [DIP1000] wrong error: scope variable may not be co…
  src/dmd/escape.d
  test/compilable/scope.d
Labels: Bug Fix, auto-merge

#10910 Rework compilable/depsOutput9948.d without phobos & POST_SCRIPT
  test/compilable/depsOutput9948.d
  test/compilable/extra-files/depsOutput.sh
  test/compilable/imports/depsOutput9948a.d
  test/compilable/imports/depsOutput9948b.d
Labels: auto-merge

#10946 Fix Issue 20687 - Allow member function address as const initializer
  src/dmd/todt.d
  test/runnable/test20687.d
Labels: Bug Fix, auto-merge

#10949 Simplify test execution in d_do_test
  test/tools/d_do_test.d
Labels: auto-merge

#10950 Prefer the host dmd to compile the test runner
  test/Makefile
Labels: auto-merge

#10934 Split C++ runnable tests into a separate directory ...
  .azure-pipelines/windows-msbuild.bat
  test/Makefile
  test/run.d
  test/runnable_cxx/cabi1.d
  test/runnable_cxx/cpp11.d
  test/runnable_cxx/cpp_abi_tests.d
  test/runnable_cxx/cpp_stdlib.d
  test/runnable_cxx/cppa.d
  test/runnable_cxx/externmangle.d
  test/runnable_cxx/externmangle2.d
  test/runnable_cxx/extra-files/cabi2.cpp
  test/runnable_cxx/extra-files/cpp11.cpp
  test/runnable_cxx/extra-files/cpp_abi_tests.cpp
  test/runnable_cxx/extra-files/cpp_stdlib.cpp
  test/runnable_cxx/extra-files/cppb.cpp
  test/runnable_cxx/extra-files/cppb.h
  test/runnable_cxx/extra-files/externmangle.cpp
  test/runnable_cxx/extra-files/externmangle2.cpp
  test/runnable_cxx/extra-files/stdint.cpp
  test/runnable_cxx/extra-files/test6716.cpp
  test/runnable_cxx/stdint.d
  test/runnable_cxx/test6716.d
  test/tools/d_do_test.d
Labels: auto-merge

#10955 implicitCastTo(): refactor
  src/dmd/dcast.d
Labels: Easy Review, Refactoring

#10956 dcast.d: some refactoring
  src/dmd/dcast.d
Labels: Easy Review, Refactoring, auto-merge

#10948 Revert "Fix Issue 20687 - Allow member function address as const initializer"
  src/dmd/todt.d
  test/runnable/test20687.d
Labels: Bug Fix

#10953 Rework handling of disabled tests in d_do_test
  test/tools/d_do_test.d
Labels: auto-merge

#10962 Remove more shell scripts used as POST_SCRIPT
  test/compilable/extra-files/rdepsOutput.sh
  test/compilable/extra-files/test11237.sh
  test/compilable/extra-files/test7754-postscript.sh
  test/compilable/extra-files/test7754.di
  test/compilable/rdeps7016.d
  test/compilable/test11237.d
  test/compilable/test7754.d
  test/runnable/extra-files/test17868-postscript.sh
  test/runnable/extra-files/test17868.d.out
  test/runnable/test17868.d
  test/runnable/test17868b.d
Labels: auto-merge

#10966 Use `DISABLED: win` in runnable/externmangle2.d ...
  test/runnable_cxx/externmangle2.d
Labels: auto-merge

#10947 fix Issue 20461 - [dip1000] Passing stack allocated string to assert …
  src/dmd/escape.d
  src/dmd/expressionsem.d
  test/fail_compilation/fail20461.d
Labels: Bug Fix, auto-merge

#10964 Add a Github action file to test runnable_cxx
  .github/workflows/runnable_cxx.yml
Labels: Blocking Other Work, auto-merge

#10927 Fix issue 19949: Implement support for C++ ABI tags
  changelog/cpp_abi_tags.dd
  ci.sh
  posix.mak
  src/dmd/attrib.d
  src/dmd/cppmangle.d
  src/dmd/dsymbolsem.d
  src/dmd/id.d
  src/dmd/semantic2.d
  test/Makefile
  test/compilable/cpp_abi_tag_unused.d
  test/compilable/cppmangle_abitag.d
  test/fail_compilation/cpp_abi_tag.d
  test/fail_compilation/cpp_abi_tag2.d
  test/runnable_cxx/abi_tags.d
  test/runnable_cxx/cpp_stdlib.d
  test/runnable_cxx/extra-files/abi_tags.cpp
  test/tools/d_do_test.d
Labels: Bug Fix, auto-merge

#10920 Fix Issue 20644 - Invalid printf deprecation for ubyte passed to "%hhu"
  src/dmd/chkformat.d
  test/compilable/chkformat.d
  test/runnable/dhry.d
  test/runnable/test42.d
Labels: Bug Fix, auto-merge

#6766 fix Issue 14639 - Assigning init value to struct uses stack, causing …
  src/dmd/aggregate.h
  src/dmd/clone.d
  src/dmd/dstruct.d
  src/dmd/opover.d
  test/runnable/sdtor.d
Labels: Bug Fix, auto-merge

#10971 Fix unittest runner invocation for windows
  test/run.d
Labels: auto-merge

#10972 Add -preview=dip1021 to fail_compilation/failob1.d
  test/fail_compilation/failob1.d
Labels: auto-merge

#10961 Fix Issue 20696 - Should error when retrieving mangling while the typ…
  src/dmd/expressionsem.d
  test/compilable/imports/test17541_3.d
  test/compilable/testInference.d
  test/fail_compilation/test20696.d
  test/runnable/link6574.d
  test/runnable/template9.d
Labels: Bug Fix

#10974 Remove std::string tests from the ABI tag tests
  .github/workflows/runnable_cxx.yml
  test/runnable_cxx/abi_tags.d
  test/runnable_cxx/extra-files/abi_tags.cpp
Labels: Continuous Integration, auto-merge

#10975 Add option for `outbuffer` to indent by 4 spaces
  src/dmd/root/outbuffer.d
Labels: auto-merge

#10977 test/Makefile: Address feedback for #10950
  test/Makefile
Labels: auto-merge

#10978 slit off StmtState from IRState
  src/dmd/irstate.d
  src/dmd/s2ir.d
Labels: Refactoring

#10980 [dmd-cxx] Move C++ tests to runnable_cxx
  test/runnable_cxx/cabi1.d
  test/runnable_cxx/cpp_abi_tests.d
  test/runnable_cxx/cppa.d
  test/runnable_cxx/externmangle.d
  test/runnable_cxx/externmangle2.d
  test/runnable_cxx/extra-files/cabi2.cpp
  test/runnable_cxx/extra-files/cpp_abi_tests.cpp
  test/runnable_cxx/extra-files/cppb.cpp
  test/runnable_cxx/extra-files/externmangle.cpp
  test/runnable_cxx/extra-files/externmangle2.cpp
  test/runnable_cxx/extra-files/test6716.cpp
  test/runnable_cxx/test6716.d
Labels: C++ Port, GDC

#10979 build.d: Forward "all" to the default "dmd" target...
  src/build.d
Labels: auto-merge

#7528 Run CircleCi with BUILD=debug
  .circleci/run.sh
  test/dshell/test_shared.d
  test/tools/dshell_prebuilt/dshell_prebuilt.d
Labels: Continuous Integration, auto-merge

#10969 Refactor: add isSomeChar to reduce duplication of checking for the 3 char types
  src/dmd/constfold.d
  src/dmd/dcast.d
  src/dmd/dinterpret.d
  src/dmd/dstruct.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/initsem.d
  src/dmd/mtype.d
  src/dmd/opover.d
  src/dmd/statementsem.d
Labels: Refactoring, auto-merge

#10984 Refactor: move IRState into toir.d
  src/dmd/irstate.d
  src/dmd/tocsym.d
  src/dmd/toir.d
  src/dmd/toobj.d
Labels: Easy Review, Refactoring, auto-merge

#10981 Add namespace handling to cpphdrgen
  src/dmd/dtoh.d
  test/compilable/dtoh_CPPNamespaceDeclaration.d
Labels: auto-merge

#10982 Cleanup dtemplate
  src/dmd/dtemplate.d
  src/dmd/template.h
Labels: auto-merge

#10930 Fixup for PR10896: Avoid old compiler bug
  src/build.d
  src/dmd/root/array.d
Labels: auto-merge

#10985 rename irstate.d to stmtstate.d
  src/build.d
  src/dmd/e2ir.d
  src/dmd/glue.d
  src/dmd/s2ir.d
  src/dmd/stmtstate.d
  src/dmd/toir.d
Labels: Easy Review, Refactoring, auto-merge

#10938 extend PR 10929 by excluding non-ptr vars
  src/dmd/escape.d
  test/fail_compilation/fail809.d
Labels: auto-merge

#10987 backend.outbuf: Merge writeWord and writeShort
  src/dmd/backend/cgobj.d
  src/dmd/backend/cv8.d
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/mscoffobj.d
  src/dmd/backend/outbuf.d
Labels: Refactoring, auto-merge

#10952 Fix Issue 20692 - Nested alias declarations and getMember trait can c…
  src/dmd/dsymbolsem.d
  src/dmd/mtype.d
  test/compilable/test20692.d
Labels: Bug Fix

#10989 Fix critical bug causing the uint64_t to be sticky
  src/dmd/dtoh.d
  test/compilable/dtoh_StructDeclaration.d
Labels: Enhancement, auto-merge

#10991 Rename irstate.d to stmtstate.d in source guide
  src/dmd/README.md
Labels: Trivial, auto-merge

#10986 follow up to PR10969. Remove ischar
  src/dmd/astbase.d
  src/dmd/dcast.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  test/compilable/implicitconv.d
Labels: auto-merge

#10992 use StmtState in ob.d for graph generation
  src/dmd/ob.d
  src/dmd/s2ir.d
  src/dmd/stmtstate.d
Labels: auto-merge
