Repository dlang/dmd, pull requests merged in 2020-05, with the labels that each got.

#11047 [stable] Add dmd.argtypes_aarch64 for the AAPCS64 ABI
  src/build.d
  src/dmd/README.md
  src/dmd/aggregate.h
  src/dmd/argtypes.d
  src/dmd/argtypes_aarch64.d
  src/dmd/argtypes_sysv_x64.d
  src/dmd/dstruct.d
  src/dmd/e2ir.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/target.d
  src/dmd/toctype.d
  src/dmd/todt.d
Labels: auto-merge

#11080 nest functions inside aecpgenkill()
  src/dmd/backend/gflow.d
Labels: Easy Review, Refactoring, auto-merge

#11085 fix Issue 19550 - [REG 2.078] Massive compiler backend slowdown
  src/dmd/backend/gflow.d
Labels: Bug Fix, auto-merge

#11090 Fix Issue 20791 - extern(C++ <strings>) should allow a trailing comma
  src/dmd/parse.d
  test/compilable/testparse.d
Labels: Enhancement, auto-merge

#11089 dmd.vsoptions: Prepare for LDC & use *latest* VS version found via COM
  src/dmd/root/filename.d
  src/dmd/vsoptions.d
  src/dmd/vsoptions.h
Labels: Bug Fix, auto-merge

#11091 [stable] Prevent redundant type semantic for va_list
  src/dmd/astbase.d
  src/dmd/dsymbolsem.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/semantic3.d
  src/dmd/target.d
  src/dmd/target.h
Labels: auto-merge

#11094 Add AVR to reserved versions
  src/dmd/cond.d
  test/fail_compilation/reserved_version.d
  test/fail_compilation/reserved_version_switch.d
Labels: auto-merge

#11086 Fix issue 20780: Function parameter UDA not accepted in nested function declarations
  src/dmd/parse.d
  test/compilable/b20780.d
  test/fail_compilation/b20780.d
Labels: Bug Fix

#11088 aecpgenkill(): refactor eliminating a couple globals
  src/dmd/backend/gflow.d
Labels: Easy Review, Refactoring, auto-merge

#11096 Fix Issue 20795 - [dip1000] segfault on templated opEquals
  src/dmd/escape.d
  test/compilable/test20795.d
Labels: Bug Fix, auto-merge

#11095 Lexer. Skip 4 whitespaces at a time
  src/dmd/lexer.d
  src/dmd/mars.d
  src/dmd/root/file.d
Labels: auto-merge

#11083 fix issue 20719 by passing previously seen structs to isTypeIsolated …
  src/dmd/func.d
  test/fail_compilation/test20719.d
Labels: Bug Fix, auto-merge

#11072 Support partial regex matching in TEST_OUTPUT
  test/README.md
  test/fail_compilation/needspkgmod.d
  test/tools/d_do_test.d
Labels: auto-merge

#11097 [refactor] Move common save scope and defer code to private function
  src/dmd/dsymbolsem.d
Labels: Refactoring, auto-merge

#11093 gflow.d: refactor defstarkill() for clarity and perf
  src/dmd/backend/dvec.d
  src/dmd/backend/gflow.d
Labels: Easy Review, Refactoring, auto-merge

#11100 Fix issue 20796: package protected symbol declared in the same packag…
  src/dmd/attrib.d
  test/compilable/bug20796.d
  test/compilable/protection/issue20796/package.d
Labels: Enhancement, auto-merge-squash

#11002 Fix Issues 20718, 15867, 12380 - Wrong location errors on const. folding / exp. optimization
  src/dmd/dinterpret.d
  src/dmd/optimize.d
  test/fail_compilation/b20011.d
  test/fail_compilation/diag12380.d
  test/fail_compilation/diag15867.d
  test/fail_compilation/diag20718.d
  test/fail_compilation/diag9250.d
  test/fail_compilation/fail19897.d
  test/fail_compilation/imports/diag20718mod.d
Labels: Bug Fix, auto-merge

#10694 [trivial] fix loc of TypeMixin
  src/dmd/parse.d
Labels: Trivial, auto-merge

#11102 Revert "Fix Issues 20718, 15867, 12380 - Wrong location errors on const. folding / exp. optimization"
  src/dmd/dinterpret.d
  src/dmd/optimize.d
  test/fail_compilation/b20011.d
  test/fail_compilation/diag12380.d
  test/fail_compilation/diag15867.d
  test/fail_compilation/diag20718.d
  test/fail_compilation/diag9250.d
  test/fail_compilation/fail19897.d
  test/fail_compilation/imports/diag20718mod.d
Labels: Bug Fix, auto-merge

#11105 [Trivial] small fix for markdown code highlight
  test/README.md
Labels: Trivial

#11104 [Trivial] Alphabetical ordering reserved version identifier
  src/dmd/cond.d
Labels: Trivial

#11113 change parseParameters() to parseParameterList()
  src/dmd/parse.d
Labels: Easy Review, Refactoring

#11116 simplify parseFunctionLiteral()
  src/dmd/parse.d
Labels: Easy Review, Refactoring, auto-merge

#11107 make VarArg a ubyte
  src/dmd/astbase.d
  src/dmd/mtype.d
  src/dmd/mtype.h
Labels: Easy Review, Refactoring, auto-merge

#11115 [Trivial] Remove _d_assocarrayliteralT
  src/dmd/backend/drtlsym.d
  src/dmd/backend/rtlsym.d
Labels: Trivial, auto-merge

#11108 STC should be ulong
  src/dmd/astbase.d
  src/dmd/declaration.d
  src/dmd/declaration.h
Labels: Easy Review, Refactoring

#11121 Fix issue 16971 - Misleading error messages...
  src/dmd/statementsem.d
  test/fail_compilation/fail6889.d
Labels: Bug Fix, auto-merge

#11118 merge stable
  VERSION
  src/build.d
  src/dmd/README.md
  src/dmd/aggregate.h
  src/dmd/argtypes.d
  src/dmd/argtypes_aarch64.d
  src/dmd/argtypes_sysv_x64.d
  src/dmd/astbase.d
  src/dmd/dstruct.d
  src/dmd/dsymbolsem.d
  src/dmd/e2ir.d
  src/dmd/escape.d
  src/dmd/globals.h
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/nspace.h
  src/dmd/root/filename.d
  src/dmd/root/outbuffer.h
  src/dmd/semantic3.d
  src/dmd/target.d
  src/dmd/target.h
  src/dmd/toctype.d
  src/dmd/todt.d
  test/compilable/test20795.d
  test/fail_compilation/fail20779.d
Labels: Bug Fix, auto-merge

#11123 test: Remove deprecated creal phobos tests
  test/runnable/complex.d
Labels: Easy Review, auto-merge

#11122 Add test to run unittests with betterC
  test/runnable/bettercUnittest.d
  test/runnable/extra-files/moreBettercUnittests.d
Labels: auto-merge

#11117 NewDeclaration takes a ParameterList
  src/dmd/astbase.d
  src/dmd/dsymbolsem.d
  src/dmd/func.d
  src/dmd/hdrgen.d
  src/dmd/mtype.d
  src/dmd/parse.d
  src/dmd/transitivevisitor.d
Labels: Easy Review, Refactoring, auto-merge

#11119 Trivial: Add a link to commit message guidelines
  CONTRIBUTING.md
Labels: auto-merge

#11126 [stable] dmd.expressionsem: Fix potential segfault
  src/dmd/expressionsem.d
Labels: 72h no objection -> merge

#11125 start adding support for storage classes for ...
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/parse.d
  test/fail_compilation/varargsstc.d
Labels: Diagnostic Messages, Easy Review

#11133 [Trivial][Refactor] remove symbols which dmd never generates
  src/dmd/backend/drtlsym.d
  src/dmd/backend/rtlsym.d
Labels: auto-merge

#11134 [root.filename] reduce splitPath indent
  src/dmd/root/filename.d
Labels: Refactoring, Trivial, auto-merge

#11129 Remove/Replace another chunk of phobos usage
  test/compilable/ddoc_markdown_links.d
  test/compilable/extra-files/ddoc_markdown_links.html
  test/compilable/extra-files/header1.d
  test/compilable/extra-files/header1.di
  test/compilable/extra-files/header1i.di
  test/compilable/test15780.d
  test/compilable/test17057.d
  test/runnable/ifti.d
  test/runnable/integrate.d
  test/runnable/test10942.d
  test/runnable/test12.d
  test/runnable/test22.d
  test/runnable/test23.d
  test/runnable/testthread2.d
Labels: auto-merge

#11130 merge stable
  VERSION
  changelog/bug10478-cli-switches.dd
  changelog/cpp_abi_tags.dd
  changelog/dep-non-externd-modulectordtors.dd
  changelog/dip25.dd
  changelog/ob.dd
  changelog/preview-in.dd
  changelog/printfParams2.dd
  changelog/reproducible-builds.dd
  src/dmd/expressionsem.d
Labels: auto-merge

#11081 Fix issue 20789: -de should disable is(T : U) if T alias-this to U is deprecated unless in deprecated scope
  src/dmd/expressionsem.d
  src/dmd/mtype.d
  test/compilable/test20789.d
Labels: Bug Fix, auto-merge

#11114 Add a DLL test for windows and posix
  test/dshell/dll.d
  test/dshell/extra-files/dll/dllmain.d
  test/dshell/extra-files/dll/mydll.d
  test/dshell/extra-files/dll/testdll.d
  test/tools/dshell_prebuilt/dshell_prebuilt.d
Labels: auto-merge

#11135 [Revised] start adding support for storage classes for ...
  src/dmd/astbase.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/parse.d
  test/fail_compilation/varargsstc.d
Labels: Blocking Other Work, auto-merge

#11141 Print additional error message on self-compilation failure
  ci.sh
Labels: Easy Review, Trivial

#11106 Fix Issue 20800 - Error: cannot implicitly convert expression with bad diagnostic
  src/dmd/hdrgen.d
  test/fail_compilation/fail20800.d
  test/fail_compilation/ice8255.d
Labels: Bug Fix, auto-merge

#11145 Fix Issue 20626 - ICE when using typeof of unittest symbol without -u…
  src/dmd/typesem.d
  test/fail_compilation/test20626.d
Labels: Bug Fix, auto-merge

#11149 replace Loop linked list with Barray
  src/dmd/backend/gloop.d
Labels: Refactoring, auto-merge

#11137 Add a test for dmd --help output
  test/compilable/extra-files/empty.conf
  test/compilable/testhelp.d
Labels: auto-merge

#11151 convert Llis from list to Barray
  src/dmd/backend/gloop.d
Labels: Refactoring, auto-merge

#11150 replace IVnext linked list with Barray
  src/dmd/backend/gloop.d
Labels: Refactoring, auto-merge

#11136 pretty-print attributes on variadic functions
  src/dmd/hdrgen.d
  test/fail_compilation/vararg2.d
Labels: Enhancement, auto-merge

#11155 [Trivial] Fix typo
  src/dmd/root/README.md
  src/dmd/root/strtold.d
Labels: Trivial, auto-merge

#11156 Explicitly import `core.attribute.selector`
  test/compilable/objc_class.d
  test/compilable/objc_interface_final_19654.d
  test/fail_compilation/objc_class1.d
  test/fail_compilation/objc_class2.d
  test/fail_compilation/objc_class3.d
  test/runnable/extra-files/test16096a.d
  test/runnable/objc_call.d
  test/runnable/objc_call_static.d
  test/runnable/objc_class.d
  test/runnable/objc_external_class_19700.d
  test/runnable/objc_instance_variable.d
  test/runnable/objc_objc_msgSend.d
  test/runnable/objc_super_call.d
Labels: Trivial, auto-merge

#11157 Fix issue 20825: paths in error messages from build.d should be click…
  src/build.d
Labels: Bug Fix, Build System, auto-merge

#11152 dmd.ctorflow: Remove self reference assignments in mergeFieldInit
  src/dmd/ctorflow.d
Labels: Easy Review, auto-merge

#11154 replace FLnext linked list with Barray
  src/dmd/backend/barray.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/cgsched.d
  src/dmd/backend/gloop.d
  src/dmd/backend/go.d
  src/dmd/backend/symbol.d
Labels: Refactoring, auto-merge

#11159 Fix Issue 20842 - Structs with disabled default/copy ctors can't be i…
  src/dmd/dstruct.d
  src/dmd/initsem.d
  test/compilable/test20842.d
Labels: Bug Fix, auto-merge

#11163 Fix issue 20835 - Enum member attributes being evaluated in wrong scope.
  src/dmd/traits.d
  test/compilable/imports/test19344.d
  test/compilable/test20835.d
Labels: Bug Fix, auto-merge

#11162 Fix Issue 20744 - Using __parameters result in function definition ca…
  src/dmd/attrib.d
  src/dmd/dsymbolsem.d
  test/compilable/test20744.d
  test/fail_compilation/cpp_abi_tag.d
Labels: Enhancement, auto-merge

#11041 delete debug hack which turns all non-root instances to speculative
  src/dmd/dtemplate.d
Labels: auto-merge

#11169 Github CI: Export built DMD as artifacts
  .github/workflows/runnable_cxx.yml
Labels: Continuous Integration, auto-merge

#11168 Change Loops from linked list to Barray
  src/dmd/backend/gloop.d
Labels: Refactoring, auto-merge

#11173 Revert "Add a test for dmd --help output"
  test/compilable/extra-files/empty.conf
  test/compilable/testhelp.d
Labels: Continuous Integration, auto-merge

#10575 Add new builtin trait isCopyable
  changelog/add_traits_isCopyable.dd
  src/dmd/id.d
  src/dmd/mtype.d
  src/dmd/traits.d
  test/compilable/traits.d
Labels: auto-merge

#11171 gloop.d: bunch of minor refactors
  src/dmd/backend/global.d
  src/dmd/backend/gloop.d
Labels: Easy Review, Refactoring, auto-merge

#11166 Fix issue 15235: inline asm: silent ICE (segfault) in asm_add_exp()
  src/dmd/iasmdmd.d
  test/fail_compilation/diag15235.d
Labels: Bug Fix, auto-merge

#11179 Add explicit @system attribute to extern functions
  src/dmd/backend/code.d
  src/dmd/backend/elfobj.d
Labels: auto-merge

#11158 Fix Issue 20840 - No deprecation for template from deprecated selecti…
  src/dmd/dtemplate.d
  test/fail_compilation/deprecatedImports.d
  test/fail_compilation/imports/deprecatedImporta.d
  test/fail_compilation/imports/deprecatedImportb.d
Labels: Bug Fix, auto-merge

#11142 Fix Issue 20830 - Segfault for multiple duplicate interfaces
  src/dmd/dsymbolsem.d
  test/fail_compilation/fail124.d
Labels: Bug Fix, auto-merge

#11164 d_do_test: Use lock for both gdb .d and .sh tests
  test/runnable/gdb15729.sh
  test/tools/d_do_test.d
Labels: auto-merge

#11181 Port some more tests to D
  test/compilable/mixin.d
  test/compilable/previewhelp.d
  test/compilable/reverthelp.d
  test/compilable/test14198.d
  test/compilable/testdmdfeatureflags.sh
  test/compilable/transitionhelp.d
  test/fail_compilation/fail7524a.d
  test/fail_compilation/fail7524a.sh
  test/runnable/extra-files/mixin.d
  test/runnable/extra-files/mixin.mixin
  test/runnable/link14198b.sh
  test/runnable/mixin.sh
Labels: auto-merge

#11051 Extend checkaction=context for boolean convertible expressions
  src/dmd/expressionsem.d
  test/runnable/testassert.d
Labels: auto-merge

#11182 iasmdmd refactoring
  src/dmd/iasmdmd.d
Labels: auto-merge

#11183 fix issue 20758 - __traits(getAttributes) as template argument result…
  src/dmd/dtemplate.d
  test/compilable/b20758.d
Labels: Bug Fix, auto-merge

#11175 recognize isAlias template pattern(s), process directly
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/template.h
Labels: auto-merge

#11160 Fix Issues 19728, 20093 - AliasSeq in UDA errors
  src/dmd/expression.d
  test/compilable/test19728.d
Labels: Bug Fix, auto-merge

#11139 expressionsem:visit(IsExp e) goto -> local function
  src/dmd/expressionsem.d
Labels: Refactoring, Trivial, auto-merge

#11187 fix issue 12520 - allow comparison of empty tuples to tuples that con…
  src/dmd/expressionsem.d
  test/compilable/issue12520.d
Labels: Bug Fix, auto-merge

#11188 make helper `extractTypeTupAndExpTup.Result` smaller
  src/dmd/expressionsem.d
Labels: auto-merge

#11184 rdlist: convert from list_t to Barray
  src/dmd/backend/go.d
  src/dmd/backend/goh.d
  src/dmd/backend/gother.d
Labels: Refactoring, auto-merge

#11170 mars.d: replace C-style strings with D arrays
  src/dmd/mars.d
Labels: auto-merge

#11190 Fix Issue 11292 - Cannot re-initialize a const field in postblit
  src/dmd/declaration.d
  test/compilable/test11292.d
Labels: auto-merge

#11192 Fix incorrect .editorconfig comment
  .editorconfig
Labels: Trivial, auto-merge

#11167 DDOC: Some "char*" => D string conversions
  src/dmd/doc.d
Labels: Refactoring, auto-merge

#11195 Refactor iasmdmd. Convert multiple optional pointer parameters to slices
  src/dmd/iasmdmd.d
Labels: auto-merge

#11193 fix issue 20875 - specialization ignored for template alias param use…
  src/dmd/dtemplate.d
  test/fail_compilation/b20875.d
Labels: Bug Fix

#11196 Share D-Scanner between builds and bump version
  src/build.d
Labels: auto-merge

#11199 replace several `new IntegerExp` with `IntegerExp.literal`
  src/dmd/cond.d
  src/dmd/dsymbolsem.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/inline.d
  src/dmd/statementsem.d
Labels: auto-merge

#11191 Fix issue 20861: Interface implementations are not checked when code gen is skipped
  changelog/check_interface_implementations.dd
  src/dmd/dclass.d
  src/dmd/dsymbolsem.d
  src/dmd/root/string.d
  test/fail_compilation/diag8318.d
  test/fail_compilation/diag9191.d
  test/fail_compilation/test17451.d
  test/tools/unit_test_runner.d
  test/unit/compilable/crlf.d
  test/unit/interfaces/check_implementations_20861.d
  test/unit/support.d
Labels: Bug Fix, auto-merge

#11200 Fix Issue 20884 - Using getMember with a type as first argument can l…
  src/dmd/traits.d
  test/compilable/traits.d
Labels: Bug Fix, auto-merge

#11201 fix issue 20885 - pointer rejected for the variable declared in a `if…
  src/dmd/parse.d
  test/compilable/b20885.d
Labels: Bug Fix, auto-merge

#11198 glocal.d: add const
  src/dmd/backend/glocal.d
Labels: Easy Review, Refactoring, auto-merge

#11165 remove loop order dependency in IVincr removal
  src/dmd/backend/gloop.d
Labels: Refactoring

#11180 gloop now recycles memory instead of free/malloc
  src/dmd/backend/barray.d
  src/dmd/backend/gloop.d
Labels: Refactoring, auto-merge

#11203 cxx-unittest: Update C++ baseline support to C++11
  src/build.d
Labels: auto-merge
