Repository dlang/dmd, pull requests merged in 2020-10, with the labels that each got.

#11818 refactor Type.resolve()
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/expressionsem.d
  src/dmd/mtype.d
  src/dmd/traits.d
  src/dmd/typesem.d
Labels: Easy Review, Refactoring, auto-merge

#11802 dtoh: Re-add rudimentary support for C++98 compatible enums
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  test/compilable/dtoh_enum_cpp98.d
Labels: auto-merge, dtoh

#11465 Preview: in-contract expressions are required to be a superset of the parent incondition, instead of being implicitly either-or.
  changelog/inclusive-incontracts.dd
  src/dmd/cli.d
  src/dmd/frontend.h
  src/dmd/func.d
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/semantic3.d
  test/compilable/previewhelp.d
  test/runnable/inclusive_incontracts.d
Labels: auto-merge

#11822 Fix Issue 21283 - [C++] Wrong mangling for ref of parameter pack
  src/dmd/cppmangle.d
  test/runnable_cxx/externmangle.d
  test/runnable_cxx/extra-files/externmangle.cpp
Labels: Bug Fix, auto-merge

#11826 dtoh: Don't generate default constructors for unions
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_StructDeclaration.d
  test/dshell/extra-files/cpp_header_gen/library.d
Labels: auto-merge

#11825 build.d: Don't needlessly rebuilt cxx-headers
  src/build.d
Labels: auto-merge

#11829 Issue 21295: Add test for symbol lookup/resolve in compilation broken
  test/fail_compilation/imports/issue21295ast_node.d
  test/fail_compilation/imports/issue21295astcodegen.d
  test/fail_compilation/imports/issue21295dtemplate.d
  test/fail_compilation/imports/issue21295visitor.d
  test/fail_compilation/issue21295.d
Labels: auto-merge

#11827 [REG 2.095] Fix build regression when compiling dmd using separate compilation
  src/dmd/aliasthis.d
  src/dmd/canthrow.d
  src/dmd/dcast.d
  src/dmd/dsymbol.d
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/initsem.d
  src/dmd/opover.d
  src/dmd/statementsem.d
  src/dmd/typesem.d
Labels: Blocking Other Work, Bug Fix, GDC, Regression, auto-merge

#11805 build.d: Add `test` target to run the test suite
  src/build.d
Labels: auto-merge

#11842 Github CI: Replace set-env with environment file
  .github/workflows/runnable_cxx.yml
Labels: Bug Fix, auto-merge

#11843 Fix Issue 21293 - dtoh: segfault when encountering opaque enum
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  test/compilable/dtoh_enum.d
  test/compilable/dtoh_enum_cpp98.d
  test/compilable/dtoh_verbose.d
Labels: Bug Fix, dtoh

#11844 dtoh: Refactor ignored... comments into a function
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_verbose.d
  test/compilable/test21217.d
Labels: Refactoring, auto-merge, dtoh

#11847 refactor dtemplate a bit
  src/dmd/dtemplate.d
Labels: Easy Review, Refactoring, Trivial, auto-merge

#11851 convert LINK and other enums to ubyte
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/tests/cxxfrontend.c
Labels: Easy Review, Refactoring, auto-merge

#11830 [dmd-cxx] Fix case codes to match isVectorTypeSupported
  src/mtype.c
Labels: C++ Port, Easy Review, GDC, auto-merge

#11831 [dmd-cxx] fix Issue 21295: Add test for symbol lookup/resolve in compilation broken
  src/declaration.c
  test/fail_compilation/fail21001.d
  test/fail_compilation/imports/fail21001b.d
  test/fail_compilation/imports/issue21295ast_node.d
  test/fail_compilation/imports/issue21295astcodegen.d
  test/fail_compilation/imports/issue21295dtemplate.d
  test/fail_compilation/imports/issue21295visitor.d
  test/fail_compilation/issue21295.d
Labels: C++ Port, Easy Review, GDC

#11862 refactor aliasSemantic()
  src/dmd/dsymbolsem.d
Labels: Easy Review, Refactoring, auto-merge

#11861 convert PINLINE to ubyte
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
Labels: Easy Review, Refactoring, auto-merge

#11860 convert LINK to ubyte
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/tests/cxxfrontend.c
Labels: Easy Review, Refactoring, auto-merge

#11795 Revise Azure CI scripts
  .azure-pipelines/windows-msbuild.bat
  .azure-pipelines/windows-visual-studio.sh
  .azure-pipelines/windows-visual-studio.yml
  .azure-pipelines/windows.sh
  .azure-pipelines/windows.yml
  azure-pipelines.yml
  src/win32.mak
  src/win64.mak
  test/run.d
  test/tools/d_do_test.d
Labels: auto-merge

#11855 Add a README to the src directory
  src/README.md
  test/README.md
Labels: auto-merge, documentation

#11853 build.d: Properly use -fPIC based on MODEL and PIC variables
  src/build.d
Labels: Build System, auto-merge

#11865 Azure CI: Bump LDC host compiler version
  azure-pipelines.yml
Labels: auto-merge

#11867 [dmd-cxx] Fix Issue 21299: Undefined reference to dmd.root.stringtable.StringValue!(Type).lstring()
  src/dtemplate.c
  test/compilable/imports/test21299/func.d
  test/compilable/imports/test21299/mtype.d
  test/compilable/imports/test21299/rootstringtable.d
  test/compilable/test21299a.d
  test/compilable/test21299b.d
  test/compilable/test21299c.d
Labels: C++ Port, Easy Review, GDC

#11858 convert CPPMANGLE to ubyte
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
Labels: Easy Review, Refactoring, auto-merge-squash

#11870 dtoh: Use NULL when generating headers for c++98
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  test/compilable/dtoh_StructDeclaration.d
  test/compilable/dtoh_cpp98_compat.d
Labels: auto-merge

#11836 Fix issue 21234: Import expression can read files outside of -J path in case of symlink/hardlink
  src/dmd/root/filename.d
  test/runnable/test21234.sh
Labels: Bug Fix, auto-merge

#11871 dtoh: Implement visit method for TypeNull types
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_VarDeclaration.d
  test/compilable/dtoh_cpp98_compat.d
Labels: auto-merge

#11841 Fix 8044 - Print name of enum passed a tmpl param
  src/dmd/hdrgen.d
  test/fail_compilation/b6227.d
  test/fail_compilation/diag12380.d
  test/fail_compilation/diag8044.d
  test/fail_compilation/fail17602.d
  test/fail_compilation/fail5435.d
Labels: Diagnostic Messages, Enhancement, auto-merge

#11839 Fix 20916 - Print trace for deprecations triggered inside templates
  changelog/deprecation-context.dd
  src/dmd/aliasthis.d
  src/dmd/dsymbol.d
  src/dmd/dtemplate.d
  src/dmd/frontend.h
  src/dmd/template.h
  test/compilable/diag20916.d
  test/fail_compilation/deprecations.d
  test/fail_compilation/ice11822.d
Labels: Bug Fix, Diagnostic Messages, auto-merge

#11804 Fix 21218 - protection attributes should be emitted to C++ headers
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_TemplateDeclaration.d
  test/compilable/dtoh_protection.d
  test/compilable/dtoh_verbose.d
  test/compilable/test21217.d
Labels: Bug Fix, auto-merge, dtoh

#11869 refactor cppmanglewin to use slices, extern(D) and identifiers
  src/dmd/cppmanglewin.d
Labels: Refactoring, auto-merge

#11796 Sort fields of VarDeclaration by descending alignment
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/frontend.h
Labels: auto-merge

#11875 Fix 20604 - [ICE] dtoh ICE with nested template structs
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_TemplateDeclaration.d
Labels: Bug Fix, auto-merge

#11878 Fix 20970 - Use a longer retry for curl on Windows
  .azure-pipelines/lib.sh
Labels: Bug Fix, auto-merge

#11877 dtoh: Handle typeof(...) in template declarations
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_TemplateDeclaration.d
Labels: auto-merge, dtoh

#11879 fix Issue 21320 - @live mistakes borrowed pointer for owner in parameter
  src/dmd/ob.d
  test/fail_compilation/fob2.d
Labels: Bug Fix, auto-merge

#11874 Fix Issue 21299: Undefined reference to dmd.root.stringtable.StringValue!(Type).lstring()
  src/dmd/dsymbolsem.d
Labels: Bug Fix, Easy Review

#11876 dtoh: Remove isBuildingCompiler and related code
  src/dmd/dtoh.d
  src/dmd/frontend.h
Labels: auto-merge, dtoh

#11880 dtoh: Emit templated function declarations
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_TemplateDeclaration.d
  test/compilable/dtoh_verbose.d
Labels: auto-merge, dtoh

#11845 merge stable
  VERSION
  src/dmd/cppmangle.d
  src/dmd/dsymbolsem.d
  src/dmd/statementsem.d
  test/compilable/test21282.d
  test/fail_compilation/b15909.d
  test/runnable_cxx/externmangle.d
  test/runnable_cxx/extra-files/externmangle.cpp
Labels: Bug Fix, auto-merge

#11872 dtoh: Emit placeholders for skipped virtual functions
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_AnonDeclaration.d
  test/compilable/dtoh_ClassDeclaration.d
  test/compilable/dtoh_verbose.d
  test/dshell/extra-files/cpp_header_gen/app.cpp
  test/dshell/extra-files/cpp_header_gen/library.d
Labels: Bug Fix, auto-merge, dtoh

#11857 more enums to ubyte's
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/astbase.d
  src/dmd/cond.d
  src/dmd/dclass.d
  src/dmd/dsymbol.d
  src/dmd/frontend.h
  src/tests/cxxfrontend.c
Labels: Easy Review, Refactoring, auto-merge

#11883 dtoh: Remove special handling for templated struct declarations
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_TemplateDeclaration.d
Labels: auto-merge, dtoh

#11886 merge stable
  .github/workflows/runnable_cxx.yml
  VERSION
  src/dmd/dsymbolsem.d
  test/compilable/imports/test21299/func.d
  test/compilable/imports/test21299/mtype.d
  test/compilable/imports/test21299/rootstringtable.d
  test/compilable/test21299a.d
  test/compilable/test21299b.d
  test/compilable/test21299c.d
  test/tools/d_do_test.d
Labels: Bug Fix, auto-merge

#11885 dtoh: Mark final classes as final
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_ClassDeclaration.d
Labels: auto-merge

#11887 dtoh: Fully print identifier chains
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  test/compilable/dtoh_TemplateDeclaration.d
Labels: auto-merge

#11868 Cirrus CI: Prepare for druntime/Phobos CI
  .cirrus.yml
  ci.sh
  cirrusci.sh
  semaphoreci.sh
Labels: Blocking Other Work, auto-merge

#11888 Fix Issue 21330 - __traits(getUnitTests) should include unittests fro…
  src/dmd/traits.d
  test/compilable/test21330.d
Labels: Bug Fix, auto-merge

#11889 Fix Issue 20324 - Calling __traits(getUnitTests) on a template causes…
  src/dmd/traits.d
  test/fail_compilation/test19176.d
  test/fail_compilation/test20324.d
Labels: Bug Fix, auto-merge

#11890 Add more highlighting to some parser error messages
  src/dmd/parse.d
  test/fail_compilation/b20780.d
  test/fail_compilation/diag_debug_conditional.d
  test/fail_compilation/diag_template_alias.d
  test/fail_compilation/diag_template_this.d
  test/fail_compilation/fail246.d
  test/fail_compilation/fail247.d
  test/fail_compilation/ice11967.d
Labels: Diagnostic Messages, Trivial, auto-merge

#11891 Refactor attributes parsing (Parser.parseAttribute)
  src/dmd/parse.d
  test/fail_compilation/b20780.d
  test/fail_compilation/ice11967.d
Labels: Diagnostic Messages, Trivial, auto-merge

#11819 Fix Issue 21285 - Delegate covariance broken between 2.092 and 2.094 (git master).
  src/dmd/expressionsem.d
  test/compilable/b21285.d
Labels: Bug Fix, auto-merge

#11894 run.d: Print up-to-date messages only in verbose mode
  test/run.d
Labels: auto-merge

#11892 aggregrate.h: Remove outer struct for enum ClassKind
  src/dmd/aggregate.h
Labels: auto-merge

#11898 Revert "Merge pull request #11381 from andralex/pool"
  src/dmd/dimport.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/mtype.d
  src/dmd/root/rmem.d
  src/dmd/semantic3.d
  src/dmd/statement.d
  src/dmd/statementsem.d
  src/dmd/target.d
Labels: auto-merge

#11863 implement `__traits(getCppNamespaces, symbol)`
  changelog/traits-getcppnamespaces.dd
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/traits.d
  test/compilable/traits.d
  test/fail_compilation/traits.d
Labels: 72h no objection -> merge

#11899 Follow up on #11869 cleanup cppmanglewin.d refactor
  src/dmd/cppmanglewin.d
Labels: auto-merge

#11901 [dmd-cxx] Issue 21299: Add regression test for another undefined reference issue
  test/compilable/test21299d.d
Labels: C++ Port, Easy Review, GDC, auto-merge

#11893 dtoh: Emit template aliases as templated using declaration
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_AliasDeclaration.d
  test/compilable/dtoh_AliasDeclaration_98.d
  test/compilable/dtoh_TemplateDeclaration.d
  test/dshell/extra-files/cpp_header_gen/app.cpp
  test/dshell/extra-files/cpp_header_gen/library.d
Labels: auto-merge

#11902 [dmd-cxx] Use run-time allocated mutexes for plain `synchronized` statements
  src/idgen.c
  src/statementsem.c
  src/target.c
  src/target.h
Labels: C++ Port, GDC, auto-merge

#11903 dtoh: Add more tests to increase coverage
  test/compilable/dtoh_ClassDeclaration.d
  test/compilable/dtoh_StructDeclaration.d
  test/compilable/dtoh_VarDeclaration.d
  test/compilable/dtoh_cpp98_compat.d
  test/compilable/dtoh_enum.d
  test/compilable/dtoh_functions.d
  test/compilable/dtoh_verbose.d
Labels: Trivial, auto-merge, dtoh

#11900 [NFC] Cpp mangle use early returns and reduce indentation
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
Labels: Easy Review, Refactoring, Trivial, auto-merge

#11832 refactor parseDeclarator()
  src/dmd/parse.d
Labels: Easy Review, Refactoring, auto-merge

#11904 reduce indenting in parseLinkage
  src/dmd/parse.d
Labels: Easy Review, Refactoring, Trivial, auto-merge

#11906 dtoh: Don't use enum namespaces as types
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_enum.d
  test/compilable/dtoh_enum_cpp98.d
Labels: Bug Fix, auto-merge

#11908 dtoh: Always emit structs/classes definitions before accessing members
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_functions.d
Labels: auto-merge

#11823 Added offset to the token location
  dub.sdl
  src/dmd/globals.d
  src/dmd/lexer.d
  test/tools/unit_test_runner.d
  test/unit/lexer/location_offset.d
Labels: 72h no objection -> merge

#11882 dtoh: Emit _d_dynamicArray template which represents slices
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_21217.d
  test/compilable/dtoh_AliasDeclaration.d
  test/compilable/dtoh_AliasDeclaration_98.d
  test/compilable/dtoh_AnonDeclaration.d
  test/compilable/dtoh_CPPNamespaceDeclaration.d
  test/compilable/dtoh_ClassDeclaration.d
  test/compilable/dtoh_StructDeclaration.d
  test/compilable/dtoh_TemplateDeclaration.d
  test/compilable/dtoh_VarDeclaration.d
  test/compilable/dtoh_cpp98_compat.d
  test/compilable/dtoh_enum.d
  test/compilable/dtoh_enum_cpp98.d
  test/compilable/dtoh_extern_type.d
  test/compilable/dtoh_functions.d
  test/compilable/dtoh_protection.d
  test/compilable/dtoh_unittest_block.d
  test/compilable/dtoh_verbose.d
  test/dshell/extra-files/cpp_header_gen/app.cpp
Labels: auto-merge, dtoh

#11909 readme: dmd: fix typo wiht -> with
  src/dmd/README.md
Labels: Trivial, auto-merge

#11913 __traits(getCppNamespace,...) returns duplicate names for templates
  src/dmd/traits.d
  test/compilable/traits.d
Labels: Easy Review, Trivial, auto-merge

#11912 semantic: avoid runtime _d_arraysetlength call when .length = 0
  .circleci/run.sh
  src/dmd/expressionsem.d
  test/compilable/extra-files/vcg-ast-arraylength-postscript.sh
  test/compilable/vcg-ast-arraylength.d
Labels: auto-merge

#11914 Added location to ConditionalDeclaration and StaticIfDeclaration
  src/dmd/astbase.d
  src/dmd/attrib.d
  src/dmd/parse.d
  test/unit/parser/conditionalcompilation_location.d
Labels: auto-merge
