Repository dlang/dmd, pull requests merged in 2020-06, with the labels that each got.

#11140 add scope varargs support to ob
  src/dmd/ob.d
  test/fail_compilation/fob2.d
Labels: Enhancement, auto-merge

#11204 [dmd-cxx] posix.mak: Update C++ baseline support to C++11
  src/backend/cg87.c
  src/backend/cgen.c
  src/backend/cod1.c
  src/backend/cod3.c
  src/backend/cod4.c
  src/backend/code.h
  src/backend/go.c
  src/backend/go.h
  src/backend/iasm.h
  src/backend/machobj.c
  src/backend/ptrntab.c
  src/iasmdmd.c
  src/posix.mak
Labels: C++ Port

#11207 fix issue 20890 - parameter corruption when other parameter is a stat…
  src/dmd/backend/cod1.d
  test/runnable/b20890.d
Labels: Bug Fix, auto-merge

#11206 Make tests pass on single-digit days of month
  test/fail_compilation/fail7524a.d
Labels: Trivial, auto-merge

#11209 fix issue 20824 - error messages generated by dmd build script can be…
  src/build.d
Labels: Bug Fix, auto-merge

#11210 De-virtualize toBasetype() so it is inlineable
  src/dmd/mtype.d
  src/dmd/mtype.h
Labels: Easy Review, Refactoring, auto-merge

#11205 Fix tag generation on posix
  posix.mak
Labels: auto-merge

#11178 Port runnable/paranoia.sh to D
  test/compilable/paranoia_ctfe.d
  test/runnable/paranoia.d
  test/runnable/paranoia.sh
  test/tools/d_do_test.d
Labels: auto-merge

#11211 Fix Issue 20894 - ICE: passing a member template mixin identifier as …
  src/dmd/dtemplate.d
  test/compilable/test20894.d
Labels: Bug Fix, auto-merge

#11216 Github CI: Update action name
  .github/workflows/runnable_cxx.yml
Labels: Trivial, auto-merge

#11220 C++: Remove duplication of 'All Rights Reserved'
  src/dmd/root/array.h
  src/dmd/root/bitarray.h
  src/dmd/root/ctfloat.h
  src/dmd/root/file.h
  src/dmd/root/filename.h
  src/dmd/root/longdouble.h
  src/dmd/root/object.h
  src/dmd/root/outbuffer.h
  src/dmd/root/port.h
  src/dmd/root/rmem.h
  src/dmd/root/root.h
Labels: Trivial, auto-merge

#11218 Fix a few minor discrepancies in C++ headers
  src/dmd/module.h
  src/dmd/mtype.h
  src/dmd/parsetimevisitor.d
  src/dmd/strictvisitor.d
  src/dmd/transitivevisitor.d
  src/dmd/visitor.h
Labels: Easy Review, auto-merge

#11223 merge stable
  VERSION
  src/dmd/attrib.d
  src/dmd/backend/cod1.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/parse.d
  src/dmd/traits.d
  src/dmd/typesem.d
  test/compilable/b20758.d
  test/compilable/b20885.d
  test/compilable/imports/test19344.d
  test/compilable/issue12520.d
  test/compilable/test19728.d
  test/compilable/test20744.d
  test/compilable/test20835.d
  test/compilable/test20894.d
  test/compilable/traits.d
  test/fail_compilation/b20875.d
  test/fail_compilation/cpp_abi_tag.d
  test/fail_compilation/fail124.d
  test/fail_compilation/test20626.d
  test/runnable/b20890.d
Labels: Enhancement, auto-merge

#11229 [dmd-cxx] Backport removal of unused parameter from include()
  src/attrib.c
  src/attrib.h
  src/canthrow.c
  src/cond.c
  src/cond.h
  src/doc.c
  src/dscope.c
  src/dsymbol.c
  src/e2ir.c
  src/expressionsem.c
  src/inline.c
  src/json.c
  src/scope.h
  src/statement.c
  src/statementsem.c
  src/toobj.c
  src/traits.c
Labels: C++ Port, GDC, auto-merge

#11208 add -vtemplates switch to print template instantiation statistics
  changelog/vtemplates.dd
  src/dmd/cli.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/mars.d
  test/compilable/vtemplates.d
Labels: Diagnostic Messages, auto-merge

#11228 [dmd-cxx] Sync target.h layout and global variable from upstream
  src/attrib.c
  src/constfold.c
  src/cppmangle.c
  src/dclass.c
  src/declaration.c
  src/dmangle.c
  src/dstruct.c
  src/e2ir.c
  src/expression.c
  src/expressionsem.c
  src/func.c
  src/hdrgen.c
  src/iasmdmd.c
  src/mars.c
  src/mtype.c
  src/mtype.h
  src/s2ir.c
  src/safe.c
  src/statementsem.c
  src/target.c
  src/target.h
  src/tocsym.c
  src/tocvdebug.c
  src/todt.c
  src/toir.c
  src/toobj.c
Labels: C++ Port, GDC, auto-merge

#11231 [dmd-cxx] Backport CHECKENABLE enum from upstream
  src/e2ir.c
  src/expressionsem.c
  src/func.c
  src/globals.h
  src/irstate.c
  src/mars.c
  src/statementsem.c
Labels: C++ Port, GDC, auto-merge

#11230 fix Issue 20893 - [REG 2.087] 32-bit arithmetic goes wrong
  src/dmd/backend/cod2.d
  test/runnable/test20893.d
Labels: Bug Fix, Regression, auto-merge, stable-priority

#11232 [dmd-cxx] Backport conversion of versionids and debugids to Identifiers
  src/cond.c
  src/cond.h
  src/dversion.c
  src/globals.h
  src/mars.c
  src/module.h
Labels: C++ Port, GDC, auto-merge

#11235 Fix 20410 - ReplaceTypeUnless replaces enums with their basetype
  src/dmd/dtemplate.d
  test/compilable/test20410.d
Labels: Bug Fix, auto-merge

#11240 dcompat.h: Don't segfault when initializing DStrings with a NULL pointer and fix DMC compatibility
  src/dmd/root/dcompat.h
  src/tests/cxxfrontend.c
Labels: Easy Review, auto-merge

#11233 dscope: remove unused constructor
  src/dmd/dscope.d
Labels: auto-merge

#11241 Small type mismatch in loop variable
  src/dmd/backend/out.d
Labels: auto-merge

#11239 allow initialization of shared variables
  changelog/shared-init.dd
  src/dmd/expressionsem.d
  test/fail_compilation/nosharedaccess.d
Labels: auto-merge

#11243 refactor iasmdmd.asm_emit
  src/dmd/iasmdmd.d
Labels: auto-merge

#11234 [dmd-cxx] Backport DString global params from upstream master
  src/attrib.c
  src/backend/dwarf.c
  src/cond.c
  src/dimport.c
  src/dmodule.c
  src/expressionsem.c
  src/globals.h
  src/glue.c
  src/lexer.c
  src/libelf.c
  src/libmach.c
  src/libmscoff.c
  src/libomf.c
  src/link.c
  src/mars.c
  src/msc.c
  src/root/dcompat.h
Labels: C++ Port, GDC, auto-merge

#11244 fix Issue 20903 - seg fault on long signed divide overflow
  src/dmd/backend/evalu8.d
  test/fail_compilation/test20903.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#11246 [dmd-cxx] Remove async read interface
  src/mars.c
  src/posix.mak
  src/root/async.c
  src/root/async.h
  src/win32.mak
Labels: C++ Port, auto-merge

#11092 Add dmd as a lib callbacks for statement semantic
  dub.sdl
  src/dmd/compiler.d
  src/dmd/mars.d
  src/dmd/statementsem.d
  test/dub_package/retrieveScope.d
  test/dub_package/testfiles/correct.d
Labels: auto-merge-squash

#11245 [dmd-cxx] Convert some global and param fields from pointers to value types
  src/dmodule.c
  src/doc.c
  src/globals.h
  src/libelf.c
  src/libmach.c
  src/libmscoff.c
  src/libomf.c
  src/link.c
  src/mars.c
  src/toobj.c
Labels: C++ Port, GDC, auto-merge

#11226 [dmd-cxx] Backport struct ParameterList from upstream master
  src/arrayop.c
  src/clone.c
  src/cond.c
  src/cppmangle.c
  src/cppmanglewin.c
  src/dcast.c
  src/dclass.c
  src/declaration.h
  src/delegatize.c
  src/dinterpret.c
  src/dmangle.c
  src/doc.c
  src/dstruct.c
  src/dtemplate.c
  src/e2ir.c
  src/escape.c
  src/expression.c
  src/expressionsem.c
  src/func.c
  src/glue.c
  src/hdrgen.c
  src/hdrgen.h
  src/initsem.c
  src/inline.c
  src/json.c
  src/mtype.c
  src/mtype.h
  src/opover.c
  src/optimize.c
  src/parse.c
  src/parse.h
  src/statementsem.c
  src/target.c
  src/tocsym.c
  src/toctype.c
  src/toobj.c
  src/traits.c
Labels: C++ Port, GDC, auto-merge

#11247 [dmd-cxx] Rename OutBuffer peekString/extractString to peekChars/extractChars
  src/arrayop.c
  src/attrib.c
  src/cppmangle.c
  src/cppmanglewin.c
  src/declaration.c
  src/dmangle.c
  src/dmodule.c
  src/doc.c
  src/dscope.c
  src/dtemplate.c
  src/dversion.c
  src/errors.c
  src/expression.c
  src/expressionsem.c
  src/func.c
  src/globals.c
  src/glue.c
  src/hdrgen.c
  src/identifier.c
  src/inifile.c
  src/init.c
  src/link.c
  src/mtype.c
  src/parse.c
  src/root/filename.c
  src/root/outbuffer.c
  src/root/outbuffer.h
  src/statement.c
  src/tocsym.c
  src/toir.c
  src/tokens.c
  src/toobj.c
Labels: C++ Port, GDC, auto-merge

#11248 [dmd-cxx] Rename enum PROTKIND to Prot::Kind
  src/access.c
  src/arrayop.c
  src/attrib.c
  src/cppmanglewin.c
  src/dclass.c
  src/declaration.c
  src/denum.c
  src/dimport.c
  src/dmodule.c
  src/doc.c
  src/dscope.c
  src/dstruct.c
  src/dsymbol.c
  src/dsymbol.h
  src/dtemplate.c
  src/expressionsem.c
  src/func.c
  src/hdrgen.c
  src/json.c
  src/mtype.c
  src/nspace.c
  src/parse.c
  src/tocvdebug.c
Labels: C++ Port, GDC, auto-merge

#11249 [dmd-cxx] Merge AndAndExp and OrOrExp into LogicalExp
  src/dinterpret.c
  src/e2ir.c
  src/expression.c
  src/expression.h
  src/expressionsem.c
  src/inline.c
  src/opover.c
  src/optimize.c
  src/parse.c
  src/sideeffect.c
  src/staticcond.c
  src/visitor.h
Labels: C++ Port, GDC

#11251 shrink some scopes in asm_make_modrm_byte
  src/dmd/iasmdmd.d
Labels: auto-merge

#11225 Fix Issue 20710 - ICE when statically accessing struct member contain…
  src/dmd/dinterpret.d
  test/compilable/test20710.d
Labels: Bug Fix, Enhancement, auto-merge

#11224 [dmd-cxx] Miscellaneous API changes in upstream dmd master
  src/access.c
  src/aggregate.h
  src/ast_node.h
  src/cond.h
  src/cppmanglewin.c
  src/ctfeexpr.c
  src/dclass.c
  src/declaration.h
  src/dmangle.c
  src/dsymbol.h
  src/errors.c
  src/expression.c
  src/expression.h
  src/globals.c
  src/globals.h
  src/init.h
  src/mars.c
  src/mtype.c
  src/mtype.h
  src/root/port.c
  src/root/port.h
  src/statement.h
  src/template.h
  src/todt.c
  src/toobj.c
  src/utf.c
Labels: C++ Port, Easy Review, auto-merge

#11254 expression.h: Add Expression::isClassReferenceExp
  src/dmd/expression.h
Labels: Trivial, auto-merge

#11227 target: Rename va_list field to tvalist
  src/dmd/target.d
  src/dmd/target.h
Labels: Refactoring, auto-merge

#11256 Fix Issue 20919 - DMD crash when '__traits' prints error involving a …
  src/dmd/hdrgen.d
  test/fail_compilation/test20919.d
Labels: Bug Fix, auto-merge

#10945 fix Issue 20183 - Assigning statement scope of struct literal or temp…
  src/dmd/escape.d
  test/fail_compilation/fail20183.d
  test/fail_compilation/retscope.d
Labels: Bug Fix

#11213 gloop.d: recycle instead of free arrays
  src/dmd/backend/gloop.d
Labels: Refactoring, auto-merge

#11202 gother.d: Elemdata's from linked list to Rarray
  src/dmd/backend/gloop.d
  src/dmd/backend/go.d
  src/dmd/backend/goh.d
  src/dmd/backend/gother.d
Labels: Refactoring, auto-merge

#11261 Remove FUNDING.yml
  .github/FUNDING.yml
Labels: Trivial, auto-merge

#11260 fix issue 20915 - exclude version and debug identifier from `__traits(allMembers)` results
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/dversion.d
  src/dmd/traits.d
  test/compilable/issue20915.d
Labels: Bug Fix, auto-merge

#10967 recognize assigning .init of all zeros, replace with memset
  src/dmd/e2ir.d
Labels: auto-merge

#11262 split off refactoring from PR 20691
  src/dmd/expressionsem.d
Labels: Refactoring, auto-merge

#11189 [build.d]: Remove outdated comments
  src/build.d
Labels: Build System, auto-merge

#11263 merge stable
  VERSION
  src/dmd/backend/cod2.d
  src/dmd/dinterpret.d
  src/dmd/hdrgen.d
  test/compilable/test20710.d
  test/fail_compilation/test20919.d
  test/runnable/test20893.d
Labels: Bug Fix, auto-merge

#11264 Fix Issue 20923 - Redefinition of 'size_t' is affecting TypeStruct fu…
  src/dmd/clone.d
  test/compilable/test20923.d
Labels: Bug Fix, auto-merge

#11270 change seg_count to seg_length
  src/dmd/backend/cgobj.d
  src/dmd/backend/mscoffobj.d
Labels: Refactoring, auto-merge

#11267 Add workaround for the invalid "lhs internal pointer" error
  test/run.d
Labels: auto-merge

#11278 Copy res/ to src/dmd/res
  src/dmd/res/default_ddoc_theme.ddoc
Labels: Trivial, auto-merge

#11274 change seg_count to seg_length part 2
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/machobj.d
Labels: Refactoring, auto-merge

#11280 toobj.d: Use isTypeClass in visitClassReference
  src/dmd/todt.d
Labels: 72h no objection -> merge, Refactoring

#11269 move res/ subdirectory to src/dmd/res/
  ci.sh
  dub.sdl
  res/default_ddoc_theme.ddoc
  src/build.d
  src/vcbuild/dmd.vcxproj
  test/tools/unit_test_runner.d
Labels: auto-merge

#11275 cgobj.d: replace array with Rarray
  src/dmd/backend/cgobj.d
Labels: Refactoring, auto-merge

#11252 fix Issue 20906 - unnecessary divide-by-zero errors when constant fol…
  src/dmd/backend/cgelem.d
  test/compilable/quadratic.d
  test/compilable/test20906.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#11276 mscoffobj.d: replace array with Rarray
  src/dmd/backend/mscoffobj.d
Labels: Refactoring, auto-merge

#11285 [dmd-cxx] Rename OnScopeStatement to ScopeGuardStatement
  src/blockexit.c
  src/clone.c
  src/dinterpret.c
  src/func.c
  src/hdrgen.c
  src/parse.c
  src/s2ir.c
  src/sapply.c
  src/scope.h
  src/statement.c
  src/statement.h
  src/statementsem.c
  src/visitor.h
Labels: C++ Port, GDC, auto-merge

#11281 cgobj.d: change ledatas to Rarray
  src/dmd/backend/cgobj.d
Labels: Refactoring

#11282 elfobj.d: use Rarray for SegData
  src/dmd/backend/elfobj.d
Labels: Refactoring

#11283 machobj.d: use Rarray for SegData
  src/dmd/backend/machobj.d
Labels: Refactoring

#11284 Fix Issue 20831 - __traits(getAttributes) failes to compile when used…
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/dtoh.d
  src/dmd/parse.d
  src/dmd/typesem.d
  test/runnable/uda.d
Labels: Bug Fix, auto-merge

#11288 partially revert #10891, split Outbuffer.reserve() into hot and cold paths for better performance
  src/dmd/backend/outbuf.d
Labels: Refactoring, auto-merge

#11286 fix issue 20709 - Segmentation fault when importing nonexistent type
  src/dmd/func.d
  test/fail_compilation/ice20709.d
  test/fail_compilation/imports/imp20709.d
Labels: Bug Fix, auto-merge

#11291 convert linreclist to Barray
  src/dmd/backend/cgobj.d
Labels: Refactoring

#11290 convert SDlinnum_data to Barray
  src/dmd/backend/code.d
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/machobj.d
  src/dmd/backend/mscoffobj.d
Labels: Refactoring

#11289 change linoff to Barray
  src/dmd/backend/code.d
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/machobj.d
Labels: Refactoring

#11287 finish SegData
  src/dmd/backend/cgobj.d
  src/dmd/backend/code.d
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/machobj.d
  src/dmd/backend/mscoffobj.d
Labels: Refactoring

#11295 Fix Issue 20833 - Template members prevent __traits(getOverloads) from working properly
  src/dmd/traits.d
  test/compilable/b20833.d
Labels: Bug Fix, auto-merge

#11293 dmd.root.filename: Fix FileName.canonicalPath() regression on Windows
  src/dmd/root/filename.d
Labels: Regression, auto-merge

#11298 memoize seg numbers with getsegment2()
  src/dmd/backend/machobj.d
Labels: Refactoring, auto-merge

#11299 use getsegment2() in dwarfdbginf.d
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/machobj.d
Labels: Refactoring

#11296 change obj.linnum_list to Barray
  src/dmd/backend/cgobj.d
Labels: Refactoring

#11301 switch Linnum.data to Outbuffer
  src/dmd/backend/cgobj.d
Labels: Refactoring, auto-merge

#11292 Fix issue 20938 - Cannot create const arrays mixing immutable and mutable structs with indirections
  changelog/array-literal-inference.dd
  src/dmd/expressionsem.d
  test/compilable/b20938.d
  test/fail_compilation/ice13024.d
Labels: Bug Fix, auto-merge

#11302 [dmd-cxx] Synchronize root/outbuffer.h interface with dmd master
  src/dcast.c
  src/dmacro.c
  src/dmangle.c
  src/dmodule.c
  src/doc.c
  src/dsymbol.h
  src/expression.c
  src/glue.c
  src/hdrgen.c
  src/inifile.c
  src/json.c
  src/lexer.c
  src/libelf.c
  src/libmach.c
  src/libmscoff.c
  src/libomf.c
  src/link.c
  src/macro.h
  src/mars.c
  src/mtype.c
  src/root/filename.c
  src/root/outbuffer.c
  src/root/outbuffer.h
Labels: C++ Port, GDC, Refactoring, auto-merge

#11277 toobj.d: Remove dead error message in overload shadowing detection
  src/dmd/toobj.d
Labels: Refactoring, auto-merge

#11310 [stable] Add some missing methods to C++ headers
  src/dmd/mtype.h
  src/dmd/version.h
Labels: auto-merge

#11212 Get rid of obsolete __ArrayEq lowering
  src/dmd/dcast.d
  src/dmd/expressionsem.d
  src/dmd/id.d
  src/dmd/mtype.h
  src/dmd/opover.d
Labels: auto-merge

#11311 fix memory leak with FIXUPs
  src/dmd/backend/cgobj.d
Labels: Refactoring

#11312 dwarfdbginf.d: fix memory leak
  src/dmd/backend/dwarfdbginf.d
Labels: Easy Review, Refactoring

#11308 change reset_symbols to Barray
  src/dmd/backend/cc.d
  src/dmd/backend/cgobj.d
  src/dmd/backend/symbol.d
Labels: Refactoring

#11307 change ptrref_buf to Barray
  src/dmd/backend/cgobj.d
Labels: Easy Review, Refactoring

#11313 dwarfdbginf.d: reset_symbuf to Barray
  src/dmd/backend/barray.d
  src/dmd/backend/dwarfdbginf.d
Labels: Easy Review, Refactoring, auto-merge

#11314 [dmd-cxx] Fix regression caused from backporting semantic visitor conversion
  src/expressionsem.c
Labels: C++ Port, Easy Review, GDC, auto-merge

#11309 C++: Use enum class for CPU type definition
  src/build.d
  src/dmd/globals.h
  src/tests/cxxfrontend.c
Labels: Easy Review, auto-merge

#11318 Array.opIndex checking only for debug builds
  src/dmd/root/array.d
Labels: Refactoring, auto-merge

#11316 aarray.d: use DMD's better hash function
  src/dmd/backend/aarray.d
Labels: Refactoring, auto-merge

#11315 [dmd-cxx] Backport documentation, refactor, and self-assign fixes in mergeFieldInit.
  src/dscope.c
Labels: C++ Port, GDC, auto-merge

#11317 merge stable
  VERSION
  src/dmd/clone.d
  src/dmd/func.d
  src/dmd/mtype.h
  src/dmd/root/filename.d
  src/dmd/traits.d
  src/dmd/version.h
  test/compilable/b20833.d
  test/compilable/test20923.d
  test/fail_compilation/ice20709.d
  test/fail_compilation/imports/imp20709.d
Labels: Bug Fix, auto-merge

#11319 array.d: split enlarge() off of reserve()
  src/dmd/root/array.d
Labels: Easy Review, Refactoring, auto-merge

#11304 fix Issue 18749 - bt instruction using 64-bit register for 32-bit offset
  src/dmd/backend/cod4.d
  test/runnable/testbtst.d
Labels: Bug Fix, auto-merge

#11323 fix Issue 20958 - incomplete semantic analysis when generating code f…
  src/dmd/dstruct.d
  src/dmd/typesem.d
  test/compilable/imports/u20958.d
  test/compilable/test20958.d
Labels: Bug Fix, auto-merge

#11325 elfobj.d: SecHdrTab to Barray
  src/dmd/backend/elfobj.d
Labels: Easy Review, Refactoring, auto-merge

#11326 elfobj.d: replace section_cnt with SecHdrTab.length
  src/dmd/backend/elfobj.d
Labels: Easy Review, Refactoring, auto-merge

#11322 Azure CI OMF job: Link testsuite tools with correct phobos.lib
  .azure-pipelines/windows.sh
  test/run.d
Labels: auto-merge

#11329 dmd.root.rmem: Rename allocmemory to allocmemoryNoFree
  src/dmd/expression.d
  src/dmd/root/rmem.d
Labels: auto-merge

#11327 Symbuf
  src/dmd/backend/elfobj.d
Labels: Easy Review, Refactoring, auto-merge-squash

#11328 elfobj: look up both name index and seg index with hash
  src/dmd/backend/aarray.d
  src/dmd/backend/elfobj.d
Labels: Refactoring, auto-merge-squash

#11330 C++ headers: Add toTypeFunction() to class Type
  src/dmd/mtype.h
Labels: Easy Review, GDC, auto-merge

#11336 Fix unbalanced backticks in pragma(printf)
  src/dmd/dsymbolsem.d
  test/fail_compilation/format.d
Labels: Easy Review

#11303 static foreach over array and numeric range speed up by ~7x
  src/dmd/cond.d
Labels: Enhancement, auto-merge

#11335 [dmd-cxx] Backport static foreach optimization
  src/cond.c
Labels: auto-merge

#11334 elfobj: change resetSyms to Barray
  src/dmd/backend/elfobj.d
Labels: Refactoring

#11333 elfobj: avoid unnecessary strlen
  src/dmd/backend/elfobj.d
Labels: Easy Review, Refactoring

#11342 test: Remove empty REQUIRED_ARGS from fail_compilation tests
  test/fail_compilation/bug5.d
  test/fail_compilation/bug5b.d
  test/fail_compilation/checkimports2.d
  test/fail_compilation/diag6677.d
  test/fail_compilation/diag_cstyle.d
  test/fail_compilation/dip22a.d
  test/fail_compilation/dip22b.d
  test/fail_compilation/dip22e.d
  test/fail_compilation/fail18228.d
  test/fail_compilation/fail18719.d
  test/fail_compilation/fail18979.d
  test/fail_compilation/fail19911c.d
  test/fail_compilation/fail19922.d
  test/fail_compilation/fail19923.d
  test/fail_compilation/fail7443.d
  test/fail_compilation/fail9665a.d
  test/fail_compilation/fix19059.d
  test/fail_compilation/no_object.d
  test/fail_compilation/parseStc5.d
  test/fail_compilation/pragmas.d
  test/fail_compilation/switches.d
  test/fail_compilation/test12228.d
  test/fail_compilation/test12558.d
  test/fail_compilation/test15306.d
  test/fail_compilation/test15785b.d
  test/fail_compilation/test15925.d
  test/fail_compilation/test16095.d
  test/fail_compilation/test16365.d
  test/fail_compilation/test17284.d
  test/fail_compilation/test19107.d
  test/fail_compilation/test314.d
  test/fail_compilation/traits.d
Labels: Trivial, auto-merge

#11338 test: runnable_cxx: Use explicit instantiations of templates
  test/runnable_cxx/extra-files/abi_tags.cpp
Labels: Easy Review, auto-merge, extern (C/C++)

#11349 test: Move imports/test18868_fls.d from COMPILE_SEPARATELY to EXTRA_SOURCES
  test/runnable/test18868.d
Labels: Trivial, auto-merge

#11345 Reject AUTO_UPDATE for TEST_OUTPUT's with special sequences
  test/tools/d_do_test.d
Labels: auto-merge
