Repository dlang/dmd, pull requests merged in 2021-09, with the labels that each got.

#13026 Compile __main.d separate from regular modules
  src/dmd/mars.d
Labels: auto-merge

#13037 [stable] Cherry-pick bit-field fixes from master
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/backend/dt.d
  src/dmd/cparse.d
  src/dmd/declaration.d
  src/dmd/dstruct.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
  src/dmd/target.d
  src/dmd/target.h
  src/dmd/todt.d
  src/dmd/traits.d
  test/compilable/testcstuff2.c
  test/compilable/zerosize.d
  test/fail_compilation/bitfields1.c
  test/fail_compilation/failcstuff1.c
  test/runnable/bitfields.c
  test/runnable/bitfieldsdm.c
  test/runnable/bitfieldsms.c
  test/runnable/bitfieldsposix32.c
  test/runnable/bitfieldsposix64.c
Labels: Bug Fix, ImportC

#13038 ImportC: add implicit array and function conversions
  src/build.d
  src/dmd/README.md
  src/dmd/expressionsem.d
  src/dmd/importc.d
  test/compilable/arraytopointer.c
Labels: auto-merge, Easy Review, ImportC

#13036 fix Issue 22252 - ImportC: Array, Function parameter types should be …
  src/dmd/typesem.d
  test/compilable/fix22252.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#12712 traits: add support for CallExp when using getParameterStorageClasses
  changelog/trait-stc-callexp.md
  src/dmd/traits.d
  test/compilable/stc_traits.d
  test/fail_compilation/test17425.d
Labels: 72h no objection -> merge, Atila Neves, Walter Bright

#13043 fix Issue 22262 - importC: Error: incompatible types for '(buf) is (0)': 'ubyte*' and 'int'
  src/dmd/expressionsem.d
  test/compilable/testcstuff2.c
  test/fail_compilation/failcstuff2.c
Labels: auto-merge, Bug Fix, ImportC

#13042 ImportC: implement e->id
  src/dmd/cparse.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  test/compilable/arraytopointer.c
Labels: auto-merge, Easy Review, ImportC

#13050 ImportC add cAdjustParamType()
  src/dmd/importc.d
  src/dmd/typesem.d
Labels: auto-merge, Easy Review, Refactoring, ImportC

#13046 fix Issue 22274 - importC: [ICE]: 4 identifiers does not match 3 declarations using K&R syntax
  src/dmd/cparse.d
  test/compilable/testcstuff2.c
Labels: auto-merge, Bug Fix, ImportC

#13039 Fix Issue 22267 i.e. make ImportC accept initializer expressions sole…
  src/dmd/cparse.d
  test/compilable/issue22267.c
Labels: Bug Fix

#13052 fix Issue 22233 - importC: (identifier)() incorrectly parsed as a cas…
  src/dmd/cparse.d
  test/compilable/test22233.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13055 fix issue 22281 - unreadable quotes in the upcoming 2.099 changelog
  changelog/range-error.dd
Labels: Bug Fix

#13044 fix Issue 22264 - importC: Error: '=', ';' or ',' expected using K&R function syntax
  src/dmd/cparse.d
  test/compilable/testcstuff2.c
Labels: auto-merge, Bug Fix, ImportC

#13053 merge stable
  VERSION
  src/build.d
  src/dmd/README.md
  src/dmd/blockexit.d
  src/dmd/cparse.d
  src/dmd/dinterpret.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  src/dmd/importc.d
  src/dmd/typesem.d
  test/compilable/arraytopointer.c
  test/compilable/fix22252.c
  test/compilable/test22214.d
  test/compilable/test22224.d
  test/compilable/test22228.d
  test/compilable/testcstuff2.c
  test/fail_compilation/fail22084.d
  test/fail_compilation/fail7173.d
  test/fail_compilation/failcstuff2.c
Labels: auto-merge, Bug Fix

#13056 Fix bug 22285
  src/dmd/doc.d
  test/compilable/ddoc_markdown_tables_22285.d
  test/compilable/extra-files/ddoc_markdown_tables_22285.html
Labels: auto-merge, Bug Fix

#13051 fix Issue 22246 - ImportC: C11 does not allow _Alignof (expression)
  src/dmd/expressionsem.d
  test/compilable/alignas.c
  test/fail_compilation/test22246.c
Labels: Bug Fix, Easy Review, ImportC

#13057 Fix issue 11008 - Allow -main switch even if user-defined main function exists
  src/dmd/cli.d
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/glue.d
  src/dmd/mars.d
  test/compilable/testhelp.d
  test/runnable/testmainb.d
Labels: Enhancement, auto-merge

#13059 Fix issue 8346 - Literals 00 - 07 results in odd errors when used with UFCS
  src/dmd/lexer.d
  test/runnable/ufcs.d
Labels: auto-merge, Bug Fix

#13058 Fix issue 21431 - Incorrect maximum and actual number of cases in a switch case range is reported
  src/dmd/statementsem.d
  test/fail_compilation/fail287.d
Labels: Bug Fix

#13062 [stable] Fix some 2.098 C++ header regressions
  src/dmd/declaration.h
  src/dmd/expression.h
  src/dmd/mtype.h
  src/dmd/root/outbuffer.h
  src/dmd/tokens.h
Labels: auto-merge

#13061 Fix Issue 22205 - catch(Exception) not longer working in debug blocks
  src/dmd/statementsem.d
  test/runnable/test22205.d
Labels: Enhancement, Regression, auto-merge, Bug Fix, Easy Review

#13045 fix Issue 22250 - ImportC: Array subscripts do not comply with C stan…
  src/dmd/expressionsem.d
  src/dmd/importc.d
  src/dmd/toir.d
  test/compilable/arraytopointer.c
  test/runnable/test22070_2.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13063 modernize function semanticX()
  src/dmd/expressionsem.d
Labels: auto-merge, Easy Review, Refactoring

#13064 modernize semanticY()
  src/dmd/expressionsem.d
Labels: Easy Review, Refactoring

#13067 Slightly reduce frontend diff with LDC
  src/dmd/expression.h
  src/dmd/frontend.h
  src/dmd/iasmgcc.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/root/longdouble.d
  src/dmd/root/man.d
  src/dmd/semantic3.d
  src/dmd/typesem.d
  src/dmd/typinf.d
Labels: auto-merge

#13069 Revise static C++ create/emplace helpers
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/builtin.d
  src/dmd/dclass.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dmodule.d
  src/dmd/dstruct.d
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/frontend.h
  src/dmd/module.h
  src/dmd/statement.d
  src/dmd/statement.h
  src/dmd/template.h
  src/dmd/typinf.d
Labels: auto-merge

#13070 fix Issue 22294 - importC: enums aren.t placed in surrounding namespace
  src/dmd/cparse.d
  test/compilable/fix22294.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13065 add/improve function Ddoc comments
  src/dmd/aliasthis.d
  src/dmd/expressionsem.d
  src/dmd/typesem.d
Labels: Trivial, Easy Review, documentation

#13066 fix Issue 22253 - ImportC expressions inadvertently supporting D properties
  src/dmd/expressionsem.d
  src/dmd/importc.d
  test/fail_compilation/failcstuff2.c
  test/fail_compilation/fix22253.c
  test/runnable/test22071.c
Labels: auto-merge, Bug Fix, ImportC

#13078 fix Issue 22286 - importC: (identifier)(other_identifier) incorrectly…
  src/dmd/cparse.d
  src/dmd/expressionsem.d
  test/compilable/test22286.c
Labels: auto-merge, Bug Fix, ImportC

#13077 fix Issue 22304 - importC: parsing gnu-style attributes fails if retu…
  src/dmd/cparse.d
  test/compilable/test22304.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13081 Fix Issue 22311 - Slice .length DWARF type
  src/dmd/backend/dwarfdbginf.d
  test/runnable/gdb_slice_debuginfo_32.d
  test/runnable/gdb_slice_debuginfo_64.d
Labels: Bug Fix

#13072 fix Issue 22303 - ImportC: pragma directives should be ignored
  src/dmd/id.d
  src/dmd/lexer.d
  test/compilable/test22303.c
Labels: Bug Fix, Easy Review, ImportC

#13088 fix Issue 22313 - ImportC: account for ( ) when doing lookahead on as…
  src/dmd/cparse.d
  test/compilable/fix22313.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13086 fix Issue 22314 - ImportC: fails to parse gnu attributes on enum members
  src/dmd/cparse.d
  test/compilable/fix22314.c
Labels: Bug Fix, Easy Review, ImportC

#13092 Disable Azure Codecov for Windows
  azure-pipelines.yml
Labels: auto-merge

#13095 fix Issue 22326 - ImportC: struct with flexible array member is incor…
  src/dmd/cparse.d
  src/dmd/frontend.h
  src/dmd/initsem.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  test/fail_compilation/failcstuff1.c
  test/runnable/test22326.c
Labels: Bug Fix, ImportC

#13091 fix Issue 22322 - ImportC: struct with floating point members causes …
  src/dmd/clone.d
  test/compilable/fix22322.c
Labels: Bug Fix, ImportC

#13089 fix Issue 22275 ImportC incompatible types char* and char[1]
  src/dmd/dcast.d
  test/compilable/fix22275.c
Labels: Bug Fix, ImportC, stable-stalled

#13098 Update range-error.dd: Fix typo in code example for out-of-bounds checking of slice operations.
  changelog/range-error.dd
Labels: auto-merge

#13102 fix Issue 22312 - importC: redundant typedefs are rejected
  src/dmd/dsymbol.d
Labels: Bug Fix, Easy Review, ImportC

#13082 [stable] Tweak list of long-running runnable tests
  test/run.d
Labels: stable-stalled

#13104 Pipe output of cd to /dev/null in postscript.sh
  test/tools/postscript.sh
Labels: auto-merge

#13101 fix Issue 22321 - ImportC: non-static arrays can.t be initialized by …
  src/dmd/initsem.d
  test/runnable/test22321.c
Labels: Bug Fix, ImportC

#13108 merge stable
  VERSION
  src/dmd/clone.d
  src/dmd/cparse.d
  src/dmd/dcast.d
  src/dmd/declaration.h
  src/dmd/dsymbol.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/importc.d
  src/dmd/initsem.d
  src/dmd/lexer.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/root/outbuffer.h
  src/dmd/semantic2.d
  src/dmd/statementsem.d
  src/dmd/toir.d
  src/dmd/tokens.h
  test/compilable/alignas.c
  test/compilable/arraytopointer.c
  test/compilable/fix22275.c
  test/compilable/fix22294.c
  test/compilable/fix22313.c
  test/compilable/fix22314.c
  test/compilable/fix22322.c
  test/compilable/test22286.c
  test/compilable/test22303.c
  test/compilable/test22304.c
  test/compilable/test22333.c
  test/compilable/testcstuff2.c
  test/fail_compilation/failcstuff1.c
  test/fail_compilation/failcstuff2.c
  test/fail_compilation/fix22253.c
  test/fail_compilation/fix22263.c
  test/fail_compilation/test22246.c
  test/run.d
  test/runnable/test22070_2.c
  test/runnable/test22071.c
  test/runnable/test22205.d
  test/runnable/test22326.c
Labels: auto-merge, Bug Fix

#13109 Fix Issue 22292 - REG[2.084.1] Recursive class literal segfaults compiler
  src/dmd/dinterpret.d
  test/compilable/test22292.d
Labels: auto-merge, Bug Fix

#13090 ImportC: move int to ptr conversion code to typeMerge()
  src/dmd/dcast.d
  src/dmd/expressionsem.d
  test/compilable/testcstuff2.c
  test/fail_compilation/failcstuff2.c
Labels: Easy Review, ImportC

#13111 issue22262: Move fail_compilation test to compilable
  test/compilable/testcstuff2.c
  test/fail_compilation/failcstuff2.c
Labels: auto-merge, Easy Review, ImportC

#13113 Pull 2.098 changelog fixes from master
  changelog/AliasAssign.dd
  changelog/ImportC.dd
  changelog/dtorfileds.dd
  changelog/fix10445.dd
  changelog/range-error.dd
  changelog/static_this_immutable_initialization.dd
  changelog/target.dd
  changelog/target.md
  changelog/union_initialization.dd
Labels: documentation

#13114 Purge 2.098 changelog files from master
  changelog/AliasAssign.dd
  changelog/ImportC.dd
  changelog/ambiguous-lambda.dd
  changelog/dtoh-improvements.dd
  changelog/dtorfileds.dd
  changelog/fix10445.dd
  changelog/mutable-cases.dd
  changelog/range-error.dd
  changelog/remove_alloc.dd
  changelog/static_this_immutable_initialization.dd
  changelog/target.dd
  changelog/union_initialization.dd
Labels: documentation
