Repository dlang/dmd, pull requests merged in 2021-11, with the labels that each got.

#13248 Minor: Move a test from traits compiles to fail compilation
  test/compilable/test4090.d
  test/fail_compilation/foreach2.d
Labels: auto-merge

#13250 Fix Issue 22462 - OpenBSD: bash lives in /usr/local
  test/Makefile
Labels: auto-merge, Bug Fix

#13242 Implement `-transition=in` to display usages of 'in'
  src/dmd/cli.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/parse.d
  test/compilable/previewall.d
  test/compilable/transition_in.d
  test/compilable/transitionhelp.d
Labels: auto-merge

#13251 Fix Issue 22463 - OpenBSD: Allow DMD to work on 32-bit OpenBSD
  src/dmd/backend/cod1.d
Labels: auto-merge, Bug Fix

#13249 Fix Issue 22461 - OpenBSD: Use fmodl
  src/dmd/backend/fp.d
Labels: auto-merge, Bug Fix

#12279 Github CI: Re-enable 32 bits tests
  .github/workflows/runnable_cxx.yml
  test/dshell/dll_cxx.d
Labels: auto-merge

#13253 Fix Issue 19482 - attributes incorrectly applied to static foreach local variables
  src/dmd/dsymbolsem.d
  src/dmd/statementsem.d
  test/compilable/test19482.d
Labels: Bug Fix

#13258 Fix 22472 - Correct error message for invalid `void` return
  src/dmd/statementsem.d
  test/fail_compilation/diag20059.d
  test/fail_compilation/ice10212.d
  test/fail_compilation/noreturn2.d
Labels: auto-merge, Bug Fix

#13259 Add missing change after using .max instead of MAX
  src/dmd/backend/drtlsym.d
Labels: Trivial

#13264 Fix Issue 22478 - OpenBSD: Add to fail_compilation/invalid_lib.d
  test/fail_compilation/invalid_lib.d
Labels: Enhancement, auto-merge

#13261 Add openbsd32 and openbsd64 to the ignore list
  test/compilable/cdcmp.d
Labels: Enhancement, auto-merge

#13260 Fix Issue 22474 - OpenBSD: Add support to test/runnable/dhry.d
  test/runnable/dhry.d
Labels: Enhancement, auto-merge

#13263 Add openbsd to ignore list
  test/fail_compilation/fail3753.d
Labels: Enhancement, auto-merge

#13220 add another case to SROA optimization
  src/dmd/backend/cgelem.d
  src/dmd/backend/cod3.d
  src/dmd/backend/cod4.d
  src/dmd/backend/dtype.d
  src/dmd/backend/elem.d
  src/dmd/backend/gsroa.d
  test/compilable/sroa.d
  test/runnable/sroa13220.d
  test/runnable/testxmm.d
Labels: auto-merge

#13262 Add openbsd to ignore list
  test/fail_compilation/fail21227_win.d
Labels: Enhancement, auto-merge

#13266 Fix Issue 21380 - A case of compiler crash when using auto ref
  src/dmd/dinterpret.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  test/fail_compilation/test21380.d
Labels: auto-merge, Bug Fix

#13252 Fix Issue 22421 - static foreach introduces semantic difference between indexing and iteration variable
  src/dmd/cond.d
  test/compilable/test22421.d
Labels: auto-merge, Bug Fix

#13247 backend: dwarfdbginf: Remove artificial attributes on wchar_t typedef
  src/dmd/backend/dwarfdbginf.d
Labels: Bug Fix, 72h no objection -> merge

#13269 Fix Issue 20998 - error in static struct initialization causes wrong position for subsequent members…
  src/dmd/initsem.d
  test/fail_compilation/fail225.d
  test/fail_compilation/test20998.d
Labels: auto-merge, Bug Fix

#13268 Fix Issue 15711 - Incorrect type inferring of [char]/string when passed via recursive template
  src/dmd/dsymbolsem.d
  test/compilable/test15711.d
Labels: Bug Fix

#13226 Rework fix for attribute based opApply overloads (issue 15624)
  src/dmd/opover.d
  test/runnable/testOpApply.d
Labels: auto-merge

#13272 straighten out makeTupleForeach template
  src/dmd/statementsem.d
Labels: Easy Review, Refactoring

#13275 eliminate TupleForeachArgs template
  src/dmd/statementsem.d
Labels: auto-merge, Easy Review, Refactoring

#13154 Partial fix issue 19294 - Support for array operations with Complex! is incomplete
  src/dmd/dcast.d
  test/compilable/b19294.d
Labels: Bug Fix, auto-merge-squash

#13277 Fix Issue 21039 - `alias this` returns 'null' for ref types when put into array initializer
  src/dmd/dcast.d
  test/runnable/test21039.d
Labels: auto-merge, Bug Fix

#13276 Fix Issue 21093 - [ICE] AssertError@dmd/optimize.d(691): Assertion failure
  src/dmd/optimize.d
  test/fail_compilation/test21093.d
Labels: auto-merge, Bug Fix

#13273 [stable] cirrus: Switch to big-sur image, use catalina for bootstrap only
  .cirrus.yml
  cirrusci.sh
Labels: auto-merge, Continuous Integration

#13279 Merge `stable` into `master`
  .cirrus.yml
  cirrusci.sh
  src/dmd/backend/cod1.d
  src/dmd/backend/fp.d
  src/dmd/cparse.d
  src/dmd/dcast.d
  src/dmd/dinterpret.d
  src/dmd/e2ir.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/func.d
  src/dmd/id.d
  src/dmd/initsem.d
  src/dmd/optimize.d
  src/dmd/statementsem.d
  src/dmd/toir.d
  test/Makefile
  test/compilable/cdcmp.d
  test/compilable/vastartend.c
  test/fail_compilation/diag20059.d
  test/fail_compilation/fail21227_win.d
  test/fail_compilation/fail225.d
  test/fail_compilation/fail3753.d
  test/fail_compilation/ice10212.d
  test/fail_compilation/invalid_lib.d
  test/fail_compilation/noreturn2.d
  test/fail_compilation/test20998.d
  test/fail_compilation/test21093.d
  test/fail_compilation/test21380.d
  test/fail_compilation/test21930.d
  test/runnable/dhry.d
  test/runnable/interpret.d
  test/runnable/test21039.d
Labels: Enhancement, auto-merge, Bug Fix, Continuous Integration, stable -> master

#13278 change void return from makeTupleForeach() to Statement
  src/dmd/statementsem.d
Labels: auto-merge, Easy Review, Refactoring

#13281 make makeTupleForeach() return a Voldemort type
  src/dmd/attrib.d
  src/dmd/statementsem.d
Labels: Easy Review, Refactoring

#13169 Fix Issue 22198 - Compile time bounds checking for static arrays
  src/dmd/expressionsem.d
  test/fail_compilation/fail20618.d
Labels: Enhancement, Needs Tests

#13282 d_do_test: Add --DRT-testmode=run-main even without `EXECUTE_ARGS`
  test/tools/d_do_test.d
Labels: Continuous Integration

#13283 fix Issue 22415 - ImportC: Deprecation: switch case fallthrough - use…
  src/dmd/blockexit.d
  test/compilable/test22415.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13280 Fix 22494 - Search paths for dmd.conf missing from dmd man page
  docs/gen_man.d
  docs/man/man5/dmd.conf.5
Labels: Enhancement, auto-merge

#13285 Fix 18054 - Use isBool instead of toInteger when const-folding cast(bool)
  src/dmd/constfold.d
  test/runnable/test18054.d
Labels: Bug Fix

#13289 fix Issue 22398 - importC: Error: unknown, when compiling source with…
  src/dmd/cparse.d
  src/dmd/dsymbolsem.d
  src/dmd/importc.d
  src/dmd/typesem.d
  test/compilable/test22398.c
Labels: auto-merge, Bug Fix, ImportC

#13291 Fix Issue 21073 - Rebindable does not work when class has alias this to inout property
  src/dmd/opover.d
  test/compilable/test21073.d
Labels: Bug Fix

#13293 Move semantic analysis of pragma(crt) from toobj to dsymbolsem
  src/dmd/dsymbolsem.d
  src/dmd/toobj.d
  test/fail_compilation/test17868b.d
Labels: auto-merge

#13294 backend: avoid unecessary allocations of dynamic array
  src/dmd/backend/var.d
Labels: Trivial, auto-merge, Refactoring

#13290 Fix Issue 16579 - Corrupted runtime on missed manifest constant propagation
  src/dmd/statementsem.d
  test/runnable/test16579.d
Labels: auto-merge, Bug Fix

#13292 Fix Issue 15804 - missing UDAs on nested struct template
  src/dmd/dsymbolsem.d
  test/runnable/uda.d
Labels: auto-merge, Bug Fix

#13296 backend: dwarfdbginf: associative arrays should report a pretty name
  src/dmd/backend/dwarfdbginf.d
  test/dshell/extra-files/dwarf/excepted_results/fix22508.txt
  test/dshell/extra-files/dwarf/fix22508.d
Labels: Enhancement, auto-merge

#13267 Fix 21538,20904: Correct implicitConvTo order for delegate parameters in `Type.covariant`
  src/dmd/mtype.d
  test/compilable/covariant_override.d
  test/fail_compilation/covariant_override.d
  test/runnable/xtest46.d
  test/unit/semantic/covariance.d
Labels: Regression, auto-merge, Bug Fix

#13047 Fix issue 22277 - removing strongly pure function calls is an incorrect optimization
  src/dmd/e2ir.d
  test/runnable/test15862.d
  test/runnable/test22227.d
Labels: Bug Fix

#13299 fix Issue 22432 - ImportC: casting result of postfix operator on a pa…
  src/dmd/cparse.d
  src/dmd/expressionsem.d
  src/dmd/importc.d
  test/compilable/test22432.c
Labels: auto-merge, Bug Fix, ImportC

#13300 fix Issue 22422 - ImportC: parse gnu attributes after a function para…
  src/dmd/cparse.d
  test/compilable/test22422.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13302 glue: object Outbuffer is being destroyed in the wrong place
  src/dmd/glue.d
  test/compilable/emptygenmain.d
Labels: auto-merge

#13303 propagate errors from Type.size()
  src/dmd/dcast.d
  src/dmd/declaration.d
  src/dmd/dsymbolsem.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/initsem.d
Labels: auto-merge, Easy Review

#12821 Fix issue 19873 - function should be by default @system even with -preview=dip1000
  src/dmd/escape.d
  test/compilable/test19873.d
  test/fail_compilation/fail809.d
  test/fail_compilation/fob2.d
  test/fail_compilation/retscope.d
Labels: Bug Fix, dip1000

#13298 Implement the LDC specific `__traits(initSymbol)`
  changelog/traits_initSymbol.dd
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dinterpret.d
  src/dmd/e2ir.d
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/todt.d
  src/dmd/traits.d
  test/fail_compilation/traits_initSymbol.d
  test/runnable/traits_initSymbol.d
Labels: auto-merge

#13314 Fix Issue 22510 - Structs with copy constructor can not be heap allocated with default constructor
  src/dmd/expressionsem.d
  test/compilable/test22510.d
Labels: auto-merge, Bug Fix

#13313 Fix 22516 - Set TypeError as return type if inference was skipped...
  src/dmd/expression.d
  src/dmd/semantic3.d
  test/fail_compilation/ice22516.d
Labels: Regression, auto-merge, Bug Fix

#13312 Fix Issue 22515 - Aggregate definition with qualifiers has inconsistencies between structs and classes
  src/dmd/dsymbolsem.d
  test/runnable/testconst.d
Labels: auto-merge, Bug Fix

#13315 Fix Issue 21367 - Nameless union propagates copy constructors and destructors over all members
  src/dmd/dsymbolsem.d
  test/runnable/test21367.d
Labels: Regression, auto-merge, Bug Fix

#13304 ImportC: make static functions local
  src/dmd/backend/cod3.d
  src/dmd/backend/code_x86.d
  src/dmd/backend/machobj.d
  src/dmd/backend/out.d
  src/dmd/glue.d
  test/runnable/test22428.c
Labels: auto-merge, ImportC

#13309 Fix 22514 - Don't raise invalid duplicate case errors when the switch...
  src/dmd/statementsem.d
  test/fail_compilation/test_switch_error.d
Labels: auto-merge, Bug Fix

#13318 dmd.root.port: Adjust Port::valcpy signature to avoid C++ long vs long long mangling
  src/dmd/frontend.h
  src/dmd/root/port.d
Labels: auto-merge, Easy Review, extern (C/C++)

#13324 fix Issue 22517 - [REG 2.093][ICE] Bus error at dmd/lexer.d:398
  src/dmd/lexer.d
Labels: Regression, auto-merge, Bug Fix

#13325 [stable] fix Issue 22517 - [REG 2.093][ICE] Bus error at dmd/lexer.d:398
  src/dmd/lexer.d
Labels: Regression, auto-merge, Bug Fix

#13321 Fix Issue 22254 - Template instantiated twice results in different immutable qualifier
  src/dmd/aggregate.d
  test/compilable/test22254.d
Labels: auto-merge, Bug Fix

#13322 fix Issue 22428 - importC: static variables/functions emit global sym…
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/frontend.h
  src/dmd/glue.d
  src/dmd/toobj.d
  test/runnable/test22428.c
Labels: auto-merge, Bug Fix, ImportC

#13323 fix Issue 22512 - importC: incomplete array type must have initializer
  test/compilable/testcstuff2.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13328 remove static if from makeTupleForeach()
  src/dmd/statementsem.d
Labels: auto-merge, Easy Review, Refactoring

#13333 make makeTupleForeach() static
  src/dmd/statementsem.d
Labels: Easy Review, Refactoring

#13332 Fix Issue 22530 - Explicit cast between classes incorrectly goes through 'alias this' inside CTFE
  src/dmd/ctfeexpr.d
  src/dmd/dinterpret.d
  test/runnable/interpret.d
Labels: Bug Fix

#13337 convert makeTupleForeach into a regular function
  src/dmd/attrib.d
  src/dmd/statementsem.d
Labels: auto-merge, Easy Review, Refactoring

#13307 Partial fix issue 19294 (Updated with broader support for array operations)
  src/dmd/dcast.d
  test/runnable/b19294.d
Labels: Bug Fix

#13286 Refactor Expression.isBool to return an optional value
  src/build.d
  src/dmd/attrib.d
  src/dmd/blockexit.d
  src/dmd/constfold.d
  src/dmd/ctfeexpr.d
  src/dmd/dinterpret.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/mtype.d
  src/dmd/optimize.d
  src/dmd/root/optional.d
  src/dmd/root/optional.h
  src/dmd/statementsem.d
  src/dmd/staticcond.d
  src/dmd/todt.d
  src/dmd/traits.d
  src/tests/cxxfrontend.c
Labels: Refactoring

#13341 ImportC: improve parsing error message
  src/dmd/cparse.d
  test/fail_compilation/failcstuff1.c
Labels: auto-merge, Easy Review, ImportC

#13327 lexer: prefer usage of implicit memset call over manual individual set.
  src/dmd/mars.d
  src/dmd/root/file.d
Labels: Trivial, auto-merge, Refactoring

#13342 Nightlies: Use process substitution instead of additional pipe segment
  .github/workflows/nightlies.yml
Labels: auto-merge, Continuous Integration

#13339 move makeTupleFunction() to global scope
  src/dmd/statementsem.d
Labels: auto-merge, Easy Review, Refactoring

#13334 fix Issue 22513 - ImportC: address of member of struct cannot be take…
  src/dmd/initsem.d
  src/dmd/optimize.d
  src/dmd/printast.d
  test/runnable/test22513.c
Labels: auto-merge, Bug Fix, ImportC

#13340 fix Issue 22500 - ImportC: Lots of errors when compiling tomlc99
  test/runnable/test22500.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13345 fix Issue 22512 - importC: incomplete array type must have initializer
  src/dmd/importc.d
  test/compilable/testcstuff2.c
Labels: auto-merge, Bug Fix, ImportC

#13344 [stable] importC: Backport master fixes to stable
  src/dmd/blockexit.d
  src/dmd/cparse.d
  test/compilable/test22415.c
  test/fail_compilation/failcstuff1.c
Labels: Bug Fix

#13338 fix size_t in setLengthVarIfKnown()
  src/dmd/optimize.d
Labels: Easy Review, Refactoring

#13346 replace Visitor in Expression_optimize() with switch and nested functions
  src/dmd/optimize.d
Labels: auto-merge, Refactoring

#13347 Fix Issue 22529 - wrong deprecation about empty statement
  src/dmd/parse.d
  test/fail_compilation/fail22529.d
Labels: Regression, auto-merge, Bug Fix

#13343 Nightlies: Use v1 instead of specific tag
  .github/workflows/nightlies.yml
Labels: auto-merge

#13356 replace STC.ctorinit with bool
  src/dmd/astenums.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
  src/dmd/statementsem.d
Labels: Easy Review, Refactoring

#13336 Fix Issue 22533 - OpenBSD: Use correct size_t compat for 32-bit
  src/dmd/common/outbuffer.h
  src/dmd/root/dcompat.h
Labels: Bug Fix

#13355 remove unused STC.init
  src/dmd/astenums.d
  src/dmd/declaration.h
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
Labels: auto-merge, Easy Review, Refactoring

#13349 Fix issue 17977 - destructor allows escaping reference to a temporary struct instance
  src/dmd/declaration.d
  test/fail_compilation/test17977.d
Labels: auto-merge, Bug Fix, dip1000

#13351 Fix Issue 22519 - cannot take address of `ref return`
  src/dmd/expressionsem.d
  test/fail_compilation/test15191.d
Labels: Enhancement, auto-merge

#13358 Fix Issue 21414 - Spurious `non-constant` expression error with immutable constructors
  src/dmd/todt.d
  test/compilable/test21414.d
Labels: Regression, auto-merge, Bug Fix

#13360 split off EXP from TOK
  src/dmd/access.d
  src/dmd/aggregate.d
  src/dmd/aliasthis.d
  src/dmd/arrayop.d
  src/dmd/astbase.d
  src/dmd/blockexit.d
  src/dmd/builtin.d
  src/dmd/canthrow.d
  src/dmd/clone.d
  src/dmd/cond.d
  src/dmd/constfold.d
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/ctfeexpr.d
  src/dmd/dcast.d
  src/dmd/declaration.d
  src/dmd/dinterpret.d
  src/dmd/dmangle.d
  src/dmd/dstruct.d
  src/dmd/dsymbol.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/e2ir.d
  src/dmd/escape.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/foreachvar.d
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  src/dmd/initsem.d
  src/dmd/inline.d
  src/dmd/inlinecost.d
  src/dmd/mtype.d
  src/dmd/nogc.d
  src/dmd/opover.d
  src/dmd/optimize.d
  src/dmd/s2ir.d
  src/dmd/safe.d
  src/dmd/semantic2.d
  src/dmd/semantic3.d
  src/dmd/sideeffect.d
  src/dmd/statementsem.d
  src/dmd/todt.d
  src/dmd/tokens.d
  src/dmd/tokens.h
  src/dmd/toobj.d
  src/dmd/traits.d
  src/dmd/typesem.d
Labels: Refactoring

#13301 backend: dwarfdbginf: add DW_AT_artificial to main subprogram when generated
  src/dmd/backend/backconfig.d
  src/dmd/backend/cdef.d
  src/dmd/backend/dwarfdbginf.d
  src/dmd/dmsc.d
  test/dshell/extra-files/dwarf/excepted_results/fix22471.txt
  test/dshell/extra-files/dwarf/fix22471.d
Labels: Enhancement, auto-merge, Debug Info

#13367 fix overshoot and undershoot with TOK to EXP conversion
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/e2ir.d
  src/dmd/escape.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/target.d
Labels: auto-merge, Refactoring

#13308 Fix Issue 21719 - [REG 2.072] "auto" methods of classes do not infer attributes correctly.
  src/dmd/func.d
  test/compilable/test21719.d
  test/runnable/xtest46.d
Labels: Regression, Bug Fix

#13370 Add opApply test case for issue 20907
  test/runnable/testOpApply.d
Labels: auto-merge

#13372 more TOK to EXP conversion
  src/dmd/cparse.d
  src/dmd/parse.d
Labels: auto-merge, Easy Review, Refactoring

#13350 Fix issue 20023 - Separate compilation breaks dip1000 / dip1008 @safety
  src/dmd/escape.d
  test/fail_compilation/imports/test20023b.d
  test/fail_compilation/test20023.d
Labels: auto-merge, Bug Fix, dip1000

#13326 Fix Issue 22385 - CTFE fails to iterate over associative array previously indexed with implicit conversion to enum base type
  src/dmd/constfold.d
  test/compilable/test10028.d
Labels: Regression, Bug Fix

#13217 fix Issue 7925 - extern(C++) delegates
  src/dmd/e2ir.d
  src/dmd/tocsym.d
  test/runnable_cxx/extra-files/cpp7925.cpp
  test/runnable_cxx/test7925.d
Labels: Enhancement

#13015 Fix Issue 19320 - -cov and -O yield variable used before set
  src/dmd/backend/gother.d
  test/compilable/test19320.d
Labels: Bug Fix
