Repository dlang/dmd, pull requests merged in 2021-06, with the labels that each got.

#12614 d_do_test: Rerun tests when an output section was updated
  test/tools/d_do_test.d
Labels: auto-merge

#12615 CONTRIBUTING.md: add section on Refactoring
  CONTRIBUTING.md
Labels: auto-merge, documentation

#12616 CONTRIBUTING.md: remove excess verbiage
  CONTRIBUTING.md
Labels: Easy Review, auto-merge-squash, documentation

#12619 ImportC: add anonymous structs
  src/dmd/cparse.d
  src/dmd/typesem.d
  test/compilable/imports/cstuff1.c
Labels: ImportC, auto-merge

#12425 Do not recommend un-approved preview switches
  src/dmd/typesem.d
  test/fail_compilation/fail7603a.d
  test/fail_compilation/fail7603b.d
  test/fail_compilation/fail7603c.d
  test/fail_compilation/fail9773.d
  test/fail_compilation/fail9891.d
  test/fail_compilation/issue20704.d
Labels: Atila Neves, Walter Bright, auto-merge

#12621 disallow empty struct-declaration-list
  src/dmd/cparse.d
  test/compilable/imports/cstuff1.c
Labels: Easy Review, ImportC, auto-merge

#12623 Remove unused getcwd import/declaration in dmodule
  src/dmd/dmodule.d
Labels: auto-merge

#12622 ImportC add floating point literal suffix support
  src/dmd/lexer.d
  test/compilable/imports/cstuff1.c
Labels: Easy Review, ImportC, auto-merge

#12620 Fix issue 21209 - scope attribute inference fails on foreach
  src/dmd/statementsem.d
  test/compilable/scope.d
Labels: Bug Fix

#12625 [stable] Avoid deprecations when compiling dmd.root.ctfloat
  src/dmd/root/ctfloat.d
Labels: auto-merge

#12626 ImportC C byte promotion behavior
  src/dmd/dcast.d
  test/compilable/imports/cstuff1.c
Labels: Easy Review, ImportC, auto-merge

#12627 fix Issue 21976 - importC: does not distinguish between cast-expression and unary-expression correctly
  src/dmd/cparse.d
  test/compilable/imports/cstuff1.c
Labels: Bug Fix, Easy Review, ImportC, auto-merge

#12628 Fix issue 17041 - foreach ref fails with static array in sequence
  src/dmd/statementsem.d
  test/runnable/foreach5.d
Labels: Bug Fix

#12629 ImportC: add C escape sequences
  src/dmd/lexer.d
Labels: Easy Review, ImportC, auto-merge

#12630 Transform setFlagFor from a template into function
  src/dmd/mars.d
Labels: auto-merge

#12632 merge stable
  VERSION
  changelog/ambiguous-ternary.dd
  changelog/body-deprecation.dd
  changelog/fqn-bypass-deprecation.dd
  changelog/package-visibility.dd
  changelog/pragma-mangle-aggregate.dd
  changelog/transition-complex.dd
  changelog/while-condition-assignment.dd
  src/dmd/root/ctfloat.d
Labels: auto-merge

#12631 ImportC add C strings
  src/dmd/lexer.d
Labels: Easy Review, ImportC

#12634 ImportC: character constants
  src/dmd/cparse.d
  src/dmd/lexer.d
  test/compilable/imports/cstuff1.c
Labels: ImportC, auto-merge

#12635 fix Issue 21994 (char*)expression fails to compile
  src/dmd/cparse.d
  test/compilable/imports/cstuff1.c
Labels: Bug Fix, Easy Review, ImportC, auto-merge

#12638 ImportC: string literals are typed as pointers
  src/dmd/cparse.d
  src/dmd/expressionsem.d
  test/compilable/imports/cstuff1.c
Labels: Easy Review, ImportC

#12639 move hasNonConstPointers() from init.d to initsem.d
  src/dmd/frontend.h
  src/dmd/init.d
  src/dmd/initsem.d
Labels: Easy Review, Refactoring, auto-merge

#12640 ImportC: recognize {exp} initializers as just exp
  src/dmd/cparse.d
  test/compilable/imports/cstuff1.c
Labels: Easy Review, ImportC, auto-merge

#12637 fix Issue 21944 - ImportC: Support parsing # line marker directive ex…
  src/dmd/lexer.d
  test/compilable/imports/cstuff1.c
Labels: Bug Fix, Easy Review, ImportC, auto-merge

#12514 ctfeexpr: support reinterpreting cast when switching safe/pure/nothrow in both directions
  src/dmd/ctfeexpr.d
  test/compilable/reinterpretctfe.d
Labels: Enhancement

#12068 dtoh: Don't assert when handling complex and imaginary types
  changelog/dtoh-improvements.dd
  src/dmd/astcodegen.d
  src/dmd/dtoh.d
  test/compilable/dtoh_ignored.d
  test/compilable/dtoh_invalid_identifiers.d
Labels: dtoh

#12624 Replace for-loops with `foreach` in dmodule
  src/dmd/dmodule.d
Labels: Refactoring, auto-merge

#12633 Fix 21993 - Implement cast(noreturn)
  src/dmd/dcast.d
  src/dmd/typesem.d
  test/compilable/noreturn3.d
  test/fail_compilation/noreturn.d
Labels: Bug Fix, auto-merge

#12642 ImportC: parse initializers into CInitializer
  src/dmd/arraytypes.d
  src/dmd/arraytypes.h
  src/dmd/astbase.d
  src/dmd/astcodegen.d
  src/dmd/cparse.d
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  src/dmd/init.d
  src/dmd/init.h
  src/dmd/initsem.d
  src/dmd/parsetimevisitor.d
  src/dmd/strictvisitor.d
  src/dmd/todt.d
  src/dmd/transitivevisitor.d
  src/dmd/visitor.h
Labels: ImportC, auto-merge

#12644 ImportC: add pretty-printing of C initializers
  src/dmd/cparse.d
  src/dmd/hdrgen.d
Labels: Easy Review, ImportC, auto-merge

#12648 [dmd-cxx] Fix Issue 19234 - betterC TypeInfo error when using slice copy on Structs
  src/expression.c
  test/compilable/betterCarray.d
Labels: C++ Port, Easy Review, GDC

#12649 dtoh: Make implementation private and add some DDOC
  src/dmd/dtoh.d
  src/dmd/frontend.h
Labels: Refactoring, Trivial, dtoh

#12651 Extend Issue 19234 - betterC TypeInfo error when using slice copy on Structs
  src/dmd/expression.d
  test/compilable/minimal3.d
Labels: Blocking Other Work, Bug Fix, Easy Review, auto-merge

#12652 fix Issue 22007 - static foreach: cannot implicitly convert expression Tuple4(0LU, 1) of type Tuple4 to int
  src/dmd/statementsem.d
  test/compilable/staticforeach.d
Labels: Bug Fix, Easy Review

#12655 dsymbolsem: replace unsafe casts
  src/dmd/dsymbolsem.d
Labels: Easy Review, Refactoring

#12654 ImportC: strings initialize arrays of unknown size
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
  src/dmd/initsem.d
  test/compilable/imports/cstuff1.c
Labels: ImportC

#12656 fix Issue 22005 - ICE: Segmentation fault with static foreach and -betterC
  src/dmd/cond.d
  test/compilable/minimal3.d
Labels: Bug Fix, Easy Review

#12658 make initializerToExpression() for arrays easier to read
  src/dmd/initsem.d
Labels: Refactoring, auto-merge

#12659 dtoh: Move context specific attributes into a dedicated struct
  src/dmd/dtoh.d
Labels: Refactoring, auto-merge, dtoh

#12643 dtoh: Handle missing elements in StructLiteralDeclarations
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  test/compilable/dtoh_UnionDeclaration.d
Labels: auto-merge, dtoh

#12660 static foreach: Delay running ctfeInterpret until the lowering stage
  src/dmd/cond.d
  test/compilable/b12504.d
  test/fail_compilation/b12504.d
Labels: auto-merge

#12662 fix Issue 22006 - static foreach and foreach over tuple doesn't work on 16-bit
  src/dmd/statementsem.d
  test/compilable/minimal3.d
  test/compilable/test22006.d
  test/fail_compilation/diag16976.d
  test/fail_compilation/fail22006.d
Labels: Bug Fix

#12663 replace gotos in initializerSemantic() with return err()
  src/dmd/initsem.d
Labels: Easy Review, Refactoring

#12664 ImportC add simple array initialization
  src/dmd/initsem.d
  src/dmd/todt.d
  test/runnable/cstuff2.c
Labels: ImportC, auto-merge

#12653 dtoh: Handle D symbols referenced from exported symbols
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_AliasDeclaration.d
  test/compilable/dtoh_enum.d
  test/compilable/dtoh_enum_cpp98.d
  test/compilable/dtoh_required_symbols.d
  test/compilable/dtoh_special_enum.d
  test/compilable/dtoh_verbose.d
  test/dshell/cpp_header_gen.d
Labels: auto-merge, dtoh

#12666 Disable Github actions workflows for forks
  .github/workflows/nightlies.yml
  .github/workflows/runnable_cxx.yml
Labels: Continuous Integration

#12667 CirrusCi: merge pull requests with target branch
  .cirrus.yml
Labels: Continuous Integration

#12669 Nightlies: Update release instead of tagging a new one
  .github/workflows/nightlies.yml
Labels: Continuous Integration

#12670 dtoh: Emit enum declarations to `donebuf` instead of `fwdbuf`...
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_required_symbols.d
  test/compilable/dtoh_special_enum.d
Labels: auto-merge, dtoh

#12674 ImportC: arrays of unknown length, zero fill uninitialized elements
  src/dmd/frontend.h
  src/dmd/init.d
  src/dmd/init.h
  src/dmd/initsem.d
  src/dmd/todt.d
  test/runnable/cstuff2.c
Labels: Easy Review, ImportC

#12675 improve semantic for visitStruct()
  src/dmd/initsem.d
Labels: Easy Review, Refactoring, auto-merge

#12672 dtoh: Merge `visitAsRoot` and `includeSymbol`
  src/dmd/dtoh.d
Labels: Refactoring, auto-merge, dtoh

#12676 add isPtrToFunction()
  src/dmd/dmangle.d
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/iasmdmd.d
  src/dmd/initsem.d
  src/dmd/inline.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/traits.d
Labels: Easy Review, Refactoring, auto-merge

#12681 dtoh: Use C-style cast for CastExp instead of cast(...)
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  test/compilable/dtoh_expressions.d
Labels: auto-merge, dtoh

#12682 dtoh: Mark structs as final by default
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_21217.d
  test/compilable/dtoh_AliasDeclaration.d
  test/compilable/dtoh_AliasDeclaration_98.d
  test/compilable/dtoh_AnonDeclaration.d
  test/compilable/dtoh_CPPNamespaceDeclaration.d
  test/compilable/dtoh_ClassDeclaration.d
  test/compilable/dtoh_StructDeclaration.d
  test/compilable/dtoh_TemplateDeclaration.d
  test/compilable/dtoh_UnionDeclaration.d
  test/compilable/dtoh_VarDeclaration.d
  test/compilable/dtoh_cpp98_compat.d
  test/compilable/dtoh_enum.d
  test/compilable/dtoh_enum_cpp98.d
  test/compilable/dtoh_expressions.d
  test/compilable/dtoh_extern_type.d
  test/compilable/dtoh_functions.d
  test/compilable/dtoh_ignored.d
  test/compilable/dtoh_invalid_identifiers.d
  test/compilable/dtoh_protection.d
  test/compilable/dtoh_required_symbols.d
  test/compilable/dtoh_special_enum.d
  test/compilable/dtoh_unittest_block.d
  test/compilable/dtoh_verbose.d
Labels: auto-merge, dtoh

#12679 dtemplate.d: remove a bunch of casts
  src/dmd/dtemplate.d
Labels: Easy Review, Refactoring, auto-merge

#12680 add isFunction_Delegate_PtrToFunction()
  src/dmd/dmangle.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/traits.d
Labels: Easy Review, Refactoring, auto-merge

#12673 Include unit tests into the coverage report
  test/tools/unit_test_runner.d
Labels: Continuous Integration, auto-merge

#12683 ImportC: nested array initializers
  src/dmd/initsem.d
  src/dmd/todt.d
  test/runnable/cstuff2.c
Labels: ImportC

#12677 Fix Issue 22019 - `case 1,:` allowed by grammar but not DMD
  src/dmd/parse.d
  test/compilable/testparse.d
Labels: Bug Fix, Walter Bright, auto-merge

#12671 Ensure that Dsymbol.search never raises an error with IgnoreErrors...
  src/dmd/dclass.d
  src/dmd/dstruct.d
  src/dmd/nspace.d
  test/unit/compilable/searching.d
  test/unit/support.d
Labels: auto-merge

#12686 ImportC: move { exp } optimization from parser to semantic()
  src/dmd/cparse.d
  src/dmd/initsem.d
  test/runnable/cstuff2.c
Labels: Easy Review, ImportC, auto-merge

#11723 fix issue 21238 - -deps considers only the first instantiation site of a template for dependencies
  src/dmd/cond.d
  src/dmd/dscope.d
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  src/dmd/scope.h
  test/compilable/depsOutput21238_foo.d
  test/compilable/depsOutput9948.d
  test/compilable/imports/depsOutput21238_bar.d
  test/compilable/imports/depsOutput21238_baz_cond.d
  test/compilable/imports/depsOutput21238_baz_moduleimport.d
  test/compilable/imports/depsOutput21238_baz_pragmalib.d
  test/compilable/imports/depsOutput21238_baz_stringimport.d
  test/compilable/imports/depsOutput21238_qux.d
  test/compilable/imports/depsOutput9948a.d
  test/compilable/imports/depsOutput9948b.d
Labels: Bug Fix, auto-merge

#12687 ImportC add C string initializers
  src/dmd/initsem.d
  test/runnable/cstuff2.c
Labels: Easy Review, ImportC, auto-merge

#12690 fix Issue 22029 - importC: Parser accepts storage-class specifiers for fields
  src/dmd/cparse.d
  test/fail_compilation/failcstuff1.d
  test/fail_compilation/imports/cstuff1.c
Labels: Blocking Other Work, Bug Fix, ImportC

#12691 fix Issue 22030 - importC: Wrong error with bad declarator
  src/dmd/cparse.d
  test/fail_compilation/failcstuff1.d
  test/fail_compilation/imports/cstuff1.c
Labels: Bug Fix, ImportC, auto-merge

#12694 ImportC: add basic struct initializations
  src/dmd/initsem.d
  test/runnable/cstuff2.c
Labels: ImportC, auto-merge

#12696 dtoh: Write symbol names using a dedicated method
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_invalid_identifiers.d
  test/compilable/dtoh_names.d
Labels: auto-merge, dtoh

#12645 [mars.d] Use parameters instead of global in setDefaultLibrary
  src/dmd/mars.d
Labels: Easy Review, Refactoring, Trivial

#12697 dtoh: Emit entire declarations before first member access
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_required_symbols.d
Labels: auto-merge, dtoh

#12692 fix Issue 22028 - importC: Parser accepts initializers for struct members
  src/dmd/cparse.d
  test/compilable/imports/cstuff2.c
  test/fail_compilation/failcstuff1.d
  test/fail_compilation/imports/cstuff1.c
Labels: Bug Fix, ImportC

#12695 ImportC: add CompoundLiteralExp
  src/dmd/cparse.d
  src/dmd/expression.d
  src/dmd/frontend.h
  src/dmd/parse.d
  src/dmd/tokens.d
  src/dmd/visitor.d
  src/dmd/visitor.h
  test/unit/lexer/location_offset.d
Labels: Easy Review, ImportC, auto-merge

#12699 Fix regression in ParseTimeVisitor C++ headers
  src/dmd/frontend.h
  src/dmd/parsetimevisitor.d
Labels: GDC, Regression, auto-merge

#12700 dmd.cparse: Remove dead code from cparseDeclaration
  src/dmd/cparse.d
Labels: ImportC, Refactoring, auto-merge

#12698 dtoh: Omit global variables with invalid identifiers
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_invalid_identifiers.d
  test/compilable/dtoh_verbose.d
Labels: dtoh

#12702 fix Issue 22035 - [REG 2.097][ICE] Segmentation fault parsing invalid case statement
  src/dmd/parse.d
  test/fail_compilation/fail22035.d
Labels: Bug Fix, Regression

#12703 fix Issue 22035 - [ICE] importC: Segmentation fault parsing invalid case statement
  src/dmd/cparse.d
  src/dmd/parse.d
  test/fail_compilation/fail22035.d
  test/fail_compilation/failcstuff1.d
  test/fail_compilation/imports/cstuff1.c
Labels: Bug Fix, ImportC, auto-merge

#12708 dmd.dmodule: Check whether packages is set to null in Module::load
  src/dmd/dmodule.d
  src/tests/cxxfrontend.c
Labels: GDC, Regression, auto-merge

#12706 fix Issue 22032 - importC: infinite loop: illegal combination of type specifiers
  src/dmd/cparse.d
  test/fail_compilation/failcstuff1.d
  test/fail_compilation/imports/cstuff1.c
Labels: Bug Fix, ImportC, auto-merge

#12701 importC: Move abstract-declarator error to cparseDeclarator
  src/dmd/cparse.d
  test/fail_compilation/failcstuff1.d
  test/fail_compilation/imports/cstuff1.c
Labels: ImportC, Refactoring

#12711 ImportC: isCDeclarator is skipping [ ] postfix check
  src/dmd/cparse.d
  test/runnable/cstuff2.c
Labels: ImportC, auto-merge

#12713 ImportC: initializers that are arrays of structs
  src/dmd/initsem.d
  src/dmd/todt.d
  test/runnable/cstuff2.c
Labels: ImportC

#12714 ImportC fix cstuff2.c to compile with default gcc
  test/runnable/cstuff2.c
Labels: ImportC, Trivial

#12716 test/compilable/sw_transition_complex: Fix bad syntax in unittest block
  test/compilable/sw_transition_complex.d
Labels: auto-merge

#12718 test/compilable/test19754: Fix incorrect IsExpression
  test/compilable/test19754.d
Labels: auto-merge

#12717 test/compilable/test15019: Fix invalid code
  test/compilable/test15019.d
Labels: auto-merge

#12678 dtoh: Consolidate forward declarations into a dedicated method
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_AliasDeclaration.d
  test/compilable/dtoh_ClassDeclaration.d
  test/compilable/dtoh_StructDeclaration.d
  test/compilable/dtoh_UnionDeclaration.d
  test/compilable/dtoh_cpp98_compat.d
  test/compilable/dtoh_enum.d
  test/compilable/dtoh_enum_cpp98.d
  test/compilable/dtoh_extern_type.d
  test/compilable/dtoh_forwarding.d
  test/compilable/dtoh_functions.d
  test/compilable/dtoh_invalid_identifiers.d
  test/compilable/dtoh_names.d
  test/compilable/dtoh_required_symbols.d
Labels: auto-merge, dtoh

#12704 ImportC: add semantic() for compound literals
  src/dmd/expressionsem.d
  src/dmd/hdrgen.d
  test/runnable/cstuff2.c
Labels: ImportC, auto-merge

#12715 ImportC apply const to correct declarator
  src/dmd/cparse.d
  test/fail_compilation/cconst1.c
Labels: ImportC, auto-merge

#12723 fix Issue 22060 - importC: Multiple forward declarations result in error struct conflicts with struct
  src/dmd/dsymbol.d
  test/compilable/imports/cstuff2.c
Labels: Bug Fix, ImportC, auto-merge

#12719 dtoh: Emit public imports in aggregates whenever possible
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_AliasDeclaration.d
  test/compilable/dtoh_verbose.d
  test/compilable/extra-files/dtoh_imports.d
Labels: auto-merge, dtoh

#12721 Fix 22053: Deprecate typeless catch at the parser level
  src/dmd/parse.d
  test/fail_compilation/fail17955.d
  test/fail_compilation/test12558.d
  test/fail_compilation/test17451.d
  test/runnable/testsafe.d
Labels: Bug Fix, auto-merge

#12725 ImportC: add toConst()
  src/dmd/cparse.d
Labels: Easy Review, ImportC, Refactoring

#12726 ImportC: don't make functions const
  src/dmd/cparse.d
Labels: Easy Review, ImportC, auto-merge

#12724 Issue 22063 - importC: Error: undefined identifier 'var' with pointer-to-typedef type
  src/dmd/cparse.d
  test/compilable/imports/cstuff2.c
Labels: Bug Fix, ImportC, auto-merge

#12730 dmd.typesem: Remove self referenced import
  src/dmd/typesem.d
Labels: Refactoring, Trivial, auto-merge

#12732 importC: Rename cparsePostExp to cparsePostfixExp
  src/dmd/cparse.d
Labels: ImportC, Refactoring, auto-merge

#12731 Parser: Group the result of parseLinkage in a struct
  src/dmd/parse.d
Labels: Refactoring, auto-merge

#12734 importC: Group all unary-operator cases together in cparseUnaryExp
  src/dmd/cparse.d
Labels: ImportC, Refactoring, Trivial

#12735 importC: Reorder functions so cparsePostfixExp comes before cparseUnaryExp
  src/dmd/cparse.d
Labels: ImportC, Refactoring, Trivial

#12733 fix Issue 22068 - importC: cast-expression accepted as lvalue in unary-expression
  src/dmd/cparse.d
  test/fail_compilation/failcstuff1.d
  test/fail_compilation/imports/cstuff1.c
Labels: Bug Fix, ImportC, auto-merge

#12742 fix Issue 22069 - importC: Error: found '&' instead of statement
  src/dmd/cparse.d
  test/compilable/imports/cstuff2.c
Labels: Bug Fix, ImportC, auto-merge

#12740 importC: Move parsing of postfix operators into own function
  src/dmd/cparse.d
Labels: Blocking Other Work, ImportC, Refactoring, auto-merge

#12739 Add CODEOWNERS for cparse.d and iasm.d
  CODEOWNERS
Labels: Easy Review, Trivial, auto-merge, documentation

#12737 [refactor] dmd.mtype: Remove the ENUMTY alias and all uses
  src/dmd/astbase.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/impcnvtab.d
  src/dmd/mtype.d
  src/dmd/objc_glue.d
  src/dmd/target.d
Labels: Refactoring, auto-merge

#12738 fix Issue 22080 - ImportC: Error: cannot implicitly convert expression of type 'extern(C) function' to 'function'
  src/dmd/cparse.d
  test/compilable/imports/cstuff2.c
Labels: Bug Fix, ImportC, auto-merge

#12736 fix Issue 22067 - importC: cast-expression accepted as lvalue in assignment-expression
  src/dmd/astcodegen.d
  src/dmd/cparse.d
  src/dmd/frontend.h
  test/compilable/imports/cstuff2.c
  test/fail_compilation/failcstuff1.d
  test/fail_compilation/imports/cstuff1.c
Labels: Bug Fix, ImportC, auto-merge

#12741 fix Issue 22079 - importC: Error: '=', ';' or ',' expected taking sizeof compound literal
  src/dmd/cparse.d
  test/compilable/imports/cstuff2.c
Labels: Bug Fix, ImportC, auto-merge

#12746 [refactor] dmd.traits: Remove dead isEnumMemX helper
  src/dmd/traits.d
Labels: Refactoring, auto-merge

#12745 fix Issue 22073 - importC: Error: found '.' when expecting ';' following compound literal
  src/dmd/cparse.d
  test/compilable/imports/cstuff2.c
Labels: Bug Fix, ImportC, auto-merge

#12747 dmd.astbase: Synchronize ASTBase with dmd front-end
  src/dmd/astbase.d
Labels: auto-merge

#12748 Fix Issue 22048 - [REG2.095] alias a = int p; compiles
  src/dmd/parse.d
  test/fail_compilation/test22048.d
Labels: Bug Fix, Easy Review, Regression, auto-merge

#12749 fix Issue 22066 - importC: Error: expression expected, not ';' using (postfix-expression)++
  src/dmd/cparse.d
  test/compilable/imports/cstuff2.c
Labels: Bug Fix, ImportC

#12751 importC: Compile all C stuff tests directly, instead of importing them
  test/compilable/imports/cstuff3.c
  test/compilable/testcstuff1.c
  test/compilable/testcstuff1.d
  test/compilable/testcstuff2.c
  test/compilable/testcstuff2.d
  test/compilable/testcstuff3.d
  test/fail_compilation/failcstuff1.c
  test/fail_compilation/failcstuff1.d
  test/fail_compilation/failcstuff2.c
  test/fail_compilation/imports/cstuff1.c
Labels: ImportC

#12750 importC: Parse prefix increment and decrement operators as an unary operator
  src/dmd/cparse.d
  test/fail_compilation/failcstuff1.c
Labels: ImportC, auto-merge

#12752 dmd.expression: Call optimize after modifiableLvalue
  src/dmd/expression.d
  src/dmd/expressionsem.d
  test/fail_compilation/diag4596.d
  test/fail_compilation/diag8178.d
  test/fail_compilation/test12385.d
Labels: Blocking Other Work, ImportC, auto-merge

#12754 test: Move "must fail" part of compilable/traits.d to fail_compilation
  test/compilable/traits.d
  test/fail_compilation/traits.d
Labels: auto-merge

#12756 Remove myself as *.h code owner
  CODEOWNERS
Labels: auto-merge

#12757 Fix style
  src/dmd/init.d
Labels: auto-merge

#12762 fix Issue 22086 - importC: RangeError@src/dmd/dscope.d(469): Range violation
  src/dmd/dscope.d
  test/fail_compilation/failcstuff1.c
Labels: Bug Fix, ImportC, auto-merge

#12763 dtoh: Consistently emit VarDeclaration's inside of templated aggregates
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_TemplateDeclaration.d
  test/compilable/dtoh_ignored.d
  test/compilable/dtoh_names.d
Labels: auto-merge, dtoh

#12761 fix Issue 22084 - [REG 2.097] Segmentation fault passing non-pod struct as variadic argument
  src/dmd/expressionsem.d
  test/fail_compilation/fail22084.d
Labels: Bug Fix, Regression

#12759 eliminate many unsafe casts from transitivevisitor.d
  src/dmd/astbase.d
  src/dmd/transitivevisitor.d
Labels: Easy Review, Refactoring, auto-merge

#12768 Merge stable into master
  src/dmd/dcast.d
  src/dmd/dinterpret.d
  src/dmd/expressionsem.d
  src/dmd/parse.d
  src/dmd/typesem.d
  test/compilable/noreturn3.d
  test/fail_compilation/fail22084.d
  test/fail_compilation/noreturn.d
  test/fail_compilation/test22048.d
Labels: Bug Fix, auto-merge

#12769 C++ namespaces: Remove dead code
  src/dmd/parse.d
Labels: auto-merge

#12770 CirrusCi: merge pull requests with target branch (#12667)
  .cirrus.yml
Labels: auto-merge

#12771 Issue 21980 - ImportC: _Thread_local allowed as storage class for ret…
  src/dmd/cparse.d
  test/fail_compilation/fail21980.c
Labels: Easy Review, ImportC, auto-merge

#12775 impcnv: should use functions, not arrays, as interface
  src/dmd/dcast.d
  src/dmd/dtemplate.d
  src/dmd/impcnvtab.d
Labels: Easy Review, Refactoring, auto-merge

#12776 remove implicitConvTy2
  src/dmd/dcast.d
  src/dmd/impcnvtab.d
Labels: Easy Review, Refactoring, auto-merge

#12777 exploit symmetry in implicit conversion tables
  src/dmd/impcnvtab.d
Labels: Easy Review, Refactoring, auto-merge

#12774 Remove unused function mangleToFuncSignature
  src/dmd/dmangle.d
Labels: Trivial

#12778 test: Fix EXTRA_FILES directive for a few tests
  test/compilable/issue21726.d
  test/compilable/test11847.d
  test/fail_compilation/test21246.d
Labels: Easy Review, Trivial, auto-merge

#12781 scope.h: Synchronize C++ headers with dscope.d
  src/dmd/scope.h
Labels: Easy Review, GDC, auto-merge

#12772 dtoh: Properly emit static arrays in template declarations whose...
  changelog/dtoh-improvements.dd
  src/dmd/astcodegen.d
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_TemplateDeclaration.d
Labels: auto-merge, dtoh

#12728 ImportC: MOD bits only apply before declarator, not after
  src/dmd/cparse.d
Labels: Easy Review, ImportC

#12782 fix Issue 22088 ImportC C11 6.3 implicit conversion semantics
  src/dmd/dcast.d
  test/compilable/testcstuff2.c
Labels: Bug Fix, Easy Review, ImportC, auto-merge

#12783 Revert "Fix Issue 19731 - auto struct methods whose address is taken don't test invariants"
  src/dmd/dsymbolsem.d
  test/compilable/test19731.d
  test/runnable/test19731.d
Labels: Easy Review, auto-merge

#12784 dtoh: Use `writeIdentifier` when writing `VarExp` that refer to...
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  test/compilable/dtoh_functions.d
  test/compilable/dtoh_names.d
Labels: auto-merge, dtoh

#12780 test: Fix dtoh tests to be compilable to object file
  test/compilable/dtoh_ClassDeclaration.d
  test/compilable/dtoh_TemplateDeclaration.d
  test/compilable/dtoh_enum.d
  test/compilable/dtoh_enum_cpp98.d
  test/compilable/dtoh_functions.d
  test/compilable/dtoh_names.d
Labels: Easy Review, Trivial, auto-merge, dtoh

#12785 dtoh: Resolve symbols from TypeIdentifier
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_TemplateDeclaration.d
Labels: auto-merge, dtoh

#12729 Add tests Issue 22061 - importC: Error: alias 'TYPE' conflicts with union 'TYPE'
  test/compilable/testcstuff2.c
  test/fail_compilation/failcstuff3.c
Labels: ImportC, auto-merge

#12788 d_do_test: Unify dir separator from `TEST_OUTPUT_FILE`s ...
  test/compilable/extra-files/json-postscript.sh
  test/compilable/extra-files/json.json
  test/compilable/extra-files/json2.json
  test/compilable/extra-files/jsonCompilerInfo.json
  test/compilable/extra-files/jsonNoOutFile.json
  test/compilable/extra-files/json_nosource.json
  test/compilable/json2.d
  test/tools/d_do_test.d
Labels: Continuous Integration, auto-merge
