Repository dlang/dmd, pull requests merged in 2021-03, with the labels that each got.

#12233 Detect noreturn statements
  src/dmd/blockexit.d
  test/fail_compilation/warn12809.d
Labels: auto-merge

#12235 Fix 14831 - Each function local symbols should have unique mangled name
  src/dmd/expressionsem.d
  test/compilable/test14831.d
  test/fail_compilation/b19523.d
  test/fail_compilation/bug9631.d
  test/fail_compilation/diag12829.d
  test/fail_compilation/diag15411.d
  test/fail_compilation/diag9831.d
  test/fail_compilation/ice11822.d
  test/fail_compilation/retscope.d
  test/fail_compilation/test15306.d
  test/fail_compilation/test16193.d
  test/runnable/test10619.d
  test/runnable/testkeyword.d
Labels: Bug Fix, auto-merge

#12226 DIP1034: type assert(0) as noreturn instead of void
  src/dmd/e2ir.d
  src/dmd/expressionsem.d
  src/dmd/mtype.d
  test/runnable/noreturn1.d
Labels: New Language Feature, auto-merge

#12207 Fix Issue 20661 - opEquals not recognized for AA key (take two)
  src/dmd/typesem.d
  test/compilable/test20661.d
Labels: Bug Fix, Easy Review, Regression, auto-merge

#12224 Fix Issue 21319 - DMD crashes on immutable circular reference
  src/dmd/dcast.d
  test/fail_compilation/test21319.d
Labels: Bug Fix, Regression, auto-merge

#12247 fix Issue 18190 - [asan] heap-buffer-overflow in Module.load.checkModFileAlias
  src/dmodule.c
Labels: Bug Fix, C++ Port, Easy Review, GDC, auto-merge

#12244 Deprecate 'body' as a keyword
  changelog/body-deprecation.dd
  src/dmd/parse.d
  test/runnable/testcontracts.d
Labels: auto-merge

#12250 Turn deprecation for ambiguous operations in ternary into errors
  changelog/ambiguous-ternary.dd
  src/dmd/parse.d
  test/fail_compilation/bug18743.d
Labels: Deprecation -> Error, auto-merge

#12251 Fix Issue 21680 - inconsistent error on `typeof({ return field; }())`
  src/dmd/expressionsem.d
  test/compilable/test21680.d
Labels: Bug Fix, auto-merge

#12253 merge stable
  VERSION
  changelog/shortfunctions.dd
  src/dmd/dcast.d
  src/dmd/dsymbol.d
  src/dmd/expressionsem.d
  src/dmd/globals.h
  src/dmd/module.h
  src/dmd/mtype.h
  src/dmd/statementsem.d
  src/dmd/typesem.d
  test/compilable/test14831.d
  test/compilable/test20661.d
  test/fail_compilation/b19523.d
  test/fail_compilation/bug9631.d
  test/fail_compilation/diag12829.d
  test/fail_compilation/diag15411.d
  test/fail_compilation/diag9831.d
  test/fail_compilation/ice11822.d
  test/fail_compilation/retscope.d
  test/fail_compilation/test15306.d
  test/fail_compilation/test16193.d
  test/fail_compilation/test21319.d
  test/runnable/test10619.d
  test/runnable/testkeyword.d
Labels: Bug Fix, auto-merge

#12208 Fix checkaction=context for tuple expressions with side effects
  src/dmd/expressionsem.d
  test/runnable/testassert.d
Labels: Bug Fix, auto-merge

#12249 Fix Issue 21678 - "_d_arraysetlengthT is not callable using argument …
  src/dmd/expressionsem.d
  src/dmd/sideeffect.d
  test/compilable/extra-files/vcg-ast-arraylength-postscript.sh
  test/compilable/vcg-ast-arraylength.d
Labels: Bug Fix, auto-merge

#12255 Fix 21682 - checkaction=context fails for expressions using static...
  src/dmd/expressionsem.d
  test/runnable/testassert.d
Labels: auto-merge

#12256 [stable] Fix orphaned CondExp __cond variable refs in codegen AST
  src/dmd/optimize.d
Labels: LDC, auto-merge

#12257 Fix links in body deprecation changelog entry
  changelog/body-deprecation.dd
Labels: auto-merge

#12215 Fix Issue 21651 - Unimported package doesn't error out when used as p…
  changelog/fqn-bypass-deprecation.dd
  src/dmd/todt.d
  src/dmd/typesem.d
  test/compilable/extra-files/serenity7190/core/Controller.d
  test/compilable/ice10598.d
  test/fail_compilation/ice10598.d
  test/fail_compilation/imports/ice10598a.d
  test/fail_compilation/imports/ice10598b.d
  test/fail_compilation/imports/test21651b.d
  test/fail_compilation/test21651.d
Labels: Bug Fix

#12245 DIP1034 move support for noreturn to backend
  src/dmd/backend/blockopt.d
  src/dmd/backend/cod1.d
  src/dmd/backend/cod2.d
  src/dmd/backend/cod3.d
  src/dmd/backend/dcgcv.d
  src/dmd/backend/evalu8.d
  src/dmd/e2ir.d
  src/dmd/glue.d
  test/runnable/noreturn1.d
Labels: New Language Feature, auto-merge-squash

#12261 fix Issue 21684 - Assert fail for Win32 with a struct larger than 64k…
  src/dmd/backend/cgobj.d
  test/compilable/fix21684.d
Labels: Bug Fix, Easy Review, auto-merge

#12269 Attempt at fixing Github actions on stable
  .github/workflows/runnable_cxx.yml
Labels: auto-merge

#12246 Fix Issue 16140 - while(auto x = y) does not behave like if(auto x = y)
  changelog/while-condition-assignment.dd
  src/dmd/astbase.d
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  src/dmd/parse.d
  src/dmd/statement.d
  src/dmd/statement.h
  src/dmd/statementsem.d
  test/compilable/extra-files/header2.d
  test/compilable/extra-files/header2.di
  test/compilable/extra-files/header2i.di
  test/runnable/test16140.d
Labels: Enhancement, auto-merge

#12273 Merge stable
  .github/workflows/runnable_cxx.yml
  VERSION
  changelog/abi-fix-creal.dd
  changelog/complex_types.dd
  changelog/copy-constructor-priority.dd
  changelog/ddoc-always-visibility.dd
  changelog/ddoc-shared-static-ctor.dd
  changelog/deprecate_dualcontext.dd
  changelog/dtoh-improvements.dd
  changelog/dwarf-switch.dd
  changelog/getVisibility.dd
  changelog/runtime-synchronized.dd
  changelog/shortfunctions.dd
  src/dmd/backend/cod3.d
  src/dmd/expressionsem.d
  src/dmd/optimize.d
  src/dmd/sideeffect.d
  test/compilable/extra-files/vcg-ast-arraylength-postscript.sh
  test/compilable/vcg-ast-arraylength.d
  test/runnable/ice21696.d
  test/runnable/testassert.d
Labels: Bug Fix, auto-merge

#12272 Replace for-loop by foreach
  src/dmd/mars.d
Labels: Refactoring, Trivial

#12276 gflow.d: use out, ref and const
  src/dmd/backend/gflow.d
Labels: Easy Review, Refactoring, auto-merge

#12271 gflow.d: make ambigsym from global to local
  src/dmd/backend/gflow.d
Labels: Easy Review, Refactoring

#12266 DIP1034 support noreturn as leaves of ?:
  src/dmd/e2ir.d
  src/dmd/expressionsem.d
  test/runnable/noreturn1.d
Labels: auto-merge

#12267 Fix Issue 21699 - Duplicate error for index out of bounds at compile time
  src/dmd/optimize.d
  test/fail_compilation/test6883.d
Labels: Bug Fix, auto-merge

#12277 Fix 21709 - Don't generate try-catch in betterC code for dtorfields
  src/dmd/semantic3.d
  test/compilable/dtorfields.d
Labels: Bug Fix, Regression, auto-merge

#12275 Working dmd on OpenBSD.
  ini/openbsd/bin32/dmd.conf
  ini/openbsd/bin64/dmd.conf
  src/dmd/backend/backconfig.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod1.d
  src/dmd/backend/dtype.d
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/os.d
  src/dmd/cli.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/link.d
  src/dmd/mars.d
  src/dmd/scanelf.d
  src/dmd/target.d
Labels: auto-merge

#12265 Issue 21693 - Lower scoped destruction of extern(C++) class to destroy/dtor call
  src/dmd/declaration.d
  test/runnable/cppdtor.d
  test/runnable_cxx/cppa.d
Labels: extern (C/C++)

#12260 Fix enclosesLifetimeOf for function parameters
  src/dmd/declaration.d
  test/compilable/scope.d
  test/fail_compilation/fail20108.d
  test/fail_compilation/retscope6.d
Labels: auto-merge

#12278 [cppmanglewin] factor Visibility mangling, constify
  src/dmd/cppmanglewin.d
Labels: Easy Review, Refactoring, Trivial, auto-merge

#12156 fix Issue 21585 - add __traits(totype, string) to convert mangled typ…
  src/dmd/dmangle.d
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/traits.d
  src/dmd/typesem.d
  test/compilable/fix21585.d
  test/fail_compilation/fix21585.d
Labels: Enhancement, auto-merge

#12282 fix Issue 21726 - Wrong comparison in package(...) visibilities
  changelog/package-visibility.dd
  src/dmd/attrib.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/frontend.h
  test/compilable/issue21726.d
  test/compilable/protection/issue21726/format/package.d
  test/compilable/protection/issue21726/package.d
  test/compilable/protection/issue21726/typecons.d
Labels: Bug Fix, auto-merge

#12285 issue 20415 - add test case
  test/compilable/ice20415.d
Labels: auto-merge

#12280 Fix 19387 - Mark generated postblits as scope
  src/dmd/dsymbolsem.d
  test/compilable/scope.d
Labels: Bug Fix, auto-merge

#12284 Fix issue 20599 - cpp_long as enum type doesn't work
  src/dmd/dsymbolsem.d
  test/compilable/issue20599.d
Labels: Bug Fix, Easy Review, auto-merge

#12283 move verifyMangleString into own function
  src/dmd/dsymbolsem.d
Labels: Easy Review, Refactoring, Trivial, auto-merge-squash

#12287 Fix issue 21687 - Confusing error message for CTFE
  src/dmd/initsem.d
  test/fail_compilation/test15989.d
Labels: Bug Fix, needs tests

#12264 fix issue 21630 - assert(0) and assert(false) should not be marked for coverage
  src/dmd/s2ir.d
  test/runnable/no_assertz_cov.d
Labels: Enhancement, auto-merge

#12289 Fix Issue 7352 - Poor error message when using variable as template type parameter
  src/dmd/dtemplate.d
  test/fail_compilation/fail134.d
  test/fail_compilation/fail7352.d
Labels: auto-merge

#12293 fix Issue 19443 - core.simd generates MOVLPS instead of MOVHLPS
  src/dmd/backend/cgxmm.d
  src/dmd/backend/xmm.d
  test/runnable/testxmm.d
Labels: Bug Fix, auto-merge

#12258 Fix Issue 20581 - DIP1000 wrongly flags hidden ref temporary
  src/dmd/declaration.d
  src/dmd/escape.d
  src/dmd/statement.d
  src/dmd/statementsem.d
  test/compilable/scope.d
  test/runnable/testassert.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#12201 DWARF: refactor debug frame header
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge

#12288 Fix issue 14145 - opDispatch not considered when function body doesn'…
  src/dmd/typesem.d
  test/fail_compilation/diag14145.d
  test/fail_compilation/fail18970.d
  test/fail_compilation/ice10938.d
Labels: 72h no objection -> merge, Bug Fix

#12206 DWARF: refactor debug line
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/outbuf.d
Labels: auto-merge-squash

#12297 fix Issue 21672 - [REG][ICE][SIMD] accessing SIMD type as a short cau…
  src/dmd/backend/cod1.d
  test/compilable/test21672.d
Labels: Bug Fix

#12298 Foreach sem refactor
  src/dmd/statementsem.d
Labels: Refactoring, auto-merge

#12300 Fix Issue 21753 - Struct literal with function literal member not allowed
  src/dmd/dmangle.d
  test/compilable/test21753.d
  test/runnable/mangle.d
Labels: Bug Fix, auto-merge

#12299 more refactoring of foreach semantic
  src/dmd/statementsem.d
Labels: Easy Review, Refactoring, Trivial

#12303 Revert "more refactoring of foreach semantic"
  src/dmd/statementsem.d
Labels: auto-merge

#12302 Fix issue 19192 - [wrong-code] [crashes] Covariant method interface <…
  src/dmd/dsymbolsem.d
  test/runnable/test19192.d
Labels: Bug Fix

#12305 Unbreak stable by adding missing import
  src/dmd/todt.d
Labels: Blocking Other Work, Trivial, auto-merge, stable-priority

#11835 Fix issue 21203: Accept pragma(mangle) on aggregate types
  changelog/pragma-mangle-aggregate.dd
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
  test/compilable/issue21203.d
  test/fail_compilation/issue21203.d
Labels: 72h no objection -> merge, Enhancement, auto-merge

#12306 Fix 21752 - Template constraint breaks nested eponymeous template
  src/dmd/dtemplate.d
  test/compilable/nested_template_constraints.d
Labels: Bug Fix, auto-merge

#12307 Fix 21765 - Assignment-as-condition error with checkaction=context
  src/dmd/expressionsem.d
  test/compilable/test20100.d
Labels: Bug Fix, auto-merge

#12304 fix Issue 21403 - dmd/backend/cgcs.d:375 assert failed
  src/dmd/e2ir.d
  test/runnable/test21403.d
Labels: Bug Fix, auto-merge

#12312 dmd.cli: Document the -fPIE command-line option
  src/dmd/cli.d
Labels: Easy Review, auto-merge, documentation

#12310 extend Issue 21403 fix to a~='c' and a~=1 operators
  src/dmd/e2ir.d
  test/runnable/test21403.d
Labels: auto-merge

#12315 Fix 21779 - Don't generate messages for disabled assertions
  src/dmd/expressionsem.d
  test/runnable/testassert_release.d
Labels: Bug Fix, auto-merge

#12320 dmd.target: Add TargetCPP.derivedClassOffset
  src/dmd/dclass.d
  src/dmd/frontend.h
  src/dmd/target.d
  src/dmd/target.h
Labels: GDC, Refactoring, auto-merge

#12319 dmd.target: Add TargetC.twchar_t for representing C wchar_t type
  src/dmd/chkformat.d
  src/dmd/dscope.d
  src/dmd/frontend.h
  src/dmd/target.d
  src/dmd/target.h
Labels: GDC, Refactoring, auto-merge

#12321 dmd.target: Add Target.libraryObjectMonitors for backends that handle synchronizing monitors inline
  src/dmd/frontend.h
  src/dmd/semantic3.d
  src/dmd/target.d
  src/dmd/target.h
Labels: GDC, Refactoring, auto-merge

#12317 [dtemplate] use early return
  src/dmd/dtemplate.d
Labels: Easy Review, Refactoring, Trivial

#12314 Remove references to the 'trig' math module
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/toir.d
Labels: auto-merge

#12322 move obj_ext, lib_ext, dll_ext and run_noext from global to target
  src/dmd/dmodule.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/glue.d
  src/dmd/lib.d
  src/dmd/link.d
  src/dmd/mars.d
  src/dmd/target.d
  src/dmd/target.h
Labels: Refactoring, auto-merge-squash

#12324 dmd.chkformat: Remove unused specifier argument in errorMsg
  src/dmd/chkformat.d
Labels: Refactoring, auto-merge

#12327 backend: begin transition to @safe code
  src/dmd/backend/oper.d
  src/dmd/backend/outbuf.d
  src/dmd/backend/ptrntab.d
  src/dmd/backend/ty.d
Labels: Easy Review, Refactoring
