Repository dlang/dmd, pull requests merged in 2021-01, with the labels that each got.

#12080 fix Issue 20652 - extern(C++) doesn't seem to mangle the types in core.simd right
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  test/runnable_cxx/extra-files/test20652.cpp
  test/runnable_cxx/test20652.d
Labels: Bug Fix, Enhancement, auto-merge

#12088 merge stable
  VERSION
  changelog/better-vtemplates.dd
  changelog/deprecate_visibility.dd
  changelog/deprecation-context.dd
  changelog/dtoh-improvements.dd
  changelog/duplicate-implementations-deprecation.dd
  changelog/extern-pascal.dd
  changelog/extern-std-cpp20.dd
  changelog/extern-std-standard.dd
  changelog/inclusive-incontracts.dd
  changelog/objc_protocols.dd
  changelog/pragma_inline_ctfe.dd
  changelog/traits-getcppnamespaces.dd
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/semantic2.d
  src/dmd/target.d
  test/compilable/test18385b.d
  test/compilable/test21514.d
  test/fail_compilation/test18385.d
  test/runnable_cxx/extra-files/test20652.cpp
  test/runnable_cxx/test20652.d
Labels: Bug Fix, auto-merge, stable -> master

#12083 fix Issue 11717 - CTFE: non-constant value with array and vector ops
  src/dmd/dinterpret.d
  test/compilable/interpret4.d
  test/fail_compilation/fail11717.d
  test/fail_compilation/fail_arrayop2.d
Labels: Bug Fix, auto-merge

#11110 fix issue 20788 - Difference between colored and non colored output
  src/dmd/errors.d
  test/compilable/testcolor.sh
Labels: Enhancement, auto-merge-squash

#12090 Fix 21518 - delegates not checked for attribute match in const arrays
  src/dmd/frontend.h
  src/dmd/mtype.d
  src/dmd/mtype.h
  test/fail_compilation/test21518.d
Labels: Bug Fix

#12087 Rename `Prot` struct, `protection` member, `prot()` to visibility/vis
  src/dmd/access.d
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/astbase.d
  src/dmd/astcodegen.d
  src/dmd/attrib.d
  src/dmd/attrib.h
  src/dmd/backend/cc.d
  src/dmd/backend/dcgcv.d
  src/dmd/backend/newman.d
  src/dmd/cppmanglewin.d
  src/dmd/dclass.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/denum.d
  src/dmd/dimport.d
  src/dmd/dmodule.d
  src/dmd/doc.d
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/dtoh.d
  src/dmd/enum.h
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/func.d
  src/dmd/hdrgen.d
  src/dmd/import.h
  src/dmd/json.d
  src/dmd/module.h
  src/dmd/nspace.d
  src/dmd/objc.d
  src/dmd/parse.d
  src/dmd/scope.h
  src/dmd/semantic3.d
  src/dmd/template.h
  src/dmd/tocvdebug.d
  src/dmd/toobj.d
  src/dmd/traits.d
  src/dmd/typesem.d
  test/fail_compilation/ice13385.d
  test/fail_compilation/parseStc2.d
  test/fail_compilation/protattr1.d
  test/fail_compilation/protattr2.d
Labels: auto-merge

#12089 Add getVisibility trait as an alias to getProtection
  changelog/getVisibility.dd
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/traits.d
  test/runnable/traits.d
Labels: auto-merge

#11824 Use run-time allocated mutexes for plain `synchronized` statements
  changelog/runtime-synchronized.dd
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/statementsem.d
  src/dmd/target.d
  src/dmd/target.h
Labels: auto-merge

#12092 Fix Issue 21481 - functions in overloaded template are lost when the …
  src/dmd/declaration.d
  test/runnable/overload.d
Labels: Bug Fix, auto-merge

#12091 Fix Issue 21522 - function gets lost when aliasing an overloaded funct…
  src/dmd/declaration.d
  test/runnable/overload.d
Labels: Bug Fix, auto-merge

#12096 Fix typo in test/README
  test/README.md
Labels: auto-merge

#12099 DWARF debug infos: Don't name ulong 'uint long'
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge

#12100 DWARF debug infos: "handle" multi dimensional arrays
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge

#12103 fix Issue 21527 - Unnecessary store to memory in SIMD code
  src/dmd/backend/cod1.d
Labels: Enhancement, auto-merge

#12105 [stable] Fix little C++ header regression
  src/dmd/scope.h
Labels: auto-merge

#12104 [dmd-cxx] Support UDAs for function arguments and single-parameter alias declarations
  src/arrayop.c
  src/clone.c
  src/cond.c
  src/declaration.c
  src/dtemplate.c
  src/expression.c
  src/expressionsem.c
  src/func.c
  src/hdrgen.c
  src/mtype.c
  src/mtype.h
  src/parse.c
  src/statementsem.c
  src/traits.c
  test/compilable/extra-files/header1.d
  test/compilable/extra-files/header1.di
  test/compilable/extra-files/header1i.di
  test/compilable/testheaderudamodule.d
  test/fail_compilation/fail10207.d
  test/fail_compilation/trait_loc_err.d
  test/fail_compilation/udaparams.d
  test/runnable/uda.d
Labels: auto-merge

#12106 [dmd-cxx] Implement new syntax for contracts and invariants
  src/arraytypes.h
  src/declaration.h
  src/func.c
  src/hdrgen.c
  src/parse.c
  src/statement.c
  src/statement.h
  test/compilable/extra-files/header1.d
  test/compilable/extra-files/header1.di
  test/compilable/extra-files/header1i.di
  test/compilable/vcg-ast.d
  test/fail_compilation/fail17502.d
  test/fail_compilation/fail_contracts1.d
  test/fail_compilation/fail_contracts2.d
  test/fail_compilation/fail_contracts3.d
  test/fail_compilation/fail_contracts4.d
  test/runnable/testcontracts.d
Labels: C++ Port, Easy Review, GDC

#12034 Fix Issue 21489 - Duplicated template instantiation using mixin insid…
  src/dmd/astbase.d
  src/dmd/frontend.h
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/typesem.d
  test/compilable/vtemplates_list.d
  test/fail_compilation/mixintype2.d
Labels: Bug Fix

#12108 [dmd-cxx] Support deprecated, @disable and user-defined attributes on enum members
  src/declaration.c
  src/declaration.h
  src/denum.c
  src/dsymbol.c
  src/dsymbol.h
  src/enum.h
  src/expression.c
  src/expression.h
  src/expressionsem.c
  src/mtype.c
  src/parse.c
  src/traits.c
  test/compilable/test17908.d
  test/compilable/test9701.d
  test/fail_compilation/disable.d
  test/fail_compilation/fail10968.d
  test/fail_compilation/fail11355.d
  test/fail_compilation/fail15044.d
  test/fail_compilation/fail341.d
  test/fail_compilation/fail9346.d
  test/fail_compilation/test17908a.d
  test/fail_compilation/test17908b.d
  test/fail_compilation/test9701.d
  test/fail_compilation/test9701b.d
Labels: C++ Port, Easy Review, GDC, auto-merge

#12062 Replace Visibility.isMoreRestrictiveThan with opCmp
  src/dmd/access.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
Labels: Easy Review, auto-merge

#12094 Fix issue 21177 - printf check does not recognize GNU extensions
  src/dmd/chkformat.d
  src/dmd/cond.d
  test/compilable/test21177.d
Labels: Bug Fix

#9702 Deprecate "Fix for the non-global template issue 5710"
  changelog/deprecate_dualcontext.dd
  src/dmd/semantic3.d
  test/compilable/test20063.d
  test/compilable/test324.d
  test/fail_compilation/nestedtempl1.d
  test/fail_compilation/nestedtempl2.d
  test/runnable/template10.d
Labels: Blocking Other Work, Bug Fix, Regression, auto-merge

#12107 [stable] Fix C++ header regressions
  src/dmd/aggregate.h
  src/dmd/objc.h
Labels: auto-merge

#11917 Fix Issue 21352 - enum members should not be given UDAs of its parent…
  src/dmd/dsymbolsem.d
  test/compilable/test20835.d
Labels: Bug Fix, auto-merge

#12102 fix Issue 21526 - x87 not rounding to precision on assignment on some…
  src/dmd/backend/glocal.d
  test/runnable/mars1.d
Labels: Bug Fix

#12110 use XMM registers when moving params to stack
  src/dmd/backend/cod1.d
Labels: auto-merge

#11936 dtoh: Generate fieldwise constructors for aggregates
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_21217.d
  test/compilable/dtoh_ClassDeclaration.d
  test/compilable/dtoh_StructDeclaration.d
  test/compilable/dtoh_TemplateDeclaration.d
  test/compilable/dtoh_cpp98_compat.d
  test/compilable/dtoh_enum.d
  test/compilable/dtoh_enum_cpp98.d
  test/compilable/dtoh_extern_type.d
  test/compilable/dtoh_functions.d
  test/compilable/dtoh_protection.d
Labels: auto-merge, dtoh

#11761 dtoh: Warn about use of C++ keywords as identifiers during -HC generation
  src/build.d
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_invalid_identifiers.d
Labels: auto-merge, dtoh

#12113 Remove unused traits identifier 'parameters'
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/traits.d
  test/fail_compilation/diag11819b.d
Labels: auto-merge

#12028 use Identifier[] instead of Array!Identifier * for package names
  src/dmd/astbase.d
  src/dmd/attrib.d
  src/dmd/attrib.h
  src/dmd/builtin.d
  src/dmd/compiler.d
  src/dmd/dimport.d
  src/dmd/dmodule.d
  src/dmd/doc.d
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  src/dmd/import.h
  src/dmd/json.d
  src/dmd/parse.d
  src/dmd/toir.d
  test/dub_package/impvisitor.d
Labels: 72h no objection -> merge

#12118 dtoh_ Enable checks for C++20 keywords
  src/dmd/dtoh.d
  test/compilable/dtoh_invalid_identifiers.d
Labels: auto-merge

#12114 enum ILS should be a ubyte
  src/dmd/declaration.h
  src/dmd/frontend.h
  src/dmd/func.d
Labels: Easy Review, Refactoring, auto-merge

#12115 build.d: Enable -cov=ctfe for recent host compilers
  .circleci/run.sh
  src/bootstrap.sh
  src/build.d
Labels: auto-merge

#12117 Fix 21534 - dtoh: Default params for default ctor missing template args
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_TemplateDeclaration.d
Labels: Bug Fix

#12111 changelog/deprecate_dualcontext: Reword to neutral tone
  changelog/deprecate_dualcontext.dd
Labels: 72h no objection -> merge, Trivial, auto-merge

#12125 [dmd-cxx] Fix Issue 21353 - 'with()' statement ignores symbol visibility in some cases
  src/expressionsem.c
  test/fail_compilation/imports/imp21353.d
  test/fail_compilation/test21353.d
Labels: C++ Port, Easy Review, GDC, auto-merge

#12128 dmangle: publics go above the fold
  src/dmd/dmangle.d
Labels: Easy Review, Refactoring

#12126 run.d: Dump env directly after processing environment variables...
  test/run.d
Labels: Build System

#11762 Move DMD-specific params
  src/dmd/dmsc.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/link.d
  src/dmd/mars.d
Labels: auto-merge

#12116 Issue 21519 - Generate coverage reports on Azure
  .azure-pipelines/windows.sh
  azure-pipelines.yml
Labels: auto-merge

#12119 fix Issue 20565 - Local template declarations in different scopes produce…
  src/dmd/dmangle.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  test/compilable/test11720.d
  test/compilable/test1537.d
  test/fail_compilation/fail11720.d
  test/fail_compilation/fail18266.d
  test/fail_compilation/test20565.d
  test/runnable/test20565.d
Labels: Bug Fix, auto-merge

#11934 Add location to linkage symbols
  src/dmd/astbase.d
  src/dmd/attrib.d
  src/dmd/attrib.h
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
  src/dmd/parse.d
  src/tests/cxxfrontend.c
  test/unit/parser/linkage_location.d
Labels: Enhancement, auto-merge

#12129 dtoh: Don't emit template instances for class declarations
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_TemplateDeclaration.d
Labels: auto-merge, dtoh

#12049 Extend -makedeps to all targets
  src/dmd/cli.d
  src/dmd/dmodule.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/lib.d
  src/dmd/mars.d
  src/dmd/utils.d
  test/compilable/extra-files/makedeps-import-codemixin.txt
  test/compilable/extra-files/makedeps.sh
  test/compilable/extra-files/makedeps_a.d
  test/compilable/imports/makedeps_a.d
  test/compilable/makedeps-stdout.sh
  test/compilable/makedeps.d
  test/compilable/makedeps_exe.d
  test/compilable/makedeps_file.d
  test/compilable/makedeps_lib.d
  test/compilable/makedeps_obj.d
  test/fail_compilation/makedeps_multiobj.d
Labels: Bug Fix, Enhancement

#12130 dtoh: Emit template arguments for instantiated base classes
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_TemplateDeclaration.d
Labels: auto-merge, dtoh

#12122 Fix 21530 - dtoh: Sanitize identifiers wrt. reserved C++ keywords
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_invalid_identifiers.d
  test/dshell/extra-files/cpp_header_gen/app.cpp
  test/dshell/extra-files/cpp_header_gen/library.d
Labels: Bug Fix, auto-merge, dtoh

#12120 Issue 21519 - Generate coverage reports on CirrusCI
  .cirrus.yml
  ci.sh
Labels: 72h no objection -> merge

#12127 Fix Issue 20868 - DIP1000: scope delegate triggers error in unsafe co…
  src/dmd/escape.d
  test/compilable/test20868.d
Labels: Bug Fix, Enhancement, auto-merge, industry

#12029 extend PR #11846 to add symbol support for AliasAssign
  src/dmd/astbase.d
  src/dmd/dsymbol.d
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  src/dmd/parse.d
  src/dmd/transitivevisitor.d
  test/fail_compilation/aliasassign.d
  test/runnable/aliasassign.d
Labels: Language Experiment, auto-merge

#11834 Tnone should not have a mangle.
  src/dmd/dmangle.d
Labels: Easy Review

#12132 Fix Issues 20695, 21547 - CpCtor disables default construction + Struct initializers are disabled wrongfully
  src/dmd/aggregate.h
  src/dmd/dstruct.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/initsem.d
  test/compilable/test20695.d
  test/fail_compilation/fail21547.d
Labels: Bug Fix, industry

#12133 fix Issue 21553 - incorrect call to expressionSemantic() in statement…
  src/dmd/dcast.d
  src/dmd/statementsem.d
Labels: Bug Fix

#12135 [dmd-cxx] Fix Issue 15371 - __traits(getMember) should bypass the protection
  src/traits.c
  test/compilable/imports/test15371.d
  test/compilable/test15371.d
Labels: C++ Port, Easy Review, GDC

#12121 test: Remove empty TEST_OUTPUT directives
  test/compilable/callconv.d
  test/compilable/checkimports3.d
  test/compilable/cppmangle.d
  test/compilable/cppmangle3.d
  test/compilable/ddoc14633.d
  test/compilable/ddoc15475.d
  test/compilable/deprecate14283.d
  test/compilable/diag11066.d
  test/compilable/diag12598.d
  test/compilable/diag3243.d
  test/compilable/extra-files/json.out
  test/compilable/json.d
  test/compilable/readmodify_structclass.d
  test/compilable/test1170.d
  test/compilable/test12567a.d
  test/compilable/test12567b.d
  test/compilable/test12567d.d
  test/compilable/test12567e.d
  test/compilable/test13053.d
  test/compilable/test14375.d
  test/compilable/test15371.d
  test/compilable/test1547.d
  test/compilable/test15785.d
  test/compilable/test15856.d
  test/compilable/test17419.d
  test/compilable/test17752.d
  test/compilable/test17791.d
  test/compilable/test19809.d
  test/compilable/test20051.d
  test/compilable/test20100.d
  test/compilable/test20136.d
  test/compilable/test20406.d
  test/compilable/test7815.d
  test/compilable/test9029.d
  test/compilable/test930.d
  test/compilable/testCpCtor.d
  test/compilable/testcheckimports.d
  test/compilable/warn3882.d
  test/runnable/argufilem.d
  test/runnable/b10562.d
  test/runnable/foreach4.d
  test/runnable/test15.d
  test/runnable/test19122.d
  test/runnable/test19441.d
  test/runnable/test19774.d
  test/runnable/test19782.d
  test/runnable/test19822.d
  test/runnable/test20025.d
  test/runnable/test711.d
  test/runnable/test809.d
  test/runnable/testargtypes.d
Labels: Trivial

#12138 Backend: Remove workaround for POSIX extension
  src/dmd/backend/dwarfdbginf.d
Labels: Refactoring, auto-merge

#12139 Backend: Add a link to DMC's source code
  src/dmd/backend/README.md
Labels: Trivial, auto-merge

#12141 Fix build regression in printast.d for real.sizeof == 8
  src/dmd/printast.d
Labels: Regression, Trivial, auto-merge

#12143 Fix 21569: Set RES path relative to build.d's directory
  src/build.d
Labels: Bug Fix, Build System, Regression, auto-merge

#12144 Fix 21567 - build.d install fails for sources from official releases
  src/build.d
Labels: Build System, Enhancement

#12147 eliminate tzero
  src/dmd/backend/dtype.d
Labels: Easy Review, Refactoring, auto-merge

#12149 cgsched.d: mark functions public or private
  src/dmd/backend/cgsched.d
Labels: Easy Review, Refactoring, auto-merge

#12148 bring enum LANG into conformance with DMC++
  src/dmd/backend/cc.d
  src/dmd/backend/cdef.d
Labels: Easy Review, Refactoring, auto-merge

#12146 Revert "Backend: Cleanup dlist"
  src/dmd/backend/dlist.d
Labels: Backend, auto-merge

#12073 fix Issue 21515 extern(C) and extern(C++) returns creal in wrong order
  changelog/abi-fix-creal.dd
  src/dmd/backend/cg87.d
  src/dmd/backend/cod1.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code.d
  test/runnable/test21515.d
  test/runnable_cxx/extra-files/test21515.cpp
  test/runnable_cxx/test21515.d
Labels: 72h no objection -> merge, Blocking Other Work, Bug Fix, auto-merge

#12151 array.h: Default initialize Array with zeroes
  src/dmd/root/array.h
Labels: Easy Review, auto-merge

#12152 dmd.declaration: Fix syntax highlighting on 'this' parameter in message
  src/dmd/declaration.d
  test/fail_compilation/fail18143.d
Labels: Easy Review, auto-merge

#12153 [dmd-cxx] Backport fixes for issue 18143 and 18719.
  src/declaration.c
  src/expressionsem.c
  src/func.c
  src/root/array.h
  test/fail_compilation/fail18143.d
  test/fail_compilation/fail18719.d
Labels: Bug Fix, C++ Port, Easy Review, GDC, auto-merge

#12155 [dmd-cxx] Rename Compiler::loadModule to onParseModule, define onImport.
  src/compiler.c
  src/compiler.h
  src/dmodule.c
Labels: C++ Port, Easy Review, GDC, auto-merge

#12157 Fix Issue 21543 - dmd infinite loop on alias this and std.typecons.Nu…
  src/dmd/mtype.d
  test/compilable/test21543.d
Labels: Bug Fix, auto-merge

#12158 printAST: Use printfloat instead of printf to format RealExp's
  src/dmd/printast.d
Labels: auto-merge

#11705 [RFC] Unify handling of revertable changes
  src/dmd/cli.d
  src/dmd/escape.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/mars.d
Labels: auto-merge

#12012 Reboot of Fix issue 20235 - caller destroys arguments on POSIX #10593
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/e2ir.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/inline.d
  src/dmd/opover.d
  src/dmd/semantic3.d
  src/dmd/target.d
  src/dmd/target.h
  test/runnable/sdtor.d
  test/runnable_cxx/cpp_abi_tests.d
  test/runnable_cxx/extra-files/cpp_abi_tests.cpp
Labels: Bug Fix, auto-merge, industry

#12164 Replace approxEqual with isClose
  test/compilable/ctfe_math.d
  test/runnable/builtin.d
Labels: auto-merge

#12165 Fix 21590 - assignment inside assert accepted for -checkaction=context
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  test/fail_compilation/dassert.d
  test/runnable/testassert.d
Labels: Bug Fix

#12162 Issue 20235 - Simplify fix by not declaring __gate
  src/dmd/expressionsem.d
Labels: 72h no objection -> merge

#12161 Fix Issue 16635 - Alias this for implicit conversion to "ref const(typeof(this))" causes dmd to segfault
  src/dmd/dcast.d
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/opover.d
  src/dmd/statementsem.d
  test/compilable/test16635.d
Labels: 72h no objection -> merge, Bug Fix

#12053 Fix duplicate function detection for overloads introduced by aliases
  src/dmd/dmangle.d
  src/dmd/mtype.d
  src/dmd/semantic2.d
  test/fail_compilation/fail2789.d
  test/fail_compilation/test18385b.d
Labels: 72h no objection -> merge, Bug Fix

#11656 Enable preview=dtorFields by default
  changelog/dtorfileds.md
  src/dmd/cli.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/mars.d
  src/dmd/semantic3.d
  test/compilable/dtorfields_deprecation.d
  test/compilable/previewhelp.d
  test/compilable/reverthelp.d
  test/compilable/riia_ctor.d
  test/runnable_cxx/cppa.d
Labels: 72h no objection -> merge

#11509 Add `-gdwarf=<version>` compiler switch
  changelog/dwarf-switch.dd
  src/dmd/backend/backconfig.d
  src/dmd/backend/cdef.d
  src/dmd/backend/dwarf.d
  src/dmd/backend/dwarfdbginf.d
  src/dmd/cli.d
  src/dmd/dmsc.d
  src/dmd/mars.d
Labels: 72h no objection -> merge

#12163 Fix Issue 21586 - Struct dtor is called twice if struct is created in…
  src/dmd/expressionsem.d
  test/runnable/test21586.d
Labels: 72h no objection -> merge, Bug Fix, Enhancement
