Repository dlang/dmd, pull requests merged in 2021-02, with the labels that each got.

#12170 Fix 21471,21598 - Always create a temporary for calls with checkactio…
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/sideeffect.d
  test/runnable/testassert.d
  test/runnable/testassert_debug.d
Labels: auto-merge

#12172 dtoh: Ignore special enums in header generation
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  test/compilable/dtoh_special_enum.d
Labels: Easy Review, auto-merge, dtoh

#12174 [dmd-cxx] add OutBuffer.print()
  src/dmangle.c
  src/root/outbuffer.c
  src/root/outbuffer.h
Labels: Bug Fix, C++ Port, GDC, auto-merge

#12175 fix DMC breakage from PR 10200
  src/dmd/backend/cod1.d
  src/dmd/backend/cod3.d
Labels: auto-merge

#12169 Fix Issue 21593 - Only update file time if file to be written already exists
  src/dmd/mars.d
  src/dmd/root/file.d
  src/dmd/utils.d
Labels: Enhancement

#12179 [dmd-cxx] Backport builtin function handling from master
  src/backend/cod2.c
  src/backend/evalu8.c
  src/backend/glocal.c
  src/builtin.c
  src/declaration.h
  src/dinterpret.c
  src/idgen.c
  src/mars.c
  src/root/ctfloat.c
  src/root/ctfloat.h
  src/toir.c
  src/toir.h
Labels: C++ Port, GDC

#12166 [stable] Fix Issue 21591 - missed backrefs in mangled names wrt. unmerged function types
  src/dmd/dmangle.d
  test/compilable/test21591.d
Labels: 72h no objection -> merge, Bug Fix, industry

#12167 Add `__c_complex_float`, `__c_complex_double`, and `__c_complex_real` types
  changelog/complex_types.dd
  src/dmd/cppmangle.d
  src/dmd/denum.d
  src/dmd/dtoh.d
  src/dmd/e2ir.d
  src/dmd/frontend.h
  src/dmd/glue.d
  src/dmd/id.d
  src/dmd/target.d
  src/dmd/toctype.d
  test/compilable/dtoh_special_enum.d
  test/runnable/test21515.d
  test/runnable_cxx/test21515.d
Labels: 72h no objection -> merge

#12177 fix Issue 21513 - [Reg 2.094.1] Slice assignment segmentation fault
  src/dmd/backend/cod2.d
  test/runnable/mars1.d
Labels: Bug Fix, Enhancement

#12181 Remove duplicate import
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge

#12182 Add DWARFv5 data representation
  src/dmd/backend/dwarf2.d
Labels: auto-merge

#12184 cod3: replace complex logic with Posix test
  src/dmd/backend/cod3.d
Labels: Easy Review, Refactoring

#12185 DWARF: Change "children" magical number to enumerator
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge

#12186 refactor allocretregs to use out
  src/dmd/backend/cod1.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code.d
Labels: Easy Review, Refactoring

#12178 Fix 21508: Do not look inside imports that shadow a symbol
  src/dmd/typesem.d
  test/fail_compilation/fail21508.d
  test/fail_compilation/fail21508_2.d
  test/fail_compilation/imports/import21508.d
  test/runnable/imports/Other.d
Labels: Bug Fix

#12189 Cirrus CI Mac: Exploit all 12 newly available CPU cores
  .cirrus.yml
Labels: Continuous Integration, auto-merge

#12188 allocretregs: remove dead code, add const
  src/dmd/backend/cod3.d
  src/dmd/backend/code.d
Labels: Easy Review, Refactoring

#12191 fix Issue 21614 - AssertError@src/dmd/semantic3.d(812): Assertion failure
  src/dmd/semantic2.d
  test/compilable/imports/issue21614a.d
  test/compilable/issue21614.d
Labels: Bug Fix, Enhancement, auto-merge

#12195 Merge stable
  VERSION
  src/build.d
  src/dmd/aggregate.h
  src/dmd/backend/cod2.d
  src/dmd/chkformat.d
  src/dmd/cli.d
  src/dmd/cond.d
  src/dmd/dmangle.d
  src/dmd/dmodule.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/lib.d
  src/dmd/mars.d
  src/dmd/mtype.d
  src/dmd/objc.h
  src/dmd/scope.h
  src/dmd/semantic2.d
  src/dmd/utils.d
  test/compilable/extra-files/makedeps-import-codemixin.txt
  test/compilable/extra-files/makedeps.sh
  test/compilable/extra-files/makedeps_a.d
  test/compilable/imports/issue21614a.d
  test/compilable/imports/makedeps_a.d
  test/compilable/issue21614.d
  test/compilable/makedeps-stdout.sh
  test/compilable/makedeps.d
  test/compilable/makedeps_exe.d
  test/compilable/makedeps_file.d
  test/compilable/makedeps_lib.d
  test/compilable/makedeps_obj.d
  test/compilable/test21177.d
  test/compilable/test21591.d
  test/fail_compilation/dassert.d
  test/fail_compilation/fail2789.d
  test/fail_compilation/makedeps_multiobj.d
  test/fail_compilation/test18385b.d
  test/runnable/mars1.d
  test/runnable/test21586.d
  test/runnable/testassert.d
Labels: Enhancement

#12168 Fix Issue 13667 - ICE: stack overflow using self-referencing cast ins…
  src/dmd/dcast.d
  src/dmd/opover.d
  test/fail_compilation/test13667.d
Labels: Bug Fix, auto-merge

#12197 Fix issue #21640: @live not working with templates
  src/dmd/mtype.d
  test/compilable/ob2.d
  test/fail_compilation/failob2.d
Labels: Bug Fix, auto-merge

#12198 tests: ob: add required args for dip1021 preview on borrowing tests
  test/compilable/ob1.d
Labels: Trivial, auto-merge

#12196 DWARF: refactor debug info header
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge-squash

#12202 DWARF: improve `rewrite` template
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge

#12183 Update description of DWARF files
  src/dmd/backend/README.md
  src/dmd/backend/dwarf.d
Labels: auto-merge

#12055 Fix 21472 - Support tuple comparison with `-checkaction=context` (2/2)
  src/dmd/expressionsem.d
  test/runnable/testassert.d
Labels: auto-merge

#12205 DIP1034 add TypeNoreturn to astbase.d and mtype.d
  src/dmd/astbase.d
  src/dmd/dmangle.d
  src/dmd/frontend.h
  src/dmd/mtype.d
Labels: New Language Feature

#12212 Fix issue 21648: remove two lines from dsymbolsem.d.
  src/dmd/dsymbolsem.d
  test/fail_compilation/fail21648.d
Labels: Bug Fix, auto-merge

#12209 DIP1034: add typeof(*null)
  src/dmd/expressionsem.d
  src/dmd/hdrgen.d
  test/compilable/noreturn1.d
Labels: Easy Review, New Language Feature

#12214 DIP 1034: add name mangling
  src/dmd/astbase.d
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/dmangle.d
  src/dmd/frontend.h
  src/dmd/mtype.d
  src/dmd/parsetimevisitor.d
  src/dmd/strictvisitor.d
  src/dmd/visitor.h
  test/compilable/cppmangle.d
  test/runnable/mangle.d
Labels: New Language Feature

#12187 dmd.dsymbolsem: Assign return value of Scope.createGlobal to 'sc'
  src/dmd/dmodule.d
  src/dmd/dsymbolsem.d
  src/tests/cxxfrontend.c
Labels: Bug Fix

#12217 DIP1034: tag functions for code generator that don't return
  src/dmd/glue.d
  src/dmd/semantic3.d
  src/dmd/tocsym.d
  test/compilable/noreturn1.d
Labels: New Language Feature

#12218 remove unnecessary error recovery code gen
  src/dmd/semantic3.d
Labels: Easy Review, Refactoring, auto-merge

#12213 Revert "Fix issue 21648: remove two lines from dsymbolsem.d."
  src/dmd/dsymbolsem.d
  test/fail_compilation/fail21648.d
Labels: auto-merge

#12221 Workaround for issue 21654 - CodeCov build already finished
  .codecov.yml
Labels: auto-merge

#12216 merge stable
  VERSION
Labels: auto-merge

#12220 Separate BCexit code from BCret code
  src/dmd/backend/cod3.d
Labels: Easy Review, Refactoring, auto-merge

#12211 fix Issue 21647 - pragma(msg) should be able to print a void type
  src/dmd/ctfeexpr.d
  src/dmd/dsymbolsem.d
  src/dmd/hdrgen.d
  test/compilable/fix21647.d
  test/fail_compilation/fail17382.d
  test/fail_compilation/ice8255.d
Labels: Bug Fix, auto-merge

#12222 DIP 1034: detect noreturn statements
  src/dmd/blockexit.d
  test/fail_compilation/warn12809.d
Labels: Easy Review, New Language Feature

#12225 Fix 21659: Special enums are never forward referenced
  src/dmd/denum.d
  test/compilable/test21659.d
Labels: Bug Fix, auto-merge

#12229 CircleCI: Ignore coverage upload failures
  .circleci/run.sh
Labels: Continuous Integration, Easy Review, auto-merge

#12231 Extern linkage variables cannot be of types with disabled default construction
  src/dmd/dsymbolsem.d
  test/compilable/issue21662.d
Labels: Bug Fix, auto-merge

#12230 Fix Issue 21661 - Can't use fully-qualified name of the current modul…
  src/dmd/dmodule.d
  test/compilable/test21661.d
Labels: Bug Fix

#12234 DIP1034: add TYnoreturn
  src/dmd/backend/ty.d
  src/dmd/backend/var.d
Labels: New Language Feature

#12237 iftrue, iffalse whitespace formatting
  src/dmd/backend/evalu8.d
Labels: Easy Review, Refactoring, Trivial, auto-merge

#12238 merge stable
  VERSION
  src/dmd/dsymbolsem.d
  test/compilable/issue21662.d
Labels: Bug Fix, auto-merge, stable -> master

#12240 Fix 14954 - extern opaque struct instance doesn't compile
  src/dmd/dsymbolsem.d
  test/compilable/imports/test14954_implementation.d
  test/compilable/test14954.d
  test/compilable/test21668.d
Labels: Bug Fix, auto-merge

#12219 test: Move runnable tests for complex and imaginary types into runnable/complex.d
  test/runnable/casting.d
  test/runnable/complex.d
  test/runnable/constfold.d
  test/runnable/ifti.d
  test/runnable/mars1.d
  test/runnable/template4.d
  test/runnable/template9.d
  test/runnable/test15.d
  test/runnable/test17965.d
  test/runnable/test18772.d
  test/runnable/test20.d
  test/runnable/test22.d
  test/runnable/test23.d
  test/runnable/test28.d
  test/runnable/test4.d
  test/runnable/test42.d
  test/runnable/test8.d
  test/runnable/testargtypes.d
  test/runnable/testconst.d
  test/runnable/testdstress.d
  test/runnable/testtypeid.d
  test/runnable/traits.d
  test/runnable/traits_getPointerBitmap.d
  test/runnable/ufcs.d
  test/runnable/uniformctor.d
  test/runnable/xtest46.d
Labels: Easy Review, auto-merge

#12239 Fix 21668 - Cannot declare ref parameter of opaque type
  src/dmd/dsymbolsem.d
  test/compilable/test21668.d
Labels: Bug Fix

#12236 Fix 10619 - Wrong local variable passed as alias arguments to templates
  src/dmd/dsymbol.d
  test/runnable/test10619.d
Labels: Bug Fix, Regression, auto-merge

#12241 Add shortened functions changelog
  changelog/shortfunctions.dd
Labels: auto-merge
