Repository dlang/dmd, pull requests merged in 2021-10, with the labels that each got.

#13124 cirrusci.sh: Run brew style --fix before installing gnupg
  cirrusci.sh
Labels: Easy Review, Continuous Integration

#13128 Revert "cirrusci.sh: Run brew style --fix before installing gnupg"
  cirrusci.sh
Labels: auto-merge

#13125 Fix issue 22355: LLD fallback for mscoff is broken in the presence of…
  src/dmd/link.d
  src/dmd/vsoptions.d
Labels: Enhancement, auto-merge

#13126 Fix Issue 22356 - Can't mixin the return type of a function
  src/dmd/parse.d
  test/compilable/mixintype2.d
Labels: auto-merge, Bug Fix

#13123 Cherry-pick add/improve function Ddoc comments (#13065) from master
  src/dmd/aliasthis.d
  src/dmd/expressionsem.d
  src/dmd/typesem.d
Labels: Blocking Other Work, auto-merge, documentation

#13118 Fix Issue 13009 - [REG2.064] inout overload conflicts with non-inout when used via alias this
  src/dmd/expressionsem.d
  test/runnable/aliasthis.d
Labels: Bug Fix

#13048 Fix Issue 22278 - [Conditional Compilation] there should be in and out flags
  src/dmd/mars.d
  test/fail_compilation/reserved_version.d
  test/fail_compilation/reserved_version_switch.d
  test/runnable/test22278.d
Labels: Enhancement, Atila Neves, Walter Bright

#13129 [stable] Cherry-pick #12995 (backend ICE)
  src/dmd/backend/cgelem.d
  test/compilable/test22226.d
Labels: Blocking Other Work, auto-merge, Bug Fix

#13122 hdrgen: remove trailing whitespace on enum declarations
  src/dmd/hdrgen.d
  test/compilable/extra-files/header1.di
  test/compilable/extra-files/header1i.di
Labels: Enhancement, auto-merge

#13121 hdrgen: remove trailing whitespace on attribute declarations
  src/dmd/hdrgen.d
  test/compilable/extra-files/header1.di
  test/compilable/extra-files/header1i.di
Labels: Enhancement, auto-merge

#13120 dwarfdbginf: DWARF array tags should not be ambiguous
  src/dmd/backend/dwarfdbginf.d
  test/dshell/extra-files/dwarf/excepted_results/fix22352.txt
  test/dshell/extra-files/dwarf/fix22352.d
  test/runnable/gdb_slice_debuginfo_32.d
  test/runnable/gdb_slice_debuginfo_64.d
Labels: Enhancement, auto-merge-squash

#13068 fix Issue 22287 - ambiguous virtual function for extern(C++) under Wi…
  src/dmd/dclass.d
  src/dmd/func.d
  test/runnable_cxx/extra-files/cpp22287.cpp
  test/runnable_cxx/test22287.d
Labels: auto-merge, Bug Fix

#13112 ImportC: implement #pragma pack
  src/dmd/aggregate.d
  src/dmd/astbase.d
  src/dmd/attrib.d
  src/dmd/cparse.d
  src/dmd/dclass.d
  src/dmd/declaration.d
  src/dmd/dscope.d
  src/dmd/dstruct.d
  src/dmd/dsymbolsem.d
  src/dmd/dtoh.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/lexer.d
  src/dmd/toir.d
  test/compilable/pragma.c
  test/fail_compilation/pragma2.c
Labels: ImportC

#13119 Fix Issue 22329 - DMD and LDC2 Segumentation Faults due to alias this
  src/dmd/aliasthis.d
  src/dmd/frontend.h
  src/dmd/mtype.d
  src/dmd/opover.d
  src/dmd/typesem.d
  test/fail_compilation/imports/imp22329.d
  test/fail_compilation/test22329.d
Labels: Bug Fix

#13131 Additional tests for bug 22292
  test/compilable/test22292.d
Labels: auto-merge, Easy Review

#13239 common: outbuffer: annotate pure and clarify branching on LEB128 func…
  src/dmd/common/outbuffer.d
Labels: auto-merge, Easy Review

#13240 tocsym: simplify ctype conversion branch on VarDeclaration visitor
  src/dmd/tocsym.d
Labels: auto-merge, Easy Review, Refactoring

#13245 fix sizeof for pthread_mutex_t on Solaris
  src/dmd/backend/os.d
Labels: auto-merge

#13241 backend: dwarfdbginf: use distinguishable type names for delegate types
  src/dmd/backend/dwarfdbginf.d
  src/dmd/toctype.d
  test/dshell/extra-files/dwarf/delegates.d
  test/dshell/extra-files/dwarf/excepted_results/delegates.txt
Labels: Enhancement, auto-merge
