Repository dlang/dmd, pull requests merged in 2021-05, with the labels that each got.

#12492 change Parentheses singular to Parenthesis
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  src/dmd/iasmdmd.d
  src/dmd/iasmgcc.d
  src/dmd/lexer.d
  src/dmd/parse.d
  src/dmd/tokens.d
  test/dub_package/lexer.d
  test/unit/lexer/location_offset.d
Labels: Refactoring, Trivial, auto-merge

#12494 Improve error message for missing response file
  src/dmd/mars.d
  src/dmd/root/response.d
  test/fail_compilation/responsefile.d
Labels: auto-merge

#12493 fix Issue 21880 - [REG 2.095] scope variable assigned to non-scope parameter calling function
  src/dmd/expressionsem.d
  test/compilable/issue21880.d
Labels: Bug Fix

#12489 unique implies there is only one instance of it whereas distinct is m…
  src/dmd/dtemplate.d
  test/compilable/vtemplates.d
  test/compilable/vtemplates_list.d
Labels: 72h no objection -> merge

#12498 fix Issue 21882 - [ICE, dip1021] src/dmd/escape.d(1850): Assertion failure
  src/dmd/escape.d
  test/compilable/issue21882.d
Labels: Bug Fix, Enhancement, auto-merge

#12500 dmd.compiler: Remove unused rootHasMain global
  src/dmd/compiler.d
  src/dmd/compiler.h
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
Labels: auto-merge

#12501 Fix Issue 21898 - Qualifier ignored in alias definition if parentheses are not present
  src/dmd/dsymbolsem.d
  test/compilable/test21898.d
Labels: Bug Fix

#12499 fix Issue 21874 - The test suite fails with most recent GDB versions
  test/runnable/gdb1.d
  test/runnable/gdb10311.d
  test/runnable/gdb14225.d
  test/runnable/gdb14276.d
  test/runnable/gdb14313.d
  test/runnable/gdb14330.d
  test/runnable/gdb4149.d
  test/runnable/gdb4181.d
Labels: Bug Fix, auto-merge

#12450 move comma rewrite from elnot to all unary ops
  src/dmd/backend/cg87.d
  src/dmd/backend/cgelem.d
Labels: auto-merge

#12504 [dmd-cxx] Fix Issue 21898 - Qualifier ignored in alias definition if parentheses are not present
  src/dsymbolsem.c
  test/compilable/test21898.d
Labels: Easy Review, GDC, auto-merge

#12515 fix Issue 21914 - naked assembler functions get wrong offset to param…
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod3.d
  test/runnable/iasm.d
Labels: Bug Fix

#12516 merge stable
  VERSION
  src/dmd/dsymbolsem.d
  src/dmd/escape.d
  src/dmd/expressionsem.d
  test/compilable/issue21880.d
  test/compilable/issue21882.d
  test/compilable/test21898.d
Labels: Bug Fix, auto-merge

#12517 Fix 21918 - Segfault for getParameterStorageClasses for invalid funct…
  src/dmd/func.d
  src/dmd/traits.d
  test/fail_compilation/traits.d
Labels: Bug Fix

#12521 pull asm parsing code into parseAsm()
  src/dmd/parse.d
Labels: Easy Review, Refactoring

#12523 Enable unitttests for backend/aarray.d
  src/dmd/backend/aarray.d
Labels: Easy Review, Refactoring, auto-merge

#12518 Provide DDoc comments for globals.d
  src/dmd/globals.d
Labels: auto-merge

#12522 Fix address calculation in backend/aarray.d AArray.apply
  src/dmd/backend/aarray.d
Labels: auto-merge

#11983 dtoh: Emit (superclass) method aliases as using ...
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_ClassDeclaration.d
  test/compilable/dtoh_cpp98_compat.d
  test/compilable/dtoh_verbose.d
Labels: auto-merge, dtoh

#12171 dtoh: Emit symbols from public imports and emit aliases as `using ...`
  changelog/dtoh-improvements.dd
  src/dmd/dsymbolsem.d
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_AliasDeclaration.d
  test/compilable/dtoh_cpp98_compat.d
  test/compilable/dtoh_verbose.d
  test/compilable/extra-files/dtoh_imports.d
  test/compilable/extra-files/dtoh_imports2.d
Labels: auto-merge, dtoh

#12527 dtoh: Support TemplateMixins
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_ClassDeclaration.d
  test/compilable/dtoh_TemplateDeclaration.d
Labels: auto-merge, dtoh

#12507 add ImportC C compiler
  changelog/ImportC.md
  src/.dscanner.ini
  src/build.d
  src/dmd/astbase.d
  src/dmd/backend/elfobj.d
  src/dmd/cparse.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dmodule.d
  src/dmd/dscope.d
  src/dmd/dtoh.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/glue.d
  src/dmd/id.d
  src/dmd/lexer.d
  src/dmd/mars.d
  src/dmd/module.h
  src/dmd/mtype.d
  src/dmd/parse.d
  src/dmd/semantic3.d
  src/dmd/target.d
  src/dmd/target.h
  src/dmd/tokens.d
  src/dmd/tokens.h
  src/tests/cxxfrontend.c
  test/compilable/imports/cstuff1.c
  test/compilable/testcstuff1.d
  test/unit/lexer/location_offset.d
Labels: auto-merge

#12531 parseAssignExp should be cparseAssignExp
  src/dmd/cparse.d
Labels: Easy Review, auto-merge

#12530 Fix issue 21928: pass Loc to Cat() explicitly.
  src/dmd/constfold.d
  src/dmd/ctfeexpr.d
  src/dmd/optimize.d
  test/fail_compilation/fail21928.d
  test/fail_compilation/fail21928b.d
Labels: Bug Fix

#12533 dmd.target: Rename TargetC.twchar_t to wchar_tsize
  src/dmd/chkformat.d
  src/dmd/dmodule.d
  src/dmd/dscope.d
  src/dmd/frontend.h
  src/dmd/target.d
  src/dmd/target.h
Labels: Refactoring, auto-merge

#12536 dmd.cparse: Support real.sizeof == double.sizeof targets
  src/dmd/cparse.d
Labels: Refactoring, auto-merge

#12534 Allocate the escape table lazily
  src/dmd/dmodule.d
  src/dmd/frontend.h
Labels: auto-merge

#12538 fix Issue 21931 - importC: 'alias time_t = time_t;' cannot alias itself, use a qualified name to create an overload set
  src/dmd/cparse.d
  test/compilable/imports/cstuff1.c
Labels: Bug Fix

#12491 Add nightly build on Github Actions
  .github/workflows/nightlies.yml
Labels: auto-merge

#12540 Enable upload of nightly builds to GitHub release
  .github/workflows/nightlies.yml
Labels: auto-merge

#12548 Fix 21940 - Recognize on/off as valid options for -check
  src/dmd/mars.d
  test/runnable/test_dip1006c.d
Labels: Bug Fix, auto-merge

#12547 Fix Issue 21939 - Duplicate error messages for wrong aggregate in 'static foreach'
  src/dmd/cond.d
  test/fail_compilation/test21939.d
Labels: Bug Fix, auto-merge

#12546 fix Issue 21934 - importC: Support asm labels to specify the assembler name to use for a C symbol
  src/dmd/cparse.d
  src/dmd/frontend.h
  src/dmd/tokens.d
  src/dmd/tokens.h
  src/tests/cxxfrontend.c
  test/compilable/imports/cstuff1.c
  test/unit/lexer/location_offset.d
Labels: Bug Fix, auto-merge

#12545 Fix Issue 21936 - Segfault with -dip1000
  src/dmd/access.d
  test/fail_compilation/imports/issue21936s.d
  test/fail_compilation/issue21936.d
Labels: Bug Fix, auto-merge

#12542 Fix Issue 2450 - Error using operators from named template mixin (version 2)
  src/dmd/expressionsem.d
  src/dmd/typesem.d
  test/fail_compilation/fail2450.d
  test/runnable/mixin1.d
Labels: Bug Fix, auto-merge

#12543 Remove early error from resolvePropertiesX()
  src/dmd/expressionsem.d
  test/fail_compilation/fail117.d
  test/fail_compilation/ice9406.d
Labels: Bug Fix, auto-merge

#12544 Fix Issue 21927 - ICE (illegal instruction) with static foreach over empty member template
  src/dmd/dinterpret.d
  test/compilable/interpret5.d
  test/fail_compilation/fail238_m32.d
  test/fail_compilation/fail238_m64.d
  test/fail_compilation/fail9766.d
  test/fail_compilation/iasm1.d
  test/fail_compilation/test20549.d
  test/fail_compilation/test21927.d
Labels: Bug Fix, auto-merge

#12550 ImportC: add __func__
  src/dmd/cparse.d
  src/dmd/frontend.h
  src/dmd/id.d
  test/compilable/imports/cstuff1.c
Labels: auto-merge

#12529 vsafe now called useDIP1000 and of type FeatureState
  src/dmd/cli.d
  src/dmd/dcast.d
  src/dmd/dsymbolsem.d
  src/dmd/escape.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/func.d
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/mars.d
  src/dmd/mtype.d
  src/dmd/statementsem.d
  src/dmd/typesem.d
Labels: auto-merge

#12549 Fix path for nightly artifacts
  .github/workflows/nightlies.yml
Labels: auto-merge

#12551 dmd.cparse: Rename cparseAsmLabel to cparseSimpleAsmExpr
  src/dmd/cparse.d
Labels: ImportC, Walter Bright

#12555 dmd.cparse: Add comment about asm(name) mapping to pragma(mangle, name)
  src/dmd/cparse.d
Labels: ImportC, Walter Bright

#12556 dmd.cparse: Use (opt) in the grammar comments
  src/dmd/cparse.d
Labels: ImportC, Walter Bright, auto-merge

#12558 dmd.cparse: Add asm() detection to isCDeclaration
  src/dmd/cparse.d
  test/compilable/imports/cstuff1.c
Labels: ImportC, Walter Bright

#12563 remove TOK.functionString
  src/dmd/cparse.d
Labels: Easy Review, ImportC, auto-merge

#12562 Combine storage class and type specifiers into one aggregate
  src/dmd/cparse.d
Labels: Easy Review, ImportC, Refactoring, auto-merge

#12537 dmd.cparse: Templatize CParser constructor to accept a TargetC interface
  src/dmd/cparse.d
  src/dmd/dmodule.d
Labels: ImportC, Refactoring, Walter Bright, auto-merge

#12561 refactor declaration of __func__
  src/dmd/cparse.d
Labels: Easy Review, ImportC, Refactoring, auto-merge

#12513 Fix Issue 21885 - Bad diagnostic: struct is not copyable because it is annotated @disable
  src/dmd/declaration.d
  test/fail_compilation/fail10968.d
  test/fail_compilation/fail11355.d
  test/fail_compilation/fail18994.d
  test/fail_compilation/fail21885.d
  test/fail_compilation/fail341.d
  test/fail_compilation/fail9346.d
Labels: 72h no objection -> merge, Easy Review, Enhancement

#12566 add scope to stringtable.d
  src/dmd/root/stringtable.d
Labels: Easy Review, Refactoring, auto-merge

#12567 Tag name space
  src/dmd/cparse.d
  test/compilable/imports/cstuff1.c
Labels: Easy Review, ImportC, auto-merge

#12557 dmd.cparse: Rename cparseAttribute to cparseGnuAttributes, clarify the grammar
  src/dmd/cparse.d
Labels: ImportC, Walter Bright

#12552 fix Issue 21946, 21942: Remove __asm and __asm__ tokens
  changelog/ImportC.md
  src/dmd/cparse.d
  src/dmd/frontend.h
  src/dmd/tokens.d
  src/dmd/tokens.h
  src/tests/cxxfrontend.c
  test/compilable/imports/cstuff1.c
  test/unit/lexer/location_offset.d
Labels: Bug Fix, ImportC, Walter Bright, auto-merge

#12539 add lexer integer literal support
  src/dmd/cparse.d
  src/dmd/lexer.d
  test/compilable/imports/cstuff1.c
Labels: ImportC, auto-merge

#12572 Revert "Tag name space"
  src/dmd/cparse.d
  test/compilable/imports/cstuff1.c
Labels: auto-merge

#12571 fix brace in error message
  src/dmd/dsymbolsem.d
  test/fail_compilation/issue21203.d
Labels: Trivial, auto-merge

#12577 fix Issue 21945 - importC AssertError@src/dmd/dsymbolsem.d(4787): Assertion failure
  src/dmd/cparse.d
  test/compilable/imports/cstuff1.c
Labels: Bug Fix, ImportC, Walter Bright

#12581 move function building functions from dsymbolsem.d to clone.d
  src/dmd/clone.d
  src/dmd/dsymbolsem.d
Labels: Easy Review, Refactoring, auto-merge

#12582 split needCopyCtor() off of buildCopyCtor()
  src/dmd/clone.d
Labels: Easy Review, Refactoring

#12573 chkformat: remove unused import [NFC][Trivial]
  src/dmd/chkformat.d
Labels: Trivial

#12570 improve documentation for DsymbolTable
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/frontend.h
Labels: Easy Review, Refactoring

#12576 fix Issue 21962 - importC: Empty enums are accepted as valid code
  src/dmd/cparse.d
  test/fail_compilation/failcstuff1.d
  test/fail_compilation/imports/cstuff1.c
  test/tools/d_do_test.d
Labels: Bug Fix, ImportC, Walter Bright, auto-merge

#12574 dmd.target: Move all top-level imports to local selective imports
  src/dmd/target.d
Labels: Refactoring, Walter Bright, auto-merge

#12583 remove comment that is now known as issue 21966
  src/dmd/expressionsem.d
Labels: auto-merge

#12579 Convert Type.ty to an enum
  src/dmd/frontend.h
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/target.d
Labels: Refactoring

#12585 fix Issue 21944 - importC: Add `-P` to C preprocessor invocation example
  changelog/ImportC.md
Labels: Bug Fix, ImportC, Trivial, Walter Bright, auto-merge

#12584 fix Issue 21967 - importC: Error function without 'this' cannot be 'const'
  src/dmd/cparse.d
  test/compilable/imports/cstuff1.c
Labels: Bug Fix, Easy Review, ImportC, Walter Bright, auto-merge

#12559 Fix 21949 - Implement conversion/covariance rules for TypeNoreturn
  src/dmd/frontend.h
  src/dmd/mtype.d
  src/dmd/mtype.h
  test/compilable/noreturn1.d
Labels: Bug Fix, auto-merge

#12575 fix Issue 21963 - importC: Support declaring union types
  src/dmd/cparse.d
  src/dmd/tokens.d
  test/compilable/imports/cstuff1.c
Labels: Bug Fix, ImportC, Walter Bright, auto-merge

#12591 testcstuff1.d: Give newly introduced tests more unique names
  test/compilable/imports/cstuff1.c
Labels: Easy Review, Trivial

#12463 fix Issue 16689 - Errors in instantiated mixin templates should show instantiation point
  src/dmd/semantic2.d
  test/fail_compilation/fail16689.d
  test/fail_compilation/fail6334.d
Labels: Enhancement, Walter Bright, auto-merge

#12590 fix Issue 21948 - importC: Support declaring local variables of typedef types
  src/dmd/cparse.d
  test/compilable/imports/cstuff1.c
Labels: Bug Fix, ImportC, Walter Bright, auto-merge

#12528 Fix 16001 - forbid lambda syntax followed by FunctionLiteralBody
  src/dmd/parse.d
  test/fail_compilation/fail16001.d
  test/fail_compilation/ice10212.d
  test/runnable/funclit.d
Labels: Enhancement, auto-merge

#12593 add ImportC to README.md
  src/dmd/README.md
Labels: Easy Review, auto-merge, documentation

#12503 fix 21905 - case of IFTI failure when combining `ref`, and `alias this` on a static instance
  src/dmd/mtype.d
  test/compilable/issue21905.d
Labels: Bug Fix

#12589 [NFC] Move public symbols to top of file in e2ir.d
  src/dmd/e2ir.d
Labels: Refactoring, auto-merge

#12587 fix Issue 21970 - importC: Error: variable extern symbols cannot have initializers
  src/dmd/cparse.d
  test/compilable/imports/cstuff1.c
Labels: Bug Fix, ImportC, auto-merge

#12580 dmd.cparse: Remove __restrict keyword
  src/dmd/cparse.d
  src/dmd/frontend.h
  src/dmd/tokens.d
  src/dmd/tokens.h
  test/compilable/imports/cstuff1.c
  test/unit/lexer/location_offset.d
Labels: ImportC, Refactoring, Walter Bright, auto-merge

#12569 fix Issue 21937 - importC: Support parsing __attribute__ specifiers
  src/dmd/cparse.d
  test/compilable/imports/cstuff1.c
  test/fail_compilation/failcstuff1.d
  test/fail_compilation/imports/cstuff1.c
Labels: Bug Fix, ImportC, Walter Bright, auto-merge

#12597 test/compilable: Move cstuff tests for bugzilla issues into cstuff2.c
  test/compilable/imports/cstuff1.c
  test/compilable/imports/cstuff2.c
  test/compilable/testcstuff2.d
Labels: ImportC, Trivial, auto-merge

#12594 add TypeTag for C struct/union/enum
  src/dmd/astbase.d
  src/dmd/cparse.d
  src/dmd/dmangle.d
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/parsetimevisitor.d
  src/dmd/typesem.d
  src/dmd/visitor.h
  test/compilable/imports/cstuff1.c
Labels: ImportC, auto-merge

#12598 Add tests for importC issues 21933, 21965, 21968, 21973.
  test/compilable/imports/cstuff2.c
Labels: Bug Fix, Easy Review, ImportC

#12599 add inner() to Scope
  src/dmd/dscope.d
  src/dmd/semantic3.d
  src/dmd/typesem.d
Labels: Easy Review, Refactoring, auto-merge

#12459 gflow.d: double speed of fillInDNunambig()
  src/dmd/backend/gflow.d
Labels: Backend, Refactoring, auto-merge

#12602 remove pident from cparseDeclarationSpecifiers
  src/dmd/cparse.d
Labels: Easy Review, ImportC, Refactoring, auto-merge

#12603 move gnu attribute parsing up to cparseDeclarationSpecifiers()
  src/dmd/cparse.d
Labels: Easy Review, ImportC, Refactoring, auto-merge

#12605 Fix 21985 - Ensure that LabelDsymbols have an explicit location
  src/dmd/declaration.h
  src/dmd/frontend.h
  src/dmd/func.d
  src/dmd/iasmdmd.d
  src/dmd/semantic3.d
  src/dmd/statement.d
  src/dmd/statementsem.d
  test/fail_compilation/fail11552.d
  test/fail_compilation/iasm1.d
  test/fail_compilation/ice11552.d
Labels: Bug Fix, auto-merge

#12600 merge stable
  VERSION
  src/dmd/access.d
  src/dmd/dinterpret.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/mars.d
  src/dmd/traits.d
  src/dmd/typesem.d
  test/compilable/interpret5.d
  test/fail_compilation/fail117.d
  test/fail_compilation/fail238_m32.d
  test/fail_compilation/fail238_m64.d
  test/fail_compilation/fail2450.d
  test/fail_compilation/fail9766.d
  test/fail_compilation/iasm1.d
  test/fail_compilation/ice9406.d
  test/fail_compilation/imports/issue21936s.d
  test/fail_compilation/issue21936.d
  test/fail_compilation/test20549.d
  test/fail_compilation/test21927.d
  test/fail_compilation/traits.d
  test/runnable/mixin1.d
  test/runnable/test_dip1006c.d
Labels: Bug Fix

#12508 Implement -target
  changelog/target.md
  src/dmd/cli.d
  src/dmd/frontend.h
  src/dmd/mars.d
  src/dmd/target.d
  src/dmd/target.h
  test/unit/triple.d
Labels: Enhancement, Needs Spec PR

#12608 fix Issue 21982 - importC: Error: variable no definition of struct
  src/dmd/cparse.d
  test/compilable/imports/cstuff2.c
Labels: Bug Fix, Easy Review, ImportC, Walter Bright

#11651 fix Issue 16274 - short argument passed in 16 bit register
  src/dmd/e2ir.d
  test/runnable/mars1.d
Labels: Bug Fix, auto-merge

#12612 d_do_test.d: Never fail when an intermediate file cannot be removed...
  test/tools/d_do_test.d
Labels: auto-merge

#11859 add MATCHpair for type safety
  src/dmd/dtemplate.d
  src/dmd/globals.h
Labels: Easy Review, Refactoring, auto-merge

#12610 merge stable
  src/dmd/frontend.d
  src/dmd/mars.d
  src/dmd/target.d
  src/tests/cxxfrontend.c
  test/dub_package/frontend_file.d
Labels: auto-merge

#12613 remove tests for MATCH less than zero
  src/dmd/dtemplate.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/mtype.d
  src/dmd/opover.d
  src/dmd/statementsem.d
Labels: Easy Review, Refactoring, auto-merge

#12592 Fixup for #12528 - Add changelog, improve message, fix tests
  changelog/ambiguous-lambda.dd
  src/dmd/parse.d
  test/fail_compilation/fail16001.d
  test/fail_compilation/ice10212.d
  test/runnable/funclit.d
Labels: auto-merge

#12607 dmd.cparse: Move bit-field parsing up to cparseDeclaration
  src/dmd/cparse.d
Labels: Easy Review, ImportC, Refactoring, Walter Bright, auto-merge
