Repository dlang/dmd, pull requests merged in 2021-04, with the labels that each got.

#12330 backend: transition to @safe code part 2
  src/dmd/backend/divcoeff.d
  src/dmd/backend/dlist.d
  src/dmd/backend/dt.d
  src/dmd/backend/dvec.d
Labels: Easy Review, Refactoring, auto-merge

#12332 backend: transition to @safe code part 4
  src/dmd/backend/cc.d
Labels: Easy Review, Refactoring

#12328 dmd.chkformat: Use %d in "more format specifiers than arguments" deprecation
  src/dmd/chkformat.d
Labels: auto-merge

#12334 backend: transition to @safe code part 6
  src/dmd/backend/cgobj.d
  src/dmd/backend/code.d
  src/dmd/backend/global.d
Labels: Easy Review, Refactoring, auto-merge

#12333 backend: transition to @safe code part 5
  src/dmd/backend/dwarf.d
  src/dmd/backend/dwarf2.d
  src/dmd/backend/filespec.d
  src/dmd/backend/mach.d
  src/dmd/backend/melf.d
  src/dmd/backend/mem.d
  src/dmd/backend/mscoff.d
  src/dmd/backend/xmm.d
Labels: Easy Review, Refactoring

#12331 backend: transition to @safe code part 3
  src/dmd/backend/aarray.d
  src/dmd/backend/codebuilder.d
  src/dmd/backend/rtlsym.d
Labels: Easy Review, Refactoring, auto-merge

#12336 Fix misspelling identifer -> identifier
  src/dmd/dmangle.d
  src/dmd/dsymbolsem.d
  test/fail_compilation/cppmangle.d
Labels: Easy Review, auto-merge

#12340 Fix mangling ambiguity, follow-up to #12300
  src/dmd/dmangle.d
  test/runnable/mangle.d
Labels: auto-merge

#12342 backend: transition to @safe code part 8
  src/dmd/backend/el.d
  src/dmd/backend/elem.d
  src/dmd/backend/evalu8.d
Labels: Easy Review, Refactoring, auto-merge

#12343 [dmd-cxx] Fix dmd codegen part of C++ port
  src/e2ir.c
  src/posix.mak
  src/win32.mak
Labels: C++ Port, Easy Review, auto-merge-squash

#12344 [dmd-cxx] Fix misspelling identifer -> identifier
  src/backend/cc.h
  src/dmangle.c
  src/parse.c
  test/fail_compilation/cppmangle.d
Labels: C++ Port, Easy Review, GDC, auto-merge-squash

#12345 [dmd-cxx] Reapply Fix issue 9029: make types match to alias template parameters with priority MATCH.convert.
  src/dtemplate.c
  test/compilable/test9029.d
Labels: C++ Port, Easy Review, GDC, auto-merge-squash

#12292 Fix 21739 - Don't merge `debug case` into previous CaseStatement
  src/dmd/astbase.d
  src/dmd/parse.d
  test/fail_compilation/debugCaseDeclaration.d
Labels: Bug Fix, auto-merge

#12348 Fix 21793 - Cannot initialize shared member with -preview=nosharedaccess
  src/dmd/expressionsem.d
  test/compilable/shared.d
Labels: Bug Fix

#12349 backend: transition to @safe code part 9
  src/dmd/backend/cgcod.d
  src/dmd/backend/code.d
  src/dmd/backend/code_x86.d
  src/dmd/backend/goh.d
  src/dmd/backend/symtab.d
  src/dmd/backend/type.d
Labels: Easy Review, Refactoring, auto-merge

#12335 backend: transition to @safe code part 7
  src/dmd/backend/machobj.d
  src/dmd/backend/mscoffobj.d
Labels: Easy Review, Refactoring

#12351 backend: transition to @safe code part 10
  src/dmd/backend/md5.d
  src/dmd/backend/util2.d
  src/dmd/backend/var.d
Labels: Easy Review, Refactoring

#12352 backend: transition to @safe code part 11
  src/dmd/backend/gdag.d
  src/dmd/backend/gflow.d
  src/dmd/backend/gloop.d
  src/dmd/backend/go.d
  src/dmd/backend/gother.d
  src/dmd/backend/gsroa.d
Labels: Easy Review, Refactoring

#12353 backend: transition to @safe code part 12
  src/dmd/backend/cv8.d
  src/dmd/backend/dcgcv.d
  src/dmd/backend/elpicpie.d
Labels: Backend, Easy Review, Refactoring

#12354 backend: transition to @safe code part 13
  src/dmd/backend/backconfig.d
  src/dmd/backend/cgcs.d
  src/dmd/backend/cgcse.d
  src/dmd/backend/compress.d
  src/dmd/backend/os.d
Labels: Backend, Easy Review, Refactoring, auto-merge

#12356 dmd.chkformat: Use type with correct signedness in pragma(printf) errors
  src/dmd/chkformat.d
  test/fail_compilation/chkformat.d
Labels: Easy Review, GDC, auto-merge

#12358 dmd.chkformat: uintmax_t is always same size as ulong, use name in error
  src/dmd/chkformat.d
  test/fail_compilation/chkformat.d
Labels: Easy Review, GDC, auto-merge

#12325 Fix 21785 - Improve error messages for opaque enums
  src/dmd/denum.d
  src/dmd/dsymbolsem.d
  test/compilable/ice10770.d
  test/fail_compilation/enum_init.d
  test/fail_compilation/ice10770.d
  test/fail_compilation/ice8511.d
Labels: Bug Fix

#12357 dmd.chkformat: Use isLP64 instead of is64bit in long size tests
  src/dmd/chkformat.d
Labels: Easy Review, GDC, auto-merge

#12316 Fix issue 16472: Spurious "is used as a type" when aliasing enum temp…
  src/dmd/templateparamsem.d
  test/compilable/issue16472.d
Labels: Bug Fix

#12318 Fix issue 20705 - `-preview=rvaluerefparam` does not work with templa…
  src/dmd/dtemplate.d
  test/compilable/issue20705.d
  test/runnable/structlit.d
Labels: Bug Fix, Easy Review, auto-merge, industry

#12323 factor out conf and arg parsing
  src/dmd/mars.d
Labels: auto-merge

#12362 backend: transition to @safe code part 16
  src/dmd/backend/out.d
  src/dmd/backend/symbol.d
Labels: Backend, Easy Review, Refactoring

#12361 backend: transition to @safe code part 15
  src/dmd/backend/cdef.d
  src/dmd/backend/cg87.d
  src/dmd/backend/cgcod.d
Labels: Backend, Easy Review, Refactoring

#12363 move cpu from param to target
  src/dmd/dmsc.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/mars.d
  src/dmd/target.d
  src/dmd/target.h
  src/tests/cxxfrontend.c
Labels: auto-merge

#12364 backend: transition to @safe code part 17
  src/dmd/backend/cgxmm.d
  src/dmd/backend/glocal.d
  src/dmd/backend/nteh.d
Labels: Backend, Easy Review, Refactoring

#12365 dmd.chkformat: Use c_longsize comparison for 'C long int' formats
  src/dmd/chkformat.d
Labels: Easy Review, GDC

#12366 dmd.chkformat: Use ptrsize comparison for 'size_t' and 'ptrdiff_t' formats
  src/dmd/chkformat.d
Labels: Easy Review, GDC, auto-merge

#12346 Fix 21791 - Stack overflow for forward-referenced enum initializer
  src/dmd/denum.d
  test/fail_compilation/enum_init.d
Labels: Bug Fix

#12359 backend: transition to @safe code part 14
  src/dmd/backend/blockopt.d
  src/dmd/backend/cgelem.d
Labels: Backend, Easy Review, Refactoring, auto-merge

#12313 DWARF: Bump `.debug_line` to version 3
  src/dmd/backend/dwarfdbginf.d
Labels: 72h no objection -> merge

#12347 Fix 21792 - Enum using itself as base type crashes dmd
  src/dmd/dsymbolsem.d
  test/fail_compilation/enum_init.d
Labels: Bug Fix, auto-merge

#12371 Fix 21797 - Stack overflow for forward-referenced enum min / max
  src/dmd/denum.d
  test/fail_compilation/enum_init.d
  test/fail_compilation/fail109.d
Labels: Bug Fix

#12373 Fix 21798 - checkaction=context creates temporary of type void
  src/dmd/expressionsem.d
  test/fail_compilation/dassert.d
Labels: Bug Fix, auto-merge

#12370 [stable] Fix runnable_cxx/test21515.d for clang
  test/runnable_cxx/extra-files/test21515.cpp
  test/runnable_cxx/test21515.d
Labels: auto-merge

#12372 Improve error messages for min/max of opaque enums
  src/dmd/denum.d
  src/dmd/typesem.d
  test/fail_compilation/enum_init.d
Labels: auto-merge

#12375 backend: transition to @safe code part 19
  src/dmd/backend/cgsched.d
  src/dmd/backend/cod3.d
  src/dmd/backend/cod4.d
  src/dmd/backend/cod5.d
Labels: Backend, Easy Review, Refactoring, auto-merge

#12377 cgcs.d: consolidate global variables into struct CGCS
  src/dmd/backend/cgcs.d
Labels: Backend, Easy Review, Refactoring

#12380 [dmd-cxx] Missing call to va_end in getMatchError
  src/mtype.c
Labels: C++ Port, Easy Review, GDC, auto-merge

#12382 cgcs.d: refactor start, reset, and term
  src/dmd/backend/cgcs.d
Labels: Backend, Easy Review, Refactoring

#12381 make barray.d @safe
  src/dmd/backend/barray.d
Labels: Backend, Easy Review, Refactoring

#12379 Fix 21799 - CTFE doesn't call base class destructor for extern(D) classes
  src/dmd/dinterpret.d
  test/runnable/class_destructors.d
Labels: Bug Fix

#12374 backend: transition to @safe code part 18
  src/dmd/backend/cod1.d
  src/dmd/backend/cod2.d
Labels: Backend, Easy Review, Refactoring, auto-merge

#12385 update link for dip1021 in global.params
  src/dmd/globals.d
Labels: Trivial, auto-merge

#12384 remove unused global.params.hasObjectiveC
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
Labels: Easy Review, Trivial, auto-merge

#12376 backend: transition to @safe code part 20
  src/dmd/backend/cgcv.d
  src/dmd/backend/cgreg.d
  src/dmd/backend/dcode.d
  src/dmd/backend/debugprint.d
  src/dmd/backend/dtype.d
Labels: Backend, Easy Review, Refactoring, auto-merge

#12387 cgcs: replace globals with refs
  src/dmd/backend/cgcs.d
  src/dmd/backend/global.d
Labels: Backend, Easy Review, Refactoring, auto-merge

#12388 cgcs: use const, foreach, improve comments
  src/dmd/backend/cgcs.d
Labels: Backend, Easy Review, Refactoring, auto-merge

#12326 fix Issue 21665 - Void initialization should not be allowed for insta…
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/safe.d
  test/fail_compilation/test21665.d
Labels: Bug Fix, auto-merge

#12386 move targetOS from global to target
  src/dmd/argtypes_x86.d
  src/dmd/astbase.d
  src/dmd/e2ir.d
  src/dmd/frontend.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/glue.d
  src/dmd/json.d
  src/dmd/mars.d
  src/dmd/s2ir.d
  src/dmd/target.d
  src/dmd/target.h
  src/dmd/tocsym.d
  src/tests/cxxfrontend.c
  test/dub_package/avg.d
  test/dub_package/impvisitor.d
  test/unit/deinitialization.d
Labels: auto-merge

#12393 use out for aecpelem() rather than pointers
  src/dmd/backend/gflow.d
Labels: Backend, Easy Review, Refactoring, auto-merge

#12394 use out for lvelem() rather than pointers
  src/dmd/backend/gflow.d
  src/dmd/backend/gloop.d
  src/dmd/backend/gother.d
Labels: Backend, Easy Review, Refactoring, auto-merge

#12396 fix Issue 14114 - Allow volatileLoad/Store to access null location
  src/dmd/backend/cgelem.d
  test/compilable/test14114.d
Labels: Bug Fix, Pending Autotester, auto-merge

#12398 Issue 21807 - Missing deprecation when slicing static array temporary...
  src/dmd/escape.d
  test/compilable/scope.d
  test/fail_compilation/fail20183.d
  test/fail_compilation/test21807.d
Labels: Regression

#12400 Fix 20068 - Treat initialization of unions in constructors as @safe
  src/dmd/expression.d
  src/dmd/expressionsem.d
  test/compilable/union_initialization.d
  test/fail_compilation/union_initialization.d
Labels: Enhancement

#12395 remove usage of TARGET from mars.d
  src/dmd/mars.d
Labels: auto-merge

#12403 fix Issue 17146 - Internal error: tk.c 266 with -O -inline
  src/dmd/toir.d
  test/compilable/test17146.d
Labels: Bug Fix, auto-merge

#12404 AssertExp should be lowered before inlining happens
  src/dmd/inline.d
Labels: Refactoring, auto-merge

#12389 Fix Issue 21802 - opAssign and opOpAssign treat lazy void parameters inconsistently
  src/dmd/expressionsem.d
  test/compilable/test21802.d
  test/fail_compilation/fail7173.d
Labels: Bug Fix, Easy Review

#12406 Fix Issue 21812 - __traits(allMembers) on types with value tuples return ghost members
  src/dmd/dsymbolsem.d
  test/compilable/test21812.d
Labels: Bug Fix, auto-merge

#12402 Fix 21229 - Accept construction of union member as initialization
  src/dmd/expression.d
  test/compilable/union_initialization.d
  test/fail_compilation/union_initialization.d
Labels: Bug Fix, Regression, auto-merge

#12410 Issue 21813 - [REG-master] Bootstrap broken from dmd-cxx baseline
  test/compilable/issue21813a.d
  test/compilable/issue21813b.d
Labels: Easy Review, Regression

#12411 [dmd-cxx] fix Issue 21813 - [REG-master] Bootstrap broken from dmd-cxx baseline
  src/dstruct.c
  src/dsymbol.h
  src/dsymbolsem.c
  src/dtemplate.c
  src/hdrgen.c
  src/mtype.c
  src/traits.c
  src/version.h
  test/compilable/imports/pkg16044/package.d
  test/compilable/imports/pkg16044/sub/package.d
  test/compilable/issue16044.d
  test/compilable/issue20915.d
  test/compilable/issue21813a.d
  test/compilable/issue21813b.d
  test/compilable/test19145.d
  test/compilable/test20894.d
  test/compilable/test21812.d
  test/fail_compilation/diag19196.d
  test/fail_compilation/test20919.d
Labels: C++ Port, Easy Review, GDC, Regression, auto-merge-squash

#12408 Merge stable into master
  src/dmd/declaration.d
  src/dmd/dinterpret.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/escape.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/initsem.d
  src/dmd/semantic3.d
  test/compilable/ctfe_math.d
  test/compilable/dtorfields.d
  test/compilable/issue20705.d
  test/compilable/scope.d
  test/compilable/union_initialization.d
  test/fail_compilation/dassert.d
  test/fail_compilation/fail20183.d
  test/fail_compilation/test15989.d
  test/fail_compilation/test21807.d
  test/fail_compilation/union_initialization.d
  test/runnable/class_destructors.d
  test/runnable/cppdtor.d
  test/runnable/structlit.d
  test/runnable/test19192.d
  test/runnable_cxx/cppa.d
  test/runnable_cxx/extra-files/test21515.cpp
  test/runnable_cxx/test21515.d
Labels: Bug Fix, auto-merge

#12417 test: Add EXTRA_FILES to compilable/issue16044.d
  test/compilable/issue16044.d
Labels: Trivial, auto-merge

#12418 [dmd-cxx] fix Issue 18963 - Relax restrictions on 'return' parameters when parameter is not a pointer
  src/typesem.c
  test/compilable/issue16044.d
  test/fail_compilation/test16228.d
Labels: C++ Port, Easy Review, GDC, auto-merge

#12392 use specific runtimes in target.d
  src/dmd/frontend.h
  src/dmd/mars.d
  src/dmd/target.d
  src/dmd/target.h
Labels: 72h no objection -> merge, auto-merge-squash

#12420 dmd.builtin: Match any submodule of the std.math package
  src/dmd/builtin.d
Labels: Blocking Other Work, Easy Review

#12399 Fix Issue 21806 - Overload selection ignores slice
  src/dmd/dcast.d
  src/dmd/dtemplate.d
  test/compilable/test21806.d
Labels: 72h no objection -> merge, Bug Fix, Regression

#12416 fix Issue 21816 - testing XMM for nan does not work
  src/dmd/backend/cod1.d
  src/dmd/backend/cod3.d
  test/compilable/extra-files/cdcmp.out
  test/runnable/mars1.d
Labels: Blocking Other Work, Bug Fix

#12294 Fix Issue 21742 - dot template expressions don't have the void type like any template
  src/dmd/expressionsem.d
  test/compilable/test21742.d
  test/fail_compilation/fail7424b.d
  test/fail_compilation/fail7424c.d
  test/fail_compilation/fail7424d.d
  test/fail_compilation/fail7424e.d
  test/fail_compilation/fail7424f.d
  test/fail_compilation/fail7424g.d
  test/fail_compilation/fail7424h.d
  test/fail_compilation/fail7424i.d
Labels: 72h no objection -> merge, Bug Fix

#12421 don't use [os specific] druntime in scanelf.d
  src/dmd/scanelf.d
Labels: Easy Review, auto-merge

#12295 Fix Issue 21743 - getOverloads fails to propagate 'this' expression …
  src/dmd/traits.d
  test/compilable/test21743.d
Labels: Bug Fix, auto-merge

#12413 Fix issue 20704 - -preview=rvaluerefparam does not work with init as default parameter
  src/dmd/typesem.d
  test/compilable/issue20704.d
  test/fail_compilation/fail7603a.d
  test/fail_compilation/fail7603b.d
  test/fail_compilation/fail7603c.d
  test/fail_compilation/fail9773.d
  test/fail_compilation/fail9891.d
  test/fail_compilation/issue20704.d
Labels: Bug Fix

#12427 fix Issue 21822 - Optimizer flowlv() does not account for OPmemcmp an…
  src/dmd/backend/gflow.d
  test/runnable/test21822.d
Labels: Bug Fix, auto-merge

#12401 DWARF: Implement `.debug_line` header v4 and v5
  src/dmd/backend/dwarfdbginf.d
Labels: 72h no objection -> merge

#12434 fix Issue 21827 - Null pointer exception in elToPair() in backend/cge…
  src/dmd/backend/cgelem.d
Labels: Bug Fix, Needs Tests, auto-merge

#12433 fix Issue 21826 - MSCOFF output for Win32 should not use EBP for anyt…
  src/dmd/backend/backconfig.d
  src/dmd/backend/cod2.d
Labels: Bug Fix, Needs Tests, auto-merge

#12432 Use `filespecname` instead of `retrieveFilename` and fix `dwarf_line_add_file`/`dwarf_line_add_directory`
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/filespec.d
Labels: auto-merge-squash

#12440 fix Issue 21831 - Wrong deprecation message in template parameters before evaluating constraints
  src/dmd/dsymbol.d
  src/dmd/dtemplate.d
  src/dmd/mtype.d
  test/compilable/test21831.d
  test/fail_compilation/fail21831.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#12441 fix Issue 21830 - Wrong deprecation message when non-deprecated template in static condition
  src/dmd/expressionsem.d
  test/compilable/test21830.d
  test/fail_compilation/fail21830.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#12442 fix Issue 21832 - Wrong deprecation message when importing non-deprecated template in static condition
  src/dmd/typesem.d
  test/compilable/imports/imp21832.d
  test/compilable/test21832.d
  test/fail_compilation/fail21830.d
  test/fail_compilation/fail21832.d
  test/fail_compilation/imports/imp21832.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#12435 fix Issue 18251 - deprecate + transition=complex shouldn't look at functions with non-matching if constraints
  src/dmd/parse.d
  test/compilable/diag20916.d
  test/compilable/test18251.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#12431 merge stable
  VERSION
  src/dmd/dcast.d
  src/dmd/dtemplate.d
  test/compilable/test21806.d
Labels: Bug Fix, auto-merge

#12415 DWARF: refactor the compilation unit header to write everything at once
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge

#12438 Fix Issue 21828 - Enum forward-references just assume int base type
  src/dmd/denum.d
  test/compilable/test21828.d
Labels: Bug Fix, auto-merge

#12390 Enable -transition=complex by default
  changelog/transition-complex.dd
  src/dmd/cli.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/mars.d
  test/compilable/compile1.d
  test/compilable/sw_transition_complex.d
  test/compilable/test18251.d
  test/compilable/test19227.d
  test/compilable/test21514.d
  test/compilable/testexpression.d
  test/compilable/transitionhelp.d
  test/fail_compilation/b3841.d
  test/fail_compilation/fail101.d
  test/fail_compilation/fail303.d
  test/runnable/complex.d
  test/runnable/iasm.d
  test/runnable/iasm64.d
Labels: Needs Spec PR

#12445 Update CodeCov token on Cirrus
  .cirrus.yml
Labels: Continuous Integration, auto-merge

#12446 Update CodeCov token on Cirrus [Stable]
  .cirrus.yml
Labels: Continuous Integration, auto-merge, stable-priority

#12448 fix Issue 21835 - Operation on float should use XMM register, not x87
  src/dmd/backend/cgelem.d
  test/runnable/mars1.d
Labels: Backend, Enhancement, auto-merge

#12447 Improve FuncResolveFlag.overloadOnly doc comment
  src/dmd/func.d
Labels: Trivial, documentation

#12430 DIP1034: make lambdaHasSideEffect true for noreturn functions
  src/dmd/sideeffect.d
  test/compilable/noreturn1.d
Labels: Bug Fix, Enhancement, auto-merge

#12443 Refactor `.debug_aranges` header to write everything at once
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge

#12449 Fix Issue 14740 - __traits(allMembers) returns erroneous 'this' member for types declared in functions
  src/dmd/traits.d
  test/compilable/test14740.d
Labels: Bug Fix, auto-merge

#12444 fix Issue 21833 - Optimizer incorrectly rewrites integer comparison t…
  src/dmd/backend/cgelem.d
  test/runnable/test21833.d
Labels: Bug Fix, auto-merge

#12451 copy optimizations from elnot to elbool
  src/dmd/backend/cgelem.d
Labels: Backend

#12355 dmd.dmangle: Fix mangling of nested functions with collisions in their name
  src/dmd/dmangle.d
  test/compilable/test14831.d
Labels: Easy Review

#12439 Fix 13815 - Use correct scope during statementSemantic on try-block
  src/dmd/statementsem.d
  test/compilable/interpret3.d
  test/fail_compilation/goto2.d
Labels: Bug Fix

#12409 fix Issue 20855 - stack overflow when compiling large file
  src/dmd/backend/backconfig.d
  src/dmd/backend/blockopt.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/go.d
  src/dmd/backend/gother.d
  src/dmd/backend/symbol.d
  src/dmd/s2ir.d
  test/runnable/test20855.d
Labels: Bug Fix, auto-merge

#12454 test20855 is too much for some platforms
  test/runnable/test20855.d
Labels: Blocking Other Work, auto-merge

#12453 move fillInDNunambig() to gflow.d
  src/dmd/backend/gflow.d
  src/dmd/backend/gloop.d
  src/dmd/backend/goh.d
Labels: Easy Review, Refactoring, auto-merge

#12455 fix accumda() so it does less recursion and more iteration
  src/dmd/backend/gother.d
Labels: Easy Review, auto-merge

#12456 rewrite asgdefelems() so it uses tail recursion
  src/dmd/backend/gflow.d
Labels: Easy Review, Refactoring, auto-merge

#12458 Fix Issue 21845 - Make `in` take precedence in getParameterStorageClasses
  src/dmd/traits.d
  test/compilable/previewin.d
Labels: Bug Fix

#12462 Fix typo in AliasAssign constructor
  src/dmd/dsymbol.d
  src/dmd/dsymbolsem.d
Labels: Easy Review, auto-merge

#12460 fix Issue 21849 - UTF8: -verrors=context doesn't respect multibyte characters
  src/dmd/errors.d
  test/fail_compilation/fail21849.d
Labels: Bug Fix, auto-merge

#12464 dmd.target: Add TargetCPP.wrapDtorInExternD
  src/dmd/clone.d
  src/dmd/frontend.h
  src/dmd/target.d
  src/dmd/target.h
Labels: auto-merge

#11801 Cirrus & Semaphore CI: Build & run DMD unittests too
  ci.sh
Labels: auto-merge

#12468 add -> and :: tokens
  src/dmd/frontend.h
  src/dmd/iasmgcc.d
  src/dmd/lexer.d
  src/dmd/parse.d
  src/dmd/tokens.d
  test/unit/lexer/location_offset.d
Labels: Easy Review, Refactoring

#12473 merge stable
  VERSION
  src/dmd/dmangle.d
  src/dmd/dsymbol.d
  src/dmd/dsymbolsem.d
  src/dmd/traits.d
  test/compilable/previewin.d
  test/compilable/test14831.d
Labels: Enhancement, auto-merge

#12466 fix Issue 20460 - [OSX] DMD writes the same address everywhere in DWA…
  src/dmd/backend/dwarfdbginf.d
Labels: Bug Fix, auto-merge

#12474 replace hardcoded extensions with enums
  src/dmd/astbase.d
  src/dmd/dmodule.d
  src/dmd/doc.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/link.d
  src/dmd/mars.d
Labels: Easy Review, Refactoring, auto-merge

#12475 lookForSourceFile(): access global.path through parameter list
  src/dmd/dmodule.d
Labels: Easy Review, Refactoring, auto-merge

#12470 [backend/dwarfeh] remove use of ELFOBJ and MACHOBJ
  src/dmd/backend/dwarfeh.d
Labels: auto-merge

#12476 Make it easier to run semaphoreci.sh on local machine
  semaphoreci.sh
Labels: auto-merge

#12426 Refactor dip25 error/deprecation handling code
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/errors.d
  src/dmd/escape.d
Labels: auto-merge

#12467 posix.mak: Run unittest directly via `build.d`
  src/posix.mak
Labels: Build System

#12472 Fix Issue 21861 - ctfe fails when a nested enum or function has a UDA
  src/dmd/dinterpret.d
  test/compilable/test21861.d
Labels: Bug Fix, auto-merge

#12478 [backend/elfobj] remove use of TARGET_*
  src/dmd/backend/elfobj.d
Labels: auto-merge

#12429 remove use of target from backend
  src/dmd/backend/elfobj.d
Labels: auto-merge

#12480 [backend/backconfig] remove use of TARGET_*
  src/dmd/backend/backconfig.d
  src/dmd/backend/cdef.d
  src/dmd/backend/out.d
Labels: auto-merge

#12482 dmd.dtoh: Fix building dtoh with soft ctfloat type
  src/dmd/dtoh.d
Labels: Easy Review, GDC, auto-merge

#12483 mtype.h: Add missing class TypeNoreturn
  src/dmd/mtype.h
Labels: Easy Review, GDC

#12481 fix 21870 - Property/method not invoked and requires () when used in static array length
  src/dmd/typesem.d
  test/compilable/issue15478.d
Labels: Bug Fix

#12484 errors.h: Add declarations for tip and vtip
  src/dmd/errors.h
Labels: Easy Review, auto-merge

#12486 dmd.expressionsem: Remove local variable from makeThis2Argument path.
  src/dmd/expressionsem.d
Labels: Refactoring, auto-merge

#12485 Fix Issue 21876 - Zero-length static arrays "cannot be read at compile time"
  src/dmd/dinterpret.d
  test/compilable/test21876.d
Labels: Bug Fix

#12487 Fix Issue 21878 - "ref" lost when indexing array in CTFE
  src/dmd/ctfeexpr.d
  test/runnable/interpret.d
Labels: Bug Fix, auto-merge

#12488 replace TOK.max_ with proper TOK.max+1
  src/dmd/frontend.h
  src/dmd/iasmdmd.d
  src/dmd/parse.d
  src/dmd/tokens.d
  src/dmd/tokens.h
  src/tests/cxxfrontend.c
Labels: Easy Review, Refactoring, auto-merge

#12490 Improve error message for base class followed by interface
  src/dmd/dsymbolsem.d
  test/fail_compilation/diag21883.d
Labels: Bug Fix, auto-merge
