Repository dlang/dmd, pull requests merged in 2021-12, with the labels that each got.

#13377 Disable -O for runnable_cxx/test7925.d due to a codegen issue
  test/runnable_cxx/test7925.d
  test/tools/d_do_test.d
Labels: auto-merge

#13371 Fix issue 22549 - float literal should support leading zero
  src/dmd/lexer.d
  test/fail_compilation/numliteral.c
Labels: auto-merge, Bug Fix, ImportC

#13374 Fix Issue 20860 - OpDispatch does not work for structs with constructor and destructor
  src/dmd/expressionsem.d
  test/compilable/test20860.d
Labels: Regression, auto-merge, Bug Fix

#13381 fix Issue 22566 - Error: unknown architecture feature '4+avx' for '-target'
  src/dmd/target.d
  test/unit/triple.d
Labels: auto-merge, Bug Fix

#13380 Fix Issue 17870 - Can't alias a mix of parent and child class members
  src/dmd/dtemplate.d
  test/compilable/test17870.d
Labels: Bug Fix

#13116 Translate _d_array{,set}ctor to templates
  src/dmd/dinterpret.d
  src/dmd/e2ir.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/id.d
  test/fail_compilation/fail10964.d
  test/fail_compilation/fail10968.d
Labels: SAOC

#13384 dmd.target: Initialize all float properties in initiallize()
  src/dmd/frontend.h
  src/dmd/target.d
Labels: auto-merge, Refactoring

#13385 fix Issue 22560 - ImportC: extra semicolon not allowed outside of fun…
  src/dmd/cparse.d
  test/compilable/test22560.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13378 fix Issue 22534 - ImportC: const pointer (not pointer to const) is tr…
  src/dmd/cparse.d
  test/compilable/test22534.c
  test/fail_compilation/fix22265.c
Labels: Bug Fix, ImportC

#13376 add string conversion for EXP
  src/dmd/hdrgen.d
  src/dmd/printast.d
  src/dmd/target.d
Labels: auto-merge, Easy Review, Refactoring

#13382 dmd.target: Declare enum CPU basetype as ubyte
  src/dmd/frontend.h
  src/dmd/target.d
  src/dmd/target.h
Labels: auto-merge, Refactoring

#13389 split off EXP into a separate type rather than an alias
  src/dmd/astbase.d
  src/dmd/cparse.d
  src/dmd/dtoh.d
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  src/dmd/iasmdmd.d
  src/dmd/iasmgcc.d
  src/dmd/initsem.d
  src/dmd/ob.d
  src/dmd/objc.d
  src/dmd/opover.d
  src/dmd/optimize.d
  src/dmd/parse.d
  src/dmd/statementsem.d
  src/dmd/staticcond.d
  src/dmd/tokens.d
  src/dmd/tokens.h
Labels: auto-merge, Easy Review, Refactoring

#13390 don't use operator precedence indexed by TOK
  src/dmd/parse.d
Labels: auto-merge

#13391 test: Add test for noreturn function parameter
  test/compilable/noreturn1.d
Labels: auto-merge, Easy Review

#13392 remove unused EXP values
  src/dmd/frontend.h
  src/dmd/tokens.d
  src/dmd/tokens.h
Labels: auto-merge

#13396 run.d: Improve error message for failed `unit` tests
  test/run.d
Labels: auto-merge, Continuous Integration

#13401 adjust os_critsecsize on 32 and 64 bit Solaris
  src/dmd/backend/os.d
Labels: auto-merge

#13405 Fix build for Solaris/Illumos
  src/dmd/backend/backconfig.d
Labels: auto-merge, Bug Fix

#13403 even more removal of EXP values
  src/dmd/frontend.h
  src/dmd/templateparamsem.d
  src/dmd/tokens.d
  src/dmd/tokens.h
  src/tests/cxxfrontend.c
Labels: auto-merge, Refactoring

#13407 eliminate many casts in optimize.d
  src/dmd/optimize.d
Labels: auto-merge, Easy Review, Refactoring

#13411 Fix Issue 22570 - more arguments than fields allowed in struct constructor
  src/dmd/expressionsem.d
  test/fail_compilation/fail22570.d
Labels: Regression, auto-merge, Bug Fix, Easy Review

#13410 test: Fix a number of broken directives
  test/compilable/test21299a.d
  test/compilable/test21299b.d
  test/fail_compilation/test17977.d
Labels: auto-merge, Easy Review

#13409 add necessary libraries to the default config on Solaris
  ini/solaris/bin32/dmd.conf
  ini/solaris/bin64/dmd.conf
Labels: auto-merge

#13408 [C++ headers] dmd.token: Change TOK and EXP to enum class types.
  src/dmd/frontend.h
  src/dmd/target.d
  src/dmd/target.h
  src/dmd/tokens.h
  src/tests/cxxfrontend.c
Labels: Regression, auto-merge

#13399 fix Issue 22538, fix Issue 22537 - ImportC: multiple static / non-static declarations of same function
  src/dmd/dsymbol.d
  test/fail_compilation/test22538.c
  test/runnable/test22538.c
Labels: auto-merge, Bug Fix, ImportC

#13414 test: runnable_cxx/cppa.d: Use C++11 std::string implementation
  test/runnable_cxx/cppa.d
  test/runnable_cxx/extra-files/cppb.cpp
Labels: auto-merge, Continuous Integration, extern (C/C++)

#13415 test: Test C++ mangling based on C++ runtime, not target platform.
  test/compilable/cppmangle.d
  test/compilable/cppmangle3.d
  test/compilable/issue21203.d
  test/compilable/issue21340.d
Labels: auto-merge, Continuous Integration, extern (C/C++)

#13417 fix Issue 22584 - importC: Error: undefined reference to 'parameter' when no parameter names in forward declaration
  src/dmd/dsymbol.d
  test/compilable/testcstuff2.c
  test/fail_compilation/failcstuff2.c
Labels: Regression, auto-merge, Bug Fix, ImportC

#13397 Fix Issue 20236 - spurious deprecation warnings on function calls wit…
  src/dmd/dsymbol.d
  test/compilable/test20236.d
Labels: Regression, Bug Fix, Easy Review

#13413 Start removing unused TOK values
  src/dmd/frontend.h
  src/dmd/tokens.d
  src/dmd/tokens.h
  src/tests/cxxfrontend.c
Labels: Easy Review, Refactoring

#13412 fix Issue 22577 - ImportC: decay of function to typedef'd const funct…
  src/dmd/importc.d
  test/compilable/test22577.c
Labels: Bug Fix, Easy Review, ImportC

#13416 test: runnable_cxx/cppa.d: Update test to be compilable with GCC 12 (development)
  test/runnable_cxx/cppa.d
Labels: auto-merge, Continuous Integration, extern (C/C++)

#13130 Fix Issue 20616 - Error: undefined identifier __dollar
  src/dmd/expressionsem.d
  src/dmd/opover.d
  test/fail_compilation/fail20616.d
Labels: Enhancement, auto-merge

#13422 fix Issue 22592 - importC: Segmentation fault indexing global array a…
  src/dmd/dsymbol.d
  test/runnable/test22592.c
Labels: auto-merge, Bug Fix, ImportC

#13420 fix Issue 22589 - importC: Error: undefined reference to '__builtin_va_start' and '__builtin_va_end'
  src/dmd/toir.d
  test/compilable/vastartend.c
Labels: auto-merge, Bug Fix, ImportC

#13419 fix Issue 22585 - importC: Error: variable 'var' extern symbols canno…
  test/runnable/test22585.c
Labels: auto-merge, Bug Fix

#13421 merge stable
  VERSION
  src/dmd/backend/backconfig.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code_x86.d
  src/dmd/backend/machobj.d
  src/dmd/backend/out.d
  src/dmd/constfold.d
  src/dmd/cparse.d
  src/dmd/ctfeexpr.d
  src/dmd/dinterpret.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/glue.d
  src/dmd/importc.d
  src/dmd/initsem.d
  src/dmd/lexer.d
  src/dmd/opover.d
  src/dmd/optimize.d
  src/dmd/parse.d
  src/dmd/printast.d
  src/dmd/semantic3.d
  src/dmd/statementsem.d
  src/dmd/todt.d
  src/dmd/toobj.d
  src/dmd/typesem.d
  test/compilable/test10028.d
  test/compilable/test20236.d
  test/compilable/test20860.d
  test/compilable/test21073.d
  test/compilable/test21414.d
  test/compilable/test22398.c
  test/compilable/test22422.c
  test/compilable/test22432.c
  test/compilable/test22534.c
  test/compilable/test22560.c
  test/compilable/test22577.c
  test/compilable/testcstuff2.c
  test/fail_compilation/b15875.d
  test/fail_compilation/fail116.d
  test/fail_compilation/fail22529.d
  test/fail_compilation/fail22570.d
  test/fail_compilation/failcstuff2.c
  test/fail_compilation/fix22265.c
  test/fail_compilation/ice22516.d
  test/fail_compilation/numliteral.c
  test/fail_compilation/test22538.c
  test/fail_compilation/test22574.d
  test/fail_compilation/test_switch_error.d
  test/runnable/interpret.d
  test/runnable/test16579.d
  test/runnable/test18054.d
  test/runnable/test22428.c
  test/runnable/test22500.c
  test/runnable/test22513.c
  test/runnable/test22538.c
Labels: Bug Fix

#13425 fix Issue 22597 - importC: Segmentation fault initializing va_list with __builtin_va_start
  src/dmd/e2ir.d
  test/runnable/test22597.c
Labels: Regression, Bug Fix, ImportC

#13429 dmd.typesem: Fix build on hosts where real_t is a struct
  src/dmd/typesem.d
Labels: GDC, auto-merge, Easy Review

#13427 Fix Issue 22593 - ICE on overloaded constructors
  src/dmd/dsymbolsem.d
  test/compilable/test22593.d
  test/fail_compilation/test22593.d
Labels: Regression, auto-merge, Bug Fix

#13424 fix Issue 22558 - [REG 2.098] Error: function 'core.stdc.stdio.vfprintf' 'pragma(printf)' functions must be 'extern(C) int vfprintf([parameters...], const(char)*, va_list)'
  src/dmd/typesem.d
  test/compilable/test22558.d
Labels: Regression, auto-merge, Bug Fix, ImportC

#13430 fix Issue 22591 - importC: Debug information for C sources have DW_AT…
  src/dmd/backend/dwarfdbginf.d
Labels: Easy Review, ImportC

#13426 minor refactor of elfobj.d and glue.d
  src/dmd/backend/elfobj.d
  src/dmd/glue.d
Labels: auto-merge, Easy Review, Refactoring

#13431 fix Issue 22602 - importC: Error: cannot convert string literal to 'void*'
  src/dmd/dcast.d
  test/compilable/testcstuff2.c
Labels: auto-merge, Bug Fix, ImportC

#13432 collect globals in glue.d into struct Glue
  src/dmd/glue.d
Labels: auto-merge, Easy Review, Refactoring

#13423 remove more unused TOKs
  src/dmd/frontend.h
  src/dmd/tokens.d
  src/dmd/tokens.h
  test/fail_compilation/ice17074.d
Labels: auto-merge, Easy Review, Refactoring

#13435 replace global objbuf with local variable
  src/dmd/glue.d
Labels: Easy Review, Refactoring

#13434 remove unsafe casts from dcast.d
  src/dmd/dcast.d
Labels: Easy Review, Refactoring

#13418 Make TOK a ubyte
  src/dmd/frontend.h
  src/dmd/tokens.d
  src/dmd/tokens.h
Labels: Easy Review, Refactoring

#13433 use D arrays for callFuncsAndGates()
  src/dmd/glue.d
Labels: auto-merge, Easy Review, Refactoring

#13436 Remove dead function tochars from token.d
  src/dmd/frontend.h
  src/dmd/tokens.d
Labels: auto-merge, Easy Review, extern (C/C++)

#13438 remove unsafe casts from initsem.d
  src/dmd/initsem.d
Labels: auto-merge, Easy Review, Refactoring

#13439 remove unsafe casts from typesem.d
  src/dmd/typesem.d
Labels: auto-merge, Easy Review, Refactoring

#13428 Update osmodel.mak with ARCH
  src/osmodel.mak
Labels: 72h no objection -> merge

#13441 fix Issue 22531 - importC: D name mangling applied to forward declara…
  src/dmd/tocsym.d
  test/runnable/test22531.c
Labels: Bug Fix, ImportC

#13437 fix Issue 22576 - ImportC: cannot implicitly convert expression S(0) …
  src/dmd/initsem.d
  test/runnable/test22567.c
Labels: Bug Fix, ImportC

#13398 Translate _d_delstruct to template
  src/dmd/canthrow.d
  src/dmd/dinterpret.d
  src/dmd/e2ir.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/nogc.d
Labels: 72h no objection -> merge

#13444 Merge stable
  VERSION
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/elfobj.d
  src/dmd/dcast.d
  src/dmd/dsymbol.d
  src/dmd/dsymbolsem.d
  src/dmd/e2ir.d
  src/dmd/glue.d
  src/dmd/initsem.d
  src/dmd/semantic3.d
  src/dmd/tocsym.d
  src/dmd/toir.d
  src/dmd/typesem.d
  test/compilable/test22558.d
  test/compilable/test22593.d
  test/compilable/testcstuff2.c
  test/compilable/vastartend.c
  test/fail_compilation/test22593.d
  test/runnable/test22531.c
  test/runnable/test22567.c
  test/runnable/test22585.c
  test/runnable/test22592.c
  test/runnable/test22597.c
Labels: Bug Fix, stable -> master

#13445 dmd.tokens: Remove commented out tokens
  src/dmd/tokens.d
  src/dmd/tokens.h
Labels: Trivial, auto-merge

#13404 Fix Issue 22136 - [REG 2.097.1] hashOf failed to compile because of d…
  src/dmd/mtype.d
  test/compilable/commontype.d
  test/runnable/test22136.d
  test/runnable/testconst.d
Labels: Regression, Bug Fix, 72h no objection -> merge

#13446 Move fix for issue 22531 from glue layer to frontend
  src/dmd/dmangle.d
  src/dmd/tocsym.d
Labels: Trivial, Easy Review

#13450 docs: Replace http:// with https:// for digitalmars.com links
  docs/man/man1/obj2asm.1
Labels: Trivial, auto-merge

#13451 test: Replace http:// with https:// for digitalmars.com links
  test/compilable/99bottles.d
  test/compilable/art4769.d
  test/compilable/test69.d
  test/fail_compilation/fail15.d
  test/fail_compilation/fail35.d
  test/fail_compilation/fail73.d
  test/runnable/iasm.d
  test/runnable/iasm64.d
  test/runnable/template1.d
  test/runnable/template2.d
  test/runnable/template6.d
  test/runnable/test12.d
  test/runnable/test15.d
  test/runnable/test22.d
Labels: Trivial, auto-merge

#13456 Replace http:// with https:// for forum, issues, and wiki dlang.org links
  CONTRIBUTING.md
  README.md
  src/dmd/e2ir.d
  src/dmd/globals.d
  src/dmd/globals.h
  test/fail_compilation/fail11.d
  test/fail_compilation/test20903.d
  test/runnable/template10.d
  test/runnable/testarray.d
Labels: Trivial, auto-merge

#13457 Replace d.puremagic.com links with issues.dlang.org
  test/runnable/testcontracts.d
  test/runnable/testsafe.d
  test/runnable/xtest46.d
Labels: Trivial, auto-merge

#13458 Replace http:// with https:// for various links throughout codebase
  .editorconfig
  samples/posix.mak
  src/dmd/backend/dwarf.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/mscoffobj.d
  src/dmd/chkformat.d
  src/dmd/dmodule.d
  src/dmd/entity.d
  src/dmd/expressionsem.d
  src/dmd/globals.d
  src/dmd/intrange.d
  src/dmd/root/longdouble.h
  src/dmd/root/stringtable.d
  test/runnable/traits_child.d
Labels: Trivial, auto-merge

#13452 Replace http:// with https:// for github.com links
  test/runnable/mars1.d
Labels: auto-merge

#13455 test: Replace http:// with https:// for dlang.org links
  src/tests/cxxfrontend.c
  test/runnable/template9.d
Labels: Trivial, auto-merge

#13460 better error message for if(exp))
  src/dmd/parse.d
  test/fail_compilation/misc_parser_err_cov1.d
Labels: Diagnostic Messages

#13453 Replace http:// with https:// for msdn links
  src/dmd/backend/cod1.d
  src/dmd/backend/cod3.d
  src/dmd/backend/pdata.d
  src/dmd/target.d
  src/dmd/tocsym.d
Labels: auto-merge

#13461 better closing paren error message
  src/dmd/parse.d
  test/fail_compilation/misc_parser_err_cov1.d
  test/fail_compilation/parseStc.d
Labels: auto-merge, Diagnostic Messages

#13462 Use %llu instead of %zu as a format specifier in errors
  src/dmd/ctfeexpr.d
  src/dmd/expressionsem.d
  src/dmd/typesem.d
Labels: auto-merge, Easy Review

#13464 fix issue 22630 - It is possible for VS to be installed and providing…
  src/dmd/vsoptions.d
Labels: auto-merge, Bug Fix

#13466 backconfig.d: fix ddoc header and indenting
  src/dmd/backend/backconfig.d
Labels: Trivial, documentation

#13467 Fix issue 22634 - assert for too many symbols should be error
  src/dmd/expressionsem.d
  test/fail_compilation/fail22634.d
Labels: Bug Fix

#13468 gather all code that sets predefined versions into mars.d
  src/dmd/frontend.h
  src/dmd/mars.d
  src/dmd/target.d
Labels: Easy Review, Refactoring

#13469 backconfig.d: reduce use of globals
  src/dmd/backend/backconfig.d
  src/dmd/backend/global.d
  test/runnable/test20855.d
Labels: auto-merge, Easy Review, Refactoring

#13470 refactor parseOS(), check for overflow
  src/dmd/frontend.h
  src/dmd/mars.d
  src/dmd/target.d
Labels: auto-merge, Easy Review

#13471 dmd.root.env: Remove dmd.globals import, move to root library
  src/build.d
  src/dmd/README.md
  src/dmd/dinifile.d
  src/dmd/link.d
  src/dmd/root/README.md
  src/dmd/root/env.d
  src/dmd/vsoptions.d
Labels: auto-merge, Easy Review, Refactoring

#13472 Move dmd.complex to dmd.root.complex
  src/build.d
  src/dmd/README.md
  src/dmd/asttypename.d
  src/dmd/constfold.d
  src/dmd/ctfeexpr.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  src/dmd/root/README.md
  src/dmd/root/complex.d
  src/dmd/root/complex_t.h
  src/dmd/tocsym.d
  src/dmd/todt.d
  src/dmd/typesem.d
  src/tests/cxxfrontend.c
Labels: auto-merge, Easy Review, Refactoring

#13474 Remove support for SemaphoreCI pipelines
  semaphoreci.sh
Labels: auto-merge, Continuous Integration

#13473 Move dmd.utf to the root library
  dub.sdl
  src/build.d
  src/dmd/README.md
  src/dmd/constfold.d
  src/dmd/dcast.d
  src/dmd/dinterpret.d
  src/dmd/dmangle.d
  src/dmd/doc.d
  src/dmd/dsymbolsem.d
  src/dmd/errors.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/identifier.d
  src/dmd/lexer.d
  src/dmd/root/README.md
  src/dmd/root/utf.d
  src/dmd/semantic2.d
  src/dmd/semantic3.d
  src/dmd/tokens.d
Labels: auto-merge, Easy Review, Refactoring

#13477 dmd.globals: Change StorageClass type from uinteger_t to ulong
  src/dmd/globals.d
Labels: auto-merge, Easy Review, Refactoring

#13475 workflows/runnable_cxx.yml: Add newer versions of gcc and clang to test
  .github/workflows/runnable_cxx.yml
Labels: Continuous Integration

#13480 ci: make Cirrus CI configuration YAML compliant
  .cirrus.yml
Labels: Trivial, auto-merge, Continuous Integration

#13479 add some allocation overflow checks
  src/dmd/backend/barray.d
  src/dmd/backend/cgelem.d
  src/dmd/backend/cgxmm.d
  src/dmd/backend/cod3.d
  src/dmd/backend/dt.d
  src/dmd/backend/dwarfeh.d
Labels: auto-merge, Easy Review

#13481 Enable runnable/bitfieldsdm.c for win32 - omf
  test/README.md
  test/runnable/bitfieldsdm.c
  test/tools/d_do_test.d
Labels: Continuous Integration
