Repository dlang/dmd, pull requests merged in 2022-11, with the labels that each got.

#14608 Re-enable enregistering of XMM registers
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/cod3.d
Labels: auto-merge

#14482 Fix Issue 23368 - Don't segfault on throwing null exception
  compiler/src/dmd/dinterpret.d
  compiler/test/fail_compilation/throwexp.d
Labels: Enhancement, auto-merge, Bug Fix

#14609 merge stable
  .github/workflows/pre_commit.yml
  VERSION
  changelog/README.md
  changelog/dmd.scope-array-on-stack.dd
  changelog/dmd.system-variables.dd
  changelog/dmd.unicode-directionality.dd
  changelog/dmd.windows_stack_limit.dd
  compiler/src/build.d
  compiler/src/dmd/blockexit.d
  compiler/src/dmd/dclass.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/root/utf.d
  compiler/test/compilable/test23431.d
  compiler/test/compilable/test23431_minimal.d
  compiler/test/compilable/test23433.d
  compiler/test/compilable/test23439.d
  compiler/test/fail_compilation/fail23439.d
  compiler/test/fail_compilation/warn14905.d
  compiler/test/unit/lexer/lexer_dmdlib.d
Labels: Bug Fix

#14470 Fix `rt_trap_exceptions_drt_gdb` in the presence of optimisations
  druntime/test/exceptions/Makefile
Labels: auto-merge

#14578 add isXExpression() method for most expression types in ASTBase
  compiler/src/dmd/astbase.d
Labels: auto-merge-squash

#14612 Fix Issue 23456 - OpenBSD: Add waitid support
  druntime/src/core/sys/posix/sys/wait.d
Labels: Enhancement

#14615 Convert `DwEhTable` to `Barray`
  compiler/src/dmd/backend/dwarf.d
  compiler/src/dmd/backend/dwarfdbginf.d
  compiler/src/dmd/backend/dwarfeh.d
Labels: Refactoring

#14619 Fix 15712 - extern(C) attribute inside extern(C) unittest is incorrectly ignored
  compiler/src/dmd/parse.d
  compiler/test/compilable/test15712.d
Labels: auto-merge, Bug Fix

#14617 Fix Issue 23458 - No template candidates listed when OverDeclaration …
  compiler/src/dmd/dtemplate.d
  compiler/test/fail_compilation/diag14818.d
Labels: Enhancement, auto-merge

#14614 Deprecate `Array.dim`
  compiler/src/dmd/root/array.d
Labels: auto-merge, Refactoring

#14618 Don't use 'Candidate is' when there is more than one alias function overload
  compiler/src/dmd/func.d
  compiler/test/fail_compilation/diag14818.d
  compiler/test/fail_compilation/ice13459.d
Labels: Enhancement, Bug Fix

#14620 Fix Issue 23463 - Don't count skipped function overloads when limiting overloads shown
  compiler/src/dmd/func.d
  compiler/test/fail_compilation/diag8101.d
  compiler/test/fail_compilation/fail15616b.d
Labels: Bug Fix

#14623 fix Issue 23462 - dmd: src/dmd/backend/cod2.d:2158: Assertion cast(in…
  compiler/src/dmd/backend/cgelem.d
  compiler/test/runnable/testxmm2.d
Labels: auto-merge, Bug Fix, Easy Review

#14621 fix Issue 22759 - ImportC: cannot modify const expression from derefe…
  compiler/src/dmd/cparse.d
  compiler/test/fail_compilation/cconst1.c
  compiler/test/fail_compilation/failcstuff2.c
  compiler/test/fail_compilation/test22759.c
Labels: Bug Fix, ImportC

#14626 Fix Issue 23466 - -verrors=context should not repeat same context for supplemental m…
  compiler/src/dmd/errors.d
  compiler/test/fail_compilation/fail_pretty_errors.d
Labels: Enhancement, auto-merge

#14624 Fix 23465 - Invalid token error points to wrong line
  compiler/src/dmd/lexer.d
  compiler/test/fail_compilation/lexer23465.d
Labels: auto-merge, Bug Fix

#14628 Fix Issue 23470 - Backticks in diagnostic are confusing with wrong nu…
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/mtype.d
  compiler/test/fail_compilation/diag8101.d
  compiler/test/fail_compilation/diag_funclit.d
  compiler/test/fail_compilation/diagin.d
  compiler/test/fail_compilation/fail99.d
  compiler/test/fail_compilation/ice10922.d
  compiler/test/fail_compilation/ice9540.d
  compiler/test/fail_compilation/test21008.d
Labels: Bug Fix

#14625 Fix 19623 - HERE string identifier cannot start with Unicode letter
  compiler/src/dmd/lexer.d
  compiler/test/runnable/lexer.d
Labels: auto-merge, Bug Fix

#14627 Fix 21062 - Confusing error when using a keyword as an identifier for…
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/test21062.d
  compiler/test/unit/parser/aliasdeclaration_location.d
  compiler/test/unit/parser/conditionalcompilation_location.d
  compiler/test/unit/parser/linkage_location.d
  compiler/test/unit/parser/visibilitydeclaration_location.d
Labels: Bug Fix, Diagnostic Messages

#14629 fix Issue 21301 - Wrong values being passed in long parameter list
  compiler/src/dmd/backend/dtype.d
  compiler/src/dmd/backend/var.d
  compiler/test/runnable/test21301.d
Labels: Bug Fix

#14622 fix Issue 23461 - dmd: src/dmd/backend/cod1.d:2037: Assertion false f…
  compiler/src/dmd/backend/cod4.d
  compiler/test/runnable/testxmm2.d
Labels: Enhancement, auto-merge, Bug Fix, Easy Review

#14634 change symbol_name() to use []
  compiler/src/dmd/backend/dwarfdbginf.d
  compiler/src/dmd/backend/ee.d
  compiler/src/dmd/backend/elpicpie.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/machobj.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/backend/nteh.d
  compiler/src/dmd/backend/pdata.d
  compiler/src/dmd/backend/symbol.d
  compiler/src/dmd/eh.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/objc_glue.d
  compiler/src/dmd/tocsym.d
  compiler/src/dmd/toobj.d
Labels: auto-merge, Easy Review, Refactoring, Backend

#14637 remove some dead code from cgen.d
  compiler/src/dmd/backend/cgen.d
  compiler/src/dmd/backend/code.d
Labels: Easy Review, Refactoring, Backend

#14632 change symbol_calloc() to use slices
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/drtlsym.d
  compiler/src/dmd/backend/dtype.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/gsroa.d
  compiler/src/dmd/backend/symbol.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/tocsym.d
Labels: Easy Review, Refactoring, Backend

#14636 fix Issue 23479 - ImportC recognizes .i and .c files, but not .h files
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/file_manager.d
  compiler/src/dmd/globals.d
  compiler/src/dmd/mars.d
  compiler/test/compilable/test23479.h
Labels: Enhancement, Easy Review, ImportC

#14643 merge stable
  VERSION
  changelog/dmd.bitfields.dd
  changelog/dmd.class_instance_alignment.dd
  changelog/dmd.crt_constructor_signature.dd
  changelog/dmd.d_optimized.dd
  changelog/dmd.deprecate_throwing_nothrow_contracts.dd
  changelog/dmd.deprecate_version_int.dd
  changelog/dmd.dip1000_deprecation_warnings.dd
  changelog/dmd.dtoh-improvements.dd
  changelog/dmd.fix-immutable-conv.dd
  changelog/dmd.fix22134.dd
  changelog/dmd.importc_typeof.dd
  changelog/dmd.markdown.dd
  changelog/dmd.new-aa.dd
  changelog/dmd.previewInLink.dd
  changelog/dmd.shortenedMethodsEnabled.dd
  changelog/dmd.unicode-directionality.dd
  changelog/dmd.windows_stack_limit.dd
  changelog/druntime.cpuid-add-avx512f.dd
  changelog/druntime.drt-oncycle-deprecate.dd
  changelog/druntime.posix_gc_signals.dd
  compiler/src/dmd/backend/cod4.d
  compiler/src/dmd/dinterpret.d
  compiler/test/fail_compilation/throwexp.d
  compiler/test/runnable/testxmm2.d
  druntime/src/core/sys/posix/sys/wait.d
Labels: Enhancement, auto-merge, Bug Fix

#14638 Fix Issue 23480 - non-empty ForStatement Increment clause should requ…
  changelog/dmd.for-increment.dd
  compiler/src/dmd/statementsem.d
  compiler/test/compilable/test4375.d
  compiler/test/fail_compilation/fail_arrayop2.d
  compiler/test/fail_compilation/misc1.d
Labels: Enhancement

#14645 refactor semantic() for ForeachStatement
  compiler/src/dmd/statementsem.d
Labels: auto-merge, Easy Review, Refactoring

#14648 Fix Issue 23498 - OpenBSD: Fix core.sys.posix.sys.wait
  druntime/src/core/sys/posix/sys/wait.d
Labels: Enhancement

#14432 Fix Issue 23332 - core.sync.condition notify methods should be @nogc
  druntime/src/core/exception.d
  druntime/src/core/sync/condition.d
  druntime/src/core/sync/mutex.d
Labels: Enhancement, Easy Review

#14654 fix Issue 21506 - misalignment of _argptr for variadic functions
  compiler/src/dmd/backend/cgelem.d
  compiler/test/runnable/test21506.d
Labels: auto-merge, Bug Fix, Easy Review, Backend

#14656 test: Fix cdcmp output to match binutils 2.39
  compiler/test/compilable/extra-files/cdcmp.out
  compiler/test/compilable/extra-files/objdump-postscript.sh
Labels: auto-merge

#14655 target: Vector comparison needs instruction support in CPU
  compiler/src/dmd/target.d
  compiler/test/runnable/testxmm.d
Labels: auto-merge

#14649 Fix 23491 - Nonsensical deprecation message when using delegate
  compiler/src/dmd/escape.d
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/retscope.d
  compiler/test/fail_compilation/retscope2.d
  compiler/test/fail_compilation/test23491.d
Labels: Bug Fix, dip1000

#14659 [super trivial] Fix confusing comment in the parser
  compiler/src/dmd/parse.d
Labels: auto-merge
