Repository dlang/dmd, pull requests merged in 2022-01, with the labels that each got.

#13465 Fix issue 22632 - Crash happens when CTFE compares an associative arr…
  src/dmd/ctfeexpr.d
  test/compilable/test22632.d
Labels: auto-merge, Bug Fix

#13485 sort commands in README.md
  test/README.md
Labels: Trivial, documentation

#13482 Azure: Replace deprecated vs2017-win2016 image with windows-2019
  azure-pipelines.yml
Labels: auto-merge, Continuous Integration

#13487 Move AST enums defined in dmd.global to astenums
  src/dmd/astenums.d
  src/dmd/denum.d
  src/dmd/dtoh.d
  src/dmd/globals.d
  src/dmd/nspace.d
  src/dmd/target.d
  test/unit/semantic/covariance.d
Labels: Refactoring

#9629 Lower CmpExp between classes to __cmp call
  src/dmd/expressionsem.d
  src/dmd/opover.d
  test/runnable/class_opCmp.d
Labels: 72h no objection -> merge

#13489 d_do_test: Add unittests for `findTestParameter` & `findOutputParameter`
  test/tools/d_do_test.d
Labels: auto-merge, Continuous Integration

#13492 Simplify a few usages of `Expression.toBool`
  src/dmd/constfold.d
  src/dmd/staticcond.d
Labels: Refactoring

#13493 Replace usages of Optional.hasValue(...) assuming a value with get()
  src/dmd/constfold.d
  src/dmd/optimize.d
  src/dmd/traits.d
Labels: auto-merge, Refactoring

#13246 backend: dwarfdbginf: Use LEB128 encoding for lines and columns
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge

#13447 add -vasm option that prints generated code per function
  src/build.d
  src/dmd/backend/backconfig.d
  src/dmd/backend/cdef.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code.d
  src/dmd/backend/disasm86.d
  src/dmd/backend/nteh.d
  src/dmd/cli.d
  src/dmd/dmsc.d
  src/dmd/mars.d
Labels: auto-merge, Diagnostic Messages, Backend

#13504 change .lsw .msw to .lo .hi for struct Cent
  src/dmd/backend/cdef.d
  src/dmd/backend/cod1.d
  src/dmd/backend/cod4.d
  src/dmd/backend/elem.d
  src/dmd/backend/evalu8.d
  src/dmd/e2ir.d
Labels: Easy Review, Refactoring

#13497 Turn switch case fallthrough into an error
  changelog/switch_fallthrough_error.dd
  src/dmd/blockexit.d
  test/fail_compilation/b16967.d
  test/fail_compilation/fail11653.d
Labels: auto-merge, Deprecation -> Error

#13508 fix Issue 22655 - Disassembler assertion on rdtsc
  src/dmd/backend/disasm86.d
Labels: auto-merge, Bug Fix

#13274 backend: use correct type names for D
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/var.d
  test/dshell/extra-files/dwarf/excepted_results/fix22469.txt
  test/dshell/extra-files/dwarf/fix22469.d
Labels: Enhancement, auto-merge

#13505 add cents to e2ir.d type conversions
  src/dmd/e2ir.d
Labels: auto-merge

#13517 Coverage: Don't fail if reports could not be uploaded to CodeCov
  .azure-pipelines/windows.sh
  .azure-pipelines/windows.yml
Labels: auto-merge, Continuous Integration

#13513 dmd.target: Add target.supportsLinkerDirective and target.cpp.splitVBasetable
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
  src/dmd/target.d
  src/dmd/target.h
Labels: auto-merge, Easy Review, Refactoring

#13514 dmd.dmdparams: Move dmdParams struct to own module
  src/build.d
  src/dmd/dmdparams.d
  src/dmd/dmsc.d
  src/dmd/link.d
  src/dmd/mars.d
Labels: auto-merge, Easy Review, Refactoring

#13526 dmd.cppmanglewin: Use target.isLP64 as the gate for following x64 ABI on Windows
  src/dmd/cppmanglewin.d
Labels: auto-merge, Easy Review, Refactoring

#13523 build.d: Skip detection of the unused CXX_KIND variable
  src/build.d
Labels: auto-merge

#13524 [stable] Makefiles: Explicitly forward ENABLE_LTO like the other options
  src/posix.mak
  src/win32.mak
  src/win64.mak
Labels: auto-merge

#13527 dmd.target: Move target independent logic of TargetCPP.parameterType back to cppmangle
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/frontend.h
  src/dmd/target.d
  src/dmd/target.h
Labels: auto-merge, Easy Review, Refactoring

#13531 Update source guide
  src/dmd/README.md
  src/dmd/root/README.md
  src/dmd/root/optional.d
Labels: Trivial, auto-merge, documentation

#13529 Revise main README.md and add a repository overview
  CONTRIBUTING.md
  README.md
Labels: auto-merge, documentation

#13525 build.d: Don't print stack traces when an executable is missing
  src/build.d
Labels: auto-merge, Continuous Integration

#13520 fix Issue 22665 - ImportC: qualified enum values should be of enum ty…
  src/dmd/expressionsem.d
  test/compilable/imports/imp22665.c
  test/compilable/test22665.d
Labels: auto-merge, Bug Fix

#13463 Fix issue 10584 - Unhelpful error default constructing nested class
  src/dmd/expressionsem.d
  test/fail_compilation/fail132.d
  test/fail_compilation/fail276.d
  test/fail_compilation/fail59.d
  test/fail_compilation/fail60.d
Labels: Bug Fix

#13516 Fix 22365 - Don't crash for conditionally empty body of a TryStatement
  src/dmd/statementsem.d
  test/compilable/dlangui_crash.d
Labels: auto-merge, Bug Fix

#13459 improve ; expected error message
  src/dmd/parse.d
  test/fail_compilation/diag8684.d
  test/fail_compilation/fail196.d
  test/fail_compilation/fail207.d
  test/fail_compilation/fail4269e.d
Labels: auto-merge, Diagnostic Messages

#13530 Fix issue 22298 - Nested function's scope parameters can be assigned to variables in enclosing function
  src/dmd/astbase.d
  src/dmd/declaration.d
  src/dmd/dsymbolsem.d
  src/dmd/escape.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  test/fail_compilation/test22298.d
Labels: auto-merge, Bug Fix, dip1000

#13533 Fix 22668 - Don't error when a deprecated method overrides another one
  src/dmd/dsymbolsem.d
  test/compilable/deprecated_override.d
Labels: auto-merge, Bug Fix

#13501 Fix Issue 22672 - Allow casting from TypeTuple to TypeTuple
  changelog/allow_casting_from_typetuple_to_typetuple.dd
  src/dmd/dcast.d
  src/dmd/expressionsem.d
  test/compilable/casttuple.d
  test/fail_compilation/casttuple.d
Labels: Enhancement, auto-merge

#13534 [dip1000] remove special case for class member assignment
  src/dmd/escape.d
Labels: auto-merge, dip1000

#13519 Azure: Fix CodeCov upload by using a proper login shell
  .azure-pipelines/windows.yml
  ci/codecov.sh
Labels: auto-merge, Continuous Integration

#13536 add common/int128.d
  src/build.d
  src/dmd/backend/cdef.d
  src/dmd/common/int128.d
Labels: auto-merge, Easy Review

#13521 fix Issue 22666 - ImportC: Error: attributes should be specified befo…
  src/dmd/cparse.d
  test/fail_compilation/failcstuff1.c
Labels: Bug Fix, Easy Review

#13490 add -os=<os> switch
  src/dmd/cli.d
  src/dmd/mars.d
  test/compilable/testos.d
Labels: Easy Review

#13491 d_do_test: Remove duplication between findTestParameter and findOutputParameter
  test/README.md
  test/tools/d_do_test.d
Labels: Continuous Integration, Refactoring

#13539 ImportC: add support for importing modules with __import
  changelog/__import.dd
  src/dmd/cparse.d
  src/dmd/frontend.h
  src/dmd/parse.d
  src/dmd/tokens.d
  src/dmd/tokens.h
  test/compilable/cimport.c
  test/compilable/imports/impcimport.c
  test/unit/lexer/location_offset.d
Labels: Enhancement, Easy Review, ImportC

#13512 Add Target.ObjectFormat, use it
  src/dmd/dmsc.d
  src/dmd/glue.d
  src/dmd/lib.d
  src/dmd/link.d
  src/dmd/target.d
  src/dmd/toir.d
Labels: Refactoring

#13542 Fix Issue 22646 - [REG2.099] CT bounds checking ignores short circuit evaluation
  src/dmd/expressionsem.d
  test/compilable/test22646.d
Labels: Regression, auto-merge, Bug Fix, Easy Review

#13544 Improve wording of error message for IFTI failure
  src/dmd/func.d
  test/fail_compilation/bug9631.d
  test/fail_compilation/constraints_aggr.d
  test/fail_compilation/constraints_func1.d
  test/fail_compilation/constraints_func2.d
  test/fail_compilation/constraints_func3.d
  test/fail_compilation/constraints_func4.d
  test/fail_compilation/diag13942.d
  test/fail_compilation/diag16977.d
  test/fail_compilation/diag8101.d
  test/fail_compilation/diag8648.d
  test/fail_compilation/diag9004.d
  test/fail_compilation/diagin.d
  test/fail_compilation/fail12744.d
  test/fail_compilation/fail14669.d
  test/fail_compilation/fail162.d
  test/fail_compilation/fail20730b.d
  test/fail_compilation/fail236.d
  test/fail_compilation/fail8009.d
  test/fail_compilation/fail95.d
  test/fail_compilation/ice11856_0.d
  test/fail_compilation/ice11856_1.d
  test/fail_compilation/ice14130.d
  test/fail_compilation/ice14907.d
  test/fail_compilation/ice6538.d
  test/fail_compilation/ice9284.d
  test/fail_compilation/test19107.d
Labels: auto-merge

#13545 Partial fix for issue 14892: define D_ProfileGC for -profile=gc
  src/dmd/mars.d
Labels: auto-merge

#13548 build.d: Properly translate ENABLE_LTO for other compilers than LDC
  src/build.d
Labels: auto-merge, Build System

#13541 fix Issue 22676 - Error: cannot implicitly convert expression 'T!C' of type 'void' to 'string'
  src/dmd/dclass.d
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  src/dmd/mtype.d
  test/compilable/test22676.d
Labels: Bug Fix

#13551 fix Issue 3818 - Generic error message for wrong foreach
  src/dmd/parse.d
  test/fail_compilation/test3818.d
Labels: auto-merge, Bug Fix, Diagnostic Messages

#13553 refactor use of target in mars.d
  src/dmd/mars.d
Labels: Easy Review, Refactoring

#13554 Fix issue 22685: Symbol nested in both function and module? Not a problem.
  src/dmd/dtemplate.d
  test/compilable/imports/test22685b.d
  test/compilable/imports/test22685c.d
  test/compilable/test22685.d
Labels: Bug Fix

#13552 fix issue 5096: bad unmatched closing brace messages
  src/dmd/parse.d
  test/fail_compilation/bug5096.d
  test/fail_compilation/diag19225.d
  test/fail_compilation/fail220.d
  test/fail_compilation/test16188.d
  test/fail_compilation/test17284.d
Labels: Enhancement

#13555 Fix 22659 - Do not gag semantic errors from `_d_array{,set}ctor`
  src/dmd/expressionsem.d
  test/fail_compilation/fail10968.d
Labels: auto-merge, Bug Fix

#13557 Fix Issue 22686 - ICE: dmd segfaults on invalid member reference in static function
  src/dmd/expressionsem.d
  test/fail_compilation/test22686.d
Labels: Regression, auto-merge, Bug Fix

#13532 ImportC: start importing __builtins.d
  src/dmd/cparse.d
  src/dmd/frontend.h
  src/dmd/id.d
  test/runnable/test22597.c
Labels: Blocking Other Work, ImportC

#13110 Produce MS Coff by default when targetting windows
  .azure-pipelines/windows.sh
  azure-pipelines.yml
  changelog/fix18964.dd
  src/dmd/cli.d
  src/dmd/frontend.h
  src/dmd/glue.d
  src/dmd/mars.d
  src/dmd/target.d
  src/dmd/target.h
  test/fail_compilation/invalid_lib.d
Labels: stalled

#13071 Fix Issue 22291 - Implement __traits(parameters)
  changelog/TraitsParameters.dd
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/traits.d
  test/compilable/fix22291.d
  test/fail_compilation/diag11819b.d
  test/fail_compilation/traits_parameters.d
Labels: Enhancement, New Language Feature, Walter Bright

#13162 Implement throw expressions (DIP 1034)
  changelog/throw_expression.dd
  src/dmd/astbase.d
  src/dmd/blockexit.d
  src/dmd/canthrow.d
  src/dmd/dinterpret.d
  src/dmd/e2ir.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  src/dmd/parse.d
  src/dmd/parsetimevisitor.d
  src/dmd/sideeffect.d
  src/dmd/statement.d
  src/dmd/statement.h
  src/dmd/statementsem.d
  src/dmd/strictvisitor.d
  src/dmd/transitivevisitor.d
  src/dmd/visitor.h
  src/tests/cxxfrontend.c
  test/compilable/extra-files/header1.d
  test/compilable/extra-files/header1.di
  test/compilable/extra-files/header1i.di
  test/compilable/noreturn1.d
  test/fail_compilation/noreturn.d
  test/fail_compilation/noreturn2.d
  test/runnable/noreturn1.d
  test/unit/semantic/control_flow.d
Labels: auto-merge, New Language Feature

#13559 remove dead __builtin code
  src/dmd/cparse.d
  src/dmd/e2ir.d
  src/dmd/frontend.h
  src/dmd/id.d
Labels: Easy Review, Refactoring

#13550 Follow up to PR#13545: update testsuite.
  src/dmd/cli.d
  test/fail_compilation/reserved_version.d
  test/fail_compilation/reserved_version_switch.d
Labels: auto-merge

#13561 fix Issue 22631 - ImportC: support C++11 unscoped enums with underlyi…
  src/dmd/cparse.d
  src/dmd/denum.d
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  src/dmd/mtype.d
  src/dmd/typesem.d
  test/compilable/enumbase.c
Labels: Enhancement, auto-merge, Easy Review, ImportC

#13562 Improve diagnostics for escaping reference to parameter `this`
  src/dmd/escape.d
  test/fail_compilation/dip25.d
  test/fail_compilation/test16589.d
  test/fail_compilation/test17450.d
Labels: auto-merge

#13564 fix Issue 22624 - ImportC: struct members in static initializer misal…
  src/dmd/todt.d
  test/runnable/fix22624.d
  test/runnable/imports/imp22624.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13565 fix Issue 22623 - ImportC: typedef'd struct definition tag not put in…
  src/dmd/cparse.d
  test/compilable/fix22623.c
  test/fail_compilation/failcstuff3.c
  test/fail_compilation/failcstuff4.c
Labels: Bug Fix, ImportC

#13522 Fix issue 22137 - -preview=dip1000 enables visibility checks for tupleof
  src/dmd/access.d
  src/dmd/dscope.d
  src/dmd/opover.d
  src/dmd/typesem.d
  test/fail_compilation/imports/imp18554.d
  test/fail_compilation/imports/issue21936s.d
  test/fail_compilation/issue21936.d
  test/fail_compilation/test18554.d
Labels: Bug Fix, dip1000

#13357 fix Issue 22541 - DIP1000: Resolve ambiguity of ref-return-scope para…
  changelog/22541.dd
  src/dmd/parse.d
  test/fail_compilation/test22541.d
Labels: Enhancement, auto-merge, dip1000

#13569 split off Parser.parseAliasReassignment()
  src/dmd/parse.d
Labels: auto-merge, Easy Review, Refactoring

#13566 Fix Issue 22127 - compiler assertion failure parser on UDA and function literal
  src/dmd/parse.d
  test/fail_compilation/fail22127.d
Labels: auto-merge, Bug Fix

#13570 split parseAliasDeclarations() off from parseDeclarations()
  src/dmd/parse.d
Labels: auto-merge, Easy Review, Refactoring

#12890 fix issues 22130, 17635 - pure factory functions
  src/dmd/astenums.d
  src/dmd/dcast.d
  src/dmd/frontend.h
  src/dmd/json.d
  src/dmd/link.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/sideeffect.d
  test/compilable/fix17635.d
  test/compilable/issue22130.d
  test/fail_compilation/fix17635.d
Labels: Bug Fix, auto-merge-squash

#13572 Adapt windows.sh to the new default for -m32
  .azure-pipelines/windows.sh
Labels: auto-merge, Continuous Integration

#13573 build.d: Target Linux64 when generating C++ headers
  src/build.d
Labels: Build System, Continuous Integration

#13574 some adjustment to parseAliasDeclarations()
  src/dmd/parse.d
Labels: auto-merge, Easy Review, Refactoring

#13567 Restore OMF builds and adapt windows.sh to MODEL=32omf
  .azure-pipelines/windows.sh
  azure-pipelines.yml
  src/dmd/mars.d
  test/dshell/dll.d
  test/dshell/dll_cxx.d
  test/dshell/linker_flag_with_spaces.d
  test/run.d
  test/runnable_cxx/cppa.d
  test/tools/d_do_test.d
Labels: auto-merge, Continuous Integration

#13549 posix.mak: Invoke bash to run the bootstrap script
  src/posix.mak
Labels: Easy Review

#13571 Fix issue 22139 - Compiler special cases object.dup when compiling with -preview=dip1000
  src/dmd/dcast.d
Labels: auto-merge, Bug Fix

#13488 d_do_test: Remove implicit `-fPIC` when using `-target` / `-os`
  test/tools/d_do_test.d
Labels: Continuous Integration

#13577 Fix issue 22709 - [dip1000] slice of static array can be escaped in @safe using ref arguments
  src/dmd/escape.d
  test/fail_compilation/retscope5.d
  test/fail_compilation/test22709.d
Labels: Bug Fix, dip1000

#13576 fix Issue 22705 - ImportC: forward reference to struct typedef gives …
  src/dmd/cparse.d
  src/dmd/dsymbol.d
  test/compilable/test22705.c
Labels: auto-merge, Bug Fix, ImportC

#13579 fix Issue 22703 - importC: C++11 unscoped enums with underlying type …
  src/dmd/cparse.d
  test/compilable/enumbase.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13580 fix Issue 22699 - importC: assignment cannot be used as a condition
  src/dmd/expressionsem.d
  src/dmd/statementsem.d
  test/compilable/test22699.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13581 Add TemplateInstance::isDiscardable() to C++ interface
  src/dmd/template.h
Labels: Trivial, auto-merge

#13583 Refactor needsCodegen()
  src/dmd/dtemplate.d
Labels: auto-merge

#13584 [Refactor] Make foreachUda and isCoreUda public
  src/dmd/attrib.d
  src/dmd/objc.d
Labels: auto-merge

#13585 win32.mak: Remove ENABLE_UNITTEST=1 from debdmd target
  src/win32.mak
Labels: auto-merge, Build System

#13586 fix Issue 22698 - ImportC: nested struct tag stored in wrong scope
  src/dmd/cparse.d
  test/compilable/test22698.c
Labels: auto-merge, Bug Fix, ImportC

#13587 fix Issue 22713 - ImportC: op= not correctly implemented for bit fields
  src/dmd/e2ir.d
  test/runnable/bitfields.c
Labels: auto-merge, Bug Fix, ImportC

#13578 -allinst: Append *all* TemplateInstances to a root module for potential codegen
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  test/runnable/imports/a15079.d
Labels: auto-merge

#13588 fix Issue 22714 - ICE: Assertion failure in ClassDeclaration::isBaseOf
  src/dmd/mtype.d
  test/compilable/imports/test22714a.d
  test/compilable/imports/test22714b.d
  test/compilable/test22714.d
  test/fail_compilation/ice10727a.d
  test/fail_compilation/ice10727b.d
Labels: Regression, auto-merge, Bug Fix, Easy Review

#13591 fix Issue 22710 - CTFE on bitfields does not account for field width
  src/dmd/dinterpret.d
  test/runnable/bitfields.c
Labels: Bug Fix, Easy Review, ImportC
