Repository dlang/dmd, pull requests merged in 2022-12, with the labels that each got.

#14660 Fix Issue 23529 - Segfault on static array cast with non-const expres…
  compiler/src/dmd/dcast.d
  compiler/test/compilable/test23529.d
Labels: Enhancement, Bug Fix

#14663 fix Issue 23532 - Missing type properties for complex special enum types
  compiler/src/dmd/typesem.d
  compiler/test/compilable/test23532.d
  druntime/src/core/stdc/config.d
Labels: Bug Fix

#14666 Fix Issue 23534 - __traits(isZeroInit) is true for enums with explicit values
  compiler/src/dmd/traits.d
  compiler/test/compilable/test23534.d
Labels: Blocking Other Work, auto-merge, Easy Review

#14667 Fix Issue 23533 - Segmentation fault accessing enum.max with -preview=nosharedaccess
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/test23533.d
Labels: auto-merge, Bug Fix, Easy Review

#14670 fix Issue 23536 - crt_constructors and crt_destructors should not be …
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/test23536.d
Labels: auto-merge, Bug Fix, Easy Review

#14662 Fix 23531 - scope variable can be assigned as AA key
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/fail22366.d
  druntime/src/core/demangle.d
Labels: Bug Fix, dip1000

#14661 fix Issue 23490 - [REG 2.101] Class vtable being overwritten by class semantic ran out of order
  compiler/src/dmd/dclass.d
  compiler/src/dmd/dsymbolsem.d
  compiler/test/compilable/imports/test23490frop.d
  compiler/test/compilable/imports/test23490pop.d
  compiler/test/compilable/imports/test23490zoo.d
  compiler/test/compilable/test23490.d
Labels: Regression, Bug Fix

#14673 fix Issue 23539 - [REG master] Scope C++ definition out of sync with D
  compiler/src/dmd/dscope.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/scope.h
Labels: Regression, GDC, LDC, auto-merge, Bug Fix, extern (C/C++)

#14672 Fix Issue 9848 - Better diagnostic when basic type was not expected
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/fail54.d
Labels: Enhancement, Bug Fix

#14658 Fix Issue 23516 - Anonymous enum without base type causes segfault inferring member value
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/fail109.d
Labels: Enhancement, Bug Fix

#14674 Merge all importC code in a single if block in DotIdExp semantic
  compiler/src/dmd/expressionsem.d
Labels: auto-merge, Easy Review, Refactoring

#14675 Remove toHash attribute soup related warnings.
  compiler/src/dmd/todt.d
Labels: auto-merge

#14681 deprecate Object.factory
  compiler/test/runnable/test34.d
  compiler/test/runnable/xtest46.d
  compiler/test/runnable/xtest46_gc.d
  druntime/src/object.d
Labels: auto-merge

#14683 __acrtused_con emitted twice in OMF object file
  compiler/src/dmd/glue.d
Labels: auto-merge, Easy Review, Refactoring

#14685 add loadCoreAtomic() and loadStdMath()
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
Labels: auto-merge, Easy Review, Refactoring

#14678 core.time: use crt_constructor instead of static this
  compiler/src/dmd/declaration.d
  druntime/src/core/time.d
Labels: Easy Review

#14687 fix Issue 23548 - [REG 2.098] C sources files have precedent over D modules in imports
  compiler/src/dmd/file_manager.d
  compiler/test/compilable/extra-files/issue23548/imports/imp23548.d
  compiler/test/compilable/imports/imp23548.c
  compiler/test/compilable/test23548.d
Labels: Regression, auto-merge, Bug Fix

#14691 add constraint in template constructor
  compiler/src/dmd/astbase.d
Labels: auto-merge

#14684 Fix Issue 23481 - [inf loop] usertype enums opOpAssign cause an compile time infinite loop
  compiler/src/dmd/aliasthis.d
  compiler/test/compilable/test23481.d
Labels: Needs Work, Bug Fix

#14697 Use -fmain rather than -main when compiling dmd-unittest executable w…
  compiler/src/build.d
Labels: auto-merge

#14698 Fix Issue 23549, 22587 - Lower certain noreturn expressions to a comm…
  compiler/src/dmd/dcast.d
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/noreturn1.d
Labels: Bug Fix

#14700 fix Issue 23548 - [REG 2.098] C sources files have precedent over D modules in imports
  compiler/src/dmd/file_manager.d
  compiler/test/compilable/extra-files/issue23548/imports/imp23548.d
  compiler/test/compilable/imports/imp23548.c
  compiler/test/compilable/test23548.d
Labels: Regression, Bug Fix

#14701 merge stable
  VERSION
  compiler/src/dmd/aliasthis.d
  compiler/src/dmd/dcast.d
  compiler/src/dmd/dclass.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/escape.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/typesem.d
  compiler/test/compilable/imports/test23490frop.d
  compiler/test/compilable/imports/test23490pop.d
  compiler/test/compilable/imports/test23490zoo.d
  compiler/test/compilable/noreturn1.d
  compiler/test/compilable/test23481.d
  compiler/test/compilable/test23490.d
  compiler/test/compilable/test23497.d
  compiler/test/compilable/test23529.d
  compiler/test/compilable/test23532.d
  compiler/test/compilable/test23533.d
  compiler/test/fail_compilation/fail109.d
  druntime/src/core/stdc/config.d
  druntime/src/core/sys/posix/sys/wait.d
Labels: Enhancement, auto-merge, Bug Fix, stable -> master

#14703 fix Issue 23562 - [REG master] Segmentation fault in core.demangle
  druntime/src/core/demangle.d
Labels: auto-merge, Bug Fix

#14704 Fix Issue 23552 - Function x does not override any function, but it actually does
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/test12228.d
  compiler/test/fail_compilation/test21008.d
  compiler/test/fail_compilation/test23552.d
Labels: Enhancement, auto-merge

#14705 refactor traitNotFound
  compiler/src/dmd/traits.d
Labels: auto-merge, Easy Review, Refactoring

#14709 fix Issue 23564 - [REG 2.099.0] SIGSEGV during compilation
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/ice23564.d
Labels: Regression, Bug Fix

#14714 [Bug fix] Use the location and type of the original index offset
  compiler/src/dmd/optimize.d
Labels: Regression, GDC, LDC, Bug Fix

#14715 fix Issue 23568: Set the result type of vector comparisons to an integer vector type
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/mtype.d
  compiler/test/runnable/testxmm2.d
Labels: auto-merge, Bug Fix

#14718 fix Issue 23569 - [REG 2.081][ICE] Segmentation fault in in AggregateDeclaration::getType() (this=0x0) at src/dmd/aggregate.d:594
  compiler/src/dmd/opover.d
  compiler/test/fail_compilation/ice23569.d
Labels: Regression, auto-merge, Bug Fix

#14712 fix Issue 23566 - ImportC: __PRETTY_FUNCTION__ is not defined
  compiler/test/compilable/testcstuff1.c
  druntime/src/importc.h
Labels: Enhancement, Easy Review, ImportC

#14719 fix Issue 23391 - [Reg 2.098.1] Segmentation fault with static foreach + range + inout
  compiler/src/dmd/constfold.d
  compiler/test/compilable/issue23391.d
Labels: Regression, Bug Fix

#14611 Allow multiple message arguments for static assert
  changelog/dmd.static-assert.dd
  compiler/src/dmd/astbase.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/semantic2.d
  compiler/src/dmd/staticassert.d
  compiler/src/dmd/staticassert.h
  compiler/src/dmd/transitivevisitor.d
  compiler/test/fail_compilation/staticassertargs.d
  compiler/test/fail_compilation/staticassertargsfail.d
Labels: Enhancement, auto-merge-squash, New Language Feature, Walter Bright

#14717 fix Issue 23567 - pragma(printf) messes up with the vtable of extern(C++) classes
  compiler/src/dmd/dsymbolsem.d
  compiler/test/compilable/issue23567.d
Labels: Regression, Bug Fix

#14725 Fix Issue 23572 - OpenBSD: Add OpenBSD to the RTLD_DEFAULT list
  druntime/src/core/demangle.d
Labels: auto-merge, Bug Fix

#14724 fix Issue 22854 - [REG 2.099-rc.1] static foreach byCodepoint segfault
  compiler/src/dmd/cond.d
  compiler/test/compilable/issue22854.d
  compiler/test/runnable/issue22854.d
Labels: Regression, Bug Fix

#14723 dmd.dinterpret: Remove unused extern(C++) linkage from many functions
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/frontend.h
Labels: auto-merge, Easy Review, Refactoring

#14728 fix issue 23122 - enum member UDAs semantics are not checked properly
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/failattr.d
Labels: auto-merge, Bug Fix

#14730 fix Issue 23499 - inliner crashes/asserts when building for 32-bit
  compiler/src/dmd/backend/inliner.d
  compiler/test/compilable/extra-files/build23499.d
  compiler/test/compilable/imports/file23499.d
  compiler/test/compilable/test23499.d
Labels: Enhancement, Bug Fix

#14733 fix Issue 23307 - [REG][CODEGEN][SIMD] wrong codegen with inlined loc…
  compiler/test/runnable/test23307.d
Labels: Bug Fix

#14732 fix Issue 22638 - [REG 2.096][ICE] cod4.d: Assertion cast(int)sz > 0 …
  compiler/src/dmd/s2ir.d
  compiler/test/compilable/test22638.d
Labels: Enhancement, auto-merge, Bug Fix

#14736 fix Issue 23574 - ICE: AssertError@src/dmd/optimize.d(866): Assertion failure
  compiler/src/dmd/optimize.d
  compiler/test/fail_compilation/fail23574.d
Labels: Bug Fix

#14734 Follow-up on #14733
  compiler/test/runnable/test23307.d
Labels: auto-merge, Easy Review

#14738 Fix Issue 23578 - Pattern match alias template parameters in is expre…
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/isexpalias.d
Labels: auto-merge, Bug Fix

#14737 extricate location.d into its own file
  compiler/src/build.d
  compiler/src/dmd/README.md
  compiler/src/dmd/globals.d
  compiler/src/dmd/location.d
  compiler/test/unit/frontend.d
  compiler/test/unit/interfaces/check_implementations_20861.d
  compiler/test/unit/lexer/diagnostic_reporter.d
  compiler/test/unit/lexer/lexer_dmdlib.d
  compiler/test/unit/objc/protocols/diagnostic_messages.d
  compiler/test/unit/objc/protocols/optional_methods.d
  compiler/test/unit/parser/aliasdeclaration_location.d
  compiler/test/unit/parser/conditionalcompilation_location.d
  compiler/test/unit/parser/diagnostic_reporter.d
  compiler/test/unit/parser/dvcondition_location.d
  compiler/test/unit/parser/linkage_location.d
  compiler/test/unit/parser/visibilitydeclaration_location.d
  compiler/test/unit/support.d
  dub.sdl
Labels: auto-merge, Easy Review, Refactoring

#14710 Avoid GC for allocating traceinfo
  changelog/druntime.nogc-traceinfo.dd
  compiler/src/dmd/dinterpret.d
  druntime/src/core/exception.d
  druntime/src/core/runtime.d
  druntime/src/core/sys/windows/dbghelp.d
  druntime/src/core/sys/windows/stacktrace.d
  druntime/src/object.d
  druntime/src/rt/deh.d
  druntime/src/rt/dmain2.d
Labels: Enhancement, auto-merge, Bug Fix

#14741 gitignore: Only match dmd in top-level directory
  .gitignore
Labels: Trivial, auto-merge, Easy Review

#14743 dmd.dmodule: Use ThreeState for Module.selfimports and rootimports fields
  compiler/src/dmd/aggregate.h
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dsymbol.h
  compiler/src/dmd/frontend.h
  compiler/src/dmd/module.h
Labels: Easy Review, Refactoring

#14742 dmd.dmodule: Pack the Module.insearch field into Module class
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/module.h
Labels: Easy Review, Refactoring

#14747 fix Issue 23586 - DMD forgets a variable was just declared
  compiler/src/dmd/parse.d
  compiler/src/dmd/statement.d
  compiler/test/compilable/test23586.d
Labels: auto-merge, Bug Fix

#14752 unhack gc crt_constructor hack
  druntime/src/core/internal/gc/impl/conservative/gc.d
  druntime/src/core/internal/gc/impl/manual/gc.d
Labels: auto-merge, Easy Review, Refactoring

#14751 make lexer.d more idependent
  compiler/src/dmd/doc.d
  compiler/src/dmd/errors.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/identifier.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/tokens.d
  compiler/src/dmd/utils.d
Labels: auto-merge, Easy Review, Refactoring

#14754 Fix FreeBSD failing test suite in master
  druntime/test/gc/sentinel2.d
Labels: Regression, auto-merge, Continuous Integration

#14756 test: Fix cdvecfill output to match binutils 2.39
  compiler/test/runnable/cdvecfill.sh
  compiler/test/runnable/extra-files/cdvecfill.out
  compiler/test/runnable/extra-files/cdvecfillavx.out
  compiler/test/runnable/extra-files/cdvecfillavx2.out
Labels: Trivial, auto-merge, Continuous Integration

#14755 [refactor] Give semanticX and semanticY functions distinct names
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/typesem.d
Labels: auto-merge, Easy Review, Refactoring

#14757 lexer: add final to range interface
  compiler/src/dmd/lexer.d
Labels: Easy Review, Refactoring

#14759 Fix typo in docs for `getsectiondata`
  druntime/src/core/sys/darwin/mach/getsect.d
Labels: auto-merge

#14750 fix Issue 23589 - [REG2.095] Purity check special case gives circular reference error
  compiler/src/dmd/expression.d
  compiler/test/compilable/test23589.d
Labels: Regression, Bug Fix

#14761 partial 19946 array fill solution
  compiler/src/dmd/e2ir.d
Labels: Easy Review, Refactoring

#14763 core.thread.osthread: Don't subtract suspend counter if thread has detached itself
  druntime/src/core/thread/osthread.d
  druntime/test/gc/sentinel2.d
Labels: auto-merge, Bug Fix, Continuous Integration

#14740 partial Issue 16098 - align(N) not respected for stack variables if N…
  compiler/src/dmd/toir.d
  compiler/test/runnable/test16098.d
Labels: Blocking Other Work
