Repository dlang/dmd, pull requests merged in 2022-05, with the labels that each got.

#14045 [stable] Move fix for issue 22974 from glue layer to frontend
  src/dmd/dmangle.d
  src/dmd/tocsym.d
Labels: auto-merge, Bug Fix

#14051 Compile `tocvdebug.d` for all platforms
  src/dmd/tocvdebug.d
Labels: auto-merge

#14052 Move scope parameter inference to escape.d
  src/dmd/escape.d
  src/dmd/semantic3.d
Labels: auto-merge, Refactoring, dip1000

#14053 fix Issue 23056 - importC: dmd asserts for missing return statement in CTFE function
  src/dmd/dinterpret.d
  test/fail_compilation/test23056.c
Labels: auto-merge, Bug Fix

#14055 [stable] Add 3 FuncDeclaration flag setters required by LDC
  src/dmd/declaration.h
  src/dmd/frontend.h
  src/dmd/func.d
Labels: auto-merge

#14054 fix Issue 23045 - importC: casted function type is missing extern(C)
  src/dmd/semantic3.d
  test/runnable/test23045.c
Labels: auto-merge, Bug Fix

#14057 d_do_test: Respect CppRuntime_Clang targets by linking libc++, not libstdc++
  test/tools/d_do_test.d
Labels: auto-merge

#13955 ImportC: run cpp on Posix .c files
  src/build.d
  src/dmd/README.md
  src/dmd/cpreprocess.d
  src/dmd/dmodule.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/link.d
  src/dmd/mars.d
  test/compilable/testcstuff1.c
  test/compilable/testcstuff3.i
  test/fail_compilation/failcstuff1.c
  test/fail_compilation/failcstuff4.i
  test/fail_compilation/test22899.c
  test/runnable/test22428.c
Labels: Easy Review, 72h no objection -> merge, ImportC

#14049 fix Issue 23057 - importC: dmd segfault on invalid syntax
  src/dmd/cparse.d
  test/fail_compilation/fail22853a.c
  test/fail_compilation/test23057.c
Labels: Enhancement, Bug Fix, Easy Review, ImportC

#14060 test/compilable/test17434a.d: Add missing EXTRA_FILES directive
  test/compilable/test17434a.d
Labels: GDC, Trivial, auto-merge, Easy Review

#13867 Fix issue 22911: dtoh: make include directives sorted for generated headers
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_21217.d
  test/compilable/dtoh_AliasDeclaration.d
  test/compilable/dtoh_AliasDeclaration_98.d
  test/compilable/dtoh_AnonDeclaration.d
  test/compilable/dtoh_CPPNamespaceDeclaration.d
  test/compilable/dtoh_ClassDeclaration.d
  test/compilable/dtoh_StructDeclaration.d
  test/compilable/dtoh_TemplateDeclaration.d
  test/compilable/dtoh_UnionDeclaration.d
  test/compilable/dtoh_VarDeclaration.d
  test/compilable/dtoh_cpp98_compat.d
  test/compilable/dtoh_enum.d
  test/compilable/dtoh_enum_cpp98.d
  test/compilable/dtoh_expressions.d
  test/compilable/dtoh_extern_type.d
  test/compilable/dtoh_forwarding.d
  test/compilable/dtoh_functions.d
  test/compilable/dtoh_ignored.d
  test/compilable/dtoh_invalid_identifiers.d
  test/compilable/dtoh_mangling.d
  test/compilable/dtoh_names.d
  test/compilable/dtoh_protection.d
  test/compilable/dtoh_required_symbols.d
  test/compilable/dtoh_special_enum.d
  test/compilable/dtoh_unittest_block.d
  test/compilable/dtoh_verbose.d
Labels: Enhancement, Trivial, Easy Review, dtoh

#13957 Issue 17374 - Begin improving inferred attribute error message for safety
  src/dmd/declaration.h
  src/dmd/expression.d
  src/dmd/frontend.h
  src/dmd/func.d
  src/dmd/statementsem.d
  test/fail_compilation/attributediagnostic.d
  test/fail_compilation/dtor_attributes.d
  test/fail_compilation/dtorfields_attributes.d
Labels: Diagnostic Messages

#13822 iasmdmd: replace init_optab() with internal checks
  src/dmd/backend/iasm.d
  src/dmd/backend/ptrntab.d
  src/dmd/iasmdmd.d
Labels: Refactoring

#14050 remove the markdown related switches
  changelog/markdown.dd
  src/dmd/cli.d
  src/dmd/doc.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/mars.d
  test/compilable/ddoc_markdown_breaks_verbose.d
  test/compilable/ddoc_markdown_code_verbose.d
  test/compilable/ddoc_markdown_emphasis_verbose.d
  test/compilable/ddoc_markdown_headings_verbose.d
  test/compilable/ddoc_markdown_links_verbose.d
  test/compilable/ddoc_markdown_lists_verbose.d
  test/compilable/ddoc_markdown_quote_verbose.d
  test/compilable/ddoc_markdown_tables_verbose.d
  test/compilable/dmdcliflags.sh
  test/compilable/reverthelp.d
  test/compilable/transitionhelp.d
Labels: auto-merge

#14072 fix Issue 23087 - getLinkage trait regression for overloads with v2.100.0-rc.1
  src/dmd/traits.d
  test/compilable/test23087.d
Labels: Bug Fix, Easy Review, Industry

#14068 Fix Issue 23083 - .tupleof on static array rvalue evaluates expressio…
  src/dmd/typesem.d
  test/runnable/test23083.d
Labels: Bug Fix

#14076 [stable] cirrus.yml: Use an alternative mirror for FreeBSD 11
  .cirrus.yml
Labels: auto-merge, Easy Review, Continuous Integration

#14080 cirrus.yml: Use an alternative mirror for FreeBSD 11
  .cirrus.yml
Labels: Easy Review, Continuous Integration

#14079 fail_compilation/test23037.c: Adjust test so it fails consistently on all platforms
  test/fail_compilation/test23037.c
Labels: auto-merge, Bug Fix, Continuous Integration

#14046 fix Issue 23066 - importC: cannot initialize char array with string l…
  src/dmd/expressionsem.d
  src/dmd/initsem.d
  test/compilable/test23066.c
  test/fail_compilation/fail12604.d
  test/fail_compilation/fail3703.d
  test/fail_compilation/test9150.d
Labels: Enhancement, Bug Fix, ImportC, stable-stalled

#14047 fix Issue 23075 - global const string definitions should go in readon…
  src/dmd/toctype.d
  src/dmd/toobj.d
Labels: Enhancement, auto-merge, Bug Fix

#14078 Fix issue 23042 - -betterC still includes RTInfo
  src/dmd/semantic3.d
Labels: auto-merge, Bug Fix

#14065 Put error messages inside setUnsafe()
  src/dmd/dcast.d
  src/dmd/dsymbolsem.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/initsem.d
  src/dmd/safe.d
  src/dmd/statementsem.d
  test/fail_compilation/test14496.d
  test/fail_compilation/test21665.d
Labels: auto-merge, Diagnostic Messages

#14082 Don't require extern(C) for CRT con/destructors
  changelog/crt_constructor_signature.dd
  src/dmd/dsymbolsem.d
  test/fail_compilation/test17868b.d
  test/runnable/extra-files/lib18456.d
  test/runnable/test17868b.d
Labels: auto-merge

#14066 Put error messages inside setUnsafe() (escape.d)
  src/dmd/escape.d
Labels: auto-merge, Diagnostic Messages

#14059 ImportC: add Win64 preprocessor support
  src/dmd/cpreprocess.d
  src/dmd/link.d
  src/dmd/mars.d
  test/compilable/ctests1.c
  test/compilable/test22294.i
Labels: ImportC

#14083 [stable] Extend LTO build with LDC to druntime modules too
  src/build.d
Labels: auto-merge

#14077 Revise newly unresolved Declaration.linkage
  src/dmd/clone.d
  src/dmd/dclass.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dmangle.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/dtoh.d
  src/dmd/e2ir.d
  src/dmd/frontend.h
  src/dmd/func.d
  src/dmd/glue.d
  src/dmd/inline.d
  src/dmd/inlinecost.d
  src/dmd/json.d
  src/dmd/objc.d
  src/dmd/semantic2.d
  src/dmd/semantic3.d
  src/dmd/tocsym.d
  src/dmd/toobj.d
  src/dmd/traits.d
Labels: auto-merge

#14084 [stable] Don't rebuild build.d for PGO builds
  src/build.d
Labels: auto-merge

#14086 Put error messages in setUnsafe() 2
  src/dmd/expression.d
  src/dmd/expressionsem.d
  test/fail_compilation/safe_gshared.d
  test/fail_compilation/safe_pointer_index.d
Labels: auto-merge, Diagnostic Messages

#14085 Revert dip1000 deprecations for 2.100
  changelog/dip1000_deprecation_warnings.dd
  src/dmd/escape.d
  test/fail_compilation/fail_scope.d
Labels: auto-merge, dip1000

#14087 Put error messages in setUnsafeDip1000()
  src/dmd/escape.d
  test/fail_compilation/fail19881.d
  test/fail_compilation/retscope.d
  test/fail_compilation/retscope2.d
  test/fail_compilation/retscope6.d
  test/fail_compilation/test17423.d
  test/fail_compilation/test20245.d
Labels: Diagnostic Messages

#14088 Use setUnsafeDIP1000 in escape.d more consistently
  src/dmd/escape.d
  test/fail_compilation/retscope2.d
  test/fail_compilation/test13536.d
  test/fail_compilation/test16365.d
  test/fail_compilation/test22145.d
Labels: auto-merge, dip1000

#14092 C preprocessor: cl.exe needs to be run from the path appropriate for …
  src/dmd/cpreprocess.d
  src/dmd/link.d
  src/dmd/vsoptions.d
Labels: auto-merge

#14096 [stable] cirrus.yml: Bump FreeBSD images to version 12.3 and 13.0
  .cirrus.yml
Labels: auto-merge, Easy Review, Continuous Integration

#14093 Handle `out` parameters in dtoh
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_functions.d
Labels: auto-merge

#14067 Do parameterStorageClass also without dip1000 switch
  src/dmd/expressionsem.d
  src/dmd/mtype.d
Labels: auto-merge, dip1000

#14098 Fix dip1000 deprecations inside dmd
  src/dmd/backend/cc.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/cgxmm.d
  src/dmd/backend/cod3.d
  src/dmd/backend/code_x86.d
  src/dmd/backend/dtype.d
  src/dmd/backend/symbol.d
  src/dmd/common/bitfields.d
Labels: auto-merge, Refactoring, dip1000

#14097 Fix issue 23098 - array literal to scope inout parameter not allowed …
  src/dmd/expressionsem.d
  test/runnable/test20734.d
Labels: Bug Fix

#14075 Fix Issue 21416 - betterC mode program with C++ interface fails to link
  src/dmd/tocsym.d
  src/dmd/todt.d
  src/dmd/toobj.d
  test/runnable/test21416.d
Labels: Bug Fix

#14101 fix Issue 23097 - [REG 2.100] ArrayIndexError@src/dmd/mtype.d(4767): index [$-1] is out of bounds for array of length 0
  src/dmd/mtype.d
  test/compilable/test23097.d
  test/fail_compilation/ice23097.d
Labels: Regression, auto-merge, Bug Fix, stable-priority, Industry

#14103 errors: Remove capitilzation of all front-end language diagnostics
  src/dmd/declaration.d
  src/dmd/dsymbol.d
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  src/dmd/mars.d
  src/dmd/parse.d
  src/dmd/scanmscoff.d
  src/dmd/semantic3.d
  src/dmd/statementsem.d
  src/dmd/traits.d
  src/dmd/utils.d
  test/compilable/dmdcliflags.sh
  test/fail_compilation/b6227.d
  test/fail_compilation/betterc.d
  test/fail_compilation/commaexp.d
  test/fail_compilation/diag10805.d
  test/fail_compilation/diag10862.d
  test/fail_compilation/fail109.d
  test/fail_compilation/fail13902.d
  test/fail_compilation/fail16001.d
  test/fail_compilation/fail196.d
  test/fail_compilation/fail21092.d
  test/fail_compilation/fail21275.d
  test/fail_compilation/ice10949.d
  test/fail_compilation/ice14844.d
  test/fail_compilation/ice9254a.d
  test/fail_compilation/ice9254b.d
  test/fail_compilation/ice9254c.d
  test/fail_compilation/issue3827.d
  test/fail_compilation/no_Throwable.d
  test/fail_compilation/test15373.d
  test/fail_compilation/test18130.d
  test/fail_compilation/test21198.d
  test/fail_compilation/test21204.d
  test/fail_compilation/test22593.d
  test/fail_compilation/traits.d
  test/fail_compilation/udaparams.d
  test/fail_compilation/write_error.d
  test/runnable/testcontracts.d
Labels: Diagnostic Messages

#14107 Limit 'address of `ref`' errors to safe code
  src/dmd/escape.d
  test/fail_compilation/dip25.d
  test/fail_compilation/fail21868b.d
  test/fail_compilation/test18484.d
Labels: dip1000

#14062 Fix issue 23079 - be more lenient when taking address of `ref` return
  src/dmd/escape.d
  src/dmd/expressionsem.d
  test/fail_compilation/fail20691.d
  test/fail_compilation/retscope.d
  test/fail_compilation/test15191.d
  test/fail_compilation/test20245.d
  test/fail_compilation/test20569.d
Labels: Enhancement, dip1000

#14108 Delete Jenkinsfile
  Jenkinsfile
Labels: auto-merge

#14106 Give checkNewEscape errors in safe code only
  src/dmd/escape.d
  test/fail_compilation/test18282.d
  test/fail_compilation/test20245.d
Labels: auto-merge, dip1000

#14109 Move dip1000 checkAddrVar functionality to escape.d
  src/dmd/dcast.d
  src/dmd/escape.d
  src/dmd/expressionsem.d
Labels: auto-merge, dip1000

#14089 Call checkXXXescape functions without -dip1000
  src/dmd/escape.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  test/compilable/test17590.d
Labels: dip1000

#14094 reboot fix Issue 23058 - importC: cannot take address inside multi-di…
  src/dmd/optimize.d
  test/fail_compilation/fail13902.d
  test/fail_compilation/test23058.c
  test/runnable/test23058.c
Labels: ImportC

#14112 Fix wrong return ref annotation in backend
  src/dmd/backend/dlist.d
Labels: auto-merge, dip1000

#14113 rename writeString to writeStringz
  src/dmd/backend/dwarfdbginf.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/machobj.d
  src/dmd/backend/mscoffobj.d
  src/dmd/common/outbuffer.d
  src/dmd/link.d
Labels: Easy Review, Refactoring

#14115 chore(docs): fix link in changelog
  changelog/mustUse.dd
Labels: auto-merge

#14119 Fix Issue 23105 - `__trait(getMember)` and `mixin()` of the same code as a string behave differently
  src/dmd/dscope.d
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/typesem.d
  test/compilable/test23105.d
  test/fail_compilation/e7804_1.d
Labels: auto-merge, Bug Fix

#14104 dmd: Remove capitilization of internal compiler error diagnostics
  src/dmd/constfold.d
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/dinterpret.d
  src/dmd/e2ir.d
  src/dmd/expressionsem.d
  src/dmd/statementsem.d
  test/fail_compilation/ice22377.d
Labels: Diagnostic Messages

#14100 Infer return scope from pure without -dip1000
  src/dmd/mtype.d
Labels: dip1000

#14063 Add __traits(classInstanceAlignment)
  changelog/class_instance_alignment.dd
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/traits.d
  test/compilable/aggr_alignment.d
Labels: New Language Feature, Walter Bright

#14111 Remove useDIP1000 branch for checkArrayLiteralEscape
  src/dmd/dcast.d
Labels: auto-merge, dip1000

#14122 fixup #14083 - missing druntime 32 bit lto
  src/build.d
Labels: Enhancement, auto-merge, Bug Fix

#14124 fix Issue 23108 - ICE: AssertError@src/dmd/clone.d(567): Assertion failure
  src/dmd/clone.d
  test/fail_compilation/fail23108a.d
  test/fail_compilation/fail23108b.d
Labels: Bug Fix, Easy Review, stable-priority

#14118 fix Issue 23054 - importC: struct compound-literal assigned by pointe…
  src/dmd/e2ir.d
  src/dmd/expressionsem.d
  test/compilable/test23054.c
Labels: auto-merge, Bug Fix, ImportC

#14127 dmd.backend: Define top-level function literals as extern(D)
  src/dmd/backend/cg.d
  src/dmd/backend/var.d
Labels: auto-merge, Bug Fix

#14123 fix Issue 23109 - ICE: AssertError@src/dmd/dclass.d(449): Assertion failure
  src/dmd/expressionsem.d
  test/fail_compilation/extra-files/test23109/object.d
  test/fail_compilation/fail23109.d
  test/fail_compilation/imports/test23109a.d
  test/fail_compilation/imports/test23109b.d
  test/fail_compilation/imports/test23109c.d
Labels: Regression, Bug Fix, stable-priority

#14121 ImportC: automatically #include importc.h
  src/dmd/cpreprocess.d
  src/dmd/dmodule.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/link.d
  test/fail_compilation/fail22853a.i
Labels: ImportC

#14126 add -P=preprocessorflag switch
  src/dmd/cli.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/mars.d
Labels: Easy Review, ImportC

#14128 pass preprocessor flags to preprocessor
  src/dmd/cpreprocess.d
  src/dmd/dmodule.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/link.d
  test/compilable/cppflags.c
Labels: auto-merge, Easy Review, ImportC

#14105 Fix issue 23100 - empty array literal passed to scope param not 'fals…
  src/dmd/expressionsem.d
  test/runnable/test20734.d
Labels: Bug Fix, stable-stalled

#14125 fix Issue 16575 - [ICE] extern(C++) function with D specific types
  src/dmd/dsymbolsem.d
  src/dmd/semantic3.d
  src/dmd/typesem.d
  test/compilable/cppmangle.d
  test/compilable/test20427.d
  test/fail_compilation/cppvar.d
  test/fail_compilation/fail16575.d
  test/fail_compilation/fail16772.d
  test/fail_compilation/fail19759.d
  test/fail_compilation/fail21206.d
  test/fail_compilation/fail21314.d
  test/fail_compilation/ice22377.d
Labels: auto-merge, Bug Fix

#14117 Remove special scope delegate treatment
  src/dmd/mtype.d
  test/fail_compilation/retscope.d
Labels: auto-merge, dip1000

#14110 Add documentation for CI pipelines
  ci/README.md
Labels: auto-merge, documentation

#14102 Update changelog for dip1000 deprecations
  changelog/dip1000_deprecation_warnings.dd
Labels: dip1000

#14131 chore(statementsem): use opApply instead of manual access
  src/dmd/statementsem.d
Labels: Trivial, auto-merge, Easy Review, Refactoring

#14133 dmd.expressionsem: Remove double-space from error message
  src/dmd/expressionsem.d
  test/fail_compilation/fail21227_win.d
Labels: auto-merge, Easy Review, Diagnostic Messages

#12817 fix Issue 22108 - parameter mistakenly interpreted as return scope instead of scope
  src/dmd/escape.d
  test/fail_compilation/fix22108.d
  test/fail_compilation/test20881.d
Labels: Bug Fix, dip1000

#14099 Fix Issue 23018 - sizeof unary-expression was not parsed correctly
  src/dmd/cparse.d
  test/compilable/testcstuff2.c
  test/fail_compilation/failcstuff1.c
Labels: Bug Fix

#14135 dmd.cpreprocess: Move searching of importc.h header to the preprocess handler itself
  src/dmd/cpreprocess.d
  src/dmd/dmodule.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
Labels: GDC, auto-merge, Easy Review, Refactoring

#14138 lexer.d: remove strange calls to .error()
  src/dmd/lexer.d
Labels: auto-merge, Easy Review, Refactoring

#14139 Fix issue 23102 - pinholeopt, "Conditional jump or move depends on un…
  src/dmd/backend/cod2.d
Labels: auto-merge, Bug Fix, Backend

#14136 Fix Issue 23123 - -vasm ignored REX prefix for cmpxchg
  src/dmd/backend/disasm86.d
Labels: auto-merge, Bug Fix

#14140 merge duplicate code in preprocess()
  src/dmd/cpreprocess.d
Labels: auto-merge, Easy Review, Refactoring

#14116 Don't assume return-ref annotation is correct without dip1000
  src/dmd/escape.d
  test/fail_compilation/dip1000_deprecation.d
  test/fail_compilation/dip25.d
  test/fail_compilation/fail_scope.d
  test/fail_compilation/test18484.d
Labels: auto-merge, dip1000

#14095 Fix Issue 23012 - Merge asm() symbol names of forward declared symbol…
  src/dmd/cparse.d
  src/dmd/dsymbol.d
  test/compilable/casmmangling.d
  test/compilable/imports/asmmerge.c
Labels: auto-merge, Bug Fix

#14145 Fix force push command in ci/README
  ci/README.md
Labels: Trivial, auto-merge, documentation

#14137 ImportC add `#define ident integer` manifest constants
  src/dmd/cparse.d
  src/dmd/dmodule.d
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/lexer.d
  test/compilable/testdefines.i
Labels: Blocking Other Work, ImportC

#14147 add -dD to cpp command
  src/dmd/link.d
  test/compilable/testdefines.c
Labels: Easy Review, ImportC

#14144 Fix issue 22865 - __traits(compiles) affects inferrence of attributes
  src/dmd/dcast.d
  src/dmd/dsymbolsem.d
  src/dmd/escape.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/func.d
  src/dmd/initsem.d
  src/dmd/mtype.d
  src/dmd/safe.d
  src/dmd/statementsem.d
  test/compilable/test22865.d
Labels: Bug Fix

#14149 Fix Issue 23082 - stringof of template alias overloaded with function accessed by trait: segfault.
  src/dmd/expressionsem.d
  test/compilable/test23082.d
Labels: auto-merge, Bug Fix

#14146 run.d: Include i files to support ImportC tests
  test/fail_compilation/fail22853a.i
  test/run.d
  test/tools/d_do_test.d
Labels: auto-merge

#14148 ImportC add Win32 OMF preprocessor #define support
  src/dmd/cpreprocess.d
  src/dmd/dmodule.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/link.d
  src/dmd/module.h
  test/compilable/testdefines.c
Labels: auto-merge, ImportC

#14153 Fix Issue 22664 - -vasm doesn't recognize rdtscp
  src/dmd/backend/disasm86.d
Labels: Bug Fix

#14154 Fix autotester whitespace failure
  src/dmd/backend/disasm86.d
Labels: Trivial, Blocking Other Work, auto-merge

#14156 chore(treewide): make dyncast() checks with a switch-case
  src/dmd/astbase.d
  src/dmd/dsymbol.d
  src/dmd/expressionsem.d
  src/dmd/hdrgen.d
  src/dmd/iasmdmd.d
  src/dmd/transitivevisitor.d
  src/dmd/typesem.d
Labels: auto-merge, Refactoring

#14155 chore(rootobject): add missing enums for DYNCAST
  src/dmd/root/object.h
Labels: auto-merge, Easy Review

#14151 ImportC add Windows cl preprocessor #define support
  src/dmd/cparse.d
  src/dmd/link.d
  test/compilable/imports/defines.c
  test/compilable/testdefines.d
Labels: ImportC

#14158 dmd.expression: Add missing CatElemAssignExp and CatDcharAssignExp definitions and visitor methods
  src/dmd/astbase.d
  src/dmd/expression.h
  src/dmd/frontend.h
  src/dmd/parsetimevisitor.d
  src/dmd/strictvisitor.d
  src/dmd/visitor.h
Labels: auto-merge, Easy Review, extern (C/C++)

#14159 dmd.statement: Add final to ScopeStatement
  src/dmd/frontend.h
  src/dmd/statement.d
Labels: auto-merge, Easy Review, Refactoring

#14160 C++: Add missing dyncast overrides
  src/dmd/cond.h
  src/dmd/init.h
  src/dmd/statement.h
  src/dmd/template.h
Labels: auto-merge, Easy Review, extern (C/C++)

#14161 C++: Add override to overriding virtual functions
  src/dmd/aggregate.h
  src/dmd/aliasthis.h
  src/dmd/attrib.h
  src/dmd/cond.h
  src/dmd/ctfe.h
  src/dmd/declaration.h
  src/dmd/dsymbol.h
  src/dmd/enum.h
  src/dmd/expression.h
  src/dmd/identifier.h
  src/dmd/import.h
  src/dmd/init.h
  src/dmd/module.h
  src/dmd/mtype.h
  src/dmd/nspace.h
  src/dmd/statement.h
  src/dmd/staticassert.h
  src/dmd/template.h
  src/dmd/version.h
  src/tests/cxxfrontend.cc
Labels: auto-merge, Refactoring, extern (C/C++)

#14163 dmd.mtype: Remove const from extern(C++) methods that override mutable virtual
  src/dmd/frontend.h
  src/dmd/mtype.d
Labels: Easy Review, extern (C/C++)

#14165 chore(treewide): make dyncast() overrides use the default attributes
  src/dmd/dtemplate.d
  src/dmd/init.d
Labels: auto-merge

#14162 dmd.dtoh: Emit 'override' keyword when generating C++11 compatible headers
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_ClassDeclaration.d
  test/compilable/dtoh_TemplateDeclaration.d
Labels: auto-merge, Easy Review, extern (C/C++), dtoh

#14167 dmd.dtoh: Emit 'final' keyword when generating C++11 compatible headers
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_ClassDeclaration.d
Labels: Easy Review, dtoh

#14168 ci/cirrusci.sh: Remove brew update-reset from cirrusci script
  ci/cirrusci.sh
Labels: Continuous Integration

#14166 fix(dsymbolsem): override methods should have semantic logic on attributes
  src/dmd/dsymbolsem.d
  test/fail_compilation/fix23138.d
Labels: auto-merge, Bug Fix

#14070 Remove -dip1000 influence on immutable conversion
  changelog/fix-immutable-conv.dd
  src/dmd/cli.d
  src/dmd/dcast.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  test/compilable/previewhelp.d
  test/fail_compilation/test15660.d
  test/unit/support.d
Labels: auto-merge, dip1000

#14169 fix Issue 22351 - extern(C++) function contravariant in D, but not C++
  src/dmd/astbase.d
  src/dmd/dtoh.d
  src/dmd/frontend.h
  src/dmd/func.d
  src/dmd/mtype.d
  src/dmd/mtype.h
  test/compilable/dtoh_ClassDeclaration.d
  test/fail_compilation/fail22351.d
  test/fail_compilation/fail23135.d
  test/runnable_cxx/extra-files/test22351.cpp
  test/runnable_cxx/extra-files/test23135.cpp
  test/runnable_cxx/test22351.d
  test/runnable_cxx/test23135.d
Labels: auto-merge, Bug Fix, dtoh, Deprecation

#14170 Fix Issue 23141 - Improve -release switch description
  src/dmd/cli.d
Labels: Enhancement, Trivial, auto-merge

#14091 Fix Issue 23088 - This bug is a symptom of a bad error message.
  src/dmd/sideeffect.d
  test/fail_compilation/fail12390.d
Labels: Bug Fix, auto-merge-squash

#14134 Fix Issue 23114 - Make noreturn conversions work
  src/dmd/dcast.d
  src/dmd/impcnvtab.d
  test/compilable/noreturn1.d
Labels: auto-merge, Bug Fix

#14150 Print deprecations for calling functions that would be `@system` with dip1000
  src/dmd/declaration.h
  src/dmd/escape.d
  src/dmd/expression.d
  src/dmd/frontend.h
  src/dmd/func.d
  test/fail_compilation/dip1000_deprecation.d
Labels: auto-merge, dip1000

#14173 chore(pre-commit): bump hook versions
  .pre-commit-config.yaml
Labels: auto-merge, Easy Review

#14174 fix Issue 23076 - SIMD assert fail with -inline -O converting float t…
  src/dmd/backend/cgxmm.d
  src/dmd/backend/cod4.d
  test/compilable/test23076.d
Labels: auto-merge, Bug Fix, Easy Review

#14176 Fix issue 23148, 21723: Generate invariant id on the basis of location rather than counter.
  src/dmd/astbase.d
  src/dmd/func.d
  test/compilable/extra-files/vcg-ast.d.cg
  test/fail_compilation/fail4421.d
  test/fail_compilation/fail7848.d
  test/fail_compilation/test20626.d
  test/runnable/extra-files/lib21723a.d
  test/runnable/extra-files/lib21723b.d
  test/runnable/extra-files/lib23148.d
  test/runnable/extra-files/test21723.d
  test/runnable/extra-files/test23148.d
  test/runnable/test21723.sh
  test/runnable/test23148.sh
Labels: auto-merge, Bug Fix

#14172 ImportC: recognize more #define manifest constants
  src/dmd/cparse.d
  test/compilable/imports/defines.c
  test/compilable/testdefines.d
Labels: Easy Review, ImportC
