Repository dlang/dmd, pull requests merged in 2022-08, with the labels that each got.

#14342 [object] Fix wrong anchor link for array dup
  druntime/src/object.d
Labels: auto-merge

#14344 Add method called from codegen to C++ interface
  compiler/src/dmd/declaration.h
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
Labels: GDC, auto-merge, Easy Review

#14310 Translate `_d_arrayassign{,_l,_r}` to templates
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/test/fail_compilation/fail10968.d
  druntime/mak/COPY
  druntime/mak/SRCS
  druntime/src/core/internal/array/arrayassign.d
  druntime/src/object.d
  druntime/src/rt/arrayassign.d
Labels: 72h no objection -> merge

#14347 Remove dprogress state variable for semantic1
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/frontend.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/mars.d
  compiler/src/dmd/module.h
  compiler/test/dub_package/retrieveScope.d
Labels: auto-merge

#14349 Broken DMD source code links
  compiler/src/README.md
  compiler/src/dmd/README.md
  compiler/src/dmd/common/README.md
  compiler/src/dmd/root/README.md
  druntime/README.md
Labels: auto-merge

#14348 [NFC] Group all `-preview=/-revert=` options in `global.params`
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.d
  compiler/src/dmd/globals.h
Labels: Trivial, auto-merge, Easy Review, Refactoring

#14353 extend () error msgs for if conditions to other statement conditions
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/ice8795.d
Labels: Easy Review

#14355 fix missing/erroneous documentation of -profile switch
  compiler/src/dmd/cli.d
Labels: auto-merge, documentation

#14357 CTFloat.parse - use out parameter
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/root/ctfloat.d
  compiler/src/dmd/root/ctfloat.h
Labels: Easy Review, Refactoring

#14359 Fix Issue 15525 - SEGV running semantic analysis on non-root decl tha…
  compiler/src/dmd/dimport.d
  compiler/test/fail_compilation/imports/import15525.d
  compiler/test/fail_compilation/test15525.d
Labels: auto-merge, Bug Fix

#14360 fix Issue 21197 - Wrong lifetime inference with DIP1000 in dmd 2.093.0
  compiler/src/dmd/escape.d
  compiler/test/compilable/test21197.d
Labels: Bug Fix

#14350 chore(ctfeexpr): use switch case instead of an if statement
  compiler/src/dmd/ctfeexpr.d
Labels: Easy Review, Refactoring

#14361 improve error messages for missing semicolons
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/testsemi.d
Labels: auto-merge, Diagnostic Messages

#14362 Issue 23226 - allow access to non-shared `this`
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/shared.d
Labels: auto-merge

#14366 Translate C style unittest to D in dwarfeh.d
  compiler/src/dmd/backend/dwarfeh.d
Labels: auto-merge, Refactoring

#14352 ImportC: disable blocks extension when preprocessing on OSX
  compiler/src/dmd/link.d
Labels: 72h no objection -> merge

#14358 fix Issue 20809 - return statement might access memory from destructe…
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/id.d
  compiler/test/fail_compilation/test20809.d
  compiler/test/runnable/test20809.d
Labels: Bug Fix

#14369 Fix wrong return annotation in core.demangle
  druntime/src/core/demangle.d
Labels: auto-merge

#14370 Add test for scope inference with `_d_arrayassign_l`
  compiler/test/compilable/scope_infer_array_assign.d
Labels: dip1000

#14368 Simplify 'maybeScope' from 2 variables to 1
  compiler/src/dmd/astenums.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/escape.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/semantic3.d
Labels: dip1000

#14365 Fix Issue 23291 - Members of arrays of shared classes cannot be compared
  druntime/src/object.d
Labels: Bug Fix

#14372 Fix Issue 20365 - Copy constructor not invoked on static arrays of structs but the postblit works
  compiler/src/dmd/expressionsem.d
  compiler/test/runnable/test20365.d
Labels: Bug Fix

#14217 Fix 23073 - scope inference from pure doesn't consider self-assignment
  compiler/src/dmd/mtype.d
  compiler/test/fail_compilation/test23073.d
Labels: Bug Fix, dip1000

#14375 Improve `@safe` annotations in outbuffer.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/common/outbuffer.d
Labels: auto-merge

#14373 Fix 23295 - explain why scope inference failed
  compiler/src/dmd/escape.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.d
  compiler/test/fail_compilation/diag23295.d
  compiler/test/fail_compilation/retscope6.d
  compiler/test/fail_compilation/test17423.d
  compiler/test/fail_compilation/test20245.d
  compiler/test/fail_compilation/test23073.d
Labels: Enhancement, auto-merge, dip1000

#14376 Improve `@safe` in doc.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/identifier.d
Labels: auto-merge, Refactoring

#14379 Add test case for issue 21094
  druntime/src/core/internal/array/equality.d
Labels: auto-merge

#14381 Fix Issue 23302 - std.algorithm.comparison.predSwitch producing SwitchError with error message as the filename
  druntime/src/core/exception.d
Labels: auto-merge, Bug Fix

#11598 Issue 12652 - Non-constant hash initializers should have a special-case diagnostic
  compiler/src/dmd/todt.d
  compiler/test/fail_compilation/issue12652.d
Labels: Enhancement, auto-merge-squash

#14385 Issue 20593 - Make parser syntax for GCC asm an error
  compiler/src/dmd/iasmgcc.d
Labels: GDC, LDC, auto-merge, Easy Review, Deprecation -> Error

#14386 Trivial: Remove some superfluous Array.setDim calls
  compiler/src/dmd/astbase.d
  compiler/src/dmd/clone.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/todt.d
Labels: auto-merge

#14388 Use more slices in transitivevisitors
  compiler/src/dmd/frontend.h
  compiler/src/dmd/transitivevisitor.d
Labels: auto-merge

#14392 Push default argument error to semantic
  compiler/src/dmd/parse.d
  compiler/src/dmd/typesem.d
  compiler/test/fail_compilation/diag3438.d
  compiler/test/fail_compilation/diag3438b.d
Labels: auto-merge

#14393 Remove cast from `Array!(Expression)*` to `Array!(RootObject)*`
  compiler/src/dmd/func.d
Labels: auto-merge

#14396 Fix Issue 23308 - void* and T* not merged properly
  compiler/src/dmd/dcast.d
  compiler/test/compilable/commontype.d
Labels: auto-merge

#14397 merge stable
  VERSION
  compiler/src/dmd/func.d
  compiler/src/dmd/mtype.d
  test/compilable/test23258.d
  test/runnable/test23234.d
Labels: auto-merge, Bug Fix

#14383 Fix Issue 13123 - Disallow throwing contracts for nothrow functions
  changelog/deprecate_throwing_nothrow_contracts.dd
  compiler/src/dmd/semantic3.d
  compiler/test/compilable/test13123.d
  compiler/test/fail_compilation/fail13123.d
  druntime/src/core/internal/utf.d
Labels: auto-merge, Bug Fix

#14142 Infer return on delegate without -dip1000
  compiler/src/dmd/escape.d
Labels: auto-merge, dip1000

#14367 fix Issue 19812 - nested class reference causes dangling reference to…
  compiler/src/dmd/escape.d
  compiler/test/compilable/test19812a.d
  compiler/test/fail_compilation/test19812b.d
  druntime/src/object.d
Labels: Bug Fix

#14354 Fix Issue 23284 - better floating point error messages.
  compiler/src/dmd/lexer.d
  compiler/test/fail_compilation/lexer5.d
Labels: Enhancement

#14399 Make `SC` a proper D enum
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cdef.d
  compiler/src/dmd/backend/cod2.d
  compiler/src/dmd/backend/elpicpie.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/out.d
  compiler/src/dmd/backend/symbol.d
  compiler/src/dmd/objc_glue.d
  compiler/src/dmd/tocsym.d
  compiler/src/dmd/toobj.d
Labels: auto-merge, Refactoring, Backend
