Repository dlang/dmd, pull requests merged in 2022-02, with the labels that each got.

#13597 change implicitCastTo() from Visitor to nested functions
  src/dmd/dcast.d
Labels: Easy Review, Refactoring

#13595 convert getIntRange() from Visitor to nested functions
  src/dmd/dcast.d
Labels: Easy Review, Refactoring

#13596 convert implicitCastTo() from Visitor to nested functions
  src/dmd/dcast.d
Labels: auto-merge, Easy Review, Refactoring

#13594 split off parseModuleAttributes() from parseModule()
  src/dmd/parse.d
Labels: auto-merge, Easy Review, Refactoring

#13598 change castTo() from Visitor to nested functions
  src/dmd/dcast.d
Labels: Easy Review, Refactoring

#13601 remove unused tokens
  src/dmd/frontend.h
  src/dmd/tokens.d
  src/dmd/tokens.h
Labels: Easy Review, Refactoring

#13600 parse.d: move private stuff to end
  src/dmd/parse.d
Labels: Easy Review, Refactoring

#13602 convert implicitConvTo() from Visitor to nested functions
  src/dmd/dcast.d
Labels: Easy Review, Refactoring

#13603 fix Issue 22625 - ImportC: original name of typedefed struct not visi…
  test/compilable/imports/imp22625.c
  test/compilable/test22625.d
Labels: auto-merge, Bug Fix

#13593 Fix Issue 22717 - TypeInfo_Struct.equals swaps lhs and rhs parameters
  .circleci/run.sh
  VERSION
  src/dmd/clone.d
  src/dmd/dtemplate.d
  test/runnable/test22717.d
Labels: auto-merge, Bug Fix

#13605 fix Issue 22607 - ImportC misses some float values ending with f
  src/dmd/lexer.d
  test/compilable/test22607.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13604 lexer.d: move private to the end, and unittests after that
  src/dmd/lexer.d
Labels: Easy Review, Refactoring

#13607 fix Issue 22725 - ImportC: segfault when compiling with -H
  src/dmd/hdrgen.d
  test/compilable/test22725.c
Labels: auto-merge, Easy Review, ImportC

#13606 Issue 22726 - ImportC: typedefs of tagged enums fail to compile
  src/dmd/cparse.d
  test/compilable/test22728.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13608 Fix issue 22733: hdrgen generates inconsistent order of STC attributes for ~this()
  src/dmd/hdrgen.d
  test/compilable/extra-files/header1.di
  test/compilable/extra-files/header1i.di
  test/compilable/extra-files/header2.di
  test/compilable/extra-files/header2i.di
Labels: Enhancement, Easy Review, Refactoring

#13556 dmd.common.int128: Synchronize with druntime core.int128
  src/dmd/common/int128.d
Labels: auto-merge, Easy Review, Refactoring

#13590 dmd.clone: Build __xopEquals and __xopCmp as hidden member functions
  src/dmd/clone.d
  src/dmd/frontend.h
  src/dmd/id.d
Labels: GDC, auto-merge, Easy Review

#13614 fix Issue 22727 ImportC: add __stdcall Windows calling convention
  src/dmd/cparse.d
  src/dmd/frontend.h
  src/dmd/tokens.d
  src/dmd/tokens.h
  test/compilable/test22727.c
  test/unit/lexer/location_offset.d
Labels: auto-merge, Bug Fix, ImportC

#13615 treewide: refactor attribution of STC to safe group
  src/dmd/astbase.d
  src/dmd/dsymbolsem.d
  src/dmd/mtype.d
Labels: Easy Review, Refactoring

#13610 fix Issue 22734 - importC: typedef anonymous enum members not availab…
  src/dmd/cparse.d
  test/compilable/imports/imp22734.c
  test/compilable/test22734.d
Labels: Bug Fix, Easy Review, ImportC

#13618 hdrgen: move trustToString function to mtype module
  src/dmd/hdrgen.d
  src/dmd/mtype.d
Labels: auto-merge, Easy Review, Refactoring

#13621 Fix issue 22746: Functions that throws marked as nothrow produces bad error
  src/dmd/semantic3.d
  test/fail_compilation/bug8150a.d
  test/fail_compilation/bug8150b.d
  test/fail_compilation/diag10319.d
  test/fail_compilation/dtor_attributes.d
  test/fail_compilation/fail10964.d
  test/fail_compilation/fail11375.d
  test/fail_compilation/fail11542.d
  test/fail_compilation/fail12809.d
  test/fail_compilation/fail14486.d
  test/fail_compilation/fail349.d
  test/fail_compilation/fail4082.d
  test/fail_compilation/fail7848.d
  test/fail_compilation/fail8724.d
  test/fail_compilation/noreturn2.d
Labels: Enhancement

#13620 Fix Issue 20777 - Extend enum base type semantic to user defined type…
  src/dmd/dsymbolsem.d
  test/compilable/enumbasearithmetic.d
Labels: auto-merge, Bug Fix

#13619 mtype: make sizeTy static immutable instead of __gshared
  src/dmd/astbase.d
  src/dmd/mtype.d
Labels: auto-merge, Easy Review, Refactoring

#13611 Adapt default `sc.ini` to MsCoff by default
  ini/windows/bin/sc.ini
  src/build.d
  test/dshell/defaults.d
  test/dshell/extra-files/defaults/hello.d
  test/tools/d_do_test.d
  test/tools/dshell_prebuilt/dshell_prebuilt.d
Labels: auto-merge

#13623 fix Issue 22401 - importC: Error: cannot implicitly convert expressio…
  test/compilable/testcstuff2.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13624 fix Issue 22749 - importC: C11 does not allow taking the address of a bit-field
  src/dmd/expressionsem.d
  test/fail_compilation/fail22749.d
  test/fail_compilation/failcstuff2.c
  test/fail_compilation/imports/imp22749.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13627 fix Issue 22344 - ImportC: overloading of functions is not allowed
  src/dmd/dsymbol.d
  src/dmd/dsymbolsem.d
  test/fail_compilation/test22344.c
Labels: auto-merge, Bug Fix, ImportC

#13630 fix: remove trailing whitespaces from 99bottles test
  test/compilable/99bottles.d
Labels: auto-merge, Easy Review, Refactoring

#13633 Fix issue 22754: Header generator shouldn't generate trailing whitespace on visibility declaration
  src/dmd/hdrgen.d
  test/compilable/header18364.d
Labels: Enhancement, auto-merge

#13634 lexer: remove whitespace on string delimiter error
  src/dmd/lexer.d
  test/fail_compilation/diag10805.d
  test/fail_compilation/fail196.d
  test/fail_compilation/fail258.d
Labels: auto-merge, Easy Review

#13632 refactor funcDeclarationSemantic()
  src/dmd/dsymbolsem.d
Labels: auto-merge, Easy Review, Refactoring

#13631 Fix issue 22753: Deprecation message for import module shouldn't produce hifen when no message
  src/dmd/dmodule.d
  test/compilable/test19609.d
Labels: Enhancement

#13635 fix Issue 22339 - importC: error message with character literal repor…
  src/dmd/cparse.d
  src/dmd/lexer.d
  src/dmd/tokens.d
  test/fail_compilation/lexer1.d
  test/fail_compilation/test22339.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13636 fix Issue 22698 - ImportC: nested struct tag stored in wrong scope
  src/dmd/typesem.d
  test/compilable/test22698.c
Labels: Bug Fix, Easy Review, ImportC

#13637 dmd.lexer: Remove overflow code for parsing ImportC integers
  src/dmd/lexer.d
  test/compilable/testcstuff1.c
Labels: auto-merge, Bug Fix, ImportC

#13612 semantic3: simplify isnothrow logic
  src/dmd/semantic3.d
Labels: Easy Review, Refactoring

#13642 Merge branch 'stable' into merge_stable
  azure-pipelines.yml
  src/dmd/backend/cod3.d
  src/dmd/dmangle.d
  src/dmd/expressionsem.d
  src/dmd/mtype.d
  src/dmd/parse.d
  src/dmd/statementsem.d
  src/dmd/vsoptions.d
  src/posix.mak
  src/win32.mak
  src/win64.mak
  test/compilable/commontype.d
  test/compilable/dlangui_crash.d
  test/fail_compilation/fail22127.d
  test/fail_compilation/fail22634.d
  test/fail_compilation/test22686.d
  test/runnable/test22136.d
  test/runnable/test22163.d
  test/runnable/testconst.d
Labels: Bug Fix

#13646 fix Issue 22758 - ImportC: parenthesized expression confused with cas…
  src/dmd/expressionsem.d
  src/dmd/printast.d
  test/compilable/test22758.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13645 Reuse build_release_template for the nightly build
  .github/workflows/nightlies.yml
Labels: auto-merge, Continuous Integration

#13640 fix Issue 22590 - importC: static functions have no debug information…
  src/dmd/backend/dwarfdbginf.d
  test/runnable/gdb22590.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13648 fix Issue 22757 - importC: typedef causes forward reference error
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  test/compilable/test22757.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13651 Fix Issue 14277 - Compile-time array casting error - ugly error report
  src/dmd/initsem.d
  test/fail_compilation/ctfe14731.d
  test/fail_compilation/diag13281.d
  test/fail_compilation/fail14277.d
  test/fail_compilation/fail15089.d
  test/fail_compilation/fail19897.d
Labels: Enhancement, auto-merge, Easy Review

#13655 expressionsem.d: remove casts
  src/dmd/expressionsem.d
Labels: auto-merge, Easy Review, Refactoring

#13656 create isUnaExp(), isBinExp(), isBinAssignExp()
  src/.dscanner.ini
  src/dmd/expression.d
  src/dmd/frontend.h
Labels: auto-merge, Refactoring

#13657 merge stable
  VERSION
Labels: auto-merge

#13659 dmd: Update deprecated comment tags to reflect which release to remove them
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  src/dmd/iasmgcc.d
  src/dmd/opover.d
  src/dmd/parse.d
  src/dmd/semantic2.d
  src/dmd/semantic3.d
  src/dmd/typesem.d
Labels: Trivial, auto-merge, Deprecation

#13664 remove Visitor from op_overload()
  src/dmd/opover.d
Labels: auto-merge, Easy Review, Refactoring

#13663 [stable] Fix 2 TODOs wrt. first 2.099 tag
  src/dmd/clone.d
  test/runnable/test22717.d
Labels: auto-merge, Bug Fix

#13662 Fix issue 22776 - string literal printing fails on non-ASCII/non-printable chars
  src/dmd/dtoh.d
  src/dmd/hdrgen.d
  src/dmd/tokens.d
  test/fail_compilation/diag15713.d
  test/fail_compilation/fail196.d
  test/fail_compilation/lexer1.d
Labels: auto-merge, Bug Fix

#13661 Remove dead members from NewExp, NewAnonClassExp, and VarDeclaration
  src/dmd/apply.d
  src/dmd/astbase.d
  src/dmd/dcast.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expression.h
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/hdrgen.d
  src/dmd/inline.d
  src/dmd/optimize.d
  src/dmd/parse.d
  src/dmd/transitivevisitor.d
  test/fail_compilation/fail_arrayop2.d
Labels: auto-merge, Refactoring

#13628 Include coverage from `unit` tests
  ci.sh
  ci/codecov.sh
  test/run.d
  test/tools/unit_test_runner.d
Labels: auto-merge, Continuous Integration

#13665 test: Adapt tests that to use alternatives for the 'delete' keyword
  test/compilable/debugInference.d
  test/compilable/test17906.d
  test/compilable/vgc1.d
  test/runnable/class_destructors.d
  test/runnable/imports/link12144a.d
  test/runnable/interface.d
  test/runnable/interface2.d
  test/runnable/interpret.d
  test/runnable/link12144.d
  test/runnable/link15017.d
  test/runnable/mixin1.d
  test/runnable/newdel.d
  test/runnable/sdtor.d
  test/runnable/test20.d
  test/runnable/test4.d
  test/runnable/testappend.d
  test/runnable/testdstress.d
Labels: auto-merge, Deprecation -> Error

#13660 dmd.typesem: Remove usage of 'this' and 'super' as types
  changelog/super_type_gone.dd
  src/dmd/dscope.d
  src/dmd/typesem.d
  test/fail_compilation/fail18228.d
  test/fail_compilation/fail_typeof.d
  test/fail_compilation/test12228.d
Labels: auto-merge, Easy Review, Deprecation

#13667 fix Issue 22780 - [REG 2.090] variable reference to scope class must be scope
  src/dmd/dsymbolsem.d
  test/compilable/test7172.d
  test/fail_compilation/fail22780.d
Labels: Regression, auto-merge, Bug Fix, Easy Review

#13668 End deprecation period for 'scope' as a type constraint on interface declarations
  changelog/error_scope_interface.dd
  src/dmd/dsymbolsem.d
  test/fail_compilation/scope_type.d
Labels: auto-merge, Easy Review, Deprecation -> Error

#13674 [stable] C++ headers: Rename TOK::cdecl to TOK::cdecl_
  src/dmd/tokens.h
Labels: auto-merge

#13666 End deprecation period for the 'delete' keyword
  changelog/deprecation_delete.dd
  src/dmd/canthrow.d
  src/dmd/dinterpret.d
  src/dmd/e2ir.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/id.d
  src/dmd/inline.d
  src/dmd/nogc.d
  src/dmd/parse.d
  test/compilable/test17906.d
  test/fail_compilation/fail14486.d
  test/fail_compilation/fail17906.d
  test/fail_compilation/fail2361.d
  test/fail_compilation/fail_arrayop2.d
  test/fail_compilation/faildeleteaa.d
  test/fail_compilation/ice11968.d
  test/fail_compilation/nogc1.d
  test/fail_compilation/test16195.d
Labels: auto-merge, Deprecation -> Error

#13675 dmd.mtype: Set an end date for the complex/imaginary deprecation process
  src/dmd/mtype.d
Labels: Trivial, auto-merge, Deprecation

#13677 fix Issue 22541 - DIP1000: Resolve ambiguity of ref-return-scope para…
  src/dmd/func.d
  test/compilable/testsctreturn.d
Labels: Enhancement, auto-merge

#13678 opover.d: remove most of the casts
  src/dmd/opover.d
Labels: auto-merge, Easy Review, Refactoring

#13676 dmd.semantic3: Set an end date for the revert5710 deprecation process
  src/dmd/semantic3.d
Labels: Trivial, Deprecation

#13535 Azure/CodeCov: Remove workaround for token-less coverage upload
  ci/codecov.sh
Labels: Continuous Integration

#13609 parse: refactor logic to check STC conflicts
  src/dmd/parse.d
Labels: Easy Review, Refactoring, 72h no objection -> merge

#13682 test/runnable/test22342.c: Use counter to verify that side-effects are executed
  test/runnable/test22342.c
Labels: auto-merge, Bug Fix

#13625 frontend: propagate error as null instead of exit(1)
  src/dmd/dmodule.d
  src/dmd/frontend.d
  test/unit/frontend.d
Labels: auto-merge, Bug Fix

#13683 test: Add missing EXTRA_FILES directives
  test/compilable/test22625.d
  test/compilable/test22665.d
  test/compilable/test22685.d
  test/compilable/test22734.d
  test/runnable/fix22624.d
Labels: GDC, Trivial, auto-merge

#13684 fix Issue 22788 - [REG master] Expression header out of sync
  src/dmd/expression.h
Labels: Regression, GDC, auto-merge, Bug Fix

#13685 Merge stable into master
  src/dmd/clone.d
  src/dmd/dmodule.d
  src/dmd/dsymbolsem.d
  src/dmd/opover.d
  src/dmd/parse.d
  src/dmd/tokens.h
  test/compilable/imports/include_unittest/compiled_lib.d
  test/compilable/imports/include_unittest/compiled_unittest_lib.d
  test/compilable/imports/include_unittest/skipped_unittest_lib.d
  test/compilable/include_unittest.d
  test/compilable/test21196.d
  test/compilable/test7172.d
  test/fail_compilation/fail22780.d
  test/runnable/test22342.c
  test/runnable/test22717.d
Labels: auto-merge, Bug Fix, stable -> master

#13672 Fix Issue 22782 - address of ref can be assigned to non-scope parameter
  smallbuffer.txt
  src/dmd/escape.d
  test/fail_compilation/test20245.d
Labels: auto-merge, Bug Fix, dip1000

#13688 [stable] [changelog] Add item for `noreturn main`
  changelog/main_return_type.dd
Labels: auto-merge

#7690 fix Issue 7625 - inlining only works with explicit else branch
  test/runnable/inline7625.d
Labels: auto-merge, Bug Fix, Easy Review

#13692 fix Issue 22145 - scope for foreach parameters is ignored
  src/dmd/statementsem.d
  test/fail_compilation/test22145.d
Labels: auto-merge, Bug Fix

#13694 toStatement(): remove Visitor
  src/dmd/statementsem.d
Labels: auto-merge, Refactoring

#13695 fix Issue 22797 - [REG master] Internal Compiler Error: cannot mixin static assert ''
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/frontend.h
  src/dmd/statementsem.d
  src/dmd/staticassert.d
  src/dmd/staticassert.h
Labels: Regression, auto-merge, Bug Fix

#13652 ci: move ci.sh and cirrusci.sh script to ci/ folder
  .cirrus.yml
  ci.sh
  ci/cirrusci.sh
  ci/run.sh
  cirrusci.sh
  test/Makefile
Labels: auto-merge, Continuous Integration

#13698 Remove smallbuffer.txt
  smallbuffer.txt
Labels: auto-merge

#13700 ci: add executable permissions to ci.sh and cirrusci.sh
  ci.sh
  cirrusci.sh
Labels: Blocking Other Work, auto-merge, Continuous Integration

#13702 fix Issue 22806 - cppmangle: Complex real mangled incorrectly
  src/dmd/cppmangle.d
Labels: auto-merge, Bug Fix

#13703 fix Issue 22810 - [REG 2.088] FAIL: runnable/test15.d on BigEndian targets
  test/runnable/test15.d
Labels: auto-merge, Bug Fix

#13704 Fix issue 22804: multiple object files without linking produces broken files
  src/dmd/glue.d
  test/dshell/extra-files/issue22804.d
  test/dshell/imports/issue22804_1.d
  test/dshell/imports/issue22804_2.d
  test/dshell/issue22804.d
  test/tools/dshell_prebuilt/dshell_prebuilt.d
Labels: Bug Fix

#13705 test/runnable: Fix-up tests that fail on PPC64 targets
  test/runnable/nan.d
  test/runnable/previewin.d
  test/runnable/traits_getPointerBitmap.d
Labels: auto-merge, Bug Fix

#13708 fix Issue 22817 - [REG 2.099] Missing file gives misleading error message
  src/dmd/dmodule.d
Labels: Regression, auto-merge, Bug Fix

#13707 fix Issue 22816 - [REG 2.099] Parser reads files with other extensions
  src/dmd/file_manager.d
Labels: Regression, auto-merge, Bug Fix

#13709 reduce complexity of class Mangler
  src/dmd/dmangle.d
Labels: Easy Review, Refactoring

#13710 fix Issue 22023 - adding to escaped argument of a variadic defeats @…
  src/dmd/typesem.d
  test/fail_compilation/test22023.d
Labels: Bug Fix

#13716 Mangler: make Backref its own encapsulation
  src/dmd/dmangle.d
Labels: auto-merge, Easy Review, Refactoring

#13715 convert visit to mangleParameter()
  src/dmd/dmangle.d
Labels: Easy Review, Refactoring

#13714 fix Issue 22818 - typesafe variadic function parameter of type class …
  src/dmd/semantic3.d
  test/fail_compilation/test22818.d
Labels: Bug Fix

#13713 Add dshell tests for Issue 22816 and Issue 22817
  test/dshell/extra-files/issue22816.d
  test/dshell/issue22816.d
  test/dshell/issue22817.d
  test/tools/dshell_prebuilt/dshell_prebuilt.d
Labels: Easy Review, auto-merge-squash

#13680 Use SmallBuffer instead of manual malloc/free
  src/dmd/backend/cgobj.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/gsroa.d
  src/dmd/e2ir.d
  src/dmd/root/speller.d
  src/dmd/root/string.d
  src/dmd/semantic3.d
  src/dmd/tocsym.d
  src/dmd/toctype.d
Labels: auto-merge, Refactoring, 72h no objection -> merge, Walter Bright

#12565 dmd.cparse: Add support more C targets
  src/dmd/cparse.d
  src/dmd/frontend.h
  src/dmd/lexer.d
  src/dmd/target.d
  src/dmd/target.h
Labels: Walter Bright, ImportC

#13718 dmd.root.file: Comment out debug messages in File.read
  src/dmd/root/file.d
Labels: auto-merge, Easy Review, Refactoring

#13722 fix Issue 21546 - covariant return checks for functions wrong if retu…
  src/dmd/mtype.d
  test/fail_compilation/test21546.d
Labels: auto-merge, Bug Fix

#13721 localize scc global variable
  src/dmd/tocsym.d
Labels: auto-merge, Easy Review, Refactoring

#13719 fix Issue 22823 - dmd.root.file: File.read fails to read any file on PPC
  src/dmd/root/file.d
Labels: auto-merge, Bug Fix

#13720 remove Visitor from Type_toCtype()
  src/dmd/toctype.d
Labels: Easy Review, Refactoring

#13726 dmd/tokens.h: Remove dead comments from headers
  src/dmd/tokens.h
Labels: Trivial, auto-merge, Refactoring

#13729 Remove checks for global.params.vcomplex
  src/dmd/dsymbolsem.d
  src/dmd/expressionsem.d
  src/dmd/semantic3.d
  src/dmd/traits.d
Labels: auto-merge, Easy Review, Refactoring

#13725 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/main_return_type.dd
  src/dmd/dmodule.d
  src/dmd/file_manager.d
  src/dmd/glue.d
  src/dmd/lexer.d
  test/dshell/extra-files/issue22804.d
  test/dshell/extra-files/issue22816.d
  test/dshell/imports/issue22804_1.d
  test/dshell/imports/issue22804_2.d
  test/dshell/issue22804.d
  test/dshell/issue22816.d
  test/dshell/issue22817.d
  test/fail_compilation/issue22826.d
  test/tools/dshell_prebuilt/dshell_prebuilt.d
Labels: auto-merge, Bug Fix, stable -> master

#13733 Add test case for Issue 21390
  test/compilable/issue21390.d
Labels: Trivial, Easy Review

#13712 fix(dub): Make config.d executable to incremental compilation
  config.d
Labels: Enhancement
