Repository dlang/dmd, pull requests merged in 2022-03, with the labels that each got.

#13736 fix Issue 22809 - ImportC: druntime.s definition of __builtin_offseto…
  src/dmd/optimize.d
  test/compilable/test22809.c
Labels: auto-merge, Bug Fix

#13738 Fix Issue 21975 - is expression ignores implicit conversion of struct via alias this when pattern matching
  src/dmd/dtemplate.d
  test/compilable/test21975.d
Labels: auto-merge, Bug Fix, Easy Review

#13734 mtype: Add TypeAggregate and refactor repetitive code for structs and classes
  src/dmd/astbase.d
  src/dmd/dmangle.d
  src/dmd/dsymbolsem.d
  src/dmd/dtoh.d
  src/dmd/expression.d
  src/dmd/frontend.h
  src/dmd/lambdacomp.d
  src/dmd/mtype.d
  src/dmd/opover.d
  src/dmd/parsetimevisitor.d
  src/dmd/semantic3.d
  src/dmd/strictvisitor.d
  src/dmd/tocsym.d
  src/dmd/visitor.h
Labels: Refactoring

#13739 fix Issue 22833 - [REG 2.083] error: 'string' is not a member of 'std'
  test/runnable_cxx/extra-files/cppb.cpp
Labels: Bug Fix, Easy Review

#13743 fix Issue 22808 - ImportC: function not decaying to pointer to functi…
  src/dmd/statementsem.d
  test/compilable/test22808.c
Labels: auto-merge, Bug Fix

#13617 Fix 22708 - Extend semantic for switch statements with invalid values
  src/dmd/statementsem.d
  test/fail_compilation/test_switch_error.d
Labels: Bug Fix

#13742 Revert "mtype: Add TypeAggregate and refactor repetitive code for structs and classes"
  src/dmd/astbase.d
  src/dmd/dmangle.d
  src/dmd/dsymbolsem.d
  src/dmd/dtoh.d
  src/dmd/expression.d
  src/dmd/frontend.h
  src/dmd/lambdacomp.d
  src/dmd/mtype.d
  src/dmd/opover.d
  src/dmd/parsetimevisitor.d
  src/dmd/semantic3.d
  src/dmd/strictvisitor.d
  src/dmd/tocsym.d
  src/dmd/visitor.h
Labels: Regression, Blocking Other Work

#13740 Add DDoc comments to AST nodes
  src/dmd/expression.d
Labels: auto-merge, documentation

#13696 add lexer option to tokenize whitespaces under version DMDLIB
  src/dmd/frontend.h
  src/dmd/lexer.d
  src/dmd/tokens.d
  src/dmd/tokens.h
  test/unit/lexer/lexer_dmdlib.d
  test/unit/lexer/location_offset.d
Labels: auto-merge

#13724 fix Issue 21008 - dmd segfaults because of __traits(getMember, ...) a…
  src/dmd/dsymbolsem.d
  test/fail_compilation/test21008.d
Labels: Bug Fix

#13649 Fix issue 22770: C++ header generator generates trailing newlines
  src/dmd/common/outbuffer.d
  src/dmd/dtoh.d
  src/dmd/frontend.h
Labels: Enhancement, auto-merge

#13750 fix Issue 22841 - importC: Error: variable 'var' is shadowing variable 'var'
  src/dmd/expressionsem.d
  test/compilable/testcstuff2.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13748 Fix issue 22802 - First ref parameter seen as `return` destination ev…
  src/dmd/escape.d
  test/fail_compilation/test19097.d
Labels: auto-merge, Bug Fix, dip1000

#13747 fix Issue 22793 - importC: __import conflicts when importing multiple…
  src/dmd/dsymbol.d
  test/compilable/test22793.c
Labels: auto-merge, Bug Fix

#13752 Fix issue 22845: DWARF .debug_line section is not standard compliant
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge, Bug Fix

#13753 fix(test): change wording COMPILE_SEPERATELY -> COMPILE_SEPARATELY
  test/tools/d_do_test.d
Labels: auto-merge, Easy Review

#13746 fix Issue 22807 - ImportC: Array index is out of bounds for old-style…
  src/dmd/constfold.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/importc.d
  src/dmd/optimize.d
  test/compilable/test22807.c
Labels: Bug Fix

#13744 Fix issue 22837 - checkConstructorEscape quits after first non-pointer
  src/dmd/escape.d
  test/fail_compilation/test19097.d
Labels: Bug Fix, dip1000

#13757 Fix issue 22848: DWARF .debug_line section should be always generated
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge, Bug Fix

#13758 ci: remove intermediate scripts introduced on PR #13652
  ci.sh
  cirrusci.sh
Labels: auto-merge, Easy Review, Continuous Integration

#13671 End deprecation period for D1 style overload operators
  changelog/d1_style_operators.dd
  src/dmd/opover.d
  src/dmd/typesem.d
  test/fail_compilation/dep_d1_ops.d
  test/fail_compilation/deprecateopdot.d
  test/runnable/opover.d
  test/runnable/xtest46.d
  test/runnable/xtest46_gc.d
Labels: auto-merge, Deprecation -> Error

#13759 chore(test): remove trailing whitespace
  test/runnable/interpret.d
  test/unit/lexer/lexer_dmdlib.d
Labels: auto-merge, Easy Review, Refactoring

#13755 Fix Issue 21844: makedeps contain non-existing files
  src/dmd/dmodule.d
  test/compilable/makedeps_exe.d
Labels: auto-merge, Bug Fix

#13669 Deprecate 'scope' as a type constraint on class declarations
  changelog/dep_scope_class.dd
  src/dmd/dsymbolsem.d
  test/compilable/test7172.d
  test/fail_compilation/fail22780.d
  test/fail_compilation/scope_class.d
  test/fail_compilation/scope_type.d
  test/fail_compilation/typeerrors.d
  test/runnable/auto1.d
  test/runnable/sctor2.d
Labels: auto-merge, Easy Review, Deprecation

#13763 move .isym from Dsymbol to Declaration
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/frontend.h
  src/dmd/tocsym.d
Labels: Refactoring

#13771 chore(build): make all build steps consistent
  src/build.d
Labels: auto-merge, Build System

#13767 Deprecate 'scope' as a type constraint on struct and enum declarations
  changelog/dep_scope_type.dd
  src/dmd/dsymbolsem.d
  test/fail_compilation/scope_type.d
Labels: auto-merge, Deprecation

#13768 dmd.cparser: Move directive lexing/parsing to specialTokenSequence
  src/dmd/cparse.d
  src/dmd/lexer.d
Labels: auto-merge, Refactoring

#13761 optimize.d: replace for loops and gotos
  src/dmd/optimize.d
Labels: auto-merge, Easy Review, Refactoring

#13773 dmd.lexer: Remove hex string constant from lexer and parser
  src/dmd/frontend.h
  src/dmd/lexer.d
  src/dmd/parse.d
  src/dmd/tokens.d
  src/dmd/tokens.h
  test/fail_compilation/dephexstrings.d
  test/fail_compilation/fail136.d
  test/fail_compilation/lexer1.d
  test/fail_compilation/lexer2.d
  test/unit/lexer/location_offset.d
Labels: Easy Review, Deprecation -> Error

#13769 replace Dsymbol.comment with hash table
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/frontend.d
  src/dmd/frontend.h
Labels: Refactoring

#13774 fix Issue 22853 - importC: Lexer allows nesting block comments
  src/dmd/lexer.d
  test/fail_compilation/fail22853a.c
  test/fail_compilation/fail22853b.c
Labels: Bug Fix, Easy Review, ImportC

#13697 add test case for scoping error with opApply
  src/dmd/opover.d
  src/dmd/statementsem.d
  test/fail_compilation/opapplyscope.d
Labels: auto-merge, Easy Review

#13775 fix Issue 22852 - importC: Lexer allows invalid wysiwyg and hex strings
  src/dmd/lexer.d
  test/fail_compilation/fail22852.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13777 Fix 22858 - Don't skip alignment of zero-sized fields
  src/dmd/aggregate.d
  test/compilable/noreturn3.d
Labels: auto-merge, Bug Fix

#13730 Issue 22827 - Deprecate 128-bit cent and ucent types
  src/dmd/typesem.d
  test/fail_compilation/fail22827.d
Labels: Needs Approval, Needs Changelog, Easy Review, Needs Spec PR

#13754 feat(test): Add DWARF_VERIFY flag on DWARF tests
  ci/cirrusci.sh
  ci/run.sh
  test/dshell/dwarf.d
  test/dshell/extra-files/dwarf/fix21160.d
  test/dshell/extra-files/dwarf/fix22426.d
  test/dshell/extra-files/dwarf/fix22471.d
  test/dshell/extra-files/dwarf/fix22508.d
  test/dshell/extra-files/dwarf/immutable.d
  test/dshell/extra-files/dwarf/immutableVoid.d
  test/dshell/extra-files/dwarf/testVersion.d
Labels: Continuous Integration, Testing Infrastructure

#13772 fix(build): avoid calling cxx-headers with useless/incompatible flags
  src/build.d
Labels: auto-merge, Build System

#13785 merge stable
  VERSION
  changelog/22541.dd
  changelog/TraitsParameters.dd
  changelog/__import.dd
  changelog/allow_casting_from_typetuple_to_typetuple.dd
  changelog/disasm.dd
  changelog/fix16997.dd
  changelog/fix18964.dd
  changelog/ignore_nonroot_ut.dd
  changelog/main_return_type.dd
  changelog/switch_fallthrough_error.dd
  changelog/throw_expression.dd
  changelog/traits_initSymbol.dd
  src/dmd/dmodule.d
  src/dmd/lexer.d
  src/dmd/mtype.d
  src/dmd/statementsem.d
  test/compilable/commontype.d
  test/compilable/makedeps_exe.d
  test/fail_compilation/fail22852.c
  test/fail_compilation/fail22853a.c
  test/fail_compilation/fail22853b.c
  test/fail_compilation/test_switch_error.d
  test/runnable/test22136.d
  test/runnable/testconst.d
Labels: auto-merge, Bug Fix

#13316 Fix issue 21285 - Delegate covariance broken
  src/dmd/expressionsem.d
  src/dmd/hdrgen.d
  src/dmd/mtype.d
  test/compilable/b21285.d
Labels: auto-merge, Bug Fix

#13778 fix Issue 22842 - importC: cannot declare function with a typedef
  src/dmd/cparse.d
  src/dmd/declaration.d
  src/dmd/dsymbolsem.d
  test/compilable/test22842.c
Labels: auto-merge, Bug Fix, ImportC

#13786 ImportC: add scoping to funcTypeIds
  src/dmd/cparse.d
  test/compilable/test22842.c
Labels: auto-merge, ImportC

#13790 Remove old comments in escape.d
  src/dmd/escape.d
Labels: Trivial, auto-merge, Easy Review, dip1000

#13362 Fix issue 22539 - slicing of returned ref scope static array should not be allowed
  src/dmd/expressionsem.d
  test/fail_compilation/test15191.d
Labels: Bug Fix, 72h no objection -> merge, dip1000

#13793 Add unittests for OutBuffer
  src/dmd/common/outbuffer.d
Labels: Easy Review

#13691 fix Issue 22790 - ref-return-scope is always ref-return, scope, unless return-scope appear in that order
  src/dmd/func.d
  src/dmd/mtype.d
  src/dmd/typesem.d
  test/compilable/scope.d
  test/fail_compilation/test21912.d
Labels: Enhancement, dip1000

#13799 Revert "fix Issue 22790 - ref-return-scope is always ref-return, scope, unless return-scope appear in that order "
  src/dmd/func.d
  src/dmd/mtype.d
  src/dmd/typesem.d
  test/compilable/scope.d
  test/fail_compilation/test21912.d
Labels: auto-merge

#13801 use ref-return-scope pretty printer
  src/dmd/escape.d
Labels: auto-merge, Easy Review, Refactoring

#13805 dmd.expression: Emplace initializer on preallocated pointer instead of temporary
  src/dmd/expression.d
Labels: Blocking Other Work, auto-merge, Bug Fix

#13806 dmd.dtemplate: Use __VERSION__ < 2099 in static condition
  src/dmd/dtemplate.d
Labels: auto-merge, Refactoring

#13808 make Dsymbol.ddocUnittest a hash table
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/frontend.h
Labels: Easy Review, Refactoring

#13809 frontend: use static immutable instead of __gshared const
  src/dmd/astbase.d
  src/dmd/dcast.d
  src/dmd/dclass.d
  src/dmd/errors.d
  src/dmd/statementsem.d
Labels: auto-merge, Easy Review, Refactoring

#13802 Use `buildScopeRef` in escapeByX
  src/dmd/escape.d
Labels: dip1000

#13798 Fix 22868 - Let __traits(parameters) see past opApply delegates
  changelog/TraitsParametersRevised.dd
  src/dmd/dscope.d
  src/dmd/traits.d
  test/compilable/fix22291.d
Labels: auto-merge, Bug Fix

#13789 Add a `FunctionFlag` for `return scope`
  src/dmd/frontend.h
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/typesem.d
Labels: dip1000

#13812 dmd.dtemplate: Declare printTemplateStats as extern(C++)
  src/dmd/dtemplate.d
  src/dmd/frontend.h
  src/dmd/template.h
Labels: auto-merge, Easy Review

#13814 dmd.dtoh: Initialize struct fields with its own ctor when generating default constructor
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_StructDeclaration.d
  test/compilable/dtoh_required_symbols.d
Labels: auto-merge, Easy Review, dtoh

#13815 dmd/common/outbuffer.h: Include root headers relative to its path
  src/dmd/common/outbuffer.h
Labels: GDC, auto-merge, Easy Review

#13811 Use ScopeRef when determining ref-return-scope for 'this'
  src/dmd/escape.d
Labels: Refactoring

#13807 module: use a FileType instead of three seperate bools
  src/dmd/astenums.d
  src/dmd/blockexit.d
  src/dmd/dmodule.d
  src/dmd/doc.d
  src/dmd/dscope.d
  src/dmd/dsymbol.d
  src/dmd/frontend.h
  src/dmd/globals.h
  src/dmd/glue.d
  src/dmd/mars.d
  src/dmd/module.h
  src/dmd/toir.d
Labels: auto-merge, Easy Review, Refactoring

#13813 dmd.dtoh: Don't emit bogus alignment comments in headers
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_AliasDeclaration.d
  test/compilable/dtoh_TemplateDeclaration.d
  test/compilable/dtoh_forwarding.d
  test/compilable/dtoh_ignored.d
  test/compilable/dtoh_invalid_identifiers.d
  test/compilable/dtoh_names.d
  test/compilable/dtoh_required_symbols.d
Labels: auto-merge, Easy Review, dtoh

#13804 Fix 22871 - Support aliases to __traits(parameters)
  src/dmd/parse.d
  src/dmd/typesem.d
  test/compilable/fix22291.d
Labels: Bug Fix

#13817 Use ScopeRef when determining ref-return-scope for 'this' part 2
  src/dmd/escape.d
Labels: Refactoring

#13803 dmd.ctfeexpr: Reduce stack usage in a few CTFE helpers
  src/dmd/ctfeexpr.d
  src/dmd/dinterpret.d
Labels: Refactoring

#13794 Move Triple from dmd.target to dmd.dmdparams
  src/dmd/dmdparams.d
  src/dmd/frontend.h
  src/dmd/target.d
  src/dmd/target.h
  test/unit/triple.d
Labels: Easy Review, Refactoring

#13792 Template Parser with Lexer argument
  src/dmd/parse.d
Labels: Blocking Other Work

#13819 dmd.dmdparams: Rename dmdParams to driverParams
  src/dmd/dmdparams.d
  src/dmd/dmsc.d
  src/dmd/link.d
  src/dmd/mars.d
Labels: auto-merge, Easy Review, Refactoring

#13818 fix Issue 22878 - importC: glibc fallback for HUGE_VAL gives 'not rep…
  src/dmd/lexer.d
  test/compilable/test22878.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13821 backend: move iasm_regs from iasmdmd.d
  src/dmd/backend/code.d
  src/dmd/iasmdmd.d
Labels: auto-merge, Easy Review, Refactoring

#13824 fix Issue 22877 - importC: wrong sizeof for string literal
  src/dmd/expressionsem.d
  test/compilable/test22877.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13810 backend: use static immutable instead of enum/gshared for fixed-length arrays
  src/dmd/backend/debugprint.d
  src/dmd/backend/oper.d
Labels: Easy Review, Refactoring, 72h no objection -> merge

#13779 Change rvalueRefParam from bool to FeatureState
  src/dmd/dtemplate.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/mtype.d
  src/dmd/typesem.d
Labels: auto-merge

#13784 Fix Issue 20015 - [REG 2.086] Deprecated -preview, -revert, and -transition options not documented
  src/dmd/cli.d
  test/compilable/transitionhelp.d
Labels: Enhancement, auto-merge, Bug Fix

#13826 fix Issue 22881 - ICE Index of array outside of bounds at CTFE
  src/dmd/constfold.d
  src/dmd/dinterpret.d
  test/fail_compilation/fail22881.d
Labels: auto-merge, Bug Fix

#13832 dmd.file_manager: Remove extern(C++) member functions
  src/dmd/file_manager.d
Labels: auto-merge, Easy Review, Refactoring

#13835 dmd.globals: Remove unused d_intN and d_unsN types
  src/dmd/astbase.d
  src/dmd/compiler.d
  src/dmd/constfold.d
  src/dmd/expression.d
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/iasmdmd.d
  src/dmd/tokens.d
Labels: auto-merge, Bug Fix, Easy Review, Refactoring

#13837 dmd.globals: Replace trivial uses of d_uns64 with ulong
  src/dmd/astbase.d
  src/dmd/constfold.d
  src/dmd/expression.d
  src/dmd/optimize.d
  src/dmd/toobj.d
  src/dmd/traits.d
  src/dmd/typesem.d
Labels: auto-merge, Easy Review, Refactoring

#13836 dmd.globals: Replace d_int64 with long
  src/dmd/astbase.d
  src/dmd/compiler.d
  src/dmd/constfold.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  src/dmd/target.d
  src/dmd/target.h
Labels: auto-merge, Easy Review, Refactoring

#13840 dmd.mtype: Change return type of size() to uinteger_t
  src/dmd/aggregate.d
  src/dmd/aggregate.h
  src/dmd/argtypes_x86.d
  src/dmd/dcast.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dinterpret.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/dsymbolsem.d
  src/dmd/e2ir.d
  src/dmd/frontend.h
  src/dmd/mtype.d
  src/dmd/mtype.h
  src/dmd/optimize.d
  src/dmd/toobj.d
Labels: auto-merge, Easy Review, Refactoring

#13841 dmd.root.filename: Fix compilation failure in canonicalize_file_name path
  src/dmd/root/filename.d
Labels: auto-merge, Bug Fix, Easy Review

#13834 Issue 22898 - [REG master] Solaris: byte.min value is 128
  src/dmd/cppmangle.d
  src/dmd/cppmanglewin.d
  src/dmd/dtoh.d
  src/dmd/id.d
  test/runnable_cxx/extra-files/test22898.cpp
  test/runnable_cxx/test22898.d
Labels: auto-merge, Easy Review

#13843 fix Issue 22892 - importC: dereferencing array as pointer is not supp…
  src/dmd/expressionsem.d
  test/compilable/test22892.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13842 fix Issue 22884 - ImportC: function does not decay to pointer when be…
  src/dmd/expressionsem.d
  test/compilable/test22884.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13844 fix Issue 22895 - importC: exponent parsed as member access
  src/dmd/lexer.d
  test/compilable/test22895.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13845 fix Issue 22896 - importC: 'function redeclaration with different typ…
  src/dmd/importc.d
  test/compilable/test22761.c
Labels: auto-merge, Bug Fix, ImportC

#13846 fix Issue 22897 - importC: segfault calling forward-declared static f…
  src/dmd/tocsym.d
  test/runnable/test22897.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13831 fix Issue 22876 - importC: expression parsing affected by parentheses…
  src/dmd/cparse.d
  test/compilable/test22842.c
  test/fail_compilation/failcstuff2.c
Labels: Blocking Other Work, auto-merge, Bug Fix, ImportC

#13847 Fix issue 22906: DMDLIB hangs on semantic analysis of non regular D files
  src/dmd/semantic2.d
  src/dmd/semantic3.d
  test/unit/frontend.d
Labels: auto-merge, Bug Fix

#13848 fix Issue 22909 - importC: u8 strings rejected by parser
  src/dmd/lexer.d
  test/compilable/testcstuff1.c
  test/fail_compilation/failcstuff1.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13849 Fix dstrcomp unittest assuming memcmp returns [-1, 0, 1]
  src/dmd/root/string.d
Labels: auto-merge

#13850 fix Issue 22904 - importC: syntax error for function call with casted…
  src/dmd/cparse.d
  test/compilable/test22904.c
Labels: auto-merge, Bug Fix, ImportC

#13243 Minor improvements to `foreach` semantic code for arrays
  src/dmd/statementsem.d
Labels: auto-merge

#13760 ci(pre-commit): add pre-commit configuration
  .github/workflows/pre_commit.yml
  .pre-commit-config.yaml
Labels: Continuous Integration

#13838 dmd.target: Remove Target.parameterSize
  src/dmd/frontend.h
  src/dmd/target.d
  src/dmd/target.h
Labels: auto-merge, Easy Review, Refactoring

#13855 fail_compilation/fail22881.d: Remove trailing whitespace
  test/fail_compilation/fail22881.d
Labels: Regression, Trivial, auto-merge, Easy Review

#13856 dmd.globals: Remove unused d_uns64 alias
  src/dmd/globals.d
  src/dmd/globals.h
Labels: auto-merge, Easy Review, Refactoring

#13693 Fix issue 20881, 22790 - make ref-return-scope consistent
  src/dmd/escape.d
  src/dmd/semantic3.d
  src/dmd/typesem.d
  test/compilable/scope.d
  test/fail_compilation/pull12941.d
  test/fail_compilation/retscope2.d
  test/fail_compilation/test15191.d
  test/fail_compilation/test17422.d
  test/fail_compilation/test20881.d
  test/fail_compilation/test21912.d
Labels: Enhancement, auto-merge, Bug Fix, dip1000

#13852 fix Issue 22885 - ImportC: typedef declared with itself should work
  src/dmd/cparse.d
  test/compilable/test22885.c
Labels: auto-merge, Bug Fix, ImportC

#13853 Fix Issue 22639 - Copy constructors with default arguments not getting called
  src/dmd/expressionsem.d
  test/compilable/test22639.d
Labels: auto-merge, Bug Fix

#13857 FuncDeclaration: Move booleans to FUNCFLAG
  src/dmd/clone.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/dinterpret.d
  src/dmd/dsymbol.d
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/dtoh.d
  src/dmd/e2ir.d
  src/dmd/escape.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/func.d
  src/dmd/glue.d
  src/dmd/iasmdmd.d
  src/dmd/inline.d
  src/dmd/opover.d
  src/dmd/s2ir.d
  src/dmd/semantic3.d
  src/dmd/tocsym.d
  src/dmd/tocvdebug.d
  src/dmd/toir.d
  src/dmd/typesem.d
Labels: auto-merge

#13851 fix Issue 22899 - importC: extra parentheses in sizeof should give er…
  src/dmd/cparse.d
  test/fail_compilation/test22899.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13859 fix Issue 22886 - ImportC: forward declaration of struct in a functio…
  src/dmd/importc.d
  test/compilable/test22886.c
Labels: Bug Fix, ImportC

#12689 Fix issue 22027, 20149 - inout doesn't imply return
  changelog/inout-return.dd
  src/dmd/dmangle.d
  src/dmd/func.d
  src/dmd/typesem.d
  test/fail_compilation/fail17927.d
  test/fail_compilation/test22840.d
  test/runnable/testscope2.d
Labels: Enhancement, Bug Fix, Vision

#13788 fix Issue 22175 - assert fail when struct assignment value is desired…
  src/dmd/backend/cod2.d
  test/runnable/test22175.d
Labels: Enhancement, auto-merge, Bug Fix

#13868 dmd.func: Add FuncDeclaration.isCrtCtor and isCrtDtor getters
  src/dmd/declaration.h
  src/dmd/frontend.h
  src/dmd/func.d
Labels: Regression, GDC, Blocking Other Work, Easy Review

#13861 [refactoring] Rename cxxfrontend.c to cxxfrontend.cc
  src/build.d
  src/tests/cxxfrontend.cc
Labels: auto-merge, Easy Review, Refactoring

#13864 test/compilable/test22886.c: fix end of file
  test/compilable/test22886.c
Labels: Easy Review, Refactoring

#13865 ci(pre-commit): add end-of-file-fixer hook
  .pre-commit-config.yaml
Labels: auto-merge, Easy Review, Continuous Integration

#13869 dtoh: make generated define directives style consistent
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_VarDeclaration.d
  test/compilable/dtoh_extern_type.d
  test/compilable/dtoh_ignored.d
Labels: Trivial, auto-merge

#13237 backend: dwarfdbginf: refactor DWARF abbreviations
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge, Refactoring

#13862 cxxfrontend.cc: Add a mini-glue layer visitor
  src/tests/cxxfrontend.cc
Labels: GDC, auto-merge, extern (C/C++)

#13873 Make FileManager a class and move it to global
  src/dmd/dmodule.d
  src/dmd/errors.d
  src/dmd/expressionsem.d
  src/dmd/file_manager.d
  src/dmd/frontend.d
  src/dmd/frontend.h
  src/dmd/globals.d
  src/dmd/globals.h
  test/unit/deinitialization.d
Labels: auto-merge

#13872 fix Issue 22912 - importC: syntax error for function call with cast a…
  src/dmd/cparse.d
  test/compilable/test22904.c
Labels: auto-merge, Bug Fix, ImportC

#13871 Automatically generate `mtype.FuncFlags` accessors
  src/dmd/frontend.h
  src/dmd/mtype.d
Labels: auto-merge, Refactoring

#13860 Fix issue 22910 - `return scope` struct member functions allow returning `this` by ref
  src/dmd/func.d
  test/compilable/extra-files/header1.d
  test/compilable/extra-files/header1i.di
  test/compilable/json.d
  test/fail_compilation/test22910.d
Labels: Bug Fix, dip1000

#13749 Fix 22831 - Check signature of extern(C) main functions
  src/dmd/dsymbolsem.d
  src/dmd/func.d
  src/dmd/semantic3.d
  test/compilable/betterCarray.d
  test/compilable/betterCswitch.d
  test/compilable/cmain.d
  test/compilable/noreturn_main.d
  test/fail_compilation/fail131.d
  test/fail_compilation/malformed_cmain.d
Labels: auto-merge, Bug Fix

#13875 Fix issue 22914 - outdated supplemental error "perhaps remove scope"
  src/dmd/escape.d
  test/fail_compilation/dip25.d
  test/fail_compilation/fail13902.d
  test/fail_compilation/fail20084.d
  test/fail_compilation/fail20448.d
  test/fail_compilation/fail21868b.d
  test/fail_compilation/fix18575.d
  test/fail_compilation/shared.d
  test/fail_compilation/test16589.d
  test/fail_compilation/test17450.d
  test/fail_compilation/test22541.d
  test/fail_compilation/test22910.d
Labels: auto-merge, Bug Fix, dip1000

#13878 dmd.lexer: Give more informative errors for #line directive
  src/dmd/lexer.d
  test/compilable/testcstuff1.c
  test/fail_compilation/fail22825a.d
  test/fail_compilation/fail359.d
  test/fail_compilation/fail7524a.d
  test/fail_compilation/fail7524b.d
  test/fail_compilation/failcstuff1.c
  test/fail_compilation/issue22826.d
  test/fail_compilation/lexer4.d
Labels: auto-merge, Easy Review, Diagnostic Messages

#13877 Fix 22915 - Print the type of invalid foreach aggregates
  src/dmd/statementsem.d
  test/fail_compilation/fail118.d
  test/fail_compilation/fail249.d
  test/fail_compilation/fail261.d
  test/fail_compilation/fail92.d
  test/fail_compilation/ice9254a.d
  test/fail_compilation/ice9254b.d
  test/fail_compilation/ice9254c.d
  test/fail_compilation/test21927.d
  test/fail_compilation/test21939.d
Labels: auto-merge, Bug Fix, Diagnostic Messages

#13882 fix Issue 22887 - ImportC: typedef enum fails
  src/dmd/cparse.d
  test/compilable/test22887.c
Labels: Bug Fix, ImportC

#13876 Use isReference instead of isRef
  src/dmd/escape.d
  src/dmd/expression.d
  src/dmd/func.d
  src/dmd/ob.d
Labels: auto-merge

#13866 ci(pre-commit): add stable branch to ci triggers
  .github/workflows/pre_commit.yml
Labels: auto-merge, Easy Review, Continuous Integration

#13881 fix Issue 22894 - importC: static struct initializer can't take addre…
  src/dmd/dinterpret.d
  test/compilable/test22894.c
Labels: Bug Fix, ImportC

#13884 backend/dwarfdbginf: fix some small codestyle issues
  src/dmd/backend/dwarfdbginf.d
Labels: Easy Review, Refactoring

#13879 backend: dwarfdbginf: refactor dwarf_func_term() abbreviations
  src/dmd/backend/dwarfdbginf.d
Labels: auto-merge, Refactoring

#13880 fix Issue 22913 - importC: array index expression parsed as cast
  src/dmd/cparse.d
  test/compilable/test22904.c
Labels: Bug Fix, ImportC

#11881 fix Issue 21324 - @live not detecting overwrite of Owner without disp…
  src/dmd/ob.d
  test/fail_compilation/fob1.d
  test/fail_compilation/fob2.d
Labels: auto-merge, Bug Fix, stalled

#13892 Merge stable into master
  .cirrus.yml
  changelog/TraitsParametersRevised.dd
  src/dmd/aggregate.d
  src/dmd/backend/cod2.d
  src/dmd/backend/machobj.d
  src/dmd/cli.d
  src/dmd/dscope.d
  src/dmd/expressionsem.d
  src/dmd/hdrgen.d
  src/dmd/mars.d
  src/dmd/mtype.d
  src/dmd/parse.d
  src/dmd/traits.d
  src/dmd/typesem.d
  test/compilable/b21285.d
  test/compilable/fix22291.d
  test/compilable/noreturn3.d
  test/compilable/test22639.d
  test/compilable/test22714.d
  test/compilable/test22859.d
  test/compilable/test22860.d
  test/compilable/transitionhelp.d
  test/fail_compilation/ice10727a.d
  test/fail_compilation/ice10727b.d
  test/runnable/test22175.d
  test/runnable/test22863.sh
Labels: auto-merge, Bug Fix

#13887 Fix 22934 - Emit context pointer as `outer` instead of `this`
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  test/compilable/dtoh_ClassDeclaration.d
Labels: auto-merge, Bug Fix, dtoh

#13895 Fix 22489 - dtoh: Handle custom mangling for functions (and globals)
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  test/compilable/dtoh_mangling.d
Labels: auto-merge, Bug Fix, dtoh

#13889 Simplify enclosesLifetimeOf
  src/dmd/declaration.d
Labels: auto-merge, dip1000

#13900 Fix Issue 22861 - build the compiler with PGO
  src/build.d
Labels: Enhancement

#13886 Avoid `init` members in backend
  src/dmd/backend/cc.d
  src/dmd/backend/cgcod.d
  src/dmd/backend/code.d
  src/dmd/backend/elfobj.d
  src/dmd/backend/obj.d
  src/dmd/glue.d
Labels: auto-merge, Refactoring

#13883 Fix Issue 11463 - DDoc html to show the normal escaped ASCII chars
  src/dmd/hdrgen.d
  src/dmd/tokens.d
  test/compilable/ddoc1.d
  test/compilable/extra-files/ddoc1.html
  test/compilable/extra-files/vcg-ast.d.cg
  test/fail_compilation/lexer1.d
Labels: Enhancement, auto-merge

#13897 Move `enclosesLifetimeOf` and `addMaybe` to escape.d
  src/dmd/declaration.d
  src/dmd/declaration.h
  src/dmd/escape.d
  src/dmd/frontend.h
Labels: auto-merge, Refactoring

#13888 Fix Issue 22919 - -checkaction=context gives "assigned to `__assertOp…
  src/dmd/escape.d
  test/compilable/test22919.d
Labels: auto-merge, Bug Fix, dip1000

#13901 fix Issue 22928 - importC: array does not have a boolean value
  src/dmd/expressionsem.d
  test/compilable/test22928.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13894 fix Issue 22924 - importC: boolean expression result should be int
  src/dmd/expressionsem.d
  test/compilable/test22924.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#13903 [REG master] dmd.func: Add setters for isNRVO and isGenerated
  src/dmd/declaration.h
  src/dmd/frontend.h
  src/dmd/func.d
  src/dmd/toir.d
Labels: Regression, GDC, auto-merge, Easy Review

#13823 frontend: make unannotated asm blocks error instead of deprecation
  changelog/deprecation_asm_stc.dd
  src/dmd/blockexit.d
  src/dmd/statementsem.d
  test/compilable/deprecate12979a.d
  test/fail_compilation/deprecate12979a.d
  test/fail_compilation/deprecate12979b.d
  test/fail_compilation/deprecate12979c.d
  test/fail_compilation/test11471.d
Labels: auto-merge, Deprecation -> Error

#13906 remove unsafe casts from constfold.d
  src/dmd/constfold.d
Labels: auto-merge, Easy Review, Refactoring

#13904 Rename `PASS.init` to `PASS.initial`
  src/dmd/aggregate.d
  src/dmd/denum.d
  src/dmd/dsymbol.d
  src/dmd/dsymbol.h
  src/dmd/dsymbolsem.d
  src/dmd/dtemplate.d
  src/dmd/expression.d
  src/dmd/expressionsem.d
  src/dmd/frontend.h
  src/dmd/func.d
  src/dmd/traits.d
  src/dmd/typesem.d
Labels: auto-merge

#13893 fix Issue 22918 - importC: some types not zero-initialized in static …
  src/dmd/denum.d
  src/dmd/dsymbolsem.d
  src/dmd/frontend.h
  src/dmd/init.h
  src/dmd/initsem.d
  src/dmd/todt.d
  src/dmd/toobj.d
  test/runnable/fix22918.c
Labels: Bug Fix, Easy Review, ImportC

#13908 ci(pre-commit): add git diff color configurations for better readability
  .github/workflows/pre_commit.yml
Labels: auto-merge, Continuous Integration

#13907 remove unsafe casts from ctfeexpr.d
  src/dmd/ctfeexpr.d
Labels: auto-merge, Easy Review, Refactoring

#13910 remove unsafe casts from traits.d
  src/dmd/traits.d
Labels: Easy Review, Refactoring

#13909 remove unsafe casts from dinterpret.d
  src/dmd/dinterpret.d
Labels: Easy Review, Refactoring

#13914 Fix 22951 - Emit non-extern (C++) destructors as private members
  changelog/dtoh-improvements.dd
  src/dmd/dtoh.d
  src/dmd/frontend.h
  test/compilable/dtoh_StructDeclaration.d
  test/dshell/extra-files/cpp_header_gen/app.cpp
  test/dshell/extra-files/cpp_header_gen/library.d
Labels: auto-merge, Bug Fix, dtoh

#13902 fix Issue 22929 - importC: extern array with unknown length gives bou…
  src/dmd/expressionsem.d
  src/dmd/optimize.d
  test/compilable/test22929.c
Labels: Blocking Other Work, Bug Fix, ImportC

#13905 dmd.func: Return false in checkNRVO for all variables with nested refs
  src/dmd/func.d
  src/dmd/toir.d
  test/runnable/nrvo.d
Labels: auto-merge, Easy Review
