Repository dlang/dmd, pull requests merged in 2022-09, with the labels that each got.

#14403 Fix Issue 23306 - @disable new() ought not disable scope A = new A
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/test23306.d
Labels: auto-merge

#14406 Refactor unittest in chkformat.d
  compiler/src/dmd/chkformat.d
Labels: auto-merge, Refactoring

#14408 Replace goto in functionResolve.applyFunction with return / nested func
  compiler/src/dmd/dtemplate.d
Labels: auto-merge

#14398 TypeFunction.callMatch: Improve structure and control flow
  compiler/src/dmd/mtype.d
Labels: auto-merge

#14411 callMatch: Remove workaround for Windows Vista
  compiler/src/dmd/mtype.d
Labels: auto-merge

#14413 Correct typo in `__builtins.di`
  druntime/src/__builtins.di
Labels: Trivial, auto-merge, Easy Review

#14402 fix Issue 22680 - @safe hole with destructors
  compiler/src/dmd/dsymbolsem.d
  compiler/test/compilable/extra-files/json.json
  compiler/test/fail_compilation/test22680.d
Labels: Blocked, Bug Fix

#14410 Clarify code around 32 bits OMF compression of symbols
  compiler/src/dmd/backend/compress.d
  druntime/src/core/demangle.d
  druntime/src/core/sys/windows/stacktrace.d
Labels: auto-merge

#14409 fix Issue 23030 - importC: errors using typedef struct after first us…
  compiler/test/compilable/test23030.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#14415 fix Issue 23327 - [ICE] SEGV in AssocArray!(Identifier, Dsymbol).AssocArray.opIndex(const(Identifier)) at src/dmd/root/aav.d:313
  compiler/src/dmd/dimport.d
  compiler/test/compilable/imports/format23327.d
  compiler/test/compilable/imports/format23327/write.d
  compiler/test/compilable/test23327.d
Labels: auto-merge, Bug Fix, Easy Review

#14416 Move tests from merge_stable PR to new test directory
  compiler/test/compilable/test21956.d
  compiler/test/compilable/test23173.d
  compiler/test/compilable/test23258.d
  compiler/test/runnable/newaa.d
  compiler/test/runnable/test23234.d
Labels: auto-merge, Easy Review

#14420 Add supplemental scope info to mixin T; errors - Fix issue 7372 - Error provides too little information to diagnose the problem (error: undefined identifier)
  compiler/src/dmd/semantic3.d
  compiler/test/fail_compilation/diag13528.d
  compiler/test/fail_compilation/fail7372.d
  compiler/test/fail_compilation/imports/fail7372.d
Labels: auto-merge

#14419 Revert "fix Issue 19662 - x86_64: Different code output when compiling with i…"
  test/runnable/test19662.d
Labels: Blocking Other Work, Easy Review

#14421 Add a missing test for typesafe variadic
  compiler/test/compilable/vararg.d
Labels: auto-merge

#14412 TypeFunction.callMatch: Extract code to match typesafe variadic argument
  compiler/src/dmd/mtype.d
Labels: auto-merge

#14422 TypeFunction.callMatch: Move parameter logic into its own function
  compiler/src/dmd/mtype.d
Labels: auto-merge

#14428 merge stable
  VERSION
  changelog/deprecate_scope_failure_return.dd
Labels: auto-merge

#14429 cirrus: Only run bootstrap pipeline on 11.x
  .cirrus.yml
  ci/README.md
Labels: auto-merge, Easy Review, Continuous Integration

#14431 ImportC merge initializer tests into one file
  compiler/test/runnable/cstuff2.c
  compiler/test/runnable/initializer.c
  compiler/test/runnable/test22994.c
Labels: Easy Review, Refactoring, ImportC

#14436 fix Issue 23230 - cannot implicitly convert expression define of type…
  compiler/test/runnable/initializer.c
Labels: auto-merge, Easy Review

#14437 fix Issue 22610 - ImportC: 3 extra initializer(s) for struct __tag21
  compiler/test/runnable/initializer.c
Labels: Bug Fix, Easy Review

#14435 fix Issue 22429 - importC: designator-list not supported yet
  compiler/test/runnable/initializer.c
Labels: Easy Review

#14439 fix Issue 23007 - importC: dmd segfaults for extra braces in array in…
  compiler/test/runnable/initializer.c
Labels: auto-merge, Bug Fix, Easy Review

#14382 Translate `_d_arraysetassign` to a template
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/test/fail_compilation/fail10968.d
  compiler/test/runnable/testassign.d
  druntime/mak/DOCS
  druntime/mak/SRCS
  druntime/src/core/internal/array/arrayassign.d
  druntime/src/object.d
  druntime/src/rt/arrayassign.d
Labels: 72h no objection -> merge

#14440 Fix up C++ headers wrt. wrong `const RootObject` mapping
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dsymbol.h
  compiler/src/dmd/expression.h
  compiler/src/dmd/module.h
  compiler/src/dmd/mtype.h
  compiler/src/dmd/root/object.h
Labels: auto-merge

#14443 fix Issue 23027 - ImportC: Array of struct is not a static and cannot…
  compiler/test/runnable/initializer.c
Labels: Easy Review, ImportC

#14444 fix Issue 22652 - importC: Braceless initializer of nested struct is …
  compiler/src/dmd/initsem.d
  compiler/test/runnable/initializer.c
Labels: ImportC

#14448 fix Issue 23338 - braceless subarray initalizers for struct fields fails
  compiler/src/dmd/initsem.d
  compiler/test/runnable/initializer.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#14451 druntime: Use X86_Any in some uClibc bindings
  druntime/src/core/stdc/math.d
  druntime/src/core/sys/posix/dlfcn.d
Labels: auto-merge, Easy Review, extern (C/C++)

#14450 druntime: Fix build for MIPS64 UClibc
  druntime/src/core/stdc/fenv.d
  druntime/src/core/stdc/math.d
  druntime/src/core/sys/posix/dlfcn.d
  druntime/src/core/sys/posix/setjmp.d
  druntime/src/core/sys/posix/sys/types.d
Labels: auto-merge, Easy Review, extern (C/C++)

#14449 refactor representsStruct()
  compiler/src/dmd/initsem.d
Labels: Easy Review, Refactoring, ImportC

#14457 ImportC: allow imports from multiple C files
  compiler/src/dmd/dsymbol.d
  compiler/test/compilable/cimports2.i
  compiler/test/compilable/imports/cimports2a.i
  compiler/test/compilable/imports/cimports2b.i
Labels: ImportC

#14455 fix Issue 23348 - not handling braceless sub structs in initializers
  compiler/src/dmd/initsem.d
  compiler/test/runnable/initializer.c
Labels: ImportC

#14458 `core.demangle`: Remove return value of `put`
  druntime/src/core/demangle.d
Labels: auto-merge

#14452 Add isUnionDeclaration method in ASTBase
  compiler/src/dmd/astbase.d
Labels: auto-merge

#14460 Fix Issue 23351 - Replace some null pointers with ErrorXYZs to stop d…
  compiler/src/dmd/parse.d
  compiler/test/compilable/segfaultgolf.d
  compiler/test/fail_compilation/e15876_1.d
  compiler/test/fail_compilation/e15876_3.d
  compiler/test/fail_compilation/e15876_4.d
  compiler/test/fail_compilation/fail17646.d
  compiler/test/fail_compilation/ice15855.d
  compiler/test/fail_compilation/misc_parser_err_cov1.d
  compiler/test/fail_compilation/test21096.d
Labels: auto-merge, Bug Fix

#14459 Fix 'the the' typos in compiler and druntime documentation
  compiler/src/dmd/doc.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/typesem.d
  compiler/src/dmd/vsoptions.d
  druntime/src/core/internal/dassert.d
  druntime/src/core/simd.d
  druntime/src/core/sys/darwin/mach/loader.d
  druntime/src/core/sys/linux/fcntl.d
  druntime/src/core/sys/posix/mqueue.d
  druntime/src/core/time.d
Labels: Trivial, auto-merge, Easy Review, documentation

#14461 fix Issue 22674 - ImportC: compatible types declared in different tra…
  compiler/src/dmd/dmangle.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/test/compilable/imports/cimports2a.i
  compiler/test/compilable/imports/cimports2b.i
  compiler/test/compilable/test22674.d
  compiler/test/fail_compilation/enumtype.c
  compiler/test/fail_compilation/enumtype2.c
Labels: Bug Fix, Easy Review, ImportC

#14463 Revert "fix Issue 19812 - nested class reference causes dangling reference to…"
  compiler/src/dmd/escape.d
  compiler/test/compilable/test19812a.d
  compiler/test/fail_compilation/test19812b.d
  druntime/src/object.d
Labels: Regression, Blocking Other Work

#14467 fix Issue 22925 - importC: multi-dimensional array is not a static an…
  compiler/test/runnable/initializer.c
Labels: Easy Review, ImportC

#14466 fix Issue 22875 - importC: cannot assign const typedef with pointers …
  compiler/test/compilable/test22875.i
Labels: Bug Fix, Easy Review, ImportC

#14465 fix 23355: invalid template parameter loses error location in some cases (T[UndefinedIdentifier] has no error loc)
  compiler/src/dmd/dtemplate.d
  compiler/test/fail_compilation/diag23355.d
Labels: Bug Fix

#14453 Add visit method for UnionDeclaration in transitivevisitor
  compiler/src/dmd/frontend.h
  compiler/src/dmd/transitivevisitor.d
Labels: auto-merge

#14454 Fix issue 21243 - Allow lambdas to return auto ref
  compiler/src/dmd/func.d
  compiler/src/dmd/parse.d
  compiler/test/compilable/test21243.d
  compiler/test/fail_compilation/fail21243.d
Labels: Enhancement, auto-merge

#14468 separate out mangleType()
  compiler/src/dmd/dmangle.d
Labels: Refactoring

#14481 fix Issue 23347 - ImportC: pragma pack causes asm label to set symbol…
  compiler/src/dmd/cparse.d
  compiler/test/runnable/test23347.c
Labels: Bug Fix, Easy Review, ImportC

#14480 fix Issue 23345 - ImportC: out of order designated initializers initi…
  compiler/src/dmd/initsem.d
  compiler/test/runnable/initializer.c
Labels: Bug Fix, Easy Review, ImportC

#14477 Revert "separate out mangleType()"
  compiler/src/dmd/dmangle.d
Labels: auto-merge

#14474 fix Issue 22973 - importC: sizeof with array and pointer access gives…
  compiler/test/compilable/test22973.i
Labels: Bug Fix, Easy Review, ImportC

#14333 CI: Switch to macOS-11 as 10.15 will be removed Aug 30th
  .github/workflows/runnable_cxx.yml
Labels: auto-merge, Continuous Integration

#14488 Move `setUnsafePreview` out of escape.d
  compiler/src/dmd/escape.d
  compiler/src/dmd/func.d
Labels: Refactoring

#14490 fix Issue 23346 - ImportC: pragma pack is not popped
  compiler/src/dmd/cparse.d
  compiler/test/compilable/test22346.c
Labels: Bug Fix, ImportC

#14487 Trivial: Turn symdebug into a boolean
  compiler/src/dmd/dmdparams.d
  compiler/src/dmd/mars.d
Labels: auto-merge-squash

#14491 Remove redundant doNotInferScope in escape.d
  compiler/src/dmd/escape.d
Labels: Easy Review, dip1000

#14493 Improve error when assigning scope variable to AA
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/fail22366.d
Labels: auto-merge, Easy Review, Diagnostic Messages, dip1000

#14495 Fix 23380 - class parameter should not be treated as ref qua lifetime
  compiler/src/dmd/escape.d
  compiler/test/compilable/test23380.d
Labels: dip1000

#14496 Use `isReturn` instead of `STC.return_` bitmask
  compiler/src/dmd/declaration.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/escape.d
  compiler/src/dmd/frontend.h
Labels: Refactoring

#14497 redo #pragma pack(pop)
  compiler/src/dmd/cparse.d
  compiler/test/compilable/pragmapack.c
  compiler/test/fail_compilation/pragma2.c
Labels: auto-merge, Easy Review, ImportC

#14498 rename mangleOverride to pMangleOverride
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/aggregate.h
  compiler/src/dmd/cppmangle.d
  compiler/src/dmd/cppmanglewin.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/frontend.h
Labels: Easy Review, Refactoring

#14484 Fix Issue 23369 - Let more symbols be imported multiple times.
  compiler/src/dmd/declaration.d
  compiler/test/compilable/imports/aliasdump.d
  compiler/test/compilable/importtests.d
Labels: Enhancement

#14506 Deduplicate logic in `implicitConvTo`
  compiler/src/dmd/dcast.d
Labels: auto-merge, Refactoring

#14505 Deduplicate `pragma(inline)` code
  compiler/src/dmd/attrib.d
  compiler/src/dmd/attrib.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/issue21378.d
  compiler/test/fail_compilation/pragmainline.d
  compiler/test/fail_compilation/pragmas.d
Labels: auto-merge, Refactoring
