Repository dlang/dmd, pull requests merged in 2023-07, with the labels that each got.

#15372 refactor flatten()
  compiler/src/dmd/statementsem.d
Labels: Easy Review, Refactoring

#15373 merge stable
  VERSION
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/escape.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/initsem.d
  compiler/src/dmd/semantic2.d
  compiler/test/compilable/test23786.c
  compiler/test/compilable/test23965.d
  compiler/test/compilable/test24013.d
  compiler/test/fail_compilation/fail22729.d
  compiler/test/fail_compilation/test21025.d
  compiler/test/fail_compilation/test23982.d
Labels: Bug Fix, stable -> master

#15312 fix Issue 18528 - dmd should deduplicate identical errors
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/fail15896.d
Labels: Bug Fix

#15378 fix Issue 24029 - ImportC: symbol name clash on statement expressions
  compiler/src/dmd/dsymbolsem.d
  compiler/test/runnable/test24029.c
Labels: Bug Fix, Easy Review, ImportC

#15377 Fix Issue 24025 - Expressions contained in parentheses should not be …
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/ccast.d
Labels: Bug Fix

#15382 [stable] Fix broken macOS CI pipelines
  ci/run.sh
Labels: auto-merge

#15387 make markinvar() a nested function
  compiler/src/dmd/backend/gloop.d
Labels: auto-merge

#15386 cgsched.d add ref where we can
  compiler/src/dmd/backend/cgsched.d
Labels: Easy Review, Refactoring

#15384 comsub() - pretregs becomes ref
  compiler/src/dmd/backend/cgcod.d
Labels: Easy Review, Refactoring

#15385 getlvalue87() - pcs becomes ref
  compiler/src/dmd/backend/cg87.d
Labels: Easy Review, Refactoring

#15383 make backend @safe by default
  compiler/src/dmd/backend/barray.d
  compiler/src/dmd/backend/blockopt.d
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cgen.d
  compiler/src/dmd/backend/cv4.d
  compiler/src/dmd/backend/debugprint.d
  compiler/src/dmd/backend/disasm86.d
  compiler/src/dmd/backend/dlist.d
  compiler/src/dmd/backend/dvec.d
  compiler/src/dmd/backend/ee.d
  compiler/src/dmd/backend/eh.d
  compiler/src/dmd/backend/fp.d
  compiler/src/dmd/backend/iasm.d
  compiler/src/dmd/backend/inliner.d
  compiler/src/dmd/backend/machobj.d
  compiler/src/dmd/backend/pdata.d
  compiler/src/dmd/backend/rtlsym.d
Labels: Easy Review, Refactoring

#15375 fix Issue 24026 - ImportC: ICE on nested C initializer 2
  compiler/src/dmd/initsem.d
  compiler/test/runnable/test23786.c
Labels: Bug Fix

#15389 fix Issue 24024 - cannot pass class this to ref class
  compiler/src/dmd/expression.d
  compiler/test/compilable/deprecate14283.d
  compiler/test/fail_compilation/diag4596.d
  compiler/test/fail_compilation/fail13116.d
Labels: Bug Fix

#15186 Fix Issue 23890 - "Warning: cannot inline function" in core.lifetime
  druntime/src/core/lifetime.d
  druntime/test/profile/Makefile
  druntime/test/profile/myprofilegc.log.freebsd.32.exp
  druntime/test/profile/myprofilegc.log.freebsd.64.exp
  druntime/test/profile/myprofilegc.log.linux.32.exp
  druntime/test/profile/myprofilegc.log.linux.64.exp
  druntime/test/profile/myprofilegc.log.osx.32.exp
  druntime/test/profile/myprofilegc.log.osx.64.exp
Labels: Enhancement, Bug Fix

#15388 parse.d: add usageOfBodyKeyword()
  compiler/src/dmd/parse.d
Labels: Easy Review, Refactoring

#15399 Fix regression introduced by #15359
  compiler/src/dmd/expressionsem.d
Labels: Regression, Easy Review

#15398 target: Rename is64bit to isX86_64
  compiler/src/dmd/cpreprocess.d
  compiler/src/dmd/dmdparams.d
  compiler/src/dmd/dmsc.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/glue.d
  compiler/src/dmd/iasmdmd.d
  compiler/src/dmd/link.d
  compiler/src/dmd/mars.d
  compiler/src/dmd/s2ir.d
  compiler/src/dmd/target.d
  compiler/src/dmd/target.h
  compiler/src/dmd/tocsym.d
  compiler/src/dmd/todt.d
  compiler/src/dmd/toir.d
  compiler/src/dmd/toobj.d
  compiler/src/tests/cxxfrontend.cc
  compiler/test/dub_package/avg.d
  compiler/test/dub_package/impvisitor.d
  compiler/test/unit/triple.d
Labels: Refactoring

#15407 Fix 24044 - Support float opCmp(...) with array
  druntime/src/core/internal/array/comparison.d
Labels: Enhancement

#15403 Improve pragma(printf) signature error message
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/format.d
Labels: Diagnostic Messages

#15392 Fix several errors parsing enum members
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/biterrors3.d
  compiler/test/fail_compilation/fail10285.d
Labels: Bug Fix

#15410 Fix Issue 7184 - parse error on *(x)++
  compiler/src/dmd/parse.d
  compiler/test/compilable/parens_inc.d
Labels: Bug Fix

#15406 Fix Issues 23951 and 23279 - traits(hasMember) does not follow alias this + ICE when using traits(hasMember) on an erroneous member
  compiler/src/dmd/traits.d
  compiler/test/compilable/test23951.d
  compiler/test/fail_compilation/test23279.d
Labels: Bug Fix

#15405 Fix Issue 13063 - `enum` is allowed as storage class for functions
  changelog/dmd.enum-function.dd
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/enum_function.d
  compiler/test/fail_compilation/fail22729.d
Labels: Bug Fix

#15404 Fix Issue 22427 - betterC: casting an array causes linker error in string comparison
  compiler/src/dmd/mars.d
  compiler/test/runnable/betterc.d
Labels: Regression, Bug Fix

#15417 merge stable
  VERSION
  compiler/src/dmd/cparse.d
  compiler/src/dmd/func.d
  compiler/src/dmd/initsem.d
  compiler/src/dmd/traits.d
  compiler/src/dmd/visitor.h
  compiler/test/compilable/cppmangle.d
  compiler/test/compilable/imports/imp24022.c
  compiler/test/compilable/test23951.d
  compiler/test/compilable/test23966.d
  compiler/test/compilable/test24022.d
  compiler/test/fail_compilation/test23279.d
  compiler/test/runnable/test23786.c
  druntime/src/core/lifetime.d
  druntime/test/profile/Makefile
  druntime/test/profile/bothgc.log.exp
  druntime/test/profile/myprofilegc.log.freebsd.32.exp
  druntime/test/profile/myprofilegc.log.freebsd.64.exp
  druntime/test/profile/myprofilegc.log.linux.32.exp
  druntime/test/profile/myprofilegc.log.linux.64.exp
  druntime/test/profile/myprofilegc.log.osx.32.exp
  druntime/test/profile/myprofilegc.log.osx.64.exp
Labels: Bug Fix, stable -> master

#15418 merge stable
  VERSION
Labels: stable -> master

#15416 use an array for casevals rather than a pointer
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/common/string.d
Labels: Easy Review, Refactoring

#15414 refactor FeatureState
  compiler/src/dmd/errors.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/globals.d
  compiler/src/dmd/globals.h
  compiler/src/dmd/semantic3.d
Labels: Easy Review, Refactoring

#15419 use SmallBuffer in optim_loglog()
  compiler/src/dmd/backend/cgelem.d
Labels: Easy Review, Refactoring

#15350 Fix Issue 11455 - Overriding template methods should raise a compile …
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/template_function_oop.d
Labels: Bug Fix

#15412 Use import for `dmd.backend.out : outdata`
  compiler/src/dmd/backend/dt.d
  compiler/src/dmd/backend/global.d
Labels: Refactoring, Backend

#15423 [stable] Add changelog for catch qualifier deprecation & update release no
  changelog/dmd.catch-immutable.dd
  compiler/src/dmd/statementsem.d
Labels: auto-merge, Easy Review

#15426 dmd.clone: Use global.params.useExceptions as gate instead of betterC
  compiler/src/dmd/clone.d
Labels: Easy Review, BetterC

#15425 dmd.errors: Merge the 'v*' and 'v*Supplemental' routines.
  compiler/src/dmd/astbase.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/errors.d
  compiler/src/dmd/errors.h
  compiler/src/dmd/expression.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/iasmdmd.d
  compiler/src/dmd/lib.d
  compiler/src/dmd/statement.d
Labels: GDC, Diagnostic Messages

#15397 [dmd/parse] Refactor enum declaration
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/biterrors3.d
  compiler/test/fail_compilation/enum_member.d
  compiler/test/fail_compilation/fail10285.d
  compiler/test/fail_compilation/fail20538.d
  compiler/test/fail_compilation/failcontracts.d
  compiler/test/fail_compilation/test9701.d
Labels: Bug Fix

#15430 Improve "need `this`" error
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/bug8891.d
  compiler/test/fail_compilation/diag15209.d
  compiler/test/fail_compilation/diag9635.d
  compiler/test/fail_compilation/fail11545.d
  compiler/test/fail_compilation/fail120.d
  compiler/test/fail_compilation/fail143.d
  compiler/test/fail_compilation/fail17955.d
  compiler/test/fail_compilation/fail25.d
  compiler/test/fail_compilation/fail301.d
  compiler/test/fail_compilation/fail46.d
  compiler/test/fail_compilation/fail50.d
  compiler/test/fail_compilation/fail61.d
  compiler/test/fail_compilation/fail7851.d
  compiler/test/fail_compilation/ice15332.d
  compiler/test/fail_compilation/ice15922.d
  compiler/test/fail_compilation/ice20056.d
  compiler/test/fail_compilation/ice7645.d
  compiler/test/fail_compilation/ice9439.d
  compiler/test/fail_compilation/test21008.d
Labels: Diagnostic Messages

#15441 refactor genrnd() and getemptyslot()
  compiler/src/dmd/backend/cg87.d
Labels: Easy Review, Refactoring

#15442 refactor getemptyslot()
  compiler/src/dmd/backend/cg87.d
Labels: Easy Review, Refactoring

#15445 use out parameter with reghasvalue()
  compiler/src/dmd/backend/cgen.d
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/cod2.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/cod4.d
Labels: Easy Review, Refactoring

#15448 modernize codgen() a little bit
  compiler/src/dmd/backend/cgcod.d
Labels: Easy Review, Refactoring

#15447 fix Issue 23857 - backend inliner takes too long on recursive functio…
  compiler/src/dmd/backend/go.d
  compiler/src/dmd/backend/inliner.d
  compiler/test/compilable/test23857.d
Labels: Bug Fix

#15446 use out with regwithvalue()
  compiler/src/dmd/backend/cg87.d
  compiler/src/dmd/backend/cgen.d
  compiler/src/dmd/backend/cgxmm.d
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/cod2.d
  compiler/src/dmd/backend/cod4.d
Labels: Easy Review, Refactoring

#15449 refactor isregvar() to use out
  compiler/src/dmd/backend/cgcod.d
  compiler/src/dmd/backend/cgxmm.d
  compiler/src/dmd/backend/cod2.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/cod4.d
Labels: Easy Review, Refactoring

#15450 switch andregcon() from pointer to ref
  compiler/src/dmd/backend/cgcod.d
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/cod2.d
Labels: Easy Review, Refactoring

#15439 Fix 24054 - return expression expected on noreturn function
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/noreturn2.d
Labels: Bug Fix, Diagnostic Messages

#15438 Reduce quotes clutter on ctfe assert failure
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/fail144.d
  compiler/test/fail_compilation/fail145.d
  compiler/test/fail_compilation/noreturn.d
Labels: Diagnostic Messages

#15452 pass MiniCodeBuf by ref
  compiler/src/dmd/backend/cod3.d
Labels: Easy Review, Refactoring

#15451 docommas(): use ref
  compiler/src/dmd/backend/cg87.d
  compiler/src/dmd/backend/cgcod.d
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/cod2.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/cod4.d
Labels: Easy Review, Refactoring

#15453 Fix 24055 - is(x == __parameters) does not work on function pointers
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/test24055.d
Labels: Bug Fix

#15455 Revive "Backend: Cleanup dlist"
  compiler/src/dmd/backend/dlist.d
Labels: Refactoring, Backend

#15456 use ref uev instead of uev*
  compiler/src/dmd/backend/cod3.d
Labels: Easy Review, Refactoring

#15454 Remove dead code from backend
  compiler/src/dmd/backend/cdef.d
  compiler/src/dmd/backend/cgen.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/code.d
  compiler/src/dmd/backend/dout.d
  compiler/src/dmd/backend/elfobj.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/machobj.d
  compiler/src/dmd/backend/mscoffobj.d
Labels: Refactoring, Backend

#15457 make FL a ubyte
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/code_x86.d
  compiler/src/dmd/backend/el.d
Labels: Easy Review, Refactoring

#15459 [CI] Remove unused local variables
  compiler/src/dmd/backend/cod4.d
Labels: Refactoring, Backend

#15434 Fix 24051 - Safety attrib inference of enum/immut/const decls
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/func.d
  compiler/src/dmd/semantic2.d
  compiler/test/fail_compilation/systemvariables_var_init.d
  druntime/src/core/sys/windows/winbase.d
Labels: Bug Fix

#15391 change deprecation of scope constructor to warning
  compiler/src/dmd/dsymbolsem.d
  compiler/test/compilable/test23145.d
Labels: Easy Review

#15460 Add `@safe` to frontend functions
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/argtypes_sysv_x64.d
  compiler/src/dmd/cli.d
  compiler/src/dmd/cond.d
  compiler/src/dmd/constfold.d
  compiler/src/dmd/cppmangle.d
  compiler/src/dmd/cppmanglewin.d
  compiler/src/dmd/ctfeexpr.d
  compiler/src/dmd/ctorflow.d
  compiler/src/dmd/dclass.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/dmangle.d
  compiler/src/dmd/dmdparams.d
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dmsc.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/dscope.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/dtoh.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/globals.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/iasmdmd.d
  compiler/src/dmd/id.d
  compiler/src/dmd/imphint.d
  compiler/src/dmd/init.d
  compiler/src/dmd/inline.d
  compiler/src/dmd/inlinecost.d
  compiler/src/dmd/intrange.d
  compiler/src/dmd/json.d
  compiler/src/dmd/libmscoff.d
  compiler/src/dmd/link.d
  compiler/src/dmd/location.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/ob.d
  compiler/src/dmd/objc.d
  compiler/src/dmd/objc_glue.d
  compiler/src/dmd/opover.d
  compiler/src/dmd/printast.d
  compiler/src/dmd/root/complex.d
  compiler/src/dmd/root/utf.d
  compiler/src/dmd/s2ir.d
  compiler/src/dmd/semantic2.d
  compiler/src/dmd/semantic3.d
  compiler/src/dmd/statement.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/target.d
  compiler/src/dmd/templateparamsem.d
  compiler/src/dmd/tocsym.d
  compiler/src/dmd/toctype.d
  compiler/src/dmd/tocvdebug.d
  compiler/src/dmd/toir.d
  compiler/src/dmd/toobj.d
Labels: Refactoring

#15465 more typesafe code in codebuilder.d
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/cod4.d
  compiler/src/dmd/backend/codebuilder.d
  compiler/src/dmd/common/outbuffer.d
  compiler/src/dmd/iasmdmd.d
Labels: Easy Review, Refactoring

#15466 Fix 8662 - Better error for duplicate labels inside static foreach body
  compiler/src/dmd/frontend.h
  compiler/src/dmd/statement.d
  compiler/src/dmd/statement.h
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/test8662.d
Labels: Bug Fix

#15467 Fix 21520 - dmd does not honor the NO_COLOR environment variable
  compiler/src/dmd/console.d
  compiler/src/dmd/globals.d
Labels: Enhancement

#15462 Add `@safe` to frontend functions 2
  compiler/src/dmd/aliasthis.d
  compiler/src/dmd/arrayop.d
  compiler/src/dmd/backend/disasm86.d
  compiler/src/dmd/compiler.d
  compiler/src/dmd/cond.d
  compiler/src/dmd/console.d
  compiler/src/dmd/cppmangle.d
  compiler/src/dmd/ctorflow.d
  compiler/src/dmd/dscope.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dversion.d
  compiler/src/dmd/errors.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/foreachvar.d
  compiler/src/dmd/func.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/identifier.d
  compiler/src/dmd/inlinecost.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/location.d
  compiler/src/dmd/nogc.d
  compiler/src/dmd/sapply.d
  compiler/src/dmd/statement.d
  compiler/src/dmd/tokens.d
  compiler/src/dmd/visitor.d
Labels: Refactoring

#15458 Fix 24056 - const uninitialized data at module scope is not in TLS
  changelog/dmd.shared-static-ctor-const.dd
  compiler/src/dmd/declaration.d
  compiler/src/dmd/mustuse.d
  compiler/test/fail_compilation/fail4923.d
  compiler/test/fail_compilation/fail66.d
  compiler/test/runnable/template9.d
  compiler/test/runnable/test20.d
  compiler/test/runnable/test3449.d
  compiler/test/runnable/test42.d
  compiler/test/runnable/testassign.d
  compiler/test/runnable/testconst.d
  compiler/test/runnable/testswitch.d
Labels: Bug Fix, Deprecation

#15469 Add `@safe` to frontend functions 3
  compiler/src/dmd/attrib.d
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/cli.d
  compiler/src/dmd/common/outbuffer.d
  compiler/src/dmd/cond.d
  compiler/src/dmd/ctfeexpr.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/delegatize.d
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/dtoh.d
  compiler/src/dmd/dversion.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/inline.d
  compiler/src/dmd/mars.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/postordervisitor.d
  compiler/src/dmd/root/filename.d
  compiler/src/dmd/root/rmem.d
  compiler/src/dmd/sideeffect.d
  compiler/src/dmd/statement.d
  compiler/src/dmd/target.d
Labels: Refactoring

#15471 doc.d: use errorSink
  compiler/src/dmd/doc.d
  compiler/src/dmd/dscope.d
  compiler/src/dmd/errors.d
  compiler/src/dmd/errorsink.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/mars.d
  compiler/src/dmd/scope.h
  compiler/src/dmd/semantic3.d
Labels: Easy Review, Refactoring

#15475 use ErrorSink in s2ir.d and e2ir.d
  compiler/src/dmd/console.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/s2ir.d
  compiler/src/dmd/toir.d
Labels: Easy Review, Refactoring

#15474 make ErrorSink available to all users of sc
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/dscope.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/semantic2.d
  compiler/src/dmd/semantic3.d
Labels: Easy Review, Refactoring

#15476 use eSink in toir.d
  compiler/src/dmd/toir.d
Labels: Easy Review, Refactoring
