Repository dlang/dmd, pull requests merged in 2023-08, with the labels that each got.

#15483 convert objrecord() to using []
  compiler/src/dmd/backend/cgobj.d
Labels: Easy Review, Refactoring

#15484 elfobj writes: use arrays
  compiler/src/dmd/backend/elfobj.d
Labels: Easy Review, Refactoring

#15485 use size_t in bytes(), array in addstr()
  compiler/src/dmd/backend/cgobj.d
  compiler/src/dmd/backend/elfobj.d
  compiler/src/dmd/backend/machobj.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/backend/obj.d
Labels: Easy Review, Refactoring

#15486 Use ref IRState instead of pointer
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/s2ir.d
  compiler/src/dmd/toir.d
Labels: Easy Review, Refactoring

#15481 obj_includelib parameter to slice
  compiler/src/dmd/backend/cgobj.d
  compiler/src/dmd/backend/elfobj.d
  compiler/src/dmd/backend/machobj.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/backend/obj.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/toobj.d
Labels: Easy Review, Refactoring

#15488 remove some dyncast calls
  compiler/src/dmd/declaration.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/dscope.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/func.d
  compiler/src/dmd/nogc.d
  compiler/src/dmd/typesem.d
Labels: Easy Review, Refactoring

#15461 Make non-scope constructor a DIP1000 error
  changelog/dmd.scope-ctor-error.dd
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/escape.d
  compiler/test/compilable/test23145.d
  compiler/test/fail_compilation/test23145.d
Labels: auto-merge

#15472 split off main.d from mars.d
  compiler/src/build.d
  compiler/src/dmd/README.md
  compiler/src/dmd/main.d
  compiler/src/dmd/mars.d
Labels: Refactoring

#15489 Fix Issue 24061 - constructor with assert(0) failed to compile
  compiler/src/dmd/semantic3.d
  compiler/test/compilable/test24061.d
Labels: Bug Fix

#15492 merge stable
  VERSION
  changelog/dmd.alias-this-syntax.dd
  changelog/dmd.enum-function.dd
  changelog/dmd.extern-c-overload.dd
  changelog/dmd.private-deprecation-error.dd
  changelog/dmd.visionos-version-identifier.dd
  changelog/druntime.input-headers.dd
  changelog/druntime.valgrind.dd
  compiler/src/dmd/backend/go.d
  compiler/src/dmd/backend/inliner.d
  compiler/test/compilable/test23857.d
Labels: auto-merge, Bug Fix

#15491 change write_bytes() to use array parameter
  compiler/src/dmd/backend/cgobj.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/dcgcv.d
  compiler/src/dmd/backend/dout.d
  compiler/src/dmd/backend/elfobj.d
  compiler/src/dmd/backend/machobj.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/backend/obj.d
  compiler/src/dmd/tocvdebug.d
Labels: Refactoring

#15494 Fix Issue 24065 - __traits(getTargetInfo) causes a segfault when pass…
  compiler/src/dmd/traits.d
  compiler/test/fail_compilation/test24065.d
Labels: auto-merge, Bug Fix

#15496 Delete unused imports part2
  compiler/src/dmd/access.d
  compiler/src/dmd/aliasthis.d
  compiler/src/dmd/arrayop.d
  compiler/src/dmd/attrib.d
  compiler/src/dmd/blockexit.d
  compiler/src/dmd/builtin.d
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/compiler.d
  compiler/src/dmd/mars.d
Labels: auto-merge

#14827 fix issue 20655 - attribute inference accepts unsafe union access as @safe
  compiler/src/dmd/backend/gloop.d
  compiler/src/dmd/safe.d
  compiler/test/fail_compilation/test20655.d
  druntime/src/core/stdcpp/string.d
Labels: auto-merge, Bug Fix

#15495 Fix Issue 24066 - __traits(isAbstractClass) causes a segfault when passed an opaque class
  compiler/src/dmd/dclass.d
  compiler/test/compilable/test24066.d
Labels: Bug Fix

#15497 Delete unused imports part3
  compiler/src/dmd/cppmangle.d
  compiler/src/dmd/cppmanglewin.d
  compiler/src/dmd/cpreprocess.d
Labels: auto-merge

#15498 Delete unused imports part4
  compiler/src/dmd/ctfeexpr.d
  compiler/src/dmd/dcast.d
  compiler/src/dmd/dclass.d
Labels: auto-merge

#15500 Add changelog for #15493
  changelog/druntime.gc-collect-safe.dd
Labels: auto-merge

#15502 fix Issue 23958 - ImportC: undefined identifier __builtin__sprintf_chk
  compiler/test/compilable/test23958.c
  druntime/src/importc.h
Labels: Enhancement, Easy Review, ImportC

#15509 detab main.d
  compiler/src/dmd/main.d
Labels: Trivial, auto-merge, Refactoring

#15431 Add location field to class Parameter
  compiler/src/dmd/clone.d
  compiler/src/dmd/cond.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/mtype.h
  compiler/src/dmd/parse.d
  compiler/src/dmd/semantic3.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/typesem.d
  compiler/src/tests/cxxfrontend.cc
Labels: GDC, auto-merge, Refactoring

#15507 only call ctime() once and not in gendocfile()
  compiler/src/dmd/doc.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.d
  compiler/src/dmd/globals.h
  compiler/src/dmd/main.d
Labels: Easy Review, Refactoring

#15506 readFile(): there can be only one
  compiler/src/dmd/doc.d
  compiler/src/dmd/utils.d
Labels: Easy Review, Refactoring

#15499 Delete unused imports part5
  compiler/src/dmd/declaration.d
  compiler/src/dmd/delegatize.d
  compiler/src/dmd/denum.d
  compiler/src/dmd/dinifile.d
  compiler/src/dmd/dinterpret.d
Labels: auto-merge

#15508 bubble errors up from writeFile()
  compiler/src/dmd/doc.d
  compiler/src/dmd/dtoh.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/lib.d
  compiler/src/dmd/link.d
  compiler/src/dmd/main.d
  compiler/src/dmd/mars.d
  compiler/src/dmd/utils.d
Labels: Easy Review, Refactoring

#15503 move DDOCFILE from doc.d to main.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/main.d
  compiler/src/dmd/mars.d
Labels: auto-merge

#15514 remove file I/O from hdrgen.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/main.d
Labels: auto-merge, Easy Review, Refactoring

#15517 Fix 24036 - assert message in CTFE becomes `['m', 'e'`...
  compiler/src/dmd/dinterpret.d
  compiler/test/fail_compilation/test24036.d
Labels: auto-merge, Bug Fix, Diagnostic Messages

#15513 no need to add default macros to ddoc files
  compiler/src/dmd/doc.d
Labels: Easy Review, Refactoring

#15515 use ref's for json.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/json.d
  compiler/src/dmd/main.d
  compiler/src/dmd/mars.d
Labels: Easy Review, Refactoring

#15519 Fix Issue 24079 - core.sys.windows.winnt.IMAGE_FIRST_SECTION returns bad pointer
  druntime/src/core/sys/windows/winnt.d
Labels: Bug Fix

#15522 make equals() nothrow
  compiler/src/.dscanner.ini
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/func.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/root/rootobject.d
Labels: auto-merge, Easy Review, Refactoring

#15518 Fix 24070 - Opaque struct with nested definition when taking pointer …
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/testcstuff2.c
Labels: auto-merge, Bug Fix, ImportC

#15523 Revert "make equals() nothrow"
  compiler/src/.dscanner.ini
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/func.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/root/rootobject.d
Labels: GDC, Blocking Other Work, auto-merge

#15530 etc.linux.memoryerror: add nothrow
  druntime/src/etc/linux/memoryerror.d
Labels: Easy Review, Refactoring, auto-merge-squash

#15512 Tweak switch skipping variable errors
  compiler/src/dmd/statement.d
  compiler/test/fail_compilation/skip.d
  compiler/test/fail_compilation/switch_skip.d
  compiler/test/fail_compilation/switches.d
Labels: auto-merge, Diagnostic Messages

#15527 Improve expected `;` after expression error
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/fail136.d
  compiler/test/fail_compilation/fail196.d
  compiler/test/fail_compilation/fail22529.d
  compiler/test/fail_compilation/ice11982.d
  compiler/test/fail_compilation/misc_parser_err_cov1.d
  compiler/test/fail_compilation/parseStc.d
Labels: auto-merge

#15529 Use separate line for extra Loc in various error messages
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/opover.d
  compiler/src/dmd/statement.d
  compiler/test/fail_compilation/fail1900.d
  compiler/test/fail_compilation/goto_skip.d
  compiler/test/fail_compilation/ice11518.d
  compiler/test/fail_compilation/main.d
  compiler/test/fail_compilation/testOpApply.d
Labels: Enhancement

#15532 escape.d: mark everything public or private
  compiler/src/dmd/escape.d
Labels: auto-merge, Easy Review, Refactoring

#15525 move ddoc file reads out of doc.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/main.d
Labels: Easy Review, Refactoring

#15528 Improve expected `}` error after aggregate members
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/diag13609a.d
  compiler/test/fail_compilation/fail17570.d
  compiler/test/fail_compilation/fnconstraint.d
  compiler/test/fail_compilation/testsemi.d
Labels: auto-merge-squash

#15511 Discriminate between different kinds of warnings
  compiler/src/dmd/astbase.d
  compiler/src/dmd/blockexit.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/dscope.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/dtoh.d
  compiler/src/dmd/errors.d
  compiler/src/dmd/errors.h
  compiler/src/dmd/errorsink.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/inline.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/sideeffect.d
  compiler/src/dmd/statement.d
  compiler/src/dmd/statement.h
  compiler/src/dmd/statementsem.d
Labels: GDC, Diagnostic Messages

#15533 [stable] Make enum function a deprecation, not an error
  changelog/dmd.enum-function.dd
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/enum_function.d
Labels: auto-merge-squash

#15535 doc.d: move file writes to caller
  compiler/src/dmd/doc.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/main.d
Labels: auto-merge, Refactoring

#15505 add eSink to library file generation
  compiler/src/dmd/glue.d
  compiler/src/dmd/lib.d
  compiler/src/dmd/libelf.d
  compiler/src/dmd/libmach.d
  compiler/src/dmd/libmscoff.d
  compiler/src/dmd/libomf.d
Labels: Easy Review, Refactoring

#15538 move file writes out of lib.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/lib.d
  compiler/src/dmd/libelf.d
  compiler/src/dmd/libmach.d
  compiler/src/dmd/libmscoff.d
  compiler/src/dmd/libomf.d
Labels: auto-merge, Easy Review, Refactoring

#15542 Fix Issue 24088 - Nested functions using the shortened syntax were no…
  compiler/src/dmd/parse.d
  compiler/test/compilable/shortened_methods.d
Labels: auto-merge, Bug Fix

#15536 fix Issue 24084 - Add -nothrow Switch to Compiler
  changelog/dmd.fix24084.dd
  compiler/src/dmd/cli.d
  compiler/src/dmd/mars.d
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/test24084.d
Labels: Enhancement, Easy Review

#15543 Fix Issue 24078 - Fold constants on array concatenation only for strings
  compiler/src/dmd/optimize.d
  compiler/test/runnable/test24078.d
Labels: auto-merge, Bug Fix

#15545 use eSink in scan*.d modules
  compiler/src/dmd/libelf.d
  compiler/src/dmd/libmach.d
  compiler/src/dmd/libmscoff.d
  compiler/src/dmd/libomf.d
  compiler/src/dmd/scanelf.d
  compiler/src/dmd/scanmach.d
  compiler/src/dmd/scanmscoff.d
  compiler/src/dmd/scanomf.d
Labels: Easy Review, Refactoring

#15551 ImportC: better diagnostic for malformed __declspec
  compiler/src/dmd/cparse.d
  compiler/test/fail_compilation/msg24094.c
Labels: auto-merge, Easy Review, Diagnostic Messages, ImportC

#15552 overloads of toSymbol() belong in one module
  compiler/src/dmd/glue.d
  compiler/src/dmd/tocsym.d
Labels: Easy Review, Refactoring

#15546 glue.d: make public functions greppable
  compiler/src/dmd/glue.d
Labels: auto-merge, Easy Review, Refactoring

#15555 Fix Issue 24106 - core.stdc.math provides an implementation of modfl for uClibc that only works when real and double are the same size
  druntime/src/core/stdc/math.d
Labels: auto-merge, Bug Fix

#15554 move errorSinkNull to globals.d
  compiler/src/dmd/errors.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.d
  compiler/src/dmd/globals.h
Labels: Easy Review, Refactoring

#15553 fix Issue 24105 - Dip1000 C variadics not marked as scope should not …
  compiler/src/dmd/escape.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/test/fail_compilation/test24015.d
Labels: Bug Fix, Easy Review, dip1000

#15557 Fix #24108 - segfault when using -H or -X on importC
  compiler/src/dmd/hdrgen.d
  compiler/test/compilable/jsonc.i
Labels: Bug Fix, auto-merge-squash

#15547 modernize scanomf.d
  compiler/src/dmd/libomf.d
  compiler/src/dmd/scanomf.d
Labels: auto-merge, Easy Review, Refactoring

#15563 Add WinAPI Annotations to importc.h
  druntime/src/importc.h
Labels: auto-merge

#15562 Fix Issue 24117 - noreturn can be used as expression
  compiler/src/dmd/dcast.d
  compiler/test/fail_compilation/noreturn_expr.d
  compiler/test/fail_compilation/noreturn_expr2.d
Labels: Bug Fix

#15559 [stable] druntime: Fix malloc-leaks in ModuleGroup.sortCtors()
  druntime/src/rt/minfo.d
Labels: stable-stalled
