Repository dlang/dmd, pull requests merged in 2023-04, with the labels that each got.

#15058 change ESCAPE from flag to bool
  compiler/src/dmd/cppmanglewin.d
Labels: auto-merge, Easy Review, Refactoring

#15061 Deduplicate function/template branches in aliasthisOf
  compiler/src/dmd/mtype.d
Labels: auto-merge, Easy Review, Refactoring

#15066 merge stable
  VERSION
  changelog/dmd.check.dd
  changelog/dmd.deprecate-alias-this-for-classes.dd
  changelog/dmd.dip25-default.dd
  changelog/dmd.extern-dllimport.dd
  changelog/dmd.get-is-virtual-function.dd
  compiler/src/dmd/declaration.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/gluelayer.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/target.d
  compiler/src/dmd/target.h
  compiler/src/tests/cxxfrontend.cc
  compiler/test/compilable/shared.d
  compiler/test/compilable/test22674.d
  compiler/test/compilable/test23799.d
  compiler/test/fail_compilation/cerrors.d
  compiler/test/fail_compilation/shared.d
  compiler/test/runnable/complex3.d
  druntime/src/core/sys/freebsd/config.d
Labels: auto-merge, Bug Fix, stable -> master

#15067 cppmangle.d: eliminate many unsafe casts
  compiler/src/dmd/cppmangle.d
Labels: auto-merge, Easy Review, Refactoring

#15064 Don't store recursive alias this type in `UnaExp`
  compiler/src/dmd/aliasthis.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/mtype.d
  compiler/src/dmd/opover.d
Labels: Refactoring

#15070 change & SC.global to ==
  compiler/src/dmd/toobj.d
Labels: Easy Review

#15060 Fix Issue 23816 - Typing invalid mnemonic in asm{} block segfaults
  compiler/src/dmd/backend/dvarstats.d
  compiler/src/dmd/backend/ptrntab.d
  compiler/test/fail_compilation/fail23816.d
Labels: Bug Fix

#15072 Turn semicolon as empty statement into an error
  changelog/dmd.empty-statement-error.dd
  compiler/src/dmd/cparse.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/fail4559.d
Labels: Deprecation -> Error

#15069 fix Issue 23014 - importC: static thread-locals do not work
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/elfobj.d
  compiler/src/dmd/backend/elpicpie.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/tokens.d
  compiler/src/dmd/tokens.h
  compiler/src/dmd/toobj.d
  compiler/test/runnable/imports/imp23014.i
  compiler/test/runnable/test23014.i
  compiler/test/unit/lexer/location_offset.d
Labels: Bug Fix

#15068 fix Issue 22559 - ImportC: support gnu case ranges
  compiler/src/dmd/cparse.d
  compiler/test/compilable/test22559.i
Labels: Enhancement, auto-merge, Easy Review, ImportC

#15077 Fix issue 23822: Check for deprecation before resolving alias on struct type member access.
  compiler/src/dmd/typesem.d
  compiler/test/fail_compilation/fail23822.d
Labels: Bug Fix

#15080 Remove unsafe Expression casts in dtemplate.d
  compiler/src/dmd/dtemplate.d
Labels: Refactoring

#15002 Deprecate invalid `#` tokens in `q{}` strings
  changelog/dmd.deprecate-pound-in-token-string.dd
  compiler/src/dmd/lexer.d
  compiler/test/fail_compilation/cerrors.d
  compiler/test/unit/lexer/diagnostic_reporter.d
Labels: stable-stalled, Deprecation

#15024 Fix issue 11989 -- deprecate TickDuration, it's no longer used anywhere.
  compiler/test/runnable/testpdb.d
  druntime/src/core/time.d
Labels: Enhancement

#15078 Fix issue 23826: Check for deprecation when passing type member as template argument.
  compiler/src/dmd/typesem.d
  compiler/test/fail_compilation/fail23826.d
Labels: Bug Fix

#15076 Fix Issue 18493 - [betterC] Can't use aggregated type with postblit
  compiler/src/dmd/clone.d
  compiler/test/compilable/test18493.d
Labels: Bug Fix, 72h no objection -> merge

#15088 Fix Issue 23832 - dmd regression 2.103.0 silent error cannot call decode at runtime
  compiler/src/dmd/typinf.d
Labels: Bug Fix

#15091 parse.d: remove more dependencies on globals.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.h
  compiler/src/dmd/lexer.d
  compiler/src/dmd/mars.d
  compiler/src/dmd/parse.d
Labels: Easy Review, Refactoring

#15090 Parser: rewrite constructor in terms of another
  compiler/src/dmd/parse.d
Labels: Easy Review, Refactoring

#15055 better missing ; error message
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/fail196.d
  compiler/test/fail_compilation/ice11982.d
  compiler/test/fail_compilation/misc_parser_err_cov1.d
  compiler/test/fail_compilation/parseStc.d
Labels: auto-merge

#15047 ImportC: support __attribute__((aligned(N)))
  compiler/src/dmd/cparse.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/test/compilable/imports/c23789.i
  compiler/test/compilable/test23789.d
  compiler/test/fail_compilation/alignedext.i
  compiler/test/fail_compilation/test23789.c
Labels: Easy Review, ImportC

#15092 parse.d: remove dependence on globals.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/typesem.d
Labels: Easy Review, Refactoring

#15093 fix Issue 23509 - ImportC: need statement expressions extension
  compiler/src/dmd/cparse.d
  compiler/src/dmd/hdrgen.d
  compiler/test/compilable/test23509.i
Labels: Bug Fix, Easy Review, ImportC

#15094 fix Issue 23715 - ImportC: No rejection of _Thread_local variables de…
  compiler/src/dmd/cparse.d
  compiler/test/compilable/testcstuff1.c
  compiler/test/fail_compilation/test23715.i
Labels: Bug Fix, Easy Review, ImportC

#15048 ImportC: support dllimport, dllexport, naked attributes
  compiler/src/dmd/cparse.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/tocsym.d
  compiler/test/compilable/cattributes.i
Labels: Easy Review, ImportC

#15103 ImportC: support noinline
  compiler/src/dmd/cparse.d
  compiler/src/dmd/id.d
  compiler/test/compilable/testnoinline.c
Labels: Easy Review, ImportC

#15102 ImportC: predefine _NO_CRT_STDIO_INLINE
  druntime/src/importc.h
Labels: Easy Review, ImportC

#15097 Fix Issue 22857 - Segfault for malformed static if in imported template
  compiler/src/dmd/cond.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/fail17646.d
  compiler/test/fail_compilation/fail22857.d
  compiler/test/fail_compilation/imports/import22857.d
  compiler/test/fail_compilation/test21164.d
Labels: Bug Fix

#15098 Fix Issue 22739 - Segmentation fault in CppMangleVisitor.headOfType
  compiler/src/dmd/cppmangle.d
  compiler/test/compilable/test22739.d
Labels: Bug Fix

#15100 Fix Issue 22765 - Assertion failure in CppMangleVisitor.template_args
  compiler/src/dmd/cppmangle.d
  compiler/test/fail_compilation/test22765.d
Labels: Bug Fix

#15104 Fix Issue 23836 - Two errors printed for typeof(super) in non-static member context
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/fail_typeof.d
Labels: Bug Fix, Easy Review

#15101 fix Issue 23402 - importc function definitions from includes can caus…
  compiler/src/dmd/expressionsem.d
  compiler/test/runnable/imports/imp23402a.c
  compiler/test/runnable/imports/imp23402b.c
  compiler/test/runnable/test23402.d
Labels: Bug Fix, Easy Review, ImportC

#15110 fix Issue 23427 - ImportC: some bitfield combinations lead to wrong s…
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/declaration.d
  compiler/test/compilable/posixbitfields.c
Labels: Bug Fix, Easy Review, ImportC

#14561 Fix 21667 - scope parameter causes 'no size because of forward refere…
  compiler/src/dmd/typesem.d
  compiler/test/compilable/test21667.d
  compiler/test/fail_compilation/previewin.d
  compiler/test/fail_compilation/testrvaluecpctor.d
  compiler/test/runnable/mangle.d
Labels: Bug Fix, stalled, dip1000

#15106 Fix Issue 23838 - DMD lexer / parser examples might not compile
  compiler/test/dub_package/avg.d
  compiler/test/dub_package/frontend.d
  compiler/test/dub_package/frontend_file.d
  compiler/test/dub_package/impvisitor.d
  compiler/test/dub_package/lexer.d
  compiler/test/dub_package/parser.d
  compiler/test/dub_package/retrieveScope.d
  dub.sdl
Labels: Bug Fix

#15107 fix Issue 22960 - importC: K&R-style functions assume variadic callin…
  compiler/src/dmd/astbase.d
  compiler/src/dmd/astenums.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/glue.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/inline.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/traits.d
  compiler/test/compilable/cvariadic.i
Labels: Bug Fix, ImportC

#15112 fix Issue 23401 - ImportC: add -cpp=filename switch to select C prepr…
  compiler/src/dmd/cli.d
  compiler/src/dmd/cpreprocess.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.d
  compiler/src/dmd/globals.h
  compiler/src/dmd/mars.d
Labels: Enhancement, Easy Review, ImportC

#15116 Infer `scope` only on parameters with pointers
  compiler/src/dmd/escape.d
Labels: dip1000

#15124 Don't build backend with `-betterC`
  compiler/src/build.d
Labels: Backend

#15118 Fix Issue 22765 for windows
  compiler/src/dmd/cppmanglewin.d
Labels: Bug Fix

#15123 core.internal.string: upgrade conversion functions
  druntime/src/core/internal/string.d
Labels: Easy Review

#15127 fix issue 23859 - [REG 2.103] Throwing while in a deep callstack causes memory corruption
  druntime/src/core/sys/windows/stacktrace.d
  druntime/test/exceptions/src/winstack.d
Labels: Bug Fix

#15121 fix Issue 23055 - importC: using compound-literal array as pointer in CTFE gives 'dereference of invalid pointer'
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/printast.d
  compiler/test/runnable/test22070_2.c
Labels: Bug Fix

#15130 Remove unused prototypes in backend
  compiler/src/dmd/backend/backend.d
  compiler/src/dmd/backend/cg87.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/cv8.d
  compiler/src/dmd/backend/dwarfdbginf.d
  compiler/src/dmd/backend/elem.d
  compiler/src/dmd/backend/glocal.d
  compiler/src/dmd/backend/go.d
  compiler/src/dmd/backend/goh.d
  compiler/src/dmd/backend/nteh.d
Labels: Refactoring, Backend

#15129 Fix Issue 19706 - Attribute inference in struct fails
  compiler/src/dmd/traits.d
  compiler/test/compilable/traits_getFunctionAttributes.d
Labels: Bug Fix

#15126 fix Issue 23837 - importc fails to link on windows x86 but successes …
  compiler/src/dmd/dstruct.d
  compiler/src/dmd/e2ir.d
  compiler/test/runnable/imports/mainx23837.c
  compiler/test/runnable/test23837.d
Labels: Bug Fix

#15131 fix Issue 23862 - with statement should accept an expression with enu…
  compiler/src/dmd/statementsem.d
  compiler/test/compilable/test23862.d
  compiler/test/fail_compilation/diag9312.d
  compiler/test/fail_compilation/fail4375q.d
Labels: Enhancement, Easy Review

#15133 Fix Issue 23861 - Compiler segmentation fault with ref and alias this
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/fail23861.d
Labels: Bug Fix

#15134 ImportC: support __attribute__((always_inline))
  compiler/src/dmd/cparse.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/test/compilable/always_inline.i
Labels: Easy Review, ImportC

#15135 ImportC: add __declspec and __attribute__ nothrow
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/test/fail_compilation/testnothrow.c
Labels: Easy Review, ImportC

#14550 Translate `_d_arraycatnTX` to a template
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/src/dmd/inline.d
  compiler/test/compilable/test19688.d
  compiler/test/runnable/extra-files/hello-profile-postscript.sh
  compiler/test/unit/lexer/location_offset.d
  druntime/src/core/internal/array/concatenation.d
  druntime/src/object.d
  druntime/src/rt/lifetime.d
  druntime/src/rt/tracegc.d
Labels: 72h no objection -> merge

#15139 Fix Issue 23846 - Respect the C standard when it comes to string to f…
  compiler/src/dmd/root/port.d
Labels: auto-merge, Bug Fix

#15136 Make core.demangle compile with -preview=nosharedacccess
  druntime/src/core/atomic.d
  druntime/src/core/demangle.d
  druntime/src/core/thread/package.d
Labels: auto-merge

#15145 ImportC: add __attribute__((pure))
  compiler/src/dmd/cparse.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/id.d
  compiler/test/fail_compilation/attrpure.i
Labels: Easy Review, ImportC

#15146 Remove function prototypes from backend pt2 redux
  compiler/src/dmd/backend/code.d
Labels: Refactoring, Backend

#15140 Fix Issue 23863 - typeof rejects AliasSeq!() as argument
  compiler/src/dmd/typesem.d
  compiler/test/compilable/test23863.d
Labels: Bug Fix

#15149 fix Issue 23866 - ImportC: Multiple __declspecs rejected
  compiler/src/dmd/cparse.d
  compiler/test/compilable/test23866.i
Labels: Enhancement, auto-merge, Bug Fix, ImportC

#15147 Fix 23867 and 23869
  druntime/src/importc.h
Labels: Bug Fix, auto-merge-squash, ImportC
