Repository dlang/dmd, pull requests merged in 2023-02, with the labels that each got.

#14857 merge stable
  VERSION
  changelog/dmd.deprecate-duplicate-system-implementations.dd
  changelog/dmd.deprecate-getAttributes-overloadSet.dd
  changelog/dmd.for-increment.dd
  changelog/dmd.scope-array-on-stack.dd
  changelog/dmd.static-assert.dd
  changelog/dmd.system-variables.dd
  changelog/druntime.nogc-traceinfo.dd
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/parse.d
  compiler/test/compilable/test19268.d
  compiler/test/fail_compilation/test15368.d
  compiler/test/fail_compilation/test22593.d
  compiler/test/fail_compilation/testrvaluecpctor.d
  druntime/src/core/internal/array/duplication.d
Labels: Enhancement, auto-merge, Bug Fix

#14858 add const scope to IN6* functions taking inet 6 address pointers
  druntime/src/core/sys/posix/netinet/in_.d
Labels: auto-merge

#14854 Fix Issue 23648 - replace uses of sprintf with snprintf in the compiler
  compiler/src/dmd/backend/cgcod.d
  compiler/src/dmd/backend/cgobj.d
  compiler/src/dmd/backend/debugprint.d
  compiler/src/dmd/backend/disasm86.d
  compiler/src/dmd/backend/dwarfdbginf.d
  compiler/src/dmd/backend/elem.d
  compiler/src/dmd/backend/elfobj.d
  compiler/src/dmd/backend/elpicpie.d
  compiler/src/dmd/backend/filespec.d
  compiler/src/dmd/backend/gsroa.d
  compiler/src/dmd/backend/machobj.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/backend/symbol.d
  compiler/src/dmd/dmangle.d
  compiler/src/dmd/eh.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/glue.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/libelf.d
  compiler/src/dmd/libmach.d
  compiler/src/dmd/libmscoff.d
  compiler/src/dmd/link.d
  compiler/src/dmd/mars.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/objc_glue.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/root/ctfloat.d
  compiler/src/dmd/root/ctfloat.h
  compiler/src/dmd/root/longdouble.d
  compiler/src/dmd/root/longdouble.h
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/tocsym.d
  compiler/src/dmd/tokens.d
  compiler/test/runnable/extra-files/paranoia.d
Labels: Bug Fix

#14861 Remove dead `return ref` check
  compiler/src/dmd/typesem.d
Labels: auto-merge, Easy Review, dip1000

#14863 dmd.root.filename: Add FileName::create helper
  compiler/src/dmd/frontend.h
  compiler/src/dmd/root/filename.d
  compiler/src/dmd/root/filename.h
  compiler/src/tests/cxxfrontend.cc
Labels: auto-merge, Easy Review, extern (C/C++)

#14708 replace addLocalClass() with ScopeDsymbol._foreach
  compiler/src/dmd/aggregate.h
  compiler/src/dmd/attrib.d
  compiler/src/dmd/attrib.h
  compiler/src/dmd/dclass.d
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dsymbol.h
  compiler/src/dmd/frontend.h
  compiler/src/dmd/module.h
  compiler/src/dmd/toobj.d
  compiler/src/tests/cxxfrontend.cc
Labels: auto-merge, Easy Review, Refactoring, Ready To Merge

#14866 fix Issue 23672 - importC: Infinite recursion: Error: found 'End of File' when expecting ','
  compiler/src/dmd/cparse.d
  compiler/test/fail_compilation/test23672.i
Labels: auto-merge, Bug Fix, ImportC

#11071 fix Issue 20781 - Can call @live function without checking dip1021 rules
  compiler/src/dmd/escape.d
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/fob1.d
  compiler/test/fail_compilation/fob2.d
Labels: Bug Fix

#14026 ImportC: add __check(assign-expression) extension
  changelog/dmd.check.dd
  compiler/src/dmd/cparse.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/tokens.d
  compiler/src/dmd/tokens.h
  compiler/test/unit/lexer/location_offset.d
  test/runnable/testcheck.c
Labels: Enhancement, Easy Review, ImportC, Ready To Merge

#14541 fix Issue 23387 - ImportC: identical structs defined in two C files l…
  compiler/src/dmd/tocsym.d
  compiler/test/runnable/imports/freer.i
  compiler/test/runnable/imports/maker.i
  compiler/test/runnable/test23387.d
  compiler/test/tools/d_do_test.d
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#12424 fix Issue 21821 - Optimizer assumes immutables do not change, but the…
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/gdag.d
  compiler/src/dmd/backend/gother.d
  compiler/src/dmd/backend/symbol.d
  compiler/src/dmd/tocsym.d
  test/runnable/test21821.d
Labels: Needs Approval, Bug Fix, Backend, Ready To Merge

#14323 add scope to constructors
  compiler/src/dmd/apply.d
  compiler/src/dmd/argtypes_sysv_x64.d
  compiler/src/dmd/arrayop.d
  compiler/src/dmd/blockexit.d
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/cppmangle.d
  compiler/src/dmd/cppmanglewin.d
  compiler/src/dmd/delegatize.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/dmangle.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/dtoh.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/foreachvar.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/inline.d
  compiler/src/dmd/inlinecost.d
  compiler/src/dmd/json.d
  compiler/src/dmd/lambdacomp.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/nogc.d
  compiler/src/dmd/ob.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/printast.d
  compiler/src/dmd/root/aav.d
  compiler/src/dmd/root/array.d
  compiler/src/dmd/root/rootobject.d
  compiler/src/dmd/s2ir.d
  compiler/src/dmd/sapply.d
  compiler/src/dmd/semantic2.d
  compiler/src/dmd/semantic3.d
  compiler/src/dmd/sideeffect.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/templateparamsem.d
  compiler/src/dmd/tocsym.d
  compiler/src/dmd/tocvdebug.d
  compiler/src/dmd/todt.d
  compiler/src/dmd/toobj.d
  compiler/src/dmd/traits.d
  compiler/src/dmd/visitor.d
Labels: Easy Review, Refactoring

#14855 fix Issue 15985 - [REG2.068/2.069] Code doesn't link unless compiled …
  compiler/src/dmd/dtemplate.d
  compiler/test/runnable/test15985.d
Labels: Bug Fix, Ready To Merge

#14680 fix Issue 23545 - export int a; should generate dllexport, not dllimport
  changelog/dmd.extern-dllimport.dd
  compiler/src/dmd/declaration.d
  compiler/src/dmd/tocsym.d
  compiler/test/dshell/dll.d
Labels: Bug Fix, Easy Review, Ready To Merge

#14867 Fix 23679 - off-by-one error for static array size limit
  compiler/src/dmd/toobj.d
  compiler/src/dmd/typesem.d
  compiler/test/compilable/test23679.d
Labels: Bug Fix

#14175 fix Issue 23145 - Stack allocation of scope new variables defeats @safe
  compiler/src/dmd/clone.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/func.d
  compiler/src/dmd/nogc.d
  compiler/test/compilable/test23145.d
  compiler/test/runnable/auto1.d
  compiler/test/runnable/cppdtor.d
  compiler/test/runnable/mixin2.d
  compiler/test/runnable/test20855.d
  compiler/test/runnable/test23.d
  compiler/test/runnable/test8.d
  compiler/test/runnable/testdstress.d
  compiler/test/runnable_cxx/cppa.d
Labels: Bug Fix, Needs Spec PR

#14651 fix Issue 23195 - Win64 function ABI bug for small non-POD arguments
  compiler/src/dmd/dstruct.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/frontend.h
  compiler/test/runnable_cxx/cpp_abi_tests.d
  compiler/test/runnable_cxx/extra-files/cpp_abi_tests.cpp
Labels: Bug Fix, Ready To Merge

#14699 fix Issue 23558 - add __traits(getModuleClasses [, module name])
  changelog/dmd.getClassInfos.dd
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/src/dmd/traits.d
  compiler/test/compilable/test23558.d
  compiler/test/fail_compilation/test23558.d
  druntime/src/object.d
Labels: Enhancement, Needs Spec PR, Ready To Merge

#14859 Fix Issue 23662: ImportC bad handling of enum arguments for a function
  compiler/src/dmd/cparse.d
  compiler/test/compilable/imports/imp23662.c
  compiler/test/compilable/test23662.d
Labels: Bug Fix

#14864 reapply fix Issue 23479 - ImportC recognizes .i and .c files, but not .h files
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/file_manager.d
  compiler/src/dmd/globals.d
  compiler/src/dmd/mars.d
  compiler/test/compilable/test23479.h
Labels: auto-merge

#14872 fix Issue 23688 - FTBFS: error: cannot convert 'Expression' to 'Expression*'
  compiler/src/dmd/expression.h
Labels: Regression, GDC, LDC, Blocking Other Work, auto-merge, Bug Fix, extern (C/C++)

#14873 [stable] Fix core.demangle compile error for non-macOS Darwin targets
  druntime/src/core/demangle.d
Labels: auto-merge

#14869 fix Issue 23682 - dip1000 problem with return by ref
  compiler/src/dmd/escape.d
  compiler/test/fail_compilation/retscope6.d
Labels: Bug Fix, dip1000

#14875 merge stable
  VERSION
  compiler/src/dmd/cparse.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/toobj.d
  compiler/src/dmd/typesem.d
  compiler/test/compilable/imports/imp23662.c
  compiler/test/compilable/test23662.d
  compiler/test/compilable/test23679.d
  compiler/test/fail_compilation/test23672.i
  compiler/test/fail_compilation/test23674.d
  druntime/src/core/demangle.d
Labels: auto-merge, Bug Fix, stable -> master

#14575 Implement named argument for functions
  compiler/src/dmd/arrayop.d
  compiler/src/dmd/astbase.d
  compiler/src/dmd/clone.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/opover.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/semantic3.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/template.h
  compiler/src/dmd/toobj.d
  compiler/test/compilable/named_arguments.d
  compiler/test/fail_compilation/call_function_type.d
  compiler/test/fail_compilation/named_arguments_error.d
  compiler/test/fail_compilation/named_arguments_overload.d
Labels: auto-merge, New Language Feature

#14877 gitignore: ignore vim backup files
  .gitignore
Labels: Trivial

#14862 reboot separate out mangleType()
  compiler/src/dmd/dmangle.d
Labels: Refactoring, Ready To Merge

#14876 Fix Issue 23705 - dmd: src/dmd/backend/cgcod.d:734: Assertion sz >= 0 failed
  compiler/src/dmd/backend/cgcod.d
  compiler/test/compilable/test23705.d
Labels: auto-merge, Bug Fix

#14878 Remove old dead code from parse.d
  compiler/src/dmd/parse.d
Labels: Trivial, auto-merge, Easy Review

#14880 [refactor] Expression: change parens type from ubyte to bool
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/frontend.h
  compiler/src/dmd/parse.d
Labels: auto-merge, Easy Review, Refactoring

#14887 merge stable
  VERSION
  compiler/src/dmd/backend/cgcod.d
  compiler/test/compilable/test23705.d
Labels: auto-merge, Bug Fix, stable -> master

#14889 Fix inconsistent `names` and `arguments` arrays
  compiler/src/dmd/expression.d
  compiler/src/dmd/parse.d
Labels: auto-merge

#14885 Deduplicate return parameter destination logic
  compiler/src/dmd/escape.d
  compiler/src/dmd/expressionsem.d
Labels: Refactoring, dip1000

#14893 Move incorrectly placed runnable tests
  compiler/test/runnable/test21821.d
  compiler/test/runnable/testcheck.c
Labels: Trivial, auto-merge

#14895 Fix linking to 64-bit time_t versions of functions on musl
  druntime/src/core/stdc/config.d
  druntime/src/core/stdc/time.d
  druntime/src/core/sys/posix/aio.d
  druntime/src/core/sys/posix/dlfcn.d
  druntime/src/core/sys/posix/mqueue.d
  druntime/src/core/sys/posix/sched.d
  druntime/src/core/sys/posix/semaphore.d
  druntime/src/core/sys/posix/signal.d
  druntime/src/core/sys/posix/sys/resource.d
  druntime/src/core/sys/posix/sys/select.d
  druntime/src/core/sys/posix/sys/stat.d
  druntime/src/core/sys/posix/sys/time.d
  druntime/src/core/sys/posix/time.d
  druntime/src/core/sys/posix/utime.d
Labels: Bug Fix

#14871 Fix 22916 - copy of ref return still treated as scope variable
  compiler/src/dmd/escape.d
  compiler/test/compilable/test22916.d
  compiler/test/fail_compilation/retscope6.d
Labels: Bug Fix, dip1000

#14899 fix Issue 23717 - runnable/bitfields.c:192:5: error: unknown type nam…
  compiler/test/runnable/bitfields.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#14810 ImportC: smoke test all C Standard .h files
  compiler/test/compilable/stdcheaders.c
  druntime/src/importc.h
Labels: Needs Approval, Easy Review, ImportC, Ready To Merge

#14657 Fix issue 23514 - Incorrect compilation when adding a 64-bit constant to a link-time address
  compiler/src/dmd/e2ir.d
  compiler/test/runnable/test23514.d
Labels: auto-merge, Bug Fix

#14898 fix Issue 23711 - compilable/testcstuff1.c:63:1: error: invalid use o…
  compiler/test/compilable/testcstuff1.c
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#14904 merge stable
  VERSION
  compiler/src/dmd/e2ir.d
  compiler/test/runnable/test23514.d
  druntime/src/core/stdc/config.d
  druntime/src/core/stdc/time.d
  druntime/src/core/sys/posix/aio.d
  druntime/src/core/sys/posix/dlfcn.d
  druntime/src/core/sys/posix/mqueue.d
  druntime/src/core/sys/posix/sched.d
  druntime/src/core/sys/posix/semaphore.d
  druntime/src/core/sys/posix/signal.d
  druntime/src/core/sys/posix/sys/resource.d
  druntime/src/core/sys/posix/sys/select.d
  druntime/src/core/sys/posix/sys/stat.d
  druntime/src/core/sys/posix/sys/time.d
  druntime/src/core/sys/posix/time.d
  druntime/src/core/sys/posix/utime.d
  druntime/test/exceptions/Makefile
Labels: auto-merge, Bug Fix, stable -> master

#14892 Revert "fix Issue 23558 - add __traits(getModuleClasses [, module name])
  changelog/dmd.getClassInfos.dd
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/src/dmd/traits.d
  compiler/test/compilable/test23558.d
  compiler/test/fail_compilation/test23558.d
Labels: Walter Bright

#14901 [stable] druntime: Fix InvalidMemoryOperation error on Windows when throwing exceptions from finalizers
  druntime/src/core/sys/windows/stacktrace.d
  druntime/test/allocations/win64.mak
  druntime/win32.mak
  druntime/win64.mak
Labels: Bug Fix

#14891 Deprecate `-preview=dip25` switch
  changelog/dmd.dip25-default.dd
  compiler/src/build.d
  compiler/src/dmd/cli.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.d
  compiler/src/dmd/mars.d
  compiler/test/compilable/previewhelp.d
  compiler/test/compilable/reverthelp.d
  compiler/test/fail_compilation/dip25.d
  compiler/test/fail_compilation/dip25flag.d
  compiler/test/fail_compilation/fail_scope.d
  compiler/test/fail_compilation/test20809.d
Labels: Deprecation

#14886 Fix 23676 - Static foreach hangs compilation for some time
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/test/compilable/test23676.d
Labels: Bug Fix

#14897 Tweak semicolon expected to close `alias` declaration error
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/e15876_5.d
  compiler/test/fail_compilation/fail21243.d
  compiler/test/fail_compilation/issue16020.d
  compiler/test/fail_compilation/udaparams.d
Labels: auto-merge

#14764 fix Issue 16098 - align(N) not respected for stack variables if N > platform stack alignment
  compiler/src/dmd/declaration.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/target.d
  compiler/src/dmd/target.h
  compiler/src/dmd/tocsym.d
  compiler/src/dmd/toir.d
  compiler/test/runnable/test16098.d
Labels: Blocking Other Work, Bug Fix, Ready To Merge

#14912 [stable] druntime: Reduce intra-druntime dependencies for array-appending hook
  druntime/src/core/internal/array/appending.d
  druntime/src/object.d
Labels: auto-merge

#14914 [stable] druntime: Only define GC-trace templates when compiling with `-profile=gc`
  druntime/src/core/internal/array/appending.d
  druntime/src/core/internal/array/capacity.d
  druntime/src/core/internal/array/concatenation.d
  druntime/src/core/internal/array/utils.d
  druntime/src/core/lifetime.d
Labels: auto-merge

#14915 Strip trailing whitespace in `Outbuffer.writenl`
  compiler/src/dmd/common/outbuffer.d
  compiler/src/tests/cxxfrontend.cc
  compiler/test/compilable/extra-files/header18365.d
  compiler/test/compilable/extra-files/imp9057.d
  compiler/test/compilable/extra-files/test23626a.d
  compiler/test/compilable/extra-files/vcg-ast.d.cg
  compiler/test/runnable/extra-files/test39.d
Labels: auto-merge

#14917 s2ir.d: move private functions to end of file
  compiler/src/dmd/s2ir.d
Labels: auto-merge, Easy Review, Refactoring

#14909 Fix Issue 23732 - Cannot create shared instance of class with -preview=nosharedaccess
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/shared.d
  compiler/test/fail_compilation/shared.d
Labels: Enhancement, auto-merge, Bug Fix

#14916 fix Issue 23710 - [REG master] Reachable code inside an 'if (false)' …
  compiler/src/dmd/s2ir.d
  compiler/test/fail_compilation/test23710.d
  compiler/test/runnable/test23710.d
Labels: auto-merge, Bug Fix, Ready To Merge

#14922 Fix Issue 23745 - Segfault with forward reference mismatched override with undeclared type
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/fail23745.d
Labels: Regression, auto-merge, Bug Fix, Easy Review

#14921 lexer.d: revise unittests to use ErrorSinks
  compiler/src/dmd/lexer.d
Labels: Easy Review

#14926 tokens.d: use buffer properly
  compiler/src/dmd/tokens.d
Labels: auto-merge, Easy Review, Refactoring

#14927 parseModulePatternDepth: replace pointer with array
  compiler/src/dmd/compiler.d
Labels: auto-merge, Easy Review, Refactoring

#14928 lexer.d: remove errors and globals imports
  compiler/src/dmd/lexer.d
Labels: auto-merge, Easy Review, Refactoring

#14929 Fix 11316: Infer storage class of parameters with function literals
  compiler/src/dmd/expression.d
  compiler/test/compilable/infer_stc.d
  compiler/test/runnable/funclit.d
Labels: Enhancement, Blocking Other Work, auto-merge

#14923 Deduplicate lexer unittest code
  compiler/test/unit/lexer/lexer_dmdlib.d
Labels: auto-merge, Refactoring

#14930 fix Issue 18472: betterC cannot use format at compile time
  compiler/src/dmd/dstruct.d
  compiler/src/dmd/inlinecost.d
  compiler/src/dmd/s2ir.d
  compiler/test/runnable/test18472.d
Labels: auto-merge, Bug Fix

#14932 Add 'override' on functions overriding interface functions
  druntime/src/core/sys/windows/stacktrace.d
Labels: Refactoring
