Repository dlang/dmd, pull requests merged in 2023-12, with the labels that each got.

#15874 merge stable
  VERSION
  changelog/dmd.catch-immutable.dd
  changelog/dmd.dtoh-improvements.dd
  changelog/dmd.enum-function.dd
  changelog/dmd.fix24084.dd
  changelog/dmd.intel-cet-ibt-protection.dd
  changelog/dmd.scope-ctor-error.dd
  changelog/dmd.shared-static-ctor-const.dd
  changelog/dmd.static-assoc-array.dd
  changelog/dmd.template-_d_newarrayT.dd
  changelog/druntime.gc-collect-safe.dd
  compiler/src/dmd/dtemplate.d
Labels: auto-merge

#15879 druntime: removes copydir target from Windows makefiles
  druntime/mak/WINDOWS
  druntime/win32.mak
  druntime/win64.mak
Labels: Build System

#15883 Removes unused DDOCFLAGS variable from druntime/win64.mak
  druntime/win64.mak
Labels: Trivial, auto-merge, Build System, Refactoring

#15875 Create README.md at ./dmd/druntime/def
  druntime/def/README.md
Labels: auto-merge, documentation

#15878 fix Issue 23714 - compilable/testcstuff1.c:213:1: error: static asser…
  compiler/src/dmd/lexer.d
  compiler/test/compilable/testcstuff1.c
Labels: Bug Fix, Easy Review, ImportC

#15871 ImportC: support #define IDENT ( expression )
  compiler/src/dmd/cparse.d
  compiler/src/dmd/errorsink.d
  compiler/src/dmd/lexer.d
  compiler/test/compilable/imports/defines.c
  compiler/test/compilable/testdefines.d
Labels: Easy Review, Ready To Merge

#15885 Move dmd.aliasthis.resolveAliasThis to dsymbolsem
  compiler/src/dmd/aliasthis.d
  compiler/src/dmd/dcast.d
  compiler/src/dmd/dsymbolsem.d
Labels: auto-merge

#15884 Delete useless imports from compiler/src/dmd/init.d
  compiler/src/dmd/init.d
Labels: auto-merge

#15886 Move dmd.aliasthis.isRecursiveAliasThis to mtype.d
  compiler/src/dmd/aliasthis.d
  compiler/src/dmd/mtype.d
Labels: auto-merge

#15888 Dscope.search: use out parameter
  compiler/src/dmd/doc.d
  compiler/src/dmd/dscope.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/iasmdmd.d
  compiler/src/dmd/lambdacomp.d
  compiler/src/dmd/semantic3.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/typesem.d
Labels: auto-merge, Easy Review, Refactoring

#15890 Fix 24272 - operations.arrayOp is forced @nogc nothrow pure
  druntime/src/core/internal/array/operations.d
Labels: auto-merge, Bug Fix

#15889 add SearchOpt to enum type
  compiler/src/dmd/astcodegen.d
  compiler/src/dmd/dclass.d
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/dscope.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dsymbol.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtoh.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/module.h
  compiler/src/dmd/scope.h
  compiler/src/dmd/typesem.d
  compiler/test/unit/compilable/searching.d
Labels: Easy Review, Refactoring

#15816 Initial attempt at stdatomic.h
  changelog/druntime.stdatomic.dd
  druntime/mak/COPY
  druntime/mak/SRCS
  druntime/src/core/internal/atomic.d
  druntime/src/core/stdc/stdatomic.d
Labels: auto-merge

#15895 use isXXX() functions for ReturnStatement semantic
  compiler/src/dmd/statementsem.d
Labels: auto-merge, Easy Review, Refactoring

#15898 fix Issue 24274 - [REG master] ImportC: unrecognized C initializer wi…
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/initsem.d
  compiler/test/runnable/test24042.c
Labels: Bug Fix, ImportC

#15899 fix Issue 24276 - ImportC: typedef aliases not emitted correctly in .…
  compiler/src/dmd/cparse.d
  compiler/test/compilable/ctod.i
Labels: auto-merge, Bug Fix, ImportC

#15902 Fix 24281 - Segfault with missing field after named argument
  compiler/src/dmd/initsem.d
  compiler/test/fail_compilation/named_arguments_struct_literal.d
Labels: auto-merge, Bug Fix, Easy Review

#15903 fix Issue 23713 - compilable/testcstuff1.c:206:1: error: static asser…
  compiler/src/dmd/cparse.d
  compiler/src/dmd/lexer.d
  compiler/test/compilable/testcstuff1.c
Labels: Bug Fix, Easy Review, ImportC

#15905 Delete useless imports in compiler/src/dmd/staticassert.d
  compiler/src/dmd/staticassert.d
Labels: auto-merge

#15904 Extract dsymbol.setFieldOffset and move it into a visitor
  compiler/src/dmd/attrib.d
  compiler/src/dmd/attrib.h
  compiler/src/dmd/dclass.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dstruct.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dsymbol.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/nspace.d
  compiler/src/dmd/nspace.h
  compiler/src/dmd/template.h
Labels: auto-merge

#15876 Remove deprecated compiler Makefiles
  .circleci/run.sh
  Makefile
  changelog/dmd.makefiles.dd
  compiler/src/build.d
  compiler/src/osmodel.mak
  compiler/src/posix.mak
  compiler/src/win32.mak
  compiler/src/win64.mak
  compiler/test/Makefile
  druntime/posix.mak
  posix.mak
  src/posix.mak
  src/win32.mak
  src/win64.mak
  win32.mak
  win64.mak
Labels: auto-merge, Build System, Refactoring

#15786 Break dependency of expression.d on gluelayer.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/frontend.h
  compiler/src/dmd/tocsym.d
Labels: auto-merge

#15906 Delete useless imports in compiler/src/dmd/nspace.d
  compiler/src/dmd/nspace.d
Labels: auto-merge

#15907 Move dmd.mtype.Type.covariant to dmd.typesem
  compiler/src/dmd/ctfeexpr.d
  compiler/src/dmd/dclass.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/mtype.h
  compiler/src/dmd/typesem.d
  compiler/test/unit/semantic/covariance.d
Labels: auto-merge

#15908 Move dmd.type.checkDeprecated to dmd/dsymbolsem.d and make it private
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/mtype.d
  compiler/src/dmd/mtype.h
Labels: auto-merge

#15909 Break dependency of dmd/mtype.d on dmd/expressionsem.d
  compiler/src/dmd/func.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/typesem.d
Labels: auto-merge

#15911 Fix Phobos CI regression
  druntime/posix.mak
Labels: auto-merge

#15912 Azure CI: Migrate from legacy MODEL=32mscoff to MODEL=32
  .azure-pipelines/windows-msbuild.bat
  azure-pipelines.yml
  compiler/test/README.md
  compiler/test/runnable/test23011.c
  compiler/test/tools/d_do_test.d
Labels: auto-merge

#15913 fix Issue 23629 - importC: Need to support code coverage analysis
  compiler/src/dmd/glue.d
  compiler/src/dmd/toir.d
  compiler/test/runnable/cov2.d
  compiler/test/runnable/extra-files/runnable-cov2.lst
  compiler/test/runnable/imports/ccov2.c
Labels: Enhancement, Easy Review, ImportC

#15919 statementsem.d: remove some casts
  compiler/src/dmd/statementsem.d
Labels: auto-merge, Easy Review, Refactoring

#15923 CI: Reduce parallelism on Windows from N=3 to N=2
  .azure-pipelines/lib.sh
  .azure-pipelines/windows-msbuild.bat
Labels: auto-merge

#15918 fix Issue 23411 - ImportC: undefined identifier __builtin_nanf
  compiler/test/compilable/stdcheaders.c
  druntime/src/__builtins.di
Labels: Bug Fix, Easy Review, ImportC

#15921 fix Issue 24283 - [SIMD][CODEGEN] Bad codegen with and not + AVX2 reg…
  compiler/src/dmd/e2ir.d
  compiler/test/runnable/testxmm2.d
Labels: auto-merge, Bug Fix, Easy Review

#15930 eliminate dependence on global.params.dihdr.fullOutput
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/hdrgen.h
  compiler/src/dmd/main.d
Labels: auto-merge, Easy Review, Refactoring

#15926 make toChars(Type) work
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/mtype.h
Labels: Easy Review, Refactoring

#15932 hdrgen.d public functions use ref HdrGenState
  compiler/src/dmd/doc.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/frontend.d
  compiler/src/dmd/hdrgen.d
Labels: auto-merge, Easy Review, Refactoring

#15931 eliminate dependence on global.params.dihdr.vcg_ast
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/hdrgen.h
  compiler/src/dmd/main.d
Labels: auto-merge, Easy Review, Refactoring

#15929 PtrStateToChars() because too many toChars()
  compiler/src/dmd/ob.d
Labels: Easy Review, Refactoring

#15927 ScopeRefToChars() because too many toChars()
  compiler/src/dmd/escape.d
  compiler/src/dmd/mtype.d
Labels: Easy Review, Refactoring

#15928 ClassKindToChars() because too many toChars()
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/dsymbolsem.d
Labels: Easy Review, Refactoring

#15915 fix Issue 22483 - DMD generates invalid string sections that work by coincidence
  compiler/src/dmd/backend/elfobj.d
Labels: auto-merge, Bug Fix

#15938 oneMember() should use out for ps
  compiler/src/dmd/astbase.d
  compiler/src/dmd/attrib.d
  compiler/src/dmd/attrib.h
  compiler/src/dmd/denum.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dsymbol.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/enum.h
  compiler/src/dmd/frontend.h
  compiler/src/dmd/staticassert.d
  compiler/src/dmd/staticassert.h
  compiler/src/dmd/template.h
Labels: auto-merge, Easy Review, Refactoring

#15936 many more HdrGenState * to ref
  compiler/src/dmd/hdrgen.d
Labels: auto-merge, Easy Review, Refactoring

#15937 move Expression.toChars() to hdrgen.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
Labels: Easy Review, Refactoring

#15939 Fixes issues 20339, 24292: Calculate isPOD without information from semantic run
  compiler/src/dmd/clone.d
  compiler/src/dmd/dstruct.d
  compiler/test/compilable/issue20339.d
  compiler/test/runnable_cxx/extra-files/test24292.cpp
  compiler/test/runnable_cxx/test24292.d
Labels: auto-merge, Bug Fix

#15935 Replace previewIn with STC.inscoperef)
  compiler/src/dmd/astenums.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dmangle.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/typesem.d
Labels: Refactoring

#15942 hdrgen.d: remove globals.d import
  compiler/src/dmd/hdrgen.d
Labels: auto-merge, Easy Review, Refactoring

#15537 Add `@standalone` attribute for module constructors
  changelog/dmd.standalone-attribute.dd
  compiler/src/dmd/attrib.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/id.d
  compiler/src/dmd/mustuse.d
  compiler/test/fail_compilation/standalone_modctor.d
  compiler/test/runnable/imports/standalone_b.d
  compiler/test/runnable/standalone_modctor.d
  druntime/src/core/attribute.d
Labels: Needs Spec PR, New Language Feature, Industry

#15943 Fix issue 24298 - cpp_delete should check for null
  druntime/src/core/stdcpp/new_.d
  druntime/test/stdcpp/src/new_test.d
Labels: auto-merge, Bug Fix

#15924 Flag rela section as info
  compiler/src/dmd/backend/elfobj.d
Labels: auto-merge

#15945 hdrgen.d: remove reference to global target
  compiler/src/dmd/hdrgen.d
  compiler/test/compilable/test9565.d
  compiler/test/fail_compilation/fail19890a.d
  compiler/test/fail_compilation/fail19890b.d
  compiler/test/fail_compilation/fail4611.d
  compiler/test/fail_compilation/staticarrayoverflow.d
Labels: auto-merge, Easy Review, Refactoring

#15947 Fix typo in assert in `common/smallbuffer.d`
  compiler/src/dmd/common/smallbuffer.d
Labels: auto-merge

#15949 Remove deprecated rndtonl from core.math
  druntime/src/core/math.d
Labels: auto-merge, Easy Review

#15950 hdrgen.d: replace some toChars() with toString()
  compiler/src/dmd/hdrgen.d
Labels: Easy Review, Refactoring

#15951 add toString to tokens.d
  compiler/src/dmd/tokens.d
Labels: Easy Review, Refactoring

#15952 hdrgen.d: more conversion to toString()
  compiler/src/dmd/hdrgen.d
Labels: Easy Review, Refactoring

#15953 Fix 24301 - Misleading error message when passing non-copyable struct…
  compiler/src/dmd/typesem.d
  compiler/test/fail_compilation/fail24301.d
Labels: Bug Fix

#15954 fix Issue 24280 - ImportC: forward reference error when compiling mul…
  compiler/src/dmd/typesem.d
  compiler/test/compilable/imports/test24280b.i
  compiler/test/compilable/test24280.i
Labels: Bug Fix, ImportC

#15957 fix Issue 24297 - ImportC incompatible with glibc _FORTIFY_SOURCE
  druntime/src/importc.h
Labels: Enhancement, Easy Review, ImportC

#15956 fix Issue 24304 - __uint16_t, __uint32_t, __uint64_t are not recognized
  compiler/test/compilable/test23214.c
  druntime/src/importc.h
Labels: Bug Fix, Easy Review, ImportC

#15961 Fix issue 22905 - gdb backtrace contains wrong location
  compiler/src/dmd/expressionsem.d
  compiler/test/runnable/gdb22905.d
  compiler/test/runnable/imports/gdb22905b.d
  compiler/test/runnable/imports/gdb22905c.d
Labels: Bug Fix

#15958 fix Issue 24303 - anonymous struct problems when typedef'd in separat…
  compiler/src/dmd/cparse.d
  compiler/test/compilable/imports/test24280b.i
  compiler/test/compilable/test24280.i
Labels: Bug Fix, ImportC

#15860 Deprecate string literals as (static) assert conditions
  changelog/dmd.assert-string.dd
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/semantic2.d
  compiler/test/fail_compilation/array_bool.d
  compiler/test/runnable/testpdb.d
Labels: Enhancement

#15965 fix OMF test failure regarding testdefines.d
  compiler/src/dmd/link.d
Labels: auto-merge

#15966 fix Issue 24306 - ImportC: same name structs in separate C files inte…
  compiler/src/dmd/dsymbolsem.d
  compiler/test/compilable/imports/test24280b.i
  compiler/test/compilable/test24280.i
Labels: Bug Fix, ImportC

#15967 ImportC: give error when encountering computed goto
  compiler/src/dmd/cparse.d
  compiler/test/fail_compilation/compgoto.i
Labels: Easy Review, ImportC

#14849 [WIP] fix issue 4071 and others: shared runtime DLL for Windows
  .azure-pipelines/windows.sh
  compiler/src/dmd/backend/backconfig.d
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cdef.d
  compiler/src/dmd/backend/dout.d
  compiler/src/dmd/backend/elpicpie.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/cli.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dmdparams.d
  compiler/src/dmd/dmsc.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/glue.d
  compiler/src/dmd/inline.d
  compiler/src/dmd/mars.d
  compiler/src/dmd/tocsym.d
  compiler/src/dmd/toobj.d
  druntime/Makefile
  druntime/src/rt/msvc.d
  druntime/src/rt/sections.d
  druntime/test/common.mak
  druntime/test/shared/Makefile
  druntime/test/shared/src/dynamiccast.d
Labels: WIP

#15969 getLines() shouldn't be reading files
  compiler/src/dmd/errors.d
  compiler/src/dmd/file_manager.d
Labels: auto-merge, Easy Review, Refactoring

#15972 change splitTextIntoLines() to splitLines()
  compiler/src/dmd/errors.d
  compiler/src/dmd/file_manager.d
Labels: Easy Review
