Repository dlang/dmd, pull requests merged in 2023-01, with the labels that each got.

#14762 Rework rewrites of OPmemset to be more general
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/e2ir.d
Labels: Bug Fix

#14765 merge stable
  VERSION
  compiler/src/dmd/backend/inliner.d
  compiler/src/dmd/cond.d
  compiler/src/dmd/constfold.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/optimize.d
  compiler/src/dmd/s2ir.d
  compiler/src/dmd/template.h
  compiler/test/compilable/extra-files/build23499.d
  compiler/test/compilable/imports/file23499.d
  compiler/test/compilable/issue20618.d
  compiler/test/compilable/issue22646.d
  compiler/test/compilable/issue22854.d
  compiler/test/compilable/issue22975.d
  compiler/test/compilable/issue23391.d
  compiler/test/compilable/issue23567.d
  compiler/test/compilable/test18646.d
  compiler/test/compilable/test19585.d
  compiler/test/compilable/test22638.d
  compiler/test/compilable/test22813.d
  compiler/test/compilable/test23499.d
  compiler/test/compilable/test23589.d
  compiler/test/fail_compilation/fail20618.d
  compiler/test/fail_compilation/fail23151.d
  compiler/test/fail_compilation/fail23574.d
  compiler/test/fail_compilation/ice23564.d
  compiler/test/runnable/issue22854.d
  compiler/test/runnable/test20811.d
Labels: Enhancement, auto-merge, Bug Fix, stable -> master

#14767 bump VERSION to v2.102.0-beta.1
  VERSION
Labels: auto-merge

#14769 cdmemset: remove code replaced by elmemset
  compiler/src/dmd/backend/cod2.d
Labels: Refactoring

#14774 Makefile: stub out all auto-tester-build and auto-tester-test recipes
  compiler/samples/win32.mak
  compiler/src/build.d
  compiler/src/posix.mak
  compiler/src/win32.mak
  compiler/test/Makefile
  druntime/posix.mak
  druntime/win32.mak
  druntime/win64.mak
  posix.mak
  src/posix.mak
  win32.mak
Labels: Continuous Integration

#14772 ci: Update cirrus macOS image to M1-based runners
  .cirrus.yml
  compiler/test/Makefile
  druntime/test/common.mak
Labels: Blocking Other Work, Continuous Integration

#14773 Remove old 'Calling member function before dip1000'
  compiler/src/dmd/escape.d
Labels: auto-merge, dip1000

#14781 runnable/issue22854.d: Reduce code expansion to speed up testsuite
  compiler/test/runnable/issue22854.d
Labels: auto-merge, Continuous Integration

#14779 Fix Issue 19649 - Misleading error for duplicate constraints
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/fnconstraint.d
Labels: Enhancement, auto-merge, Bug Fix, Diagnostic Messages

#14783 Fix Issue 23597 - .di files not compatible with -i
  compiler/src/dmd/compiler.d
  compiler/test/compilable/imports/test23597.di
  compiler/test/compilable/issue23597.d
Labels: Enhancement

#14771 Fix Issue 23261 - druntime core.std.attribute.Tagged1_2 constructor i…
  druntime/src/core/attribute.d
Labels: Bug Fix

#14789 fix Issue 20101 - BetterC: Template instantiation in CTFE only contex…
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/toobj.d
  compiler/src/dmd/traits.d
  compiler/test/compilable/test20201.d
Labels: Enhancement

#14795 fix Issue 23584 - ImportC: __builtin_bit_cast not supported
  compiler/test/compilable/test22809.c
  druntime/src/importc.h
Labels: Bug Fix, Easy Review, ImportC

#14797 ImportC better error message for __int128
  compiler/src/dmd/cparse.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/tokens.d
  compiler/src/dmd/tokens.h
  compiler/test/fail_compilation/test128.i
  compiler/test/unit/lexer/location_offset.d
Labels: Easy Review

#14791 fix Issue 23606 - betterC with CTFE and gc
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dscope.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/inline.d
  compiler/src/dmd/nogc.d
  compiler/src/dmd/tocsym.d
  compiler/test/compilable/test23606.d
Labels: Bug Fix

#14799 fix Issue 23616 - ImportC: clang __has_feature and __has_extension no…
  compiler/src/dmd/link.d
  compiler/test/compilable/test23616.c
  druntime/src/importc.h
Labels: Blocking Other Work, Bug Fix, Easy Review, ImportC

#14800 Follow up "- betterC with CTFE and gc"
  compiler/src/dmd/declaration.h
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/nogc.d
Labels: Refactoring

#14796 Remove some special cases from dmd.typesem.resolveHelper
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/typesem.d
  compiler/test/fail_compilation/diag14235.d
  compiler/test/fail_compilation/test23607.d
Labels: Bug Fix

#14806 fix Issue 23407 - ImportC: function-local struct definition as part o…
  compiler/src/dmd/cparse.d
  compiler/test/compilable/test23407.i
Labels: Bug Fix

#14803 fix issue 23620 - 'alias this' is not respected in static array lengt…
  compiler/src/dmd/typesem.d
  compiler/test/compilable/b23620.d
Labels: auto-merge, Bug Fix

#14808 Handle `null` elements in `Array.toString`
  compiler/src/dmd/root/array.d
Labels: auto-merge, Easy Review

#14807 Fix Issue 23617 - traits(child) compile error need this for something that doesn't need this
  compiler/src/dmd/typesem.d
  compiler/test/compilable/test23617.d
Labels: auto-merge, Bug Fix

#14790 fix Issue 23218 - cgxmm.d:1373 assert fail
  compiler/src/dmd/backend/var.d
  compiler/src/dmd/dcast.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expressionsem.d
  compiler/test/runnable/testxmm.d
Labels: Enhancement, Bug Fix

#14727 fix Issue 21772 - [REG2.069] Consecutive different-signed double.nans…
  compiler/src/dmd/constfold.d
  compiler/src/dmd/ctfeexpr.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/frontend.h
  compiler/test/runnable/test21772.d
Labels: auto-merge, Bug Fix

#14811 fix Issue 23622 - ImportC #defines conflict with declarations
  compiler/src/dmd/cparse.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/frontend.h
  compiler/test/compilable/test23622.c
Labels: Blocking Other Work, auto-merge, Bug Fix, Easy Review, ImportC

#14801 fix Issue 23583 - ImportC: undefined identifier __builtin___memmove_chk
  compiler/test/compilable/test23583.c
  druntime/src/importc.h
Labels: Blocking Other Work, auto-merge, Bug Fix, Easy Review

#14805 fix Issue 23614 - ImportC: __int128 not supported
  druntime/src/importc.h
Labels: Blocking Other Work, auto-merge, Bug Fix, Easy Review, ImportC

#14814 fix Issue 23618 - Right Shift equals expressions on unsigned shorts s…
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/e2ir.d
  compiler/test/runnable/test23618.d
Labels: Blocking Other Work, auto-merge, Bug Fix, Industry

#14777 fix Issue 20520 - Runtime segfault when taking typeid of a class inst…
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/printast.d
  compiler/test/runnable/test20520.d
Labels: auto-merge, Bug Fix

#14815 Merge stable
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/printast.d
  compiler/test/runnable/test20520.d
  compiler/test/runnable/test23618.d
  druntime/src/importc.h
Labels: Blocking Other Work, auto-merge, Bug Fix

#14816 Fix issue 23625 - Function ZeroMemory missing in windows headers
  druntime/src/core/sys/windows/winbase.d
Labels: auto-merge, Bug Fix

#14817 Fix Issue 23624 - Race condition in test runner for DMD
  compiler/test/run.d
Labels: auto-merge, Bug Fix

#14787 fix Issue 18026 - Stack overflow in dmd/dtemplate.d:6248, TemplateInstance::needsCodegen()
  compiler/src/dmd/dtemplate.d
  compiler/test/compilable/test18026.d
Labels: Bug Fix

#14820 fix Issue 19467 - Support EV_SET on OSX
  druntime/src/core/sys/darwin/sys/event.d
Labels: Enhancement, auto-merge, Bug Fix, Easy Review, BetterC

#14818 fix Issue 23626 - [REG2.096] Template deduction with auto const ref Args... and delegate
  changelog/dmd.deprecate-duplicate-system-implementations.dd
  compiler/src/dmd/frontend.h
  compiler/src/dmd/mtype.d
  compiler/src/dmd/semantic2.d
  compiler/test/compilable/extra-files/test23626a.d
  compiler/test/compilable/extra-files/test23626b.d
  compiler/test/compilable/test23626.d
  compiler/test/fail_compilation/fail23626a.d
  compiler/test/fail_compilation/fail23626b.d
Labels: Regression, Bug Fix

#14823 merge stable
  VERSION
  changelog/dmd.deprecate-duplicate-system-implementations.dd
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/mtype.d
  compiler/src/dmd/semantic2.d
  compiler/test/compilable/extra-files/test23626a.d
  compiler/test/compilable/extra-files/test23626b.d
  compiler/test/compilable/test18026.d
  compiler/test/compilable/test23626.d
  compiler/test/fail_compilation/fail23626a.d
  compiler/test/fail_compilation/fail23626b.d
  druntime/src/core/sys/darwin/sys/event.d
Labels: Bug Fix

#14819 fix Issue 19268 - BetterC turns off .dup for CTFE
  compiler/test/compilable/test19268.d
  druntime/src/core/internal/array/duplication.d
Labels: auto-merge, Bug Fix

#14825 ci: Remove old druntime CI scripts
  druntime/.circleci/config.yml
  druntime/.circleci/run.sh
  druntime/.cirrus.yml
  druntime/.codecov.yml
Labels: auto-merge, Easy Review, Continuous Integration

#14828 src/dmd/errors.d(384): `old_loc` is thread local
  compiler/src/dmd/errors.d
Labels: Trivial, Easy Review

#14830 fix Issue 21492 - betterC: TypeInfo is generated for code guarded by …
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/s2ir.d
  compiler/src/dmd/toir.d
  compiler/test/runnable/test21492.d
Labels: Bug Fix

#14776 Add named arguments to struct literals
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/initsem.d
  compiler/src/dmd/parse.d
  compiler/test/compilable/named_argumens_struct.d
  compiler/test/fail_compilation/diag11132.d
  compiler/test/fail_compilation/fail155.d
  compiler/test/fail_compilation/fail156.d
  compiler/test/fail_compilation/fail158.d
  compiler/test/fail_compilation/fail22570.d
  compiler/test/fail_compilation/fail299.d
  compiler/test/fail_compilation/named_arguments_parse.d
  compiler/test/fail_compilation/test20998.d
Labels: New Language Feature

#14833 remove untag.d from test suite
  compiler/test/runnable/extra-files/untag.html
  compiler/test/runnable/untag.d
Labels: Easy Review

#14834 Fix parens in expandTuples documentation
  compiler/src/dmd/expression.d
Labels: auto-merge

#14835 dmd.expression: Fix another stray paren in DDoc
  compiler/src/dmd/expression.d
Labels: auto-merge

#14836 Fix Issue 23639 - Casting to shared not allowed with -preview=nosharedaccess
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/test23639.d
  compiler/test/fail_compilation/shared.d
Labels: Blocking Other Work, Bug Fix

#14840 Fix Issue 23635 - Nonsensical "`case` must be a `string` or an integr…
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/diag9358.d
  compiler/test/fail_compilation/test_switch_error.d
Labels: auto-merge, Bug Fix

#14711 fix Issue 16495 - __traits(fullyQualifedName) instead of std.traits.f…
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/src/dmd/traits.d
  compiler/test/compilable/test16495.d
  compiler/test/fail_compilation/test16495.d
Labels: Enhancement, Needs Changelog

#14839 Fix 15368 - improve error message when using auto in foreach
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/test15368.d
Labels: Enhancement

#14841 Fix issue 11051 - Unmatched case in a final switch should throw in both release and non-release mode
  compiler/src/dmd/statementsem.d
  compiler/test/runnable/extra-files/test11051.d
  compiler/test/runnable/test_safe_final_switch.sh
Labels: Bug Fix

#14843 fix Issue 23651 - Order dependency in semantic analysis of template members
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/test/compilable/test23651.d
Labels: auto-merge, Bug Fix, Refactoring

#14587 Add -verror-supplements, to let the user define how many supplemental…
  compiler/src/dmd/cli.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/globals.d
  compiler/src/dmd/globals.h
  compiler/src/dmd/mars.d
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/diag8101.d
  compiler/test/fail_compilation/fail15616a.d
  compiler/test/fail_compilation/fail15616c.d
  compiler/test/fail_compilation/fail15616d.d
Labels: auto-merge, Walter Bright

#14845 rename VarDeclaration.aliassym to aliasTuple
  compiler/src/dmd/declaration.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtoh.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/semantic2.d
  compiler/src/dmd/toobj.d
  compiler/src/tests/cxxfrontend.cc
Labels: Easy Review, Refactoring

#14846 Propagate SCOPE.compiles for nested functions in traits(compiles) blocks
  compiler/src/dmd/expression.d
  compiler/src/dmd/func.d
  compiler/src/dmd/semantic3.d
Labels: Blocking Other Work

#13687 Fix Issue 21613 - DMD crash: copy ctor + templated rvalue ctor
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/test/fail_compilation/test22593.d
  compiler/test/fail_compilation/testrvaluecpctor.d
Labels: auto-merge, Bug Fix, Easy Review, stable-stalled

#14838 fix Issue 23598 - Circular reference bug with static if and eponymous…
  compiler/src/dmd/attrib.d
  compiler/src/dmd/attrib.h
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dsymbol.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/frontend.h
  compiler/test/compilable/test23598.d
  compiler/test/fail_compilation/ice12727.d
  compiler/test/fail_compilation/ice13816.d
Labels: Bug Fix

#14671 fix Issue 19575 - core.cpuid not usable without a runtime
  druntime/src/core/cpuid.d
Labels: Blocking Other Work, auto-merge, Bug Fix, Easy Review

#14844 Fix Issue 23650 - Using typeid with struct defined in __traits(compiles, ...) causes linker error
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/typinf.d
  compiler/test/runnable/test23650.d
Labels: Blocking Other Work, Bug Fix

#14847 Remove FUNCFLAG.compileTimeOnly
  compiler/src/dmd/declaration.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
Labels: auto-merge

#14837 Translate `_d_newclass` to a template
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/test/compilable/test23431_minimal.d
  compiler/test/compilable/test23433.d
  compiler/test/fail_compilation/fail308.d
  compiler/test/fail_compilation/ice23569.d
  druntime/src/core/lifetime.d
  druntime/src/object.d
  druntime/src/rt/tracegc.d
  druntime/test/profile/myprofilegc.log.freebsd.32.exp
  druntime/test/profile/myprofilegc.log.freebsd.64.exp
  druntime/test/profile/myprofilegc.log.linux.32.exp
  druntime/test/profile/myprofilegc.log.linux.64.exp
  druntime/test/profile/myprofilegc.log.osx.32.exp
  druntime/test/profile/myprofilegc.log.osx.64.exp
Labels: 72h no objection -> merge

#14852 Tweak @live undisposed owner error
  compiler/src/dmd/ob.d
  compiler/test/fail_compilation/failob1.d
  compiler/test/fail_compilation/failob2.d
  compiler/test/fail_compilation/fob1.d
  compiler/test/fail_compilation/fob2.d
Labels: auto-merge

#14824 ci: Update Ubuntu images to 22.04
  .cirrus.yml
  ci/README.md
  compiler/test/runnable_cxx/cppa.d
  druntime/src/importc.h
  druntime/test/exceptions/Makefile
Labels: auto-merge

#14851 fix Issue 23658 - .di generation of variables should turn them into d…
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/test/compilable/extra-files/header1.di
  compiler/test/compilable/extra-files/header1i.di
  compiler/test/compilable/extra-files/header2.di
  compiler/test/compilable/extra-files/header2i.di
Labels: auto-merge, Bug Fix, Easy Review
