Repository dlang/dmd, pull requests merged in 2023-06, with the labels that each got.

#15280 Fix Issue 16384 - Invariant not called with multiple defined.
  compiler/src/dmd/sideeffect.d
  compiler/test/runnable/testinvariant.d
Labels: Bug Fix

#15288 Make druntime/src/rt/lifetime._d_arrayshrinkfit truly nothrow
  druntime/src/rt/lifetime.d
Labels: auto-merge

#15287 fix Issue 23719 - runnable/test22071.c:22:16: error: .abc. is a point…
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/importc.d
  compiler/test/fail_compilation/fix22253.c
  compiler/test/fail_compilation/test23719.c
  compiler/test/runnable/test22071.c
Labels: Bug Fix, Easy Review, ImportC

#15290 merge stable
  VERSION
  changelog/dmd.attr-inference-diag.dd
  changelog/dmd.empty-statement-error.dd
  changelog/dmd.in-externd.dd
  changelog/dmd.in-ref.dd
  changelog/dmd.throw-qualifier.dd
  changelog/dmd.uda-template-args.dd
  druntime/src/core/stdc/assert_.d
Labels: auto-merge, Bug Fix

#15138 Make usage of std{in,out,err} compile with -preview=nosharedaccess
  druntime/src/core/atomic.d
  druntime/src/core/internal/gc/proxy.d
  druntime/src/core/internal/parseoptions.d
  druntime/src/core/stdc/wchar_.d
Labels: 72h no objection -> merge

#15292 Add missing functions and noreturn to core.stdc.assert_
  druntime/src/core/stdc/assert_.d
Labels: auto-merge

#15297 [stable] Fix tests race condition for fail_compilation/failcstuff4.{c,i}
  compiler/test/fail_compilation/failcstuff4b.i
Labels: auto-merge

#15291 core.sys.windows.dll improve documentation
  druntime/src/core/sys/windows/dll.d
Labels: documentation

#15300 Fix 23979 - ICE on failed alias this attempt on pointer expression
  compiler/src/dmd/opover.d
  compiler/test/compilable/test23979.d
Labels: Bug Fix

#15302 Fix 23978 - ICE: dip1021 memory corruption
  compiler/src/dmd/escape.d
  compiler/test/compilable/test23978.d
Labels: Bug Fix

#15305 Fix 23986 - ICE: dip1021 asserts on `typeof(null)` parameter
  compiler/src/dmd/escape.d
  compiler/test/compilable/test23986.d
Labels: Bug Fix

#15311 Refactor local variables in `deduceFunctionTemplateMatch`
  compiler/src/dmd/dtemplate.d
Labels: Refactoring

#15309 riden should be ridden
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/cli.d
  compiler/src/dmd/compiler.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtoh.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/semantic3.d
  compiler/test/fail_compilation/dtor_attributes.d
  compiler/test/fail_compilation/fail19209.d
  compiler/test/fail_compilation/fail23745.d
Labels: Easy Review

#15313 [object.destroy] Add example for nested struct
  druntime/src/object.d
Labels: auto-merge

#15282 Fix issue 23947: Class method private is ignored if there's a public overload after it
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/imports/issue23947a.d
  compiler/test/fail_compilation/issue23947.d
Labels: Bug Fix

#15295 Move lowerings to `_d_array{setassign,assign_{l,r}}` to a `LoweredAssignExp` AST node
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/test/runnable/test23959.d
Labels: Enhancement, Bug Fix, auto-merge-squash

#15316 fix Issue 23988 - Conditional Exp does not bring enums to correct com…
  compiler/src/dmd/dcast.d
  compiler/test/compilable/commontype.d
Labels: Bug Fix

#15321 Fix Issue 4663 - Wrong 'static' position error message
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/funcpostattr.d
Labels: Enhancement

#15301 Fix Issue 23980 - OpenBSD: Add getthrname(2) and setthrname(2) to unistd.d
  druntime/src/core/sys/openbsd/unistd.d
Labels: Enhancement, auto-merge

#15325 merge stable
  VERSION
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/escape.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/opover.d
  compiler/test/compilable/stdcheaders.c
  compiler/test/compilable/test23978.d
  compiler/test/compilable/test23979.d
  compiler/test/compilable/test23986.d
  compiler/test/fail_compilation/failcstuff4b.i
  compiler/test/runnable/test23959.d
  druntime/src/importc.h
Labels: Bug Fix, stable -> master

#15310 Merge stable
  VERSION
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/escape.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/opover.d
  compiler/test/compilable/stdcheaders.c
  compiler/test/compilable/test23978.d
  compiler/test/compilable/test23979.d
  compiler/test/compilable/test23986.d
  compiler/test/fail_compilation/failcstuff4b.i
  compiler/test/runnable/test23959.d
  druntime/src/importc.h
Labels: Bug Fix

#15328 Refer to bugzilla issues by hyperlink
  compiler/src/dmd/attrib.d
  compiler/src/dmd/backend/cgcod.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/eh.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/inline.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/optimize.d
  compiler/src/dmd/toir.d
  compiler/src/dmd/traits.d
  compiler/test/compilable/b20938.d
  compiler/test/compilable/test16635.d
  compiler/test/compilable/testInference.d
  compiler/test/runnable/functype.d
  compiler/test/runnable/interface2.d
  compiler/test/runnable/link10425.d
  compiler/test/runnable/template9.d
  compiler/test/runnable/testcontracts.d
  druntime/src/core/atomic.d
  druntime/src/core/internal/gc/impl/conservative/gc.d
  druntime/src/core/lifetime.d
  druntime/src/object.d
  druntime/src/rt/dwarfeh.d
  druntime/src/rt/lifetime.d
  druntime/src/rt/util/typeinfo.d
Labels: Trivial

#15327 Improve error message for declaring opaque type variable
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/enum_init.d
  compiler/test/fail_compilation/failcstuff4.c
Labels: Diagnostic Messages

#15319 Make 'private function is not accessible' deprecation an error.
  changelog/dmd.private-deprecation-error.dd
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/fail21275.d
  compiler/test/fail_compilation/issue23947.d
Labels: Deprecation -> Error

#15329 Fix 23982 - segfault when printing scope inference failure
  compiler/src/dmd/escape.d
  compiler/test/fail_compilation/test23982.d
Labels: Bug Fix

#15315 Fix Issue 23965 - Disable deprecation checks for DRuntime hooks
  compiler/src/dmd/dsymbolsem.d
  compiler/test/compilable/test23965.d
Labels: Bug Fix

#15317 Fix Issue 23968 - Deprecation not emitted with alias to template function in UFCS
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/test23968.d
Labels: Bug Fix

#15337 Fix Issue 22729 - ICE: Invalid array access for invalid interface definition
  compiler/src/dmd/semantic2.d
  compiler/test/fail_compilation/fail22729.d
Labels: auto-merge, Bug Fix

#15336 Fix Issue 23971 - Provide clearer error message when trying to return…
  compiler/src/dmd/semantic3.d
  compiler/test/fail_compilation/fail16772.d
  compiler/test/fail_compilation/fail21206.d
Labels: Enhancement, Trivial

#15338 Issue 21025 - Segfault for function contract -preview=dip1021
  compiler/src/dmd/escape.d
  compiler/test/fail_compilation/test21025.d
Labels: Bug Fix, Easy Review

#15341 Remove some unused imports
  compiler/src/dmd/access.d
  compiler/src/dmd/asttypename.d
Labels: Easy Review, Refactoring

#15344 fix Issue 23768 - ImportC: ICE on nested C initializer
  compiler/src/dmd/initsem.d
  compiler/test/compilable/test23786.c
Labels: Bug Fix

#15347 Fix Issue 24013 - [REG 2.103.0] address of a __traits(getOverloads) item is not converted to a delegate anymore
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/test24013.d
Labels: Bug Fix

#15335 Fix 20008 - __traits(allMembers) of packages is complete nonsense
  compiler/src/dmd/traits.d
  compiler/test/compilable/imports/pkg20008/package.d
  compiler/test/compilable/imports/pkg20008/submod.d
  compiler/test/compilable/imports/pkg20008/subpkg/package.d
  compiler/test/compilable/imports/pkg20008/subpkg/subsubmod.d
  compiler/test/compilable/imports/test9692b.d
  compiler/test/compilable/test20008.d
  compiler/test/compilable/test9692.d
Labels: Bug Fix

#15354 Fix issue 24018: set length manually via runtime function.
  compiler/test/compilable/issue24018.d
  druntime/src/core/internal/array/concatenation.d
Labels: Bug Fix

#15356 Remove ballast code from compiler/src/dmd/expressionsem.d
  compiler/src/dmd/expressionsem.d
Labels: Easy Review

#15355 Fix Issue 24017 - Bypassing nothrow with debug doesn’t work
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/test24017.d
Labels: Bug Fix, Easy Review

#15358 Only predefine D_ModuleInfo, D_Exceptions, D_TypeInfo if feature is enabled
  compiler/src/dmd/target.d
Labels: Easy Review

#15357 Use params.useExceptions instead of betterC to gate generation of try/catch in ctors
  compiler/src/dmd/semantic3.d
Labels: GDC, Easy Review

#15360 Remove nothrow from doGNUABITagSemantic predicate function
  compiler/src/dmd/root/array.d
  compiler/src/dmd/semantic2.d
Labels: GDC, Easy Review

#15359 Fix Issue 11612 - Inconsistent error on negative new array size
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/issue20422.d
Labels: Bug Fix

#15361 Remove e2ir/dmsc 'import' from backend
  compiler/src/dmd/backend/dtype.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/symbol.d
  compiler/src/dmd/dmsc.d
  compiler/src/dmd/e2ir.d
Labels: Refactoring, Backend

#15364 Move eh.d to backend
  compiler/src/build.d
  compiler/src/dmd/README.md
  compiler/src/dmd/backend/backconfig.d
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/backend/cgxmm.d
  compiler/src/dmd/backend/eh.d
  compiler/src/dmd/backend/errors.di
  compiler/src/dmd/backend/evalu8.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/gother.d
  compiler/src/dmd/backend/nteh.d
Labels: Refactoring, Backend

#15367 fix tabs in transitivevisitor.d
  compiler/src/dmd/transitivevisitor.d
Labels: Trivial

#15363 Fix Issue 15436 - Compiler still refers to AliasSeq-s as "tuple"-s
  compiler/src/dmd/astbase.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/dmangle.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/iasmdmd.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/opover.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/typesem.d
  compiler/test/compilable/extra-files/header1.di
  compiler/test/compilable/extra-files/header1i.di
  compiler/test/compilable/extra-files/vcg-ast.d.cg
  compiler/test/compilable/stc_traits.d
  compiler/test/compilable/test13668.d
  compiler/test/compilable/test17143.d
  compiler/test/compilable/test17373.d
  compiler/test/compilable/test17545.d
  compiler/test/compilable/test19728.d
  compiler/test/compilable/test21282.d
  compiler/test/compilable/test21330.d
  compiler/test/fail_compilation/casttuple.d
  compiler/test/fail_compilation/cppmangle.d
  compiler/test/fail_compilation/dassert.d
  compiler/test/fail_compilation/diag13884.d
  compiler/test/fail_compilation/diag14876.d
  compiler/test/fail_compilation/fail12436.d
  compiler/test/fail_compilation/fail15755.d
  compiler/test/fail_compilation/fail222.d
  compiler/test/fail_compilation/ice12574.d
  compiler/test/fail_compilation/ice14424.d
  compiler/test/fail_compilation/typeerrors.d
  compiler/test/runnable/uda.d
  compiler/test/runnable/xtest46.d
  compiler/test/runnable/xtest46_gc.d
Labels: Enhancement

#15349 Upstream vendor-specific errors relating to missing object.d
  compiler/src/dmd/dmodule.d
Labels: GDC, LDC, Easy Review

#15351 Fix Issue 24010 - Destructor called before end of scope for tuples
  compiler/src/dmd/statementsem.d
  compiler/test/runnable/sdtor.d
Labels: Bug Fix, Industry
