Repository dlang/dmd, pull requests merged in 2023-09, with the labels that each got.

#15565 Refactor FuncExp.matchType to use ErrorSink
  compiler/src/dmd/dcast.d
  compiler/src/dmd/errorsink.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/match_func_ptr.d
Labels: auto-merge

#15570 chkformat.d: use ErrorSink
  compiler/src/dmd/chkformat.d
  compiler/src/dmd/expressionsem.d
Labels: auto-merge, Easy Review, Refactoring

#15571 refactor fillinops() to modernize it
  compiler/src/dmd/backend/cgelem.d
Labels: auto-merge, Easy Review, Refactoring

#15558 escape.d: start using ErrorSink
  compiler/src/dmd/clone.d
  compiler/src/dmd/dscope.d
  compiler/src/dmd/dstruct.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/escape.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/typesem.d
Labels: Easy Review, Refactoring

#15574 replace aaGetSymbol() with RTLSYM
  compiler/src/dmd/backend/drtlsym.d
  compiler/src/dmd/backend/rtlsym.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/tocsym.d
Labels: auto-merge, Easy Review, Refactoring

#15573 escape.d: more ErrorSink
  compiler/src/dmd/dscope.d
  compiler/src/dmd/escape.d
Labels: auto-merge, Easy Review

#15579 verify sizes of MSCOFF structs
  compiler/src/dmd/backend/mscoff.d
  compiler/src/dmd/backend/mscoffobj.d
Labels: auto-merge

#15580 convert covb from pointer to array
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/glue.d
  compiler/src/dmd/module.h
  compiler/src/dmd/toir.d
Labels: auto-merge, Easy Review, Refactoring

#15583 remove anacrhonistic alias toSymbol declarations
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/s2ir.d
  compiler/src/dmd/todt.d
  compiler/src/dmd/toir.d
  compiler/src/dmd/toobj.d
Labels: auto-merge, Easy Review, Refactoring

#15577 Fix Issue 24109 - [REG2.103] 'need this' when invoking outer method from inner method
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/test24109.d
Labels: Bug Fix

#15575 Fix Issue 24110 - [REG2.104] Array comparison lowering apparently not handled properly in __traits(compiles)
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/test24110.d
Labels: Bug Fix

#15584 Revert "Fix Issue 24112 - binary expressions with noreturn vars produ…
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/noreturn_bin.d
Labels: auto-merge

#15582 fix issue 22682 - `pragma(mangle)` does not work for nested functions
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/statementsem.d
  compiler/test/compilable/issue22682.d
  compiler/test/fail_compilation/issue22682.d
Labels: Bug Fix

#15588 Improve error messages when enum member cannot be generated
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/diag12063.d
  compiler/test/fail_compilation/fail109.d
Labels: auto-merge, Bug Fix

#15589 Improve error when generating first enum member of non-scalar type
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/diag7477.d
Labels: auto-merge

#15548 modernize scanmscoff.d
  compiler/src/dmd/scanmscoff.d
Labels: auto-merge, Easy Review, Refactoring

#15590 remove thisblock global variable
  compiler/src/dmd/backend/gother.d
Labels: auto-merge, Easy Review, Refactoring

#15591 refactor nteh.d a bit
  compiler/src/dmd/backend/nteh.d
Labels: Easy Review, Refactoring

#15594 gflow.d: pass length as parameter
  compiler/src/dmd/backend/gflow.d
Labels: auto-merge, Easy Review, Refactoring

#15593 gflow.d: eliminate need to reference global
  compiler/src/dmd/backend/gflow.d
Labels: auto-merge, Easy Review, Refactoring

#15592 gother.d: consolidate some globals into struct
  compiler/src/dmd/backend/gother.d
Labels: auto-merge, Easy Review, Refactoring

#15595 fix Issue 24130 - ImportC: Windows headers use inline asm with differ…
  compiler/src/dmd/cli.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/glue.d
  compiler/src/dmd/iasm.d
  compiler/src/dmd/iasmdmd.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/statement.d
  compiler/src/dmd/statement.h
  compiler/test/compilable/test24130.c
Labels: Bug Fix, Easy Review, ImportC

#15598 [stable] Fix Issue 24139 - 'this' corruption in extern(C++) dtor when destructing via TypeInfo_Struct
  compiler/src/dmd/clone.d
  compiler/test/runnable/test24139.d
Labels: Bug Fix

#15587 Fix Issue 24107 - The error for exceeding the CTFE recursion limit by passes speculative compilation.
  compiler/src/dmd/dinterpret.d
  compiler/test/compilable/test24107.d
Labels: Bug Fix

#15578 Issue 24118 - ICE / regression from 2.103.1 - segfault on CTFE only code in 2.104.2 and 2.105.0
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/test24118.d
Labels: Bug Fix

#15599 Fix Issue 15752 - Better Error Message for Assigning Incorrect AA Emp…
  compiler/src/dmd/initsem.d
  compiler/test/fail_compilation/aa_init.d
Labels: Enhancement

#15601 fix Issue 24123 - More importc definitions are needed for macOS
  druntime/src/importc.h
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#15604 [stable] Fix Issue 24144 - [REG2.105] Silent file name index overflow
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.h
  compiler/src/dmd/location.d
Labels: Bug Fix

#15609 merge stable
  VERSION
  compiler/src/dmd/clone.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.h
  compiler/src/dmd/location.d
  compiler/src/dmd/optimize.d
  compiler/src/dmd/parse.d
  compiler/test/compilable/shortened_methods.d
  compiler/test/compilable/test24109.d
  compiler/test/compilable/test24118.d
  compiler/test/fail_compilation/test24110.d
  compiler/test/runnable/test24078.d
  compiler/test/runnable/test24139.d
  druntime/src/core/stdc/math.d
  druntime/src/rt/minfo.d
Labels: Bug Fix

#15615 change toCBuffer to use ref parameters
  compiler/src/dmd/doc.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/init.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/statement.d
Labels: Easy Review, Refactoring

#15611 move functions out of statement.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/statement.d
Labels: Easy Review, Refactoring

#15616 doc.d: switch to ref buf instead of *buf
  compiler/src/dmd/doc.d
  compiler/src/dmd/hdrgen.d
Labels: Easy Review, Refactoring

#15617 change OutBuffer* to ref OutBuffer
  compiler/src/dmd/attrib.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/dtoh.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/hdrgen.h
  compiler/src/dmd/main.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/printast.d
  compiler/src/dmd/semantic3.d
  compiler/src/dmd/typesem.d
Labels: Easy Review, Refactoring

#15619 more OutBuffer* to ref OutBuffer
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/mtype.h
Labels: Easy Review, Refactoring

#15585 fix Issue 24129 - ImportC: MS-Link cannot handle multiple COMDATs wit…
  compiler/src/dmd/glue.d
  compiler/src/dmd/tocsym.d
  compiler/test/runnable/extra-files/test24129b.c
  compiler/test/runnable/test24129.c
Labels: Bug Fix, ImportC

#15621 move visitVarDecl() out of DsymbolPrettyPrintVisitor
  compiler/src/dmd/hdrgen.d
Labels: Easy Review, Refactoring

#15622 remove error() from Statement
  compiler/src/dmd/astbase.d
  compiler/src/dmd/blockexit.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/iasmgcc.d
  compiler/src/dmd/statement.d
  compiler/src/dmd/statementsem.d
Labels: Easy Review, Refactoring

#15623 blockexit.d: use ErrorSink
  compiler/src/dmd/blockexit.d
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/func.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/semantic3.d
  compiler/src/dmd/statementsem.d
Labels: Easy Review, Refactoring

#15624 fix regression in #15623
  compiler/test/unit/semantic/control_flow.d
Labels: Easy Review

#15629 run toCBufferInstance through front door of DsymbolPrettyPrintVisitor
  compiler/src/dmd/hdrgen.d
Labels: Easy Review, Refactoring

#15630 move visitTemplateParameters out of DsymbolPrettyPrintVisitor
  compiler/src/dmd/hdrgen.d
Labels: Easy Review, Refactoring

#15634 change hasNoDefault to hasDefault
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/statement.d
  compiler/src/dmd/statement.h
  compiler/src/dmd/statementsem.d
Labels: Easy Review, Refactoring

#15633 make use of Statement.arraySyntaxCopy()
  compiler/src/dmd/statement.d
Labels: Easy Review, Refactoring

#15612 CLI: Remove obsolete flag and all its warnings, undocument -wo flag
  compiler/src/dmd/blockexit.d
  compiler/src/dmd/cli.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/dscope.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtoh.d
  compiler/src/dmd/errors.d
  compiler/src/dmd/errors.h
  compiler/src/dmd/errorsink.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/globals.d
  compiler/src/dmd/globals.h
  compiler/src/dmd/inline.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/main.d
  compiler/src/dmd/mars.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/sideeffect.d
  compiler/src/dmd/statementsem.d
  compiler/test/compilable/obsolete_body.d
  compiler/test/compilable/test23145.d
  compiler/test/fail_compilation/body.d
  compiler/test/fail_compilation/dip1000_deprecation.d
  compiler/test/fail_compilation/fail_scope.d
  compiler/test/fail_compilation/test13536.d
  compiler/test/fail_compilation/test16365.d
Labels: GDC, Blocking Other Work, Diagnostic Messages

#15635 make DsymbolPrettyPrintVisitor a function local class 2
  compiler/src/dmd/hdrgen.d
Labels: Refactoring

#15638 hdrgen.d: convert switch to array
  compiler/src/dmd/hdrgen.d
Labels: Easy Review, Refactoring

#15640 fix Issue 24156 - ImportC: Apple uses __signed as a keyword
  druntime/src/importc.h
Labels: Bug Fix, Easy Review, ImportC

#15639 fix Issue 24154 - ImportC: useless expression parsed as invalid varia…
  compiler/src/dmd/cparse.d
  compiler/test/runnable/initializer.c
Labels: Bug Fix, ImportC
