Repository dlang/dmd, pull requests merged in 2023-05, with the labels that each got.

#15144 refactor SmallBuffer
  compiler/src/dmd/common/string.d
Labels: Easy Review, Refactoring

#15065 Use DotExpFlag type for flag parameter
  compiler/src/dmd/aliasthis.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/mtype.d
  compiler/src/dmd/typesem.d
Labels: Refactoring

#15151 Remove SYMDEB_TDB
  compiler/src/dmd/backend/dcgcv.d
  compiler/src/dmd/backend/global.d
Labels: auto-merge, Refactoring, Backend

#15156 merge stable
  VERSION
  compiler/src/dmd/backend/dvarstats.d
  compiler/src/dmd/backend/ptrntab.d
  compiler/src/dmd/cond.d
  compiler/src/dmd/cppmangle.d
  compiler/src/dmd/cppmanglewin.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/statementsem.d
  compiler/test/compilable/extra-files/header1.di
  compiler/test/compilable/extra-files/header2.di
  compiler/test/compilable/test22739.d
  compiler/test/fail_compilation/cerrors.d
  compiler/test/fail_compilation/fail17646.d
  compiler/test/fail_compilation/fail19948.d
  compiler/test/fail_compilation/fail22857.d
  compiler/test/fail_compilation/fail23816.d
  compiler/test/fail_compilation/imports/import22857.d
  compiler/test/fail_compilation/test21164.d
  compiler/test/fail_compilation/test22765.d
  compiler/test/unit/lexer/diagnostic_reporter.d
  druntime/src/core/sys/windows/stacktrace.d
  druntime/test/exceptions/src/winstack.d
Labels: Bug Fix

#15150 Remove function prototypes from backend pt3
  compiler/src/dmd/backend/global.d
Labels: Refactoring, Backend

#15154 Remove SPP version blocks
  compiler/src/dmd/backend/blockopt.d
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cdef.d
  compiler/src/dmd/backend/cgcs.d
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/backend/ee.d
  compiler/src/dmd/backend/evalu8.d
  compiler/src/dmd/backend/fp.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/go.d
  compiler/src/dmd/backend/nteh.d
  compiler/src/dmd/backend/obj.d
  compiler/src/dmd/backend/out.d
  compiler/src/dmd/backend/var.d
Labels: Refactoring, Backend

#15157 fix Issue 23870 - ImportC doesn't accept '\' followed by newline, whe…
  compiler/src/dmd/lexer.d
  compiler/test/compilable/test23870.i
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#15158 Document dmd.backend not shared by DMC anymore
  compiler/src/dmd/README.md
Labels: auto-merge

#15159 bump VERSION to v2.104.0-beta.1
  VERSION
Labels: auto-merge, stable -> master

#15160 fix Issue 23871 - ImportC: __attribute not recognized
  compiler/test/compilable/test23871.c
  druntime/src/importc.h
Labels: Enhancement, auto-merge, Easy Review, ImportC

#15152 Remove backend os.d (reboot)
  compiler/src/build.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/go.d
  compiler/src/dmd/backend/os.d
Labels: Refactoring, Backend

#14707 Fix Issue 21415 - catch immutable exceptions breaks immutable
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/fail2456.d
  compiler/test/runnable/eh2.d
Labels: Bug Fix

#15164 Fix Issue 23874 - -profile=gc segfaults / ICE regression
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/test23874.d
Labels: auto-merge, Bug Fix

#15165 Remove exh.d
  compiler/src/build.d
  compiler/src/dmd/backend/README.md
  compiler/src/dmd/backend/cgcod.d
  compiler/src/dmd/backend/cgxmm.d
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/cod2.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/cv8.d
  compiler/src/dmd/backend/ee.d
  compiler/src/dmd/backend/exh.d
  compiler/src/dmd/backend/newman.d
  compiler/src/dmd/backend/out.d
  compiler/src/dmd/backend/pdata.d
Labels: auto-merge, Refactoring, Backend

#15166 Remove extern variables from ty.d
  compiler/src/dmd/backend/ty.d
  compiler/src/dmd/backend/var.d
Labels: auto-merge, Refactoring, Backend

#15117 Simplify _d_isbaseof by calling _d_isbaseof2
  druntime/src/rt/cast_.d
Labels: auto-merge

#15167 Remove version (HTOD) blocks
  compiler/src/dmd/backend/blockopt.d
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cdef.d
  compiler/src/dmd/backend/drtlsym.d
  compiler/src/dmd/backend/dtype.d
  compiler/src/dmd/backend/ee.d
  compiler/src/dmd/backend/el.d
  compiler/src/dmd/backend/elem.d
  compiler/src/dmd/backend/elpicpie.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/go.d
  compiler/src/dmd/backend/nteh.d
  compiler/src/dmd/backend/obj.d
  compiler/src/dmd/backend/out.d
  compiler/src/dmd/backend/symbol.d
  compiler/src/dmd/backend/type.d
  compiler/src/dmd/backend/var.d
Labels: auto-merge, Refactoring, Backend

#15168 Fix Issue 23873 - [ICE] segfault on imported static if ; else auto x
  compiler/src/dmd/dimport.d
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/imports/import23873.d
  compiler/test/fail_compilation/test23873.d
Labels: Bug Fix

#15169 Fix C translation error in elem.d
  compiler/src/dmd/backend/elem.d
Labels: Backend

#15173 Remove function prototypes from backend pt5
  compiler/src/dmd/backend/cgen.d
  compiler/src/dmd/backend/code.d
  compiler/src/dmd/backend/mscoffobj.d
Labels: Refactoring, Backend

#15174 fix Issue 23879 - ImportC: Windows system headers use __alignof
  compiler/test/compilable/test23879.c
  druntime/src/importc.h
Labels: Bug Fix, Easy Review, ImportC

#15170 fix issues 20737 and 23014 - TLS variables unusable with -betterC/imp…
  compiler/src/dmd/backend/cod2.d
  compiler/src/dmd/backend/elpicpie.d
  compiler/test/runnable/betterc.d
  compiler/test/runnable/test23014.i
Labels: Bug Fix

#15155 Reduce FuncDeclaration size
  compiler/src/dmd/declaration.h
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/tests/cxxfrontend.cc
Labels: Refactoring

#15176 Deduplicate getting `TypeFunction` from `CallExp`
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/escape.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/optimize.d
Labels: Refactoring

#15171 Remove version SCPP_HTOD blocks
  compiler/src/dmd/backend/dtype.d
  compiler/src/dmd/backend/elem.d
  compiler/src/dmd/backend/elpicpie.d
  compiler/src/dmd/backend/symbol.d
Labels: Refactoring, Backend

#15178 Remove function prototypes from backend pt6
  compiler/src/dmd/backend/code.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/symbol.d
Labels: Refactoring, Backend

#14641 Fix Issue 23475 - confusing printf deprecation message with ulong/lon…
  compiler/src/dmd/chkformat.d
  compiler/test/fail_compilation/chkformat.d
Labels: Enhancement, Bug Fix, Ready To Merge

#15181 Clean up old imports/versions in backend
  compiler/src/dmd/backend/blockopt.d
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cdef.d
  compiler/src/dmd/backend/cgcod.d
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/backend/cgen.d
  compiler/src/dmd/backend/cgobj.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/dcgcv.d
  compiler/src/dmd/backend/ee.d
  compiler/src/dmd/backend/elem.d
  compiler/src/dmd/backend/evalu8.d
  compiler/src/dmd/backend/gother.d
  compiler/src/dmd/backend/newman.d
  compiler/src/dmd/backend/nteh.d
  compiler/src/dmd/backend/out.d
  compiler/src/dmd/backend/var.d
Labels: Refactoring, Backend

#15184 Try to fix g++ failures phrasing command differently
  .github/workflows/runnable_cxx.yml
Labels: auto-merge, Bug Fix, auto-merge-squash

#15185 Remove function prototypes from backend pt7
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/var.d
Labels: Refactoring, Backend

#15180 Rename `backend/out.d` to `dout.d`
  compiler/src/build.d
  compiler/src/dmd/backend/README.md
  compiler/src/dmd/backend/dout.d
Labels: auto-merge, Refactoring, Backend

#15177 Fix Issue 23882 - ICE (segfault) on nasty alias this code
  compiler/src/dmd/dcast.d
  compiler/test/fail_compilation/test23882.d
Labels: Bug Fix

#15179 Fix Issue 23874 - -profile=gc segfaults / ICE regression - part 2
  compiler/src/dmd/dsymbolsem.d
  compiler/test/compilable/test23874.d
Labels: Bug Fix

#15172 fix Issue 23875 23880
  compiler/src/dmd/cparse.d
  compiler/src/dmd/initsem.d
  compiler/test/compilable/test23875.c
  compiler/test/fail_compilation/test23875.c
  druntime/src/importc.h
Labels: Bug Fix, Easy Review

#15099 Fix Issue 22760 - Segmentation fault in CppMangleVisitor.template_arg
  compiler/src/dmd/cppmangle.d
  compiler/test/compilable/test22760.d
Labels: Bug Fix

#15198 fix char type in core.internal.string
  druntime/src/core/internal/string.d
Labels: auto-merge, Easy Review

#15190 fix Issue 23886 - ImportC preprocessor directive #ident not supported
  compiler/src/dmd/cparse.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/test/fail_compilation/test23886.i
Labels: Enhancement, Easy Review, ImportC

#15191 Issue 23889 - ImportC: alloca() not supported
  compiler/test/runnable/test23889.c
  druntime/src/importc.h
Labels: Easy Review, ImportC

#15194 Fix 'overloads' error when there are no overloads
  compiler/src/dmd/func.d
  compiler/test/fail_compilation/bug9631.d
  compiler/test/fail_compilation/constraints_aggr.d
  compiler/test/fail_compilation/constraints_func1.d
  compiler/test/fail_compilation/constraints_func2.d
  compiler/test/fail_compilation/constraints_func3.d
  compiler/test/fail_compilation/constraints_func4.d
  compiler/test/fail_compilation/diag13942.d
  compiler/test/fail_compilation/diag16977.d
  compiler/test/fail_compilation/diag20268.d
  compiler/test/fail_compilation/diag23355.d
  compiler/test/fail_compilation/diag8101.d
  compiler/test/fail_compilation/diag8648.d
  compiler/test/fail_compilation/diag9004.d
  compiler/test/fail_compilation/diagin.d
  compiler/test/fail_compilation/fail12744.d
  compiler/test/fail_compilation/fail14669.d
  compiler/test/fail_compilation/fail162.d
  compiler/test/fail_compilation/fail20730b.d
  compiler/test/fail_compilation/fail236.d
  compiler/test/fail_compilation/fail8009.d
  compiler/test/fail_compilation/fail95.d
  compiler/test/fail_compilation/ice11856_1.d
  compiler/test/fail_compilation/ice14130.d
  compiler/test/fail_compilation/ice14907.d
  compiler/test/fail_compilation/ice6538.d
  compiler/test/fail_compilation/ice9284.d
  compiler/test/fail_compilation/named_arguments_error.d
  compiler/test/fail_compilation/test19107.d
Labels: auto-merge

#15189 Remove function prototypes from backend pt10
  compiler/src/dmd/backend/cc.d
Labels: auto-merge, Refactoring, Backend

#15200 Remove function prototypes from backend pt11
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cgcv.d
  compiler/src/dmd/backend/cgen.d
  compiler/src/dmd/backend/iasm.d
  compiler/src/dmd/backend/machobj.d
  compiler/src/dmd/backend/obj.d
  compiler/src/dmd/backend/util2.d
Labels: auto-merge, Refactoring, Backend

#15201 Remove old copyright notice
  compiler/src/dmd/backend/cdef.d
Labels: auto-merge, Refactoring, Backend

#15203 Add test for "static import cannot have an import bind list"
  compiler/test/fail_compilation/static_import.d
Labels: auto-merge

#15195 embed DMD VERSION in object file
  compiler/src/dmd/backend/cgobj.d
  compiler/src/dmd/backend/elfobj.d
  compiler/src/dmd/backend/machobj.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/backend/obj.d
  compiler/src/dmd/glue.d
Labels: Easy Review

#15199 reduce Loc.sizeof by 8 bytes
  compiler/src/dmd/doc.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.h
  compiler/src/dmd/lexer.d
  compiler/src/dmd/location.d
  compiler/src/dmd/s2ir.d
  compiler/test/unit/interfaces/check_implementations_20861.d
  compiler/test/unit/objc/protocols/diagnostic_messages.d
  compiler/test/unit/objc/protocols/optional_methods.d
Labels: Refactoring

#15206 optimize idPool() a bit
  compiler/src/dmd/compiler.d
  compiler/src/dmd/cond.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/func.d
  compiler/src/dmd/identifier.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/tokens.d
  compiler/src/dmd/typesem.d
Labels: auto-merge, Easy Review, ImportC

#15209 Fix 23908 - confusing nonexistent import hint on cyclic import
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/imports/spell23908a.d
  compiler/test/fail_compilation/imports/spell23908b.d
  compiler/test/fail_compilation/spell23908.d
Labels: auto-merge, Bug Fix, Diagnostic Messages

#15210 [Stable] Try to fix g++ failures phrasing command differently
  .github/workflows/runnable_cxx.yml
Labels: Bug Fix

#15211 Encapsulate `Loc` member access
  compiler/src/dmd/doc.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.h
  compiler/src/dmd/lexer.d
  compiler/src/dmd/location.d
Labels: auto-merge, Refactoring

#15216 chore(pre-commit): update hooks
  .pre-commit-config.yaml
Labels: Trivial, auto-merge, Easy Review

#15215 Remove function prototypes from backend pt13
  compiler/src/dmd/backend/cdef.d
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/backend/cgreg.d
  compiler/src/dmd/backend/cgsched.d
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/cod2.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/cod4.d
  compiler/src/dmd/backend/dcgcv.d
  compiler/src/dmd/backend/dtype.d
  compiler/src/dmd/backend/dwarfdbginf.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/gsroa.d
  compiler/src/dmd/backend/nteh.d
  compiler/src/dmd/e2ir.d
Labels: auto-merge, Refactoring, Backend

#10958 Fix Issue 20687 - Allow member function address as const initializer
  compiler/src/dmd/todt.d
  compiler/test/runnable/test20687.d
Labels: Needs Approval, auto-merge, Bug Fix

#15207 Fix Issue 23905 - Initialization of SumType with opaque enum causes ICE
  compiler/src/dmd/denum.d
  compiler/test/fail_compilation/test23905.d
Labels: Bug Fix

#15122 Allow `alias this` to use assignment-style syntax
  changelog/dmd.alias-this-syntax.dd
  compiler/src/dmd/parse.d
  compiler/test/compilable/aliasdecl.d
  compiler/test/fail_compilation/diag9574.d
Labels: auto-merge

#15217 Turn overloading extern(C) functions into an error
  changelog/dmd.extern-c-overload.dd
  compiler/src/dmd/semantic2.d
  compiler/test/compilable/test18385.d
  compiler/test/fail_compilation/fail23626a.d
  compiler/test/fail_compilation/fail2789.d
  compiler/test/fail_compilation/test18385.d
Labels: auto-merge, Deprecation -> Error

#15218 Remove function prototype from backend pt14
  compiler/src/dmd/backend/blockopt.d
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cgcv.d
  compiler/src/dmd/backend/cgobj.d
Labels: auto-merge, Refactoring, Backend

#15192 Fix Issue 23900 - @safe is allowed in inline asm
  compiler/src/dmd/statementsem.d
  compiler/test/compilable/test12979a.d
  compiler/test/fail_compilation/fail327.d
Labels: auto-merge, Bug Fix

#15219 Remove function prototypes from backend pt15
  compiler/src/dmd/backend/cgcod.d
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/backend/cgobj.d
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/code_x86.d
  compiler/src/dmd/backend/drtlsym.d
  compiler/src/dmd/backend/dwarf.d
  compiler/src/dmd/backend/evalu8.d
  compiler/src/dmd/backend/fp.d
  compiler/src/dmd/backend/gloop.d
  compiler/src/dmd/backend/rtlsym.d
  compiler/src/dmd/backend/util2.d
Labels: Refactoring, Backend

#15208 Better UFCS failure diagnostic
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/test/fail_compilation/ice11856_1.d
  compiler/test/fail_compilation/ufcs.d
Labels: Diagnostic Messages

#15221 Remove function prototypes from backend pt16
  compiler/src/dmd/backend/el.d
Labels: Refactoring, Backend

#15222 backend: Remove old MEM_ aliases
  compiler/src/dmd/backend/blockopt.d
  compiler/src/dmd/backend/cdef.d
  compiler/src/dmd/backend/dtype.d
  compiler/src/dmd/backend/elem.d
  compiler/src/dmd/backend/symbol.d
  compiler/src/dmd/backend/symtab.d
Labels: Refactoring, Backend

#15213 Don't allocate argument list on the stack
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/opover.d
  compiler/src/dmd/statementsem.d
Labels: auto-merge

#15226 Remove backend/md5.di
  compiler/src/dmd/backend/md5.di
Labels: auto-merge, Refactoring, Backend

#15227 Remove function prototypes from backend pt17
  compiler/src/dmd/backend/cod4.d
  compiler/src/dmd/backend/code.d
  compiler/src/dmd/backend/divcoeff.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/dmsc.d
Labels: auto-merge, Refactoring, Backend

#15229 Replace gluelayer prototypes with imports
  compiler/src/dmd/gluelayer.d
Labels: auto-merge, Refactoring

#12596 move apply from apply to aggregate
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/apply.d
  compiler/src/dmd/dclass.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/tocvdebug.d
Labels: auto-merge, Easy Review, Refactoring

#15228 Consolidate frontend 'imports' of the backend
  compiler/src/dmd/backend/cgcod.d
  compiler/src/dmd/backend/global.d
Labels: Refactoring, Backend

#15230 Simplify opcost table generation
  compiler/src/dmd/backend/oper.d
Labels: auto-merge, Refactoring, Backend

#15232 Remove version (SCPP) blocks
  compiler/src/dmd/backend/blockopt.d
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cdef.d
  compiler/src/dmd/backend/cgcod.d
  compiler/src/dmd/backend/cgcs.d
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/backend/cgen.d
  compiler/src/dmd/backend/cgobj.d
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/cod2.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/cod4.d
  compiler/src/dmd/backend/dcgcv.d
  compiler/src/dmd/backend/debugprint.d
  compiler/src/dmd/backend/dout.d
  compiler/src/dmd/backend/dwarfdbginf.d
  compiler/src/dmd/backend/ee.d
  compiler/src/dmd/backend/el.d
  compiler/src/dmd/backend/elfobj.d
  compiler/src/dmd/backend/evalu8.d
  compiler/src/dmd/backend/gother.d
  compiler/src/dmd/backend/machobj.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/backend/nteh.d
  compiler/src/dmd/backend/ptrntab.d
  compiler/src/dmd/backend/symbol.d
  compiler/src/dmd/backend/type.d
  compiler/src/dmd/backend/var.d
Labels: auto-merge, Refactoring, Backend

#14664 Translate `_d_newitem{U,T,iT}` to a template
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  druntime/src/core/lifetime.d
  druntime/src/object.d
  druntime/src/rt/lifetime.d
  druntime/src/rt/tracegc.d
  druntime/test/profile/bothgc.log.exp
  druntime/test/profile/bothnew.def.exp
  druntime/test/profile/myprofilegc.log.freebsd.32.exp
  druntime/test/profile/myprofilegc.log.freebsd.64.exp
  druntime/test/profile/myprofilegc.log.linux.32.exp
  druntime/test/profile/myprofilegc.log.linux.64.exp
  druntime/test/profile/myprofilegc.log.osx.32.exp
  druntime/test/profile/myprofilegc.log.osx.64.exp
Labels: 72h no objection -> merge

#15233 rename `apply.d` -> `postordervisitor.d`
  compiler/src/build.d
  compiler/src/dmd/README.md
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/dclass.d
  compiler/src/dmd/delegatize.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/foreachvar.d
  compiler/src/dmd/inline.d
  compiler/src/dmd/inlinecost.d
  compiler/src/dmd/nogc.d
  compiler/src/dmd/ob.d
  compiler/src/dmd/postordervisitor.d
  compiler/src/dmd/sideeffect.d
  compiler/src/dmd/tocvdebug.d
Labels: auto-merge-squash

#15235 remove need for Expression.parens part 1
  compiler/src/dmd/parse.d
Labels: auto-merge, Easy Review, Refactoring

#15238 merge stable
  VERSION
  compiler/src/dmd/backend/cod2.d
  compiler/src/dmd/backend/elpicpie.d
  compiler/src/dmd/cppmangle.d
  compiler/src/dmd/dcast.d
  compiler/src/dmd/denum.d
  compiler/src/dmd/dimport.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/imports/library.c
  compiler/test/compilable/test22760.d
  compiler/test/compilable/test23874.d
  compiler/test/compilable/test23913.d
  compiler/test/fail_compilation/imports/import23873.d
  compiler/test/fail_compilation/test23873.d
  compiler/test/fail_compilation/test23882.d
  compiler/test/fail_compilation/test23905.d
  compiler/test/runnable/betterc.d
  compiler/test/runnable/test23014.i
Labels: auto-merge, Bug Fix, stable -> master

#15239 Fix Issue 23912 - Destructor disables scope inference
  compiler/src/dmd/expression.d
  compiler/test/compilable/test23912.d
Labels: auto-merge, Bug Fix

#15237 remove e.parens part 2
  compiler/src/dmd/parse.d
Labels: auto-merge, Easy Review, Refactoring

#15236 Remove version (MARS) blocks pt1
  compiler/src/dmd/backend/aarray.d
  compiler/src/dmd/backend/backconfig.d
  compiler/src/dmd/backend/blockopt.d
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cdef.d
  compiler/src/dmd/backend/cgcod.d
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/backend/cgobj.d
  compiler/src/dmd/backend/cgxmm.d
  compiler/src/dmd/backend/cod1.d
  compiler/src/dmd/backend/cod2.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/codebuilder.d
  compiler/src/dmd/backend/cv8.d
  compiler/src/dmd/backend/dcgcv.d
Labels: Refactoring, Backend

#15244 Fix optional type & parameters for `function` literal
  compiler/src/dmd/parse.d
  compiler/test/runnable/funclit.d
Labels: auto-merge

#15247 Remove version (MARS) blocks pt2
  compiler/src/dmd/backend/cgobj.d
  compiler/src/dmd/backend/dcgcv.d
  compiler/src/dmd/backend/debugprint.d
  compiler/src/dmd/backend/dout.d
  compiler/src/dmd/backend/drtlsym.d
  compiler/src/dmd/backend/dtype.d
  compiler/src/dmd/backend/dvarstats.d
Labels: auto-merge, Refactoring, Backend

#15246 Make atomicStore work with -preview=nosharedaccess
  compiler/test/compilable/atomic_store_2_shared_classes.d
  druntime/src/core/atomic.d
Labels: auto-merge

#15248 Remove version (MARS) blocks pt3
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/backend/dwarfdbginf.d
  compiler/src/dmd/backend/ee.d
  compiler/src/dmd/backend/el.d
  compiler/src/dmd/backend/elem.d
  compiler/src/dmd/backend/elfobj.d
  compiler/src/dmd/backend/elpicpie.d
  compiler/src/dmd/backend/evalu8.d
  compiler/src/dmd/backend/go.d
  compiler/src/dmd/backend/iasm.d
  compiler/src/dmd/backend/inliner.d
  compiler/src/dmd/backend/machobj.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/backend/newman.d
  compiler/src/dmd/backend/nteh.d
  compiler/src/dmd/backend/pdata.d
  compiler/src/dmd/backend/symbol.d
  compiler/src/dmd/backend/util2.d
  compiler/src/dmd/backend/var.d
Labels: auto-merge, Refactoring, Backend

#15249 fix Issue 23928 - improve error msg: scope variable s assigned to non…
  compiler/src/dmd/escape.d
  compiler/test/fail_compilation/retscope.d
  compiler/test/fail_compilation/test20245.d
Labels: Enhancement, auto-merge, Easy Review, Diagnostic Messages

#15251 Remove unused backend.util2 functions
  compiler/src/dmd/backend/dcgcv.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/gloop.d
  compiler/src/dmd/backend/go.d
  compiler/src/dmd/backend/util2.d
Labels: auto-merge, Easy Review, Refactoring, Backend

#15252 Remove backend/newman.d
  compiler/src/.dscanner.ini
  compiler/src/build.d
  compiler/src/dmd/backend/README.md
  compiler/src/dmd/backend/newman.d
Labels: auto-merge, Refactoring, Backend

#15188 Remove function prototypes from backend pt9
  compiler/src/dmd/backend/dtype.d
  compiler/src/dmd/backend/type.d
Labels: auto-merge, Refactoring, Backend

#15253 Remove need to set version=MARS
  compiler/src/build.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/func.d
  compiler/src/dmd/globals.d
  compiler/src/dmd/gluelayer.d
  compiler/src/dmd/iasm.d
Labels: Refactoring

#15254 Remove function prototypes from backend pt18
  compiler/src/dmd/backend/type.d
Labels: auto-merge, Refactoring, Backend

#15255 Remove function prototypes from backend pt19
  compiler/src/dmd/backend/type.d
Labels: auto-merge, Refactoring, Backend

#15256 Remove function prototypes from backend pt20
  compiler/src/dmd/backend/type.d
Labels: auto-merge, Refactoring, Backend

#15258 Remove function prototypes from backend pt21
  compiler/src/dmd/backend/type.d
Labels: auto-merge, Refactoring, Backend

#15259 Remove ph2.d
  compiler/src/build.d
  compiler/src/dmd/backend/README.md
  compiler/src/dmd/backend/backconfig.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/ph2.d
  compiler/src/dmd/backend/util2.d
Labels: auto-merge, Refactoring, Backend

#15260 Remove function prototypes from backend pt22
  compiler/src/dmd/backend/cv8.d
  compiler/src/dmd/backend/elfobj.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/backend/obj.d
  compiler/src/dmd/backend/pdata.d
Labels: auto-merge, Refactoring, Backend

#15261 Remove function prototypes from backend pt23
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cgobj.d
  compiler/src/dmd/backend/cod2.d
  compiler/src/dmd/backend/filespec.d
  compiler/src/dmd/backend/mem.d
Labels: auto-merge, Refactoring, Backend

#15262 Remove function prototypes from backend pt24
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/dwarfdbginf.d
  compiler/src/dmd/backend/elfobj.d
Labels: auto-merge, Refactoring, Backend

#15265 prolog_namedArgs
  compiler/src/dmd/backend/cgcod.d
  compiler/src/dmd/backend/cod3.d
Labels: auto-merge, Easy Review, Refactoring

#15268 add visit method in transitive visitor for static foreach
  compiler/src/dmd/frontend.h
  compiler/src/dmd/transitivevisitor.d
Labels: auto-merge

#15270 remove MAXLL and MINLL
  compiler/src/dmd/backend/cod3.d
Labels: Easy Review, Refactoring

#15271 write_bytes p should be const
  compiler/src/dmd/backend/cgobj.d
  compiler/src/dmd/backend/elfobj.d
  compiler/src/dmd/backend/machobj.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/backend/obj.d
Labels: auto-merge, Easy Review, Refactoring

#15272 convert actionTable to pointer to Barray
  compiler/src/dmd/backend/blockopt.d
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/dwarfeh.d
  compiler/src/dmd/s2ir.d
Labels: auto-merge, Easy Review, Refactoring

#15267 fix Issue 21425 - Using va_start twice results in wrong values
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/oper.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/glue.d
  compiler/test/runnable/variadic.d
Labels: auto-merge, Bug Fix

#15275 rename cod3_EA to more sensible hasModregm
  compiler/src/dmd/backend/cgsched.d
  compiler/src/dmd/backend/cod3.d
Labels: auto-merge, Easy Review, Refactoring

#15276 Remove unused Darwin version in alloca
  druntime/src/rt/alloca.d
Labels: auto-merge, Refactoring

#15273 Bswitch to D array
  compiler/src/dmd/backend/blockopt.d
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cod3.d
  compiler/src/dmd/backend/debugprint.d
  compiler/src/dmd/s2ir.d
Labels: Refactoring

#15277 [REFACTOR] Remove unused DOS386 and Unix in alloca
  druntime/src/rt/alloca.d
Labels: auto-merge, Refactoring

#15278 fix Issue 23936 - ImportC: pragma pack is not working for structs
  compiler/src/dmd/cparse.d
  compiler/test/compilable/pragmapack.c
  compiler/test/compilable/test23936.i
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#15279 fix Issue 23935 - ImportC: __pragma not allowed between struct and ta…
  compiler/src/dmd/cparse.d
  compiler/test/compilable/test23935.i
Labels: Bug Fix, Easy Review, ImportC

#15283 Fix issue 23948 - __FILE__ and __MODULE__ cannot be implicitly converted to const(char)* as default paramenter
  compiler/src/dmd/expression.d
  compiler/test/compilable/test23948.d
Labels: Enhancement

#15285 Fix issue 23949 - core.stdc.assert_ for FreeBSD is incorrect
  druntime/src/core/stdc/assert_.d
Labels: Enhancement, auto-merge, Bug Fix
