Repository dlang/dmd, pull requests merged in 2023-10, with the labels that each got.

#15641 VoidInitExp doesn't need its own toChars()
  compiler/src/dmd/ctfe.h
  compiler/src/dmd/expression.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
Labels: Easy Review, Refactoring

#15568 make D great again
  compiler/src/dmd/blockexit.d
  compiler/test/compilable/testpull1810.d
  compiler/test/compilable/warn12809.d
  compiler/test/fail_compilation/test20522.d
Labels: Enhancement, Trivial, Bug Fix

#15643 eliminate toChars() from Initializer
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/init.d
  compiler/src/dmd/init.h
  compiler/src/dmd/initsem.d
  compiler/src/dmd/json.d
  compiler/src/dmd/optimize.d
  compiler/src/dmd/statementsem.d
Labels: Easy Review, Refactoring

#15642 eliminate toChars() from Statement
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/statement.d
  compiler/src/dmd/statement.h
Labels: Easy Review, Refactoring

#15644 fix Issue 24171 - [REG 2.100] Segfault compiling an empty ddoc file
  compiler/src/dmd/doc.d
  compiler/test/compilable/extra-files/ddoc24171.dd
  compiler/test/compilable/test24171.sh
Labels: Regression, Bug Fix

#15649 Fix issue 19460 - C style cast error has wrong line number for functions
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/ccast.d
Labels: Bug Fix

#15651 Fix issue 24174 - [CTFE] goto within with statements & catch blocks cause a infinite loop
  compiler/src/dmd/dinterpret.d
  compiler/test/compilable/issue24174.d
Labels: Bug Fix

#15654 fix Issue 24173 - ImportC: add Microsoft iNN integer literal suffixes
  compiler/src/dmd/lexer.d
  compiler/test/fail_compilation/test24173.c
Labels: Enhancement, Easy Review, ImportC

#15646 remove error() from Expression
  compiler/src/dmd/arrayop.d
  compiler/src/dmd/attrib.d
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/constfold.d
  compiler/src/dmd/ctfeexpr.d
  compiler/src/dmd/dcast.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/dmangle.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/importc.d
  compiler/src/dmd/initsem.d
  compiler/src/dmd/inline.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/mustuse.d
  compiler/src/dmd/nogc.d
  compiler/src/dmd/objc.d
  compiler/src/dmd/opover.d
  compiler/src/dmd/optimize.d
  compiler/src/dmd/semantic2.d
  compiler/src/dmd/sideeffect.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/staticcond.d
  compiler/src/dmd/todt.d
  compiler/src/dmd/traits.d
  compiler/src/dmd/typesem.d
  compiler/test/fail_compilation/fail235.d
  compiler/test/fail_compilation/ice6538.d
Labels: Easy Review, Refactoring

#15656 Fix issue 11070 - Allow declaration statement in a switch expression
  compiler/src/dmd/astbase.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/statement.d
  compiler/src/dmd/statement.h
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/issue11070.d
  compiler/test/runnable/issue11070.d
Labels: Enhancement, Needs Changelog, New Language Feature

#15657 try out replacing Dsymbol.error()
  compiler/src/dmd/access.d
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/main.d
Labels: Easy Review, Refactoring

#15659 try out replacing Dsymbol.error() part 3
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/dmangle.d
Labels: Easy Review, Refactoring

#15663 try out replacing Dsymbol.error() part 5
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dstruct.d
  compiler/src/dmd/dsymbol.d
  compiler/test/unit/frontend.d
Labels: Easy Review, Refactoring

#15658 try out replacing Dsymbol.error() part 2
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/aggregate.h
  compiler/src/dmd/attrib.d
  compiler/src/dmd/clone.d
  compiler/src/dmd/cppmangle.d
  compiler/src/dmd/cppmanglewin.d
  compiler/src/dmd/dclass.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/denum.d
  compiler/src/dmd/dimport.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/parse.d
Labels: Easy Review, Refactoring

#15664 try out replacing Dsymbol.error() part 6
  compiler/src/dmd/dsymbolsem.d
Labels: Easy Review, Refactoring

#15668 try out replacing Dsymbol.error() part 7
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/dversion.d
  compiler/src/dmd/expressionsem.d
Labels: Easy Review, Refactoring

#15670 try out replacing Dsymbol.error() part 8
  compiler/src/dmd/func.d
  compiler/src/dmd/nspace.d
Labels: Easy Review, Refactoring

#15671 try out replacing Dsymbol.error() part 9
  compiler/src/dmd/ob.d
  compiler/src/dmd/objc.d
  compiler/src/dmd/optimize.d
Labels: Easy Review, Refactoring

#15652 fix issue 3396 - call to unimplemented abstract method lead to linkin…
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/issue3396.d
Labels: Bug Fix

#15674 try out replacing Dsymbol.error() part 10
  compiler/src/dmd/semantic2.d
  compiler/src/dmd/semantic3.d
Labels: Easy Review, Refactoring

#15676 [dtoh] dont use __ for anonymous member
  compiler/src/build.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/frontend.h
Labels: Trivial, Easy Review

#15675 try out replacing Dsymbol.error() part 11
  compiler/src/dmd/glue.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/toobj.d
  compiler/src/dmd/traits.d
  compiler/src/dmd/typesem.d
Labels: Easy Review, Refactoring

#15677 try out replacing Dsymbol.error() The Final Chapter
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/denum.d
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dsymbol.h
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/errors.d
  compiler/src/dmd/frontend.h
Labels: Easy Review, Refactoring

#15678 use isDefaultInitExp() instead of isDefaultInitOp()
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
Labels: Easy Review, Refactoring

#15679 fix issue 23686 - TemplateAliasParam default value possibly considere…
  compiler/src/dmd/dtemplate.d
  compiler/test/fail_compilation/b23686.d
Labels: Bug Fix

#15682 use ErrorSink in canthrow.d
  compiler/src/dmd/blockexit.d
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/traits.d
  compiler/src/tests/cxxfrontend.cc
Labels: Easy Review, Refactoring

#15681 fix issue 23865 - ICE on attempt to insert an non overloadable symbol…
  compiler/src/dmd/declaration.d
  compiler/test/compilable/test20039.d
  compiler/test/fail_compilation/ice23865.d
  compiler/test/fail_compilation/test18480.d
Labels: Bug Fix

#15683 Fix ICE: failed to detect static initialization of associative array
  compiler/src/dmd/ctfeexpr.d
  compiler/src/dmd/declaration.d
  compiler/test/runnable/staticaa.d
Labels: GDC, Blocking Other Work, Bug Fix, New Language Feature

#15691 fix issue 23733 - Can't use template type parameter as type of alias …
  compiler/src/dmd/dtemplate.d
  compiler/test/runnable/template9.d
Labels: Bug Fix

#15692 remove unnecessary imports from root.rootobject
  compiler/src/dmd/root/rootobject.d
Labels: Easy Review, Refactoring

#15693 fix issue 24188 - ICE with missing imported symbol
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/ice24188.d
  compiler/test/fail_compilation/ice24188_a/ice24188_c.d
Labels: Bug Fix

#15698 test: Add missing EXTRA_FILES directives to tests
  compiler/test/compilable/test20008.d
  compiler/test/compilable/test23789.d
  compiler/test/runnable/test23837.d
Labels: GDC, Trivial, Blocking Other Work

#15700 Catch need not be a RootObject
  compiler/src/dmd/astbase.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/statement.d
  compiler/src/dmd/statement.h
Labels: Easy Review, Refactoring

#15697 Fix out of sync C++ headers for GDC and LDC
  compiler/src/dmd/doc.h
  compiler/src/dmd/errors.h
  compiler/src/dmd/hdrgen.h
  compiler/src/dmd/json.h
Labels: GDC, LDC, Blocking Other Work, DMD as a library

#15701 Revert "Catch need not be a RootObject"
  compiler/src/dmd/astbase.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/statement.d
  compiler/src/dmd/statement.h
Labels: GDC, LDC, Blocking Other Work, DMD as a library

#15704 eliminate static constructor in mustuse.d
  compiler/src/dmd/mustuse.d
Labels: Easy Review, Refactoring

#15706 C++: Use d_size_t in gendocfile declaration
  compiler/src/dmd/doc.h
Labels: GDC, DMD as a library

#15707 fix Issue 24181 - reading double parameter from RCX rather than XMM1
  compiler/src/dmd/backend/cod1.d
  compiler/test/runnable/test24181.c
Labels: Bug Fix

#15709 move `firstComma` to `dinterpret.d`
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/expression.d
Labels: Trivial, Refactoring

#15705 Fix Issue 24168 - Corrupted if TLS values are passed in ref parameters
  compiler/src/dmd/backend/elpicpie.d
  compiler/test/runnable/issue24168.d
Labels: Bug Fix

#15716 Remove D1 warning about length shadowing local variables
  compiler/src/dmd/dscope.d
Labels: Easy Review, Diagnostic Messages, D1

#15717 Fix more out of sync C++ headers
  compiler/src/dmd/statement.h
Labels: GDC, LDC, DMD as a library

#15721 Remove conditionally disabled warnings from setUnsafePreview
  compiler/src/dmd/func.d
Labels: Trivial, Diagnostic Messages

#15720 Remove conditionally disabled warnings from blockexit pass
  compiler/src/dmd/blockexit.d
Labels: Trivial, Diagnostic Messages

#15719 Remove conditionally disabled warnings from semantic pass
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
Labels: Trivial, Diagnostic Messages

#15718 Remove warning for discarded return value
  compiler/src/dmd/sideeffect.d
  compiler/test/fail_compilation/fail3882.d
Labels: Diagnostic Messages

#15724 C++: Fix use of bool in C++ headers for fields
  compiler/src/dmd/aliasthis.h
  compiler/src/dmd/expression.h
  compiler/src/dmd/globals.h
  compiler/src/dmd/statement.h
Labels: GDC, DMD as a library

#15725 do not add __gshared to functions generated from C
  compiler/src/dmd/cparse.d
  compiler/test/compilable/ctod.i
  compiler/test/compilable/extra-files/ctod.di
Labels: Easy Review

#15728 C++: Mark many non-virtual 'final' methods as 'extern (D)'
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/aggregate.h
  compiler/src/dmd/attrib.h
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/cond.d
  compiler/src/dmd/cond.h
  compiler/src/dmd/dcast.d
  compiler/src/dmd/dclass.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dimport.d
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dscope.d
  compiler/src/dmd/dstruct.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/import.h
  compiler/src/dmd/init.h
  compiler/src/dmd/module.h
  compiler/src/dmd/mtype.d
  compiler/src/dmd/mtype.h
  compiler/src/dmd/objc.h
  compiler/src/dmd/scope.h
  compiler/src/dmd/sideeffect.d
  compiler/src/dmd/statement.d
  compiler/src/dmd/statement.h
  compiler/src/dmd/template.h
  compiler/src/dmd/tokens.d
  compiler/src/dmd/tokens.h
  compiler/src/tests/cxxfrontend.cc
Labels: GDC, LDC, extern (C/C++), DMD as a library

#15731 ImportC: align not set to default
  compiler/src/dmd/cparse.d
  compiler/test/compilable/ctod.i
Labels: ImportC

#15733 dmd.expression: Remove ::emplace function
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/frontend.h
  compiler/src/tests/cxxfrontend.cc
Labels: GDC, LDC, DMD as a library

#15736 fix Issue 24121 - ImportC: typedef enum fails to compile when generat…
  compiler/src/dmd/denum.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/test/compilable/ctod.i
Labels: Bug Fix

#15740 fix Issue 24199 - ImportC: generated .di file uses struct keyword whe…
  compiler/src/dmd/hdrgen.d
  compiler/test/compilable/ctod.i
Labels: Bug Fix, ImportC

#15743 Cirrus CI: Allow single remaining FreeBSD coverage job to fail (might be out of credits)
  .cirrus.yml
Labels: auto-merge

#15741 Add core.sys.linux.linux.if_packet.
  druntime/mak/COPY
  druntime/mak/SRCS
  druntime/src/core/sys/linux/linux/if_packet.d
Labels: auto-merge

#15747 Replace DMD-specific flags with GDC in error messages when IN_GCC
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/semantic3.d
  compiler/src/dmd/statementsem.d
Labels: GDC, auto-merge, Diagnostic Messages

#15748 Remove shortenedMethods from CompileEnv
  compiler/src/dmd/cli.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.h
  compiler/src/dmd/lexer.d
  compiler/src/dmd/main.d
  compiler/src/dmd/parse.d
Labels: GDC, auto-merge, Diagnostic Messages

#15750 fix Issue 24193 - Incorrect size of unions with bit fields
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/dstruct.d
  compiler/src/dmd/dsymbol.d
  compiler/test/compilable/dbitfield.d
Labels: auto-merge, Bug Fix

#15751 fix Issue 24187 - ImportC: _Float32 not defined
  compiler/test/compilable/fix24187.c
  druntime/src/importc.h
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#15749 dmd.typinf: Remove dependency on gluelayer
  compiler/src/dmd/asttypename.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/gluelayer.d
  compiler/src/dmd/tocsym.d
  compiler/src/dmd/todt.d
  compiler/src/dmd/toobj.d
  compiler/src/dmd/typinf.d
  compiler/src/dmd/typinf.h
  compiler/src/tests/cxxfrontend.cc
Labels: GDC, Refactoring

#15746 Add core.sys.linux.linux.if_arp.
  druntime/mak/COPY
  druntime/mak/SRCS
  druntime/src/core/sys/linux/linux/if_arp.d
Labels: auto-merge

#15754 Get rid of extra indirection for implictCastTo and castTo for expressions
  compiler/src/dmd/constfold.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/func.d
  compiler/src/dmd/optimize.d
Labels: auto-merge

#15755 Move expression.BinExp.checkOpAssignTypes to expressionsem
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
Labels: auto-merge

#15759 make purpose of alignmember() clearer
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/dclass.d
  compiler/src/dmd/toir.d
Labels: auto-merge, Easy Review, Refactoring

#15760 replace pointers in placeField() with refs
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/attrib.d
  compiler/src/dmd/declaration.d
Labels: auto-merge, Easy Review, Refactoring

#15762 toPrettyChars: optimize 1 component length
  compiler/src/dmd/dsymbol.d
Labels: auto-merge, Easy Review, Refactoring

#15764 Move expression.StringExp.toUTF8 to expressionsem
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
Labels: auto-merge

#15765 make placeField() and alignmember() free functions
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/attrib.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/toir.d
Labels: Easy Review, Refactoring
