Repository dlang/dmd, pull requests merged in 2024-08, with the labels that each got.

#16765 build.d: support machine hardware name aarch64
  compiler/src/build.d
Labels: auto-merge

#16767 escape.d: Remove special cases for STC.temp
  compiler/src/dmd/escape.d
Labels: auto-merge, Refactoring, dip1000

#16768 Fix bugzilla 24694 - [DIP1000] can escape stack pointer through struc…
  compiler/src/dmd/escape.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/test24694.d
Labels: Bug Fix, dip1000

#16769 update instr.d and disasmarm.d for AArch64
  compiler/src/dmd/backend/arm/disasmarm.d
  compiler/src/dmd/backend/arm/instr.d
Labels: Easy Review, Backend, Aarch64

#16770 Fix Bugzilla Issue 24687 - [REG2.110] Cannot cast string-imports to select overload anymore
  compiler/src/dmd/dcast.d
  compiler/test/compilable/import_exp.d
Labels: auto-merge, Bug Fix

#16771 Implement auto ref for local variables
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/diag9679.d
  compiler/test/runnable/declaration.d
Labels: auto-merge

#16773 Add reserved version identifier for Xtensa architecture
  compiler/src/dmd/cond.d
  compiler/test/fail_compilation/reserved_version.d
  compiler/test/fail_compilation/reserved_version_switch.d
Labels: auto-merge

#16774 druntime: move src/core/threadasm.S to src/core/thread/
  druntime/Makefile
  druntime/src/core/thread/threadasm.S
Labels: auto-merge

#16779 Also make deprecationSupplemental adhere to error limit
  compiler/src/dmd/errors.d
  compiler/test/compilable/deprecationlimit.d
Labels: Diagnostic Messages

#16780 Bugzilla 24700 - Don't search for mscoff .dp$B section over and over
  compiler/src/dmd/backend/mscoffobj.d
Labels: Refactoring, Industry

#16782 Print full CommaExp with -vcg-ast
  compiler/src/dmd/hdrgen.d
Labels: auto-merge

#16783 Require adjacent `auto ref` keywords
  changelog/dmd.auto-ref-adjacent.dd
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/diag9679.d
  druntime/src/core/lifetime.d
Labels: auto-merge, Deprecation

#16781 Fix bugzilla 24699 - [REG2.108] No short-circuit evaluation of mixing…
  compiler/src/dmd/dtemplate.d
  compiler/test/compilable/compile1.d
Labels: auto-merge, Bug Fix

#16788 Fix Bugzilla 24705 - Arguments of synchronized method are wrongly sha…
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/test22626.d
Labels: auto-merge, Bug Fix

#16787 Fix Bugzilla 24706 - Missing errors for first operand of comma expres…
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/misc1.d
  compiler/test/fail_compilation/must_use.d
Labels: auto-merge, Bug Fix

#16789 Fix bugzilla 24639 - ImportC: defines of negative constants not detec…
  compiler/src/dmd/cparse.d
  compiler/test/compilable/imports/defines.c
  compiler/test/compilable/testdefines.d
Labels: Enhancement

#16790 [NFC] [funcsem.d] use early continue, reduce nesting
  compiler/src/dmd/funcsem.d
Labels: Easy Review, Refactoring, auto-merge-squash

#16791 Fix Bugzilla 24707 - error message has bad parameter attribute order
  compiler/src/dmd/hdrgen.d
  compiler/test/compilable/extra-files/vcg-ast.d.cg
  compiler/test/fail_compilation/auto_ref_inout.d
  compiler/test/fail_compilation/fail20730b.d
  compiler/test/fail_compilation/varargsstc.d
Labels: Bug Fix

#16797 disasm86: add array overflow checks
  compiler/src/dmd/backend/x86/disasm86.d
Labels: auto-merge, Easy Review, Backend

#16800 Remove deprecation for bugzilla 22999
  changelog/dmd.deprecation-case.dd
  compiler/src/dmd/blockexit.d
  compiler/test/fail_compilation/test22999.d
Labels: Deprecation -> Error

#16796 Fix Bugzilla 24701 - No error produced from casted noreturn variable
  compiler/src/dmd/expressionsem.d
  compiler/test/runnable/noreturn2.d
Labels: auto-merge, Bug Fix

#16804 update disasmarm.d and instr.d
  compiler/src/dmd/backend/arm/instr.d
Labels: auto-merge, Backend, Aarch64

#16802 [Deprecation -> Error] destructor field attributes
  changelog/dmd.deprecation-dtor-fields.dd
  compiler/src/dmd/semantic3.d
  compiler/test/compilable/dtorfields_deprecation.d
Labels: Deprecation -> Error

#16806 Add closefrom declarations for freebsd, glibc, and, openbsd
  druntime/src/core/sys/freebsd/unistd.d
  druntime/src/core/sys/linux/unistd.d
  druntime/src/core/sys/openbsd/unistd.d
Labels: auto-merge

#16808 Optimize traits.d by factoring out two common sub-expressions when ev…
  compiler/src/dmd/traits.d
Labels: Trivial, Refactoring

#16669 [target.d] refactor 64bit logic
  compiler/src/dmd/dmsc.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/target.d
  compiler/src/dmd/todt.d
Labels: Easy Review, Refactoring

#16801 [Deprecation -> Error] nothrow function contracts that throw
  changelog/dmd.deprecation-throwing-contracts.dd
  compiler/src/dmd/semantic3.d
  compiler/test/fail_compilation/fail13123.d
Labels: Deprecation -> Error

#16813 [next edition] Error when aliasing a method of a variable
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/alias_instance_member.d
  compiler/test/fail_compilation/alias_instance_member2.d
Labels: auto-merge

#16387 Fix Bugzilla 21564 - assignment syntax for instantiating mixin templates
  compiler/src/dmd/parse.d
  compiler/test/runnable/mixin1.d
Labels: Enhancement, auto-merge, Needs Spec PR

#16817 [test/compileable/vastartend.c] use main function
  compiler/test/compilable/vastartend.c
Labels: auto-merge

#16819 initialize cgstate.allregs in cod3.d
  compiler/src/dmd/backend/code.d
  compiler/src/dmd/backend/x86/cgcod.d
  compiler/src/dmd/backend/x86/cod3.d
Labels: Easy Review, Refactoring, Backend

#16822 Fix bugzilla 24731 - IFTI cannot handle integer expressions
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/expression.d
  compiler/test/runnable/ifti.d
Labels: auto-merge, Bug Fix

#16821 Fix bugzilla 24733 - ImportC: `#pragma pack(pop)` restores wrong alignment
  compiler/src/dmd/cparse.d
  compiler/test/compilable/test24733.c
Labels: Bug Fix
