Repository dlang/dmd, pull requests merged in 2024-11, with the labels that each got.

#17049 Fix bugzilla issue 24153 - Inliner breaks -betterC by requiring TypeInfo
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/betterCinline.d
Labels: Bug Fix

#17047 Fix bugzilla issue 24841 - UTF-16 surrogates when used as an escape of a string should hint on error
  compiler/src/dmd/lexer.d
Labels: Enhancement

#17048 use ErrorSink on preFunctionParameters()
  compiler/src/dmd/expressionsem.d
Labels: Easy Review, Refactoring

#17046 use ErrorSink on errorSupplementalAttr()
  compiler/src/dmd/canthrow.d
  compiler/src/dmd/expressionsem.d
Labels: Easy Review, Refactoring

#17056 Fix bugzilla issue 24835.
  druntime/src/core/internal/traits.d
Labels: Bug Fix

#17055 Fix Bugzilla 24848 - bad parser diagnostic for a partial MulExp
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/binexperr.d
  compiler/test/fail_compilation/e15876_3.d
  compiler/test/fail_compilation/e15876_4.d
  compiler/test/fail_compilation/ice15855.d
  compiler/test/fail_compilation/ice8795.d
  compiler/test/fail_compilation/misc_parser_err_cov1.d
  compiler/test/fail_compilation/traits_alone.d
Labels: auto-merge, Bug Fix

#17043 add __traits getBitfieldOffset and getBitfieldWidth
  changelog/dmd.getBitfieldInfo.dd
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/src/dmd/traits.d
  compiler/test/fail_compilation/biterrors5.d
Labels: Enhancement, New Language Feature

#17053 Fix bugzilla issue 24846 - atomicLoad does not work for class arguments with -preview=nosharedaccess
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/test/compilable/atomic_loadstore_shared_classes.d
Labels: Bug Fix

#17058 fix(errors): align errorKindToString with SARIF level values
  compiler/src/dmd/sarif.d
  compiler/test/fail_compilation/sarif_test.d
  compiler/test/fail_compilation/sarifmultiple_test.d
Labels: auto-merge

#17059 Reduce imports in intrange.d
  compiler/src/dmd/intrange.d
Labels: auto-merge, Refactoring

#17060 Fix 24855 - VRP fails to prevent overflow after division
  compiler/src/dmd/intrange.d
  compiler/test/compilable/testVRP.d
  druntime/src/core/internal/gc/impl/conservative/gc.d
Labels: auto-merge, Bug Fix

#17061 [core.memory docs] Add warnings about uninitialized memory
  druntime/src/core/memory.d
Labels: auto-merge

#17062 expressionsem.d: Get rid of duplication for shift and binary bit-op expressions
  compiler/src/dmd/expressionsem.d
Labels: auto-merge

#17064 Bit-shift expressions: Cast scalar right-hand-sides to vectors if needed
  compiler/src/dmd/expressionsem.d
Labels: auto-merge

#17063 [stable] GitHub Actions: Bump macos-12 jobs to macos-13
  .github/workflows/main.yml
  .github/workflows/runnable_cxx.yml
  ci/README.md
Labels: auto-merge

#17065 fix bugzilla Issue 24861 - Vestige of 16 bit code being accidentally …
  compiler/src/dmd/backend/x86/cod2.d
Labels: auto-merge, Bug Fix, Easy Review, Backend

#17066 swap error and verror in ErrorSink
  compiler/src/dmd/errors.d
  compiler/src/dmd/errorsink.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/link.d
Labels: Easy Review, Refactoring

#17070 [stable] compilable/stdcheaders.c: Work around unsupported NAN in new WinSDK headers
  compiler/test/compilable/stdcheaders.c
Labels: auto-merge

#17069 Merge stable
  .github/workflows/main.yml
  .github/workflows/runnable_cxx.yml
  ci/README.md
  compiler/src/dmd/dcast.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/enumsem.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/src/dmd/lexer.d
  compiler/test/compilable/atomic_loadstore_shared_classes.d
  compiler/test/compilable/stdcheaders.c
  compiler/test/fail_compilation/diag24812.d
  compiler/test/fail_compilation/hexstring.d
  druntime/src/importc.h
Labels: Enhancement, auto-merge, Bug Fix, stable -> master

#17071 fix Bugzilla 24353 - add mutability check for foreach with opApply
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/test24353.d
Labels: Bug Fix

#16832 fix Bugzilla 24745 - improve associative array syntax error message
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/test24745.d
Labels: Enhancement

#17072 Untangling setUnsafe()
  compiler/src/dmd/escape.d
  compiler/src/dmd/safe.d
Labels: auto-merge, Refactoring

#17073 Adding block metadata facilities into the GC package
  druntime/mak/COPY
  druntime/mak/DOCS
  druntime/mak/SRCS
  druntime/src/core/internal/array/utils.d
  druntime/src/core/internal/gc/blockmeta.d
  druntime/src/rt/lifetime.d
Labels: auto-merge

#17075 Fix bugzilla issue# 24864: hasElaborateDestructor wrong with anonymous unions
  druntime/src/core/internal/traits.d
Labels: Bug Fix

#17074 split setFunctionToUnsafe() into two functions
  compiler/src/dmd/safe.d
Labels: auto-merge, Refactoring

#17076 dinterpret.d: Remove special case for `_d_arrayappend{cTX,T}`
  compiler/src/dmd/dinterpret.d
Labels: Refactoring

#17078 Reduce number of tried template instances for class, interface and AA…
  druntime/src/core/internal/traits.d
Labels: auto-merge

#17083 Fix Bugzilla 24872 - Assigning non-copyable value to array has no effect
  druntime/src/core/internal/array/arrayassign.d
Labels: Bug Fix

#17086 use va_list instead of template for vprintf
  compiler/src/dmd/mtype.d
Labels: auto-merge, Easy Review, Refactoring

#17089 small step towards AttributVfd2
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/safe.d
Labels: Refactoring

#17090 next step to AttributeVfd
  compiler/src/dmd/func.d
Labels: auto-merge, Refactoring

#17088 split AttributeViolation into two distinct uses
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/funcsem.d
  compiler/src/dmd/nogc.d
  compiler/src/dmd/safe.d
Labels: auto-merge, Refactoring

#17087 use OutBuffer to build and pass around strings
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/typesem.d
Labels: auto-merge, Easy Review, Refactoring

#17091 use OutBuffer for getMatchError()
  compiler/src/dmd/mtype.d
  compiler/src/dmd/typesem.d
Labels: auto-merge, Easy Review, Refactoring

#17093 should no longer need the else clause
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/func.d
Labels: auto-merge, Easy Review, Refactoring

#17082 Fix bugzilla issue 24871 - DDoc strips indent in triple slash comments
  compiler/src/dmd/lexer.d
  compiler/test/compilable/ddoc24871.d
  compiler/test/compilable/extra-files/ddoc24871.html
Labels: auto-merge, Bug Fix

#17094 Fix bugzilla 24845 - Compiler error when trying to assign to an AA va…
  compiler/src/dmd/expression.d
  compiler/test/compilable/compile1.d
  compiler/test/fail_compilation/fail6795.d
Labels: auto-merge, Bug Fix

#15343 Fix 23722 - Lambdas are mangled incorrectly when using multiple compi…
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/b19523.d
  compiler/test/fail_compilation/bug9631.d
  compiler/test/fail_compilation/constraints_defs.d
  compiler/test/fail_compilation/constraints_tmpl.d
  compiler/test/fail_compilation/cppvar.d
  compiler/test/fail_compilation/diag12829.d
  compiler/test/fail_compilation/diag15411.d
  compiler/test/fail_compilation/diag20268.d
  compiler/test/fail_compilation/diag9831.d
  compiler/test/fail_compilation/diag_funclit.d
  compiler/test/fail_compilation/fail11125.d
  compiler/test/fail_compilation/fail12236.d
  compiler/test/fail_compilation/fail12378.d
  compiler/test/fail_compilation/fail12908.d
  compiler/test/fail_compilation/fail13120.d
  compiler/test/fail_compilation/fail13424.d
  compiler/test/fail_compilation/fail17969.d
  compiler/test/fail_compilation/fail39.d
  compiler/test/fail_compilation/iasm1.d
  compiler/test/fail_compilation/ice10922.d
  compiler/test/fail_compilation/ice11822.d
  compiler/test/fail_compilation/ice11850.d
  compiler/test/fail_compilation/ice12235.d
  compiler/test/fail_compilation/ice8309.d
  compiler/test/fail_compilation/misc1.d
  compiler/test/fail_compilation/opapplyscope.d
  compiler/test/fail_compilation/previewin.d
  compiler/test/fail_compilation/retscope.d
  compiler/test/fail_compilation/test15306.d
  compiler/test/fail_compilation/test16193.d
  compiler/test/fail_compilation/test17451.d
  compiler/test/fail_compilation/test19107.d
  compiler/test/fail_compilation/test19971.d
  compiler/test/fail_compilation/test20719.d
  compiler/test/fail_compilation/test21912.d
  compiler/test/fail_compilation/test23170.d
  compiler/test/fail_compilation/testInference.d
  compiler/test/fail_compilation/var_func_attr.d
  compiler/test/runnable/imports/test23722b.d
  compiler/test/runnable/mangle.d
  compiler/test/runnable/test23722.d
  compiler/test/runnable/testkeyword.d
  compiler/test/runnable/traits.d
Labels: Bug Fix, WIP

#17044 Implement Safer D
  changelog/dmd.safer.dd
  compiler/src/dmd/cli.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.d
  compiler/src/dmd/globals.h
  compiler/src/dmd/safe.d
  compiler/src/dmd/statementsem.d
  compiler/test/compilable/previewhelp.d
  compiler/test/fail_compilation/safer.d
Labels: Enhancement, Needs Spec PR

#17096 Fix bugzilla 24883 - Speculative template overload error escapes with…
  compiler/src/dmd/templatesem.d
  compiler/test/compilable/rvalueref.d
Labels: auto-merge, Bug Fix

#17095 Fix bugzilla issue 24882 - COM class is allocated using GC not malloc
  changelog/dmd.isCOMClass.dd
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/src/dmd/traits.d
  compiler/test/runnable/test36.d
  druntime/src/core/lifetime.d
Labels: auto-merge, Bug Fix

#17099 Remove C++ bitflags / _padding fields from SCOPE
  compiler/src/dmd/dscope.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/scope.h
Labels: auto-merge, Refactoring
