Repository dlang/dmd, pull requests merged in 2024-06, with the labels that each got.

#16546 move cdcmp_flag to CGstate.cmp_flag
  compiler/src/dmd/backend/code.d
  compiler/src/dmd/backend/x86/cod2.d
  compiler/src/dmd/backend/x86/cod4.d
Labels: auto-merge, Easy Review, Refactoring, Backend

#16540 make X86 a positive affirmation
  compiler/src/dmd/dmdparams.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/frontend.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/link.d
  compiler/src/dmd/mars.d
  compiler/src/dmd/target.d
  compiler/src/dmd/target.h
  compiler/src/dmd/toir.d
Labels: Easy Review, Refactoring

#16548 redo setDefaultLibrary()
  compiler/src/dmd/main.d
  compiler/src/dmd/mars.d
Labels: Easy Review, Refactoring

#16549 add driverParams to parseCommandLine()
  compiler/src/dmd/main.d
  compiler/src/dmd/mars.d
Labels: Easy Review, Refactoring

#16550 [stable] Fix missing new CastExp field in C++ header
  compiler/src/dmd/expression.h
Labels: auto-merge

#16551 [stable] Don't needlessly cross-preprocess in 2 tests
  compiler/test/compilable/test24504.c
  compiler/test/compilable/test24511.d
Labels: auto-merge

#16553 merge stable
  VERSION
  changelog/dmd.alias-instance-member.dd
  changelog/dmd.bitfield-introspection.dd
  changelog/dmd.ctfeWrite.dd
  changelog/dmd.deprecation-limit.dd
  changelog/dmd.dtoh-windows.dd
  changelog/dmd.foreach-array-index-type.dd
  changelog/dmd.foreach-reverse-delegate-error.dd
  changelog/dmd.identifier-tables.dd
  changelog/dmd.importc-unicode.dd
  changelog/dmd.linker-error.dd
  changelog/dmd.omf-removed.dd
  changelog/druntime.core.sys.linux.sys.mount.dd
  changelog/druntime.removenostackcollect.dd
  changelog/druntime.thread-sleep-trusted.dd
  compiler/src/dmd/enumsem.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/test24504.c
  compiler/test/compilable/test24511.d
  compiler/test/compilable/test24560.d
Labels: Bug Fix, stable -> master

#16555 backend_init() gets const ref parameters
  compiler/src/dmd/dmsc.d
  compiler/src/dmd/main.d
  compiler/src/dmd/mars.d
  compiler/src/dmd/target.d
Labels: auto-merge, Easy Review, Refactoring

#16563 add arm tests
  compiler/test/runnable/arm.d
Labels: Easy Review, Backend, Aarch64

#16564 use ErrorSink in parseCommandLine()
  compiler/src/dmd/main.d
  compiler/src/dmd/mars.d
Labels: auto-merge, Easy Review, Refactoring

#16565 remove errors.d from mars.d
  compiler/src/dmd/main.d
  compiler/src/dmd/mars.d
Labels: Easy Review, Refactoring

#16567 continue with removing errors.d from mars.d
  compiler/src/dmd/main.d
  compiler/src/dmd/mars.d
Labels: auto-merge, Easy Review, Refactoring

#16568 compiler/test/unit/semantic/imports.d: call deinitializeDMD
  compiler/test/unit/semantic/imports.d
Labels: auto-merge

#16569 Fix bugzilla 24580 - ImportC: Asm label after attributes results in s…
  compiler/src/dmd/cparse.d
  compiler/test/compilable/testcstuff2.c
Labels: Enhancement, auto-merge

#16570 Fix bugzilla 24577 - Struct with constructor returned from C++ wrong
  compiler/src/dmd/target.d
  compiler/test/runnable_cxx/extra-files/cpp_nonpod_byval.cpp
  compiler/test/runnable_cxx/nonpod_byval.d
Labels: auto-merge, Bug Fix

#16573 remove unnecessary genmovreg() overloads
  compiler/src/dmd/backend/x86/cgcod.d
  compiler/src/dmd/backend/x86/cod3.d
Labels: Easy Review, Refactoring, Backend

#16572 expand opportunity for OPabs
  compiler/src/dmd/backend/cgelem.d
Labels: Enhancement, auto-merge, Backend

#16575 FIX: Issue 24595 - OpenBSD: Use .init_array/.fini_array
  compiler/src/dmd/backend/elfobj.d
Labels: Enhancement

#16574 Fix bugzilla issue 24566 - condition that starts with runtime value and uses compile time array does not short circuit
  compiler/src/dmd/optimize.d
  compiler/test/compilable/issue24566.d
Labels: auto-merge, Bug Fix

#16576 Fix 24597 -- FreeBSD/OpenBSD: Enable ELF_COMDAT
  compiler/src/dmd/backend/elfobj.d
Labels: Enhancement, auto-merge

#16577 Fix Bugzilla 24598
  compiler/test/compilable/stdcheaders.c
  compiler/test/compilable/test21672.d
  compiler/test/compilable/test22346.c
  compiler/test/fail_compilation/fail17105.d
  compiler/test/fail_compilation/fail18372.d
  compiler/test/fail_compilation/fail6451.d
  compiler/test/fail_compilation/ice20042.d
  compiler/test/fail_compilation/ice20264.d
  compiler/test/fail_compilation/impconv.d
  compiler/test/fail_compilation/vector_types.d
  compiler/test/fail_compilation/xmmslice.d
  compiler/test/runnable/bitfieldsms.c
  compiler/test/runnable/bitfieldsposix32.c
  compiler/test/runnable/bitfieldsposix64.c
  compiler/test/runnable/dbitfieldsms.d
  compiler/test/runnable/dbitfieldsposix32.d
  compiler/test/runnable/dbitfieldsposix64.d
  compiler/test/runnable/dhry.d
  compiler/test/runnable/extra-files/hello-profile-postscript.sh
  compiler/test/runnable/ice21727.d
  compiler/test/runnable/test12.d
  compiler/test/runnable/test17559.d
  compiler/test/runnable/test19086.d
  compiler/test/runnable/test22597.c
  compiler/test/runnable/test23343.c
  compiler/test/runnable/test23889.c
  compiler/test/runnable/test_cdstrpar.d
  compiler/test/runnable/testargtypes.d
  compiler/test/runnable/testthread2.d
  compiler/test/runnable/variadic.d
  compiler/test/runnable/whetstone.d
  compiler/test/runnable_cxx/cpp_abi_tests.d
  compiler/test/runnable_cxx/cppa.d
  compiler/test/tools/d_do_test.d
Labels: Enhancement, auto-merge

#16578 Fix Bugzilla 24590 - Don't run module destructors if druntime failed to initialize
  compiler/test/runnable/extra-files/test24590.d
  compiler/test/runnable/test24590.sh
  druntime/src/rt/dmain2.d
  druntime/src/rt/sections_elf_shared.d
Labels: Enhancement, auto-merge

#16579 Android: Use rt.sections_elf_shared, not rt.sections_android
  druntime/CODEOWNERS
  druntime/mak/DOCS
  druntime/mak/SRCS
  druntime/src/core/sys/posix/dlfcn.d
  druntime/src/rt/sections.d
  druntime/src/rt/sections_android.d
  druntime/src/rt/sections_elf_shared.d
Labels: auto-merge

#15294 Fix Issue 23957 - Casting to derived extern(C++) class is unsafe
  compiler/src/dmd/cppmangle.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/safe.d
  compiler/src/dmd/statement.d
  compiler/test/fail_compilation/cpp_cast.d
Labels: Bug Fix, auto-merge-squash

#16581 localize declarations in cdcond()
  compiler/src/dmd/backend/x86/cgcod.d
  compiler/src/dmd/backend/x86/cod2.d
Labels: Easy Review, Refactoring, Backend

#16558 Fix Bugzilla 24582 - Detect unsafe `cast(bool[])`
  compiler/src/dmd/safe.d
  compiler/test/fail_compilation/bool_cast.d
Labels: Bug Fix

#16582 Add supplemental messages to explain unsafe casts
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/safe.d
  compiler/test/fail_compilation/cast_qual.d
  compiler/test/fail_compilation/cpp_cast.d
  compiler/test/fail_compilation/fail20000.d
  compiler/test/fail_compilation/shared.d
  compiler/test/fail_compilation/test15672.d
  compiler/test/fail_compilation/test15703.d
  compiler/test/fail_compilation/test19646.d
Labels: auto-merge

#16585 refactor FuncParamRegs_alloc()
  compiler/src/dmd/backend/code.d
  compiler/src/dmd/backend/x86/cod1.d
  compiler/src/dmd/glue.d
Labels: Easy Review, Refactoring, Backend

#16588 Fix bugzilla 24579 - stat_t has wrong size for Android armv7a
  druntime/src/core/sys/posix/dirent.d
  druntime/src/core/sys/posix/sys/stat.d
Labels: auto-merge, Bug Fix

#16584 Fix Bugzilla 24603 - Can copy from non-void array into void[] in safe…
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/test15704.d
Labels: Enhancement, auto-merge, Bug Fix

#16589 merge stable
  VERSION
  changelog/dmd.unsafe-boolean-values.dd
  compiler/src/dmd/backend/elfobj.d
  compiler/src/dmd/optimize.d
  compiler/test/compilable/issue24566.d
Labels: Enhancement, Bug Fix, stable -> master

#16586 CI: Add self-compile step to GHA main jobs
  .github/workflows/main.yml
  ci/run.sh
Labels: auto-merge

#16590 Fix bugzilla 24592 - ImportC: Bitfield layout wrong for int64 on 32-b…
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/e2ir.d
  compiler/test/runnable/bitfieldsposix32.c
  compiler/test/runnable/bitfieldsposix64.c
  compiler/test/runnable_cxx/extra-files/testbitfields_cpp.cpp
  compiler/test/runnable_cxx/extra-files/testbitfields_importc.c
  compiler/test/runnable_cxx/testbitfields.d
Labels: auto-merge, Bug Fix

#16583 Fix Bugzilla 17148 - Copying from const(void)[] to void[] breaks immu…
  changelog/dmd.copying-to-void-arrays.dd
  compiler/src/dmd/cli.d
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/previewhelp.d
  compiler/test/fail_compilation/test15660.d
  druntime/src/core/lifetime.d
  druntime/src/core/thread/osthread.d
  druntime/src/core/thread/threadbase.d
  druntime/src/rt/aaA.d
  druntime/src/rt/lifetime.d
Labels: Bug Fix

#16591 [dmd/expressionsem] Refactor copying to void[] errors
  compiler/src/dmd/expressionsem.d
Labels: auto-merge

#16592 Fix Bugzilla 24602 - Internal compiler error: failed to detect static…
  compiler/src/dmd/semantic2.d
  compiler/test/runnable/staticaa.d
Labels: auto-merge, Bug Fix

#16598 update getlvalue() with ref parameter
  compiler/src/dmd/backend/x86/cg87.d
  compiler/src/dmd/backend/x86/cgxmm.d
  compiler/src/dmd/backend/x86/cod1.d
  compiler/src/dmd/backend/x86/cod2.d
  compiler/src/dmd/backend/x86/cod3.d
  compiler/src/dmd/backend/x86/cod4.d
Labels: auto-merge, Easy Review, Refactoring, Backend

#16596 refactor gensaverestore()
  .gitignore
  compiler/src/dmd/backend/code.d
  compiler/src/dmd/backend/x86/cod1.d
Labels: auto-merge, Easy Review, Refactoring, Backend

#16595 Fix bugzilla 24583 - di generator emits return scope and scope return…
  compiler/src/dmd/hdrgen.d
  compiler/test/compilable/extra-files/header1.d
  compiler/test/compilable/extra-files/header1.di
  compiler/test/compilable/extra-files/header1i.di
  compiler/test/fail_compilation/retref2.d
Labels: Bug Fix

#16597 add Elf AArch64 relocation types to melf.d
  compiler/src/dmd/backend/melf.d
Labels: Easy Review, Backend, Aarch64

#16602 move disasm86.d to x86/disasm86.d
  compiler/src/.dscanner.ini
  compiler/src/build.d
  compiler/src/dmd/backend/x86/cgcod.d
  compiler/src/dmd/backend/x86/disasm86.d
Labels: auto-merge, Easy Review, Refactoring, Backend

#16603 modernize parameters to loadea()
  compiler/src/dmd/backend/x86/cg87.d
  compiler/src/dmd/backend/x86/cgxmm.d
  compiler/src/dmd/backend/x86/cod1.d
  compiler/src/dmd/backend/x86/cod2.d
  compiler/src/dmd/backend/x86/cod4.d
Labels: auto-merge, Easy Review, Refactoring, Backend

#16601 [dtemplate.d] use early return
  compiler/src/dmd/dtemplate.d
Labels: Trivial, Easy Review, Refactoring

#16594 Fix Bugzilla 12885 - const union wrongly converts implicitly to mutable
  compiler/src/dmd/mtype.d
  compiler/test/fail_compilation/union_conv.d
Labels: auto-merge, Bug Fix

#16600 add disasmarm.d for AArch64 disassembly
  compiler/src/.dscanner.ini
  compiler/src/build.d
  compiler/src/dmd/README.md
  compiler/src/dmd/backend/arm/disasmarm.d
Labels: Aarch64

#16604 Improve safety of disasmarm.d
  compiler/src/dmd/backend/arm/disasmarm.d
Labels: auto-merge, Refactoring

#16605 Mute noisy warnings when using ImportC with GCC
  druntime/src/importc.h
Labels: auto-merge

#16606 Fix Bugzilla 24622 - Modify const data with void[] concatenation/append
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/void_cat.d
Labels: Bug Fix

#16608 CI: Use macOS-12 instead of macOS-11
  .github/workflows/runnable_cxx.yml
  ci/README.md
Labels: auto-merge

#16607 Upgrade some deprecated GitHub actions
  .github/workflows/pre_commit.yml
  .github/workflows/runnable_cxx.yml
Labels: auto-merge

#16610 Rename CppRuntime_Clang/Gcc to CppRuntime_libcpp/libstdcpp.
  compiler/src/dmd/cond.d
  compiler/src/dmd/dmdparams.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/target.d
  compiler/src/dmd/target.h
  compiler/test/compilable/cppmangle.d
  compiler/test/compilable/cppmangle3.d
  compiler/test/compilable/issue21203.d
  compiler/test/compilable/issue21340.d
  compiler/test/fail_compilation/reserved_version.d
  compiler/test/fail_compilation/reserved_version_switch.d
  compiler/test/runnable_cxx/cpp_stdlib.d
  compiler/test/runnable_cxx/cppa.d
  compiler/test/tools/d_do_test.d
  compiler/test/unit/triple.d
  druntime/src/core/stdcpp/allocator.d
  druntime/src/core/stdcpp/array.d
  druntime/src/core/stdcpp/exception.d
  druntime/src/core/stdcpp/memory.d
  druntime/src/core/stdcpp/string.d
  druntime/src/core/stdcpp/string_view.d
  druntime/src/core/stdcpp/typeinfo.d
  druntime/src/core/stdcpp/xutility.d
Labels: Enhancement, auto-merge

#16611 Fix bugzilla 24594 - ImportC: Packed struct has wrong layout
  compiler/src/dmd/cparse.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/test/compilable/test24594.c
Labels: Bug Fix

#16612 Improve safety of disasarm.d 2
  compiler/src/dmd/backend/arm/disasmarm.d
Labels: auto-merge

#16609 replace WRFL() with el_str()
  compiler/src/dmd/backend/debugprint.d
  compiler/src/dmd/backend/symbol.d
  compiler/src/dmd/backend/x86/cod1.d
  compiler/src/dmd/backend/x86/cod2.d
  compiler/src/dmd/backend/x86/cod3.d
Labels: auto-merge, Easy Review, Refactoring, Backend

#16614 Tweak message for unsafe cast to bool array/pointer
  compiler/src/dmd/safe.d
  compiler/test/fail_compilation/bool_cast.d
Labels: auto-merge

#16615 separate RMload/RMstore into separate argument
  compiler/src/dmd/backend/code.d
  compiler/src/dmd/backend/x86/cgxmm.d
  compiler/src/dmd/backend/x86/cod1.d
  compiler/src/dmd/backend/x86/cod2.d
  compiler/src/dmd/backend/x86/cod3.d
  compiler/src/dmd/backend/x86/cod4.d
  compiler/src/dmd/backend/x86/code_x86.d
Labels: auto-merge, Easy Review, Refactoring, Backend

#16616 move PSW out of register set
  compiler/src/dmd/backend/x86/cgcod.d
  compiler/src/dmd/backend/x86/code_x86.d
Labels: Easy Review, Refactoring, Backend

#16617 fix hasUDA template to handle multiple UDAs
  druntime/src/core/internal/traits.d
Labels: auto-merge, Bug Fix

#16619 enlarge register mask to 64 bits
  compiler/src/dmd/backend/cdef.d
  compiler/src/dmd/backend/code.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/x86/cgcod.d
  compiler/src/dmd/backend/x86/cod1.d
  compiler/src/dmd/backend/x86/cod2.d
  compiler/src/dmd/backend/x86/cod4.d
Labels: auto-merge, Easy Review, Refactoring, Backend, Aarch64

#16622 Fix Bugzilla 24630 - Casting a bool pointer to a mutable pointer type…
  compiler/src/dmd/safe.d
  compiler/test/fail_compilation/bool_cast.d
Labels: auto-merge, Bug Fix

#16623 refactor Import.overloadInsert
  compiler/src/dmd/dimport.d
Labels: auto-merge

#16625 Fix Bugzilla 24631 - Pointer cast allows changing @system field in @s…
  compiler/src/dmd/safe.d
  compiler/test/fail_compilation/system_ptr_cast.d
Labels: auto-merge, Bug Fix

#16627 Add correct statvfs_t for Musl.
  druntime/src/core/sys/posix/sys/statvfs.d
Labels: auto-merge

#16626 increase REGMAX to account for AArch64 registers (#16620)
  compiler/src/dmd/backend/cdef.d
  compiler/src/dmd/backend/gsroa.d
Labels: auto-merge, Easy Review, Refactoring, Backend, Aarch64

#16629 use genpush() more aggressively
  compiler/src/dmd/backend/code.d
  compiler/src/dmd/backend/x86/cod1.d
  compiler/src/dmd/backend/x86/cod2.d
  compiler/src/dmd/backend/x86/cod3.d
Labels: auto-merge, Easy Review, Refactoring, Backend

#16628 remove redundant `static` of enum
  druntime/src/core/internal/traits.d
  druntime/src/core/runtime.d
  druntime/src/core/sys/windows/stacktrace.d
  druntime/src/rt/tracegc.d
Labels: auto-merge

#16631 [trivial] Fix foreach range tuple element error message
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/fail13577.d
Labels: Trivial, auto-merge

#16634 add LDR decoding
  compiler/src/dmd/backend/arm/disasmarm.d
Labels: auto-merge, Easy Review, Aarch64

#16633 add CGstate to prolog functions
  compiler/src/dmd/backend/x86/cgcod.d
  compiler/src/dmd/backend/x86/cod3.d
Labels: auto-merge, Easy Review, Refactoring, Backend

#16632 refactor variable declarations to use `auto`
  compiler/src/dmd/clone.d
  compiler/src/dmd/dstruct.d
  compiler/src/dmd/errors.d
  compiler/src/dmd/funcsem.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/objc.d
  compiler/src/dmd/optimize.d
  compiler/src/dmd/safe.d
  compiler/src/dmd/semantic2.d
Labels: Refactoring

#16636 add sections to disasmarm.d
  compiler/src/dmd/backend/arm/disasmarm.d
Labels: auto-merge, Easy Review, Aarch64

#16637 add disasm support for stp/ldp
  compiler/src/dmd/backend/arm/disasmarm.d
Labels: auto-merge, Easy Review, Aarch64

#16613 Fix bugzilla issue 24623 followup.
  compiler/src/dmd/cond.d
  compiler/src/dmd/dmdparams.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/target.d
  compiler/src/dmd/target.h
  compiler/test/compilable/cppmangle.d
  compiler/test/compilable/cppmangle3.d
  compiler/test/compilable/issue21203.d
  compiler/test/compilable/issue21340.d
  compiler/test/fail_compilation/reserved_version.d
  compiler/test/fail_compilation/reserved_version_switch.d
  compiler/test/runnable_cxx/cpp_stdlib.d
  compiler/test/runnable_cxx/cppa.d
  compiler/test/tools/d_do_test.d
  compiler/test/unit/triple.d
  druntime/src/core/stdcpp/allocator.d
  druntime/src/core/stdcpp/array.d
  druntime/src/core/stdcpp/exception.d
  druntime/src/core/stdcpp/memory.d
  druntime/src/core/stdcpp/string.d
  druntime/src/core/stdcpp/string_view.d
  druntime/src/core/stdcpp/typeinfo.d
  druntime/src/core/stdcpp/xutility.d
Labels: Enhancement, auto-merge

#16639 Remove never used functions from unwind.d
  druntime/src/core/internal/backtrace/unwind.d
Labels: auto-merge

#16638 Treat `import("file")` as hex string
  changelog/dmd.import-exp-hexstring.dd
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/import_exp.d
  compiler/test/compilable/test16088.d
  compiler/test/compilable/test21227.d
Labels: Enhancement, auto-merge
