Repository dlang/dmd, pull requests merged in 2024-02, with the labels that each got.

#16122 Remove some errStatus parameters from Demangle
  druntime/src/core/demangle.d
Labels: Refactoring

#16132 core.demangle: refactor errMsg assignment to a function
  druntime/src/core/demangle.d
Labels: Refactoring

#16124 mv functionResolve() to templatesem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/func.d
  compiler/src/dmd/opover.d
  compiler/src/dmd/templatesem.d
Labels: Easy Review, Refactoring

#16131 Fix Issue 24365 - ICE when printing showCtfeContext error
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/test24365.d
Labels: Bug Fix

#16123 Fix sliceCmpStringWithArray for StringExp with size 8
  compiler/src/dmd/constfold.d
  compiler/test/runnable/literal.d
Labels: Bug Fix

#16126 fix bugzilla Issue 24315 - dmd/cpreprocess.d:87: warning: use of tmpn…
  compiler/src/dmd/link.d
Labels: Bug Fix, WIP

#16134 merge stable
  VERSION
  changelog/dmd.assert-string.dd
  changelog/dmd.makefiles.dd
  changelog/dmd.pragma.dd
  changelog/dmd.standalone-attribute.dd
  changelog/dmd.template-_d_newarratmT.dd
  changelog/druntime.coreatomic.dd
  changelog/druntime.makefiles.dd
  changelog/druntime.stdatomic.dd
  compiler/src/dmd/dsymbolsem.d
  compiler/test/fail_compilation/test24365.d
Labels: Bug Fix

#16127 mv findVtblIndex() and overrideInterface() to funcsem.d
  compiler/src/dmd/cppmanglewin.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/funcsem.d
Labels: Easy Review, Refactoring

#16137 test: Reorganize the unicode tests so those with BOMs are identifiable by name
  compiler/test/compilable/ddoc4162.d
  compiler/test/compilable/ddoc5446.d
  compiler/test/compilable/ddoc7795.d
  compiler/test/compilable/ddoc_bom_UTF8.d
  compiler/test/compilable/extra-files/ddoc_bom_UTF8.html
  compiler/test/fail_compilation/gag4269a.d
  compiler/test/fail_compilation/gag4269b.d
  compiler/test/fail_compilation/gag4269c.d
  compiler/test/fail_compilation/gag4269d.d
  compiler/test/fail_compilation/gag4269e.d
  compiler/test/fail_compilation/gag4269f.d
  compiler/test/fail_compilation/gag4269g.d
  compiler/test/fail_compilation/ice10599.d
  compiler/test/runnable/bom_UTF16.d
  compiler/test/runnable/bom_UTF16BE.d
  compiler/test/runnable/bom_UTF32.d
  compiler/test/runnable/bom_UTF8.d
Labels: Trivial, auto-merge, Testing Infrastructure

#16138 [REG master] Explicitly instantiate StringValue!Type in dmd.mtype
  compiler/src/dmd/mtype.d
Labels: Regression, GDC, Blocking Other Work, auto-merge

#16139 refactor out ISXREF
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/toir.d
Labels: Easy Review, Refactoring

#16142 Update constraints of GNU atomicExchange to match DigitalMars
  druntime/src/core/internal/atomic.d
Labels: GDC, Blocking Other Work, auto-merge, Easy Review

#16146 Fix issue 24309 - Memory allocation failed on Azure pipeline
  druntime/src/core/internal/gc/impl/conservative/gc.d
Labels: auto-merge, Bug Fix

#16149 dmd.cppmanglewin: Move checkImmutableShared below the private: line
  compiler/src/dmd/cppmanglewin.d
Labels: auto-merge, Easy Review, Refactoring

#16150 Add hexstring field to ASTBase.StringExp
  compiler/src/dmd/astbase.d
Labels: auto-merge

#16151 Update ASTBase.stcToBuffer to match declaration in ASTCodegen
  compiler/src/dmd/astbase.d
Labels: auto-merge

#16152 Fix constructor signature for ASTBase.Parameter to match that of ASTC…
  compiler/src/dmd/astbase.d
Labels: auto-merge

#16156 dmd: Remove extern(C++) from global functions that don't need it
  compiler/src/dmd/astenums.d
  compiler/src/dmd/dcast.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dsymbol.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/errors.h
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/libelf.d
  compiler/src/dmd/libmach.d
  compiler/src/dmd/libmscoff.d
  compiler/src/dmd/libomf.d
  compiler/src/dmd/mtype.h
  compiler/src/dmd/toctype.d
  compiler/src/dmd/todt.d
  compiler/src/dmd/typesem.d
Labels: auto-merge, Easy Review, Refactoring, extern (C/C++)

#16160 Fix IsAtomicLockFree for PPC targets
  druntime/src/core/internal/atomic.d
Labels: Regression, GDC, auto-merge, Easy Review

#16162 functionParameters() - fix some turgid comparisons
  compiler/src/dmd/expressionsem.d
Labels: Easy Review, Refactoring

#16164 Fix Bugzilla Issue 24370 - static array values in static AA initialis…
  compiler/src/dmd/semantic2.d
  compiler/test/runnable/staticaa.d
Labels: auto-merge, Bug Fix

#16165 straighten out needsDtor
  compiler/src/dmd/expressionsem.d
Labels: auto-merge, Easy Review, Refactoring

#16051 fix Bugzilla Issue 3543 - [tdpl] ternary operator can't find common type for c…
  compiler/src/dmd/dcast.d
  compiler/test/compilable/commontype.d
  compiler/test/compilable/test3543.d
Labels: Enhancement, auto-merge, Ready To Merge

#16163 background work for caller does destruction
  compiler/src/dmd/clone.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/target.d
Labels: Refactoring

#16037 druntime: Prepare `test/shared` for Windows support
  druntime/Makefile
  druntime/test/common.mak
  druntime/test/shared/Makefile
  druntime/test/shared/src/dynamiccast.d
  druntime/test/shared/src/finalize.d
  druntime/test/shared/src/host.c
  druntime/test/shared/src/lib.d
  druntime/test/shared/src/libloaddep.d
  druntime/test/shared/src/linkDR.c
  druntime/test/shared/src/link_loaddep.d
  druntime/test/shared/src/load.d
  druntime/test/shared/src/loadDR.c
  druntime/test/shared/src/load_13414.d
  druntime/test/shared/src/load_linkdep.d
  druntime/test/shared/src/load_loaddep.d
  druntime/test/shared/src/utils.di
  druntime/test/shared/src/utils.h
Labels: auto-merge

#16136 test: Add UNICODE_NAMES directive to files with utf-8 symbols
  compiler/test/README.md
  compiler/test/runnable/mangle.d
  compiler/test/runnable/testmodule.d
  compiler/test/runnable/ufcs.d
Labels: GDC, Testing Infrastructure

#16135 Extract mtype.Type.addMod and move it to typesem
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/astbase.d
  compiler/src/dmd/astcodegen.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/mtype.h
  compiler/src/dmd/parse.d
  compiler/src/dmd/typesem.d
Labels: auto-merge

#16168 Extract mtype.Type.equivalent and move it to dmd.typesem
  compiler/src/dmd/constfold.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/mtype.h
  compiler/src/dmd/typesem.d
Labels: auto-merge

#16144 Adds "Unsupported platform" static asserts
  druntime/src/core/thread/osthread.d
  druntime/src/core/time.d
Labels: auto-merge

#16170 Run backend inliner on pragma(inline) functions
  compiler/src/dmd/backend/dout.d
Labels: auto-merge, Easy Review, Backend

#16171 Always run backend inliner when -inline seen on command-line
  compiler/src/dmd/dmsc.d
  compiler/test/compilable/interpret3.d
  compiler/test/runnable/link15021.d
  compiler/test/runnable_cxx/test7925.d
Labels: Easy Review, Backend

#16159 dmd: Move default field initializers to runtime
  compiler/src/dmd/dmdparams.d
  compiler/src/dmd/frontend.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/main.d
  compiler/src/dmd/target.d
  compiler/test/unit/deinitialization.d
Labels: Blocking Other Work, auto-merge, Easy Review, Refactoring

#16182 Remove dmd.iasm from the gluelayer module
  compiler/src/build.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/gluelayer.d
  compiler/src/dmd/iasm.d
  compiler/src/dmd/statementsem.d
  dub.sdl
Labels: GDC, Easy Review, Refactoring

#16180 Fix Bugzilla 24387 - Base class construction ignores private
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/imports/issue21685.d
  compiler/test/fail_compilation/issue21685_main.d
Labels: Bug Fix

#16183 Move handleTagSymbols and handleSymbolRedeclarations to dmd.importc
  compiler/src/dmd/dscope.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/importc.d
Labels: Easy Review, Refactoring, ImportC

#16172 Fix Bugzilla 24383 - Index assignment expression in __traits(compiles…
  compiler/src/dmd/parse.d
  compiler/test/compilable/traits.d
Labels: Bug Fix

#16179 refactor inliner()
  compiler/src/dmd/backend/inliner.d
Labels: Refactoring

#16155 dmd: Move all public C++ functions into a dmd namespace
  compiler/src/build.d
  compiler/src/dmd/aggregate.h
  compiler/src/dmd/argtypes.h
  compiler/src/dmd/argtypes_aarch64.d
  compiler/src/dmd/argtypes_sysv_x64.d
  compiler/src/dmd/argtypes_x86.d
  compiler/src/dmd/cppmangle.d
  compiler/src/dmd/cppmanglewin.d
  compiler/src/dmd/cxxfrontend.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/dmangle.d
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dmsc.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/doc.h
  compiler/src/dmd/dstruct.d
  compiler/src/dmd/dsymbol.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/dtoh.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/funcsem.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/hdrgen.h
  compiler/src/dmd/iasm.d
  compiler/src/dmd/iasmgcc.d
  compiler/src/dmd/init.h
  compiler/src/dmd/initsem.d
  compiler/src/dmd/json.d
  compiler/src/dmd/json.h
  compiler/src/dmd/mangle.h
  compiler/src/dmd/module.h
  compiler/src/dmd/mtype.d
  compiler/src/dmd/mtype.h
  compiler/src/dmd/optimize.d
  compiler/src/dmd/semantic2.d
  compiler/src/dmd/semantic3.d
  compiler/src/dmd/statement.h
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/template.h
  compiler/src/dmd/templateparamsem.d
  compiler/src/dmd/typesem.d
  compiler/src/dmd/typinf.d
  compiler/src/dmd/typinf.h
  compiler/src/tests/cxxfrontend.cc
Labels: GDC, LDC, auto-merge, Refactoring, extern (C/C++)

#16181 fix Issue 24390 - AssertError@src/dmd/backend/cgxmm.d(1476): Assertion failure
  compiler/src/dmd/backend/inliner.d
  compiler/test/compilable/imports/test24390a.d
  compiler/test/compilable/imports/test24390b.d
  compiler/test/compilable/test24390.d
Labels: Blocking Other Work

#16186 Fix Bugzilla 23786 - __traits(parent, {}) in overloaded function prod…
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/test23786.d
Labels: auto-merge, Bug Fix

#16184 partial bugzilla 24389 - importC: Parser support for top-level asm definitions
  compiler/src/dmd/astbase.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/cxxfrontend.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dsymbol.h
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/iasm.d
  compiler/src/dmd/iasmgcc.d
  compiler/src/dmd/parsetimevisitor.d
  compiler/src/dmd/visitor.h
  compiler/src/tests/cxxfrontend.cc
  compiler/test/fail_compilation/fail24389.c
Labels: GDC, ImportC

#16192 test continue inside do-while
  compiler/test/runnable/mars1.d
Labels: Easy Review

#16189 gha: Ignore macOS 13 if linker is broken on the runner
  .github/workflows/main.yml
Labels: auto-merge, Continuous Integration

#16195 merge stable
  .github/workflows/main.yml
  VERSION
  compiler/src/dmd/semantic2.d
  compiler/test/runnable/staticaa.d
Labels: Bug Fix

#16198 Turn -preview=dip1000 warning into a deprecation
  compiler/src/dmd/func.d
Labels: Diagnostic Messages

#16197 Turn foreach_reverse(AA) into an error
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/warn13679.d
Labels: Diagnostic Messages

#16196 refactor runProgram()
  compiler/src/dmd/link.d
  compiler/src/dmd/main.d
Labels: Easy Review, Refactoring

#16200 Fix Bugzilla 20802 - Link failure with writefln
  compiler/test/runnable/extra-files/link20802a.d
  compiler/test/runnable/extra-files/link20802b.d
  compiler/test/runnable/link20802.sh
  druntime/src/core/exception.d
Labels: Bug Fix

#16201 gha: Update cross-platform-actions to v0.23.0
  .github/workflows/main.yml
Labels: Easy Review, Continuous Integration

#16199 fix bugzilla Issue 24397 ImportC: support function-like macros
  compiler/src/dmd/cparse.d
  compiler/src/dmd/link.d
  compiler/src/dmd/toir.d
  compiler/test/compilable/imports/defines.c
  compiler/test/compilable/testdefines.d
Labels: Enhancement, Atila Neves, ImportC

#16206 lib*.d: use proper OS versioning
  compiler/src/dmd/libelf.d
  compiler/src/dmd/libmach.d
  compiler/src/dmd/libmscoff.d
Labels: auto-merge, Easy Review, Refactoring

#16205 runPreprocessor - eliminate dependence on a couple globals
  compiler/src/dmd/cpreprocess.d
  compiler/src/dmd/link.d
  compiler/src/dmd/main.d
Labels: Easy Review, Refactoring

#16209 link.d: move Posix/Windows declarations into unified single blocks
  compiler/src/dmd/link.d
Labels: Easy Review, Refactoring

#16211 dinifile.d: untangle version blocks
  compiler/src/dmd/dinifile.d
Labels: Easy Review, Refactoring

#16212 machobj: Remove enum constants duplicated in dmd.backend.mach
  compiler/src/dmd/backend/machobj.d
Labels: Easy Review, Refactoring

#16194 [stable] GHA: Switch to old Xcode as workaround for macOS-13 jobs
  .github/workflows/main.yml
Labels: auto-merge, Continuous Integration

#16210 console.d: clearly deliniate Posix/Windows code
  compiler/src/dmd/console.d
Labels: Easy Review, Refactoring

#16214 GHA: Set N parallelism dynamically
  .github/workflows/main.yml
  .github/workflows/runnable_cxx.yml
Labels: auto-merge

#16213 machobj: Remove code disabled by static if(0)
  compiler/src/dmd/backend/machobj.d
Labels: Refactoring

#16203 build.d: Remove synchronized file access on OSX
  compiler/src/build.d
Labels: Easy Review, Build System

#16216 cgobj.d: improve Posix/Windows logic
  compiler/src/dmd/backend/cgobj.d
Labels: auto-merge, Easy Review, Refactoring

#16217 dout.d: remove Windows version
  compiler/src/dmd/backend/dout.d
Labels: auto-merge, Easy Review, Refactoring

#16218 dwarfdbginf.d: improve Posix/Windows logic
  compiler/src/dmd/backend/dwarfdbginf.d
Labels: auto-merge, Easy Review, Refactoring

#16219 Fix Bugzilla 24402 - OSX: Linker warning: pointer not aligned at __OBJC_PROTOCOL_$_Foo
  compiler/src/dmd/objc_glue.d
Labels: auto-merge, Bug Fix, Easy Review, Backend

#16221 Fix Bugzilla 24137 - Link failure on macOS with symbol count from symbol table and dynamic symbol table differ
  compiler/src/dmd/backend/machobj.d
Labels: auto-merge, Bug Fix, Easy Review, Backend

#16223 Fix Bugzilla 20297 - Link warning: no platform load command found in object.o, assuming: macOS
  compiler/src/dmd/backend/mach.d
  compiler/src/dmd/backend/machobj.d
Labels: auto-merge, Bug Fix, Backend

#16224 Fix Bugzilla 23517 - dmd with -g flag fails to link on macOS with unaligned pointer
  compiler/src/dmd/backend/dwarfdbginf.d
  compiler/test/runnable/debug_info.d
  druntime/test/exceptions/Makefile
Labels: auto-merge, Bug Fix, Backend

#16229 toWStrings(): fix unnecessarily complex loop
  compiler/src/dmd/common/smallbuffer.d
Labels: auto-merge, Easy Review, Refactoring

#16232 remove obsolete code from inliner
  compiler/src/dmd/backend/inliner.d
Labels: Easy Review, Refactoring, Backend

#16226 Move dmd/root/object.h to dmd/rootobject.h
  compiler/src/build.d
  compiler/src/dmd/ast_node.h
  compiler/src/dmd/identifier.h
  compiler/src/dmd/root/array.h
  compiler/src/dmd/root/bitarray.h
  compiler/src/dmd/rootobject.h
  compiler/src/dmd/template.h
  compiler/src/tests/cxxfrontend.cc
Labels: GDC, LDC, C++ Port, Refactoring

#16230 file.d: move Posix/Windows to the top
  compiler/src/dmd/common/file.d
Labels: Easy Review, Refactoring

#16234 Fix Bugzilla issue 24405 - FreeBSD's ifaddrs missing the ifa_broadaddr field.
  druntime/src/core/sys/freebsd/ifaddrs.d
Labels: Bug Fix

#16235 Remove unused imports.
  compiler/src/dmd/dimport.d
Labels: auto-merge

#16236 Remove unused imports.
  compiler/src/dmd/staticcond.d
Labels: auto-merge

#16238 make sure hello world in C works
  compiler/test/runnable/helloc.c
Labels: Easy Review, ImportC

#16222 Fix Bugzilla 24399 - Link failure on MacOS with address=0x0 points to section(2) with no content
  compiler/src/dmd/todt.d
  compiler/test/compilable/issue24399.d
Labels: auto-merge, Bug Fix, Backend

#16241 Fix bugzilla issue 24408 - Remove duplicate AF_INET6 declaration.
  druntime/src/core/sys/linux/sys/socket.d
Labels: Bug Fix

#16240 [stable] GHA: Bump Xcode version to 15.1 for macOS-13 jobs
  .github/workflows/main.yml
Labels: Bug Fix, Easy Review, Continuous Integration

#16233 Fix Bugzilla issue 24404 - ifaddrs union fields incorrectly name on Linux.
  druntime/src/core/sys/linux/ifaddrs.d
Labels: Bug Fix

#16246 Fix Bugzilla 24409 - DMD crash for CTFE in stompOverlappedFields
  compiler/src/dmd/dinterpret.d
  compiler/test/compilable/issue24409.d
Labels: Bug Fix

#16261 Fix bugzilla issue 24417: fds_bits named incorrectly on FreeBSD
  druntime/src/core/sys/posix/sys/select.d
Labels: auto-merge, Bug Fix

#16264 Fix Bugzilla 24422 - ImportC: ICE: Segfault in cparseFunctionDefinition
  compiler/src/dmd/cparse.d
  compiler/test/fail_compilation/fail24422.c
Labels: Bug Fix

#16266 reduce dependency of glue code on globals
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/s2ir.d
  compiler/src/dmd/toir.d
Labels: Easy Review, Refactoring
