Repository dlang/dmd, pull requests merged in 2025-08, with the labels that each got.

#21639 druntime, musl: Remove unused __USE_FILE_OFFSET64 bindings
  druntime/src/core/sys/posix/dirent.d
  druntime/src/core/sys/posix/dlfcn.d
  druntime/src/core/sys/posix/stdio.d
  druntime/src/core/sys/posix/stdlib.d
  druntime/src/core/sys/posix/sys/mman.d
  druntime/src/core/sys/posix/sys/statvfs.d
Labels: Merge:auto-merge, Druntime

#21631 fix #21630: `enum` and `alias` ignored on runtime foreach loop variables
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/statementsem.d
  compiler/test/fail_compilation/issue21630.d
Labels: Merge:auto-merge, Diagnostic Messages

#21652 account for OPstrpar with zero size
  compiler/src/dmd/backend/arm/cod1.d
Labels: Compiler:Backend, Arch:Aarch64

#21653 fix github Issue 18247 Bitfield with 64 bits always zero
  compiler/src/dmd/backend/cgelem.d
  compiler/test/runnable/bit.d
Labels: Severity:Bug Fix, Compiler:Backend, Feature: bitfields

#21661 fix #21660 - Error overlapping initialization for D bit-fields
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/fail21660.d
  compiler/test/runnable/test21660.d
Labels: Severity:Bug Fix

#21666 fix #18101 wrong code generated for bitfield assignment to ?:
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/biterrors5.d
Labels: Review:Blocking Other Work, Feature: bitfields

#21669 rename bit-field to bitfield in comments and strings
  compiler/src/dmd/clone.d
  compiler/src/dmd/declaration.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/target.d
  compiler/test/fail_compilation/biterrors.d
  compiler/test/fail_compilation/biterrors2.d
  compiler/test/fail_compilation/biterrors3.d
  compiler/test/fail_compilation/biterrors4.d
  compiler/test/fail_compilation/biterrors5.d
  compiler/test/fail_compilation/bitfields2.c
  compiler/test/fail_compilation/fail22749.d
  compiler/test/fail_compilation/failcstuff2.c
  compiler/test/fail_compilation/failcstuff5.c
Labels: Severity:trivial

#21671 Fix null deference in code in `test/unit/frontend.d`
  compiler/test/unit/frontend.d
Labels: Review:Trivial

#21678 importC: Reject conditional expressions as lvalues
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/lvalue1.c
Labels: Feature:ImportC

#21676 Increase timeouts for FreeBSD on GHA
  .github/workflows/main.yml
Labels: Infrastructure:Continuous Integration

#21572 Packagise the glue layer into`glue/`
  compiler/src/build.d
  compiler/src/dmd/README.md
  compiler/src/dmd/glue/e2ir.d
  compiler/src/dmd/glue/objc.d
  compiler/src/dmd/glue/package.d
  compiler/src/dmd/glue/s2ir.d
  compiler/src/dmd/glue/tocsym.d
  compiler/src/dmd/glue/toctype.d
  compiler/src/dmd/glue/tocvdebug.d
  compiler/src/dmd/glue/todt.d
  compiler/src/dmd/glue/toir.d
  compiler/src/dmd/glue/toobj.d
  compiler/src/dmd/gluelayer.d
  compiler/src/dmd/main.d
  compiler/src/dmd/objc.d
  dub.sdl
Labels: Severity:Refactoring

#21677 use default args instead of multiple functions
  compiler/src/dmd/expressionsem.d
Labels: Severity:Refactoring

#21687 dmd.dmodule: Remove unused Module.find function
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/module.h
Labels: Merge:auto-merge, Severity:Refactoring, Compiler:C++ Interface

#21686 dmd.file_manager: Lower priority of imports found on local path
  compiler/src/dmd/file_manager.d
  compiler/test/compilable/imports/imp23548.d
  compiler/test/compilable/test23548.d
Labels: Feature:ImportC

#21685 fix #20114 AA in operator does not work with static if
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/frontend.h
  compiler/test/compilable/interpret4.d
Labels: Merge:auto-merge

#21694 fix 21693 - __rvalue ignored with component expressions
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/fail21693.d
Labels: Bug Fix

#21696 fix #20365 - Bitfield address escapes through ref
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/importc.d
  compiler/src/dmd/semantic3.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/typesem.d
  compiler/test/compilable/test20365.d
  compiler/test/fail_compilation/biterrors4.d
  compiler/test/fail_compilation/biterrors5.d
  compiler/test/fail_compilation/fail20365.d
  compiler/test/fail_compilation/fail22749.d
  compiler/test/fail_compilation/failcstuff2.c
  compiler/test/fail_compilation/failcstuff5.c
Labels: Bug Fix, Feature: bitfields

#21698 fix some misc test suite null pointer usage
  compiler/test/compilable/b1215.d
  compiler/test/compilable/test14838.d
  compiler/test/compilable/test20100.d
  compiler/test/runnable/test42.d
Labels: Review:Trivial

#21689 add test for #17487 Associative arrays do not correctly handle keys with copy constructors
  compiler/test/runnable/test17487.d
Labels: Merge:auto-merge

#21709 gha: Add latest releases to bootstrap workflow
  .github/workflows/bootstrap.yml
Labels: Review:Easy Review, Infrastructure:Continuous Integration

#21713 [dmodule.d] remove unused semantic import
  compiler/src/dmd/dmodule.d
Labels: Review:Trivial

#21692 Fix #20184 - ImportC recognizes .i and .c files, but not .h files
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/file_manager.d
  compiler/src/dmd/globals.d
  compiler/src/dmd/mars.d
  compiler/test/compilable/imports/h20184.h
  compiler/test/compilable/test20184.d
Labels: Feature:ImportC

#21716 improve error message for bad size/type
  compiler/src/dmd/iasm/dmdx86.d
  compiler/test/fail_compilation/iasm1.d
Labels: Merge:auto-merge, Diagnostic Messages

#21719 importC: Fix grammar for constant expressions
  compiler/src/dmd/cparse.d
Labels: Feature:ImportC

#21729 ImportC: Use the location of the declarator ident for dsymbols
  compiler/src/dmd/astcodegen.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/frontend.h
  compiler/test/compilable/jsonc.i
  compiler/test/fail_compilation/malformed_cmain.c
  compiler/test/fail_compilation/test22344.c
  compiler/test/fail_compilation/testnothrow.c
Labels: Merge:auto-merge, Feature:ImportC

#21743 lexer: Remove dead UCN branch
  compiler/src/dmd/lexer.d
Labels: Merge:auto-merge, Severity:Refactoring, Feature:ImportC

#21739 parser: Promote dangling else warning to error
  changelog/dmd.dangling-else.dd
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/fail4375a.d
  compiler/test/fail_compilation/fail4375b.d
  compiler/test/fail_compilation/fail4375c.d
  compiler/test/fail_compilation/fail4375d.d
  compiler/test/fail_compilation/fail4375e.d
  compiler/test/fail_compilation/fail4375f.d
  compiler/test/fail_compilation/fail4375g.d
  compiler/test/fail_compilation/fail4375h.d
  compiler/test/fail_compilation/fail4375i.d
  compiler/test/fail_compilation/fail4375j.d
  compiler/test/fail_compilation/fail4375k.d
  compiler/test/fail_compilation/fail4375l.d
  compiler/test/fail_compilation/fail4375m.d
  compiler/test/fail_compilation/fail4375o.d
  compiler/test/fail_compilation/fail4375p.d
  compiler/test/fail_compilation/fail4375q.d
  compiler/test/fail_compilation/fail4375r.d
  compiler/test/fail_compilation/fail4375s.d
  compiler/test/fail_compilation/fail4375t.d
  compiler/test/fail_compilation/fail4375u.d
  compiler/test/fail_compilation/fail4375v.d
  compiler/test/fail_compilation/fail4375w.d
  compiler/test/fail_compilation/fail4375x.d
  compiler/test/fail_compilation/fail4375y.d
  compiler/test/runnable/integrate.d
  compiler/test/unit/parser/diagnostic_reporter.d
Labels: Merge:auto-merge, Severity:Deprecation -> Error

#21754 errors: Give better names to the main diagnostic entrypoints
  compiler/src/dmd/errors.d
Labels: Compiler:GDC, Diagnostic Messages, Severity:Refactoring

#21752 inline: Send all diagnostics through errorSink
  compiler/src/dmd/inline.d
  compiler/src/dmd/main.d
Labels: Merge:auto-merge, Diagnostic Messages, Severity:Refactoring

#21764 Move `MATCHpair` to `templatesem.d`
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/templatesem.d
Labels: Review:Trivial

#21766 fix #17462 object.require modifies AA before populating value
  druntime/src/core/internal/newaa.d
  druntime/src/object.d
  druntime/test/aa/src/test_aa.d
Labels: Druntime:AA

#21778 replace vestigial use of static with private, and move to end
  compiler/src/dmd/glue/e2ir.d
Labels: Review:Easy Review, Severity:Refactoring

#21777 globals: Rename gaggedWarnings to gaggedDeprecations
  compiler/src/dmd/errors.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.d
  compiler/src/dmd/globals.h
  compiler/src/dmd/typesem.d
Labels: Merge:auto-merge, Diagnostic Messages

#21784 [dmodule.d] remove unused import
  compiler/src/dmd/dmodule.d
Labels: Review:Trivial

#21786 [dsymbolsem.d] reduce indentation in `oneMembers`
  compiler/src/dmd/dsymbolsem.d
Labels: Review:Trivial

#21787 [dsymbolsem.d] simplify logic for `isAliasSeq`
  compiler/src/dmd/dsymbolsem.d
Labels: Review:Trivial

#21741 druntime-test: Detect musl more robustly
  druntime/Makefile
  druntime/test/common.mak
  druntime/test/exceptions/Makefile
  druntime/test/importc_compare/Makefile
Labels: Merge:auto-merge-squash
