Repository dlang/dmd, pull requests merged in 2025-01, with the labels that each got.

#20638 Prevent `core.internal.traits.AliasSeq` from bleeding through `core.time`
  druntime/src/core/time.d
Labels: Merge:auto-merge, Druntime

#20637 Print match level for ambiguous overloads
  compiler/src/dmd/funcsem.d
  compiler/test/fail_compilation/bug19569.d
  compiler/test/fail_compilation/diag11769.d
  compiler/test/fail_compilation/fail14554.d
  compiler/test/fail_compilation/fail16600.d
  compiler/test/fail_compilation/fail19729.d
  compiler/test/fail_compilation/fail22157.d
  compiler/test/fail_compilation/fail23626b.d
  compiler/test/fail_compilation/fail8313.d
  compiler/test/fail_compilation/fail8373.d
  compiler/test/fail_compilation/fail_scope.d
  compiler/test/fail_compilation/named_arguments_overload.d
  compiler/test/fail_compilation/pull12941.d
  compiler/test/fail_compilation/test18385b.d
  compiler/test/fail_compilation/testInference.d
  compiler/test/fail_compilation/testOpApply.d
Labels: Merge:auto-merge, Diagnostic Messages

#20642 Use Scope instead of dmd.globals for checking preview switch state
  compiler/src/dmd/declaration.h
  compiler/src/dmd/dscope.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/nogc.d
  compiler/src/dmd/safe.d
  compiler/src/dmd/scope.h
  compiler/src/dmd/semantic3.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/templatesem.d
  compiler/src/dmd/typesem.d
Labels: Merge:auto-merge, Severity:Refactoring

#20647 [parse.d] fix documentation for `parseAssignCondition`
  compiler/src/dmd/parse.d
Labels: Review:Trivial, Review:Easy Review, Severity:documentation

#20646 replace `prm` with `param` in `statement.d`
  compiler/src/dmd/astbase.d
  compiler/src/dmd/cond.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/inline.d
  compiler/src/dmd/inlinecost.d
  compiler/src/dmd/statement.d
  compiler/src/dmd/statement.h
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/visitor/transitive.d
Labels: Review:Trivial, Review:Easy Review, Severity:Refactoring

#20648 Fix invalid "Source: " links in druntime module ddocs
  druntime/src/__importc_builtins.di
  druntime/src/core/internal/backtrace/dwarf.d
  druntime/src/core/internal/backtrace/elf.d
  druntime/src/core/internal/backtrace/macho.d
  druntime/src/core/internal/elf/io.d
  druntime/src/core/internal/postblit.d
  druntime/src/core/internal/string.d
  druntime/src/core/sys/darwin/mach/stab.d
  druntime/src/core/sys/posix/stdc/time.d
  druntime/src/core/sys/windows/dbghelp.d
  druntime/src/core/sys/windows/stdc/time.d
  druntime/src/core/thread/threadbase.d
  druntime/src/core/thread/threadgroup.d
  druntime/src/core/thread/types.d
  druntime/src/etc/linux/memoryerror.d
  druntime/src/rt/sections_elf_shared.d
Labels: Merge:auto-merge, Severity:documentation

#20652 Implement AUTO_UPDATE for multiple TEST_OUTPUT blocks
  compiler/test/tools/d_do_test.d
Labels: Merge:auto-merge, Infrastructure:Testing Infrastructure

#20651 Make DT a D enum
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/dout.d
  compiler/src/dmd/backend/dt.d
Labels: Severity:Refactoring, Compiler:Backend

#20632 Use selective imports when importing platform-specific modules (core.sys)
  druntime/src/core/internal/atomic.d
  druntime/src/core/internal/backtrace/elf.d
  druntime/src/core/internal/backtrace/handler.d
  druntime/src/core/internal/backtrace/macho.d
  druntime/src/core/internal/elf/dl.d
  druntime/src/core/internal/elf/io.d
  druntime/src/core/internal/execinfo.d
  druntime/src/core/internal/gc/impl/conservative/gc.d
  druntime/src/core/internal/gc/os.d
  druntime/src/core/runtime.d
  druntime/src/core/sync/condition.d
  druntime/src/core/sync/config.d
  druntime/src/core/sync/event.d
  druntime/src/core/sync/mutex.d
  druntime/src/core/sync/rwmutex.d
  druntime/src/core/sync/semaphore.d
  druntime/src/core/thread/fiber/package.d
  druntime/src/core/thread/osthread.d
  druntime/src/core/thread/types.d
  druntime/src/core/time.d
  druntime/src/etc/linux/memoryerror.d
  druntime/src/rt/cover.d
  druntime/src/rt/monitor_.d
  druntime/src/rt/sections_darwin_64.d
  druntime/src/rt/sections_elf_shared.d
  druntime/src/rt/sections_osx_x86.d
  druntime/src/rt/sections_osx_x86_64.d
  druntime/test/shared/src/load.d
  druntime/test/thread/src/external_threads.d
  druntime/test/thread/src/fiber_guard_page.d
Labels: Merge:auto-merge

#20650 Make dt_t.nbytes accept a slice instead of size+pointer
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/dout.d
  compiler/src/dmd/backend/dt.d
  compiler/src/dmd/backend/pdata.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/objc_glue.d
  compiler/src/dmd/todt.d
  compiler/src/dmd/toobj.d
Labels: Merge:auto-merge, Severity:Refactoring, Compiler:Backend

#20656 backend.cc: Remove dead code
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/symbol.d
Labels: Merge:auto-merge, Severity:Refactoring, Compiler:Backend

#20655 Make DataBuilder.abytes accept a slice instead of size, ptr
  compiler/src/dmd/backend/dt.d
  compiler/src/dmd/todt.d
Labels: Merge:auto-merge, Severity:Refactoring, Compiler:Backend

#20657 Use const when possible
  compiler/src/dmd/compiler.d
  compiler/src/dmd/cpreprocess.d
  compiler/src/dmd/inline.d
  compiler/src/dmd/intrange.d
Labels: Review:Trivial, Merge:auto-merge, Severity:Refactoring

#20663 Place the `version(linux):` in `core.sys.linux.sys.procfs` higher.
  druntime/src/core/sys/linux/sys/procfs.d
Labels: Merge:auto-merge

#20664 Fix "Casting class references to void* should be `@safe`"
  compiler/src/dmd/safe.d
  compiler/test/runnable/testsafe.d
Labels: Merge:auto-merge

#20666 Remove some more bugzilla links
  README.md
  compiler/src/dmd/mangle/cpp.d
  compiler/src/dmd/mars.d
  compiler/src/dmd/ob.d
Labels: Review:Trivial, Merge:auto-merge, Severity:documentation

#20577 Make subtracting pointers of different types an error
  changelog/dmd.deprecation-pointer-subtract.dd
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/test11006.d
Labels: Severity:Deprecation -> Error, Review:Ready To Merge

#20676 Remove redundant else
  compiler/src/dmd/console.d
  compiler/src/dmd/dtoh.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/pragmasem.d
  compiler/src/dmd/templateparamsem.d
  compiler/src/dmd/traits.d
  compiler/src/dmd/typesem.d
Labels: Merge:auto-merge

#20677 Fix missing backtick in escape.d error message
  compiler/src/dmd/escape.d
  compiler/test/fail_compilation/retscope2.d
  compiler/test/fail_compilation/retscope3.d
  compiler/test/fail_compilation/retscope6.d
  compiler/test/fail_compilation/test18282.d
Labels: Review:Trivial, Merge:auto-merge

#20634 build default move constructors
  compiler/src/dmd/clone.d
  compiler/src/dmd/dstruct.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/func.d
  compiler/src/dmd/funcsem.d
  compiler/test/compilable/copyCtor2.d
  compiler/test/fail_compilation/failCopyCtor2.d
  compiler/test/runnable/rvalue1.d
Labels: Review:WIP

#20679 Fix ambiguous type deduction around hex strings
  compiler/src/dmd/dcast.d
  compiler/test/runnable/literal.d
Labels: Merge:auto-merge

#20680 Make `likely` and `unlikely` templates
  druntime/src/core/builtins.d
Labels: Merge:auto-merge

#20681 dmd: Fix interface for C++ backends
  compiler/src/dmd/common/charactertables.d
  compiler/src/dmd/common/charactertables.h
  compiler/src/dmd/cxxfrontend.d
  compiler/src/dmd/errors.d
Labels: Merge:auto-merge, Compiler:C++ Interface

#20682 core.builtins: Fix return value of likely/unlikely
  druntime/src/core/builtins.d
Labels: Compiler:GDC, Compiler:LDC, Merge:auto-merge, Druntime

#20665 Remove 'samples' folder, move them to undeaD
  Makefile
  README.md
  changelog/dmd.remove-samples.dd
  compiler/samples/.gitignore
  compiler/samples/all.sh
  compiler/samples/build.bat
  compiler/samples/chello.d
  compiler/samples/clean.bat
  compiler/samples/d2html.d
  compiler/samples/d2html.kwd
  compiler/samples/dclient.d
  compiler/samples/dhry.d
  compiler/samples/dserver.d
  compiler/samples/dserver64.def
  compiler/samples/hello.d
  compiler/samples/htmlget.d
  compiler/samples/listener.d
  compiler/samples/mydll/build.bat
  compiler/samples/mydll/dll.d
  compiler/samples/mydll/mydll.d
  compiler/samples/mydll/mydll.def
  compiler/samples/mydll/mydll.di
  compiler/samples/mydll/test.d
  compiler/samples/pi.d
  compiler/samples/posix.mak
  compiler/samples/sieve.d
  compiler/samples/wc.d
  compiler/samples/wc2.d
  compiler/samples/win32.mak
  compiler/samples/winsamp.d
  compiler/samples/winsamp.def
Labels: Merge:72h no objection -> merge

#20687 Use const when possible
  compiler/src/dmd/common/blake3.d
  compiler/src/dmd/dinifile.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/glue.d
Labels: Merge:auto-merge

#20689 Fix #20688 SO_REUSEPORT not defined
  druntime/src/core/sys/posix/sys/socket.d
Labels: Merge:auto-merge

#20695 Fix bus error in custom_gc test
  druntime/test/init_fini/src/custom_gc.d
Labels: Merge:auto-merge, Druntime

#20697 Remove redundant else
  compiler/src/dmd/backend/elpicpie.d
  compiler/src/dmd/backend/gloop.d
  compiler/src/dmd/backend/gother.d
  compiler/src/dmd/backend/x86/cgcod.d
  compiler/src/dmd/backend/x86/cod1.d
  compiler/src/dmd/ctfeexpr.d
  compiler/src/dmd/dcast.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/pragmasem.d
  druntime/src/core/internal/gc/os.d
Labels: Merge:auto-merge

#20699 fix #20516 ImportC undefined identifier _Float16
  druntime/src/importc.h
Labels: Feature:ImportC

#20702 globals.h: Add missing C++ constructors for ImportPathInfo
  compiler/src/dmd/globals.h
  compiler/src/tests/cxxfrontend.cc
Labels: Compiler:GDC, Merge:auto-merge, Compiler:C++ Interface

#20698 Move all array and finalizer functionality into the GC
  druntime/src/core/internal/array/construction.d
  druntime/src/core/internal/array/utils.d
  druntime/src/core/internal/gc/blockmeta.d
  druntime/src/core/internal/gc/impl/conservative/gc.d
  druntime/src/rt/lifetime.d
  druntime/test/exceptions/src/assert_fail.d
Labels: Druntime:GC

#20708 Add fieldwise to Previews
  compiler/src/dmd/dscope.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/opover.d
Labels: Merge:auto-merge, Severity:Refactoring

#20712 Fix format string injection in safe errors
  compiler/src/dmd/safe.d
Labels: Merge:auto-merge

#20713 Remove debug() / version() integers
  changelog/dmd.deprecation-version-debug-number.dd
  compiler/src/dmd/mars.d
  compiler/src/dmd/parse.d
  compiler/test/fail_compilation/diag11198.d
  compiler/test/fail_compilation/diag_debug_conditional.d
  compiler/test/fail_compilation/test13786.d
  compiler/test/runnable/lexer.d
Labels: Severity:Deprecation -> Error

#20714 Store messages directly in AttributeViolation
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/funcsem.d
  compiler/src/dmd/nogc.d
  compiler/src/dmd/safe.d
Labels: Severity:Refactoring

#20716 Use variadic arguments for AttributeViolation format string
  compiler/src/dmd/escape.d
  compiler/src/dmd/func.d
  compiler/src/dmd/funcsem.d
  compiler/src/dmd/nogc.d
  compiler/src/dmd/safe.d
  compiler/src/dmd/typesem.d
Labels: Merge:auto-merge, Severity:Refactoring

#20710 Fix build on i686, arm64 and x86_64+32b multilib for Darwin.
  druntime/src/core/thread/osthread.d
Labels: Merge:auto-merge-squash, Arch:Aarch64, OS:Mac OS, Druntime, Arch:powerpc

#20718 backend: Make FL a D enum
  compiler/src/dmd/backend/arm/cod1.d
  compiler/src/dmd/backend/arm/cod2.d
  compiler/src/dmd/backend/arm/cod3.d
  compiler/src/dmd/backend/arm/cod4.d
  compiler/src/dmd/backend/blockopt.d
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cg.d
  compiler/src/dmd/backend/cgelem.d
  compiler/src/dmd/backend/cgen.d
  compiler/src/dmd/backend/cgsched.d
  compiler/src/dmd/backend/code.d
  compiler/src/dmd/backend/codebuilder.d
  compiler/src/dmd/backend/cv8.d
  compiler/src/dmd/backend/dcgcv.d
  compiler/src/dmd/backend/debugprint.d
  compiler/src/dmd/backend/dout.d
  compiler/src/dmd/backend/drtlsym.d
  compiler/src/dmd/backend/dt.d
  compiler/src/dmd/backend/dwarfdbginf.d
  compiler/src/dmd/backend/ee.d
  compiler/src/dmd/backend/elem.d
  compiler/src/dmd/backend/elfobj.d
  compiler/src/dmd/backend/elpicpie.d
  compiler/src/dmd/backend/global.d
  compiler/src/dmd/backend/gloop.d
  compiler/src/dmd/backend/inliner.d
  compiler/src/dmd/backend/machobj.d
  compiler/src/dmd/backend/mscoffobj.d
  compiler/src/dmd/backend/symbol.d
  compiler/src/dmd/backend/x86/cg87.d
  compiler/src/dmd/backend/x86/cgcod.d
  compiler/src/dmd/backend/x86/cgreg.d
  compiler/src/dmd/backend/x86/cgxmm.d
  compiler/src/dmd/backend/x86/cod1.d
  compiler/src/dmd/backend/x86/cod2.d
  compiler/src/dmd/backend/x86/cod3.d
  compiler/src/dmd/backend/x86/cod4.d
  compiler/src/dmd/backend/x86/code_x86.d
  compiler/src/dmd/backend/x86/nteh.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/iasmdmd.d
  compiler/src/dmd/objc_glue.d
  compiler/src/dmd/s2ir.d
  compiler/src/dmd/tocsym.d
  compiler/src/dmd/toobj.d
Labels: Merge:auto-merge, Severity:Refactoring, Compiler:Backend

#20720 Fix bypassing nothrow in debug statements
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/statementsem.d
  compiler/test/compilable/debug_statement_attributes.d
  compiler/test/compilable/test24017.d
Labels: Merge:auto-merge

#20725 Use selective imports when importing from `core.stdc` in `core`
  druntime/src/core/gc/config.d
  druntime/src/core/int128.d
  druntime/src/core/lifetime.d
  druntime/src/core/memory.d
  druntime/src/core/runtime.d
  druntime/src/core/sync/condition.d
  druntime/src/core/sync/semaphore.d
  druntime/src/core/thread/osthread.d
  druntime/src/core/time.d
Labels: Merge:auto-merge, Severity:Refactoring

#20724 backend: Make BC a D enum
  compiler/src/dmd/backend/arm/cod3.d
  compiler/src/dmd/backend/blockopt.d
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/cgcs.d
  compiler/src/dmd/backend/cgsched.d
  compiler/src/dmd/backend/code.d
  compiler/src/dmd/backend/debugprint.d
  compiler/src/dmd/backend/dout.d
  compiler/src/dmd/backend/dwarfeh.d
  compiler/src/dmd/backend/eh.d
  compiler/src/dmd/backend/gdag.d
  compiler/src/dmd/backend/gflow.d
  compiler/src/dmd/backend/gloop.d
  compiler/src/dmd/backend/go.d
  compiler/src/dmd/backend/gother.d
  compiler/src/dmd/backend/gsroa.d
  compiler/src/dmd/backend/inliner.d
  compiler/src/dmd/backend/x86/cgcod.d
  compiler/src/dmd/backend/x86/cgreg.d
  compiler/src/dmd/backend/x86/cod3.d
  compiler/src/dmd/backend/x86/cod5.d
  compiler/src/dmd/backend/x86/nteh.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/ob.d
  compiler/src/dmd/s2ir.d
Labels: Severity:Refactoring, Merge:auto-merge-squash, Compiler:Backend

#20731 Don't reference DMD-specific flags when IN_GCC
  compiler/src/dmd/safe.d
Labels: Compiler:GDC, Diagnostic Messages

#20732 dcast: Don't pass format string over varargs
  compiler/src/dmd/dcast.d
Labels: Diagnostic Messages, Severity:Refactoring

#20722 Remove usage of obsolete `_fdToHandle` in rt/dmain2.d
  druntime/src/rt/dmain2.d
Labels: Merge:auto-merge

#20643 Add an assert-based segfault handler to `etc.linux.memoryerror`
  changelog/druntime.segfault-message.dd
  druntime/src/etc/linux/memoryerror.d
  druntime/src/rt/dmain2.d
  druntime/test/exceptions/Makefile
  druntime/test/exceptions/src/memoryerror_null_call.d
  druntime/test/exceptions/src/memoryerror_null_read.d
  druntime/test/exceptions/src/memoryerror_null_write.d
  druntime/test/exceptions/src/memoryerror_stackoverflow.d
Labels: Druntime

#20723 Use selective imports when importing from `core.stdc` in `core.internal`
  druntime/src/core/internal/abort.d
  druntime/src/core/internal/array/casting.d
  druntime/src/core/internal/array/construction.d
  druntime/src/core/internal/array/duplication.d
  druntime/src/core/internal/array/utils.d
  druntime/src/core/internal/backtrace/dwarf.d
  druntime/src/core/internal/backtrace/handler.d
  druntime/src/core/internal/backtrace/libunwind.d
  druntime/src/core/internal/backtrace/unwind.d
  druntime/src/core/internal/elf/dl.d
  druntime/src/core/internal/gc/bits.d
  druntime/src/core/internal/gc/blkcache.d
  druntime/src/core/internal/gc/impl/conservative/gc.d
  druntime/src/core/internal/gc/os.d
  druntime/src/core/internal/gc/pooltable.d
  druntime/src/core/internal/parseoptions.d
  druntime/src/core/internal/qsort.d
  druntime/src/core/internal/util/array.d
Labels: Merge:auto-merge

#20737 druntime: Add version(GNU) definitions of c_long and c_ulong
  druntime/src/core/stdc/config.d
Labels: Compiler:GDC, Merge:auto-merge, Druntime

#20734 druntime: Add version(GNU) imports to rt.deh and sections modules
  druntime/src/rt/deh.d
  druntime/src/rt/sections.d
Labels: Compiler:GDC, Merge:auto-merge, Druntime

#20738 Add test cases for static arrays initialization with hex string
  compiler/test/fail_compilation/hexstring.d
Labels: Merge:auto-merge

#20736 druntime: Update GNU implementation of callWithStackShell
  druntime/src/core/thread/osthread.d
Labels: Compiler:GDC, Merge:auto-merge, Druntime

#20735 druntime: Add GNU_InlineAsm implementations
  druntime/src/core/sys/windows/dll.d
  druntime/src/core/sys/windows/threadaux.d
  druntime/src/core/thread/osthread.d
  druntime/src/rt/dmain2.d
Labels: Compiler:GDC, Merge:auto-merge, Druntime

#20696 Disallow initializing fields with themself
  changelog/dmd.deprecation-noop-assignment.dd
  compiler/src/dmd/expressionsem.d
  compiler/test/compilable/interpret3.d
  compiler/test/compilable/test22510.d
  compiler/test/fail_compilation/ctor_self_assignment.d
Labels: Severity:Deprecation

#20746 Remove more D1 operator code
  compiler/src/dmd/opover.d
Labels: Merge:auto-merge, Severity:Refactoring

#20748 opover.d: remove goto, reduce indentation
  compiler/src/dmd/opover.d
Labels: Severity:Refactoring

#20752 Allow failure on FreeBSD jobs
  .github/workflows/main.yml
Labels: Infrastructure:Continuous Integration

#20751 Remove redundant else
  compiler/src/dmd/compiler.d
  compiler/src/dmd/ctfeexpr.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/func.d
  compiler/src/dmd/iasmdmd.d
  compiler/src/dmd/mangle/cpp.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/objc.d
  compiler/src/dmd/objc_glue.d
  compiler/src/dmd/target.d
Labels: Severity:Refactoring

#20749 Move class __cmp lowering to opover.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/opover.d
Labels: Severity:Refactoring

#20750 opover.d: Separate and simplify BinExp/AssignExp cases
  compiler/src/dmd/opover.d
Labels: Severity:Refactoring

#20754 Separate visit() functions from op_overload
  compiler/src/dmd/clone.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/opover.d
Labels: Merge:auto-merge, Severity:Refactoring

#20755 Remove redundant BinExp semantic type check
  compiler/src/dmd/expressionsem.d
Labels: Severity:Refactoring

#20757 Perform binSemanticProp in opOverloadBinary
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/opover.d
Labels: Severity:Refactoring

#20761 some reorganizing of instruction patterns
  compiler/src/dmd/backend/arm/instr.d
Labels: Severity:Refactoring, Severity:documentation, Arch:Aarch64

#20759 opover: Deduplicate binary overload selection code
  compiler/src/dmd/opover.d
Labels: Merge:auto-merge, Severity:Refactoring

#20758 druntime: remove libunwind dependency and make execinfo optional (LDC upstream)
  druntime/mak/COPY
  druntime/mak/DOCS
  druntime/mak/SRCS
  druntime/src/core/internal/backtrace/dwarf.d
  druntime/src/core/internal/backtrace/handler.d
  druntime/src/core/internal/backtrace/libunwind.d
  druntime/src/core/internal/backtrace/unwind.d
  druntime/src/core/runtime.d
Labels: Druntime

#20765 opover.d: simplify opOverloadAssign and search_function
  compiler/src/dmd/opover.d
Labels: Severity:Refactoring

#20771 Rename Id.index to Id.opIndex etc.
  compiler/src/dmd/clone.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/src/dmd/initsem.d
  compiler/src/dmd/mangle/cpp.d
  compiler/src/dmd/mangle/cppwin.d
  compiler/src/dmd/mustuse.d
  compiler/src/dmd/opover.d
  compiler/src/dmd/semantic3.d
  compiler/src/dmd/typesem.d
Labels: Merge:auto-merge, Severity:Refactoring

#20772 Remove references to D1 `opDot`
  compiler/src/dmd/frontend.h
  compiler/src/dmd/id.d
  compiler/src/dmd/typesem.d
  compiler/test/fail_compilation/deprecateopdot.d
Labels: Merge:auto-merge

#20773 backend: remove unused C++ enums
  compiler/src/dmd/backend/cc.d
  compiler/src/dmd/backend/dout.d
Labels: Severity:Refactoring, Compiler:Backend

#20774 Remove BinExp.att fields
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/opover.d
Labels: Severity:Refactoring

#20775 disassemble cnt, fmov and uaddlv
  compiler/src/dmd/backend/arm/disasmarm.d
Labels: Arch:Aarch64

#20776 disassembler addv instruction
  compiler/src/dmd/backend/arm/disasmarm.d
Labels: Merge:auto-merge, Arch:Aarch64

#20778 Fix astbase.d deprecation warnings
  compiler/src/dmd/astbase.d
Labels: Review:Trivial

#20779 Reduce size of StructLiteralExp
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/frontend.h
Labels: Severity:Refactoring

#20782 Port ntdef macros `NT_INFORMATION`, `NT_WARNING` and `NT_ERROR`
  druntime/src/core/sys/windows/ntdef.d
Labels: Severity:Enhancement, Merge:auto-merge, OS:Windows, Druntime

#20784 add more instructions to INSTR
  compiler/src/dmd/backend/arm/instr.d
Labels: Merge:auto-merge, Arch:Aarch64

#20785 Refactor use of Loc/SourceLoc
  compiler/src/dmd/doc.d
  compiler/src/dmd/errors.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.d
  compiler/src/dmd/iasmdmd.d
  compiler/src/dmd/json.d
  compiler/src/dmd/location.d
  compiler/src/dmd/parse.d
  compiler/src/dmd/s2ir.d
  compiler/src/dmd/tocsym.d
  compiler/test/dub_package/retrieve_scope.d
  compiler/test/unit/frontend.d
  compiler/test/unit/interfaces/check_implementations_20861.d
  compiler/test/unit/lexer/diagnostic_reporter.d
  compiler/test/unit/lexer/lexer_dmdlib.d
  compiler/test/unit/objc/protocols/diagnostic_messages.d
  compiler/test/unit/objc/protocols/optional_methods.d
  compiler/test/unit/parser/diagnostic_reporter.d
  compiler/test/unit/support.d
Labels: Merge:auto-merge, Severity:Refactoring

#20787 implement cdpopcnt for AArch64
  compiler/src/dmd/backend/arm/cod4.d
  compiler/src/dmd/backend/arm/disasmarm.d
  compiler/src/dmd/target.d
  druntime/src/core/bitop.d
Labels: Compiler:Backend, Arch:Aarch64

#20789 Improve opBinary error messages
  changelog/dmd.error-messages.dd
  compiler/src/dmd/dcast.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/opover.d
  compiler/test/fail_compilation/dep_d1_ops.d
  compiler/test/fail_compilation/diag12063.d
  compiler/test/fail_compilation/diag16499.d
  compiler/test/fail_compilation/fail297.d
  compiler/test/fail_compilation/fail3.d
  compiler/test/fail_compilation/test22329.d
Labels: Diagnostic Messages

#20790 add __builtin__popcount() for ImportC
  druntime/src/__importc_builtins.di
Labels: Review:Easy Review, Arch:Aarch64

#20792 opover.d: refactor common DotTemplateInstanceExp creation logic
  compiler/src/dmd/opover.d
Labels: Merge:auto-merge, Severity:Refactoring

#20791 Improve opIndex/opSlice error messages
  changelog/dmd.error-messages.dd
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/opover.d
  compiler/test/fail_compilation/fail20616.d
  compiler/test/fail_compilation/fail_arrayexp.d
  compiler/test/fail_compilation/fail_opover.d
Labels: Merge:auto-merge, Diagnostic Messages

#20794 opover.d: Refactor pattern matching with isXXX
  compiler/src/dmd/mtype.d
  compiler/src/dmd/opover.d
Labels: Merge:auto-merge, Severity:Refactoring

#20796 expressionsem.d: Combine redundant branches
  compiler/src/dmd/expressionsem.d
Labels: Merge:auto-merge, Severity:Refactoring

#20795 Check array types with new `isStaticOrDynamicArray` function
  compiler/src/dmd/argtypes_aarch64.d
  compiler/src/dmd/arrayop.d
  compiler/src/dmd/cparse.d
  compiler/src/dmd/ctfeexpr.d
  compiler/src/dmd/dcast.d
  compiler/src/dmd/dinterpret.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/escape.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/importc.d
  compiler/src/dmd/initsem.d
  compiler/src/dmd/inline.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/ob.d
  compiler/src/dmd/opover.d
  compiler/src/dmd/todt.d
Labels: Severity:Refactoring

#20797 Move Expression.checkValue to expressionsem.d
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
Labels: Merge:auto-merge, Severity:Refactoring

#20799 Replace C pointer syntax with D
  compiler/src/dmd/access.d
  compiler/src/dmd/astbase.d
  compiler/src/dmd/compiler.d
  compiler/src/dmd/cond.d
  compiler/src/dmd/console.d
  compiler/src/dmd/cxxfrontend.d
  compiler/src/dmd/dcast.d
  compiler/src/dmd/doc.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/func.d
  compiler/src/dmd/glue.d
  compiler/src/dmd/iasm.d
  compiler/src/dmd/iasmdmd.d
  compiler/src/dmd/iasmgcc.d
  compiler/src/dmd/intrange.d
  compiler/src/dmd/mtype.d
  compiler/src/dmd/s2ir.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/templatesem.d
  compiler/src/dmd/tocsym.d
  compiler/src/dmd/tocvdebug.d
  compiler/src/dmd/todt.d
  compiler/src/dmd/toir.d
  compiler/src/dmd/toobj.d
  compiler/src/dmd/typesem.d
Labels: Merge:auto-merge, Severity:Refactoring

#20793 implement cdnot() for AArch64
  compiler/src/dmd/backend/arm/cod2.d
  compiler/src/dmd/backend/arm/disasmarm.d
  compiler/src/dmd/backend/arm/instr.d
  compiler/src/dmd/backend/x86/cod2.d
  compiler/src/dmd/backend/x86/cod3.d
Labels: Merge:auto-merge, Compiler:Backend, Arch:Aarch64

#20798 Fix #20763 - Inconsistent handling of type + value in typeof expressions
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/typesem.d
  compiler/test/fail_compilation/b17285.d
  compiler/test/fail_compilation/ice9545.d
  compiler/test/fail_compilation/test20763.d
Labels: Merge:auto-merge, Severity:Deprecation

#20800 Improve opOpAssign error messages
  changelog/dmd.error-messages.dd
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/opover.d
  compiler/test/fail_compilation/dep_d1_ops.d
  compiler/test/fail_compilation/diag13320.d
  compiler/test/fail_compilation/fail18985.d
  compiler/test/fail_compilation/fail3672.d
Labels: Diagnostic Messages

#20801 Improve error messages for `opUnary`
  changelog/dmd.error-messages.dd
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/opover.d
  compiler/test/fail_compilation/dep_d1_ops.d
  compiler/test/fail_compilation/operator_undefined.d
Labels: Merge:auto-merge

#20802 Remove dead debug/version level logic
  compiler/src/dmd/astbase.d
  compiler/src/dmd/cond.d
  compiler/src/dmd/cond.h
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/dversion.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.d
  compiler/src/dmd/globals.h
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/mars.d
  compiler/src/dmd/module.h
  compiler/src/dmd/parse.d
  compiler/src/dmd/version.h
Labels: Severity:Refactoring

#20803 Don't expose internal names in errors
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/identifier.d
  compiler/test/compilable/extra-files/json.json
  compiler/test/fail_compilation/fail10964.d
  compiler/test/fail_compilation/fail10968.d
  compiler/test/fail_compilation/fail18143.d
  compiler/test/fail_compilation/fail4421.d
  compiler/test/fail_compilation/fail6107.d
  compiler/test/fail_compilation/fail7848.d
  compiler/test/fail_compilation/ice12902.d
Labels: Diagnostic Messages

#20804 Move toChars overrides to hdrgen.d
  compiler/src/dmd/attrib.d
  compiler/src/dmd/attrib.h
  compiler/src/dmd/cond.d
  compiler/src/dmd/ctfe.h
  compiler/src/dmd/declaration.d
  compiler/src/dmd/declaration.h
  compiler/src/dmd/doc.d
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/dsymbol.h
  compiler/src/dmd/dtemplate.d
  compiler/src/dmd/expression.d
  compiler/src/dmd/expression.h
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/dmd/hdrgen.d
  compiler/src/dmd/identifier.d
  compiler/src/dmd/template.h
  compiler/test/compilable/extra-files/json.json
Labels: Severity:Refactoring

#20807 Refactor opover.d to improve style
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/opover.d
Labels: Severity:Refactoring

#20806 Improve error messages for missing opCmp / opEquals
  compiler/src/dmd/errors.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/opover.d
  compiler/test/fail_compilation/bug9631.d
  compiler/test/fail_compilation/diag12063.d
  compiler/test/fail_compilation/fail20.d
  compiler/test/fail_compilation/ice10624.d
Labels: Diagnostic Messages

#20808 Remove reference to `_d_arrayassign` in errors
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/fail10968.d
Labels: Merge:auto-merge, Diagnostic Messages

#20777 Shrink Loc from 12 to 4 bytes
  compiler/src/dmd/cparse.d
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/globals.h
  compiler/src/dmd/identifier.d
  compiler/src/dmd/lexer.d
  compiler/src/dmd/location.d
  compiler/src/dmd/mars.d
  compiler/src/dmd/statementsem.d
  compiler/src/dmd/typesem.d
  compiler/src/tests/cxxfrontend.cc
Labels: Severity:Refactoring
