Repository dlang/dmd, pull requests merged in 2025-07, with the labels that each got.

#21501 fix stack adjustment for large values
  compiler/src/dmd/backend/arm/cod2.d
  compiler/src/dmd/backend/arm/instr.d
  compiler/src/dmd/backend/x86/cod3.d
Labels: Compiler:Backend, Arch:Aarch64

#21506 handle large stack frame prolog/epilog
  compiler/src/dmd/backend/arm/cod3.d
  compiler/src/dmd/backend/x86/cod3.d
Labels: Compiler:Backend, Arch:Aarch64

#21493 fix #21478: Ref parameter overload not called when struct implements copy constructor
  compiler/src/dmd/typesem.d
  compiler/test/runnable/test21478a.d
  compiler/test/runnable/test21478b.d
Labels: Severity:Bug Fix

#21508 cdmemset() for AArch64
  compiler/src/dmd/backend/arm/cod2.d
  compiler/src/dmd/backend/arm/cod3.d
  compiler/src/dmd/backend/arm/disasmarm.d
  compiler/src/dmd/backend/arm/instr.d
  compiler/src/dmd/backend/x86/cod2.d
Labels: Compiler:Backend, Arch:Aarch64

#21509 improved cdmemset()
  compiler/src/dmd/backend/arm/cod1.d
  compiler/src/dmd/backend/arm/cod2.d
Labels: Compiler:Backend, Arch:Aarch64

#21428 fix #21426: Windows GC only wakes up one thread when doing parallel scanning
  druntime/src/core/internal/gc/impl/conservative/gc.d
Labels: Merge:auto-merge

#21517 work on various offset schemes in instr encoding
  compiler/src/dmd/backend/arm/cod1.d
  compiler/src/dmd/backend/arm/cod3.d
  compiler/src/dmd/backend/arm/cod4.d
  compiler/src/dmd/backend/arm/instr.d
Labels: Compiler:Backend, Arch:Aarch64

#21148 fix #21142 seg fault on floating point code
  compiler/src/dmd/backend/x86/cgxmm.d
  compiler/test/runnable/mars1.d
Labels: Compiler:Backend, Arch:x86, Arch:x86_64, Severity:Crash, Bug Fix

#21529 Remove some unused `dmd.gluelayer` imports
  compiler/src/dmd/declaration.d
  compiler/src/dmd/funcsem.d
Labels: Review:Trivial, Severity:Refactoring

#21536 [aggregate.d] move `searchCtor` to `expressionsem.d`
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/expressionsem.d
Labels: Severity:Refactoring

#21538 [cond.d] restrict semantic imports
  compiler/src/dmd/cond.d
Labels: Review:Trivial, Severity:Refactoring

#21532 [dsymbol.d] remove dependance on glue layer
  compiler/src/dmd/dsymbol.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/tocsym.d
  compiler/src/dmd/todt.d
  compiler/src/dmd/toir.d
  compiler/src/dmd/toobj.d
Labels: Severity:Refactoring

#21535 move `loadModuleFromLibrary` to `dsymbolsem.d`
  compiler/src/dmd/dmodule.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/expressionsem.d
  compiler/src/dmd/typesem.d
Labels: Severity:Refactoring

#21534 [func.d] remove dependance on glue layer
  compiler/src/dmd/e2ir.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/func.d
  compiler/src/tests/cxxfrontend.cc
Labels: Severity:Refactoring

#21541 [aggregate.d] move `apply` to `dsymbolsemd.d`
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/tocvdebug.d
Labels: Severity:Refactoring

#21559 support 2*REGSIZE in cdmemsetn()
  compiler/src/dmd/backend/arm/cod2.d
Labels: Compiler:Backend, Arch:Aarch64

#21561 implement cdstreq()
  compiler/src/dmd/backend/arm/cod2.d
  compiler/src/dmd/backend/arm/disasmarm.d
  compiler/src/dmd/backend/arm/instr.d
Labels: Compiler:Backend, Arch:Aarch64

#21566 Add suggested fix to error message when casting struct to bool
  compiler/src/dmd/expressionsem.d
  compiler/test/fail_compilation/diag13320.d
Labels: Diagnostic Messages

#21571 [ob.d] make most of it private
  compiler/src/dmd/ob.d
Labels: Review:Trivial, Severity:Refactoring

#21528 Use AA for `cpp_type_info_ptr_sym` cache
  compiler/src/dmd/aggregate.h
  compiler/src/dmd/dclass.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/tocsym.d
Labels: Severity:Refactoring

#21578 fix `frontend.h`
  compiler/src/dmd/frontend.h
Labels: Review:Trivial

#21580 [dstruct.d] remove some unused semantic imports
  compiler/src/dmd/dstruct.d
Labels: Review:Trivial

#21591 [funcsem.d] make some function `private` and restrict import
  compiler/src/dmd/dstruct.d
  compiler/src/dmd/funcsem.d
Labels: Review:Trivial

#21603 need 2 instructions for offsets larger than 0xFFF
  compiler/src/dmd/backend/arm/cod3.d
  compiler/src/dmd/backend/arm/disasmarm.d
  compiler/src/dmd/backend/codebuilder.d
Labels: Compiler:Backend, Arch:Aarch64

#21606 fix #21605 test suite null deref in bug19652.d
  compiler/test/runnable/bug19652.d
Labels: Review:Trivial

#21570 [dscope.d] compress some flags
  compiler/src/dmd/aggregate.d
  compiler/src/dmd/attrib.d
  compiler/src/dmd/common/bitfields.d
  compiler/src/dmd/dscope.d
  compiler/src/dmd/dsymbolsem.d
  compiler/src/dmd/frontend.h
  compiler/src/dmd/scope.h
  compiler/src/dmd/semantic3.d
Labels: Severity:Refactoring

#21609 implement code gen for fabs()
  compiler/src/dmd/backend/arm/cod2.d
  compiler/src/dmd/backend/arm/cod3.d
  compiler/src/dmd/backend/arm/instr.d
Labels: Compiler:Backend, Arch:Aarch64

#21616 Fix incorrect sign for expanding arrays into subsequent pages
  druntime/src/core/internal/gc/impl/conservative/gc.d
Labels: Merge:auto-merge

#21621 fix null deref in test suite
  compiler/test/compilable/parens_inc.d
Labels: Review:Trivial

#21626 fix the BP to SP conversion wrong
  compiler/src/dmd/backend/arm/cod3.d
Labels: Compiler:Backend, Arch:Aarch64
